### PR TITLE
Add TE Connectivity 2041021 SD card connector

### PR DESCRIPTION
**Pull request by evanshultz**
This is a fixed version of https://github.com/KiCad/Connectors_TE-Connectivity.pretty/pull/2#event-1363406776, which was abandoned. All fixed requested by @poeschlr have been made.

Datasheet: http://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F2041021%7FB%7Fpdf%7FEnglish%7FENG_CD_2041021_B_C_2041021_B.pdf%7F2041021-4

Image:
image

Note: I did not see a dimension or angle for the sloped area on the right side, so I made it 45 degrees.

The pin numbers should allow mating with an existing symbol:
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ x ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ x ] An example screenshot image is very helpful 
- [ x ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ x ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
@jkriege2 @poeschlr 
Can I get a review, please?

**Comment by poeschlr** [comment]
The 3d settings are not right. (it has offset different to 0) I fear we have a bug in our testscripts as these do not seem to catch this.

The courtyard clearance towards the top is not quite right:
sd

**Comment by evanshultz** [comment]
@poeschlr 
Thanks! Both items are fixed.

**Comment by poeschlr** [comment]
Looks good. Thanks

**Pull request merged**
