### PR TITLE
Add RGB Led footprint for ASMB-MTB0-0A3A2

### PR DESCRIPTION
**Pull request by aurabindo**
Signed-off-by: Aurabindo J <mail@aurabindo.in>

Add RGB LED footprints for ASMB-MTB{0,1}-0A3A2
Datasheets: 
https://docs.broadcom.com/docs/AV02-4186EN
https://docs.broadcom.com/docs/AV02-4194EN
avago_plcc4

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for your contribution. Please change a few minor things:
1. please make the style of the pin1-marker like in other symbols in this lib: 
2018-01-20 18_03_21-library browser led_smd d__kicad_kicad-footprints_led_smd pretty
2. In the filename you should give the BODY-size, i.e. 3.2x2.8
3. Please replace the `-` behind Avagon by an underscor `_`

**Comment by aurabindo** [comment]
avago_led

**Comment by aurabindo** [comment]
@jkriege2 Should the numbering also match the style you shown ? (The direction the pin1 marking should extend to identify pin2)

**Comment by jkriege2** [comment]
This is fine with me now ... the numbering should follow the one used by the manufacturer (this is a manufacturer-specific symbol!)

**Pull request merged**
