### PR TITLE
Add LTC-4627Jx 7-segemnt displays

### PR DESCRIPTION
**Pull request by Schlumpf**
Used for symbols: LTC-4627JD, LTC-4627JD-01, LTC-4627JF, LTC-4627JG, LTC-4627JR LTC-4627JS

Datasheets:
 - http://optoelectronics.liteon.com/upload/download/DS30-2001-393/C4627JG.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2008-0116/LTC-4627JD-01.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2000-192/C4627JF.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2001-393/C4627JG.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2000-185/LTC-4627JR.pdf
 - http://optoelectronics.liteon.com/upload/download/DS30-2000-186/LTC-4627JS.pdf

image image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- ~Give a reason behind any intentional library convention rule violation.~

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @Schlumpf , i think fab layer triangle for pin 1 needs to change to 1mm chamfer on the upper left corner.
Thank you for your contribution.

**Comment by myfreescalewebpage** [comment]
@Schlumpf starting the review of this footprint:

- [ ] F.Fab layer: the footprint is too long, you have 40.8mm while the datasheet indicate 40.18mm
- [ ] F.SilkS layer: clearance with F.Fab should be 0.11mm

Else no comment to do
Joel

**Comment by myfreescalewebpage** [comment]
@Schlumpf ping

**Comment by Schlumpf** [comment]
Ooops, I fixed the body size now.
Why should be an offset between Silk and Fab? I did not find it in KLC...

**Comment by chschlue** [comment]
[Silk must be fully visible after assembly.](https://kicad-pcb.org/libraries/klc/F5.1/) Therefore silk must be outside fab.

**Comment by Schlumpf** [comment]
@chschlue I know this rule, but apparently I interpreted it differently.

My thoughts:
The Fab layer describes the nominal size of the component. Thus, the component ends at the center of the fab layer line. So that the complete silk line is visible, the inner edge of the silk line must not be closer to the component than the center of the fab line.

Am I wrong? Where do the 0.11mm come from?

**Comment by chschlue** [comment]
0.11mm isn't fixed.
Your thoughts are correct, we just usually add a bit of allowance.

**Comment by myfreescalewebpage** [comment]
0.11mm is the offset value used when using the generator to generate connectors, etc etc. However, there is no strong value, but I always recommend this one for consistency across the library.
Please ping when the above modifications are done.

**Comment by Schlumpf** [comment]
@myfreescalewebpage OK, done

This recommendation should mentioned in KLC. Until now, I used my explanations above for my FPs.

**Comment by myfreescalewebpage** [comment]
So much to do with klc ;)
Thanks the footprint is great for me, merging.

**Pull request merged**
