### PR TITLE
L smd tdk

### PR DESCRIPTION
**Pull request by evanshultz**
https://product.tdk.com/info/en/catalog/datasheets/inductor_commercial_standard_nlv25-ef_en.pdf
https://product.tdk.com/info/en/catalog/datasheets/inductor_commercial_standard_nlv32-ef_en.pdf
image

I had to guess on the body widths a bit because the lead ends are defined and not the body.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Dimensioned drawing:
image

Note that other 2.5x2mm and 3.2x2.5mm SMD inductors that can fit into these footprints, but I know TDK and they make both sizes so I went with them. Let me know if there's another way these should be named.

**Comment by poeschlr** [comment]
NLFV25-EF where did you get the body length of 2.1mm from? (datasheet only dimensions including terminals and that measurement is 2.5mm)

Similarly with NLFV32 and the 2.7mm body length (datasheet gives 3.2 including terminals)

**Comment by evanshultz** [comment]
I noted in the first post that I guessed those dimensions by measuring from the document. I also measured actual parts.

**Comment by poeschlr** [comment]
It might be better to draw the body outline such that it includes the terminals instead. We do it similarly for tantal caps. And this would remove the need to guess a measurement.

**Comment by evanshultz** [comment]
@poeschlr 
OK. Done. I thought this is easy enough to check in the commit that I didn't re-dimension.

Also, I updated the datasheets above to the ones used by the footprints (I used the basic NLV## instead of the commercial or "special" NL*V## versions).

**Comment by poeschlr** [comment]
We decided in similar pull requests that we should include the body size in the footprint name (to be KLC compliant and also to make it easier for users to see what the footprint represents)

Dimensions are now ok.
The change in mpn is ok with me.

**Comment by evanshultz** [comment]
@poeschlr 
You got it. Footprint names updated.

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
