### PR TITLE
Speaker flat 15.0x11.0mm P2mm SMD

### PR DESCRIPTION
**Pull request by persus**
Speaker flat 15.0x11.0mm P2mm SMD

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Datasheet?

**Comment by antoniovazquezblanco** [comment]
Please, post a screenshot and the link to the datasheet of the component. Thanks!

**Comment by persus** [comment]
image

**Comment by persus** [comment]
I'm affraid I hav no data sheet. I searched the internet and didn't find anything. The best I found os the following Link: https://www.alibaba.com/product-detail/Micro-speaker-for-mobile-phone-15x11mm_60804926912.html?spm=a2700.7724857.normalList.26.56a217de5t1RBA

**Comment by poeschlr** [comment]
How should we check something for correctness without a document that gives us the necessary information?
How should a user know if the footprint fits their component if they can not check the datasheet of their component against the specification of the footprint?

And even if we get good documentation, the footprint name would need to be a lot more specific as i highly doubt there is any form of standardization for such components that would mean that a parts of equal size are exchangeable.

**Comment by poeschlr** [comment]
@persus i would assume that there simply is no way to provide us with documentation for your contribution. I will therefore close this PR. Feel free to open a new one if the status changes.

**Pull request closed without merging**
