### PR TITLE
Added QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.

### PR DESCRIPTION
**Pull request by cnieves1**
Generated by script, using PR: https://github.com/pointhi/kicad-footprint-generator/pull/458
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/00002164B.pdf

imagen
imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cnieves1** [comment]
I think the footprint is correct. Paste and mask are split.

**Comment by poeschlr** [comment]
Footprints for generic packages must be scripted with our IPC generator found here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON Documentation for a similar generator see https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO/Readme.md

**Comment by chschlue** [comment]
@cnieves1 Please update once more to account for pad width changes.

**Comment by cnieves1** [comment]
If you mean to update the footprints due to this commit:
  https://github.com/pointhi/kicad-footprint-generator/pull/458/commits/075355fc7abb30b2525119aa4c8ddffb75643f91

the only changes to footprints are tedit fields:

> warning: LF will be replaced by CRLF in Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.kicad_mod.
> The file will have its original line endings in your working directory.
> diff --git a/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.kicad_mod b/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.kicad_mod
> index eca0d61..95943e6 100644
> --- a/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.kicad_mod
> +++ b/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm.kicad_mod
> @@ -1,4 +1,4 @@
> -(module QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm (layer F.Cu) (tedit 5E2FFDFC)
> +(module QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm (layer F.Cu) (tedit 5E391AC8)
>    (descr "QFN, 32 Pin (http://ww1.microchip.com/downloads/en/DeviceDoc/00002164B.pdf#page=68), generated with kicad-footprint-generator ipc_noLead_generator.py")
>    (tags "QFN NoLead")
>    (attr smd)
> diff --git a/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias.kicad_mod b/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias.kicad_mod
> index c7e3642..d9db894 100644
> --- a/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias.kicad_mod
> +++ b/Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias.kicad_mod
> @@ -1,4 +1,4 @@
> -(module QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias (layer F.Cu) (tedit 5E2FFDFC)
> +(module QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias (layer F.Cu) (tedit 5E391AC8)
>    (descr "QFN, 32 Pin (http://ww1.microchip.com/downloads/en/DeviceDoc/00002164B.pdf#page=68), generated with kicad-footprint-generator ipc_noLead_generator.py")
>    (tags "QFN NoLead")
>    (attr smd)
> warning: LF will be replaced by CRLF in Package_DFN_QFN.pretty/QFN-32-1EP_5x5mm_P0.5mm_EP3.3x3.3mm_ThermalVias.kicad_mod.
> The file will have its original line endings in your working directory.
> 

I guess you don't want to commit only these changes..

**Comment by chschlue** [comment]
Alright. Thanks.

**Comment by chschlue** [comment]
Is there a related symbol PR?
Maybe I'm just blind.

**Comment by cnieves1** [comment]
Forgot to add the symbol PR. Done at:
https://github.com/KiCad/kicad-symbols/pull/2478
Thanks!

**Pull request merged**
