### PR TITLE
Xbga 121 10x10mm

### PR DESCRIPTION
**Pull request by Misca1234**
Added XBGA-121_10x10mm_Layout11x11_P0.8mm

Used by PIC24FJ256DA210-IBG in push
https://github.com/KiCad/kicad-symbols/pull/1266
http://ww1.microchip.com/downloads/en/DeviceDoc/39969b.pdf

Script push
https://github.com/pointhi/kicad-footprint-generator/pull/241

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1170

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
How did you determine the pad size and mask clearance?

**Comment by Misca1234** [comment]
copy paste from an existing one, are they to off ?

**Comment by poeschlr** [comment]
Just wondering as i have no clue how to determine it for my self. (BGA is a bit of black magic to me at this point in time.)
We might want to double check with an application note.

**Comment by Misca1234** [comment]
The closest I founf at microchip is this 
http://ww1.microchip.com/downloads/en/DeviceDoc/121L_TFBGA_10x10_BG_C04-0148F.pdf

So pad size should be 0.32, should I just keep the mask clearance or change it ?

**Comment by Misca1234** [comment]
almost all paste_margin in the .yml file are 0.000001 that is 100 times more narrow

**Comment by poeschlr** [comment]
Paste margins are set to that value to ensure that paste has basically the same size as copper.
The clearance above is for mask i would assume.

**Comment by poeschlr** [comment]
Looks good, thanks

**Comment by Misca1234** [comment]
They are moved now

bild

**Comment by evanshultz** [comment]
https://blogs.mentor.com/tom-hausherr/blog/2011/01/08/pcb-design-perfection-starts-in-the-cad-library-part-9-bga-components/ has two charts for packages with balls. They are reproduced here for clarity, but read the whole article because there are lots of things you may not get just from looking at the charts (and I'll refrain from copying more of the article here).

Collapsible balls:
image

Non-collapsible balls:
image

I think we should be able to use this to determine footprint info for BGAs without it. Perhaps this, with a bit of supporting info, should be in KLC? @poeschlr ?

BTW, this agrees with IPC 7095 is anybody has that and uses it as their reference.

**Pull request merged**
