### PR TITLE
Add Littelfuse NANO2 45x series

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.littelfuse.com/~/media/electronics/datasheets/fuses/littelfuse_fuse_451_453_datasheet.pdf.pdf

Screenshot:
littelfuse_45x

Probably footprint name is not the best.

---
All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
When rounding the courtyard outline round it the same all around (You rounded up in y direction and down in x direction)
Screenshot from 2019-10-13 19-39-28

**Comment by jneiva08** [comment]
@poeschlr 
Have increased distance between pad and  F.CrtYd it should be 3.685 and round up to 3.69
The vertical it is 1.825, have already round up to 1.83.

Don't know if the naming is the best, because i intend to PR for the support footprint ([link](https://www.littelfuse.com/~/media/electronics/datasheets/fuses/littelfuse_fuse_154_154t_154l_154tl_datasheet.pdf.pdf))

**Comment by poeschlr** [comment]
thanks

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
