### PR TITLE
added ST_UQFN-6L package

### PR DESCRIPTION
**Pull request by Shackmeister**
Im slightly confused about ST insisting on calling their DFN packages "QFN" :sa: 
last time I added an ST package I believe I renamed it to DFN.
Datasheet: http://www.st.com/content/ccc/resource/technical/document/datasheet/3a/28/cf/d0/31/63/48/8c/CD00282307.pdf/files/CD00282307.pdf/jcr:content/translations/en.CD00282307.pdf

Screenshot:
uqfn6l

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
@poeschlr @jkriege2 @evanshultz can any of you guys please have a look at this?

**Comment by evanshultz** [comment]
Sure!
- Dimensions should be XxY so 1.5x1.7mm; they're reversed.
- Can you add more to the description than just the datasheet?
- Also, change the URL to http://www.st.com/resource/en/datasheet/ecmf02-2amx6.pdf.
- It looks correct to shrink the paste layer by -0.1mm, but can the mask layer stay at default?
- Could the F.Fab ref des be a bit bigger? Also, it's weirdly close to 0,0 but not quite there.

**Comment by Shackmeister** [comment]
hi @evanshultz thanks for the review, all your suggestions should be fixed now, can you have another look?
st_qfn_6

**Comment by evanshultz** [comment]
@Shackmeister 
Thanks!
- The file name wasn't changed to reflect the XxY dimensions.-
- I calculate the outermost left and right courtyard sides should be +/-1.2mm, but these are 1.12mm. Am I calculating wrong?

All else looks good.

**Comment by Shackmeister** [comment]
Im pretty sure the file name was changed correctly :)
Courtyard is now fixed

**Comment by evanshultz** [comment]
Oh yes. Sorry about that. Thanks!

**Pull request merged**
