### PR TITLE
Replacement of PR499

### PR DESCRIPTION
**Pull request by JacobEFO**
Add scripted MSOP-16. Replacement of PR499

This pull request takes the footprints from PR499 https://github.com/KiCad/kicad-footprints/pull/499  and script them.

---

**EDIT: UPDATED FOOTPRINT PICTURES**
**EDIT: This PR no longer overwrites current footprints. They do however miss 3d models now.**

**Footprint 1:**
- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
http://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/ltc-legacy-msop/05081669_A_MS16.pdf

- [x] An example screenshot image is very helpful
image

- [x] Check the output of the Travis automated check scripts - fix any errors as required
No errors locally.

**Footprint 2:**
- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/ltc-legacy-msop/05081667_F_MSE16.pdf

- [x] An example screenshot image is very helpful
image

- [x] Check the output of the Travis automated check scripts - fix any errors as required
Travis generates errors with solder paste marks.

**Footprint 2_ThermalVias:**
- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/ltc-legacy-msop/05081667_F_MSE16.pdf

- [x] An example screenshot image is very helpful
image

- [x] Check the output of the Travis automated check scripts - fix any errors as required
Travis generates errors with solder paste marks. And generates errors on the vias because they are missing layers as per http://kicad-pcb.org/libraries/klc/F7.4/

NOTE: These three footprinst all overwrite existing versions of the corresponding packages. The footprints drawn in ttps://github.com/KiCad/kicad-footprints/pull/499 were originally Linear Technology specific, but confering with @poeschlr lead to these footprints leaving out manufacturer information.

Scripting PR: https://github.com/pointhi/kicad-footprint-generator/pull/281

### CODE REVIEW

**Comment by poeschlr** [comment]
These look a bit strange. (pads are quite far below the body. A bit untypical for gullwing parts.)
If i would have to guess then i would assume you entered the wrong values for lead length. The script assumes the lead length to be the length of the lead contacting the pcb (from the outside tip till the bend)
Hint: It has the nominal value 0.53mm in the last datasheet you linked. (you have minimum = 0.925)

Furthermore: use the same dimensioning style in the yaml file as in the datasheet. If the datasheet gives nominal plus tolerance then the yaml file should contain nominal plus tolerance. (If the datasheet gives minimum/maximum then use only min and max, if it gives minimum/nominal/maximum then include all 3)

**Comment by JacobEFO** [comment]
I was very puzzled with the extremely long pads. I recall seing another example that I followed, but unfortunately now I cannot find it.

I'll fix this and update with commits.

**Comment by poeschlr** [comment]
review comments added to the script pull request

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
