### PR TITLE
CT3151 horizontal banana jack

### PR DESCRIPTION
**Pull request by ppelleti**
[Datasheet](http://www.caltestelectronics.com/images/attachments/P315100rH_drawing.pdf)

banana_jack_ct3151

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

Should not this be re named into ?
CalTest_CT3151V1.kicad_mod 

The following measurement is not the same in your foot print 
bild

it should be 27.7 but it is 27.82

**Comment by ppelleti** [comment]
> it should be 27.7 but it is 27.82

The leftmost fab line is at -21.9.  The rightmost fab line is at 5.8.  The distance between them is 27.7.

**Comment by Misca1234** [comment]
ok, 
What do yo usay about changing the name into 'CalTest_CT3151V1.kicad_mod' ?

**Comment by ppelleti** [comment]
> What do yo usay about changing the name into 'CalTest_CT3151V1.kicad_mod' ?

`CalTest_CT3151` would be fine, but `V1` is for the vertical version.  This is the horizontal version.

**Comment by ppelleti** [comment]
I have renamed it to `CalTest_CT3151`.

**Comment by Misca1234** [comment]
Great thx

**Pull request merged**
