### PR TITLE
BelFuse 0ZRE series fuse

### PR DESCRIPTION
**Pull request by carlosromorgar**
https://www.belfuse.com/resources/datasheets/circuitprotection/ds-cp-0zre-series.pdf

image

image

image

image

image

image

image

image

image

image

image

image

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
All looks good, anyone against merge ?

**Comment by evanshultz** [comment]
@carlosromorgar 
Thanks for contributing!

Some things need updated:
- The description needs to be a real description, not just a link. In fact, the keywords are a decent description so that text could be moved and simple keywords added.
- Silk is offset from fab lines by 0.1mm. It should be at least 0.11mm.
- Don't need series name and full part number. Dimensions are fine but not required. Use `Fuse_BelFuse_0ZRE0005FF_L8.3mm_W3.8mm` if you want to include dimensions.
- We use IPC Level B for padstacks, so the drill is 0.2mm over the lead diameter and the pad size is 0.55mm over the drill. Both are too large when looking at just one footprint.

I didn't do any dimensional checks or look at any but the first footprint, but if the items above can be corrected someone can do a more thorough review when they're closer to being merge-ready.

**Comment by SchrodingersGat** [comment]
Hi @carlosromorgar are you able to address the points made by @evanshultz above? :)

**Comment by carlosromorgar** [comment]
Hi,

sorry for my late response. I have done all changes. I hope they are enough to merge the symbols.

Best regards

image

image

image

image

image

image

image

image

image

image

image

image

image

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
