### PR TITLE
Added QFN-16-1EP_4x4mm_P0.65mm_EP2.5x2.5mm

### PR DESCRIPTION
**Pull request by JeppeSRC**
Added QFN-16-1EP_4x4mm_P0.65mm_EP2.5x2.5mm

[Datasheet](http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
I would assume the script pull request for this is https://github.com/pointhi/kicad-footprint-generator/pull/430

Please read and sign our licence agreement.

**Comment by JeppeSRC** [comment]
Yes it is.

Is the CI supposed to complain about the past and mask layers?

**Comment by poeschlr** [comment]
our test scripts sadly do not work with thermal vias at this point in time. A fix for this is currently worked on https://github.com/KiCad/kicad-library-utils/pull/288

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
