### PR TITLE
Relay: Add Panasonic AD11 Form A

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
SYM PR: KiCad/kicad-symbols#1915
FP PR: KiCad/kicad-footprints#1638
3D PR: https://github.com/KiCad/kicad-packages3D/pull/572
3D SOURCE PR: easyw/kicad-3d-models-in-freecad#289
KLC NAMING: https://github.com/KiCad/kicad-website/issues/418

https://www.panasonic-electric-works.com/pew/es/downloads/ds_dw_hl_en.pdf

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Can the description include some basic dimensions?
1. Can you put pin 1 in the top left corner and unrotate all pads, if needed?
1. Can you point me to the discussion about relay footprint naming? It's not in KLC but I feel like there was a discussion, only I can't find it now.

Once that's done I'll review. Due to the rotation I don't want to dimension twice.

**Comment by antoniovazquezblanco** [comment]
> Can you point me to the discussion about relay footprint naming? It's not in KLC but I feel like there was a discussion, only I can't find it now.

It is about switches. I would go with the same naming scheme: https://github.com/KiCad/kicad-symbols/issues/580

**Comment by antoniovazquezblanco** [comment]
TODO: Reopen 3D PR

**Comment by evanshultz** [comment]
1. One thing I don't like about this naming scheme is that it separates members of the same family. For example, if a family have 1FormA and 1FormC members they're potentially spaced apart. Not sure if it's a problem or anybody else feels the same way, but I want to mention it for discussion purposes. Naturally it doesn't apply here so I'll move discussion to the main issue, but rather than start a paradigm that we abandon I'd rather ask before merging and see if there is quick feedback.
1. Can you unrotate pad 5?
1. All dimensions look good to me:
image

**Comment by antoniovazquezblanco** [comment]
Fixed issues and opened a report to reach an agreement on relay notation.

Thank you very much @evanshultz!

**Comment by evanshultz** [comment]
Oops. I forgot to start the naming discussion. Thanks for stepping in.

If you don't mind, let's allow that to percolate for a bit before merging.

**Comment by antoniovazquezblanco** [comment]
> If you don't mind, let's allow that to percolate for a bit before merging.

Totally agree!

**Comment by antoniovazquezblanco** [comment]
@evanshultz Has naming evolved enough? Can we agree on this or is it still not ready enought?

Thanks!

**Comment by antoniovazquezblanco** [comment]
@evanshultz what do you think about naming? It seems https://github.com/KiCad/kicad-footprints/pull/1728 has been merged with the current naming convention. Do we agree on moving fordward?

Thanks!

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
I'm OK with it. Seems like the conversation died off a bit in the thread but the main points are here. Other items can be cleaned up library-wide if and when that happens.

One thing, which oddly CI didn't catch: the 3D model doesn't match the footprint name. Shouldn't it?

**Comment by antoniovazquezblanco** [comment]
Updated 3D model path!

Updated 3D PR https://github.com/KiCad/kicad-packages3D/pull/663

Thanks!

**Comment by evanshultz** [comment]
Thanks!!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
