### PR TITLE
Sensor_Audio: Add LGA footprint for Knowles SPH0641LU4H-1

### PR DESCRIPTION
**Pull request by zonque**
This add an LGA footprint for a digital MEMS microphone. The datasheet is here: https://media.digikey.com/pdf/Data%20Sheets/Knowles%20Acoustics%20PDFs/SPH0641LU4H-1.PDF

image

The symbol for this part is here: https://github.com/KiCad/kicad-symbols/pull/2952

### CODE REVIEW

**Review by cpresser — CHANGES_REQUESTED** [review]
I did all the checkings relative to the center of the NPTH hole centered in Pad3
- [x] Position and size of Pads 1,2,4,5 are good
- [ ] The body dimension (F.Fab) is off. I measured 3.6x2.6mm
- [x] That also makes the courtyard wrong. It should be 0.25mm outside of the F.Fab lines.
- [ ] Can you explain why you added that circle on F.Mask?
- [ ] Silkscreen should contain a Pin1 indicator. I added a screenshot on how that could look
- [ ] The 4 arcs for paste don't have the exact same coordinates (I checked that by setting the origin into the center of the circle, then looked at the properties of the arc)
- [x] Coordinates of Pad3 are exact
- [ ] Please rotate and shrink the RefDes on F.Fab so it fits within the F.Fab lines.

**Comment by zonque** [comment]
Thanks for the review @cpresser!

I addressed all you comments except for the arcs on F.Paste. I would say they are close enough to what the datasheet describes, but if you think they need fixing I'd appreciate a pointer on how that could be done.

**Comment by cpresser** [comment]
To fix the arcs, you can do the same I did do inspect them
1. Set the origin into the center (x=0, y=0.77)
2. Open the properties windows for each element, adjust the numbers
3. Set origin back.
image


More review Items:
- [ ] F.Fab is not properly closed. Also the bevel is not at 45° 
image
- [ ] F.Fab line thickness should be 0.1mm
- [ ] Silkscreen line thickness should be 0.12mm
- [ ] Silkscreen is taking to much space. I would suggest to do something like this (consistent with other parts, for example `LGA-12_2x2mm_P0.5mm`)
image

**Comment by zonque** [comment]
Okay, I think I got it now.

**Comment by cpresser** [comment]
I did not fully check the newest changes. Because I am not happy with the silkscreen. It still takes up to much board space.
- Remove the circle
- Put it closer to F.Fab as in my screenshot or seen on other LGA parts. Basically the silkscreen should touch, but not overlap the Fab Outline.

**Comment by cpresser** [comment]
Silkscreen looks okay now. Thanks!

Can you please fix the remaining travis-ci issues:
* F9.3 add a 3D-Model filename. Even though no model exists yet. The idea is that the footprint does not need to change should the 3D-Model be added in the future.
* F5.3 courtyard onto 0.01mm grid. Move them (away from the part) by 0.005mm to fix that.
* F6.3 is a false positive, you can ignore that

**Comment by zonque** [comment]
> * F9.3 add a 3D-Model filename. Even though no model exists yet. The idea is that the footprint does not need to change should the 3D-Model be added in the future.
> 
> * F5.3 courtyard onto 0.01mm grid. Move them (away from the part) by 0.005mm to fix that.

Done and done.

**Comment by cpresser** [comment]
> > * F9.3 add a 3D-Model filename. Even though no model exists yet. The idea is that the footprint does not need to change should the 3D-Model be added in the future.
> > * F5.3 courtyard onto 0.01mm grid. Move them (away from the part) by 0.005mm to fix that.
> 
> Done and done.

Not according to travis: https://travis-ci.org/github/KiCad/kicad-footprints/builds/728342240

**Comment by zonque** [comment]
```
   Courtyard lines are not on 0.01mm grid
     - Line (-1.58,-2) -> (1.58,-2) on layer 'F.CrtYd'
     - Line (1.58,-2) -> (1.58,2) on layer 'F.CrtYd'
     - Line (1.58,2) -> (-1.58,2) on layer 'F.CrtYd'
     - Line (-1.58,2) -> (-1.58,-2) on layer 'F.CrtYd'
```

:thinking:

**Comment by cpresser** [comment]
> ```
>    Courtyard lines are not on 0.01mm grid
>      - Line (-1.58,-2) -> (1.58,-2) on layer 'F.CrtYd'
>      - Line (1.58,-2) -> (1.58,2) on layer 'F.CrtYd'
>      - Line (1.58,2) -> (-1.58,2) on layer 'F.CrtYd'
>      - Line (-1.58,2) -> (-1.58,-2) on layer 'F.CrtYd'
> ```
> 
> thinking

Interesting. That might be a bug in the check script. I will investigate.

**Comment by cpresser** [comment]
The 3D-Model name warning is not a false positive and should be addressed.

**Comment by zonque** [comment]
> Interesting. That might be a bug in the check script. I will investigate.

I moved it to the 0.1 mm grid now. Let's see.

**Comment by zonque** [comment]
> I moved it to the 0.1 mm grid now. Let's see.

Nope.

```
    Courtyard lines are not on 0.01mm grid
     - Line (-1.6,-2) -> (1.6,-2) on layer 'F.CrtYd'
     - Line (1.6,-2) -> (1.6,2) on layer 'F.CrtYd'
     - Line (1.6,2) -> (-1.6,2) on layer 'F.CrtYd'
     - Line (-1.6,2) -> (-1.6,-2) on layer 'F.CrtYd'
```

**Comment by cpresser** [comment]
> > I moved it to the 0.1 mm grid now. Let's see.
> 
> Nope.
> 
> ```
>     Courtyard lines are not on 0.01mm grid
>      - Line (-1.6,-2) -> (1.6,-2) on layer 'F.CrtYd'
>      - Line (1.6,-2) -> (1.6,2) on layer 'F.CrtYd'
>      - Line (1.6,2) -> (-1.6,2) on layer 'F.CrtYd'
>      - Line (-1.6,2) -> (-1.6,-2) on layer 'F.CrtYd'
> ```

It is a bug in the check script. And I am to blame. https://github.com/KiCad/kicad-library-utils/pull/334

Please revert to the proper 0.01mm grid. I will try to fix the check scripts in the meantime.

**Comment by cpresser** [comment]
Travis is still broken, but my local check is fine:
image

**Review by cpresser — APPROVED** [review]

**Pull request merged**
