### PR TITLE
Fixed wrong pin spacing in Choke_Schaffner_RN202 and missing pins in Converter_DCDC_XP_POWER-ITxxxxxS_THT

### PR DESCRIPTION
**Pull request by HB9GKW**
Fixed wrong Y pin spacing in Choke_Schaffner_RN202 (10mm to 15.2mm) and added missing pins in Converter_DCDC_XP_POWER-ITxxxxxS_THT.

1. Footprint of choke RN202 [https://www.schaffner.com/products/download/product/datasheet/rn-series-common-mode-chokes-new/](url) requires a Y pin spacing of 15.2mm instead of 10mm.

2. Footprint Converter_DCDC_XP_POWER-ITxxxxxS_THT has missing pins (5 and 8) required for ITQXXXXS(A) series [https://www.xppower.com/portals/0/pdfs/SF_ITQ.pdf](url). The datasheet link of both ITX and ITQ series DC-DC converters has been updated too.

Best Regards
Alex

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by HB9GKW** [comment]
I'm sorry. Didn't check the output of the Travis automated check scripts. The fix is now committed.

**Comment by evanshultz** [comment]
@HB9GKW 
Thanks for submitting this fix. Please note there is still one CI error.

Also, this footprint is scripted. You can find the script at https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Inductors/Choke_Schaffner_RNXXX.py. It would be ideal if you could re-generate the new footprint from the script and also update the script. Is that something you would be willing and able to do?

**Comment by HB9GKW** [comment]
Okay I understand pad 1 is not at the origin due to the offset.
@evanshultz 
You're right. Fixing the script makes more sense. Unfortunately my python and git skills are very limited, therefore I would appreciate if someone else could do that.

**Comment by chschlue** [comment]
In the spirit of `build a man a fire, and he'll be warm for a day. Set a man on fire, and he'll be warm for the rest of his life`, would like to learn how to do it?
If not, I can submit a fix later.

**Comment by HB9GKW** [comment]
@chschlue
Yes I would like to know how to do that! I guess step 1 is understanding the script. Step 2 fixing the script and submit a PR? Step 3 generate all corresponding footprints and checking them with other helper scripts?

**Comment by evanshultz** [comment]
Essentially. If it just works you don't need to understand the script.
1. Grab the script.
1. Run it. Note that this looks a little old, so it may have been written under Python 2. All newly-submitted scripts are written for Python 3. It may or may not run in 3 without issues.
1. Fix the vendor name on line 54 of the script. (There may be other issues but I just happened to notice that while scanning the script.)
1. You can grab just the relevant footprint and replace the one in this PR with the new one from the script.
1. Submit changes to the script at the repo from which is lives.

If that's too much, one of us can do it. Or we can help walk you though it.

**Comment by evanshultz** [comment]
Also, I see that you submitted this PR using the master branch of your repo. That's not good practice - you should create a new branch and then submit the changes on the new branch.

**Comment by chschlue** [comment]
The script runs in Python 3, but I just noticed it uses hardcoded `\` as path delimiters.

**Comment by HB9GKW** [comment]
Ok thanks for your advices. I should read carefully thru all the basics for contributing in git. Combining two different issues in one PR seems also no good practice. Could you please fix the current issue with the script?

**Comment by evanshultz** [comment]
Already fixed. :)

**Comment by Flo3561** [comment]
I have opened a pull-request for adapting the generator script https://github.com/pointhi/kicad-footprint-generator/pull/497.
There are also several other components to be modified (RN142/RN143/RN232) and RN218 to be added. 

How shall we proceed @evanshultz ? 
Opening a new PR for this Inductor modification and handling the DC/DC power converter issue with this PR?

**Comment by Flo3561** [comment]
Any update?
@evanshultz / @chschlue

**Comment by evanshultz** [comment]
@HB9GKW 
Since these are all good fixes I will merge. I had missed this. Sorry.

There is a symbol that need fixing as well; can you do that? The *SA symbol (single output with no remote on/off) is missing pins 3 and 5.

@Flo3561 
Merging this will fix the one footprint, but you have a couple of other fixes in your script plus other pin location fixes. So if you can create a new PR for the script-generated footprints then I can merge all of those at once on top of this PR. Sound OK?

**Comment by Flo3561** [comment]
@evanshultz

**Comment by Flo3561** [comment]
@evanshultz

**Comment by Flo3561** [comment]
@evanshultz 
I have created a new PR #2107 . But CI shows several errors (Violating F5.3 / Courtyard lines are not on 0.01mm grid / Courtyard must be closed.) with only small changes like no more float value for the angle of fp_arc element (before "60.0" now "60").

**Comment by evanshultz** [comment]
Merging this even though it introduces an error in the RN202 footprint, since this can be addressed in the PR mentioned above.

And after a second review of the symbols, I see one symbol that is missing pins and needs fixed (oddly, it appears the other symbols wouldn't have matched the old footprint which is scary). Submitted https://github.com/KiCad/kicad-symbols/pull/2512 to fix that.

**Pull request merged**
