### PR TITLE
OnSemi_XDFN4-1EP_1.0x1.0mm_EP0.52x0.52mm.kicad_mod

### PR DESCRIPTION
**Pull request by chmorgan**
XDFN4 footprint used for a number of OnSemo regulators.
https://www.onsemi.com/pub/Collateral/NCP115-D.PDF

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chmorgan starting the review of this footprint.

- [X] No comment on the pads.
- [ ] The silkscreen is too much closed to the pad and fab layer. Clearance is usually 0.11mm from the fab layer and 0.2mm from the pad. You should increase the clearance for this part.
- [ ] Clearance for CrtYd layer is usually 0.25mm, it's too large on the left and right sides.

@chschlue I prefer to ask you the question just to be sure: is it possible to script this kind of part, with specific pads in the corner and 45° rotated EP ?

Joel

**Comment by myfreescalewebpage** [comment]
Thanks @chschlue .
@chmorgan waiting your changes.

**Comment by myfreescalewebpage** [comment]
@chmorgan are you still alive on this subject ?

**Comment by chmorgan** [comment]
@myfreescalewebpage pushed some updates to the footprint.

image

**Comment by myfreescalewebpage** [comment]
Looks great, no more comment.

**Pull request merged**
