### PR TITLE
Adding Samtec_FMC_ASP-134486-01_10x40_P1.27mm_Vertical connector

### PR DESCRIPTION
**Pull request by ki5libs**
Adding Samtec_FMC_ASP-134486-01_10x40_P1.27mm_Vertical connector
[Datasheet](http://suddendocs.samtec.com/prints/asp-134486-01-mkt.pdf)

ASP-134486-01

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Seems like a few measurements are not quite right
Screenshot from 2019-06-02 14-23-06

**Comment by ki5libs** [comment]
Hi @poeschlr 

Sorry for a long delay, but I finally got this and make some dimension fixies. And please tell me what tool do you use for dimensions checking?

**Comment by poeschlr** [comment]
I use freecad with the sadly no longer maintained drawing dimensions workbench. (Replaced with techdraw that is more focused on making standard conform drawings and sadly has a few usability issues.)
I made a tutorial for it here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279

**Comment by poeschlr** [comment]
Sorry for the delay, there is still a problem with two dimensions:
drawing svg

**Comment by ki5libs** [comment]
Hi @poeschlr 
I've fixed one dimension (3.165->3.1). But I'm not sure, that it's really necessary to make 54.380 from 54.381. It looks like rounding issue of conversion to metric system: 2.141 x 25.4 = 54.3814

**Comment by poeschlr** [comment]
If the datasheet gives 3 digits after the decimal point then we check up to 3 digits after the decimal point. Naturally it must then agree to be let through

**Comment by poeschlr** [comment]
Wait i read it the other way round

**Comment by poeschlr** [comment]
You moved it too far. Now the distance is 3.09 instead of 3.1

**Comment by ki5libs** [comment]
Sorry, it should be OK now

**Comment by poeschlr** [comment]
Looks good now, thanks

**Pull request merged**
