### PR TITLE
Add Dialight 591 series

### PR DESCRIPTION
**Pull request by jneiva08**
Product page: http://www.dialightsignalsandcomponents.com/Product/Details/557514/5912301013F
Dataheet: http://www.dialightsignalsandcomponents.com/Assets/Drawings/2D_Drawings_DrawingDetailedSpec/C17354.pdf

Screenshot:
footprint

3d

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hello @jneiva08,
Great PR!
There is a minor mistake. Two terminal footprints should be aligned with pin 1 on the left side.

**Comment by jneiva08** [comment]
Sorry for taking too long to fix.

screenshot:
dialight

**Comment by poeschlr** [comment]
You do not need to apologize. A contribution is ready when it is ready. We could also have been much faster with a review but well everyone here is a volunteer and nobody has as much time for kicad as they would like.

**Comment by gmsotavio** [comment]
I agree with every single word Rene said.

A single dimension remains incorrect. Check the dimensioned drawing.
image

**Comment by jneiva08** [comment]
@gmsotavio , have fixed wrong F.CrtYd

**Comment by gmsotavio** [comment]
> @gmsotavio , have fixed wrong F.CrtYd

@jneiva08, now, everything looks good. Thanks for your contribution!
image

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
