### PR TITLE
Add Texas R-PUQFN-N10

### PR DESCRIPTION
**Pull request by EvilMav**
[Land pattern from BQ24392 Datasheet](www.ti.com/lit/ds/symlink/bq24392.pdf), as the package PDF does not contain a recommended footprint.

kicad_puqfn_n10

This footprint is not scriptable as discussed in https://github.com/pointhi/kicad-footprint-generator/issues/257
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Please rotate the footprint 90 degree clockwise such that pin 1 results on the top left corner.

The datasheet in the footprint description is wrong.

The courtyard clearance is relative to either relative to pads or the part body whichever is larger. (In this particular case it must be relative to the pads.)

screenshot from 2019-01-17 23-38-35

**Comment by EvilMav** [comment]
@poeschlr  Thank you for the quick review! Should be fixed now.
kicad_puqfn_n10

**Comment by poeschlr** [comment]
Tutorial is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279

**Comment by poeschlr** [comment]
Looks good, thanks

screenshot from 2019-01-19 00-08-52

**Pull request merged**
