### PR TITLE
Add Artesyn ATA Series SMT DC to DC converter footprint.

### PR DESCRIPTION
**Pull request by stambaughw**
Please consider this pull request for the [Artesyn ATA series DC to DC converter](https://www.artesyn.com/power/assets/ata_series_ds_01apr2015_79c25814fd.pdf) SMT footprint.  I have already submitted the [3D model pull request](https://github.com/KiCad/kicad-packages3D/pull/472).

converter_dcdc_artesyn-ata-series_smd

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks again!

- I think "Series" can be removed from the footprint and 3D model names.
- Dimensions in the description are a bit wrong.
- Include https://www.artesyn.com/power/assets/trn_dc-dc_ata_3w_series_releas1430412818_techref.pdf in the description (along with the datasheet you already have there) since it shows the recommended land pattern on page 75.
- The Y dimension on vertical silk lines are inconsistent (9.8mm, 9.81mm, 9.85mm, etc.).
- Horizontal courtyard lines above and below the pads should be 9.84mm.
- The vendor name in the footprint should be camelcase as caught by Travis.

Some of these may seem pedantic, like the horizontal courtyard lines moving by 0.01mm, but that follows the guidelines in KLC. You know well if code quality is inconsistent it'ss very hard to manage/review submissions and maintain code. This is a similar situation.

**Comment by stambaughw** [comment]
Would the file name be DCDC_Converter_Artesyn-SMD.kicad_mod?

Wouldn't it just be prudent to only include only the technical reference
link since it contains all of the information that is in the datasheet?
 It seems that having both urls is a bit excessive.

**Comment by evanshultz** [comment]
`Converter_DCDC_Artesyn_ATA_SMD` is good. You may only include the technical reference, but the datasheet is so much easier to parse and has all the useful info but the footprint.

**Comment by stambaughw** [comment]
I think I got it right now.

**Comment by evanshultz** [comment]
Thanks.

- The fab layer value and 3D model need to have a matching name.
- Would you mind cleaning up the vertical silk lines as mentioned above?

**Comment by evanshultz** [comment]
Wayne, just fix the CI errors and I think this is good to go.

**Comment by evanshultz** [comment]
There are still naming mismatches which CI caught that haven't been fixed.

**Comment by evanshultz** [comment]
All that's left is to fix the 3D model name to match the file name.

**Comment by evanshultz** [comment]
Thank you!

**Pull request merged**
