### PR TITLE
Add Buzzer_Murata_PKLCS1212Exxxx-R1 series

### PR DESCRIPTION
**Pull request by HendryKaak**
Hello,

Generic + footprint information (Page 4-5):
[Datasheet](https://www.murata.com/~/media/webrenewal/support/library/catalog/products/sound/p37e.ashx)

Product specific specs:
[Product specs](http://www.murata.com/en-us/api/pdfdownloadapi?cate=&partno=PKLCS1212E4001-R1)

Screenshot:
Footprint Editor - Buzzer_Beeper_Buzzer_Murata_PKLCS1212Exxxx-R1

Footprint:
Piezoelectric Sound Components - Standard Land Pattern Dimensions

check_kicad_mod.py script:
check_kicad_mod py Buzzer_Murata_PKLCS1212Exxxx-R1 kicad_mod

I also noticed that footprint `Buzzer_Murata_PKMCS0909E4000-R1.kicad_mod` should probably be renamed to `Buzzer_Murata_PKMCS0909Exxxx-R1.kicad_mod` (together with the 3D-model), since that is also a buzzer series. Shall I commit this together with this PR as well or preferably a separate PR? AFAICS is that this specific footprint is currently not used in a symbol, so that should be OK I guess?

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by aris-kimi** [comment]
@HendryKaak , thank you for your contribution.

I only have one comment about pin1 fab layer bevel
εικόνα

@chschlue , this(0.5mm) has to be 1mm on both axes right??
also i am not 100% sure about naming (i think `-R1` can removed) but i seems ok. I need confirmation.

Other dimensions are correct.

**Comment by chschlue** [comment]
@aris-kimi yes and yes.

**Comment by aris-kimi** [comment]
Thanks.

So @HendryKaak , it is only one fix at the fab layer bevel and then it is ready to merge.

**Comment by chschlue** [comment]
And the naming.

**Comment by HendryKaak** [comment]
Hey, thanks for reviewing @aris-kimi 
Ah yes, I missed out on the fab-layer bevel size. Good point :-)
I added the `-R1` to keep the name consistent with component `Buzzer_Murata_PKMCS0909E4000-R1`, but yes it just indicates the used packaging material and nothing more. It's probably OK to rename that file as well. I'll add the rename commit in the same branch so it can be merged together with this commit (and rebase it on top of master).

**Comment by aris-kimi** [comment]
Dimensions are ok.

@chschlue one question, are we ok with this naming change?
`Buzzer_Murata_PKMCS0909E4000-R1` to `Buzzer_Murata_PKMCS0909Exxxx`

**Comment by chschlue** [comment]
We generally don't use trailing wildcards. Please remove `xxxx` at the end now that `-R1` is gone.

**Comment by HendryKaak** [comment]
Third time's a charm :-)

**Comment by aris-kimi** [comment]
Thanks @HendryKaak , merging now.

**Comment by HendryKaak** [comment]
Thank you both :+1:

**Pull request merged**
