### PR TITLE
Added footprint for ERM19264 192x64 display module

### PR DESCRIPTION
**Pull request by Dovgalyuk**
Added footprint for ERM19264 192x64 display module
datasheet: https://www.buydisplay.com/download/manual/ERM19264-1_Series_Datasheet.pdf
display description: https://www.buydisplay.com/default/4-inch-192x64-lcd-module-graphic-display-ks0107-ks0108-black-on-white

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by Dovgalyuk** [comment]
Symbol pull request: https://github.com/KiCad/kicad-symbols/pull/2083

**Comment by myfreescalewebpage** [comment]
Hi @Dovgalyuk , thanks for contributing,

A few comments I have during my review:

- [ ] Origin should be on pad 1 (see travis error)
- [ ] The external dimensions of the display should be all with F.Fab layer
- [ ] Then you need to add F.SilkS layer (0.12mm offset from F.Fab is ok)
- [ ] Then you need to add F.CrtYd layer (0.5mm offset from F.Fab is ok)
- [ ] An indicator should be present to show pin 1 on F.Fab and F.SilkS layers (see other LCD in the lib)
- [ ] 3D model to be defined (even if the wrl file does not exist), see travis error

Two questions:

- [ ] How do you know the distance between the pad and the border is 2mm ? I have seen the dimensions anywhere
- [ ] The kicad_mod file has empty lines which are totally not useful, have you edited the kicad_mod file by end ? It's not required and not wanted

Will continue the review after that

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@Dovgalyuk ping

**Comment by Dovgalyuk** [comment]
>  3D model to be defined (even if the wrl file does not exist), see travis error

I used this display in my hobby project. Therefore I haven't enough time to create a 3D model, sorry.

>  How do you know the distance between the pad and the border is 2mm ? I have seen the dimensions anywhere

I think it was measured on my board.

> The kicad_mod file has empty lines which are totally not useful, have you edited the kicad_mod file by end ? It's not required and not wanted

I can fix it, if needed.

**Comment by myfreescalewebpage** [comment]
> I used this display in my hobby project. Therefore I haven't enough time to create a 3D model, sorry.

I don't ask to create the 3D model itself, I just required to have the path of the 3D model defined in the footprint, like all the footprints.

> I can fix it, if needed.

Yes please. Just save the file with the editor, it should fix it for you.

**Comment by Dovgalyuk** [comment]
> > I used this display in my hobby project. Therefore I haven't enough time to create a 3D model, sorry.
> 
> I don't ask to create the 3D model itself, I just required to have the path of the 3D model defined in the footprint, like all the footprints.

Should it be a link to the file that does not exist?

**Comment by myfreescalewebpage** [comment]
Yes. Example on a footprint I have just reviewed:

Capture

(the 3D view remains with only the footprint).

This permit to easily add the 3D files later if someone want to do it, no more need to change the footprint.

**Comment by Dovgalyuk** [comment]
Now travis complains on other footprints, but the display seem to be ok.

**Comment by myfreescalewebpage** [comment]
Closing/opening to refresh the Travis test.

**Comment by myfreescalewebpage** [comment]
I made a mistake in my previous review:

- [ ] Then you need to add F.CrtYd layer (**0.25mm** offset from F.Fab is ok)

Then continue the review:

- [ ] Where have you found the pad are at 2mm from the left border ?
- [ ] Mounting holes should be "NPTH, Mechanical"
- [ ] The display area inside the footprint should be on F.SilkS instead of F.Fab
- [ ] I disagree with the size of the display area, should be 104x39mm

Joel

**Comment by Dovgalyuk** [comment]
> * [ ]  Then you need to add F.CrtYd layer (**0.25mm** offset from F.Fab is ok)
> * [ ]  The display area inside the footprint should be on F.SilkS instead of F.Fab
> * [ ]  I disagree with the size of the display area, should be 104x39mm

Ok


> * [ ]  Where have you found the pad are at 2mm from the left border ?

Not sure about it. I guess that I measured it on the physical device.

> * [ ]  Mounting holes should be "NPTH, Mechanical"

Haven't got it. Do you have an example?

**Comment by myfreescalewebpage** [comment]
> Mounting holes should be "NPTH, Mechanical"
Haven't got it. Do you have an example?

This is in pad properties window

**Comment by myfreescalewebpage** [comment]
Please do not force push, this totally break the commit history and then it's a total mess to perform reviews, we are forced to restart the review from the beginning...

**Comment by myfreescalewebpage** [comment]
Have you made the above changes ?

**Comment by Dovgalyuk** [comment]
> Please do not force push, this totally break the commit history and then it's a total mess to perform reviews, we are forced to restart the review from the beginning...

Sorry about that, I forgot that commits can be squashed later.

**Comment by Dovgalyuk** [comment]
> Have you made the above changes ?

Yes, please check it.

**Comment by myfreescalewebpage** [comment]
Full review from this point. For me one issue to be fixed:
- [ ] The mounting hole size AND diameter should be 2.5mm (seen this on LM16255 device in the lib which is very similar to your footprint).

And 1 issue I wasn't aware 5 minutes ago but I just learned:
- [ ] You have to rotate the footprint so the pin 1 is on top left position. Again LM16255 is a good example. KLC rule F4.2 at https://kicad-pcb.org/libraries/klc/F4.2/

Joel

**Comment by Dovgalyuk** [comment]
> Full review from this point. For me one issue to be fixed:
> 
> * [ ]  The mounting hole size AND diameter should be 2.5mm (seen this on LM16255 device in the lib which is very similar to your footprint).

PDF says that the hole is 1.6mm. Should I set size to 1.6mm then?

**Comment by myfreescalewebpage** [comment]
No, 2.5mm is great I think because the hole is probably used to have a screw of M1.6 and we need extra space to mount it easily.

**Comment by Werni2A** [comment]
@myfreescalewebpage The 1.6mm from the datasheet are actually the radius of the holes. I think the drills should be a little bit greater than 3.2mm in diameter, what do you think?
image

**Comment by Dovgalyuk** [comment]
> Full review from this point. For me one issue to be fixed:
> 
> * [ ]  The mounting hole size AND diameter should be 2.5mm (seen this on LM16255 device in the lib which is very similar to your footprint).
> 
> And 1 issue I wasn't aware 5 minutes ago but I just learned:
> 
> * [ ]  You have to rotate the footprint so the pin 1 is on top left position. Again LM16255 is a good example. KLC rule F4.2 at https://kicad-pcb.org/libraries/klc/F4.2/
> 
> Joel

Done.

**Comment by myfreescalewebpage** [comment]
Good remark of @Werni2A thanks. The dimension is actually the radius 1.6mm so diameter 3.2mm. I suggest 3.5mm for the holes. @Dovgalyuk can you increase a bit please ?

**Comment by Dovgalyuk** [comment]
> Good remark of @Werni2A thanks. The dimension is actually the radius 1.6mm so diameter 3.2mm. I suggest 3.5mm for the holes. @Dovgalyuk can you increase a bit please ?

Fixed.

**Comment by myfreescalewebpage** [comment]
Thanks. Just notice you have also some travis error to be fixed. Silkscreen liners width should be 0.12mm:

**Comment by Dovgalyuk** [comment]
> Thanks. Just notice you have also some travis error to be fixed. Silkscreen liners width should be 0.12mm:
> 
> Capture

Ok.

**Comment by myfreescalewebpage** [comment]
Thanks, great job done here ! Merging.

**Pull request merged**
