### PR TITLE
Create Linear MSOP-12-16 for LT3748

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Creation of MSOP-12-16 3x4mm for LT3748, copied from Linear_MSOP-12-16-1EP_3x4mm_P0.5mm and removed the expose pad.

File comparison between "Linear_MSOP-12-16-1EP_3x4mm_P0.5mm.kicad_mod" and "Linear_MSOP-12-16_3x4mm_P0.5mm.kicad_mod":

capture

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing

https://www.analog.com/media/en/technical-documentation/data-sheets/3748fb.pdf

- [x] An example screenshot image is very helpful 

capture

- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate

https://github.com/KiCad/kicad-symbols/pull/1600

- [x] Check the output of the Travis automated check scripts - fix any errors as required

No errors at this time

- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
If you compare the footprint in this datasheet with the one in the existing footprint (https://www.analog.com/media/en/technical-documentation/data-sheets/3630fd.pdf), you will see that the outer edges of the pads is 5.1mm min whereas the datasheet above says 5.23mm min. The footprint is right at 5.1mm.

However, all the package dimensions are the same so this footprint is likely to be fine. So I'll merge after I hear back from you if you want to make any changes or go with it.

**Comment by myfreescalewebpage** [comment]
@evanshultz thanks for the review, I haven't seen this details before, I have only compare the packages dimensions themselves, which are exactly the same, and I agree the difference is acceptable here.

**Comment by evanshultz** [comment]
On the assumption that this will be scripted in the future, which requires updating the script to allow "missing" pins like on this package, any issues should go away anyway.

**Comment by myfreescalewebpage** [comment]
An optional list with missing pins in the config file of the script and it's can be easily achieved I think :)

**Comment by evanshultz** [comment]
Yeah. I believe some script already has this but it's straightforward to imagine how to do it if not.

**Pull request merged**
