### PR TITLE
Updated SODIMM 200 footprint - rework

### PR DESCRIPTION
**Pull request by herostrat**
Because I butchered my PR, here is a corrected one, where no wrong commits are included.

Previous PR can be found here:
https://github.com/KiCad/kicad-footprints/pull/1158

---

Copying the text from there:

Sorry for the late update, because I used a modified version I forgot to update and push here.

This PR should replace and correct #375

The CtrYd was modified to be 0.5mm.
The shape of the wings was also modified in according to the real dimensions.

grafik

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

 [x] Provide a URL to a datasheet for the footprint(s) you are contributing
 [x] An example screenshot image is very helpful
 [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
 [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hello @herostrat thanks for this contribution. I have some few comments you will find below.

- [ ] Positions/sizes of the pins/holes ok except for the even pins, which are at X position "-0.500001" mm instead of "-0.5" m.

- [ ] There is a fab line under the device, do not understood what it correspond, should be removed according to me, see following screenshot

capture

- [ ] A clearance of 0.12mm should be always present between the Fab and Silkscreen layers

- [ ] The width of the silkscreen lines should be 0.12mm (see travis error)

- [ ] The CrtYd layer should be enlarged to let enough place to eject the sodimm module, see following screenhots

capture

capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @herostrat are you still alive on this subject ? Thanks

**Comment by herostrat** [comment]
I surely am.
I updated every point except the last.

I hope I can finish it soon.

**Comment by myfreescalewebpage** [comment]
Great, thanks for the news!

**Comment by daviid5** [comment]
Hello together
Is there anything which prevents merging this package into Master?

**Comment by herostrat** [comment]
I hope nothing anymore.

I just finished my thesis and completely forgot to finish this PR.
Sorry guys...

**Comment by myfreescalewebpage** [comment]
@daviid5 it has just been updated, a checklist was still pending, just on my previous comments.
Need to check again, but if this is great should be merged very soon.

**Comment by myfreescalewebpage** [comment]
@herostrat I have a problem to open the footprint in Kicad, it is not shown in the editor. Are you able to open it ?

**Comment by herostrat** [comment]
@myfreescalewebpage I verified and can find and open the footprint.
I am using 5.1.2

Anybody else has this problem?

**Comment by evanshultz** [comment]
I see it:
image

**Comment by myfreescalewebpage** [comment]
Just updated from 5.0 to the latest version 5.1.2-1, the footprint is visible :) Will continue the review asap.

**Comment by myfreescalewebpage** [comment]
I still see some fab line under the devices:

Capture3

Also some lines are not properly set:

Capture2

And following update to the last Kicad version I have a strange error about silkscreen.... Maybe also @evanshultz can give a feedback:

Capture

I think you should define them again

Joel

**Comment by herostrat** [comment]
Thanks for the feedback Joel, I corrected everything I could. This was too sloppy of me, I will take better care in the future.

grafik
grafik
grafik

---

The layer problem is fixed, although I do not know how it came into existence?
The layer was changed to rescue, I changed it back to the correct front silk layer.

**Comment by myfreescalewebpage** [comment]
I still see one line which should be removed:

Capture3

(this make a travis error)

Else, seems nice, but I will prefer if another librarian can have a look too, maybe @evanshultz ?

Cheers,
Joel

**Comment by herostrat** [comment]
I removed this line.
I don't even know why it was there in the first place, I adopted it from the original design.
grafik

**Comment by myfreescalewebpage** [comment]
Thanks, we do not allow it in KiCad.
However, I just notice this is another line to be removed which make the travis error, see following screenshot:

Capture

**Comment by herostrat** [comment]
Done

**Comment by myfreescalewebpage** [comment]
@poeschlr or @evanshultz the is PR is not bad according to me but if you can double check, this is very nice. Thanks, Joel

**Comment by evanshultz** [comment]
@myfreescalewebpage 
What kind of check are you looking for?

At #375 Rene measured the footprint against a TE model found online and commented about the courtyard distance. Did you confirm those things have been corrected?

Did you dimensionally check the footprint against the one at https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1473149%7FK3%7Fpdf%7FEnglish%7FENG_CD_1473149_K3.pdf%7F1473149-4?

I opened it quickly and I see that the silk lines show up on F.Cu for me, which is disallowed. But looking at the file I don't see lines on F.Cu. So I must be doing something wrong.

**Comment by myfreescalewebpage** [comment]
@evanshultz general review, I sometimes not have clear ideas about Paste or not Paste, etc. But the overall dimensions and great.
Thanks
Joel

**Comment by evanshultz** [comment]
All dimensions of the footprint check out:
image

And the 3D model from TE seems to line up nicely once it's rotated properly:
image

My only question/concern is why I'm seeing the silk lines show up on the F.Cu layer. I don't see any lines on F.Cu in the branch or on the file on my computer, but I do when opening in KiCad 5.1.2. The silk lines, teal in your screenshots above, are red for me because of the layer change. Am I the only one?

**Comment by evanshultz** [comment]
I sorted out git and now see proper silk lines. Weird. Now here are a few other comments:
1. There is no fab pin 1 mark.
1. The silk can go a bit closer to the pins. 0.12-0.2mm clearance is good.
1. I forgot to check the courtyard above and when I did I believe there are a few areas where it's wrong. Not everywhere came out to 0.5mm. Please review and either correct the footprint or let me know where I got it wrong.
image
image

**Comment by evanshultz** [comment]
@herostrat 
Are you soon planning to address the issues I noted above so this can be merged?

**Comment by myfreescalewebpage** [comment]
Reopening the issue to keep trace of it, so another guy can continue the job.

**Comment by myfreescalewebpage** [comment]
Just seen #1934

**Pull request closed without merging**
