### PR TITLE
Footprints for Meanwell IRM-30/45/60 AC/DC converters.

### PR DESCRIPTION
**Pull request by Sthing**
Matches symbols in https://github.com/KiCad/kicad-symbols/pull/844
Generated by the script from https://github.com/pointhi/kicad-footprint-generator/pull/164

Datasheets:
 - http://www.meanwell.com/Upload/PDF/IRM-30/IRM-30-SPEC.PDF
 - https://www.meanwell-web.com/content/files/pdfs/productPdfs/MW/IRM-45/IRM-45-spec.pdf
 - https://www.meanwell-web.com/content/files/pdfs/productPdfs/MW/IRM-60/IRM-60-spec.pdf

Screenshots:
image
image

------------
- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi 

You should remove the chamfer in the bottom left corner

The chamfer up in the right corner should only be in F.Fab layer

Any particular reason you palced the F.CrtYrd ontop of the F.Silk (just asking) ?

**Comment by Misca1234** [comment]
@Sthing 
Please see comment above

**Comment by Sthing** [comment]
Hi @Misca1234 and @poeschlr 

Sorry for being so late.

Misca1234 wrote:
> You should remove the chamfer in the bottom left corner
Why that corner? The component physically has a chamfer in all corners.
I do not under stand why the bottom-left chamfer has to go, but the two to the right can stay.

> Any particular reason you palced the F.CrtYrd ontop of the F.Silk?
No - I just adapted a generator script.

**Comment by Misca1234** [comment]
@KiCad/librarians 
Do we have an opinion about placing F.Silk ontop of F.Fab layer?
If not, these foot rpints corresponds with data sheet and can be merged

**Comment by Misca1234** [comment]
@Sthing 
Notice that you have some travis errors

**Comment by evanshultz** [comment]
While IPC does not relate silkscreen and the courtyard, I would like to see silk inside the courtyard. The scripts commonly use 0.11mm offset from the fab lines and that works well. Much larger than that and it's possible to eat away the silk due to other closely-placed units. And at 0.25mm offset the chance is even larger.

I would like to see this better-defined in KLC, but I understand Rene's desire to not specify it rigidly.

All that being said, KLC doesn't specify this offset and I wouldn't hold up merging if that was the only open item.

**Comment by Misca1234** [comment]
@Sthing 
you need either modify the file 
pointhi/kicad-footprint-generator/scripts/Capacitors_SMD.chamfers
or copy the file to you directory

in either case you need to add round to the "prints", that is
```

polygon_line = [
{'x': round(top_left_pos.x, 2), 'y': round(top_left_pos.y, 2)},

```

**Comment by chschlue** [comment]
@Sthing regarding this as abandoned, reopen if you're still on this.

**Pull request closed without merging**
