### PR TITLE
Add Nordic AQFN-73 package

### PR DESCRIPTION
**Pull request by ChristianHirsch**
Add AQFN-73 package based on [NRF52840 Datasheet](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52%2Fdita%2Fnrf52%2Fchips%2Fnrf52840.html).
image

### CODE REVIEW

**Comment by ChristianHirsch** [comment]
@SchrodingersGat @poeschlr

**Comment by poeschlr** [comment]
The exposed pad should have a reduced solder mask. (split into 2x2 or 3x3 smaller squares with space between them.)
This is explained in many application notes by many manufacturers. Example: https://www.nxp.com/docs/en/application-note/AN1902.pdf

**Comment by ChristianHirsch** [comment]
Hi @poeschlr, I split the EP to 2x2 squares with 0.3mm space between them. Is this better now?
image

**Comment by poeschlr** [comment]
Not the copper should be split. Only the paste layer.
Have a look at Package_SSOP:HTSSOP-20-1EP_4.4x6.5mm_P0.65mm as an example

**Comment by ChristianHirsch** [comment]
Alright, fixed it. Is it ok now?

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
