### PR TITLE
Updated fiducials to Surface Mount

### PR DESCRIPTION
**Pull request by evanshultz**
Fixes https://github.com/KiCad/kicad-footprints/issues/1045. Also see https://bugs.launchpad.net/kicad/+bug/1799601.

Fiducials do not show up in the POS (pick n place) report because they are Virtual type and to show up there they must be Surface Mount type. This is an apparent regression because, while the type has never been correct in KiCad v3 they appeared in the report (we don't know about v4). At any rate, they should be in the POS report so at least for now this is the solution.

Changes:
- Made all Surface Mount type
- Removed old syntax ("~" for pins without number, "(at 0 0)")
- Simplified keywords
- Removed duplicated German from description
- Removed excessive precision
- Set line widths as specified in KLC
- Converted double Cu circles to a single one

Some of the copper are drawings and not a pad, but I think the chance of an issue is extremely small so I left it alone. At a later date these could be converted to a custom pad shape if it's important.

Also, some of these footprint names are not intuitive and just poor. But... can't change them now.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
A second fab layer ref des has been added.

Other CI errors:
1. I must assume the silk fiducials work now so I'm loath to reduce silk line widths because the camera may have a harder time to locate them.
1. I've also not added a 3D model reference but I can if asked since I suppose there is something that could be shown in the 3D viewer.
1. Is a courtyard required on fiducials that won't need rework? Maybe to maintain placement clearance?
1. On some footprints there is nothing on the fab layer but I think that's OK as they don't need anything.
1. Silk/pad intersection is the silk on exposed fiberglass (the pad is removing mask) so that's fine.

**Comment by antoniovazquezblanco** [comment]
Fixes #1045.

Explanation: Using keyword to close the issue when this is merged.

**Comment by antoniovazquezblanco** [comment]
I had a look at this.

1. Agree
2. Agree
3. I would add a courtyard to tell the user to avoid placing anything inside the required perimeter for the camara to detect it.
4. Agree
5. Agree

Some of those fiducials are massive btw.
Could you please explain to me why there are fiducials in bottom layers with silk refdes in the top ones? Shouldn't bottom layers use mirrored top layer fiducials? Why do those exist?

Thanks

**Comment by evanshultz** [comment]
OK. I'll add courtyard and then we can merge if all else looks good.

**Comment by evanshultz** [comment]
Courtyard is added. I could add a fab circle or square to ones with no fab drawing so that the user, looking at the fab layer, would be able to see something was in that area. But I think it's a minor thing. These look fine in the 3D viewer as they are and our check script should be smarter to know if a pad does not have copper it's OK to have silk there (but we can ignore for now). Anything else?

I have no idea why all of these fiducials exist or why they're built as they are. I lean towards not changing things, but I agree with your questions and can't explain any of it. I've always used much smaller fiducials that are just a copper dot with a slightly bigger mask opening around it, with all elements on one side; I then mirror the fiducial when I needed one on the bottom side.

Note that IPC 2221A recommends a circular fiducial clearance that has a radius three times a circular fiducial (copper? silk?) radius. The minimum is double the radius. This is according to SMEMA (see Figure 5-6). I don't have access to 2221B so I can't say if things have changed.

**Comment by antoniovazquezblanco** [comment]
Merged as is. Opening an issue to be resolved in the future about those rare fiducials.

Thank you very much!

**Pull request merged**
