### PR TITLE
Vishay WSR2/3 footprint

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.vishay.com/docs/30101/wsr.pdf

Footprint:
r

r2

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Did you link the correct datasheet? At first glance the suggested footprint in it looks very different to what you submitted here.

**Comment by jneiva08** [comment]
fixed datasheet

**Comment by poeschlr** [comment]
@jneiva08 sorry for the late answer.

I would assume your small extension to the pads is meant as the connection point for the sensing connection when using this as a shunt. If this is the case then using a separate pad for it might be best.
This would provide a point to attach a second trace. (It would still need the same pin number assigned as the pads are touching.)

**Comment by jneiva08** [comment]
@poeschlr sorry for bothering.
When added the footprint added that extra pad like datasheet recommended.
It will be wise to remove or add extra pad like you say, but without F.Mask?

**Comment by poeschlr** [comment]
Why not both?
Add an option with extra pad and give it a suffix _KelvinConnection (The second pad must sadly have the same pad number as the first one.) And an option without it allowing users to use this part like a normal resistor.

**Comment by jneiva08** [comment]
@poeschlr  have made the alterations. need add the new screenshots and measurements?

**Comment by poeschlr** [comment]
That would help a lot.

**Comment by jneiva08** [comment]
Screenshot for R_Shunt_Vishay_WSR2_WSR3:
wsr

Screenshot for R_Shunt_Vishay_WSR2_WSR3_KelvinConnection
wsr_2

Sorry i cant put the measurements because the freecad is giving segmentation fault :(

**Comment by poeschlr** [comment]
Looks good, thanks

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
