### PR TITLE
Transformers: Add footprint for Excelitas ZS1052 AC ignition coil

### PR DESCRIPTION
**Pull request by mrnuke**
The ZS1052 AC is designed to trigger Xenon flashes by providing a 9kV+ impulse to the flash grid. This ionizes the gas inside the flash tube, allowing it to conduct electricity, and form an arc.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

[Datasheet](http://www.excelitas.com/downloads/ZS1052ACH.pdf)
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
-- 3D model coming soon
- [x] Check the output of the Travis automated check scripts - fix any errors as required

ac1052-fp

ac1052-3d

### CODE REVIEW

**Comment by aewallin** [comment]
some quick thoughts:
- F7.3 - Pin 1 should be rectangular or a rounded rectangle
- F5.2 - Fabrication layer: Footprint polarisation / location of pin-1 is drawn
- F5.1 - Silkscreen must not be placed over pads or areas of exposed copper. Clearance between silkscreen and exposed copper elements must be at least 0.2mm or more than the pad mask expansion (whichever is greater).

see: http://kicad-pcb.org/libraries/klc/

**Comment by mrnuke** [comment]
> some quick thoughts:

Thanks for the quick review! I'll get things fixed.

>     * F7.3 - Pin 1 should be rectangular or a rounded rectangle

Sorry, that's a bad idea for this footprint. With something that pulses in excess of 10kV, I one really wants to avoid any sharp corners.
>     * F5.2 - Fabrication layer: Footprint polarisation / location of pin-1 is drawn

How would I draw it? A dot next to pin 1? Encase pin 1 in a rectangle?

>     * F5.1 - Silkscreen must not be placed over pads or areas of exposed copper. Clearance between silkscreen and exposed copper elements must be at least 0.2mm or more than the pad mask expansion (whichever is greater).

OOPS. I was just fixing that. Forgot about it the first time. Should be fixed in updated  PR.

**Comment by aewallin** [comment]
F5.2.2 suggests a 1mm bevel on the F.Fab layer to indicate pin1.

**Comment by mrnuke** [comment]
[3D model PR](https://github.com/KiCad/kicad-packages3D/pull/492)

**Comment by mrnuke** [comment]
it-fits

**Comment by Misca1234** [comment]
Hi

All looks good, but could you add one minor detail, could you add the data sheet link in the document link field ?

bild

then we are ready to go

**Comment by mrnuke** [comment]
@Misca1234, I've added the datasheet link in a separate commit.

From my experience, by the time I need to use a footprint again in a few years time, the vendor's website is re-organized, and the link is dead.

**Comment by Misca1234** [comment]
I know, i have the same expereince wit ha lot of the 3D models i am creating, but when they work it is really good

**Pull request merged**
