### PR TITLE
Add Y14 Relay

### PR DESCRIPTION
**Pull request by asukiaaa**
Add Y14 relay.

http://www.hsinda.com.cn/en/ProductShow.asp?ID=208

screenshot from 2018-04-25 20-23-56

Thanks.

------------

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by asukiaaa** [comment]
Symbol: https://github.com/KiCad/kicad-symbols/pull/539

**Comment by asukiaaa** [comment]
Dear JAN

Thanks for checking and comments.
I updated footprint like this.

screenshot from 2018-04-27 20-42-43

3D model waits for mergning.
https://github.com/KiCad/kicad-packages3D/pull/302

Thanks.

**Comment by asukiaaa** [comment]
> the outline of F.Fab does not match the outlines of the packaged in the datasheet. Your rectangle is 7.1x12.2mm² but the datasheet says 7.6x12.3mm²

Sorry, I miss understood about outline setting.
I did set outline CrtYd, so I updated outline as F.Fab.

screenshot from 2018-04-28 09-51-06

Thanks.

**Comment by jkriege2** [comment]
Nearly there ... only two things remain:
1. please rename to `Relay_SPDT_HsinDa_Y14`
2. the clearances of F.CrtYd are still wrong:
2018-04-28 07_31_51-footprint editor no active library

Thanks,
JAN

**Comment by jkriege2** [comment]
Also: Please link the wrl-model file, not  the step! The latter is automatically used by StepUp instead of wrl (see Travis)!

Thanks,
JAN

**Comment by asukiaaa** [comment]
Thanks for the comments.

> please rename to Relay_SPDT_HsinDa_Y14

I did for this file and 3D model files.

> the clearances of F.CrtYd are still wrong:

Sorry, I miss this.
I updated this.

screenshot from 2018-04-28 15-30-36

> Also: Please link the wrl-model file, not the step! The latter is automatically used by StepUp instead of wrl (see Travis)!

Thanks for the information.
I removed reference for step file.

**Comment by jkriege2** [comment]
Thanks,
great work!

JAN

**Comment by asukiaaa** [comment]
Thanks for checking many time and merging.

**Pull request merged**
