### PR TITLE
Add USB-B connector Lumberg 2411 02

### PR DESCRIPTION
**Pull request by mibe**
Lumberg 2411 02 is a USB 2.0 type B receptacle.
[Datasheet](http://downloads.lumberg.com/datenblaetter/en/2411_02.pdf)

Unbenannt

I've already had a PCB made with that footprint, the part fits nicely:

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by mibe** [comment]
Here's another image from the bottom side:

**Comment by chmorgan** [comment]
Hello @mibe. Would you be willing to review another pending pull request here in exchange for me reviewing yours here? If so please reply with a link to the PR you reviewed and comment in that PR on your review of the changes.

**Comment by chmorgan** [comment]
@chschlue to confirm, should this be rotated so pin 1 is in the top left right?

**Comment by chmorgan** [comment]
Hi @mibe, the courtyard on the left and right sides is more than 0.25mm from the nearest feature, I think its 0.5, can you make it 0.25mm from the nearest feature? It looks 0.5mm on the top and bottom as well, that you make that 0.25mm from the center of the fab lines?

**Comment by chschlue** [comment]
Yes. Also, 0.5mm is correct for connectors.

**Pull request merged**
