### PR TITLE
adds footprints for Xilinx Kintex-7 BGAs

### PR DESCRIPTION
**Pull request by herostrat**
For more information please refer to: https://github.com/KiCad/kicad-footprints/issues/1560
and the script PR: https://github.com/pointhi/kicad-footprint-generator/pull/350

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks again!

**Comment by herostrat** [comment]
Thank you too!

@antoniovazquezblanco should this also be added to the 5.1.3 milestone?

**Comment by evanshultz** [comment]
Since I'm on top of this and merging right away, the milestone isn't adding much value because it's not a reminder to do something in the future. And as these are common additions to the library (as opposed to a bugfix) there's no reason they need to be merged for any particular release.

But I added the 5.1.3 milestone anyway. :)

**Comment by herostrat** [comment]
Ok, good for me.
I just thought because the others were marked and I was not sure why.

**Pull request merged**
