### PR TITLE
Add Ohmite_LVK20 4 contacts resistor

### PR DESCRIPTION
**Pull request by penoud**
add LVK20 4 contacts shunt resistor
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
https://www.mouser.com/pdfdocs/Ohmite_res_lvk.PDF
- [X] An example screenshot image is very helpful 
image
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
https://github.com/KiCad/kicad-packages3D/pull/385
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
You included two files here. One with and one without manufacturer name prefix. Please remove the one without prefix. I will look at the contribution it self later. (I am working on something else right now.)

**Comment by penoud** [comment]
Removed the LVK20 file.

**Comment by poeschlr** [comment]
Oh i just noticed, we should prefix the footprint with `R_Shunt` so it should be named `R_Shunt_Ohmite_LVK20`

The footprint it self looks good.

screenshot from 2018-08-28 10-46-41

**Comment by penoud** [comment]
I change the filename as requested. Add the datasheet link. But I add previously the LVK12 with a wrong filename. The R_Shunt_ prefix was missing.

**Comment by poeschlr** [comment]
The 3d model name also needs updating to use the new footprint name and it should use the file ending .wrl (I seem to have missed a lot in your other pull request.)

Regarding your other part, either open a new pull request that fixes that as well, do the fix in this pull request or i could do it.

**Comment by penoud** [comment]
Dear poeschlr, thank for your feedback and your explanation on the LVK12. I will do it. I updated for this PR the names of the 3d models to reflect filename change.

**Comment by poeschlr** [comment]
You still use step file ending in the 3d settings. please change that to wrl (kicad will automatically replace the file ending where it needs to do it.)

**Comment by penoud** [comment]
Ok I remove the step link. Since I was possible to enter several model I was thincking to put both. I didn't kow that kicad would replace the wrl by step automaticly if posssible. I will update my other PR. Thanks

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
