### PR TITLE
Add PT61017PEL Ethernet LAN Transformer

### PR DESCRIPTION
**Pull request by cpresser**
I could not find any LAN Transformers in the current library. So I added a generic one.
A matching symbol is here: https://github.com/KiCad/kicad-symbols/pull/1017

------------

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by nickoe** [comment]
I am not well versed in KLC, but I tried to review this and all looks ok, except the name of the footprint. I think it should be prefixed with Bourns_ like it is done for the Pulse transformers.

**Comment by Shackmeister** [comment]
Hi @cpresser 

Thanks for the contribution, a couple of things to fix before we merge it :)

- footprint should be rotated 90 deg CW so pin 1 is in the top left corner

- Name should probably be Transformer_Ethernet_Bourns_PT61017PEL

- Silk pin 1 indicator would be better with a line along pin 1 (see image)

- roundrects are recommended.

- silkscreen should be atleast 0,2mm away from the pads.

- courtyard clearance should be 0,25mm

- making the courtyards follow the shape, is alot nicer and will probably save some DRC errors :)

bourns_pt61017pel

**Comment by evanshultz** [comment]
While KLC hasn't been updated, IPC says silk can be the line width away from pads. This is almost universally 0.12mm.

**Comment by Misca1234** [comment]
@cpresser 
Try something like this

(module Transformer_Ethernet_Bourns_PT61017PEL (layer F.Cu) (tedit 5BC2ECF1)
  (descr https://www.bourns.com/docs/Product-Datasheets/PT61017PEL.pdf)
  (tags "LAN Ethernet Isolation Transformer")
  (attr smd)
  (fp_text reference REF** (at 0 -7.5) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value Transformer_Ethernet_Bourns_PT61017PEL (at 0 7.5) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start 3.45 -6.4) (end 3.45 6.4) (layer F.Fab) (width 0.1))
  (fp_line (start -3.45 -5.4) (end -3.45 6.4) (layer F.Fab) (width 0.1))
  (fp_line (start 3.45 -6.4) (end -2.45 -6.4) (layer F.Fab) (width 0.1))
  (fp_line (start 3.45 6.4) (end -3.45 6.4) (layer F.Fab) (width 0.1))
  (fp_line (start 3.58 -6.53) (end -3.57 -6.53) (layer F.SilkS) (width 0.12))
  (fp_line (start 3.58 5.1) (end 3.58 6.53) (layer F.SilkS) (width 0.12))
  (fp_line (start 3.58 6.53) (end -3.58 6.53) (layer F.SilkS) (width 0.12))
  (fp_line (start -3.58 6.53) (end -3.58 5.1) (layer F.SilkS) (width 0.12))
  (fp_line (start 5.5 -5.1) (end 5.5 5.1) (layer F.CrtYd) (width 0.05))
  (fp_line (start 3.7 6.65) (end -3.7 6.65) (layer F.CrtYd) (width 0.05))
  (fp_line (start -5.5 5.1) (end -5.5 -5.26) (layer F.CrtYd) (width 0.05))
  (fp_line (start -3.7 -6.65) (end 3.7 -6.65) (layer F.CrtYd) (width 0.05))
  (fp_text user %R (at 0 0) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start -2.45 -6.4) (end -3.45 -5.4) (layer F.Fab) (width 0.1))
  (fp_line (start -5.5 5.1) (end -3.7 5.1) (layer F.CrtYd) (width 0.05))
  (fp_line (start -3.7 5.1) (end -3.7 6.65) (layer F.CrtYd) (width 0.05))
  (fp_line (start 3.7 6.65) (end 3.7 5.1) (layer F.CrtYd) (width 0.05))
  (fp_line (start 3.7 5.1) (end 5.5 5.1) (layer F.CrtYd) (width 0.05))
  (fp_line (start 3.7 -6.65) (end 3.7 -5.1) (layer F.CrtYd) (width 0.05))
  (fp_line (start 3.7 -5.1) (end 5.5 -5.1) (layer F.CrtYd) (width 0.05))
  (fp_line (start 3.58 -6.53) (end 3.58 -5.14) (layer F.SilkS) (width 0.12))
  (fp_line (start -3.58 -6.53) (end -3.58 -5.14) (layer F.SilkS) (width 0.12))
  (fp_line (start -3.58 -5.14) (end -5.31 -5.14) (layer F.SilkS) (width 0.12))
  (fp_line (start -3.7 -6.65) (end -3.7 -5.26) (layer F.CrtYd) (width 0.05))
  (fp_line (start -3.7 -5.26) (end -5.5 -5.26) (layer F.CrtYd) (width 0.05))
  (pad 16 smd rect (at 4.4 -4.445 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 1 smd rect (at -4.4 -4.445 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 15 smd rect (at 4.4 -3.175 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 2 smd rect (at -4.4 -3.175 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 14 smd rect (at 4.4 -1.905 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 3 smd rect (at -4.4 -1.905 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 13 smd rect (at 4.4 -0.635 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 4 smd rect (at -4.4 -0.635 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 12 smd rect (at 4.4 0.635 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 5 smd rect (at -4.4 0.635 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 11 smd rect (at 4.4 1.905 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 6 smd rect (at -4.4 1.905 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 10 smd rect (at 4.4 3.175 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 7 smd rect (at -4.4 3.175 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 9 smd rect (at 4.4 4.445 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (pad 8 smd rect (at -4.4 4.445 270) (size 0.76 1.7) (layers F.Cu F.Paste F.Mask))
  (model ${KISYS3DMOD}/Transformer_SMD.3dshapes/Transformer_Ethernet_Bourns_PT61017PEL.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)

**Comment by Misca1234** [comment]
> So my idea is to make a footprint named "Transformer-Ethernet_SMD-16_12.7x7.1mm_P1.27"

If you do this, you can also remove the old ones but then you must update the symbols as well

**Comment by cpresser** [comment]
> > So my idea is to make a footprint named "Transformer-Ethernet_SMD-16_12.7x7.1mm_P1.27"
> 
> If you do this, you can also remove the old ones but then you must update the symbols as well

Afaik there are no "old ones". I could not find any ethernet transformer in the current libs. Am I missing something?

**Comment by antoniovazquezblanco** [comment]
You can find other transformers in the current libs. See the following examples:

https://github.com/KiCad/kicad-footprints/blob/master/Transformer_SMD.pretty/Transformer_Ethernet_HALO_TG111-MSC13.kicad_mod

https://github.com/KiCad/kicad-footprints/blob/master/Transformer_SMD.pretty/Transformer_Ethernet_Bel_S558-5999-T7-F.kicad_mod

An example symbol can be found at:
https://github.com/KiCad/kicad-symbols/blob/9b5f16596d5f4133258b6ec25ec26730199b22e6/Transformer.lib#L1809

**Comment by antoniovazquezblanco** [comment]
@Misca1234 which direction should this PR follow? Should it go generic or specific to this part?

Thanks!

**Comment by Misca1234** [comment]
@cpresser, @antoniovazquezblanco 
I dont mind generic, as long as cpresser want to sort it out

**Comment by cpresser** [comment]
I checked the existing items in the lib.
Halo TG111 is a different type of transformer with 24 pins (gigabit ethernet). So it does not overlap this PR, same for its symbol.

The Transformer_Ethernet_Bel_S558-5999-T7-F does overlap this PR. It was added in Dezember 2018, its basically a race-condition between those PRs.
https://github.com/KiCad/kicad-footprints/pull/1100

So, I see two options:
1. We keep the singular Bel_S558 footprint, and edit this one back to its original name (PT61017PEL)
2. Remove the Bel footprint and merge this one. The current BEL footprint also does not have round rects.

The Keywords of this FP already contain "S558", so users should be able to find it. 
Also, the previous PR has no symbol. I am unsure how people are supposed to use it.

**Comment by myfreescalewebpage** [comment]
Hi all!

I don't think we can make a generic footprint, just looking at this PR and #1100, I agree that we can solder the part on the same footprint (by hand at least), but when looking carefully to the product dimensions and recommended layout, they are different.

@evanshultz maybe your opinion ?

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Following my previous comment, I made the following comment:

- [ ] Name of the footprint should be `Transformer_Ethernet_Bourns_PT61017PEL`
- [ ] Fab layer has not the right dimensions, part is 6.9x12.8mm
- [ ] Pad position have too much digits ! Impossible to review correctly.
- [ ] Pad size have too much digits and are not correct, should be 0.76x1.7mm.

Need to make modifications above to perform complete review.

Cheers,
Joel

**Comment by cpresser** [comment]
Hi Joel,

I switched back to an atomic footprint.

**Comment by myfreescalewebpage** [comment]
Hi @cpresser 

Checked pad, Fab, Silkscreen, CrtYd layers, only one comment about this:

- [ ] The CrtYd rectangle clearance is only 0.2mm on the top and bottom of the footprint. Sbould be 0.25mm as recommended by the KLC. Image below. The silkscreen can also be moved accordingly to be sure it will not be overlapped by the part.

capture

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@cpresser ok for me, no more comment, merging the footprint.

Thanks for this great job :)

Cheers,
Joel

**Comment by cpresser** [comment]
Thanks for you patience :+1:

**Pull request merged**
