### PR TITLE
Bga676

### PR DESCRIPTION
**Pull request by vlunyov**
BGA-676 was added (based on BGA-672).
All links to 3D model, PDF document etc were changed to correct state.
It is usefull for XILINX FPGA Artix 7 and Kintex 7 users.
https://www.xilinx.com/support/documentation/package_specs/fg676.pdf

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you please post a screenshot?

**Comment by vlunyov** [comment]
bga-676

**Comment by vlunyov** [comment]
Only 4 pins were added to BGA-672 to make BGA-676. Also the Document Link and Keywords were changed.
bga-676-zoom

**Comment by vlunyov** [comment]
Of course the link to 3D model was changed too.

**Comment by poeschlr** [comment]
For BGA packages (especially for large ones) the courtyard clearance should be 1mm. (This is defined in IPC standards and should allow for reworking a PCB)

So this should be changed at least in new contributions. Ideally also in the original footprint you used as a basis for this one.

**Comment by poeschlr** [comment]
It should be 1.0mm +/-0.005mm such that it is on 0.01mm grid (See kicad library convention http://kicad-pcb.org/libraries/klc/F5.3/)

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
