### PR TITLE
add lvk12 4 contacts resistor

### PR DESCRIPTION
**Pull request by penoud**
add lvk12 4 contacts resistor. Datasheet reference link bellow.
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
https://www.ohmite.com/assets/docs/res_lvk.pdf
- [X] An example screenshot image is very helpful 
image
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
Yes PR #382 in the package-3d repository.
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
There should not be silk below the part as it would increase the risk of tombstoning. (There is no need for marking pin 1 as these parts are symmetrical.)

The courtyard clearance should be 0.25 (+/- 0.005)mm all around.
The outline in y direction is not quite right.
The pad spacing in x is not correct.

Add the manufacturer name as prefix to the footprint name.

screenshot from 2018-08-26 23-28-40

**Comment by penoud** [comment]
New screenshot:
image

**Comment by poeschlr** [comment]
Another suggestion: rotate the reference on the silk layer by 90 degree. This could allow it to use a larger font size while still fitting inside the outline.

**Comment by penoud** [comment]
Change according last comment. New screenshot:
image

**Comment by poeschlr** [comment]
I meant the reference that is shown in gray (fab layer) not the greenish one (silk layer)

**Comment by penoud** [comment]
Done. 
I got it now. I was not sure but your ref to silk confuse me ;-)

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
