### PR TITLE
Added footprint for connector DIN 41612  A-C

### PR DESCRIPTION
**Pull request by AndreaQ77**
New footprint with 2 rows spaced 5.08mm

*Replace this line with your commit message! Please provide a description of your pull request*

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by AndreaQ77** [comment]
3d model pull request:
https://github.com/KiCad/kicad-packages3D/pull/481

**Comment by aewallin** [comment]
Datasheet?
Screenshot?

**Comment by aewallin** [comment]
FWIW the current connector-footprints in the library seem to use small characters for the pin names e.g. "a1", "a2" and so on.
See existing footprints e.g. Connector_DIN:DIN41612_xxx

**Comment by evanshultz** [comment]
It looks like https://github.com/KiCad/kicad-footprints/pull/1076 may generate this footprint and many others via script. I much prefer the scripted approach.

**Comment by evanshultz** [comment]
@AndreaQ77 
Can you please check if these footprints will be part of the PR I mentioned above?

**Comment by evanshultz** [comment]
Scripted DIN 41612 footprints have been merged at https://github.com/KiCad/kicad-footprints/pull/1076. And IDC headers are now generated by a script as well and merged at https://github.com/KiCad/kicad-footprints/pull/1586. Closing this PR but thanks for the contribution! Additional footprints can be built using the scripts, if desired.

**Pull request closed without merging**
