### PR TITLE
Add Mini-Circuits PL-258 land-pattern

### PR DESCRIPTION
**Pull request by aewallin**
land-pattern PL-258
land pattern: https://ww2.minicircuits.com/pcb/98-pl258.pdf
component: https://ww2.minicircuits.com/pdfs/RMK-3-451+.pdf
package: https://ww2.minicircuits.com/case_style/TT1224.pdf

pl-258

symbol PR example: https://github.com/KiCad/kicad-symbols/pull/1201

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
- [ ] bevel to indicate pin1
- [ ] rotate? so pin1 is top left
- [ ] re-name to include case name TT1224
- [ ] 0.25mm courtyard
- [ ] reduce THT via-pad sizes so they don't overflow SMD GND-pads?
- [ ] description: case and land-pattern links.

**Comment by poeschlr** [comment]
Are you sure this part uses this numbering scheme? This is oposite to every other part by mini circuit you added so far.

If it does use this numbering scheme than i would suggest to include the suffix  _ClockwisePinNumbering in the footprint name to make it very clear to the user (similar to some Bosch LGA packages).

**Comment by aewallin** [comment]
re-named symbol and did major revisions. should be OK for review now.
pl-258

**Comment by poeschlr** [comment]
Regarding your open question: Yes please rotate such that pin 1 is on the top left corner.

Otherwise the footprint looks good.
screenshot from 2019-01-01 22-47-11

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
