### PR TITLE
adds shielded and unshielded version of Amphenols RJCSE connectors

### PR DESCRIPTION
**Pull request by herostrat**
Drawing:
https://cdn.amphenol-icc.com/media/wysiwyg/files/drawing/rjcsex38x01x.pdf

Datasheet:
https://www.mouser.de/datasheet/2/18/MODULAR_CAT-273815.pdf

grafik

Could someone verify that I got the numbering of the led pins right?
Just to have a second pair of eyes and current flowing through the LEDs

------------

I think the naming of the other Amphenol (e.g. RJ45_Amphenol_RJHSE538X.kicad_mod) should be also changed, because they neglet the number of connectors on each element.

e.g.
RJ45_Amphenol_RJHSE538X.kicad_mod -> RJ45_Amphenol_RJHSE538X-01.kicad_mod

Is this ok for everyone?

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you add a screenshot that shows the footprint from within kicad?

**Comment by herostrat** [comment]
Of course, sorry:

Shielded:
grafik

Unshielded:
grafik

**Comment by poeschlr** [comment]
Damn. Wanted to close and reopen this to get cla to update. Seems your branch was already deleted.
If you are still prepared to contribute these then please make a new pull request.

Sorry for the long delay by the way.

**Comment by herostrat** [comment]
No problem at all.

We can let it be closed as I am currently trying to generate the amphenol RJ45 stuff via scripting.
So we can hopefully have the full portfolio

**Pull request closed without merging**
