### PR TITLE
Adding BGA footprint for Analog/LT 28pin BGA

### PR DESCRIPTION
**Pull request by eeyrjmr**
Footprint for Analog/LT uModule switching regulator (28pin, 2x7).  
Associated symbol pull request: https://github.com/KiCad/kicad-symbols/pull/1667
Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/8063fa.pdf

Untitled

### CODE REVIEW

**Comment by eeyrjmr** [comment]
All travis issues cleared. This PR is ready for review

Untitled

**Comment by evanshultz** [comment]
Thanks for contributing to the official KiCad library!

Would you be willing to make this footprint using the script at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Package_BGA? It will match our library conventions better, be much easier to maintain. and be faster to review. If you need help let us know. This isn't required, to be clear.

**Comment by eeyrjmr** [comment]
ok I forked kicad-footprint-generator and added a section for Analog_BGA-28 ( https://github.com/pointhi/kicad-footprint-generator/pull/326 )

I change the footprint to be consistent with the other naming conventions and thus ill update the symbol

bga

**Comment by evanshultz** [comment]
Thanks! This looks really nice! I made a couple comments in the script PR which would affect the footprint.

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
