### PR TITLE
QFN-24-1EP_4x4mm_P0.5mm_EP2.15x2.15mm

### PR DESCRIPTION
**Pull request by dudelectric**
Push of 
**QFN-24-1EP_4x4mm_P0.5mm_EP2.15x2.15mm**  and **QFN-24-1EP_4x4mm_P0.5mm_EP2.15x2.15mm_ThermalVias** 
created with https://github.com/pointhi/kicad-footprint-generator/
**Pull Request link: https://github.com/pointhi/kicad-footprint-generator/pull/607**
**Pull Request for the Symbol: https://github.com/KiCad/kicad-symbols/pull/2959**
for part **LED1642GWQTR**
Part Datasheet: https://www.st.com/resource/en/datasheet/led1642gw.pdf
image

---

## :warning: Deprecation warning

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-footprints/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Review by chschlue — APPROVED** [review]
Thanks.

**Review by chschlue — CHANGES_REQUESTED** [review]
Oops.
TSSOP-24 snuck in here. Please leave that alone.

**Review by chschlue — APPROVED** [review]
Thanks

**Comment by dudelectric** [comment]
Thanks

**Pull request merged**
