### PR TITLE
 Finish #348: Magjack J1B1211CCD by Cetus 

### PR DESCRIPTION
**Pull request by poeschlr**
- Corrected minor mistakes with the NPTH pads
- Added fab, silk and courtyard outlines
- Corrected footprint name
- Better description and keywords

Finishes #348 
datasheet: https://wizwiki.net/wiki/lib/exe/fetch.php?media=products:wiz550web:wiz550webds_kr:j1b1211ccd.pdf

screenshot from 2018-08-29 16-45-24

screenshot from 2018-08-29 17-02-17

### CODE REVIEW

**Comment by Misca1234** [comment]
Is this a replacement for push
https://github.com/KiCad/kicad-footprints/pull/348
?

**Comment by poeschlr** [comment]
Yes. (Is even mentioned in the description above)

**Comment by Shackmeister** [comment]
Hi @poeschlr 

Can you fix the following?

- courtyard grid 

- add "_Horizontal" to name

- silk line in the top is not square

- perhaps a double corner would be a better pin 1 silk indicator

- if you feel like it, change the pin 1 rect to a roundrect

**Comment by poeschlr** [comment]
Fixed as suggested.

I did not change the pin 1 marking as i feel the missing corner style is closer to what IPC suggests.

**Comment by Shackmeister** [comment]
Thanks! :)

**Pull request merged**
