### PR TITLE
Uppercase D for diameter

### PR DESCRIPTION
**Pull request by strombom**
Changed names and paths to 3D models.

Issue: https://github.com/KiCad/kicad-footprints/issues/178

3D models pull request: https://github.com/KiCad/kicad-packages3D/pull/252

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
In https://github.com/KiCad/kicad-packages3D/pull/252 you renamed some crystal-3D models, which I didn't find in this PR ... (42 renamed 3D-files= 21 modles vs. 13 changed footprints in this PR)

**Comment by strombom** [comment]
@jkriege2

The crystals are twice as many in 3D-package (20) compared to in 3D-package-source (10).
3D-package has step and wrl files
3D-package-source only has FCStd files

These two exists in footprints but not in 3Dpackages or source:
kicad-footprints\Connector_Pin.pretty\Pin_D1.0mm_L10.0mm_LooseFit.kicad_mod
kicad-footprints\Connector_Pin.pretty\Pin_D1.3mm_L11.0mm_LooseFit.kicad_mod

The loosefit footprints have 1.2 mm drill holes. The normal have 1.0 mm drill holes. Maybe the thought is that both footprints should reference the same 3D models? Should I change the reference?

**Comment by strombom** [comment]
Now I have renamed footprint references to 3D-packages.

Also renamed files in Button_Switch_THT, Crystal and Inductor_SMD with lower case h, w and l.

Footprint pull request: https://github.com/KiCad/kicad-footprints/pull/337
Package 3D pull request: https://github.com/KiCad/kicad-packages3D/pull/252
Package 3D source pull request: https://github.com/KiCad/kicad-packages3D-source/pull/99

**Comment by poeschlr** [comment]
I assume your additional changes do not require further symbol updates. Is that correct?

**Comment by strombom** [comment]
I have searched through the symbol library for lower case parameters but can't seem to find any, so it "should" not require more updates.

There are no crystal, button or inductor libraries in symbols either so that shouldn't be a problem either.

**Comment by poeschlr** [comment]
The button_switches models and footprint names do not agree with each other. It seems the footprints have added SPST to the name before the number of switches.

The [testscript](https://github.com/KiCad/kicad-library-utils/blob/master/packages3d/check_3dmodels.py) also reports an error for some of the models in the crystals lib (run with -v to get the same output i got):
- Mislabeled 3D model 'Resonator-3pin_W6.0mm_H3.0mm'
- Mislabeled 3D model 'Crystal_HC49-U-3pin_Vertical'
- Mislabeled 3D model 'Resonator_muRata_DSS6-3pin_W7.0mm_H2.5mm'
- Mislabeled 3D model 'Resonator_muRata_DSN6-3pin_W7.0mm_H2.5mm'
- Mislabeled 3D model 'Resonator-2pin_W8.0mm_H3.5mm'
- Mislabeled 3D model 'Crystal_HC52-U-3pin_Vertical'
- Mislabeled 3D model 'Resonator-3pin_W7.0mm_H2.5mm'
- Mislabeled 3D model 'Resonator-2pin_W6.0mm_H3.0mm'
- Mislabeled 3D model 'Resonator_muRata_CSTLSxxxX-3pin_W5.5mm_H3.0mm'
- Mislabeled 3D model 'Resonator-2pin_W10.0mm_H5.0mm'
- Mislabeled 3D model 'Resonator-2pin_W7.0mm_H2.5mm'
- Mislabeled 3D model 'Resonator-3pin_W8.0mm_H3.5mm'
- Mislabeled 3D model 'Resonator-3pin_W10.0mm_H5.0mm'
- Mislabeled 3D model 'Resonator_muRata_CSTLSxxxG-3pin_W8.0mm_H3.0mm'

Not sure if you introduced these errors. If not i can merge as is. (Can be fixed in a different PR)

**Comment by strombom** [comment]
It might be my fault, it's the "pin" / "Pin" that has been changed. I can go throught the folders and check.

Which one is correct, "pin" or "Pin"?

**Comment by poeschlr** [comment]
I would say "Pin" is the correct version.

**Comment by strombom** [comment]
Lowercase pin in kicad_mod files have been changed to Pin and filenames have been changed as well.

There are a few capacitors with _3pin. The other components have a dash instead -3Pin. Which one is correct, should I change it to _3Pin or -3Pin?

I'm a bit confused regarding the button switches, how to best figure out matching names?

**Comment by strombom** [comment]
Maybe all "-XPin" should be renamed to "_XPin"?

**Comment by poeschlr** [comment]
No we have a - as a separator between the package name and the number of pins in all other footprint names. So the - is ok.

The switches can be fixed in a different pull request. Somehow there the footprint names have changed but the 3d models have been forgotten to be updated.

I will check this pr later today. I need a bit of a break right now.

**Comment by poeschlr** [comment]
Looks good. Thanks (every remaining problem example the switches can be fixed in a different PR)

**Pull request merged**
