### PR TITLE
added a HDMI Plug from Global Technology

### PR DESCRIPTION
**Pull request by Shackmeister**
added a HDMI Plug

Datasheet:
http://www.contactswitch.com/en/download.aspx?id=1449

Screenshot:
hdmi connector

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Is it possible that we do net yet have a symbol for HDMI connectors?

**Comment by Shackmeister** [comment]
Yup I couldn't find one, i have a symbol but its not KLC compliant what so ever.

**Comment by poeschlr** [comment]
The footprint looks good. I made an issue for the missing symbol.

**Comment by Shackmeister** [comment]
Nice, and you agree with the name?

**Comment by poeschlr** [comment]
Did not look wrong to me but now that you ask i am not so sure any more :)

**Comment by Shackmeister** [comment]
Well I tried my best to align with this and the USB connector but there seems to be some inconsistensy

**Comment by Shackmeister** [comment]
https://github.com/KiCad/kicad-footprints/pull/251

**Pull request merged**
