### PR TITLE
coaxial connector sma molex 73251-2200 horziontal

### PR DESCRIPTION
**Pull request by aewallin**
Molex horizontal SMA-connector with long threaded part.
There might be similar parts from Cinch, Amp/TE - can be created as aliases later. The threads extend 16.5mm from the center-pin on this part.
Not sure if a "PCB-edge" line is required (other footprints seem to have this un Dwgs.User layer?)

Datasheet:
https://www.molex.com/pdm_docs/sd/732512200_sd.pdf
3D drawing: https://www.molex.com/pdm_docs/adobe3D/73251-2200.pdf

Screenshot:
molex_sma

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Thanks for this addition.

Sadly some of the dimensions of this footprints do not quite agree with the datasheet. Additionally the courtyard clearance must be 0.5mm all around for connectors (+/-0.005mm as it needs to be on 0.01mm grid)
For more details about that see the dimensioned drawing created from your footprint.
molex_sma svg

**Comment by aewallin** [comment]
Thanks for the detailed review. I tried to fix the issues found.
I don't quite understand the courtyard tolerance of 0.5 +/- 0.005 mm.
If the KLC requires courtyard to be on a 0.1 mm grid then the tolerance should be 0.5 +/- 0.05 mm to be compatible with the 0.1mm grid rule?

**Comment by poeschlr** [comment]
The KLC specifies 0.01 not 0.1

**Comment by poeschlr** [comment]
Looks good now. Thanks.

For reference the updated drawing.
screenshot from 2018-12-05 21-16-35

**Pull request merged**
