### PR TITLE
renamed SOT669 to LFPAK56

### PR DESCRIPTION
**Pull request by daviid5**
following #313 
regarding this closed PR https://github.com/KiCad/kicad-footprints/pull/481
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Ratfink** [comment]
Thanks for making these changes!  Just one thing: it looks like you accidentally duplicated the word "LFPAK" in the descriptions for the _ThermalVias footprints.

Will you be making PRs for the 3D model changes I mentioned in https://github.com/KiCad/kicad-footprints/pull/481#issuecomment-380206441, or would you like me to handle that?

**Comment by Ratfink** [comment]
Oh, the 3D model filenames and value texts need to be updated with the new names as well.

**Comment by daviid5** [comment]
It would be nice if you could make the changes in the 3D-Models, I have no clue ho to do this
FYI, the packages with the thermal vias are violating F6.2 ( Footprint anchor is not located at center of footprint), I think this is acceptable, because then the different packages (with or without the thermal vias) ware interchangeable, because the pins 1-4 are in every package variant at the same absolute position.

**Comment by Ratfink** [comment]
Okay, I made PRs for the 3D model changes.  Now if you could make the three changes I described above, this should be ready to merge.

**Comment by Ratfink** [comment]
Hey, it's been a week, so I'm just checking in.  Do you think you'll be able to make the small changes I described above soon, so this can be merged?

**Comment by Ratfink** [comment]
I think all this needs now is the minor description changes I mentioned above:

> Just one thing: it looks like you accidentally duplicated the word "LFPAK" in the descriptions for the _ThermalVias footprints. Remove the duplicate words please, and maybe change "LFPAK" to "LFPAK56" in all the descriptions.

**Comment by Ratfink** [comment]
@daviid5 Just checking in—Do you think you'll be able to finish this soon?

**Comment by Ratfink** [comment]
Okay, I did it myself because the remaining change was so tiny and the original contributor has been gone for over a month.

**Pull request merged**
