### PR TITLE
Connector_JST: add XA (horizontal + vertical)

### PR DESCRIPTION
**Pull request by fenugrec**
Generated from scripts "conn_jst_XA_vertical.py" and
"conn_jst_XA_horizontal.py" , from  https://github.com/pointhi/kicad-footprint-generator/pull/484

The vertical variant ("top entry") has two types, with / without a plastic locating boss. The script and this PR generate both types. Screenshot shows type "with boss"

Datasheet for XA series : https://www.jst-mfg.com/product/pdf/eng/eXA1.pdf

JST_XA

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by fenugrec** [comment]
Still ready to merge; minor non-fonctional changes to silkscreen and courtyard from upstream script ( https://github.com/pointhi/kicad-footprint-generator/pull/525 )

**Comment by fenugrec** [comment]
I've confirmed at least the `JST_XA_S04B-XASK-1_1x04_P2.50mm_Horizontal` footprint works :

IMG_20200423_102611965c2

**Comment by jhalmen** [comment]
gentle ping
@evanshultz anything one can do to help this along?

**Comment by evanshultz** [comment]
@fenugrec @jhalmen 
Sorry for the terribly long delay. We're almost against the wire on getting this merged before switching to GitLab, but I'm finally looking at this now.

**Comment by evanshultz** [comment]
@fenugrec @jhalmen 
1. Should `JST_XA_B18B-XASK-1_1x18_P2.50mm_Vertical` be here? I don't see any 18 pin parts in the datasheet. It was discussed at https://github.com/pointhi/kicad-footprint-generator/pull/484 so I think the datasheet may have been updated.
1. The silk looks rather excessive, but these footprints can still be merged. The horizontal ones are obvious how they are inserted without any extra silk under the part body. This makes the file and library bigger unnecessarily. Scale this across hundreds of footprints and you can understand the caution. I therefore didn't check this closely.

I made more comments in the script PR, but most of them don't affect the footprints. So really just resolving the mystery of the 18 pin footprint is holding this back, I think.

I apologize for the long delay in getting to this. I will likely merge this before the GitHub closing cutoff in several hours if I don't hear anything from either of you. Thanks again for the great collaboration and hard work to tag team this footprint family!

**Comment by fenugrec** [comment]
>     1. Should `JST_XA_B18B-XASK-1_1x18_P2.50mm_Vertical` be here?
It's at least in https://www.jst-mfg.com/product/pdf/eng/eXA1.pdf that I downloaded 2 minutes ago ? where are you getting your copy ?
Can we leave it in please, IMO whether or not it's orderable at a precise date is beside the point. It exists/existed, and anyway no sane user would go ahead and make a design that depends on this being available forever ?

>     2. The silk looks rather excessive,
Yes. IIRC I was basing on other JST syms, but I agree it could / should be reduced/simplified.

> I made more comments in the script PR
I skimmed over them; I hope they won't disappear in the migration, because they should be looked at + fixed but I absolutely don't have time to look at this (and the generating script) at the moment.

**Comment by evanshultz** [comment]
That's strange. I have https://www.jst-mfg.com/product/pdf/eng/eXA1.pdf open in another tab, I just refreshed, and I'm an idiot. I looked a couple times and missed it. It is there.

I will merge this since the script updates don't affect the footprints, then. Sorry for the false alarm!

**Comment by fenugrec** [comment]
Thanks !

**Pull request merged**
