### PR TITLE
Adding newly created smd versions for jst connectors.

### PR DESCRIPTION
**Pull request by poeschlr**
This pull request adds the footprints generated with the now generalized smd connector script.
Script location: https://github.com/pointhi/kicad-footprint-generator/pull/81

This will add a new version of the following footprints added in the past. (Back then each series had it's own generator script.)
- GH series https://github.com/KiCad/kicad-footprints/pull/25
    - http://www.jst-mfg.com/product/pdf/eng/eGH.pdf
- SHL series https://github.com/KiCad/kicad-footprints/pull/27
    - http://www.jst-mfg.com/product/pdf/eng/eSHL.pdf
- PH smd version (SM4) https://github.com/KiCad/kicad-footprints/pull/26
    - http://www.jst-mfg.com/product/pdf/eng/ePH.pdf

In addition it also adds:
- ACH
    - http://www.jst-mfg.com/product/pdf/eng/eACH.pdf
- AUH
    - http://www.jst-mfg.com/product/pdf/eng/eAUH.pdf
- LEA
    - http://www.jst-mfg.com/product/pdf/eng/eLEA.pdf
- SFH
    - http://www.jst-mfg.com/product/pdf/eng/eSFH.pdf
- SH
    - http://www.jst-mfg.com/product/pdf/eng/eSH.pdf
- SUR
    - http://www.jst-mfg.com/product/pdf/eng/eSUR.pdf
- XAG
    - http://www.jst-mfg.com/product/pdf/eng/eXAG.pdf
- ZE
    - http://www.jst-mfg.com/product/pdf/eng/eZE.pdf

I will add screenshots in comments. (And yes some of these "series" only have one footprint in them. They are still script generated.)

### CODE REVIEW

**Comment by poeschlr** [comment]
ACH series connectors:
http://www.jst-mfg.com/product/pdf/eng/eACH.pdf
3 generator entries (1pol, 2/3pol, 4/5pol)

screenshot from 2017-11-11 16-59-21
screenshot from 2017-11-11 16-43-12
screenshot from 2017-11-11 16-47-31
screenshot from 2017-11-11 16-50-04

---

AUH series (ok there is only one here)
http://www.jst-mfg.com/product/pdf/eng/eAUH.pdf
screenshot from 2017-11-11 16-59-30
screenshot from 2017-11-11 16-54-26

**Comment by poeschlr** [comment]
JST GH:
http://www.jst-mfg.com/product/pdf/eng/eGH.pdf
screenshot from 2017-11-11 17-45-30
screenshot from 2017-11-11 17-32-33

screenshot from 2017-11-11 17-35-00


Single connector JST LEA 2pol
http://www.jst-mfg.com/product/pdf/eng/eLEA.pdf
screenshot from 2017-11-11 17-44-58

screenshot from 2017-11-11 17-42-46

**Comment by poeschlr** [comment]
JST SFH (again only one footprint. Not really possible to create it with my script in a good way. But i had it already in there before i noticed that i made a mistake.)
http://www.jst-mfg.com/product/pdf/eng/eSFH.pdf
screenshot from 2017-11-11 18-23-43
screenshot from 2017-11-11 18-23-37

JST PH (SMD versions -> SM4 in name)
http://www.jst-mfg.com/product/pdf/eng/ePH.pdf
screenshot from 2017-11-11 18-23-56

screenshot from 2017-11-11 18-01-27
screenshot from 2017-11-11 17-55-31

**Comment by poeschlr** [comment]
SH series:
http://www.jst-mfg.com/product/pdf/eng/eSH.pdf
screenshot from 2017-11-11 18-59-02
screenshot from 2017-11-11 18-55-54
screenshot from 2017-11-11 18-52-32


SHL series
http://www.jst-mfg.com/product/pdf/eng/eSHL.pdf
screenshot from 2017-11-11 18-59-11
screenshot from 2017-11-11 18-58-48

**Comment by poeschlr** [comment]
SUR series:
http://www.jst-mfg.com/product/pdf/eng/eSUR.pdf
screenshot from 2017-11-11 19-13-14
screenshot from 2017-11-11 19-08-35
screenshot from 2017-11-11 19-05-01

XAG (only the 5 pin variant exists. And it is still script generated.)
http://www.jst-mfg.com/product/pdf/eng/eXAG.pdf

screenshot from 2017-11-11 19-13-23
screenshot from 2017-11-11 19-12-44

**Comment by poeschlr** [comment]
Finally merge-able!

Here the stuff about ZE series:
http://www.jst-mfg.com/product/pdf/eng/eZE.pdf
screenshot from 2017-11-11 19-22-16
screenshot from 2017-11-11 19-21-46
screenshot from 2017-11-11 19-23-17

**Comment by SchrodingersGat** [comment]
Thanks, the screenshots look good, Travis is happy, and I trust you've read the datasheets well :)

**Pull request merged**
