### PR TITLE
Add Infineon_PG-HDSOP-10-1

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.infineon.com/cms/en/product/packages/PG-HDSOP/PG-HDSOP-10-1/

Seems similar to the PG-HSOF footprints which are in this lib. Plus, it's conceptually a pair of DPAK devices end-to-end and DPAK is in the lib.

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Dimensioned drawing (I fixed the top and bottom courtyard after this):
image

Also fixed 3D model directory and added a few more keywords.

**Comment by poeschlr** [comment]
Why is the courtyard clearance 0.5mm in y direction and 0.25 in x?
Everything else seems good to merge.

**Comment by evanshultz** [comment]
A brain fart was the root cause, but see above the drawing where I caught this error and already addressed it. This should be ready to merge. Thanks for checking it out!

**Comment by poeschlr** [comment]
Ok i did not notice that remark.

**Pull request merged**
