### PR TITLE
Connector Abracon RJ45 ARJP11A-MA

### PR DESCRIPTION
**Pull request by ppielorz**
Added Ethernet RJ45 jack connector footprint.
Datasheet: https://abracon.com/Magnetics/lan/ARJP11A.PDF

Screenshot:
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi, thanks for your contribution.

Please, make sure that the courtyard clearance is 0.5 mm (for both pads and fab outline). Now it is 0.68 mm. After change this, I will do the review.

image

**Comment by ppielorz** [comment]
I've corrected courtyard lines according to your remark.

**Comment by gmsotavio** [comment]
Hi @ppielorz,

There a few wrong dimensions. Please, check the dimensioned drawing bellow.

image

**Comment by gmsotavio** [comment]
image

**Comment by gmsotavio** [comment]
Looks good! I going to review the symbol before merge this.

For reference:
image

**Pull request merged**
