### PR TITLE
Connector_BarrelJack: Add CLIFF FC681465S DC socket

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Connector_BarrelJack: Add CLIFF FC681465S DC socket

Datasheet: https://www.cliffuk.co.uk/products/dcconnectors/DualDCSockets.pdf
BarrelJack_CLIFF_FC681465S_SMT_Horizontal

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by piotr-wiszowaty** [comment]
Correct datasheet: https://www.cliffuk.co.uk/products/dcconnectors/FC681465S.pdf

**Comment by chmorgan** [comment]
Hi @piotr-wiszowaty can you git rebase and collapse the three commits into one? Also, can you go through the checklist in the first post here in the PR and check off the tasks that you've completed?

**Comment by poeschlr** [comment]
No please don't. we squash merge so please keep the history of the pull request itself intact.

**Comment by chmorgan** [comment]
@poeschlr doh, I'll keep that in mind for future reviews.

**Comment by piotr-wiszowaty** [comment]
OK, tasks checked.

**Comment by chmorgan** [comment]
Hi @piotr-wiszowaty.

- The dimensions look good, I checked the pins, overall component size, and pad sizes

- The pin numbering looks incorrect. The data sheet says "component side" vs. "bottom side" but looking at your footprint the pins are reversed as if looking up through the pcb. Have you verified the pinout with the physical part?

**Comment by piotr-wiszowaty** [comment]
Yes, one of the datasheets (the first one I linked to) is incorrect. The 
second one matches
the actual physical components (which I verified).

**Pull request merged**
