### PR TITLE
TO-277A center footprint anchor

### PR DESCRIPTION
**Pull request by strombom**
TO-277A
Datasheet: https://www.vishay.com/docs/95570/to-277asmpc.pdf

Moved all geometry in order to center the footprint anchor, it was slightly shifted in y-direction.

Added small marker in silkscreen for pin 1.

image

image

image

3D Model added: https://github.com/KiCad/kicad-packages3D/pull/239

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by strombom** [comment]
Updated pin marker and fab outline:

- Changed pin marker to chamfer.
- Changed fab outline to nominal dimension.

image

**Comment by strombom** [comment]
Changed paste mask to 60%

image

**Comment by strombom** [comment]
Smaller distance between hatch pattern: 0,55mm

image

**Comment by poeschlr** [comment]
Looks good thanks

**Pull request merged**
