### PR TITLE
Added HTSSOP-14-1EP_4.4x5.0mm_P0.65mm_EP3.4x5.0mm_Mask3.0x3.1mm

### PR DESCRIPTION
**Pull request by cnieves1**
Generated using: https://github.com/pointhi/kicad-footprint-generator/pull/510
Datasheet: http://www.ti.com/lit/ds/symlink/lm5161.pdf#page=34
Package drawing: http://www.ti.com/lit/ml/mpds370/mpds370.pdf
Custom TI name: R-PDSO-G14 (PWP)
imagen
Captura de pantalla de 2020-03-16 11-27-54

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chmorgan** [comment]
Hi @cnieves1, can you explain why the drawing is showing a smaller EP than the part does?

**Comment by cnieves1** [comment]
I don't fully understand the issue...

Central pad dimension is specified by solder mask size, as other footprints do, like, for example:
  HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.4x3.7mm
Copper under central pad is bigger than central pad in order to improve thermal transfer.
If you look at the footprint with thermal vias (HTSSOP-14-1EP_4.4x5mm_P0.65mm_EP3.4x5mm_Mask3x3.1mm_ThermalVias):
Captura de pantalla de 2020-03-16 22-46-45

Is that what you are asking?

**Comment by chmorgan** [comment]
@cnieves1 ahh thats exactly it. For whatever reason the footprint isn't rendering mask correctly. It's rendering mask and then copper on top, thanks for pointing that out.

**Comment by chmorgan** [comment]
@cnieves1 the recommended land pattern in the datasheet doesn't match with the lands in the part. For example the pads are 1.575mm long but the datasheet indicates 1.78mm. Am I looking in the wrong place?

**Comment by cnieves1** [comment]
No, you are right. 
In this case, I think the footprint generator  calcules the land pattern based on physical dimensions (both body and legs), using IPC rules.
Therefore the generated footprint usually doesn't match the manufacturer's recommended footprint.
If the IPC rules built into the generator are right, the footprint would be ok.
In other PRs, the general recommendation is using this generator whenever possible, so I hope it is doing the right thing...

**Comment by evanshultz** [comment]
@chmorgan 
Correct. See readme at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO.

For scripted entries you will review if the package dimensions entered into the script match in the datasheet, disregarding the recommended footprint. If they do, and the footprint doesn't have an weird error that stands out, merge the footprint and add a comment on the script repo that the footprint has been merged.

**Comment by chmorgan** [comment]
@evanshultz appreciate the tip and it makes sense that the the values might not match exactly.

**Pull request merged**
