### PR TITLE
Added TWELITE SMD (JN5164/5169 breakout module)

### PR DESCRIPTION
**Pull request by true-nature**
Datasheet: [https://www.mono-wireless.com/jp/products/TWE-LITE/MW-PDS-TWELITE-JP.pdf](https://www.mono-wireless.com/jp/products/TWE-LITE/MW-PDS-TWELITE-JP.pdf) (Japanese only, see page 6)
Dimensions: [https://www.mono-wireless.com/jp/products/TWE-LITE/TWE-L-size2.png](https://www.mono-wireless.com/jp/products/TWE-LITE/TWE-L-size2.png)
[3D model PR](https://github.com/KiCad/kicad-packages3D/pull/282)
It has an oval NPTH for soldering antenna wire.
Screenshot:
twelite_fp
twelite_fp_3dsetting
twelite_3d_top_w_ant

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I would assume that there might be the requirement that no copper should be placed below the antenna. (Add a keepout marking as is done with other rf module footprints)

Even if this is not the case, there should be an area where no other components can be placed (as the antenna is in the way) So at least the courtyard should be extended that way.

**Comment by true-nature** [comment]
I am sorry I missed the explanation.
If it is the antenna shown in the screenshot shown above, keepout marking will be required as you pointed out.

TWELITE wire antennas are not limited to one type, but there are three types of patterns even if they are sold as products. Of these, a matchstick like a red cap standing upright on the board does not need to add keepout marking. 
[WIREANTENNAS](https://www.mono-wireless.com/jp/products/TWE-ANTENNAS/omni/wireantennas.png)

Also, it is not necessary to add keepout marking on modules with U.FL jacks installed instead of wire antennas.
[TWELITE with U.FL jack](https://www.mono-wireless.com/jp/products/TWE-LITE/ant-contact-0.jpg)

In combination with modules and antennas, the type of footprint will increase, so in this pull request only the basic part of the module that does not include the antenna is included.
twelite_3d_top

**Comment by poeschlr** [comment]
The courtyard clearance should be 0.25mm +-0.05 (currently is 0.215)
The footprint name might not be specific enough. It seems you only named it after the company alone instead of including the part number or at least the part family in the name.

how did you decide on the large NPTH pad for the antenna?

For reference the dimensioned drawing created from the footpirnt
screenshot from 2018-05-08 16-43-35

**Comment by true-nature** [comment]
- Fixed courtyard clearance
- Renamed TWELITE to it's part number TWE-L-WX
- Renamed TWELITE_DIP to TWE-L-DP-W

An example of large NPTH for the antenna is illustrated in the datasheet(page 7).
The NPTH in example conflicts with pad 29,30,31,32,. My design has enough clearlance for these pads.
[DataSheet](https://mono-wireless.com/jp/products/TWE-LITE/MW-PDS-TWELITE-JP.pdf)

As illustrated in example, TWELITE DIP has a large NPTH for the antenna.
[TWELITE DIP PCB](https://mono-wireless.com/jp/products/TWE-Lite-DIP/asset/smd-pcb.png)

**Comment by true-nature** [comment]
Usage of the NPTH for the wire antenna is demonstrated in this video.
[How to soldering the TWELITE DIP](https://www.youtube.com/watch?v=VvpRGxkQ9fg) (from 01:05 to 01:30 of 03:29)

**Comment by Shackmeister** [comment]
Hi @true-nature The name for these is typically Manufacturer_Partnumber

could you please change the silk pin 1 to an "extra corner"?

**Comment by Misca1234** [comment]
We are all satisfied with this foot print and can merge it ?

**Comment by poeschlr** [comment]
The courtyard clearance is 0.265 instead of 0.25 (+/-0.005)

**Comment by true-nature** [comment]
I think that the courtyard clearance is already expanded from 0.215 to 0.265 since [commit 1e001e9](https://github.com/KiCad/kicad-footprints/pull/448/commits/1e001e9cc099a7119b108cd018ca5cb064f2e9ee).

**Comment by poeschlr** [comment]
It is expanded too much. should be 0.255 at most

**Comment by true-nature** [comment]
Sorry. I misunderstood. I'll decrease it.

**Comment by Shackmeister** [comment]
Hi @true-nature 

The script is showing your Courtyard is not on 0,01mm grid, can you please fix this?

**Comment by Misca1234** [comment]
@poeschlr  @Shackmeister 
Are you happy with true-nature's changed (if so, I will merge)

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
