### PR TITLE
Added D_DO-247-2_Vertical

### PR DESCRIPTION
**Pull request by aris-kimi**
This footprint is a copy of TO-247-2_Vertical from Package_TO_SOT_THT library renamed.

Found in this diode datasheet: https://www.st.com/resource/en/datasheet/stbr3012-y.pdf

3D PR: https://github.com/KiCad/kicad-packages3D/pull/710

EDIT:
d_do-247

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chschlue** [comment]
Please add a cathode silk marker for this diode-specific version.
Also, would you like to add horizontal variants for completeness?

**Comment by aris-kimi** [comment]
Hi @chschlue , i am not sure how to mark cathode. Is just a vertical line between pads, near cathode pin, acceptable?
I am also not sure i understood you correctly. By horizontal variants you mean horizontal lines on the top of the symbol to indicate heatsink position?

diode

**Comment by chschlue** [comment]
> Hi @chschlue , i am not sure how to mark cathode. Is just a vertical line between pads, near cathode pin, acceptable?

Yes. It's more or less up to you, but that's how it's been done for most THT diodes, I think.

> I am also not sure i understood you correctly. By horizontal variants you mean horizontal lines on the top of the symbol to indicate heatsink position? (noted area)

No, I was talking about diode versions of TO-247-2_Horizontal* (leads bent 90 degress and package flat on the board).

Another thing: I'm not sure the `-2` pin count suffix is necessary.

**Comment by aris-kimi** [comment]
Oh, cool, yes i am on it. I will deal with it after work. I'll add cathode mark, remove `-2 `and add the other variants in the same branch.

**Comment by aris-kimi** [comment]
I think that was the best approach i could thought.. If ok i will proceed with symbol's footprint name and footprint's 3D symbols.
I was wondering, do we need extra a _TadDown with an exposed pad?

**Comment by chschlue** [comment]
LGTM so far.
What do you mean, extra _TabDown?

**Comment by aris-kimi** [comment]
Something with an exposed pad for solder connected... If you understood what i mean, it will be ok i guess to add in a future PR...

**Comment by chschlue** [comment]
I think I get it now...
AFAIK, TO-247 is isolated all around and has no conductive tab like, say, TO-220. Am I mistaken?

**Comment by aris-kimi** [comment]
Honestly i don't know.. I am not sure if conductive tabs are used same way from all manufacturers per package type, but we can consider heat dissipation as a need, and the lack of heat sink in a design, if can be avoided, is a pro in my opinion. If you think we can add something for this purpose, inform me and i'll deal with it in a new PR.
Thank you for your comments and i am sorry for not making myself clear in the first place.

**Comment by chschlue** [comment]
I don't think that's very useful as a one-size-fits-all solution. Thermal management is very project-specific.

Our DPAK FP, for example, has copper under the tab, but first and foremost as an electrical connection. It can (and is supposed to) of course be used as a heatsink by adding a copper zone around it, vias, and so on, manually, case-by-case, according to your specific requirements.
I don't see how adding a random patch of copper (and perhaps mask cutout) under a TO-247 package takes any work off users' backs.

**Pull request merged**
