### PR TITLE
Button_Switch_SMD: Add a 6x6 1P1T button

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Re push: https://github.com/KiCad/kicad-footprints/pull/1161

https://www.ckswitches.com/media/1471/pts645.pdf

Screenshot from 2019-03-14 20-02-48

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
You moved the courtyard in y direction. I think it was correct the first time around. (In that direction the body is what defines where it should be not the pads.)

Screenshot from 2019-03-21 06-17-11

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by poeschlr** [comment]
thanks

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
