### PR TITLE
Filter: Add 1FPxx - EMI filter

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Filter: Add 1FPxx - EMI filter

Datasheet: https://filtercon.com.pl/wp-content/uploads/2019/07/Karta-katalogowa-FP-12-1.pdf

1FPxx

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by piotr-wiszowaty** [comment]
Symbol: [https://github.com/KiCad/kicad-symbols/pull/2313](https://github.com/KiCad/kicad-symbols/pull/2313)

**Comment by piotr-wiszowaty** [comment]
Footprint: [https://github.com/KiCad/kicad-footprints/pull/1966](https://github.com/KiCad/kicad-footprints/pull/1966)

**Comment by piotr-wiszowaty** [comment]
Please, scratch my last comment (wrong tab).

**Comment by poeschlr** [comment]
There are two different lead layouts in the datasshet (grey vs blue background of the drawing)
How does one know which one applies to a particular order number?

**Comment by piotr-wiszowaty** [comment]
The "grey" layout is standard and the "blue" one is available on request. This is stated on the manufacturer's
webpage (https://filtercon.com.pl/sieciowe-filtry-przeciwzakloceniowe-do-druku-serii-fp-obudowa-plastikowa/) and also
in the original version of the datasheet (https://filtercon.com.pl/wp-content/uploads/2019/07/Karta-katalogowa-FP-pol-12.pdf):
"UWAGA: Podstawowy rozstaw wyprowadzeń 20x15 mm na życzenie 17,5x15 mm".

**Comment by poeschlr** [comment]
Looks good, thanks

For reference the dimensioned drawing of the footprint
Screenshot from 2020-03-06 22-50-40

**Pull request merged**
