### PR TITLE
Add Maxim WLP-9 footprint

### PR DESCRIPTION
**Pull request by drid**
Add Maxim WLP-9 footprint

https://pdfserv.maximintegrated.com/package_dwgs/21-0067.PDF
https://pdfserv.maximintegrated.com/package_dwgs/21-100168.PDF

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you use our bga generator script found here? https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_BGA

This one builds the footprint after the suggested footprint of the manufacturer but ensures a consistent style and also makes the lib easier to maintain.

**Comment by drid** [comment]
Script PR https://github.com/pointhi/kicad-footprint-generator/pull/542

**Comment by poeschlr** [comment]
I realized that the datasheet you link in this pull request is a different one than the one linked in the footprint itself.

For other requests see comment on pull request

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
