### PR TITLE
Added Dinkle DT55 Terminal block

### PR DESCRIPTION
**Pull request by crackerizer**
Added Dinkle DT55 Terminal block with 4 terminal footprint, https://www.dinkle.com/en/terminal/DT-55-B01W-XX
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I don't think it is a good idea to make a separate lib for just one footprint. Might be better to add it to the TherminalBlock lib.

The silk outline should be outside the body, whereas the fab outline represents the exact body outline. (means the silk outline will result in being outside the fab outline)
Add pin 1 markers on fab and silk. (The silk pin 1 marker must be visible after assembly)
The fab artwork is a bit complex. Maybe make it a bit simpler. (Remove a few of the horizontal lines)
For connectors the courtyard clearance should be 0.5.
The pads are quite large. Maybe reduce their size by a bit. (Especially in y direction.)

**Comment by crackerizer** [comment]
I will added all pin count after this one got merged to make sure I get it right.
I will fix the footprint to all requirements. Do I have to add pin 1 marker to this footprint? Because it is symmetric. I added rectangle pin 1 because it does not pass the Travis CI build.

**Comment by jkriege2** [comment]
Hi!

a note on the side: All the other terminal blocks were generated by scripts that you find e.g. here:
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/TerminalBlock_RND

Do you use a comparable approach, or did you hand-draw them? If you scripted them it would be great to have the code posted in the repo I gave above (also that will make adding variants also from other manufacturers, way easier).

Best,
JAN

**Comment by jkriege2** [comment]
About pin1-marker: We have them on all (or at least the great majority) of terminal blocks. Just orient your design on the already existing footprints, e.g. 
2018-01-27 11_01_30-footprint editor no active library

**Comment by crackerizer** [comment]
I did handwrite them. The move exact function makes things much easier to create these footprints by hand.

**Comment by crackerizer** [comment]
Fixed

**Comment by poeschlr** [comment]
The footprint looks good now. Thanks for your contribution. (If you want to add the other footprints you can open a new pull request for them.)

**Comment by crackerizer** [comment]
Thanks, I will start adding the rest of this footprint.

**Pull request merged**
