### PR TITLE
Adafruit displays

### PR DESCRIPTION
**Pull request by Shackmeister**
3D model has also been made and will be coming shortly

Datasheet:
https://learn.adafruit.com/monochrome-oled-breakouts/downloads

Screenshot:
adafruit_ssd1306

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
does anybody know what that error message is about?

**Comment by poeschlr** [comment]
We might want to add a stacktrace output on error to our scripts. (Not sure what the problem is)

**Comment by Shackmeister** [comment]
The Stepup parser can't handle when there are " inside the desc, I believe they are written as /" when they are not supposed to be parsed

**Comment by evanshultz** [comment]
Usually I see the escape character being a backslash, so `"` would turn into `\"` to result in a quote mark after parsing.

**Comment by poeschlr** [comment]
Is there some better documentation out there that contains all measurements or do i really need to open the eagle files for that?

You currently have a cortyard clearance of 0.5mm i think this does not fall under one of the exceptions that would need such a large clearance. So reduce it down to 0.25mm

For reference the drawing i created from the footprint:
screenshot from 2018-05-08 18-18-18

**Comment by Shackmeister** [comment]
In the link I provided you can find an image with the dimensions, they are unfortunately given in inches :(
lcds___displays_fabprint

**Comment by poeschlr** [comment]
Looks good, sorry for forgetting about that for so long.

**Comment by Shackmeister** [comment]
Thanks :) Ill get around to PR The 3D model soon (hopefully) :)

**Pull request merged**
