### PR TITLE
Renaming of Texas PTN Series footprints to generic module names

### PR DESCRIPTION
**Pull request by jamesrlucas**
Continuation of PR #2083 - where it was agreed that the PTN 780x0 Footprint names were not suitable, so I have renamed the footprints based on the package names given in the datasheet. 

PTN78000 is now Texas_EUS_R-PDSS-T5_THT
PTN78020 is now Texas_EUK_R-PDSS-T7_THT
PTN78060 is now Texas_EUW_R-PDSS-T7_THT

All three have been moved to the Modules folder, as they may not necessarily be DC-DC converters.

Datasheet examples [PTN78000](https://www.ti.com/lit/ds/symlink/ptn78000w.pdf) [PTN78020](https://www.ti.com/lit/ds/symlink/ptn78020w.pdf) and [PTN78060](https://www.ti.com/lit/ds/symlink/ptn78060w.pdf)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks!

Please remove the old footprints. And do any symbols need to be updated?

**Comment by jamesrlucas** [comment]
How do I remove the old footprints? I've removed them from my branch, but what do I do from there?

Only affected symbols are in PR [#2497](https://github.com/KiCad/kicad-symbols/pull/2497), I'll submit changes once I get to work tomorrow.

**Comment by chschlue** [comment]
You can either `git rm` the old footprints or `git mv <old> <new>`.
The latter way keeps the repo's history cleaner (keeps information that these were moved).

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
