### PR TITLE
Inductors Choke Schaffner - wrong manufacturer name and pin spacings

### PR DESCRIPTION
**Pull request by Flo3561**
Inductors Choke Schaffner - corrected description wrong manufacturer name / RN142,RN143,RN202 mechanical corrections / added RN218

Datasheet:
https://www.schaffner.com/de/produkte/download/product/datasheet/rn-series-common-mode-chokes-new/

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by evanshultz** [comment]
You fixed the branch conflict correctly. Great!

Can you re-generate all footprints? It doesn't look like the RN232 fix is included. Right?

The CI errors all look bogus as the courtyard is on a 0.01mm grid and I don't see arcs in the existing footprints' courtyard. Once you submit new footprints that will kick off CI again and we can check it.

**Comment by Flo3561** [comment]
@evanshultz:
I have already regenerated all of them. It looks like the changed height property for RN232 isn't really reflected in the footprint file (and in the generator script) at all... Therefore there is no change.

**Comment by Flo3561** [comment]
@evanshultz: Do you have any update on this topic?

**Comment by evanshultz** [comment]
The issue is that the check script doesn't understand arcs properly. I'll just go with it, though using corners on the courtyard in the script or improving the check script would be proper.

Thanks again for your work and patience!

**Pull request merged**
