### PR TITLE
Add BGA-624_25x25_21.0x21.0mm_Pitch0.8mm

### PR DESCRIPTION
**Pull request by tpambor**
Datasheet: https://www.nxp.com/docs/en/package-information/SOT1529-1.pdf

Created using script: pointhi/kicad-footprint-generator#208

3D Model PR: KiCad/kicad-packages3D#421

fp

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
How did you determine the pad sizes and mask margins?

**Comment by tpambor** [comment]
They are based on typical values for 0.8mm pitch BGAs.

NXP recommends on slide 11 of https://www.nxp.com/docs/en/package-information/PBGAPRES.pdf a pad diameter of 0.40mm, a stencil opening of 0.40mm and on slide 14 a soldermask opening for NSMD pads of 0.525mm. The only difference to this pull request is that here the soldermask opening is only 0.5mm.

If desired I can increase the soldermask opening to match the recommendations.

**Comment by poeschlr** [comment]
If we base the footprint on that document then i feel it might be better to follow it exactly. So please correct the solder mask opening.

**Comment by tpambor** [comment]
Updated to match the recommendations.

**Comment by poeschlr** [comment]
Looks good. Thanks

for the future: please do not amend commits after you got a review. It gets much harder for us to tell what exactly changed. We can keep the history clean by using the squash merge feature.

**Pull request merged**
