### PR TITLE
add SFP/SFP+ connector and cage

### PR DESCRIPTION
**Pull request by aewallin**
SMD connector and THT cage for single SFP/SFP+ transciever.
This is a standardized/generic connector - standards:
* SFP+ defined in SFF-8431 https://www.snia.org/technology-communities/sff/specifications
* SFP defined in INF-8074i , from e.g. http://www.10gtek.com/templates/wzten/pdf/INF-8074.pdf

SFP is for 1 Gbit, while SFP+ is for 10 Gbit - same footprint AFAIK.

Cage e.g. TE MPN 2227302-1: https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=2227302&DocType=Customer+Drawing&DocLang=English
SMD Connector e.g. TE MPN 1367073-4: https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1367073&DocType=Customer+Drawing&DocLang=English
SFP+ standard e.g. "SFF-8431" from https://www.snia.org/technology-communities/sff/specifications?field_doc_status_value=All&combine=8431

This footprint has a lot going on - so I will fix things one by one as I get review comments - thanks ;)

Some open questions to discuss:
- here I suggest a footprint with SMD+THT parts together. If they would be separate it is very hard in PCB design to get the SMD-part and THT-cage positioned correctly. OTOH some designs will use dual- or quad-cages and this combo-footprint might not be useful there.
- The TE documents suggest a keepout-area. I have not drawn it yet but it can be added.
- Some Cage holes are optionally NPTH or Plated. I have used plated everywhere.
- Cage-pin is a named pin - should be matched on symbol side. (alternative name it "21" - one more than the SMD pads?)

Symbol: https://github.com/KiCad/kicad-symbols/pull/1327

sfp_footprint

sfp_large

sfp_small

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
only remaining travis error is now about footprint anchor. will wait for reviewer comments before (possibly) fixing.
- Footprint center calculated as (-18.675,0.0)mm

**Comment by poeschlr** [comment]
Denote the keepout area in accordance to http://kicad-pcb.org/libraries/klc/F4.5/

The land pattern looks good otherwise:
Screenshot from 2019-04-02 21-35-09

**Comment by aewallin** [comment]
keepout added.
This follows the silk-layer and dimensions of the datasheet (where given).
In principle keepout-lines could be moved by some 0.01mm if one wants strictly to follow the datasheet drawing...
Connector_SFP_and_Cage

**Comment by poeschlr** [comment]
The keepout in the datasheet is for all copper except ground. The component keepout is the courtyard layer so make sure the courtyard layer is drawn to take this area into account.

**Comment by aewallin** [comment]
I have now extended the keepout-zone to +/-8.125mm in Y-direction as in the datasheet.
the description is also as per datasheet "component and trace keepout (except chassis ground)"

remaining KLC error is about origin of footprint, which can be changed but I'm not sure if it improves things or not..

Connector_SFP_and_Cage

**Comment by poeschlr** [comment]
looks good, thanks

**Comment by aewallin** [comment]
great - thanks for the review/merge!

**Pull request merged**
