### PR TITLE
Texas drc0010j

### PR DESCRIPTION
**Pull request by jneiva08**
Add footprint Texas DRC0010J VSON10
Datasheet:

Screenshot: http://www.ti.com/lit/ds/symlink/tps63000.pdf pag.23

drc_0010j_footprint

drc_0010j

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 

A single things trouble me is the pin 11 and the solder paste. Datasheet page 25 indicate the solder paste mask and probably it's better to apply it...

Have a look to the similar DSC0010J footprint in the lib.

Cheers,
Joel

**Comment by jneiva08** [comment]
hi @myfreescalewebpage 

I don't understand you question. The pad 11 is made exactly like the datasheet says, it is F.Cu and F.Mask, for soldering have two F.Paste pads.

Can be more explicit.

The DSC0010J is not like datasheet recommend.

Thanks

**Comment by myfreescalewebpage** [comment]
Hi @jneiva08 

Sorry, have been too much quickly on the footprint review, removed my previous comment.
Seems okay for me, fab ok, position/size ok, crtyd ok. Merging the footprint.

Cheers,
Joel

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
