### PR TITLE
MP2303 Footprint, Generated by: IPC gullwing generator

### PR DESCRIPTION
**Pull request by EpeR1**
SOIC package, the MP2303 version.
Generated by: Kicad's IPC gullwing generator.

The symbol is here:
KiCad/kicad-symbols#2060

Datasheet:
https://www.monolithicpower.com/en/documentview/productdocument/index/version/2/document_type/Datasheet/lang/en/sku/MP2303A/document_id/494

fp1
fp2

### CODE REVIEW

**Comment by evanshultz** [comment]
Thank you! Can you please submit the link to the script PR? I don't see it at https://github.com/pointhi/kicad-footprint-generator/pulls. That is how I will check the footprint.

Please use the `EP_size_x_overwrite` YAML key (similar for y dimension) to make the thermal pad match the datasheet dimensions of 2.62x3.51mm. You can see an example at https://github.com/pointhi/kicad-footprint-generator/pull/431/files.

**Comment by EpeR1** [comment]
Ok, updated.
The PR is here:
https://github.com/pointhi/kicad-footprint-generator/pull/648

**Comment by evanshultz** [comment]
Thanks! I left comments in the script PR. Some of them are formatting for maintenance, but it should all be easy to implement.

**Comment by EpeR1** [comment]
Yes, I see, ad updated as requested.

**Comment by evanshultz** [comment]
Thank you!

**Pull request merged**
