### PR TITLE
Converter_DCDC_TRACO_TDN_5-xxxxWISM_SMD adjusted pad sizes to IPC-735…

### PR DESCRIPTION
**Pull request by chmorgan**
…1 standard using library expert pro, changed pads to have no rotation

*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chmorgan** [comment]
@chschlue and here is the pad size adjustment per IPC-7351

**Comment by chmorgan** [comment]
@chschlue I used the defaults which selected a density of nominal

On the silk overlapping with fab I've seen that on other parts. Is there something in the KLC that would justify moving the silk outside of the fab beyond the implication that the fab is the part outline and F5.1 entry 4 says it has to be visible? I'm wondering if we should be considering a KLC update.

I see the silk to copper distance in F5.1. Would it make sense to update the F5_1 rule to check for that clearance or are there enough exceptions to warrant not doing so?

image

**Comment by chmorgan** [comment]
Realized I had pushed this branch to the main repo last night, I'll correct and remove when this is merged or otherwise concluded. New PR from my fork is at https://github.com/KiCad/kicad-footprints/pull/2138

**Comment by chschlue** [comment]
Ah yes, I noticed that when pulling this branch to do the review but then forgot to mention it.
It's also a good idea to actually remove the upstream push url from your git remotes to prevent accidents.

Silk should be visible for placement and debugging, that's one aspect.
Another one is: Silk is an actual layer of paint on the board and so destroys planarity, which is why SMT parts generally shouldn't have any underneath (yes, I'm aware that this particular package has its leads protruding downward).

If you find KLC rules which are unclear, don't convey their rationale or are plain stupid, you're welcome to open issues and/or PRs on kicad-website.
This is something only the new guys can do because you simply turn blind to this sort of thing over time ;)

**Comment by chschlue** [comment]
@chmorgan can this be closed?

**Comment by chmorgan** [comment]
@chschlue yep, closing

**Pull request closed without merging**
