### PR TITLE
Adding Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm

### PR DESCRIPTION
**Pull request by thomasonw**
This pull request is to support the small umRata resonators.  Both an SMT and a hand-solder footprint has been added.  There is no accompanying 3D image, though the proposed image name has been populated.

This is an example URL for a 16Mhz component:   [https://www.murata.com/products/productdetail?partno=CSTNE16M0VH3C000R0](https://www.murata.com/products/productdetail?partno=CSTNE16M0VH3C000R0 )

image

image

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for you contribution. I quickly checked it and found some small problems. Please correct them, before we can merge this!

1. Please directly add the PDF-datasheet-link to the description: https://www.murata.com/en-eu/products/productdata/8801162264606/SPEC-CSTNE16M0VH3C000R0.pdf ... the DS also contains the recommended layout, the webpage does not.
2. Your symbol outline drawing on F.Fab is way too large (see http://kicad-pcb.org/libraries/klc/F5.2/)! Please correct that. This drawing should exactly replicate the avg. symbol outline. Also the pin1-marker should simply look like this: 
2018-04-15 12_03_04-footprint editor no active library
3. the courtyard line should have a clearance of 0.25mm to the pad-outlines and/or the F.Fab outline (whichever is farther out): http://kicad-pcb.org/libraries/klc/F5.3/

Best,
JAN

**Comment by jkriege2** [comment]
PS: In the `_HandSoldering variant, the silkscreen-line is too close to the pads (the offset should usually be >=0.2mm, see http://kicad-pcb.org/libraries/klc/F5.1/)

**Comment by thomasonw** [comment]
OK, again thanks.  Made these corrections - adjusted some text size as well within the guidelines.  Hopefully this will be good!  (But am grateful for the care you folks are taking, the Libs have been a weakness in KiCAD - and so glad to see it get good focus these days)

**Comment by jkriege2** [comment]
Hi!

way better ... please also fix the other errors (text sizes/contents) that Travis noted:
```
Checking footprint 'Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm':
  Violating F5.1
    Silkscreen layer requirements
    Reference label errors:
     - Reference label has a height of 0.8mm (expected: 1.0mm).
     - Reference label has a width of 0.8mm (expected: 1.0mm).
     - Reference label has a thickness of 0.12mm (expected: 0.15mm).
Checking: Crystal.pretty/Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm_HandSoldering.kicad_mod
Checking footprint 'Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm_HandSoldering':
  Violating F5.1
    Silkscreen layer requirements
    Reference label errors:
     - Reference label has a height of 0.8mm (expected: 1.0mm).
     - Reference label has a width of 0.8mm (expected: 1.0mm).
     - Reference label has a thickness of 0.12mm (expected: 0.15mm).
  Violating F5.2
    Fabrication layer requirements
    Value Label Errors
     - Value text should match footprint name:
     - Value text is 'Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm', expected: 'Resonator_SMD_muRata_CSTxExxV-3Pin_3.0x1.1mm_HandSoldering'
```

**Comment by thomasonw** [comment]
OK, made corrections - I had miss-red allowable FAB label sizing vs. Silk.  (Plus did text editing for the hand-soldering, so missed the ref name).  Travis seems happy now!

**Comment by thomasonw** [comment]
OK, made corrections - I had miss-red allowable FAB label sizing vs. Silk.  (Plus did text editing for the hand-soldering, so missed the ref name).  Travis seems happy now!

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
