### PR TITLE
Add Würth WE-GF inductor

### PR DESCRIPTION
**Pull request by Schlumpf**
Datasheet: https://www.we-online.de/katalog/datasheet/74476401.pdf
grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] ~If there are matching symbol or 3D model pull requests, provide link(s) as appropriate~
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] ~Give a reason behind any intentional library convention rule violation.~

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by aris-kimi** [comment]
Datasheet:
εικόνα
FreeCAD:
εικόνα

Thanks @Schlumpf , i am going to merge this in the next few minutes.

**Comment by chschlue** [comment]
1210 indicates body size, so we need to keep it in the name to be able to add other sizes from this series.

But something else is odd here: Courtyard is 4.3mm in x-direction (which is correct), yet distance to pad 1 is only 0.225mm. Is the CrtYd rectangle not centered correctly?

**Comment by aris-kimi** [comment]
0.225 from edge, 0.05 coyrt width /2 = 0.25

0.25 * 2 + 1 + 1 + 1.8 = 4.3

**Comment by aris-kimi** [comment]
I wasn't sure only about name. I am merging now @chschlue .

**Comment by chschlue** [comment]
Maybe I'm seriously boneheaded today, but my reasoning is:
- we agree that 4.3mm is correct
- 0.225mm from pad 1 is definitely not correct (must be 0.25mm)
- it follows that CrtYd distance from pad 2 is 0.275mm, which is also not correct

**Comment by aris-kimi** [comment]
εικόνα
It is ok. Image might was loaded with info.. But lines' width is 0.05, from its edge to copper edge it is 0.225, since it is 0.05/2 = 0.025 added with 0.225 i count is 0.25 nice and round.

**Comment by chschlue** [comment]
I see. Never mind.

**Pull request merged**
