### PR TITLE
Heatsink fix for PR #55

### PR DESCRIPTION
**Pull request by poeschlr**
This is the replacement PR for #55 
I will slowly rework these footprints over the next few days.

### CODE REVIEW

**Comment by poeschlr** [comment]
I am done here.
screenshot from 2017-11-30 11-00-00

**Comment by SchrodingersGat** [comment]
These look great!

1. Please add lib-table entry
2. Run the --fixmore option to add default 3D model path

**Comment by poeschlr** [comment]
I think i misused git here. It seems to have lost the information that the fp-lib-table has been changed already. So it simply used the version in the master branch. I needed to merge the master into my branch to get the fp-lib-table entry to stick.

**Comment by SchrodingersGat** [comment]
Thanks! :)

**Comment by SchrodingersGat** [comment]
Yeah it can be weird sometimes.. Looks like you got it sorted though

**Comment by poeschlr** [comment]
It might have happened because i reverted a local merge yesterday. (I work on two pcs and forgot to pull my own changes before making some others. Wanted to keep git log clean. Well seems i failed in that.)

**Pull request merged**
