### PR TITLE
Adding IDT oscillator JS6 package footprint

### PR DESCRIPTION
**Pull request by ki5libs**
Adding IDT oscillator JS6 package footprint
[Datasheet](https://www.idt.com/document/dst/xu-family-datasheet#page=15)

JS6_new

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
We never include the word pin in the footprint name.
The pitch should be included in the footprint name.

Rotate the footprint 90 degree such that pad 1 is on the top left corner (IPC zero orientation A)

Use IPC style pad 1 marking. (chamfer on fab, missing/short line on silk. look at DFN-8-1EP_2x2mm_P0.5mm_EP0.9x1.5mm for inspiration)

Possibly move silk closer to the fab outline (to aid part alignment for manual assembly)

general dimensions look ok (checked with kicad internal tools so there is no nice screenshot available)

**Comment by poeschlr** [comment]
I forgot to check the courtyard clearance in my last review. Sadly it is too large all around (is 0.3mm in x direction and >0.3mm in y)

**Comment by ki5libs** [comment]
Fixed and renamed similarly to [this PR](https://github.com/KiCad/kicad-footprints/pull/1918)

**Comment by poeschlr** [comment]
This one could benefit from an increased clearance between pads and silk (there will be enough silk left if you make the clearance 0.2mm, but it will make this footprint useable for cheaper fabs.)

**Comment by ki5libs** [comment]
@poeschlr, done.

Clearance

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
