### PR TITLE
add L_Bourns-SRU1028

### PR DESCRIPTION
**Pull request by nerdyscout**
equivalent to the already existing SRU8043 this does add the footprint for SRU1028

grafik

[datasheet](https://www.bourns.com/docs/Product-Datasheets/SRU1028.pdf)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi. Thanks for your contribution.
- Why have you removed the silk near pad 1? This footprint is not polarized.
- I would suggest you appending the body dimensions to the footprint name. Appending body dimensions is a recent decision, and we are doing this for all inductors, but this is not well documented yet. The name would be L_Bourns-SRU1028_10.0x10.0mm.
- Some dimensions are wrong. Take a look in the dimensioned drawing bellow.
image

**Comment by nerdyscout** [comment]
[SRU1028](https://www.bourns.com/docs/Product-Datasheets/SRU1028.pdf)
image

[SRU8043](https://www.bourns.com/docs/Product-Datasheets/SRU8043.pdf)
image

I made no several changes, as well to the existing SRU8043 to keep them compliant.

**Comment by gmsotavio** [comment]
- [ ] I haven't checked the SRU8043 yet.  As you have renamed it, current designs that use this footprint will break. So, I believe that is a better option to open a new PR to SR8043.
- [ ] There are two incorrect dimensions remaining. Take a look at the dimensioned drawing. The proper value is 0.25mm.
image
-[ ] I realized that you had used the Shape offset X (in red color). We usually do not use this feature. I think it is a better option to calculate the right value for Position X (in blue color), taking into account the pad offset.

**Comment by nerdyscout** [comment]
ok, reverted changes of CR8043 and changed CrtYd as well as pad offset.

**Comment by gmsotavio** [comment]
The dimensions look good for me now.
image

image

- [ ] Accidentally, you have removed the RefDes on the Fab. Layer. Add the missing RefDes and this footprint will be ready to be merged.

**Comment by gmsotavio** [comment]
Great! Thanks.
image

**Pull request merged**
