### PR TITLE
Add Oscillator_SMD_Fox_FT5H_5.0x3.2mm

### PR DESCRIPTION
**Pull request by bitglue**
Datasheet: https://www.mouser.com/datasheet/2/160/T5HN_T5HV-1662393.pdf

Symbol: https://github.com/KiCad/kicad-symbols/pull/2754
3D model: https://github.com/KiCad/kicad-packages3D/pull/699
3D model source: https://github.com/KiCad/kicad-packages3D-source/pull/282

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by bitglue** [comment]
I have a symbol too, will submit in a bit.

**Comment by poeschlr** [comment]
Please do not use the mouser datasheet. Point to the datasheet directly via the manufacturers website

**Comment by aewallin** [comment]
silk-lines look like they are hidden under the part? (see KLC F5.1.4. "no silkscreen allowed under component")

**Comment by bitglue** [comment]
They follow the outline. You want them set out? By how much?

**Comment by aewallin** [comment]
There is no exact guideline for how much silk-screen should be outside the outline of the part, just that silk should not be under the (SMD) component. I guess one line-width is enough of a gap between the outline and the silk.

**Comment by bitglue** [comment]
@poeschlr @aewallin thanks for the reviews. Changes made:

- offset the silk lines so they are fully visible under the package
- added a HandSoldering variant, with the pads 0.5mm larger
- changed link to datasheet from foxonline.com

**Comment by bitglue** [comment]
Updated footprint:

fox

HandSoldering variant:

fox_handsoldering

**Comment by aris-kimi** [comment]
Hi @bitglue , are you willing to continue with this PR? Sorry for short notice pinging. Things changing fast and it is good to merge this as it is a full symbol addition with symbol footprint and 3d model..

**Comment by bitglue** [comment]
rotated the footprint, i'll try to do the 3d model tonight

**Comment by bitglue** [comment]
It would be _so_ nice if the rule checker was embedded in the footprint editor.

**Comment by aris-kimi** [comment]
Yes i thought of it too, but i learnt that it rounds numbers so it is not adviced to use it for reviewing... I will review this a little later. Thank for acting fast :)

**Comment by bitglue** [comment]
I could have messed up the rotation. And it occurs to me I have evening plans, so probably won't get to this and the footprint tonight. Should be able to get to everything this weekend though, if not sooner.

**Comment by aris-kimi** [comment]
@chschlue , is there a rule about handsolder pad dimmensions or this can be custom per creator/part?

@bitglue ,
np. I gave it a look, yes it is a little messed.

Select all, and move excactly x: `0.037443` y: `-0.012557`
Applies to Oscillator_SMD_Fox_FT5H_5.0x3.2mm.

For the second part, since i saw it hasn't moved.
My strategy is:
note down pin1 coordinates,
select all,
move excactly as (current pin1 coordinates noted) * `-1` in order to locate this pin to 0,0 (with all selection moved),
(i think` * -1` applies, i allways check my cursor coordinates since current KiCAD's coordinate counting confuses me..)
select a high grid and confirm pin 1 has moved correct,
now selet all once again and rotate,
(better if you keep your cursor at 0.0 after selection and before rotation applied)
fit pin 1 at 0.0 point with the cursor,
confirm pin1 once again and select all,
final move excactly all selection to noted pin1 coordinates with all negative values but in reversed fields(x-y),
final confirm.

With less steps:
start with a high number grid step,
select all,
fit your cursor to 0.0,
apply rotation as many times needed.

Previous steps mostly will help to center a lost footprint also with consulting datasheet drawings.

Hope this helped.

**Comment by chschlue** [comment]
No, it's basically arbitrary.

But (for perspective) the recommended pads are larger than a whole 0603 package, is a special hand soldering variant necessary @bitglue?

**Comment by bitglue** [comment]
Fixed the rotation, and updated the 3d model
image

**Comment by bitglue** [comment]
@chschlue with the pads on the bottom it's kind of a tricky thing to hand solder with any footprint. I don't think the bigger pads would make it significantly easier, so I just ditched that footprint.

**Comment by bitglue** [comment]
@aris-kimi @chschlue Any more changes required?

**Comment by aris-kimi** [comment]
No @bitglue , looks good.
Merging now.
Thank you for your contribution.

**Pull request merged**
