### PR TITLE
Wurth ElektronikFCC connector 68611214422

### PR DESCRIPTION
**Pull request by carlosromorgar**
http://katalog.we-online.de/em/datasheet/68611214422.pdf

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Please give the two mounting pads the pin number MP (The FFC lib has been forgotten when we made that change for all other similar footprints. See https://github.com/KiCad/kicad-footprints/issues/562)

Should you ever need other similar footprints, we have a script that can generate similar footprints: https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Connector/Connector_Hirose/conn_ffc_hirose_fh12_smd_side.py

**Comment by poeschlr** [comment]
A few measurements are not quite right:
screenshot from 2018-05-05 12-09-28

**Comment by pushytoxin** [comment]
Components from Würth Electronics are named 'Wuerth'. You might want to replace 'WurthElektronik' with 'Wuerth' so it follows the current convention.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
