### PR TITLE
add texas SOP-8 package

### PR DESCRIPTION
**Pull request by balcer**
http://www.ti.com/lit/ds/symlink/iso1050.pdf

footprint

https://github.com/KiCad/kicad-symbols/pull/1342

I found 3D model on Texas Instrument website:
https://webench.ti.com/cad/dlbxl.cgi/newstep/DUB0008A.stp

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Regarding 3d model: It is nice to know that there is one available but i would bet you already broke the license agreement you signed when downloading it by sharing it here.

This footprint should really be integrated in our script. I can take care of this as i am working on it right now anyways. If you are interested in this sort of thing then you can still look at the generator which is found in https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO

**Comment by balcer** [comment]
Thanks for quick response, Poeschlr.

> Regarding 3d model: It is nice to know that there is one available but i would bet you already broke the license agreement you signed when downloading it by sharing it here.

How on earth can I break licence agreement by posting link url?

KLC M1.2:

> If a manufacturer provides 3D model data for download from its website, these models should not be duplicated in the KiCad library.
A link to the manufacturer model files may be added to the README.md file within the 3D model directory.

I'm also interested in 3D model automation. Not only for this footprint. Could you tell me where to start in "KiCad workflow" style. 

> This footprint should really be integrated in our script. I can take care of this as i am working on it right now anyways. If you are interested in this sort of thing then you can still look at the generator which is found in https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO

> Yes, I know this tool. I did PR there. Mayby next week I will try to move this footprint to script.

Chears

**Comment by poeschlr** [comment]
3d model scripts are found here: https://github.com/easyw/kicad-3d-models-in-freecad

I already scripted your footprint. i have a slightly larger pull request open that moves around some stuff so it is easier if i just take care of this to avoid merge conflicts.

**Comment by poeschlr** [comment]
Scripted replacement is found here: https://github.com/KiCad/kicad-footprints/pull/1273

**Comment by balcer** [comment]
Thanks

**Pull request closed without merging**
