### PR TITLE
Adding R_Shunt_Vishay_WSKW0612

### PR DESCRIPTION
**Pull request by ki5libs**
Adding R_Shunt_Vishay_WSKW0612
[Datasheet](https://www.vishay.com/docs/30332/wskw0612.pdf)
wskw0612
[3D package PR](https://github.com/KiCad/kicad-packages3D/pull/351)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

Should not pad 1 and 2 be 2.67 (2.668 mm)  wide ?

**Comment by ki5libs** [comment]
According to the datasheet:
pad 1 and 2 width (a) = 1.01 mm
pad 1 and 2 length (b - d - c) = 3.43 - 0.381 - 0.762 = 2.287 mm
Is it OK, isn't it?

**Comment by ki5libs** [comment]
Fixed the courtyard. Checked the symbol - you are right
What do think I should better do: adding new symbol with connected pairs of pins 1-4 and 2-3 or change pins numbering on this footprint? Datasheet describes pin enumeration as I1, I2, E1, E2 and 1-2 locate on opposite sides so the first variant seems preferable to me...

**Comment by poeschlr** [comment]
I would prefer if we would make all such footprints fit the generic symbol. (otherwise we will have a lot of symbols and users will have a hard time finding out which symbol fits what footprints)

**Comment by ki5libs** [comment]
So is the solution just reenumerate pins clockwise?

**Comment by poeschlr** [comment]
Yes that would be perfect.

**Comment by ki5libs** [comment]
Done. Screenshot also updated

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
