### PR TITLE
Added footprint for Diodes SIP-3 Ammo-Pack

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.diodes.com/assets/Package-Files/SIP-3-Ammo-Pack.pdf

Screenshot:
ammopack

PR for symbol: https://github.com/KiCad/kicad-symbols/pull/1048

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Are you sure of the the distance, according to the data sheet e1 is 1.3 but you use 2.65 ?
(I have not looked more closer to it)

**Comment by jneiva08** [comment]
The datasheet on first post was wrong, it was for SIP-3 (BulkPack), have already changed.

Diodes have SIP-3 Bulk-Pack and Ammo-Pack.
If i'm not wrong, exists Allegro SIP-3 and is compatible, or make sense make on Diodes_SIP-3_BulkPack?

**Comment by Misca1234** [comment]
Now the data sheet distance e2 is 2.9 but you use 2.65

Could you just shorten the F.Silk so it wont hit the pad, use some margins as well

bild

**Comment by jneiva08** [comment]
The 2.9 is the maximum, I used the typical. Or should use the maximum?

**Comment by Misca1234** [comment]
Naaa, you are right, I did not notice they put in the order min, max, typ, lemme re check

**Comment by Misca1234** [comment]
Now I agree with myself ;)
Could you fix the F.Silk covering copper ?

**Comment by jneiva08** [comment]
Fixed F.Silk

**Comment by Misca1234** [comment]
Thx

**Comment by jneiva08** [comment]
Thanks for merge.

Makes sense to make Diodes_SIP-3_BulkPack?
The Allegro SIP-3 appear to be equivalent.

**Comment by Misca1234** [comment]
hmm, perhaps it should be an alias to the Diodes_SIP-3_BulkPack symbol ?

**Pull request merged**
