### PR TITLE
Add L_Bourns_SRP2313AA

### PR DESCRIPTION
**Pull request by strombom**
L_Bourns_SRP2313AA
http://www.bourns.com/docs/product-datasheets/srp2313aa.pdf

image

image

image

3D Model: https://github.com/KiCad/kicad-packages3D/pull/249

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Please modify the footprint, so it matches the recommended layout from the datasheet: 
2018-01-31 07_53_27-srp2313aa pdf - adobe acrobat reader dc

**Comment by strombom** [comment]
Oh I used the part dimension instead of footprint dimension...

image
image
image

**Comment by strombom** [comment]
Square corners on inside of pads

image

**Comment by jkriege2** [comment]
nice work. Please add the link you gave above to the description and I will merge!

**Comment by strombom** [comment]
Thanks, I'm impressed how you guys find all small errors :)

**Pull request merged**
