### PR TITLE
Morion ocxos MV267 and MV317

### PR DESCRIPTION
**Pull request by aewallin**
OCXO oscillators MV267 and MV317

Datasheets:
http://www.morion.com.ru/catalog_pdf/MV267.pdf
https://www.morion-us.com/catalog_pdf/mv317.pdf

Screenshots:
mv267
mv317

Symbol: to do.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
Update to f.fab, silk, and courtyard. MV317
mv317
mv371_spec

**Comment by aewallin** [comment]
Update to MV267:
mv267
mv267_spec

**Comment by poeschlr** [comment]
Please add pin 1 markers and make pin 1 square instead of circular (our rounded rectangle)

Rotate mv317 such that pin 1 is on the top right corner.

The datasheets for this parts are on the lower end of the quality spectrum. Is there any chance we get more information about tolerance ranges for the dimensions? Especially the dimension tolerances for the leads would be interesting.

Assuming the lead diameters given are maximum sizes then add 0.2mm to the diameter to get the hole size. (Meaning both parts would need a 0.1mm increased hole size compared to now.)
oscilator svg

**Comment by poeschlr** [comment]
Damn i gave wrong advice again. The pin 1 should be on top left. Meaning you rotated too far. Sorry about that.

Additionally the pin 1 markers are still missing.

**Comment by poeschlr** [comment]
Thanks looks good now.

**Pull request merged**
