### PR TITLE
LFBGA169 used for eMMC flashes

### PR DESCRIPTION
**Pull request by nerdyscout**
Hi,

this footprint can be used for eMMC flashes like https://4donline.ihs.com/images/VipMasterIC/IC/SGST/SGSTS20279/SGSTS20279-1.pdf?hkey=EF798316E3902B6ED9A73243A3159BB0

grafik

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by nerdyscout** [comment]
redone whole part, should be fine now
grafik

**Comment by nerdyscout** [comment]
courtyard clearance is now 1mm.
Sry, but i don't get your problem with Pad L4. I can see it in the datasheet at page 14.

**Comment by nerdyscout** [comment]
i still count 169pins. without this extra pin the design would be symmetrical and should have a even pin count. but it does not. 

rows * columns -> + 14 * 14
cutout between -> -7 * 4
cutout in centre -> - 4 * 4
pins spread arround -> +4 * 4
Pin L4 -> +1

==> sum 169

**Comment by poeschlr** [comment]
You are right.
Thanks for your contribution.

**Pull request merged**
