### PR TITLE
Button_Switch_THT: Add CK OS102011MS2QN1 footprint

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://www.ckswitches.com/media/1428/os.pdf

imagen

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
@antoniovazquezblanco what is the state of this?

**Comment by poeschlr** [comment]
Regarding fp name i think it would be something like:

`SW_Slide_1P2T_CK_OS102011MS2QN1`

I am however not so sure if we should have all these options for the type (rocker and slider would look the same on the symbol side). 
They would specify the footprint closer but might either require us to have more symbols or have multiple filters per symbol.

See: https://github.com/KiCad/kicad-symbols/issues/580

**Comment by antoniovazquezblanco** [comment]
> According to IPC-2221A, the switch pads can be 1.35mm in diameter and the mounting holes can be 2.05mm. They don't have to be exactly this size, but since there's only 0.15mm between the pads I think we should go smaller to avoid shorting.

I did not get this one. What should I do? 🤔 

The rest is done!

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
I was saying that the distance between pads is only 0.15mm, which is very small. I'm suggesting we go with smaller pads than IPC would recommend to give more space and avoid accidental shorts. However, when I calculate now I get 0.25mm (2.1mm - 0.75mm - 1/1mm).

Here is the footprint now:
image

Looks good to me. Ready to merge?

**Comment by antoniovazquezblanco** [comment]
Yes! Thank you very much!

**Pull request merged**
