### PR TITLE
Change nxe2 sxxxx mc tht name

### PR DESCRIPTION
**Pull request by od83**
Hi, 

What I did:
1. remove Converter_DCDC.pretty/Converter_DCDC_muRata_NXE2SxxxxMC_THT.kicad_mod
2. add Converter_DCDC.pretty/Converter_DCDC_muRata_NXExSxxxxMC_SMD.kicad_mod

I did not change the footprint itself, only (file)name and description.

Why I did it:
a. The footprint is (and was) a SMD type, not THT type.
b. The footprint can also be used for the NXE1S Series of Murata's 1W DC/DC converters

Reference:
[NXE1 Series](http://power.murata.com/data/power/ncl/kdc_nxe1.pdf)
[NXE2 Series](http://power.murata.com/data/power/ncl/kdc_nxe2.pdf)

Symbol pull request for added NXE1S0x0xMC and changed NXE2SxxxxMC are [here](https://github.com/KiCad/kicad-symbols/pull/2452).

PAD_NXExSxxxxMC_SMD

Best regards,
Oliver

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by od83** [comment]
Is the license/cla pending a blocking issue?
I can't get it resolved by rechecking.
I signed the CLA but it is not recognized since I didn't have an email address set in git by that time

Please let me know if I need to start a new Branch / PR

**Comment by chschlue** [comment]
Yes, that's a blocking issue. But adding the address to GH afterwards and closing and reopening this PR should do the trick.

**Comment by od83** [comment]
merge 3,623 commits? No!

I tried to change the git history in order to fix my "author" in the envelope.
However, this is not what I intended. I'll close this PR, delete the branch and start over.

Sorry for the inconveniences.

**Comment by od83** [comment]
merge 3,622 commits? No.
I tried to rewrite (GIT) history. Never a good idea.
I'll close this PR and start over fresh.

Sorry about the inconveniences.

[The new PR](https://github.com/KiCad/kicad-footprints/pull/2068)

**Pull request closed without merging**
