### PR TITLE
Added footprint for CUI CMR-12062S-67 speaker

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.cuidevices.com/product/resource/cmr-12062s-67.pdf
3D: https://github.com/KiCad/kicad-packages3D/pull/681

imagen
Captura de pantalla de 2020-04-21 12-31-12

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cnieves1** [comment]
Regarding F6.2: footprint is centered, but it has only two pads on the bottom, so TravisCI calculations are wrong.
Regarding F6.3: this device is not soldered. Connection is made with compression springs.

**Comment by cpresser** [comment]
Question: That 'ear'-shape on F.Fab, is that a removable tape on the device?

**Comment by cnieves1** [comment]
Yes, it is. I think it should be better to draw it, just in case there is any conflict with other component nearby...

**Comment by cpresser** [comment]
What If I want to put a component next to the speaker, below that flap of tape. Then the courtyard should not be there. Nevertheless, the flap should be drawn somehow.

I was about to say there might be problems during production, the speaker need to be assembled last so the tape is not interfering with another pick'n'place operation. But that does not apply since the speaker will not get assembled in a SMT line prior to reflow.
Or am I missing something here?

**Comment by chschlue** [comment]
This type of speaker is usually glued to the cover first and will contact the PCB on final assembly.
I don't get the point of having that tab in the FP at all.

**Comment by chschlue** [comment]
Example:
spkr

Sorry, couldn't resist using an image of a prehistoric phone :)

**Comment by cnieves1** [comment]
I think you are right. Removed cover from footprint. Thanks!

**Comment by cnieves1** [comment]
Captura de pantalla de 2020-04-24 23-56-29

**Comment by cpresser** [comment]
Good thing this is such a simple footprint and easy to check :)
All dimensions look good. The choice of the Pin1 indicator-style is also fine.

**Comment by cnieves1** [comment]
I agree this is up to the designer and hard to guess beforehand. If you think 0.5mm is better, it's fine for me...

**Comment by cnieves1** [comment]
Increased courtyard clearance to 0.5mm:
Captura de pantalla de 2020-05-25 11-41-35

**Pull request merged**
