### PR TITLE
Converter_ACDC: Fix IRM-02 SMD footprint

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://www.meanwell.com/scripts/resource/pdfViewer/web/viewer.html?f=IRM-02&pdf=IRM-02-SPEC.PDF&r=aHR0cDovL3d3dy5tZWFud2VsbC5jb20=

imagen

Related issues:
https://github.com/KiCad/kicad-footprints/issues/749

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
The courtyard clearance on the left and right side is not quite right.
The pad positions in x direction is not quite right
See sketch
acdc

**Comment by antoniovazquezblanco** [comment]
Sorry. Fixed now. Thanks

**Comment by poeschlr** [comment]
Looks good, thanks for your continued great work to make the lib better

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
