### PR TITLE
Add mounting holes with a fastener pad on the top layer only

### PR DESCRIPTION
**Pull request by StefanHamminga**
Add mounting holes with a fastener pad on the top layer and a minimal (0.2mm) annular ring on other layers. As discussed in issue #2391 these are additional footprints based on the "Pad" variants, with the suggested suffix "TopOnly".

### CODE REVIEW

**Comment by StefanHamminga** [comment]
Christian, would you want a TopBottom variant as well? And if so, as part of this PR or a new one?

**Comment by chschlue** [comment]
Add them to this PR if you like.

**Comment by StefanHamminga** [comment]
Done!

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
