### PR TITLE
Bonens 3386F trimpot added

### PR DESCRIPTION
**Pull request by aliteke79**
Bonens 3386F trimpot is added.
https://img.ozdisan.com/ETicaret_Dosya/487795_9424728.pdf
https://img.ozdisan.com/ETicaret_Dosya/14249_5746158.pdf

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
output

### CODE REVIEW

**Comment by poeschlr** [comment]
Please provide a screenshot of the footprint and a link to the datasheet.

From the automatic checks:
- Make pad 1 rectangular
- Fill out the 3d settings. (Adding a 3d model is not required but the footprint must be prepared to accept one.)

**Comment by aliteke79** [comment]
it's a Chinese brand, i couldn't find a good datasheet so i have added two document link.

**Comment by evanshultz** [comment]
Is this a copy of one of the top-adjust Bourns 3386 parts (https://www.bourns.com/pdfs/3386.pdf)? The library has X, C, and P version of Bourns 3386 (https://github.com/KiCad/kicad-footprints/tree/master/Potentiometer_THT.pretty).

It seems the Bourns 3386F is the same part as you submitted above, but from a well-known brand with a better (and available!) datasheet.

We have generated all trimmer pot footprints by script and that would be the best way to add more. Right now I'm finishing off some updates to the script before I upload it, and I could add the 3386F footprint if you like.

**Comment by aliteke79** [comment]
Hi @evanshultz, it is smilar to Bourns 3386F but size is little different. Bourns has 2.54mm pitch and Bonens has 2.5mm. Maybe they want to make a difference.

**Comment by aliteke79** [comment]
Okay.

**Comment by evanshultz** [comment]
Footprint submitted and linked above. I'm closing this PR. Thanks for pointing out this footprint that was missing in our library!

**Pull request closed without merging**
