### PR TITLE
reworked all DIP-switch footprints (naming, style, some new, ...)

### PR DESCRIPTION
**Pull request by jkriege2**
- script-generated: https://github.com/pointhi/kicad-footprint-generator/pull/106 (reworked existing scripts)
- reworked naming:
  - `SW_DIP_[SWITCHTYPE]x[#SWITCHES]_[SWITCHSTYLE]_[X]x[Y]x[Z]mm_W[LEAD_SPAN]mm_P[PITCH]mm_[MODIFIERS]`
  - `SW_DIP_[SWITCHTYPE]x[#SWITCHES]_[SWITCHSTYLE]_[MAN]_[MPN]_W[LEAD_SPAN]mm_P[PITCH]mm_[MODIFIERS]`
    - SWITCHTYPE - SPST,...
    - #SWITCHES - Number of switches in package
    - SWITCHSTYLE - SLide, Piano, ...
    - MAN - manufacturer
    - MPN - manufacturer part number
    - X - Major dimension of part on x axis
    - Y - Major dimension of part on y axis
    - Z - Major dimension of part on z axis (Optional)
    - Lead span - Distance between leads
    - Pitch - Lead pitch
    - Modifiers - Modifiers to footprint specifications
    Options - Extra footprint options (Optional)

- reworked style (especially pin1-marker: L on THT/SMD-mounted-THT and standard-markers for SOIC-style SMDs)
- added some new: `SW_DIP_SPSTxXX_Slide_..._LowProfile_JPin`
- improved descriptions (body-size, webpage/datasheets ...)
- also includes the footprints required there: https://github.com/KiCad/kicad-footprints/pull/216
- **NOTE: This requires some renames of 3D models!!!** ... I will add an issue for that as I pressume these are script-generated: https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/DIP_parts done by @terjeio ???

2018-01-04 12_35_44-pcbnew d__kicad_devproject_devproject kicad_pcb
2018-01-04 12_44_15-3d viewer

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing **IN FILES**
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by twam** [comment]
The reworked footprints work fine with those I tried to address in #216. 👍

Other comments:
* Your argument to have the silk screen also on some of the SMD components is that there is small distance between part and board. However the argument of KLC allowing silk screen under components is not the extra space, but the help for manual assembly. As those parts are assembled the same way as other SMD parts I do not see why this exception should apply here. I personally think this is inconsistent and should be removed here.
* Only parts without the switches on the silk screen show them on the fab layer. I think this should be independent. Either we think it is helpful to have them in the fab layer, then it should be always there or it is not helpful. Then get also rid of it. I personally would get rid of it.
* Your Pin 1 designator is also different between the DIP based SMD parts and the other ones. I also would suggest to always use the standard markers among all SMD parts.
So all my points are only questions of taste, but as one goal of the rework is to make it more consistent it maybe worth thinking about it.

Besides that, thanks again for the very quick pull request!

**Comment by jkriege2** [comment]
Switches on F.Fab are there alwys ... just KiCAD does overlay F.Fab with silkscreen (i.e. F.Fab is not visible) in newer versions.

Abou the other style issues: What does everybody else think? I can change the footpritns easily in the scripts ... Let me know!

**Comment by twam** [comment]
Just checked my components box and also found some of these:
https://datasheet.lcsc.com/szlcsc/1-27mm-10-DIP-switcha_C54956.pdf

They seem to fit on none of your footprints. If you're over-motivated you could add those as well. Oterwise I'll create a follow up request once your request is merged.

**Comment by jkriege2** [comment]
There you go:

2018-01-06 09_50_53-pcbnew d__kicad_devproject_devproject kicad_pcb

**Comment by twam** [comment]
Awesome! 👍

**Comment by jkriege2** [comment]
@SchrodingersGat @poeschlr Yould you have some time for a review?

Thanks,
JAN

**Comment by jkriege2** [comment]
@SchrodingersGat @poeschlr Could one of you have a look at this?

Thanks,
JAN

**Comment by poeschlr** [comment]
Looks good, thanks

**Comment by Shackmeister** [comment]
@jkriege2 Im working on the 3D models to get them working with these footprints. The footprint scripts doesn't however seem to be updated. This makes getting the naming right really hard.

Am I blind or did you forget to push them?

**Pull request merged**
