### PR TITLE
Add 18-pin variant of SSOP used by Toshiba (fixes #631)

### LINKED ISSUE #631: Missing SSOP-18 footprint
Looking for a matching footprint for a Toshiba 62083A 8-channel DMOS transistor array, I noticed that there is no SSOP-18 footprint in the library.

The SSOP-20 footprint at https://github.com/KiCad/kicad-footprints/blob/master/Package_SO.pretty/SSOP-20_4.4x6.5mm_P0.65mm.kicad_mod comes very close judging by the outline, but has two extra pins.

I kindly ask that whoever generated the fantastic SSOP footprints and matching 3D models, please extend the series by this SSOP-18 variant.

A description of the geometry can be found in Toshiba's data sheet, page 9 top half:
https://toshiba.semicon-storage.com/info/docget.jsp?did=29893

Thank you very much in advance!

### PR DESCRIPTION
**Pull request by acolomb**
This is a slight modification of the existing SSOP-20 footprint, with
only two pins removed and symmetry restored.

Reference is the TBD62083A datasheet at
https://toshiba.semicon-storage.com/info/docget.jsp?did=29893

The linked part is mostly equivalent and pin-compatible to an ULN2804A
darlington array, so its schematic symbol can be used.

### CODE REVIEW

**Comment by acolomb** [comment]
Additional screenshot:
screenshot from 2018-06-05 20-04-18

**Comment by acolomb** [comment]
@poeschlr I'm still trying to figure out the 3D generator stuff. Trying to modify the scripts used for the original SSOP-20 footprint that I modified - working on https://github.com/easyw/kicad-3d-models-in-freecad/blob/master/cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT/cq_parameters_ssop.py

**Comment by acolomb** [comment]
3D model added as STEP and WRL:
https://github.com/KiCad/kicad-packages3D/pull/320

**Comment by acolomb** [comment]
Source modification to generate the 3D model has been proposed as https://github.com/easyw/kicad-3d-models-in-freecad/pull/173

**Comment by Misca1234** [comment]
This looks al right to me, if no objections i will merge it

**Comment by Misca1234** [comment]
@acolomb 
Regarding the https://github.com/KiCad/kicad-footprints/issues/631

I have to say that you was very quick to get up and running in just a day with both foot print and 3D models, if you have more, just bring it on ;)

Just some advices.
If you are missing a component, look at pushes that waiting for merge, someone might already done the work and waiting for merge.

There might be a footprint that match your need but with a slightly different name, which means no need to do the work.

**Comment by acolomb** [comment]
Well, this was pretty much copy-and-paste of an existing footprint and model.  Finding the 3d model generator repository could have been a little easier.  I was not sure at first if it was the right source because it's not mentioned much as some kind of officially sanctioned source.

Most of the time, I don't need 3D models for myself, so most footprints I design as part of a project would not qualify for KLC quality. :-(  I'll contribute what I can, though, as long as it meets my own quality and your quality standards.

**Comment by poeschlr** [comment]
You would not need to supply the 3d model to comply with the KLC. The only thing we expect is that the 3d settings are filled out such that adding a model later would not require editing the footprint. (Also allows users to add their own models without the need to edit the footprint.)

**Comment by evanshultz** [comment]
@Misca1234 
Please merge this if it's ready and needed. However, I think it can be closed in favor of https://github.com/KiCad/kicad-footprints/pull/619, which I just merged.

@acolomb 
Thanks for contributing! Even if this PR isn't merged, we appreciate your willingness to give to the KiCad libraries and hope to see more from you in the future.

**Comment by acolomb** [comment]
After merging #619 and this one #632, we now have the SSOP-18 package duplicated. I guess my version didn't get the file name quite right, ending in `_Pitch0.65mm` instead of `_P0.65mm`.  There are some differences on the Silk layer also.

Feel free to delete my version in favor of #619, that one seems to blend in better with the rest. @Misca1234 sorry, I now realized that the other PR had already been filed when I started my work.

**Comment by evanshultz** [comment]
Created https://github.com/KiCad/kicad-footprints/pull/739.

@Misca1234 
I'm a bit baffled why this was merged. I pointed out above I believe I already merged the necessary footprint and this can be closed. The OP agrees. Did you find something unique about this footprint that required it to be merged also?

**Comment by Misca1234** [comment]
@evanshultz 
> @Misca1234
> Please merge this if it's ready and needed. However, I think it can be closed in favor of #619, 
> which I just merged.

I misinterpreted your "Please merge this if it's ready" and "I think it can be closed in favour" where I put a '=' between 'merge' and 'closed'

**Pull request merged**
