### PR TITLE
Mini-Circuits GP731/GP1212 plain footprint

### PR DESCRIPTION
**Pull request by aewallin**
Plain version of existing footprint, following #1308 
https://ww2.minicircuits.com/case_style/GP731.pdf

parent footprint was #1136, the changes here are:
- remove GND-pads
- all pad-connections to "from parent footprint"
- all clearances to zero
- no update to courtyard was needed.

gp731

*Replace this line with your commit message! Please provide a description of your pull request*

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by herostrat** [comment]
FYI, there are two footprints in this PR (GP731 and GP1212).

**Comment by aewallin** [comment]
yes, as seen from the PDF one is 100mil high and the other 150mil high - so we have two footprints in order to be able to assign two different height 3D models to the two footprints. I can change the title of the PR if it helps..

**Comment by herostrat** [comment]
Ah ok, I did not read through the whole exchange.
Just wanted to let you know, I know I pushed one footprint to the wrong branch while managing multiple footprints at once.

Sorry for the false alarm.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
