### PR TITLE
Rgb THT led URL fixes

### PR DESCRIPTION
**Pull request by aris-kimi**
Same as: https://github.com/KiCad/kicad-footprints/pull/2413

Not working link replaced, description corrected.

```
Checking footprint 'LED_D5.0mm-4_RGB':

  Violating F7.5

    Annular ring must be at least 0.15mm

    Pad 1 x-dimension annular ring (0.085mm) is below minimum (0.15mm)

    Pad 2 x-dimension annular ring (0.085mm) is below minimum (0.15mm)

    Pad 3 x-dimension annular ring (0.085mm) is below minimum (0.15mm)

    Pad 4 x-dimension annular ring (0.085mm) is below minimum (0.15mm)

Checking: LED_THT.pretty/LED_D5.0mm-4_RGB_Wide_Pins.kicad_mod

Checking footprint 'LED_D5.0mm-4_RGB_Wide_Pins' - No errors

```
This violation needs to stay i think.
εικόνα

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hellow @aris-kimi 
Can you double checked the datasheet you have indicated ? Seems it is not working here.
Instead i have found : https://www.kingbright.com/attachments/file/psearch/000/00/00/L-154A4SUREQBFZGEW(Ver.11A).pdf
Thanks
Joel

**Comment by myfreescalewebpage** [comment]
@aris-kimi ping

**Comment by aris-kimi** [comment]
Sorry, i am here now. I have used your link instead.
I am not sure to be honest. This link used to work. I have changed location and now it does not. It could be an isp issue or a bad url after all... If i open it again i will post a screenshot. I hope we won't need it :-)

**Comment by myfreescalewebpage** [comment]
Thanks.
Footprint "LED_D5.0mm-4_RGB_Staggered_Pins" is the same device and need also an upgrade of the datasheet, if you can do it.
Thanks
Joel

**Comment by myfreescalewebpage** [comment]
So cool ! Thanks !

**Pull request merged**
