### PR TITLE
Create TE_5767171-1

### PR DESCRIPTION
**Pull request by cronJ**
Add TE_5767171-1 (also known as Mictor38)

https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F5767171%7FB2%7Fpdf%7FEnglish%7FENG_CD_5767171_B2.pdf%7F5767171-1#page=2

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cronJ** [comment]
Numbering is defined here:

image

**Comment by chmorgan** [comment]
Hi @cronJ. On the left hand side courtyard did you push that out slightly to keep clearance with the fab line that is sticking out to the left? Is that fab line sticking out to indicate where pin 1 is? I'm thinking that it would make sense to make the fab lines match the part outline, then you can make the courtyard consistent and based on the fab, eg. we don't want to push the courtyard out due to a fab feature for pin 1 indication.

In terms of indicating pin 1 you can use a triangle or some other feature on both fab and silk. If its silk you would put it outside of the fab outline so it can be seen after the part is placed.

I don't have a clear idea of what this connector looks like from real world usage so apologizes for asking dumb questions.

**Comment by cronJ** [comment]
Here is the [part page](https://www.te.com/usa-en/product-5767056-1.html?te_campaign=oct_glo_manufacturer&elqCampaignId=26136&te_bu=Cor&te_type=other) so you can see how the real part looks like.

**Comment by chmorgan** [comment]
@cronJ can you check the changes I made to the fab, centering, courtyard etc? Once you get that stuff down it should take a lot less effort to get your footprints through the process.

**Comment by chmorgan** [comment]
@cronJ note that the travis check on footprint center is incorrect as this part has a plastic tab only on one side. If you check the footprint and packaging guidelines you can see that the pick and place clip is centered on the part itself.

**Pull request merged**
