### PR TITLE
Converter dcdc mu rata ncs1 sxxxx sc tht

### PR DESCRIPTION
**Pull request by Misca1234**
Repush of Converter_DCDC_Murata_NCS1SxxxxSC_THT
https://github.com/KiCad/kicad-footprints/pull/637

Data sheet
https://power.murata.com/data/power/ncl/kdc_ncs1.pdf

This footprint fits:

* NCS1S1203SC - 4.5-18V in, 3.3V out
* NCS1S1205SC - 4.5-18V in, 5V out
* NCS1S1212SC - 4.5-18V in, 12V out
* NCS1S2403SC - 9-36V in, 3.3V out
* NCS1S2405SC - 9-36V in, 5V out
* NCS1S2412SC - 9-36V in, 12V out

Datasheet: https://power.murata.com/data/power/ncl/kdc_ncs1.pdf

It is made with scripts
https://github.com/pointhi/kicad-footprint-generator/pull/211

Regarding the discussion about holes in earlier thread, holes are 1.0

3D model
https://github.com/KiCad/kicad-packages3D/pull/424

yml data
Converter_DCDC_Murata_NCS1SxxxxSC_THT:
  description: "Murata NCS1SxxxxSC https://power.murata.com/data/power/ncl/kdc_ncs1.pdf"
  datasheet: "https://power.murata.com/data/power/ncl/kdc_ncs1.pdf"
  tags: "Murata NCS1SxxxxSC"
  extratexts: [[-3.0, 0, "", "F.SilkS", 1.0, 1.0]]
  at: [-2.27, 3.195]
  size: [21.87, 8.2]
  pins: [["tht", "1", 0, 0, 2.0, 2.0, 1.0], ["tht", "2", 2.54, 0, 2.0, 2.0, 1.0], ["tht", "3", 5.12, 0, 2.0, 2.0, 1.0], ["tht", "6", 12.7, 0, 2.0, 2.0, 1.0], ["tht", "7", 15.24, 0, 2.0, 2.0, 1.0]]

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
The foot print is generated with the generic script StandardBox.py

This push can not be fixed until push 
https://github.com/pointhi/kicad-footprint-generator/pull/201

is merged (contains fixes for StandardBox)

**Comment by poeschlr** [comment]
The chamfer for marking pin 1 is a bit small. (should be 25% of shortest side length with a maximum of 1mm. Which in this case will mean 1mm size is required.)

The clearance between neighboring pads is a bit small. Maybe make the pads into ovals. (reducing the pad size in x direction by 0.22 would still leave 0.39mm annular ring while having 0.8mm clearance between the pads.)

screenshot from 2019-01-01 19-02-29

**Comment by Misca1234** [comment]
It looks like this now 
bild

bild

**Comment by poeschlr** [comment]
Pad 1 is smaller than the others in y direction.

**Comment by Misca1234** [comment]
They are now of the same height

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
