### PR TITLE
Inductor_SMD: Add Sumida CDMC6D28 SMD Power Inductor Series

### PR DESCRIPTION
**Pull request by gmsotavio**
Datasheet: http://products.sumida.com/products/pdf/CDMC6D28.pdf
L_Sumida_CDMC6D28_4

L_Sumida_CDMC6D28
L_Sumida_CDMC6D28_2
L_Sumida_CDMC6D28_3

L_Sumida_CDMC6D28_5
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
I'm aware that I need to append the body dimensions to the footprint name.

**Comment by gmsotavio** [comment]
I have changed the courtyard style and appended the body dimensions to footprint name.
image

**Comment by poeschlr** [comment]
The round corner is not dimensioned in the datasheet so i would not suggest to include it in the courtyard layer (for the others it is ok to indicate that this corner is rounded.)

**Comment by gmsotavio** [comment]
Sorry, I didn't understand. You are suggesting to remove rounded corners in Fab and CrtYd layers?

**Comment by gmsotavio** [comment]
Ok. I agree with you. Great that you have pointed out this mistake. The same is done in this PR, from another contributor: https://github.com/KiCad/kicad-footprints/pull/1720
image

**Comment by gmsotavio** [comment]
Ok. Good catch, I agree with you. Thank you for pointing out that mistake. 
In another PR, the contributor did the same mistake: https://github.com/KiCad/kicad-footprints/pull/1720. I kept the contoured style, but squared the corners. If you prefer, I can return the style to rectangular. KLC is not clear about the preferred style (both rectangular and contoured is allowed), but I have been moving my footprints to contoured style because it allows more density and is preferred in IPC-7351C.

image

Note: I messed up my branch, then a force push was unavoidable.

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
