### PR TITLE
Package_SO: Add SOIC 8 5.257x5.275

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
http://ww1.microchip.com/downloads/en/DeviceDoc/20005045C.pdf

Screenshot from 2019-05-16 12-56-26

Sym PR https://github.com/KiCad/kicad-symbols/pull/1859
Script PR https://github.com/pointhi/kicad-footprint-generator/pull/357

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
see comments on script pull request

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by poeschlr** [comment]
thanks.

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
