### PR TITLE
Keystone 2479 Fix: Vertical distance from pin 1 center to top F.Fab line and component length are not correct.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.keyelco.com/product-pdf.cfm?p=1041

imagen

From datasheet data, distance from pin 1 to component edge (F.Fab) is (37.49-23.5)/2=6,995nm.
Same distance in footprint is 5.95mm

imagen

Moved all drawings, keeping the pins and holes positions, to fix this.

Another problem is that component length is 52.63mm in datasheet, while length in footprint (see screenchot above) is 50.4+2.6mm=53mm.
Fixed this too.

Result with these changes:
imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cnieves1** [comment]
Regarding F5.4, it is the original design already in the library.

**Comment by cnieves1** [comment]
3D for fixed version at: https://github.com/KiCad/kicad-packages3D/pull/648

**Comment by poeschlr** [comment]
For reference: the footprint was originally added here https://github.com/KiCad/Battery_Holders.pretty/pull/4

**Comment by Misca1234** [comment]
There is a scrips in 
https://github.com/pointhi/kicad-footprint-generator.git
that create this foot print
kicad-footprint-generator/scripts/Battery/BatteryHolder.yml

Instead of modifying the existing fp, it could be re generated instead

**Comment by cnieves1** [comment]
This file was generated using https://github.com/pointhi/kicad-footprint-generator/pull/490
It seems previous file in master was not generated using this generator...

**Comment by evanshultz** [comment]
@cnieves1 
Do you find the scripted footprint to match the datasheet?

**Comment by cnieves1** [comment]
No, it does not match the datasheet, at least in height. Generated model is 11mm height, while datasheet specifies it as 13mm.

In cq_parameters.py, there is specified H=13.00. I tried changing it to H=15.00, but this has nothing to do with case height.

I don't know where I can change this...

**Comment by Misca1234** [comment]
Let me have a check, it was I who created the scripts originally

**Comment by cnieves1** [comment]
Sorry, I meant the 3D has incorrecta height, not the footprint...

**Comment by Misca1234** [comment]
Ok, the scripts have a number of basic shapes to model with, perhaps they are not flexible enough, let me check

**Comment by Misca1234** [comment]
I have fixed the script, but not pushed it, the problem was related to models that have a "thick bottom"
I hope I can push it this week

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
