### PR TITLE
Added LFCSP-WQ-24-7EP_4x4mm_P0.5mm_EP2.6416x2.6416mm

### PR DESCRIPTION
**Pull request by matthuszagh**
footprint datasheet
https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/cp_24_7.pdf

ultralibrarian model
https://app.ultralibrarian.com/Details/Item/Analog%2bDevices%2bInc/ADL5802ACPZ-R7/15411459?octoId=c7120f026f4c18d5

image

FYI, I'm adding this footprint in order to add [ADL5802](https://www.analog.com/media/en/technical-documentation/data-sheets/ADL5802.pdf) to the libraries. [PR](https://github.com/KiCad/kicad-symbols/pull/1375) for this symbol.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
mostly these are named "1EP" I think, to show that there is one exposed pad.

**Comment by matthuszagh** [comment]
I'll make the change. It looks like the rest of the differences can be encoded in the body size and EP size (although I'm not 100% sure on that), so I guess it shouldn't present any problems down the line.

How do you feel about 2.6416 vs 2.642? Does it make a difference?

**Comment by matthuszagh** [comment]
I went ahead and just made the 1EP change.

**Comment by evanshultz** [comment]
I'd prefer to script this footprint since it can be handled with the scripting tools at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_DFN_QFN. Let's discard anything ADI gives us and go with `LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm` using the IPC pad design. Are you up for that?

**Comment by evanshultz** [comment]
The package definition looks good to me. Can you let me know about the "few issues" you mentioned above? I'm not following you.

Would you also post a screenshot of the updated footprints?

Lastly, please remove the initial footprint you submitted.

**Comment by matthuszagh** [comment]
image

image

I'm seeing the following errors in travis:
Checking footprint 'LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm':
  Violating F6.3
    Pad requirements for SMD footprints
    Pad(s) potentially missing layers
     - Pad '25' missing layer 'Paste'
Checking: Package_CSP.pretty/LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm_ThermalVias.kicad_mod
Checking footprint 'LFCSP-24-1EP_4x4mm_P0.5mm_EP2.5x2.5mm_ThermalVias':
  Violating F6.3
    Pad requirements for SMD footprints
    Pad(s) potentially missing layers
     - Pad '25' missing layer 'Paste'
     - Pad '25' missing layer 'Paste'
     - Pad '25' missing layer 'Mask'
  Violating F7.4
    Pad requirements for THT footprints
    Some THT pads have incorrect layer settings
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'
     - Pad '25' missing layer '*.Mask'

**Comment by evanshultz** [comment]
Oh. Yes. Our check script isn't (yet) smart enough to realize this footprint design is actually good.

Thanks!

**Pull request merged**
