### PR TITLE
Move Sierra XA11X0 to RF_GPS

### PR DESCRIPTION
**Pull request by jneiva08**
Forgot to move Sierra XA11X0 from RF_Modules to RF_GPS

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@jneiva08 please also submit modification of kicad-symbols / kicad-packages3D repo at the same time, PR need to be merged at the same time.

Joel

**Comment by jneiva08** [comment]
I didn't find Symbol for this footprint

**Comment by myfreescalewebpage** [comment]
Confirmed, me too didn't found any symbol using this footprint. Merging the PR.

Joel

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
