### PR TITLE
Add TI 20-pin S-PVQFN 2.4mm EP variant

### PR DESCRIPTION
**Pull request by xl0**
Datasheet: http://www.ti.com/lit/ds/symlink/cc1101.pdf page 103.
pvqfn
QFN-20-1EP_4x4mm_P0.5mm_EP2.5x2.5mm 3D model matches reasonably well.

### CODE REVIEW

**Comment by Ratfink** [comment]
Thanks for the contribution!

This for the most part looks good.  There's just one thing I see that needs to be fixed: the paste openings for the EP should be 0.3 mm apart according to the datasheet, not 0.4 mm.

**Comment by woo2** [comment]
@Ratfink I'm sure you're busy. Have you made progress?

**Comment by Ratfink** [comment]
It's @xl0's PR, not mine.  I'm just here to review his work, give feedback, and merge when it's complete.  He said in https://github.com/KiCad/kicad-footprints/pull/456#issuecomment-379804219 that he'll try to work on these soon.

**Comment by Ratfink** [comment]
@xl0 It's been a month and a half now, and this PR is still blocking https://github.com/KiCad/kicad-symbols/pull/392.  Will you be able to finish it up, or should one of us librarians take over?

**Comment by xl0** [comment]
Sorry, overloaded at the moment. I will be able to finish this and the other pull requests in the foreseeable future, just not right now.

If someone else wants to take over, that's also totally fine with me.

**Comment by poeschlr** [comment]
I added this to my script. The pull request for the generated footprint is found in: https://github.com/KiCad/kicad-footprints/pull/691

**Comment by evanshultz** [comment]
Replaced with https://github.com/KiCad/kicad-footprints/pull/691.

**Pull request closed without merging**
