### PR TITLE
Fix pad sizes for two terminal smd devices (issue #466)

### PR DESCRIPTION
**Pull request by poeschlr**
The wrong IPC tables have been used for devices >=0603_1605Metric
For devices where the dimension S instead of T was given,
Smax was used instead fo Smax(RMS).

The example footprint given in #466:
Dimension G of the 2512 (6332Metric) footprint is now 4.54mm which is approximately Smin - 2*Heel = 4.45 - 2*(-0.05). The small difference comes from other considered tolerances.

Script pull request: https://github.com/pointhi/kicad-footprint-generator/pull/119

### CODE REVIEW

**Comment by poeschlr** [comment]
@evanshultz @Ratfink @jkriege2 @Shackmeister 

Can one of you take a look at this? The current smd two terminal footprints are not usable and this PR does fix that.

**Comment by Ratfink** [comment]
Overall, this looks great to me!  My one concern is that it looks like overly-conservative silkscreen-to-pad clearance caused 0805 parts to lose their silkscreen entirely, but the lines would be very short unless we go with the suggested clearance in #439, so this might be okay.

**Comment by Ratfink** [comment]
Actually, @Shackmeister brought up a good point at https://github.com/KiCad/kicad-packages3D/pull/280: some of the LED footprints we have don't seem to have any real parts that fit them.  I'd be in favor of removing those, as I mentioned in that thread.

**Comment by poeschlr** [comment]
If i remember correctly then i checked it with either farnell or RS and i could find some parts that would fit them. I don't have time to check it again. And even if we decide to remove them this should be done in a separate PR anyways. (One topic per PR)

**Comment by poeschlr** [comment]
Guys our current footprints are not usable for production. This PR (hopefully) fixes the problem. Could one of you guys look at it and decide if it can be merged?

Please only look at the size of the pads. Other discussions should be made in a separate issue.

**Comment by Shackmeister** [comment]
pad sizes looks good to me, Ill merge it
But a few more eyes on this wouldnt hurt as it's some pretty important parts

a small script enhancement which could be added in the future, flip the Fab REF** is the package is wider than long

**Pull request merged**
