### PR TITLE
Add USB_C_Receptacle_XKB_U262-161N-4BVC11

### PR DESCRIPTION
**Pull request by twam**
Screenshot: image

Datasheet: https://datasheet.lcsc.com/szlcsc/1811141824_XKB-Enterprise-U262-161N-4BVC11_C319148.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by jstjst** [comment]
I took a look at the footprint and noticed following things: 
- [ ] Name should be `USB_C_Receptacle_XKB_U262-16XN-4BVC11`
- [ ] The dimensions in red should be fixed (Take a look at the comment below about the datasheet first)
- [ ] Clearance between silkscreen and pads should be 0.2mm
- [ ] Silkscreen Reference Designator should be outside the component
- [ ] Component value at Fab layer should be below the component
- [ ] Courtyard should have a clearance of 0.5mm
- [ ] Silkscreen should not overlap Fab layer (use a offset of 0.11mm, so that silkscreen and fab just touches)
- [ ] Footprint anchor should be placed in the middle of the component body
- [ ] Description should be added (look at the other USB C Connectors)
grafik
grafik

Maybe this datasheet should be used: http://www.helloxkb.cn/uploads/USB/U262-16XN-4BVC11.pdf
The dimensions in this datasheet are also a bit different. I think a librarian should take a look at this.

**Comment by twam** [comment]
First of all thank you for your intensive review.

 * [x]  Name should be `USB_C_Receptacle_XKB_U262-16XN-4BVC11`
 * [ ]  The dimensions in red should be fixed (Take a look at the comment below about the datasheet first)
> The datasheet you digged out does not mention the size of the pads. How did you infer them?
 * [x]  Clearance between silkscreen and pads should be 0.2mm
 * [x]  Silkscreen Reference Designator should be outside the component
 * [x]  Component value at Fab layer should be below the component
 * [x]  Courtyard should have a clearance of 0.5mm
 * [x]  Silkscreen should not overlap Fab layer (use a offset of 0.11mm, so that silkscreen and fab just touches)
 * [x]  Footprint anchor should be placed in the middle of the component body
> This will result in a warning of the checker, but nevertheless changed it now.
 * [x]  Description should be added (look at the other USB C Connectors)
 * [x] Maybe this datasheet should be used: http://www.helloxkb.cn/uploads/USB/U262-16XN-4BVC11.pdf

**Comment by jstjst** [comment]
You got the silkscreen and Fab mixed up: The Fab layer should represent the real component dimension and the silkscreen should have a offset (the offset is not fixed but 0.11 and 0.06 are commonly used) to the outside, so it is visible after assembly. Take a look at this footprint as an example: `USB_C_Receptacle_GCT_USB4085`
Also try use a 0.01mm grid for graphic lines.

**Comment by twam** [comment]
Sorry to mix that up. Swapped them now:

image

**Comment by jstjst** [comment]
Looks pretty good now, just some things left:
- [ ] Use this (your original) datasheet, because there are all the dimensions: https://datasheet.lcsc.com/szlcsc/1811141824_XKB-Enterprise-U262-161N-4BVC11_C319148.pdf
- [ ] Fix the red dimensions
- [ ] Place Reference on silkscreen above the component, because text should not overlap

grafik

**Comment by twam** [comment]
Hopefully now everything is fixed. Thanks for all your efforts.
image

PS: I really need to get the creation of that nice images running on my Mac. ;)

**Comment by jstjst** [comment]
The bottom edge is 0.01 mm to low, the rest is fine:
grafik

Take a look a look at these instructions: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279
I was able to use TechDraw, but you need FreeCAD 0.19 to draw centerlines

**Comment by twam** [comment]
The bottom line should be at 3,675 mm as the component is 7,35 mm height. As you asked me to put all lines at a 0.01 mm grid I moved it to 3,68 mm (outwards). Result in an increase of the distance between the hole in and the line from 2.6 to 2.605 mm (not 2.61 mm!). For that reason the distance between the two lines is also increased by 2*0.005 mm = 0.01 mm.

**Comment by jstjst** [comment]
Sorry, didn't realized that. I think I put the origin on one side (so it is 0,005mm off center) at components with an odd overall dimension. But I don't know if this is the right way to handle it.
@poeschlr What is the common practice in this case? Other than that the footprint would be ready to merge.

**Comment by poeschlr** [comment]
> As you asked me to put all lines at a 0.01 mm grid

Only the courtyard layer has this rule. The fab layer should be drawn exactly.

**Comment by twam** [comment]
> Only the courtyard layer has this rule. The fab layer should be drawn exactly.

And the silkscreen? Still offset by 0.11 mm or also align on 0.01 mm grid?

**Comment by poeschlr** [comment]
Silk is not really important. Just make sure it is visible after assembly. (fully outside nominal dimensions but still close enough to the body to be of help) If i make a footprint by hand then i use a reasonable grid for the silk outline. If i make it with a script then i offset the silk by exactly 0.11mm.

One thing that is important is to have at least the line width clearance to exposed copper (pads) I however suggest to use a clearance of 0.2mm for a component this large (allows cheaper fabs to be used by our users)

**Comment by jstjst** [comment]
@poeschlr Dimension fixed now, so it is ready to merge.

**Comment by poeschlr** [comment]
thanks to both of you

**Pull request merged**
