### PR TITLE
Magnetic buzzer kobitone 254 emb84 q ro

### PR DESCRIPTION
**Pull request by Misca1234**
This is a re push of 
Kobitone 254-EMB84Q-RO
https://www.mouser.es/datasheet/2/209/KT-400385-1171904.pdf

original push
https://github.com/KiCad/kicad-footprints/pull/558

I was to quick with to merge it, missed to point that the distance between the F.Fab and FSilk was to small, so this push address that

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please fix conflicts :)

**Comment by Misca1234** [comment]
hmmmrrfff, one sec

**Comment by Misca1234** [comment]
The banaman was included as well, let me remove it

**Comment by Misca1234** [comment]
Now so, all done

**Pull request merged**
