### PR TITLE
Added footprint for ADE7953

### PR DESCRIPTION
**Pull request by G-Pereira**
[Footprint](https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/cp-28/CP_28_10.pdf) for [ADE7953](https://www.analog.com/media/en/technical-documentation/data-sheets/ADE7953.pdf)
https://github.com/KiCad/kicad-symbols/pull/2897
image

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by G-Pereira** [comment]
All my edits are done, it's ok now :)

**Review by chschlue — CHANGES_REQUESTED** [review]
Please link to the corresponding generator PR.

**Comment by G-Pereira** [comment]
> Please link to the corresponding generator PR.

I have used KiCAD's built-in generator. What do you mean?

**Comment by chschlue** [comment]
That explains it. I was wondering why it looked odd somehow.

Sry, this was supposed to be done using https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by G-Pereira** [comment]
> That explains it. I was wondering why it looked odd somehow.
> 
> Sry, this was supposed to be done using https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

@chschlue Thank you for pointing me in the right direction! It should be fine now, [this](https://github.com/KiCad/kicad-footprints/files/5130134/lfcsp-28.yaml.txt) was the file I created to generate the footprint I've just committed.

**Comment by G-Pereira** [comment]
@chschlue I am getting a warning on Travis that tells me that I am probabily missing the Paste layer for the pad. [This](https://github.com/KiCad/kicad-footprints/files/5130373/lfcsp-28.yaml.txt) is the generation file.

**Review by chschlue — CHANGES_REQUESTED** [review]
The CI error is fine, the EP isn't a combined copper+paste pad but has paste pads of their own to achieve the desired paste coverage.

Please open a PR on the generator repo adding the size definitions.

**Comment by G-Pereira** [comment]
What pas coverage should I use? EP_paste_coverage: 0.75 or 0.65?

**Comment by chschlue** [comment]
As long as there's no manufacturer recommendation, please leave it out.
That way, it can always be recreated using the then current generator's default change.

**Comment by G-Pereira** [comment]
Done! https://github.com/pointhi/kicad-footprint-generator/pull/593 I will update the footprint generation once that is merged. I will temporarily make a commit with the current version

**Comment by G-Pereira** [comment]
I've noticed I haven't marked as complete. What do you think of the footprint now @chschlue ?

**Comment by chschlue** [comment]
Merged. Please update.

**Comment by G-Pereira** [comment]
It is already up to date

**Comment by G-Pereira** [comment]
@chschlue  I really thought it was but apparently it is not. Sadly the generator is throwing this unrelated error atm:
```
$ python3 size_definitions/lfcsp.yaml 
  File "size_definitions/lfcsp.yaml", line 1
    LFCSP-WD-8-1EP_3x3mm_P0.65mm_EP1.6x2.44mm:
                ^
SyntaxError: invalid syntax
```

**Comment by G-Pereira** [comment]
Updated now!

**Review by chschlue — APPROVED** [review]
Thanks.

**Pull request merged**
