### PR TITLE
added FFC molex series 502231

### PR DESCRIPTION
**Pull request by Shackmeister**
Datasheet: https://www.molex.com/pdm_docs/sd/5022312400_sd.pdf

OBS: The lock is sticking out on one side, since I need the space under I just added it in cmts.user.
If prefered I can add this to the fab layer.

Travis might complain about the center of the footprint, the center is estimated from the datasheet and measured using FC

Skærmbillede fra 2019-06-10 15-40-48

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@Shackmeister 
There were handmade, I presume?

**Comment by Shackmeister** [comment]
Yes b)

**Comment by evanshultz** [comment]
The ground pads aren't really a shield, right? More like a mounting point. So 'MP' instead of 'SH'?

All dimensions check out for me:
image

@poeschlr 
Are you OK using Cmts.User for this purpose? Makes sense to me since there's no an immovable element there that must always be avoided, but only something to watch out for at a height above the PCB surface that allows small components to fit. With the current limitations of KiCad, visual 3D checking might help but I don't think it's right to use F.Fab.

**Comment by Shackmeister** [comment]
The pads are connected to shield of the flat Flex cable

**Comment by evanshultz** [comment]
Ahh. OK.

Two more things:
1. The center is shown as, I guess, 2.21mm below the edge of the pin tips in the datasheet. I don't know exactly where the pin tip lays on the pad, but the top edge of the pins in the footprint are 1.73mm (1.045mm pad center + 1.37mm tall pads / 2). So it seems like if you were targeting that center from the datasheet the pin tips will stick off the pads. Have I misunderstood?
1. Pad corner radius should be 25% up to 0.25mm. The SH pads have too much corner radius.

**Comment by Shackmeister** [comment]
1. I used the image in page 4 showing the pick place center, did some measurements in FC on the 3D model, and moved it from there.

2. Fixed the corner radius to 0.25mm

**Comment by evanshultz** [comment]
OK. We'll go with that. Thanks!

**Pull request merged**
