### PR TITLE
Footprint for Quectel BC66

### PR DESCRIPTION
**Pull request by jneiva08**
Add footprint for Quectel BC66

Datasheet: https://www.quectel.com/UploadImage/Downlad/Quectel_BC66_Hardware_Design_V1.1.pdf
**Note:** to access datasheet needs to be register on Quectel website.

Screenshot:
bc66

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I would suggest the use of rounded rectangle pads with 25% round radius ration (maximum 0.25mm)
This is in preference to the oval pad shapes shown in the datasheet. (As defined by IPC)

The datasheet contains following note:
> The module should be kept about 3mm away from other components on the host PCB.

We could implement this with the courtyard layer. (use a clearance of 3mm between the courtyard and the body.)

Some of the inner pads are positioned wrong
screenshot from 2019-01-23 22-15-21

**Comment by poeschlr** [comment]
Why 29% roundrect radius? IPC would specify 25%

**Comment by jneiva08** [comment]
the footprint have the following aspect:

bc66

Have fixed the inner pad, and moved back the roundrect radius to 25%, and added courtyard to 3mm instead of 0.25mm.

**Comment by poeschlr** [comment]
You used the 3mm clearance relative to the pads. I would read the datasheet as if it should be relative to the body.

The rest of your fixes look good.

screenshot from 2019-01-25 16-33-00

**Comment by jneiva08** [comment]
Removed extra 1mm from F.CrtYd

modem

**Comment by poeschlr** [comment]
Looks good now. thanks

**Comment by jneiva08** [comment]
thanks, for your time :+1:

**Pull request merged**
