### PR TITLE
Add BatteryHolder Keystone 1048 into Battery.pretty

### PR DESCRIPTION
**Pull request by ghost**
Add BatteryHolder Keystone 1048 into Battery.pretty
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by mike7b4** [comment]
Yeah the reason I didn't post screenshot is cause travis cl check failed so I try solve  the problem but then got interrupted by other stuff. So I will try again today solve the issues :)

Btw I changed to footprint and used same URL as the one in 1042 but changed id to 120

http://www.keyelco.com/product.cfm/product_id/920

**Comment by mike7b4** [comment]
Yup. Known the issues.

Got interrupted by other stuff yesterday so this issue is not yet solved. The reason I did not post a screenshot was because travis CI failed build so I planned to fix the issues before add a screenshot.

Also the link to keystone is now same as 1042 except different artid but it points to the homepage not the PDF itself?

 http://www.keyelco.com/product.cfm/product_id/920 but do you want me to set to the octopart link in the footprint settings if so maybe thge 1042 should also get changed?

Hopefully I get the issues fixed today or else I put it on hold.

**Comment by mike7b4** [comment]
screenshot of footprint.

screenshot_20180408_142754

**Comment by mike7b4** [comment]
screen shoot of footprint.
screenshot_20180408_145705

**Comment by Ratfink** [comment]
[KLC]: http://kicad-pcb.org/libraries/klc/ "KiCad Library Convention"
[G1.1]: http://kicad-pcb.org/libraries/klc/G1.1/ "Only standard characters are used for naming libraries and components"
[G1.2]: http://kicad-pcb.org/libraries/klc/G1.2/ "Each library is limited to 250 items"
[G1.3]: http://kicad-pcb.org/libraries/klc/G1.3/ "Libraries are organized by functionality"
[G1.4]: http://kicad-pcb.org/libraries/klc/G1.4/ "English language should be used throughout libraries"
[G1.5]: http://kicad-pcb.org/libraries/klc/G1.5/ "Plural naming is to be avoided"
[G1.6]: http://kicad-pcb.org/libraries/klc/G1.6/ "Capitalization conventions"
[G1.7]: http://kicad-pcb.org/libraries/klc/G1.7/ "Library files use Unix style line endings"
[G1.8]: http://kicad-pcb.org/libraries/klc/G1.8/ "Components can only contain features supported in latest stable release"
[G1.9]: http://kicad-pcb.org/libraries/klc/G1.9/ "Dimensional units"
[G2.1]: http://kicad-pcb.org/libraries/klc/G2.1/ "Defining generic and atomic parts"
[S1.1]: http://kicad-pcb.org/libraries/klc/S1.1/ "Symbol libraries should be categorized by function"
[S2.1]: http://kicad-pcb.org/libraries/klc/S2.1/ "General symbol naming guidelines"
[S2.2]: http://kicad-pcb.org/libraries/klc/S2.2/ "Non-functional variations in part number should be replaced with wildcard"
[S2.3]: http://kicad-pcb.org/libraries/klc/S2.3/ "Where atomic parts are available in multiple footprint options, a separate symbol must be drawn for each footprint"
[S3.1]: http://kicad-pcb.org/libraries/klc/S3.1/ "Origin is centered on the middle of the symbol"
[S3.2]: http://kicad-pcb.org/libraries/klc/S3.2/ "Text fields should use a common text size of 50mils"
[S3.3]: http://kicad-pcb.org/libraries/klc/S3.3/ "Symbol outline and fill requirements"
[S3.4]: http://kicad-pcb.org/libraries/klc/S3.4/ "Symbols with complex functionality may incorporate simple functional diagrams"
[S3.5]: http://kicad-pcb.org/libraries/klc/S3.5/ "Pin connection points must be placed outside of the symbol"
[S3.6]: http://kicad-pcb.org/libraries/klc/S3.6/ "Pin name position offset"
[S3.7]: http://kicad-pcb.org/libraries/klc/S3.7/ "Pin numbering for exposed pads"
[S3.8]: http://kicad-pcb.org/libraries/klc/S3.8/ "Multi unit symbols"
[S4.1]: http://kicad-pcb.org/libraries/klc/S4.1/ "General pin requirements"
[S4.2]: http://kicad-pcb.org/libraries/klc/S4.2/ "Pins should be grouped by function"
[S4.3]: http://kicad-pcb.org/libraries/klc/S4.3/ "Rules for pin stacking"
[S4.4]: http://kicad-pcb.org/libraries/klc/S4.4/ "Pin electrical type"
[S4.5]: http://kicad-pcb.org/libraries/klc/S4.5/ "Pins not connected on the footprint may be omitted from the symbol"
[S4.6]: http://kicad-pcb.org/libraries/klc/S4.6/ "Hidden pins"
[S4.7]: http://kicad-pcb.org/libraries/klc/S4.7/ "Active low pins should be designated using a bar above the symbol name"
[S5.1]: http://kicad-pcb.org/libraries/klc/S5.1/ "Symbols with a default footprint link to a valid footprint file"
[S5.2]: http://kicad-pcb.org/libraries/klc/S5.2/ "Footprint filters should match all appropriate footprints"
[S6.1]: http://kicad-pcb.org/libraries/klc/S6.1/ "Component Reference Designator (RefDes)"
[S6.2]: http://kicad-pcb.org/libraries/klc/S6.2/ "Component fields must be filled appropriately"
[S6.3]: http://kicad-pcb.org/libraries/klc/S6.3/ "Component metadata is added to symbol (and all aliases)"
[S7.1]: http://kicad-pcb.org/libraries/klc/S7.1/ "Power flag symbols"
[S7.2]: http://kicad-pcb.org/libraries/klc/S7.2/ "Graphical symbols"
[F1.1]: http://kicad-pcb.org/libraries/klc/F1.1/ "Footprint libraries are categorized by function"
[F1.2]: http://kicad-pcb.org/libraries/klc/F1.2/ "Connector footprint libraries"
[F2.1]: http://kicad-pcb.org/libraries/klc/F2.1/ "General footprint naming conventions"
[F2.2]: http://kicad-pcb.org/libraries/klc/F2.2/ "Footprint naming field prefixes"
[F2.3]: http://kicad-pcb.org/libraries/klc/F2.3/ "Manufacturer specific version of generic footprints"
[F2.4]: http://kicad-pcb.org/libraries/klc/F2.4/ "Footprint naming for non-standard pin numbering"
[F2.5]: http://kicad-pcb.org/libraries/klc/F2.5/ "Footprint naming conventions for specific components"
[F3.1]: http://kicad-pcb.org/libraries/klc/F3.1/ "SMD chip package naming conventions"
[F3.2]: http://kicad-pcb.org/libraries/klc/F3.2/ "Resistor naming conventions"
[F3.3]: http://kicad-pcb.org/libraries/klc/F3.3/ "Capacitor naming conventions"
[F3.4]: http://kicad-pcb.org/libraries/klc/F3.4/ "SMD IC package naming conventions"
[F3.5]: http://kicad-pcb.org/libraries/klc/F3.5/ "THT IC package naming conventions"
[F3.6]: http://kicad-pcb.org/libraries/klc/F3.6/ "Connector naming conventions"
[F3.7]: http://kicad-pcb.org/libraries/klc/F3.7/ "Fuse naming conventions"
[F4.1]: http://kicad-pcb.org/libraries/klc/F4.1/ "Datasheet recommendations take priority"
[F4.2]: http://kicad-pcb.org/libraries/klc/F4.2/ "Pin 1 should be located at the top left"
[F4.3]: http://kicad-pcb.org/libraries/klc/F4.3/ "Connected copper elements have the same pad number"
[F4.4]: http://kicad-pcb.org/libraries/klc/F4.4/ "Thermal pads"
[F4.5]: http://kicad-pcb.org/libraries/klc/F4.5/ "Specifying footprint keepout areas"
[F4.6]: http://kicad-pcb.org/libraries/klc/F4.6/ "Local clearance and settings should be set to zero"
[F5.1]: http://kicad-pcb.org/libraries/klc/F5.1/ "Silkscreen layer requirements"
[F5.2]: http://kicad-pcb.org/libraries/klc/F5.2/ "Fabrication layer requirements"
[F5.3]: http://kicad-pcb.org/libraries/klc/F5.3/ "Courtyard layer requirements"
[F6.1]: http://kicad-pcb.org/libraries/klc/F6.1/ "Footprint placement type must be set to surface mount"
[F6.2]: http://kicad-pcb.org/libraries/klc/F6.2/ "Footprint anchor should be placed in the middle of the component body"
[F6.3]: http://kicad-pcb.org/libraries/klc/F6.3/ "Pad requirements for SMD footprints"
[F7.1]: http://kicad-pcb.org/libraries/klc/F7.1/ "Footprint placement type must be set to Through Hole"
[F7.2]: http://kicad-pcb.org/libraries/klc/F7.2/ "Footprint anchor should placed at the location of Pin-1"
[F7.3]: http://kicad-pcb.org/libraries/klc/F7.3/ "Pin 1 should be rectangular, and other pads circular or oval"
[F7.4]: http://kicad-pcb.org/libraries/klc/F7.4/ "Pad requirements for THT footprints"
[F7.5]: http://kicad-pcb.org/libraries/klc/F7.5/ "Minimum annular ring width"
[F7.6]: http://kicad-pcb.org/libraries/klc/F7.6/ "Minimum hole diameter"
[F8.1]: http://kicad-pcb.org/libraries/klc/F8.1/ "Virtual components"
[F9.1]: http://kicad-pcb.org/libraries/klc/F9.1/ "Footprint meta-data is filled in as appropriate"
[F9.2]: http://kicad-pcb.org/libraries/klc/F9.2/ "Footprint properties are as default values unless otherwise required in datasheet"
[F9.3]: http://kicad-pcb.org/libraries/klc/F9.3/ "Footprint 3D model requirements"
[M1.1]: http://kicad-pcb.org/libraries/klc/M1.1/ "Models should be created by contributor"
[M1.2]: http://kicad-pcb.org/libraries/klc/M1.2/ "Manufacturer models should not be duplicated"
[M1.3]: http://kicad-pcb.org/libraries/klc/M1.3/ "Source files for 3D models should be supplied"
[M2.1]: http://kicad-pcb.org/libraries/klc/M2.1/ "Permitted 3D model file types"
[M2.2]: http://kicad-pcb.org/libraries/klc/M2.2/ "Model alignment and scaling"

No, don't use the Octopart datasheet URL I posted, that was just as a reference for reviewers because Keystone's website wasn't loading for me yesterday (but now it is).  Using a datasheet straight from the manufacturer is always preferred. 🙂

Thanks for centering the footprint properly.  Besides meeting KLC requirements, that makes checking dimensions a lot easier.

* Please be consistent in use of metric and inch dimensions from the datasheet.  I see that you sized the pads as the minimum size required by the datasheet in inches, but the mounting holes appear to use the metric diameter with inch positions.  To follow the Keystone 1042 that's already in the library, I suggest using the metric dimensions for everything.
* The silkscreen, fabrication layer, and courtyard still all need work.
  * The fab layer lines should make a precise, closed outline of the part, following the datasheet drawing ([F5.2]).  The chamfer at the corner should be at 45 degrees, and would preferably be only 1 mm high and wide.
  * The silkscreen outline should be precisely positioned just outside the fab layer outline (ideally with an offset of 0.11 or 0.12 mm from the fab layer lines, your choice which offset to use), making sure there's no silkscreen under the part ([F5.1]).  There should be a mark for pin 1 like the 1042 has, and for a battery holder like this one, + and - marks to indicate polarity would be nice to have as well.  The silkscreen lines should keep a 0.20 mm clearance from the pads.
  * The courtyard should form a precise, closed outline with a 0.5 mm clearance from exposed copper pads and the part body ([F5.3]).  This is used to help users keep parts a reasonable distance away from one another to aid assembly and rework.

Finally, I notice that there's no symbol in the library that would work for this part.  As such, pin numbering is an open question.  I suggest the following:

1. Cell 1 +
2. Cell 1 -
3. Cell 2 +
4. Cell 2 -

@evanshultz @jkriege2 @poeschlr @Misca1234 @Shackmeister Does this pin numbering for two-cell, four-terminal battery holders sound good to y'all?

**Comment by Misca1234** [comment]
Should not 
BatteryHolder_Keystone_1048_2x18650
or at least  
REF**
Be outside F.CrtYrd, otherwise they wont be visible ?

**Comment by poeschlr** [comment]
Not outside courtyard but outside of the area covered by the part. (Meaning if the part is designed correctly they should be outside of the fab layer.) And yes i am a bit pedantic with the wording here. (Being outside of the courtyard would also guarantee visibility. But for parts with very simplified courtyard outlines this might be quite far away from the actual part it self.)

**Comment by Misca1234** [comment]
@Ratfink 
> @evanshultz @jkriege2 @poeschlr @Misca1234 @Shackmeister Does this pin numbering for two-cell,
> four-terminal battery holders sound good to y'all?

In principle I don't object to have other "pin names" than the regular 1,2,3,4, ..., we already have A1, A2, A3 ...

**Comment by Ratfink** [comment]
Oh, I see the user who submitted this PR has deleted their account.  We could close the PR, or one of us could adopt it.  Given all the problems listed in the last review, I feel like if someone still wanted to submit a footprint for this part, the easiest approach would be to start from scratch.  Therefore, I'm in favor of closing this.

**Comment by Misca1234** [comment]
Agree, 
I don't mind to adopt it and put it up on my list of future pushes

**Comment by Ratfink** [comment]
Actually, it looks like we can't even add more commits to the PR branch because the repository is gone.  I'll close this then, as it would have to be resubmitted no matter what.

**Pull request closed without merging**
