### PR TITLE
Add script generated HVQFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm

### PR DESCRIPTION
**Pull request by Kev-J**
Hi, this HVQFN footprint was necessary for my symbol of the PN512 (https://github.com/KiCad/kicad-symbols/pull/2884)

Datasheet: https://www.nxp.com/docs/en/package-information/SOT617-1.pdf
Sans titre

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cpresser** [comment]
Can you please add a link to the script? I would like to review that.

**Comment by chschlue** [comment]
@cpresser This looks like it's been made using Modedit's FP generator.
I guess we should be more verbose about the whole "scripting required" issue...

@Kev-J please script this using https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by Kev-J** [comment]
In fact I used the KiCAD built-in tool to generate this. Wasn't it the good way to do?

**Comment by Kev-J** [comment]
@chschlue thanks for the hint. I will do a PR on the kicad-footprint-generator to add this piece of yaml:
kicad-footprint-generator/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/hvqfn.yaml

```
HVQFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm:
  device_type: 'HVQFN'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'https://www.nxp.com/docs/en/package-information/SOT617-1.pdf'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  body_size_x:
    minimum: 4.9
    nominal: 5.0
    maximum: 5.1
  body_size_y:
    minimum: 4.9
    nominal: 5.0
    maximum: 5.1
  overall_height:
    maximum: 1
  lead_width:
    minimum: 0.18
    maximum: 0.3
  lead_len:
    minimum: 0.3
    maximum: 0.5

  EP_size_x:
    minimum: 3.1
    maximum: 3.1
  EP_size_y:
    minimum: 3.1
    maximum: 3.1
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [2, 2]
  #EP_size_limit_x: 2.7  #for relatively large EP pads (increase clearance)
  #EP_size_limit_y: 2.7  #for relatively large EP pads (increase clearance)

  thermal_vias:
    count: [4, 4]
    drill: 0.2
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    # EP_num_paste_pads: [2, 2]
    EP_paste_coverage: 0.55
    # grid:
    # bottom_pad_size:
    # paste_avoid_via: True
  pitch: 0.5
  num_pins_x: 8
  num_pins_y: 8
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'
```

However, I got the following error:
`ValueError: Chamfer size ((x=0.21824767465201061, y=0.21824767465201061)) too large for given pad size ((x=0.18540496217739158, y=0.18540496217739158))`

I tried to play with chamfer_edge_pins but I couldn't get a generated module. Do you have any hint on what I did wrong?

Cheers,
Kevin

**Comment by cpresser** [comment]
> In fact I used the KiCAD built-in tool to generate this. Wasn't it the good way to do?
> 
> Edit: My bad, I thought the process was the same as for symbols. I got it now :) May I suggest to add a checkbox in the PR template like "paste the script if the package is requiring it"

No, you could not know. Afaik it is nowhere documented. Which is bad.
Its on my todo-list for stuff after the gitlab move.

The 'correct' approch is to open a PR in the footprints-generator repo that adds the .yaml changes. So we can recreate those footprints later if required.
I will review that script, and if it is good, merge the script and the generated symbol.

**Comment by Kev-J** [comment]
> 
> 
> > In fact I used the KiCAD built-in tool to generate this. Wasn't it the good way to do?
> > Edit: My bad, I thought the process was the same as for symbols. I got it now :) May I suggest to add a checkbox in the PR template like "paste the script if the package is requiring it"
> 
> No, you could not know. Afaik it is nowhere documented. Which is bad.
> Its on my todo-list for stuff after the gitlab move.
> 
> The 'correct' approch is to open a PR in the footprints-generator repo that adds the .yaml changes. So we can recreate those footprints later if required.
> I will review that script, and if it is good, merge the script and the generated symbol.

Ok, you can find the PR right here: https://github.com/pointhi/kicad-footprint-generator/pull/629

**Comment by cpresser** [comment]
@chschlue This is a duplicate of `QFN-32-1EP_5x5mm_P0.5mm_EP3.1x3.1mm`.
I have no clue what the current approach is for those cases. Can you help me out with this?

**Comment by chschlue** [comment]
Sadly, the current approach is to add duplicates if manufacturer naming differs (as in this case).
The future approach will probably be to remove all those [HVTUWwhatever] prefixes and add a height parameter instead (I can search for the discussion regarding this later.)

**Comment by myfreescalewebpage** [comment]
@cpresser do you want to review this one ? Else tell me I will do it

**Comment by cpresser** [comment]
Thanks for the reminder @myfreescalewebpage
This was ready to merge, but I missed it. To much open PRs.

**Pull request merged**
