### PR TITLE
Bourns MF-RG series PTC fuses

### PR DESCRIPTION
**Pull request by ppelleti**
[Datasheet](http://www.bourns.com/docs/Product-Datasheets/mfrg.pdf).

mf-rg300

mf-rg1100

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Ratfink** [comment]
Thanks for volunteering to add these footprints to the KiCad library.  Unfortunately, the datasheet is missing a dimension for all of the parts!
screenshot from 2018-05-31 17-34-25
Fortunately, this dimension can be found from the .stp 3D models for these parts: http://www.bourns.com/resources/design-tools/engineering-files-list?folder=mfrg
Using FreeCAD, I measured this dimension as 1.20 mm for all of these parts.  You can independently verify this if you'd like.

Anyway, please fix the footprints so the pins have this Y offset.  Other than that, these footprints look great.  Were they made by hand, or with a script?

**Comment by ppelleti** [comment]
> You can independently verify this if you'd like.

No, I don't know anything about FreeCAD.  Thanks for doing the measurement.

> Anyway, please fix the footprints so the pins have this Y offset.

I will add that to the script.

> Were they made by hand, or with a script?

Yes, I made these and also the [MF-RHT series](https://github.com/KiCad/kicad-footprints/pull/580) with a script.

**Comment by poeschlr** [comment]
When we ask if you made something with a script then we kind of expect a link to the script. (It is easier for us to check a script for correctness then to check the dimensions of 29 files.)

**Comment by ppelleti** [comment]
Sure, I will provide the script.  It's not ready yet, though, because I haven't added the Y offset yet.

I will try to get back to this soon and finish the script.  (Adding the offset is easy, but the hard part is handling all the cases where part of the silkscreen outline needs to be removed because it is too close to the pad.)

**Comment by poeschlr** [comment]
The [kicad footprint generator (KicadModTree)](https://github.com/pointhi/kicad-footprint-generator) supports silk keepout. (Implemented by @jkriege2 for the terminal block footprints)
It is found under tools. Maybe this can help.

**Comment by ppelleti** [comment]
> The kicad footprint generator (KicadModTree) supports silk keepout.

Thanks!  I'm using KicadModTree, but I hadn't known about the silk keepout tools.  I will take a look at that.

**Comment by ppelleti** [comment]
OK, I've added the offset.  The silk keepout tool made this a lot easier!

fuse_bourns_mf-rg300

The script that generated these is on the [ptc-fuse-tht](https://github.com/ppelleti/kicad-footprint-generator/tree/ptc-fuse-tht) branch of my fork of the kicad-footprint-generator repo.  Specifically, the two files in question are [ptc-fuse-tht.py](https://github.com/ppelleti/kicad-footprint-generator/blob/ptc-fuse-tht/scripts/Fuse/ptc-fuse-tht.py) and [ptc-fuse-tht.yaml](https://github.com/ppelleti/kicad-footprint-generator/blob/ptc-fuse-tht/scripts/Fuse/ptc-fuse-tht.yaml).

**Comment by SchrodingersGat** [comment]
Thanks @ppelleti

**Pull request merged**
