### PR TITLE
Added Keystone 3002

### PR DESCRIPTION
**Pull request by valerionew**
Hi, 
I've added the Keystone 3002 battery holder for 2032 button cells.

Documentation sources:
* https://www.tme.eu/it/Document/a823211ec201a9e209042d155fe22d2b/KEYS2996.pdf
* https://www.mouser.it/Power/Battery-Holders-Clips-Contacts/Coin-Cell-Battery-Holders/Datasheets/_/N-cicxg?keyword=534-3002
* https://www.mouser.it/datasheet/2/209/epd_10012015_12BH002-GR-1171043.pdf (clone)

image

Updated to 14fe1ed
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Do you have a reason why you use a much larger center pad than suggested.

There are a few dimensions wrong. Check the left bottom side of the fab outline for the soldering tab. (it is too low down. This is the reason for that left edges center to be too low.)

Screenshot from 2019-04-02 21-14-43

**Comment by 5N44P** [comment]
The pad dimension is free, only the minimum is specified. A bigger pad improves the contact area in case of an uneven surface. I've reduced it a bit to minimize the risk of short circuits.

Everything else should be fixed, except travis that started loosing his mind again

**Comment by 5N44P** [comment]
I've tried rebasing my branch but it didn't work

**Comment by 5N44P** [comment]
@poeschlr looks like adding an empty commit was enough to solve the issue, may i try with my other PR at #804?

**Comment by poeschlr** [comment]
Thanks for informing me of that workaround. Yes try it for the other request as well.

I would however guess that there was some bug in travis that simply got resolved in the meantime. (I restarted the build over there by closing and reopening the pull request. Lets see if that resulted in correct behavior. If it did then it was a travis bug not a bug in our scripts or setup as we did not change anything.)

**Comment by poeschlr** [comment]
Part of the problem for travis might be that you have based this pull request on a 10 month old state of the official repo.

Always start from the current master to avoid problems.
meaning add this repo as a second remote. Lets call it upstream (as is customary)
`git remote add upstream https://github.com/KiCad/kicad-footprints.git`

from that point on you can do the following:
```
git fetch upstream
git checkout upstream/master
git checkout -b new_branch_name
```

and continue from there.

**Comment by myfreescalewebpage** [comment]
Closing because duplicated

**Pull request closed without merging**
