### PR TITLE
Add Murata MEE isolated DC/DC SIP footprints

### PR DESCRIPTION
**Pull request by chschlue**
Add Murata MEE isolated DC/DC SIP footprints

https://power.murata.com/pub/data/power/ncl/kdc_mee1.pdf
https://power.murata.com/pub/data/power/ncl/kdc_mee3.pdf

Symbols: https://github.com/KiCad/kicad-symbols/pull/1979

Converter_DCDC_Murata_MEE1SxxxxSC_THT
Converter_DCDC_Murata_MEE3SxxxxSC_THT

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
You selected the minimum hole size instead of nominal.
For the MEE3 you selected the maximum distance between leads and body edge instead of nominal (nominal is not explicitly given, but we can assume even tolerance distribution and therefore take the mean of the tolerance range)

**Comment by chschlue** [comment]
Mean tolerance for vertical lead to edge distance adds up to more than max vertical package dimension given; centered pads vertically instead.

**Comment by chschlue** [comment]
mee1dim
mee3dim

**Comment by poeschlr** [comment]
Thanks looks good now

**Pull request merged**
