### PR TITLE
Create WE 750343373

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
WE Flyback Transformer 750343373

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing

https://katalog.we-online.com/ctm/datasheet/750343373.pdf

- [x] An example screenshot image is very helpful 

foot

- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate

https://github.com/KiCad/kicad-symbols/pull/1608

- [x] Check the output of the Travis automated check scripts - fix any errors as required

No error at this moment

- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Can you please beef up the description?
1. The annular rings are a bit small for such large pins. Maybe at least 1mm over the drill size?
1. Missing pin 1 mark on fab and silk layers.
1. I think not mentioning transformers at http://kicad-pcb.org/libraries/klc/ is a mistake. 0.25mm is too small for a part so big in all three dimensions.

**Comment by myfreescalewebpage** [comment]
Hi @evanshultz thanks for the review!
About your points:
1- fixed, added description already used on symbol
2- right, don't known if we have common rules, increased to 1mm over drill size
3- added
4- I agree too, maybe some rules should be added depending of the size of the part
Joel

**Comment by evanshultz** [comment]
1. For a footprint I think the description should be physical characteristics like size. The info there now doesn't necessarily affect anything about the footprint.
2. See https://github.com/KiCad/kicad-footprints/issues/595 for some info. Not cannonized.
3. Looks like this now:
image

I just found one thing and that's all to do before merging: Replace `WE` with `Wuerth`. That's the manufacturer name we used.

**Comment by myfreescalewebpage** [comment]
Renamed :)

**Comment by evanshultz** [comment]
Thanks! Could you adjust the description so it refers to footprint stuff and not electrical info which isn't related to the physical component?

**Comment by myfreescalewebpage** [comment]
Well I do not know what I can write, have you got suggestion ? Is there a common format we have for transformer ?

**Comment by evanshultz** [comment]
Ha! You're full of jokes today! Just teasing. There are no guidelines for transformer footprint descriptions AFAIK. Really, all footprint descriptions are pretty wild and uncontrolled.

Well... how about `Transformer, horizontal core with bobbin, 10 pin, 3.81mm pitch, 15.24mm row spacing, 22x23x17.53mm (<url>)`? Is that descriptive of the footprint (and joined 3D model)? I'm thinking of some transformer footprints I will be submitting and what terms and needed to describe them.

**Comment by myfreescalewebpage** [comment]
Not pad ! I'm confused when this is footprints. Every thing is simple with symbol but not so much clear for me with the footprints :) Modification done.

**Comment by evanshultz** [comment]
Agreed. This is an area that could probably use some rough guidelines to help steer things in a useful direction without getting too detailed and overwrought.

Thanks!

**Pull request merged**
