### PR TITLE
added a few missing CP_Elec Height variations

### PR DESCRIPTION
**Pull request by Shackmeister**
Added some common Capacitor sizes which were lost in the remaking of the footprints. Please note it's only height variations. not pad dimensions.
Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/140
cap_footprints
radial_smd caps

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
@evanshultz could you help me out with this one? :)

**Comment by poeschlr** [comment]
What type of help would you need?

**Comment by Shackmeister** [comment]
a check and possibly a merge :)

**Comment by poeschlr** [comment]
I checked the script changes (the addition of size definitions)
I can not see anything obviously wrong in either that file or the screenshot you provided. So assuming your parts are in the screenshot i would be prepared to merge.

**Comment by Shackmeister** [comment]
All the parts should be in the screenshot, can you have a look at the 3D models as well?

**Comment by poeschlr** [comment]
In that case thanks for your contribution.

**Pull request merged**
