### PR TITLE
Coilcraft LPS5030 shielded power inductor

### PR DESCRIPTION
**Pull request by poeschlr**
Designed in freecad (source file included)

https://www.coilcraft.com/pdfs/lps5030.pdf

screenshot from 2019-01-26 20-19-16
screenshot from 2019-01-26 20-19-12

screenshot from 2019-01-26 19-28-02

---
screenshot from 2019-01-26 19-44-44

### CODE REVIEW

**Comment by evanshultz** [comment]
Looks nice. If you can resolve the branch conflicts I'll merge.

**Comment by poeschlr** [comment]
Oh i based that pull request on top of the wrong commit. Sorry about that. Will fix that later today.

**Comment by poeschlr** [comment]
I recreated the pull request on top of the current master

**Comment by evanshultz** [comment]
OK. Still opens nice in KiCad and looks good. I didn't re-dimension but everything above is correct. Thanks!

**Pull request merged**
