### PR TITLE
Increase hole size to 1.3mm

### PR DESCRIPTION
**Pull request by crazyquark**
This attempt to address https://github.com/KiCad/kicad-footprints/issues/1102

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Please sign the CLA. It is mandatory for all contributions. Thanks!

**Comment by evanshultz** [comment]
@crazyquark 
Please increase the hole size to 1.3mm as shown in the datasheet. And then the pad height needs to go to at least 1.85mm to meet IPC 2221 annular ring size.

**Comment by evanshultz** [comment]
This is actually an old footprint. You can change the entire thing to the below (includes the fixes above):
```
(module SW_PUSH-12mm (layer F.Cu) (tedit 5D160D14)
  (descr "SW PUSH 12mm https://www.e-switch.com/system/asset/product_line/data_sheet/143/TL1100.pdf")
  (tags "tact sw push 12mm")
  (fp_text reference REF** (at 6.08 -4.66) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value SW_PUSH-12mm (at 6.62 9.93) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start 0.25 8.5) (end 12.25 8.5) (layer F.Fab) (width 0.1))
  (fp_line (start 0.25 -3.5) (end 12.25 -3.5) (layer F.Fab) (width 0.1))
  (fp_line (start 12.25 -3.5) (end 12.25 8.5) (layer F.Fab) (width 0.1))
  (fp_text user %R (at 6.35 2.54) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start 0.1 -3.65) (end 12.4 -3.65) (layer F.SilkS) (width 0.12))
  (fp_line (start 12.4 0.93) (end 12.4 4.07) (layer F.SilkS) (width 0.12))
  (fp_line (start 12.4 8.65) (end 0.1 8.65) (layer F.SilkS) (width 0.12))
  (fp_line (start 0.1 -0.93) (end 0.1 -3.65) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.77 -3.75) (end 14.25 -3.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start -1.77 -3.75) (end -1.77 8.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 14.25 8.75) (end 14.25 -3.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 14.25 8.75) (end -1.77 8.75) (layer F.CrtYd) (width 0.05))
  (fp_circle (center 6.35 2.54) (end 10.16 5.08) (layer F.SilkS) (width 0.12))
  (fp_line (start 0.25 -3.5) (end 0.25 8.5) (layer F.Fab) (width 0.1))
  (fp_line (start 0.1 8.65) (end 0.1 5.93) (layer F.SilkS) (width 0.12))
  (fp_line (start 0.1 4.07) (end 0.1 0.93) (layer F.SilkS) (width 0.12))
  (fp_line (start 12.4 5.93) (end 12.4 8.65) (layer F.SilkS) (width 0.12))
  (fp_line (start 12.4 -3.65) (end 12.4 -0.93) (layer F.SilkS) (width 0.12))
  (pad 1 thru_hole oval (at 12.5 0) (size 3.048 1.85) (drill 1.3) (layers *.Cu *.Mask))
  (pad 2 thru_hole oval (at 12.5 5) (size 3.048 1.85) (drill 1.3) (layers *.Cu *.Mask))
  (pad 1 thru_hole oval (at 0 0) (size 3.048 1.85) (drill 1.3) (layers *.Cu *.Mask))
  (pad 2 thru_hole oval (at 0 5) (size 3.048 1.85) (drill 1.3) (layers *.Cu *.Mask))
  (model ${KISYS3DMOD}/Button_Switch_THT.3dshapes/SW_PUSH-12mm.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)
```

**Comment by crazyquark** [comment]
OK, on it.

**Comment by crazyquark** [comment]
Updated with @evanshultz 's version. Not sure why this wasn't already in the repo if it is an old known issue...

**Comment by evanshultz** [comment]
Thanks for fixing this!

**Pull request merged**
