### PR TITLE
Create SOIC-14-16_3.9x9.9mm_P1.27mm.kicad_mod

### PR DESCRIPTION
**Pull request by phamhuuhuyhoang**
Added SOIC-14-16_3.9x9.9mm_P1.27mm.kicad_mod 
image

http://www.ti.com/lit/ds/symlink/ucc256301.pdf
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by aewallin** [comment]
can you add a link to the kicad-footprint-generator PR?

**Comment by phamhuuhuyhoang** [comment]
I did not make a PR in the kicad-footprint-generator. I modified an existing SOIC package in the generator to remove the missing pins.

**Comment by evanshultz** [comment]
Then please remove the reference to the generator in the footprint description. And also post an image of the footprint as requested above. Thank you!

**Comment by poeschlr** [comment]
Why do you then even list the generator script in the description of the pull request.

Also the generator should support removing pins. So i would say this MUST be made with the generator.  (we already have examples that use it)

**Comment by poeschlr** [comment]
Ok i double checked the script and i seem to not yet have the pin removal in the gullwing generator it is only in the no lead generator. Sorry for the confusion.

**Comment by phamhuuhuyhoang** [comment]
I have removed reference to kicad footprint generators and uploaded a picture of the footprint.

**Comment by evanshultz** [comment]
Thank you for uploading an image of the footprint. I don't see a commit pushed to this branch to update the footprint description, though.

**Comment by phamhuuhuyhoang** [comment]
Description updated and committed to branch

**Comment by evanshultz** [comment]
This is all good and I missed your update. Sorry about that. Thank you!

**Pull request merged**
