### PR TITLE
Add Phoenix_PTSM 2 and 5 pin terminal blocks.

### PR DESCRIPTION
**Pull request by jcyrax**
2 terminal blocks from Phoenix PTSM series.
**TerminalBlock_Phoenix_PTSM-0,5-5-2,5-H-SMD_1x05_P2.50mm_Horizontal**
http://www.phoenixcontact.com/us/products/1771059/pdf
image
image
image

**TerminalBlock_Phoenix_PTSM-0,5-2-2,5-H-SMD_1x02_P2.50mm_Horizontal**
http://www.phoenixcontact.com/us/products/1702473/pdf
image
image
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jcyrax** [comment]
It seems module checking script crashed with these parts.

**Comment by poeschlr** [comment]
These would be perfectly suited for the generator script: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Connector/Connector_SMD_single_row_plus_mounting_pad

**Comment by poeschlr** [comment]
You would only need to add the measurements into a yaml file. Look at the other yaml files you find in there to find out what you need to add.

**Comment by Shackmeister** [comment]
@jcyrax are you still planning on trying the script approach? please let me know if I can be helpful

**Comment by jcyrax** [comment]
Yes, but currently I don't have time.

**Comment by jcyrax** [comment]
I don't think I'll have time to do this in foreseeable future.

**Pull request closed without merging**
