### PR TITLE
RF_Module: Fix and improves HOPERF_RFM9XW_SMD footprint

### PR DESCRIPTION
**Pull request by gmsotavio**
Changes F.Fab thickness from 0.12 to 0.1 mm;
Changes F.Silk thickness from 0.10 to 0.12 mm;
Improves F.Silk drawing, including pin 1 indication;
Fixes F.CrtYd clearance to 0.25mm;

**Before**
screenshot_2018-12-24_15-44-28

**After**
screenshot_2018-12-24_15-43-44

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
add pin1 indication on f.fab with a bevel?

**Comment by gmsotavio** [comment]
> add pin1 indication on f.fab with a bevel?

No, I've added pin 1 indication with a bevel in F.Silk layer, not F.Fab.

**Comment by aewallin** [comment]
See F5.2
http://kicad-pcb.org/libraries/klc/F5.2/

**Comment by gmsotavio** [comment]
> See F5.2
> http://kicad-pcb.org/libraries/klc/F5.2/

I was mislead by another modules in library. Several footprints in RF_Modules library do not includes a bevel on F.Fab, just on F.Silk. Some not even in silk. I will fix. Thanks!!

**Comment by gmsotavio** [comment]
@aewallin 

Please, give me your opinion. Which is better?
This
screenshot_2018-12-25_10-46-03

or this?
screenshot_2018-12-25_10-46-24

The bevel not looks like uniform across entire library.

**Comment by aewallin** [comment]
The lower picture, with the cut-off corner, is the way to go. Suggested size is 1mm (or 25% of size for really small footprints).
The upper arrow-style might be useful when pin1 is somewhere in the middle of the pin-row.

**Comment by gmsotavio** [comment]
Committed! Thanks for guidance.

**Comment by aewallin** [comment]
- geometry looks OK to me
- I get 404 on the datasheet link (but other links for the same PDF exist..)
- the datasheet promises a suggested land-pattern, but I can't find one in the datasheet
- to be checked before merging by a Librarian.
rf_review

**Comment by gmsotavio** [comment]
> I get 404 on the datasheet link (but other links for the same PDF exist..)

I've fixed one nanosecond before your comment.

screenshot_2018-12-25_16-31-34


>the datasheet promises a suggested land-pattern, but I can't find one in the datasheet

I've not found too. But I have the real component and I've tested by my self. I can say that the original author of this footprint did a good job.

**Comment by poeschlr** [comment]
The changes to the footprint look good. There is no change to the pads so no need to check them again.

**Pull request merged**
