### PR TITLE
QFN-56-1EP_8x8mm_P0.5mm

### PR DESCRIPTION
**Pull request by calebns**
QFN-56 8x8mm 0.5mm pitch, required for CY7C6813A

http://www.ti.com/lit/an/scea032/scea032.pdf

image

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you include the size of the exposed pad in the footprint name as a suffix?
So the name should be `QFN-56-1EP_8x8mm_P0.5_EP5.6x5.6mm`

**Comment by calebns** [comment]
Fixed

**Comment by semihalf-macek-wojciech** [comment]
Thanks. The datasheet should be different
http://www.cypress.com/file/138911/download

Modified the footprint to match QFN standard for landing pads (TI doc), but with a smaller EP (as required by Cypress)

Now, it has:
EP: 4.5x5.2
Landing pad size: 0.28x0.69
Paste coverage: 67%

image

**Comment by poeschlr** [comment]
Thanks.

**Pull request merged**
