### PR TITLE
add LFCSP-8-1EP_3x3mm_P0.5mm_EP1.6x2.34mm

### PR DESCRIPTION
**Pull request by hvraven**
This adds a LFCSP footprint used by Analog. [Datasheet](https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/CP_8_11.pdf). Generated using the footprint generator, PR here: https://github.com/pointhi/kicad-footprint-generator/pull/433
Screenshot_20190925_143811

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by chschlue** [comment]
@evanshultz assigned you because you're already assigned to the script PR

**Comment by chschlue** [comment]
@lorem-ipsum would you push an update?

**Comment by chschlue** [comment]
@hvraven ping

**Comment by hvraven** [comment]
Hi @chschlue ,

sorry for the long time off, did the regeneration now.

Cheers,
Hendrik

**Comment by myfreescalewebpage** [comment]
@hvraven I have made a review of the PR, looks great, merging.
Joel

**Pull request merged**
