### PR TITLE
Add DirectFET SC

### PR DESCRIPTION
**Pull request by chschlue**
Add DirectFET SC

https://www.infineon.com/dgdl/Infineon-AN-1035-ApplicationNotes-v29_01-EN.pdf?fileId=5546d462533600a40153559159020f76#page=24

DirectFET_SC

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Is it just me or is the vertical location of the S pads not shown? From https://www.infineon.com/dgdl/auirl7732s2.pdf?fileId=5546d462533600a4015355baca60154a we can see that it is 1.05mm, but it appears AN-1035 missed this dimension. I'll let Infineon know.
1. Same issue with body and courtyard height. (Courtyard width is fine.)

image

**Comment by chschlue** [comment]
You're right.
I think I didn't even notice and just assumed an equal distance from center.

**Comment by chschlue** [comment]
@evanshultz ping

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
