### PR TITLE
Converter_DCDC_TRACO_TDN_5-xxxxWISM_SMD adjusted pad sizes to IPC-735…

### PR DESCRIPTION
**Pull request by chmorgan**
…1 standard using library expert pro, changed pads to have no rotation

*Replace this line with your commit message! Please provide a description of your pull request*

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chmorgan** [comment]
image

**Comment by chmorgan** [comment]
@chschlue damnit, sorry man. Pushed fixes for that.

**Comment by chmorgan** [comment]
@chschlue is this ok? I moved the pin 1 indicator for fab inside of the outline to avoid having to expand the courtyard.

image

**Comment by chmorgan** [comment]
@chschlue I think the courtyard makes sense, I missed the top line that was 0.05mm too close.

Update image with bevel and pushing updates. I kept the outer marking on the silk to ensure it would be visible when the part was placed, per KLC (and what I'd like to see when assembling a board).

image

**Comment by chmorgan** [comment]
@chschlue is the idea that the courtyard should be exactly 0.25mm away? I'm using an 0.05mm grid here, should I be using a smaller grid or assigning by value to get a precise value?

**Comment by chmorgan** [comment]
@chschlue also, I'm seeing 0.25mm from the pad to courtyard on the top and bottom, not 0.275mm.

Switched to an 0.1mm grid and using the measurement tool (rather than the zero origin approach). Only had to move the right and left lines, the top and bottom were exactly at 0.25mm from the pads and the left and right are 0.25mm from the fab lines.

**Comment by chschlue** [comment]
CrtYd should be as accurate as possible while still fitting a 0.01mm grid.
This means in x direction ±4.8mm is right on target while in y direction ±8.12 or ±8.13mm is as good as it gets.

**Comment by chmorgan** [comment]
@chschlue are you measuring from the center of lines or the edges of lines? I'm using the edges but if I use the center I get measurements closer to yours.

**Comment by chschlue** [comment]
See https://github.com/KiCad/kicad-footprints/pull/2138#pullrequestreview-374737944

**Comment by chmorgan** [comment]
@chschlue k, let me update and repush, that explains the differences I was seeing.

**Comment by chmorgan** [comment]
@chschlue alright, that *should* do it

**Comment by chschlue** [comment]
Done.

One more thing:
3slyk9
:)

**Comment by chmorgan** [comment]
Hah. Seriously though it’s ok to force push so we don’t have dozens of fix commits to squash?

**Comment by chschlue** [comment]
The problem with force-pushing during review iterations is that it makes it unnecessarily hard for the reviewer to track the actual changes.
Example: If I tell you that courtyard is off by 0.1mm and you add a commit fixing that, I can immediately see that you moved those lines and those lines only.

Squashing all those commits afterwards is just a single click in GH's web UI.

**Comment by chmorgan** [comment]
@chschlue k, I'll avoid in the future

**Pull request merged**
