### PR TITLE
Common mode chokes Coilcraft

### PR DESCRIPTION
**Pull request by rleh**
* Common mode choke Coilcraft 0603USB
* Common mode choke Coilcraft 0805USB
* Common mode choke Coilcraft 1812CAN

---

* Datasheets
  * https://www.coilcraft.com/pdfs/0603usb.pdf
  * https://www.coilcraft.com/pdfs/0805usb.pdf
  * https://www.coilcraft.com/pdfs/1812can.pdf
* No matching symbol or 3D model available
* Script check passes 🙂
* Naming scheme `L_CommonModeChoke_*` according to #1645

## Coilcraft 0603USB
grafik
grafik

## Coilcraft 0805USB
grafik
grafik

## Coilcraft 1812CAN
grafik
grafik

### CODE REVIEW

**Comment by rleh** [comment]
I screwed up to pin numbering on the 0805USB choke. Now fixed.

**Comment by rleh** [comment]
Is it okay to have these three similar common mode chokes in a single pull request? If necessary, I can split this into three different pull requests.

**Comment by chschlue** [comment]
That's fine.

**Comment by rleh** [comment]
Silkscreen clearance (for 0603USB and 0805USB) is only 120µm (= silkscreen line width), according to [KLC F5.1 §3 b](https://kicad-pcb.org/libraries/klc/F5.1/). Is that okay for the small components?

The 1812CAN footprint has 200µm silkscreen-to-exposed-copper clearance.

**Comment by chschlue** [comment]
It's allowable, but is it necessary?
If you want to keep silk inside courtyard, how about decreasing line width to 100µm while increasing clearance to 150µm?

**Comment by rleh** [comment]
That's a good idea, I'll change it immediately.

**Comment by rleh** [comment]
The CI now complains about `Courtyard lines are not on 0.01mm grid`.

**Comment by rleh** [comment]
Should i move the courtyard to the 10µm grid to conform to [F5.3 §2](https://kicad-pcb.org/libraries/klc/F5.3/), but violate [F5.3 §5](https://kicad-pcb.org/libraries/klc/F5.3/)?

**Comment by chschlue** [comment]
Oops. Missed 1812 courtyard before.

Yes, stick to the grid, rounding up or down.
But CrtYd is 0.305mm from Fab instead of 0.255mm. Please fix.

**Comment by rleh** [comment]
Courtyard is now fixed.
I accidentally measured from the edge of the Fab line, hence the 305µm.
grafik
grafik

**Comment by rleh** [comment]
Thanks again for reviewing! 😊

**Pull request merged**
