### PR TITLE
Fix EP round radius for xQFN footprints

### PR DESCRIPTION
**Pull request by poeschlr**
Splitting #1821 into smaller bits. This one handles xQFN footprints with the new EP radius.
Script: pointhi/kicad-footprint-generator#422
Issue: #1798

### CODE REVIEW

**Comment by evanshultz** [comment]
I reviewed all footprints.

The following had minor copper changes but I'm OK to merge:
- UQFN-10_1.3x1.8mm_P0.4mm
- UQFN-10_1.6x2.1mm_P0.5mm
- UQFN-48-1EP_6x6mm_P0.4mm_EP4.62x4.62mm

WQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm_ThermalVias had pads widened from 0.25mm to 0.3mm. The non-via footprint was already 0.3mm. Not sure why but I'm OK with this as well.

There are some TI footprints that don't match the doc (rounded corners shown, no special mask cutout, etc.). There may be others. Do you have a plan for them? I guess you could partition them into a unique YAML file and handle them separately?
- VQFN-16-1EP_3x3mm_P0.5mm_EP1.45x1.45mm
- VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm
- VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm
- VQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm
- VQFN-28-1EP_4x5mm_P0.5mm_EP2.55x3.55mm
- WQFN-16-1EP_4x4mm_P0.5mm_EP2.6x2.6mm
- WQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm
- WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm

**Comment by poeschlr** [comment]
I do not think we should use too specific footprints for such generic packages. More detail in my response on the script.

Regarding pad width. My guess is that there was a mistake when it was originally added. Maybe a mistake in the original yaml entry and after fixing that the thermal via version was forgotten to be updated.

**Comment by evanshultz** [comment]
OK. I'm on board with going more generic:
- VQFN-16-1EP_3x3mm_P0.5mm_EP1.45x1.45mm: IPC-7351 isn't suggested but it's shown as JEDEC MO-220 (appears to be `MO-220VEED-6`)
- VQFN-16-1EP_3x3mm_P0.5mm_EP1.68x1.68mm: No IPC or package reference
- VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm: No IPC or package reference
- VQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm: No IPC or package reference
- VQFN-28-1EP_4x5mm_P0.5mm_EP2.55x3.55mm: No IPC or package reference, and should link to datasheet page 40
- WQFN-16-1EP_4x4mm_P0.5mm_EP2.6x2.6mm: No IPC or package reference
- WQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm: No IPC or package reference
- WQFN-24-1EP_4x4mm_P0.5mm_EP2.6x2.6mm: No IPC or package reference

Based on your answer, if you can update the datasheet URL for the footprint I noted above I'll merge this.

**Comment by poeschlr** [comment]
With generic i mean we still use the ti datasheet for the package size source but do not necessarily make the name TI specific (after all we ignore the suggested footprint with our generators anyway)

Similar to how we do it with all other manufacturers. (I am not sure why we started down the road of having so many TI specific footprints. Possibly because TI has such good documentation and it was tempting to use TI in preference to other compatible parts)

**Comment by evanshultz** [comment]
@poeschlr 
Understood. I'm only asking for you to update the JEDEC reference for the one footprint I noted above and I'll merge.

**Comment by poeschlr** [comment]
Done

**Comment by evanshultz** [comment]
Thanks!

**Pull request merged**
