### PR TITLE
Fixed coin cell holder negative contact size, removed from paste layer

### LINKED ISSUE #1896: BatteryHolder_Keystone_3034 does not make contact
I've manufactured some board with that footprint, but the contact with the battery fails, probably because of the soldermask thickness. 

Should i make a PR with a larger pad, as i made in #1622?

### PR DESCRIPTION
**Pull request by 5N44P**
Fixes #1896, see the issue for the discussion

All the changed dimensions are from linx parts documentation ([12mm][1], [20mm][2]), except the one for 24mm cells, which is an estimate based on IEC 60086, since there are no datasheets with reasonable (and not **minimum**) size specified.

Screenshots:
image
image
image
image
image
image
image

[1]: https://linxtechnologies.com/wp/wp-content/uploads/bat-hld-012-smt.pdf
[2]: https://www.mouser.it/datasheet/2/238/bat-hld-001-1659379.pdf
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by 5N44P** [comment]
I'm not sure about what to do with the silkscreen on the keystone 3034. Should i break the line where the contact starts or make it go around the battery profile?

All the other travis errors are from courtyard problems already committed, can we merge this without the due fixes for now?

**Comment by chschlue** [comment]
It's not required to fix all pre-existing errors.

Personally, I would break the line.
You may go around if you like, you just cannot cross copper.

**Comment by 5N44P** [comment]
Should be ready to merge now

**Comment by chschlue** [comment]
- [x] Keystone 3000

**Pull request merged**
