### PR TITLE
Add Texas WSON-6 package.

### PR DESCRIPTION
**Pull request by Misaka0x2730**
This footprint used for TPS61041DRV.

TPS61041DRV - http://www.ti.com/lit/ds/symlink/tps61040.pdf sheet 36.

wson-6

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
- f.fab bevel could be 25% of width for this small part (not 1mm as it looks like now)
- courtyard around pads, with 0.25mm clearance, not around silk.

**Comment by poeschlr** [comment]
This might be better scripted. As i am working on the script responsible right now i would suggest to take this over. Any objections?

**Comment by myfreescalewebpage** [comment]
@poeschlr no objections for me.

Cheers
Joel

**Comment by poeschlr** [comment]
replaced with https://github.com/KiCad/kicad-footprints/pull/1266

**Pull request closed without merging**
