### PR TITLE
Added variant of DFN-8 3x3mm

### PR DESCRIPTION
**Pull request by SchrodingersGat**
* Datasheet - http://www.ixysic.com/home/pdfs.nsf/www/IX4426-27-28.pdf/$file/IX4426-27-28.pdf
* Used round-rect pads

image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
This PR adds two variations on the DFN-8 3x3mm 0.65mm pitch footprints, for use by some symbols as posted to https://github.com/KiCad/kicad-symbols/pull/828

**Comment by evanshultz** [comment]
@SchrodingersGat 
I see two more symbol PRs from you, and they are missing footprints. Considering your capabilities, would you make script-generated footprints as the first step to merging your symbols?

**Comment by poeschlr** [comment]
Looked at this more closely as well. Why does this contain two versions with differently sized exposed pad? (The datasheet contains only one. None of the two given fits the datasheet dimensions.)

From the datasheet i would use the generator parameters:
``` yaml
DFN-8-1EP_3x3mm_P0.65mm_EP1.7x2.05mm:
  device_type: 'DFN'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://www.ixysic.com/home/pdfs.nsf/www/IX4426-27-28.pdf/$file/IX4426-27-28.pdf'
  # ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  body_size_x:
    nominal: 3
    tolerance: 0
  body_size_y:
    nominal: 3
    tolerance: 0
  lead_width:
    nominal: 0.3
    tolerance: 0.05
  lead_len:
    nominal: 0.4
    tolerance: 0.05

  EP_size_x: 1.7
  EP_size_y: 2.05
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [2, 2]
  # heel_reduction: 0.1 #for relatively large EP pads (increase clearance)

  pitch: 0.65
  num_pins_x: 0
  num_pins_y: 4
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_PullBack'
  #include_suffix_in_3dpath: 'False'
  #include_pad_size: 'fp_name_only' # 'both' | 'none' (default)
```

The footprint generated by these parameters can be found in https://github.com/KiCad/kicad-footprints/pull/865

**Comment by evanshultz** [comment]
@SchrodingersGat 
If you confirm Rene's footprint, you can close this PR (and optionally merge his). If the symbol matches the merged footprint I'll merge the symbol then.

**Pull request closed without merging**
