### PR TITLE
Fix IRM-03 THT footprint

### PR DESCRIPTION
**Pull request by evanshultz**
Fixes https://github.com/KiCad/kicad-footprints/issues/1320.

Essentially a do-over. See the issues noted above:
1. Flipped due to the drawing being a bottom view and the footprint didn't take that into account.
1. Rotated to put pin 1 at top left(-ish).
1. Correct the 17.78mm dimension (was 17.18mm).
1. Corrected description.

https://www.meanwell.com/Upload/PDF/IRM-03/IRM-03-SPEC.PDF

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Looks good, thanks

**Comment by BrettMerrick** [comment]
Any possibility someone can correct the 3D model for this to match? Happy to have a go myself if someone could point me in the right direction.

**Comment by antoniovazquezblanco** [comment]
Those are script generated I believe. Have a look at:

https://github.com/easyw/kicad-3d-models-in-freecad/blob/81573d70b4d41b6726806f908164b05a8835fc81/cadquery/FCAD_script_generator/Converter_ACDC/cq_parameters.py#L134

Thanks!

**Comment by BrettMerrick** [comment]
Thanks,

Is a pull request against that repo sufficient, or will I need to install and run those and generate a request against KiCad/kicad-packages3D?

**Comment by poeschlr** [comment]
You would need to make a pull request on both the script repo and on the pacakges3d one. Link from either of the pull requests to the other.

**Comment by BrettMerrick** [comment]
OK, so there is no existing workflow?
Will I need to now run those scripts to generate the new model for use in another pull request here?

**Pull request merged**
