### PR TITLE
Amphenol RJ12

### PR DESCRIPTION
**Pull request by openelectron**
Added connector AMPHENOL Modular Jack - 54601

Datasheet:
https://cdn.amphenol-icc.com/media/wysiwyg/files/drawing/c-bmj-0082.pdf

screenshot_2018-02-06_12-50-40
*Replace this line with your commit message! Please provide a description of your pull request*

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by openelectron** [comment]
partially fixes issue #301 but did not remove the old footprint

**Comment by Ratfink** [comment]
Thanks for the contribution!  I have a few notes, though.

* It looks like pins 2, 4, and 6 are in the wrong positions.  The datasheet shows them evenly staggered between pins 1, 3, and 5, but you've got them shifted to the right a bit.
* The proper courtyard clearance for connectors is 0.5 mm, not 0.25 mm.
* This isn't an especially high-density part, so a silkscreen line width of 0.1 mm is a bit thin.  0.12 mm is the standard value.
* Though not required by KLC for through-hole parts, moving the silkscreen outline to be just outside of the part's shape would improve visibility.

Also, I notice there's a second footprint in here that you didn't mention in the first post.  A datasheet link and screenshot for that part would help in reviewing it.

**Comment by openelectron** [comment]
@Ratfink, I have made the changes you requested, except the last one. When the connector is fitted in the board the silkscreen is visible already.

**Comment by Ratfink** [comment]
Thanks for making these changes!

* Please include the datasheet link at the end of the footprint description.
* You left the lower vertical silkscreen lines at 0.10 mm thickness, please change them to 0.12 mm as well.
* Please move the value field down a bit more so it's completely outside of the body outline.

**Comment by openelectron** [comment]
@Ratfink I wasn't clear where you wanted the datasheet link. I think its in the right place...

everything else done as requested.

**Comment by Ratfink** [comment]
Looks good, and yep, that's the right place for the datasheet link.

Sorry, but I edited the comment above with two more changes, which it looks like you didn't see before you pushed what you did.  If you could address those points, I think this will be ready to merge.

**Comment by openelectron** [comment]
@Ratfink I think that is it..

**Comment by openelectron** [comment]
@Ratfink  Now I see what you mean (I think) ....

**Comment by Ratfink** [comment]
Thanks for the contribution!

**Pull request merged**
