### PR TITLE
Varistor: Add a new models

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
# RV_Disc_D9mm_W6.1mm_P5mm.kicad_mod

https://katalog.we-online.de/pbs/datasheet/820572711.pdf

imagen

# RV_Disc_D16.5mm_W6.7mm_P7.5mm.kicad_mod

https://katalog.we-online.de/pbs/datasheet/820542711.pdf

imagen

I will bre creating a 3D PR soon

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
The silk outline should be outside for both of them (right now the smaller one has it on top of fab)
The outline of the smaller one has a width of 6mm instead of 6.1 as indicated by the name.

**Comment by antoniovazquezblanco** [comment]
Solved. Thanks!

**Comment by poeschlr** [comment]
thanks

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
