### PR TITLE
Connector_Hirose: Add DF11 series

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Datasheet: https://www.hirose.com/product/document?clcode=CL0543-0517-5-08&productname=DF11-4DP-2DSA(08)&series=DF11&documenttype=2DDrawing&lang=en&documentid=0000986679

Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/392

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by herostrat** [comment]
Hey antonio,

I checked the dimensions and could not find any error there.

Why did you name the footprints not according to the datasheets table?
There they use the total pins as the number before the DP, you used the number of colons.

**Comment by antoniovazquezblanco** [comment]
Sorry, I missed that one. Now corrected. Thanks!

**Comment by herostrat** [comment]
Awesome, than I do not see any more problems.
Should I merge or do you think we should wait for another feedback?

**Comment by evanshultz** [comment]
Hang on please. I'm making comments on the script.

@herostrat 
How did you check dimensions? And on the footprints or the script?

**Comment by herostrat** [comment]
Understood.
What would be the best order, first script checks, than footprint merge, than script merge?

I checked on the footprint, I measured the dimensions for two in FreeCAD and crosschecked with KiCads internal ruler tool.

**Comment by evanshultz** [comment]
A couple of my script comments will affect the footprints. Since this is often the case, I review the script first. The order you mentioned works for me and has seemed to be successful.

After checking the script, I usually just do FreeCAD unless KSU can't import some elements and I then need to use KiCad. I also post the dimensioned drawing so that any issues, or verification of correctness, are clear. After taking the time to review pasting a screenshot is usually minimal extra effort.

**Comment by antoniovazquezblanco** [comment]
Fixed scripts and updated fps

**Comment by antoniovazquezblanco** [comment]
Fixes https://github.com/KiCad/kicad-footprints/issues/1663

**Comment by evanshultz** [comment]
There is no 2 pin version. The minimum number of pins is 4. Did I misunderstand, or is there a connector that shouldn't belong here (if so please update the script).

**Comment by antoniovazquezblanco** [comment]
> There is no 2 pin version. The minimum number of pins is 4. Did I misunderstand, or is there a connector that shouldn't belong here (if so please update the script).

In DF11 series there is a 4 pin connector (2 pins per row) `DF11-4D...`. Or are what footprint are you talking about? Thanks

**Comment by evanshultz** [comment]
I thought I saw a `DF11-2DP` in one commit. Maybe I lost my mind. Sorry.

Changes that I note, with questions in italic:
- FH12: Corrected vendor name and updated orientation keyword
- DF11: @herostrat checked it out above and the script was reviewed as well
- DF12: Updated orientation keyword
- DF13: Corrected vendor name and updated orientation keyword. _Some had added silk lines, like `Hirose_DF13-03P-1.25DS_1x03_P1.25mm_Horizontal`. What's up with that? Also in the same footprint, should a 0.9x1.4mm pad have a roundrect_ratio of 0.25? The criteria of 25% the side up to 0.25mm max would seem to indicate to me that roundrect_ratio should be only 0.225. What am I missing?_
- DF13C: Corrected vendor name and updated orientation keyword
- DF63: Removed `_Horizontal` footprints that are actually vertical (new footprints are already present).

Can you check out the DF13 questions above?

And because of the last item, I'd like to get a sign-off from Rene when he gets back. Just to be safe.

**Comment by antoniovazquezblanco** [comment]
> Some had added silk lines, like Hirose_DF13-03P-1.25DS_1x03_P1.25mm_Horizontal. What's up with that?

There are no added silk lines. Only removed. There were overlapping silk lines and I removed those. There was a particular case for the 2 pin version that required an "if-else" block added.

> Also in the same footprint, should a 0.9x1.4mm pad have a roundrect_ratio of 0.25? The criteria of 25% the side up to 0.25mm max would seem to indicate to me that roundrect_ratio should be only 0.225. What am I missing?

imagen

imagen

I have not changed anything regarding that in the script. I don't know why in that specific model the diff tool has highlighted line changes.

http://kicad-pcb.org/libraries/klc/F7.3/

Should I change anything?

> And because of the last item, I'd like to get a sign-off from Rene when he gets back. Just to be safe.

https://github.com/KiCad/kicad-footprints/issues/1663#issuecomment-510801145

> I would still require good reason to do so as to keep the library from being too volatile. (Something like this is a clear case where the name change can be easily explained.)


Thanks

**Comment by evanshultz** [comment]
Ah. I meant deleted, not added. Sorry. Everything still looks fine after viewing this branch so it seems OK.

My brain was thinking about the round rect pads backwards. It's good.

Let's do it!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
