### PR TITLE
Add 2 mm and 2.1 mm mounting holes

### PR DESCRIPTION
**Pull request by diegoherranz**
Modified from other existing mounting holes.
Thanks.

--------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Which screws would fit these mounting holes?

**Comment by poeschlr** [comment]
I was mainly confused as i thought you might have intended these to be used for M2 screws.

**Comment by poeschlr** [comment]
Thanks for your contribution and sorry it took so long.

**Comment by diegoherranz** [comment]
Not a problem. The important thing is that it eventually gets merged.
Thanks again to the good work by the librarians.

**Pull request merged**
