### PR TITLE
add Onion Omega2+ footprint

### PR DESCRIPTION
**Pull request by balcer**
https://raw.githubusercontent.com/OnionIoT/technical-drawings/master/Mechanical/OM-O2.PDF

omega footprint

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@balcer, you have several travis errors to be corrected. For the 3D model, you should provide the URL even if it does not exist (have a look to some Arduino module in the lib for an example). The travis error F9.3 will remain anyway but it is not a problem.

Thanks,
Joel

**Comment by balcer** [comment]
@myfreescalewebpage Sorry I was on holidays. Footprint ready for the first review. All fix from now on I will make without --force option.

**Comment by balcer** [comment]
Hi, @myfreescalewebpage I made changes according to your suggestions. I additionally added some mechanical features according to the datasheet. I think that I should also add keepout area for sd card but Dwgs.User and Cmts.User layers are not available during footprint design.

**Comment by myfreescalewebpage** [comment]
@balcer, thanks for the modifications. Regarding to the CrtYd layer, you have not read correctly my comment, the 0.25mm clearance is between the CrtYd and Fab layers. You have set 0.25mm between Silkcreen and CrtYd layers... Agreed with you regarding to the SD card, but maybe in the future due to impossibility to add it actually. Your design with internal drawing of the module is great !! :)

**Comment by myfreescalewebpage** [comment]
@balcer thanks, looks great now ! Merging.

**Pull request merged**
