### PR TITLE
Add _RoundHole to name (now _CircularHoles)

### PR DESCRIPTION
**Pull request by robkam**
regular footprint Jack_3.5mm_QingPu_WQP-PJ398SM_Vertical.kicad_mod with oval holes to follow

### CODE REVIEW

**Comment by poeschlr** [comment]
We use the suffix CircularHoles in other such footprints

**Comment by poeschlr** [comment]
The 3d model should still point at the non circular hole variant (yes travis will complain but it is just too much work to teach travis that it is ok that way)

**Comment by poeschlr** [comment]
thanks

**Comment by Ratfink** [comment]
@poeschlr It isn't too much work; in fact there's an open PR that does it: https://github.com/KiCad/kicad-library-utils/pull/247

**Pull request merged**
