### PR TITLE
Added SOD-923 footprint

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.onsemi.com/pub/Collateral/ESD9B-D.PDF

imagen

imagen

### CODE REVIEW

**Comment by cnieves1** [comment]
3D depends on PR: https://github.com/easyw/kicad-3d-models-in-freecad/pull/326

**Comment by chschlue** [comment]
sod-923

Please fix top and bottom courtyard.

**Comment by cnieves1** [comment]
Done 
imagen

**Comment by chschlue** [comment]
sod-923
- [ ] Courtyard clearance must take pads into account
- [ ] Silkscreen clearance must be at least line width

**Comment by cnieves1** [comment]
Hope it is fixed now.
Captura de pantalla de 2019-12-27 09-46-18

**Comment by chschlue** [comment]
Thanks

**Pull request merged**
