### PR TITLE
Panasonic ALFG series relay

### PR DESCRIPTION
**Pull request by aracosta1**
Footprint for Panasonic relais series ALFG
Datasheet at [Panasonic](https://www3.panasonic.biz/ac/e_download/control/relay/power/catalog/mech_eng_lfg.pdf)

image

---

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @aracosta1 , i noticed that you didn't use round pads and drill holes, i am wondering if this is acceptable since datasheet gives holes' dia.

εικόνα

**Comment by aracosta1** [comment]
Hi @aris-kimi,
I choose to make slotted holes because the ratio of the pin dimension is 2 or bigger, 1.6x0.8 for pin 3 & 4 and 1.6x0.3 for pin 1 & 2.
I propose to add a round hole version of the footprint with `_CircularHoles` suffix.

**Comment by cpresser** [comment]
It is okay to use slotted holes here. The `_CircularHoles` variant will be a nice addition.

@aris-kimi I just did assign you to this PR. If you would rather have me review the PR just change the assigned person.

**Comment by myfreescalewebpage** [comment]
@aris-kimi ping, are you able to review this PR following comment of @cpresser  ?

**Comment by aris-kimi** [comment]
Yes @myfreescalewebpage , i will start this today, but later when i finish work.

**Comment by myfreescalewebpage** [comment]
No problem

**Comment by aris-kimi** [comment]
Hi @aracosta1 , sorry for the delay. 
I do have those comments about this footprint.

- [ ] fab layer line width must be 0.1mm

- [ ] fab layer should have 1mm bevel to indicate pin1 position

- [ ] pin 3 & 4 drill holes can be reduced to 2mm & 1mm

- [ ] pin 1 & 2 drill holes can be reduced to 2mm & ~0.5mm~

- [ ] fab layer dimensions are 0.3mm bigger than ds (, and i am not totaly sure about tolerances described)

- [ ] courtyard clearance from fab layer must be 0.25mm

- [ ] I think silkscreen can be placed between courtyard and fab layer, meanning silk clearance from fab layer 0.1mm-0.2mm

@myfreescalewebpage , i want some assistance with footprint name. I think it is ok, but i need confirmation.

**Comment by myfreescalewebpage** [comment]
According to me the footprint name is great

**Comment by aracosta1** [comment]
> Hi @aracosta1 , sorry for the delay.
> I do have those comments about this footprint.
> 
> * [ ]  pin 3 & 4 drill holes can be reduced to 2mm & 1mm
> * [ ]  pin 1 & 2 drill holes can be reduced to 2mm & ~0.5mm~

for these pin I used the calculation from KLC F7.7, 
y = 0,8 + 0,2 = 1.0mm
x >= 1.6 + y = 2.6 mm
 if you feel it's too big I can chage to smaller measures as suggested.

For the other point I will correct them. 
I'm going to add also the _CircularHole version. Should I add to the PR or open another one ?

**Comment by aris-kimi** [comment]
Thank you for your reply. You can add it here yes.

I think it is too big but i missed that KLC rule, so you are correct we should keep it as it is.

**Comment by aracosta1** [comment]
> Hi @aracosta1 , sorry for the delay.
> I do have those comments about this footprint.
> 
> * [ ]  fab layer dimensions are 0.3mm bigger than ds (, and i am not totaly sure about tolerances described)

From ds I read tolerances as 0.1mm for items up to 1mm, 0.2mm for measures up to 3mm and 0.3mm for measures over 3mm.
So I added 0.3mm to fab layer to have room for worst case tolerances.

**Comment by aris-kimi** [comment]
You still need to add that 1mm bevel at fab layer something like this image:
εικόνα

**Comment by myfreescalewebpage** [comment]
@aracosta1 any news here ?

**Comment by aracosta1** [comment]
> @aracosta1 any news here ?

I’ll work on it on the weekend

**Pull request closed without merging**
