### PR TITLE
Add Hirose df12c_ds and df12e_df

### PR DESCRIPTION
**Pull request by jneiva08**
All the connectors were made by [script](https://github.com/pointhi/kicad-footprint-generator/pull/175)

datasheet: https://www.hirose.com/product/en/download_file/key_name/DF12C%283.0%29%2D50DS%2D0.5V%2881%29/category/Drawing%20(2D)/doc_file_id/38626/
The pin numeration wasn't written on datasheet.

Screenshot of all connectors:
df12c_ds

Dimension of two:
df12c-30ds

df12c-50ds

Please let me know if is need more modifications.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
1. The part naming scheme is a bit off - e.g. the 30 pin connector:

```Hirose_DF12_DF12C3.0-30DS-0.5V_2x30_P0.50mm_Vertical``

Should have the row numbering as ```2x15```

2. Please move the second RefDes (on F.Fab) to (0, 0)

Looks good against a sample 3D model:

image

**Comment by jneiva08** [comment]
I think it will need a litle more work on F.SilkS/F.Fab to easy to separate df12c_ds from df12e_dp (it will be in new PR)
Need to fix F.Paste it's wrong

**Comment by SchrodingersGat** [comment]
@jneiva08 ok LMK when you're happy :)

**Comment by poeschlr** [comment]
@jneiva08 What is the state of this?

**Comment by jneiva08** [comment]
@poeschlr @SchrodingersGat Sorry for taking a long time to update this PR.

Have fixed the naming issue, the F.SilkS was too close of pad, and removed "F.Cu" on F.Paste Pad.
The dimensions didn't changed.

Have created another script do make footprint of DF12E, with all earlier fix.

The DF12C is supposed to go in the bottom, and the DF12E is to be in the top.
When created the footprint scripts did have in attention of that, when flip DF12C it match pin 1 of DF12E.

The only strange thing is %R is not in the center. Exits some way to force to be in the center?

footprint

3d_sem

3d

**Comment by poeschlr** [comment]
It seems like your original datasheet is no longer valid. The new one is found here: https://www.hirose.com/product/document?clcode=CL0537-0694-9-81&productname=DF12C(3.0)-50DS-0.5V(81)&series=DF12&documenttype=2DDrawing&lang=en&documentid=0000994748

It uses a different dimensioning scheme compared to the one you show above so i worry that they might have changed some things. (They dimension the inside to inside distance for pads not the outside to outside one as you do.)

**Comment by jneiva08** [comment]
All sizes are the same, except in DF12E that I was made mistake in the measure

**Comment by poeschlr** [comment]
Thanks for your contribution

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
