### PR TITLE
Add SHT1x - temperature/humidity sensor

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Datasheet: https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Humidity/Sensirion_Humidity_Sensors_SHT1x_Datasheet.pdf

sht1x

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by manio** [comment]
Hey Piotrek,
Masz błąd z Travis-a, popraw sobie bo zapomniałeś dodać do fp-lib-table:
https://gist.github.com/manio/e709f86623a2b9a533bad1c8ab2e4d5a
Pozdro! :)

**Comment by piotr-wiszowaty** [comment]
Już.

**Comment by poeschlr** [comment]
The silkscreen is a bit far away from the part. Move it closer in to better help guide manual assembly.

Move the text regarding keepout inside the keepout area. (Reduce the text size accourdingly)
Make sure the word Keepout is in the text. Maybe 2 lines: Keepout; No Copper

A few measurements are not quite right. Courtyard does not take keepout into account.

screenshot from 2019-01-19 11-29-06

**Comment by piotr-wiszowaty** [comment]
Yes, the F.Fab width (4.94) is based on a guess that the circle is in the middle of the component horizontal-wise.

**Comment by poeschlr** [comment]
The courtyard clearance in y direction is still not quite right:

screenshot from 2019-01-20 22-07-48

**Comment by poeschlr** [comment]
Looks good, thanks

**Comment by diegoherranz** [comment]
Will anyone update the symbol so it uses this footprint by default? @piotr-wiszowaty?
https://github.com/KiCad/kicad-symbols/blob/master/Sensor.lib#L220

By the way, the footprint is within the "sensor_temperature" category, but the symbol is in the "sensor" category (Multi-function sensors), which probably makes more sense since this is both temperature and humidity?

Thanks!

**Comment by piotr-wiszowaty** [comment]
Good idea (2x).
footprint: [#1332](https://github.com/KiCad/kicad-footprints/pull/1332)
symbol: [#1451](https://github.com/KiCad/kicad-symbols/pull/1451)

**Pull request merged**
