### PR TITLE
Add QFN-12 footprint with 8 thermal vias

### PR DESCRIPTION
**Pull request by drid**
From https://gitlab.com/librespacefoundation/lsf-kicad-lib

Add QFN-12 footprint with 8 thermal vias and pad sizes as required by MMZ09332BT1

https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/ltc-legacy-qfn/QFN_12_%2005-08-1855.pdf
https://www.nxp.com/docs/en/data-sheet/MMZ09332B.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
This is a footprint for a standard qfn package so its footprint should be generated using our ipc generator script (and yes it will deviate from the nxp suggestion. we decided to use ipc over manufactuer suggestions for generic packages)

**Comment by drid** [comment]
Can a via pattern like
image
 be generated?

Is there a way to only generate ThermalVia version as not to create duplicates?

**Comment by poeschlr** [comment]
No but again we do not follow the recommendation of a single manufacturer for generic packages.

**Comment by drid** [comment]
Ok, i can do 9. Is there a way to generate the thermalvia only footprint since the non thermal one will be a QFN-12 duplicate?
Unless there is no point in having the existing QFN-12 with extra vias

**Comment by poeschlr** [comment]
We might want to wait for feedback on https://github.com/KiCad/kicad-website/issues/438

**Comment by myfreescalewebpage** [comment]
@drid any news here ?

**Comment by drid** [comment]
There was no feedback on that matter, I can either a scripted specialized footprint with mnf name as suggested.

**Comment by myfreescalewebpage** [comment]
Yes, they are already some footprint in the generator with manufacturer in the name

**Comment by drid** [comment]
Created https://github.com/pointhi/kicad-footprint-generator/pull/640

**Comment by chschlue** [comment]
@myfreescalewebpage script addition merged.

**Comment by myfreescalewebpage** [comment]
Thanks, merging here

**Pull request merged**
