### PR TITLE
Added NXP_LGA-8 for MPL3115A2

### PR DESCRIPTION
**Pull request by jneiva08**
Is the same footprint as "NXP_LGA-8_3x5mm_P1.25mm_H1.2mm" but with "_H1.1mm"

Datasheet: https://www.nxp.com/docs/en/data-sheet/MPL3115A2.pdf
Script: https://github.com/pointhi/kicad-footprint-generator/pull/347
Symbol: https://github.com/KiCad/kicad-symbols/pull/1796#issuecomment-493778763

Footprint:
NXP_LGA-8_H1 1mm

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
see comments on script PR

**Comment by jneiva08** [comment]
Have made the changes requested and updated the footprint.

**Comment by poeschlr** [comment]
Parameters that influence the footprint are ok but the footprint height is still wrong. Merging the footprint, thanks

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
