### PR TITLE
Sop 8 son 8

### PR DESCRIPTION
**Pull request by Misca1234**
I was uberhauling the library Memory_NVRAM and Fujitsu's NVRAM serie MB85RSXX
and saw that there was missing 4 footprints for these NVRAM's

Fujitsu_WLP-8_3.09x2.28mm_Pitch0.4mm
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS1MT-DS501-00022-7v0-E.pdf

SOP-8_3.9x5.05mm_P1.27mm
http://www.fujitsu.com/downloads/MICRO/fsa/pdf/products/memory/fram/MB85RS16-DS501-00014-6v0-E.pdf

SOP-8_5.30x5.24mm_P1.27mm
http://www.fujitsu.com/ca/en/Images/MB85RS2MT-DS501-00023-1v0-E.pdf

SON-8-1EP_3.0x2.0mm_P0.5mm_EP1.4x1.6mm
http://www.fujitsu.com/downloads/MICRO/fsa/pdf/products/memory/fram/MB85RS16-DS501-00014-6v0-E.pdf

Foot print push here
https://github.com/KiCad/kicad-footprints/pull/634

3D models push here
https://github.com/KiCad/kicad-packages3D/pull/321

bild

bild

bild

bild

bild

bild

bild

bild

bild

bild

bild

bild

bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I would suggest the use of polygon pads for the chamfered pad or ignore that it is suggested to be chamfered.

**Comment by Misca1234** [comment]
Something like this for SON-8-1EP_3.0x2.0mm_P0.5mm_EP1.4x1.6mm

bild

bild

bild

bild

bild

**Comment by poeschlr** [comment]
Is there a reason to have the mask layer split to a separate pad? As far as i can see you use the same size as for the copper pad.

The paste layer should still be split. I would suggest a 2x2 array (3 rectangle pads plus one chamfered rectangle. The later is again a polygon pad)

**Comment by Misca1234** [comment]
Some thing like this then 

bild

**Comment by poeschlr** [comment]
The BGA package has the wrong pin pitch in y direction and maybe slightly wrong courtyard clearance.

As there is no suggested footprint i used my [pad calculator](https://docs.google.com/spreadsheets/d/1mz7J-FMTo-L3qUG917im-0DBbNAzGDmI479VqDLaEyw/edit?usp=sharing) to check what the pads should look like in the SOP footprints. The 3.9mm wide one is kind of ok but the 5.3mm wide one is far out. The SON footprint has a very small toe fillet.

Width 5.3mm

outside (Z) |   | 8.961248608 |   | 8.95
-- | -- | -- | -- | --
inside (S) |   | 5.518748736 |   | 5.5
width (X) |   | 0.66 |   | 0.65
  |   |   |   |  
pad center |   | 3.6125 |   |  
pad lenght |   | 0.8625 |   |  
pad width |   | 0.65 |   |  



Width 3.9mm

outside (Z) |   | 6.915331193 | 6.9
-- | -- | -- | --
inside (S) |   | 3.944626719 | 3.95
width (X) |   | 0.555192213 | 0.55
  |   |   |  
pad center |   | 2.7125 |  
pad lenght |   | 0.7375 |  
pad width |   | 0.55 |  

SON:

outside (Z) |   | 3.709164729 | 3.7
-- | -- | -- | --
inside (S) |   | 2.054222958 | 2.05
width (X) |   | 0.4 | 0.4
  |   |   |  
pad center |   | 1.4375 |  
pad lenght |   | 0.4125 |  
pad width |   | 0.4 |

**Comment by Misca1234** [comment]
Perhaps it is better to use scripts for this

Should Fujitsu_WLP-8_3.09x2.28mm_Pitch0.4mm
use kicad-footprint-generator/scripts/Package_LGA ?
or
kicad-footprint-generator/scripts/Package_BGA

SOP-8_3.9x5.05mm_P1.27mm
SOP-8_5.30x5.24mm_P1.27mm
SON-8-1EP_3.0x2.0mm_P0.5mm_EP1.4x1.6mm
use kicad-footprint-generator/scripts/Package_SOIC ?

**Comment by poeschlr** [comment]
Instead of package_soic for the sop footprints use the new package_gullwing generator that is in my pull request: https://github.com/pointhi/kicad-footprint-generator/pull/149

The SON package might best use the dfn generator. (there is already a wson that is created by that generator in the lib)

The package lga generator should work but i have not checked it in a while. (some changes to some underlying things could have damaged it.)

I am not sure if the bga generator can make footprints with this type of pad layout.

**Comment by Misca1234** [comment]
This push is remade with scripts, starting with the SOP's
the 2 SOP's are in this push
https://github.com/KiCad/kicad-footprints/pull/887

**Comment by Misca1234** [comment]
This push is remade with scripts

The SON is in this push
https://github.com/KiCad/kicad-footprints/pull/966

**Comment by Misca1234** [comment]
They have now been separated, closing this psuh

**Pull request closed without merging**
