### PR TITLE
Add Valve socket octal

### PR DESCRIPTION
**Pull request by dsiggi**
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
       https://cdn-reichelt.de/documents/datenblatt/A100/FSRICHARDSON_ROEHRENF_8PRK_EN.pdf
- [x] An example screenshot image is very helpful 
       valve_socket_octal
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
@dsiggi 
I am currently ovehaul the valve foot prints and make them with scripts, 
join the discussion here
https://github.com/KiCad/kicad-footprints/issues/1103

PS
This mean that we do not have t hand make the foot pritns
I also have 3D models waiting when the foot pritns are ok
DS

**Comment by poeschlr** [comment]
@Misca1234 what is the state on this?

**Comment by Misca1234** [comment]
I would guess it is obsolete because of 
https://github.com/KiCad/kicad-footprints/pull/1139

The octal socket type is included in the push

@dsiggi 
Would you agree to close this ?
Please have a look at 
https://github.com/KiCad/kicad-footprints/pull/1139
and see if it covers your needs, including this.

**Comment by dsiggi** [comment]
Yes,
I think we can close here. The socket is in your Pull Request, so it's good for me.

**Pull request closed without merging**
