### PR TITLE
Correct Tdson-8-1

### PR DESCRIPTION
**Pull request by evanshultz**
Breaking apart https://github.com/KiCad/kicad-footprints/pull/981.

https://www.infineon.com/cms/en/product/packages/PG-TDSON/PG-TDSON-8-1/

Nearly all dimensions were wrong so they got fixed.

image

image

Removed hand soldering footprints since the X dimension was +/-3.5mm and the fixed reflow one is +/-3.325mm. No substantial difference.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Infineon suggests a simple rectangle for copper. Only soldermask would get the complex outline you chose.

**Comment by evanshultz** [comment]
Oh yes. Thanks. The original one was like that so the documentation changed or I missed it when I did the original update. Also corrected the description to match just the Infineon metadata.
image

**Comment by evanshultz** [comment]
@poeschlr 
Is this ready? I hope I fixed what you brought up.

**Comment by poeschlr** [comment]
Infineon suggests your old detailed shape for the mask layer, you now have only a rectangle pad. I am convinced it would work this way but would for sure require a bit more paste that way so i would prefer to follow the suggestion more closely.

**Comment by evanshultz** [comment]
That's not what I see. Here is the website's image:
image

The mask is cut out the same as the copper pad. Only the stencil (paste) is broken up.

Have I misunderstood?

**Comment by chschlue** [comment]
Mask looks "pinnacle" shaped to me while copper is rectangular.

**Comment by evanshultz** [comment]
Alright. I finally get it. Mask has 'teeth' at the top. I was afraid I was misunderstanding. Will fix...

**Comment by evanshultz** [comment]
Corrected:
image

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
