### PR TITLE
Add Max30102 heart rate sensor

### PR DESCRIPTION
**Pull request by aurabindo**
Signed-off-by: Aurabindo J <mail@aurabindo.in>

Add MAX30102 Heart Rate Sensor. I'm not sure if Sensor lib is the right location for this.
Datasheet: https://datasheets.maximintegrated.com/en/ds/MAX30102.pdf
max30

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Please use a style closer to the standard style 
2018-01-20 17_47_51-library browser package_csp d__kicad_kicad-footprints_package_csp pretty

- i.e. box around the package + pin1-marker as additional corner
- add pin1-marker to F.Fab

**Comment by jkriege2** [comment]
Also this footprint should go to the existing folder for opto-devices: https://github.com/KiCad/kicad-footprints/tree/master/OptoDevice.pretty

**Comment by aurabindo** [comment]
Okay I will update them soon

**Comment by aurabindo** [comment]
@jkriege2 from where should the bounding box offset be measured ? boundary in the silk screen or F.Fab ?

**Comment by jkriege2** [comment]
F.Fab and/or pad-outline, whichever is farther out. You can also use our check-scripts with the option `--fixmore`, which will autogenerate the courtyard for you!

**Comment by aurabindo** [comment]
max30102_fp

**Pull request merged**
