### PR TITLE
added Texas_S-PWSON-N6 footprint

### PR DESCRIPTION
**Pull request by Shackmeister**
Datasheet: http://www.ti.com/lit/ds/symlink/tps717.pdf

screenshot:
s-pwson-n6

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
The exposed pad has the wrong size. I think you mixed up copper and paste dimensions.

Also the datasheet suggests thermal vias. So add a version that includes them as suggested in the datasheet.

screenshot from 2018-01-18 01-21-56

**Comment by Shackmeister** [comment]
do we have a standard for the size of the Thermal Vias?

**Comment by Shackmeister** [comment]
@poeschlr nice catch Mr René Eagleeye Poeschlr

Travis output should be ok

I used 0.6mm pad and 0.25 mm drill and only *.Cu layer
(found in another footprint)

pwson_thermalvias

**Comment by poeschlr** [comment]
You also need a copper only pad on B.Cu for radiating heat.
More details see KLC
http://kicad-pcb.org/libraries/klc/F4.4/

**Comment by Shackmeister** [comment]
Ill give it a try and then you'll probably have to correct me :)
If Paste is not ok to have on the Vias should I just split up the paste layer enough to avoid the vias?

**Comment by Shackmeister** [comment]
first attempt
pwson_6_thermalvias

**Comment by poeschlr** [comment]
Back layer should only be copper so this is ok.

Splitting paste does not really make much sense for this FP. (The datasheet does suggest the paste area as you made it.)

**Comment by Shackmeister** [comment]
so it's all good? :)

**Comment by poeschlr** [comment]
Thanks for the contribution

**Pull request merged**
