### PR TITLE
Modififed foot print

### PR DESCRIPTION
**Pull request by Misca1234**
This is a remake of the 
LA25-P
http://www.lem.com/docs/products/la_25-p.pdf

It is mainly the foot print that have been updated
a 3D model have been added
The 3D model is script generated

Symbol
https://github.com/KiCad/kicad-symbols/pull/320

foot print 
https://github.com/KiCad/kicad-footprints/pull/387

3D model
https://github.com/KiCad/kicad-packages3D/pull/272

bild

bild

### CODE REVIEW

**Comment by Ratfink** [comment]
Thanks for the contribution!

I have just one suggestion.  The recommended pad diameter in the datasheet is 2.2 mm, but you have it as 2.5 mm.  Please set the footprint's pads to match the datasheet.

**Comment by Misca1234** [comment]
Changed it to 2.2

**Comment by poeschlr** [comment]
The body dimensions are not quite right (see annotations in the sketch)
screenshot from 2018-05-06 03-58-09

**Comment by Misca1234** [comment]
This one is so old so not even LEM support the data sheet any more, I found a new source here
http://www.components-center.com/datasheets/10/PRT-13612.pdf

If the suggested changes are made then the F.CrtYrd line will be 37 mm "wide" which in turn makes the F.Crtyrd wider than the specified 36.6 mm in the datasheet.
So neither the F.Fab, F.Silk or F.CrtYrd will match the 36.6 from the datasheet

**Comment by poeschlr** [comment]
The datasheet you found agrees with the dimensions of the footprint as it is now. Could you add that datasheet to the description? That would document where the dimensions come from and i can merge.

**Comment by Misca1234** [comment]
Some crap have happen with git again, I tried to rebase against the master but it was so heavily modified so the merge from master to this branch was messed up so I tried to create a new branch 

new push
https://github.com/KiCad/kicad-footprints/pull/567

**Pull request closed without merging**
