### PR TITLE
Scripted version for LQFP-144, 160 and 176

### PR DESCRIPTION
**Pull request by poeschlr**
Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/245

# LQFP-144_20x20mm_P0.5mm:
datasheet: http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf (page 426)

screenshot from 2018-12-19 00-10-54
```yaml
LQFP-144_20x20mm_P0.5mm:
  size_source: 'http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf (page 426)'
  body_size_x:
    nominal: 20
  body_size_y:
    nominal: 20
  overall_size_x:
    nominal: 22
  overall_size_y:
    nominal: 22
  lead_width:
    minimum: 0.17
    nominal: 0.22
    maximum: 0.27
  lead_len:
    minimum: 0.45
    nominal: 0.6
    maximum: 0.75
  pitch: 0.5
  num_pins_x: 36
  num_pins_y: 36
```

# LQFP-160_24x24mm_P0.5mm:
datasheet: 'https://www.nxp.com/docs/en/package-information/SOT435-1.pdf

screenshot from 2018-12-19 00-11-00
```yaml
LQFP-160_24x24mm_P0.5mm:
  size_source: 'https://www.nxp.com/docs/en/package-information/SOT435-1.pdf'
  body_size_x:
    minimum: 23.9
    maximum: 24.1
  body_size_y:
    minimum: 23.9
    maximum: 24.1
  overall_size_x:
    minimum: 25.85
    maximum: 26.15
  overall_size_y:
    minimum: 25.85
    maximum: 26.15
  lead_width:
    minimum: 0.17
    maximum: 0.27
  lead_len:
    minimum: 0.45
    maximum: 0.75
  pitch: 0.5
  num_pins_x: 40
  num_pins_y: 40
```

# LQFP-176_20x20mm_P0.4mm:
datasheet: 'https://www.onsemi.com/pub/Collateral/566DB.PDF

screenshot from 2018-12-19 00-11-05
```yaml
LQFP-176_20x20mm_P0.4mm:
  size_source: 'https://www.onsemi.com/pub/Collateral/566DB.PDF'
  body_size_x:
    nominal: 20
    tolerance: 0.1
  body_size_y:
    nominal: 20
    tolerance: 0.1
  overall_size_x:
    nominal: 22
    tolerance: 0.2
  overall_size_y:
    nominal: 22
    tolerance: 0.2
  lead_width:
    nominal: 0.15
    tolerance: [0.04, 0.05]
  lead_len:
    nominal: 0.5
    tolerance: 0.2
  pitch: 0.4
  num_pins_x: 44
  num_pins_y: 44
```

# LQFP-176_24x24mm_P0.5mm:
datasheet: 'https://www.st.com/resource/en/datasheet/stm32f207vg.pdf (page 163)

screenshot from 2018-12-19 00-11-11
```yaml
LQFP-176_24x24mm_P0.5mm:
  size_source: 'https://www.st.com/resource/en/datasheet/stm32f207vg.pdf (page 163)'
  body_size_x:
    minimum: 23.9
    maximum: 24.1
  body_size_y:
    minimum: 23.9
    maximum: 24.1
  overall_size_x:
    minimum: 25.9
    maximum: 26.1
  overall_size_y:
    minimum: 25.9
    maximum: 26.1
  lead_width:
    minimum: 0.17
    maximum: 0.27
  lead_len:
    minimum: 0.45
    maximum: 0.75
  pitch: 0.5
  num_pins_x: 44
  num_pins_y: 44
```

### CODE REVIEW

**Comment by Shackmeister** [comment]
@poeschlr could you perhaps add height in the parameters? Just in case we add this yaml format to the 3D generator

**Comment by poeschlr** [comment]
Knock yourself out. I'm done with this.

**Comment by poeschlr** [comment]
Sorry that came across a bit harsh. I just invested 8 hours into this. (all LQFP footprints are now transferred to the script) I have enough for now.

The review here should really only look at the footprint side of things as this is the only thing i added.

**Comment by evanshultz** [comment]
Would you mind using a direct link to the appropriate page, such as http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#page=426 for the Microchip one? And for the Microchip, perhaps page 425 is a better place to start since that is the first page dealing with this package? A direct link would also be nice for the ST footprint.

**Comment by poeschlr** [comment]
updated datsheet links

**Pull request merged**
