### PR TITLE
New scripted versions for LQFP-52 footprints

### PR DESCRIPTION
**Pull request by poeschlr**
This adds scripted versions of the LQFP 52 footprints
script PR: https://github.com/pointhi/kicad-footprint-generator/pull/245

The 0.65mm pitch version uses ipc definition for small pin pitch
(0.625mm) to allow for enough pad to pad clearance.

# LQFP-52-1EP_10x10mm_P0.65mm_EP4.8x4.8mm (plus thermal via)

datasheet: https://www.onsemi.com/pub/Collateral/848H-01.PDF

screenshot from 2018-12-18 20-04-24
screenshot from 2018-12-18 20-05-33

```yaml
LQFP-52-1EP_10x10mm_P0.65mm_EP4.8x4.8mm:
  size_source: 'https://www.onsemi.com/pub/Collateral/848H-01.PDF'
  body_size_x:
    nominal: 10
    tolerance: 0
  body_size_y:
    nominal: 10
    tolerance: 0
  overall_size_x:
    nominal: 12
    tolerance: 0
  overall_size_y:
    nominal: 12
    tolerance: 0
  lead_width:
    minimum: 0.22
    maximum: 0.4
  lead_len:
    minimum: 0.45
    maximum: 0.75
  pitch: 0.65
  num_pins_x: 13
  num_pins_y: 13

  EP_size_x: 4.8
  EP_size_y: 4.8
  EP_num_paste_pads: [3, 3]

  thermal_vias:
    count: [4, 4]
    drill: 0.2
    paste_via_clearance: 0.1
    paste_between_vias: 1
    paste_rings_outside: 1
    EP_paste_coverage: 0.65
    grid: [1, 1]
```

# LQFP-52_10x10mm_P0.65mm
datasheet: https://www.nxp.com/docs/en/package-information/98ARL10526D.pdf
screenshot from 2018-12-18 20-05-53

```yaml
LQFP-52_10x10mm_P0.65mm:
  size_source: 'https://www.nxp.com/docs/en/package-information/98ARL10526D.pdf'
  # ipc_density: 'least'
  force_small_pitch_ipc_definition: True
  body_size_x:
    nominal: 10
  body_size_y:
    nominal: 10
  overall_size_x:
    nominal: 12
  overall_size_y:
    nominal: 12
  lead_width:
    nominal: 0.325
  lead_len:
    minimum: 0.45
    maximum: 0.75
  pitch: 0.65
  num_pins_x: 13
  num_pins_y: 13
```

### CODE REVIEW

**Comment by evanshultz** [comment]
`LQFP-52-1EP_10x10mm_P0.65mm_EP4.8x4.8mm` still only has pads 0.15mm apart (3.9mm - 0.5mm / 2 - 3.25mm - 0.5mm / 2 = 0.15mm). That's a bit tight for me. The small pitch IPC definition (used on the no-EP one) gets to 0.25mm which I like. Could you use that definition for all footprints here?

`LQFP-52_10x10mm_P0.65mm` shows 0.25-0.4mm lead width, which may affect things over using the 0.325 nominal reference dimension. How would this one be affected if the lead width min and max are used?

**Comment by poeschlr** [comment]
You are totally right. fixed.

**Comment by evanshultz** [comment]
Since 0.4mm is the max width for all, and they're now all using 0.4mm wide pads, this looks good to me. I do still wonder if it's best to use min and max lead width in the definition instead of only a nominal value? (I could image it being a good precedent, even if it's doesn't affect the footprints here.)

**Comment by evanshultz** [comment]
Right. And `LQFP-52_10x10mm_P0.65mm` above only shows the nominal lead width. Elsewhere I saw min and max which I expected. I'm letting you know that so you can update the definition.

**Comment by poeschlr** [comment]
The nxp datsheet for that one sadly has no tolerance listed for it.

And it is another one of these footprints that are not used by any symbol right now. (Only left in because it is not completely wrong so there is really no reason to delete it.)

**Pull request merged**
