### PR TITLE
add DS1095-WNR0

### PR DESCRIPTION
**Pull request by balcer**
http://www.connfly.com/userfiles/image/UpLoadFile/File/2013/5/6/DS1095.pdf

usb

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by balcer** [comment]
Hey, I'm planning to prepare 3D model for this connector but I want to be sure that footprint is ok.

**Comment by poeschlr** [comment]
A few dimensions are not quite right:
Screenshot from 2019-04-02 21-56-31

**Comment by balcer** [comment]
Hi, @poeschlr I made some changes, is it ok now? Sorry for abounding. And force push, last time I promise.

**Comment by poeschlr** [comment]
There are still a few errors
Screenshot from 2020-02-04 22-54-38

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
