### PR TITLE
More pulse footprints

### PR DESCRIPTION
**Pull request by evanshultz**
I have added the transformers from https://productfinder.pulseeng.com/products/datasheets/SPM2007_61.pdf. In some cases, I had previously added a compatible transformer (https://github.com/KiCad/kicad-footprints/pull/645, https://productfinder.pulseeng.com/products/datasheets/P663.pdf) so I simply placed the MPN of the new transformer as a keyword in the existing footprint.

A few of the dimensions were eyeballed, typically where the "body" (the part that sticks up farthest from the PCB) wasn't dimensioned.

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
The corresponding symbols are submitted at https://github.com/KiCad/kicad-symbols/pull/926.

**Comment by Misca1234** [comment]
Pulse_PA0926NL, should it not be named Pulse_P0926NL ?

PA1323NL
Why is the size given on page 19.0 x 8.6 x 7.6 different on page 5

PE-68386NL is this foot print exactly as PA2001NL ?

pa0264nl is this foot print exactly as pa2004nl ?

**Comment by evanshultz** [comment]
> Pulse_PA0926NL, should it not be named Pulse_P0926NL ?

Yes. I was afraid of mixing up "P" and "PA" so I checked this specifically a couple times. And still miraculously got it wrong. Thank you for catching that. Fixed now.

The dimensions of PA1323NL match on pages 1 and 5, but they're not the dimensions you wrote above. I don't see an issue with this PN. Can you please check this and let me know the issue you found?

For the two you asked if there are exactly the same, yes, Pulse confirmed to me that they are.

**Comment by Misca1234** [comment]
PA1323NL, not sure where I got the 19x from

**Pull request merged**
