### PR TITLE
Add RAK Wireless RAK811 LoRa module footprint

### PR DESCRIPTION
**Pull request by alnunez**
RAK Wireles RAK811 LoRa modules: RAK811-LF (433 MHz), and RAK811-HF (868MHz & 915MHz) versions. Both use the same footprint.

Datasheet:[https://downloads.rakwireless.com/LoRa/RAK811/Hardware_Specification/RAK811_LoRa_Module_Datasheet_V1.4.pdf](https://downloads.rakwireless.com/LoRa/RAK811/Hardware_Specification/RAK811_LoRa_Module_Datasheet_V1.4.pdf)

Schematic Symbol PR#[2812](https://github.com/KiCad/kicad-symbols/pull/2812)

RAK811-FP

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cp-aquila** [comment]
Hi @alnunez 
Just judging from the screenshot there are some small issues:
- Pin1 Silkscreen  indicator is not consistent with other footprints or KLC. See F5.1 https://kicad-pcb.org/img/klc/silk_polarized.png
- The courtyard looks to tight around the copper. It should have 0.25mm clearance. I might misjudge that because I am just looking at the screenshot!
- There is no Pin1 indicator on F.Fab

**Comment by alnunez** [comment]
> Hi @alnunez
> Just judging from the screenshot there are some small issues:
> 
>     * Pin1 Silkscreen  indicator is not consistent with other footprints or KLC. See F5.1 https://kicad-pcb.org/img/klc/silk_polarized.png
> 
>     * The courtyard looks to tight around the copper. It should have 0.25mm clearance. I might misjudge that because I am just looking at the screenshot!
> 
>     * There is no Pin1 indicator on F.Fab
> 
>     * The datasheet-link should be in the description

Done!

* Pin 1 silkscreen modified to meet KLC F5.1
* Pin1 indicator on F.Fab draw
* Datasheet link added to description
* Re-checked courtyard It's 0.25mm clearance from copper

**Comment by aris-kimi** [comment]
Hi @alnunez , thank you for your contribution.

I noticed only one change that needs to be done

εικόνα

Bevel line needs to have 1mm width:
εικόνα

**Comment by alnunez** [comment]
> Hi @alnunez , thank you for your contribution.
> 
> I noticed only one change that needs to be done
> 
> εικόνα
> 
> Bevel line needs to have 1mm width:
> εικόνα

OK. Fixed!

**Comment by myfreescalewebpage** [comment]
@alnunez I complete the review here:

- [ ] The F.Fab in the top left corner is not at 45°, to be fixed.

Else looks good
Joel

**Comment by alnunez** [comment]
> @alnunez I complete the review here:
> 
> * [ ]  The F.Fab in the top left corner is not at 45°, to be fixed.
> 
> Else looks good
> Joel

Ok. Fixed

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
