### PR TITLE
Added DHT11

### PR DESCRIPTION
**Pull request by Misca1234**
Its symbol is DTH11 in Sensor.lib
http://akizukidenshi.com/download/ds/aosong/DHT11.pdf

But there is no Sensor.pretty directory in the repository so I created Sensor.pretty but it might be the wrong way to go.

bild

bild

bild

### CODE REVIEW

**Comment by Ratfink** [comment]
Thanks for the contribution!

The footprint looks good overall.  I must question the name though: DHT11 sensors are only available in one package, correct?  In that case, I believe the name shouldn't have body dimensions or pin pitch.

Are you also planning on submitting a PR for the corresponding symbol to set its footprint association?

**Comment by poeschlr** [comment]
I think you two have shown a lot of good work lately. Both of you made some nice reviews and i think you would fit quite nicely into the maintainers team. If you are interested just give me a heads up and i will add you to the maintainers team.

**Comment by Ratfink** [comment]
@poeschlr Thank you very much for the offer!  I would love to join the team.

@Misca1234 One more thing: adding the Sensor.pretty library seems like a fine choice to me.  Just be sure to add it to the fp-lib-table as well.

**Comment by poeschlr** [comment]
@Ratfink welcome to the team. you should now be able to merge changes. If you are unsure just ping one of us more experienced members.

**Comment by Misca1234** [comment]
Hi

"I must question the name though: DHT11 sensors are only available in one package, correct?"
Yes, I was checking libraries for errors and en counted the symbol for DTH11 and saw it did not have a footprint, that is the reason for this push,
I am going to add more to sensor.lib from aosong but that will be both symbol, footprint and 3D models.
they have one very similar, CM2120 which will be added.

" Just be sure to add it to the fp-lib-table as well." 
That was a follow up question, can i change that too, if so, I can add it to this push

@poeschlr 
" quite nicely into the maintainers team."
Oh, thanks a lot, that was trustfully of you to give me that oppertunity.
What is required of me and what will I be able to do beside what I am doing now ?

**Comment by poeschlr** [comment]
As this would be a voluntary position nothing can be required from you. 
You would gain write access to the repos that are under the responsibility of the library team.

This means you get the ability to merge pull requests. (If you make a review of a PR and think it fulfills all requirements to be added, you are then able to merge.)

Or put differently: Nothing really changes, but you get more "power". It is expected that you will use it responsibly.

**Comment by aimylios** [comment]
@Misca1234
You designed this footprint under the assumption that the body is 4,5mm thick and that the pins are centred in x direction. This is not the case for the DHT11 devices that I have, which are 6,0mm thick (datasheet says 5,5mm) and the pins are shifted about half a mm to the right side (i.e. positive x direction in your fp).

dht11

**Comment by Misca1234** [comment]
Hmm, that explains why I could not fit the 3D model correctly, let me update it according to your information

Here is how the 3D model will look like 

bild

**Comment by Misca1234** [comment]
Something like this ?
bild

**Comment by aimylios** [comment]
Difficult to say by your image, but I think you shifted the pins in positive y direction, is that correct? This is not what I meant, I was talking about the x direction.
Even the datasheet shows the asymmetry, although in the wrong direction and it doesn't give the actual values...
dht11_drw

**Comment by Misca1234** [comment]
This should do it

**Comment by Misca1234** [comment]
This should do it 

bild

**Comment by Misca1234** [comment]
@poeschlr 
That is a great responsibility but would be interesting, I am flattered and it would be interesting to take that role.

**Comment by poeschlr** [comment]
Welcome to the team. I just send out the invitation.

**Comment by aimylios** [comment]
@Misca1234
Yes, that looks good! But please take everything I say with a grain of salt, the devices I have here are relatively old (maybe even several years), and I don't know if the package has changed in the meantime and is now more similar to what the datasheet says.

Did you draw the 3D model yourself? It looks like the holes on the front are not distributed evenly, although they should be.
dht11_photo

**Comment by Shackmeister** [comment]
Welcome to the team @Misca1234 and @ratfink :)

**Comment by Misca1234** [comment]
@Shackmeister 
thanks a lot

@aimylios 
Yes 3D model is handdrawn, i guess i can add some more holes

**Comment by Misca1234** [comment]
@poeschlr 
So I will do this on my computer to merge this branch to master and push it to the master repository ?
git checkout master
git merge DHT11
git push origin master

or should I do it via some page on github ?

**Comment by poeschlr** [comment]
Every pull request now should show a "merge pull request" button (in green) on the bottom of the conversation page (this page for example.)
If everything is ok you are allowed to merge via this button. (Only contributions by others of course. Yours will still be reviewed by some other librarian and merged by them. I used it only as an example because, well when you read this on the github page you should see the button easily.)
More details see the github user documentation: https://help.github.com/articles/merging-a-pull-request/

**Comment by daab4848** [comment]
@poeschlr @Ratfink @Misca1234 I was thoughtlessly wandering through different footprint PRs and I just happen to come across this PR. It seems ready to merge, but has not been done so (perhaps accidentally forgotten?)

**Comment by poeschlr** [comment]
I really dislike the fact that the datasheet is missing that many dimensions. Is there perhaps any official document that we can use to verify the dimensions?

**Comment by Misca1234** [comment]
Not bad, I will check the model against the dimensions

**Comment by Misca1234** [comment]
After all tours with this one and git messed with the merge 

warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your merge.renamelimit variable to at least 1567 and retry the command.
Automatic merge failed; fix conflicts and then commit the result.

I recreate this push
https://github.com/KiCad/kicad-footprints/pull/576

**Pull request closed without merging**
