### PR TITLE
Add 3.5x3.5mm QFN-20 with 2mm pad.

### PR DESCRIPTION
**Pull request by ObKo**
Also known as TI's S-PVQFN-N20

http://www.ti.com/lit/ml/mpqf239/mpqf239.pdf

Generated by kicad-footprint-generator.

qfn-20-doc

qfn-20

Associated with: https://github.com/pointhi/kicad-footprint-generator/pull/339, https://github.com/KiCad/kicad-symbols/pull/1728

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks! Comments made in the script PR.

**Comment by ObKo** [comment]
Fixed.

**Comment by evanshultz** [comment]
Thank you. Can you please confirm if this captures the final changes to the script? Then I will merge.

Also, please don't force push commits because that makes reviewing harder. I will squash merge to keep the commit history clean.

**Comment by ObKo** [comment]
> Thank you. Can you please confirm if this captures the final changes to the script?
I confirm.

**Comment by evanshultz** [comment]
Great. Thank you!

**Pull request merged**
