### PR TITLE
Fujitsu wlp 8 3.09x2.28mm pitch0.4mm

### PR DESCRIPTION
**Pull request by Misca1234**
Push of Fujitsu_WLP-15_2.28x3.092mm_Layout3x5_P0.4mm

used by MB85RS1MT page 24
http://www.fujitsu.com/global/documents/products/devices/semiconductor/fram/lineup/MB85RS1MT-DS501-00022-7v0-E.pdf

https://github.com/pointhi/kicad-footprint-generator/compare/master...Misca1234:Fujitsu_WLP-8_3.09x2.28mm_Pitch0.4mm?expand=1

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
This part requires a different pin pitch for y direction compared to x direction.

screenshot from 2018-12-05 22-56-51

**Comment by Misca1234** [comment]
Fixed, moved the pins 0.2 mm

bild

**Comment by poeschlr** [comment]
Manually or did you upsate the script.  If you did it manually then please close the script pr. ( I am on mobile. The link above does not work for me. So I can not check this for myself right now. )

**Comment by Misca1234** [comment]
Yes, I did it manually and I also killed/closed the script push

**Comment by poeschlr** [comment]
Sorry for the delay.

The inner pads are not quite at the right place.
screenshot from 2019-01-01 15-47-01

**Comment by Misca1234** [comment]
They are moved now

bild

**Comment by poeschlr** [comment]
Thanks. Looks god now.

**Pull request merged**
