### PR TITLE
Macom ETC RF transformer

### PR DESCRIPTION
**Pull request by calebns**
https://cdn.macom.com/datasheets/ETC1-1-13.pdf

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
I think you have forgot the %R text in the middle of the foot print

**Comment by calebns** [comment]
Yes, the %r is in the footprint code at pint 0,0 already. I don't know why it didn't showed up on the picture attached, probably I've messed sth up with the printscreen.

**Comment by Shackmeister** [comment]
Hi @calebns 
I had a look at the footprint and have a few comments:

- %R designator should be flipped 90 degress and scaled down a bit to fit within the fab outline, text thickness should be 15% of text size

- fab chamfer should be 1/4 of the shortest side.

- The extra graphic on silkscreen is not needed

- please add a silkscreen line along pin 1 to indicate the pin 1

- silkscreen should have a clearance of 0.2mm to the pads, this can be tested by setting the "Solder Mask Clearance", inside "Footprint Properties", to 0.2mm

- fab outline should according to the datasheet be 2,79mm x 3,83mm

- Courtyard should be 0.25mm from pads or fab outline, whichever is closer

Dont hesitate to ask if I can be helpful with something :)

Please see attached image for inspiration:
macom

**Comment by Ratfink** [comment]
Closing, as #585 was finished first.

**Pull request closed without merging**
