### PR TITLE
Adding samtec edge connector footprints (MECF)

### PR DESCRIPTION
**Pull request by poeschlr**
The other footprints in the old Samtec repo are normal pin header footprints. For discussion if they should be included see: https://github.com/KiCad/kicad-footprints/issues/130

This PR will add both the MECF series edge connectors and the footprints for the compatible sockets.

# Edge connector

- should the connector pads include paste?
- should the pads be of type TYPE_CONNECT instead of TYPE_SMT?
- Currently we use a courtyard clearance of 0.25 is this ok? (Does a courtyard even make sense here?)

### CODE REVIEW

**Comment by poeschlr** [comment]
# Compatible Sockets for Edge Connectors

Only change compared to the old connector is that now the NPTHs have the same pad size as drill size. (was 0 earlier which kills the 3d viewer of my version.)

For now i added the sockets to the same lib as the edge connectors. Should they be separated?

**Comment by SchrodingersGat** [comment]
> 
>     should the connector pads include paste?
>     should the pads be of type TYPE_CONNECT instead of TYPE_SMT?
>     Currently we use a courtyard clearance of 0.25 is this ok? (Does a courtyard even make sense here?)

* I think these should **not** have paste - the socket grips exposed copper on the PCB, yes?
* What does TYPE_CONNECT actually mean? I have never understood this.

**Comment by poeschlr** [comment]
I will remove paste.

I also do not really know why a special pad type for connector is necessary. But it seems to be there in kicad.

**Comment by SchrodingersGat** [comment]
Check out this thread here - https://forum.kicad.info/t/usage-pad-type-connector/1087/3

So we should be using these pads for 

* Edge connectors
* Wire bonding pads

**Comment by poeschlr** [comment]
Pads now have the type connect and don't include paste.

**Comment by SchrodingersGat** [comment]
Nice work :)

**Pull request merged**
