### PR TITLE
Fix 7SegmentLED_LTS6760_LTS6780

### PR DESCRIPTION
**Pull request by cpresser**
Body size was 12.5, but it is 12.6mm
Also fixed silk screen width and position to be completely outside if F.Fab

Related: https://github.com/KiCad/kicad-symbols/pull/2051

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
The courtyard outline would also need fixing.

**Comment by cpresser** [comment]
Thanks for the check. Turns out poking around with the values and moving single lines is not the best approach.
I now redrew the body from scratch.

**Comment by poeschlr** [comment]
courtyard clearance in x direction is 0.26 on both sides

**Comment by poeschlr** [comment]
Ah damn forgot that the kicad measure tool rounds to two digits. https://bugs.launchpad.net/kicad/+bug/1829317
The clearance is 0.255 meaning it is ok.

**Pull request merged**
