### PR TITLE
Littelfuse Polymer Protected Zener Diode LS series

### PR DESCRIPTION
**Pull request by carlosromorgar**
http://m.littelfuse.com/~/media/electronics/datasheets/polyzen_devices/littelfuse_polyzen_standard_polyzen_catalog_datasheet.pdf.pdf

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by carlosromorgar** [comment]
Hi

This footprint is for KiCad/kicad-symbols#494

BR

**Comment by poeschlr** [comment]
Courtyard clearance is not uniform around the part (should be 0.25mm all around)
Body size should be 4x4mm

More details see screenshot
screenshot from 2018-05-05 03-46-33

**Comment by poeschlr** [comment]
Add a 3d models reference and we are good to go. (Fill out the 3d settings. You are not required to provide a 3d model but filling everything out in preparation allows users to add their own models if the so desire without changing the footprint.)

**Comment by carlosromorgar** [comment]
Hi
Sorry for that. It is my first time submitting footprints, and I have no experience. It is right the next commit?
Thanks
BR

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
