### PR TITLE
Add molex smd connector footprints. 

### PR DESCRIPTION
**Pull request by poeschlr**
The following Molex connectors are included here.
 - PicoBlade 
    - http://www.molex.com/pdm_docs/sd/533980271_sd.pdf
    - http://www.molex.com/pdm_docs/sd/532610271_sd.pdf)
 - Pico-Clasp 
    - http://www.molex.com/pdm_docs/sd/5013310207_sd.pdf
    - http://www.molex.com/pdm_docs/sd/2023960207_sd.pdf
 - Pico-EZmate 
    - http://www.molex.com/pdm_docs/sd/781710002_sd.pdf
    - http://www.molex.com/pdm_docs/sd/2026560021_sd.pdf
 - Panelmate
    - no datasheet found (needed to trust the old footprints)

Script: https://github.com/pointhi/kicad-footprint-generator/pull/81

I discovered that the picoblade and pico ezmate had slightly wrong pad sizes and positions. (according to the datasheets)
For panelmate i could not find a good datasheet. (not available for new business. But still available at distributors.)

I choose the molex naming for the series name. We did not really get to a conclusion in https://github.com/KiCad/Connectors_Molex.pretty/issues/58 (@jkriege2, @evanshultz, @Shackmeister did not care to comment.)

Now the fun part. The screenshots. (Footprints on the back side are the old once. Yes i added a few connector types.)

screenshot from 2017-11-11 00-22-48
screenshot from 2017-11-11 00-22-40

screenshot from 2017-11-11 00-22-31
screenshot from 2017-11-11 00-08-55
screenshot from 2017-11-11 00-08-50

### CODE REVIEW

**Comment by poeschlr** [comment]
I noticed a mistake. The Panelmate connectors are Horizontal not Vertical. Will fix it shortly. (I will also add more connectors. There have been scripts in the script repo that do not have corresponding footprints in the Connectors_Molex repo.)

**Comment by poeschlr** [comment]
Pico lock horizontal: http://www.molex.com/pdm_docs/sd/5040500891_sd.pdf
screenshot from 2017-11-11 11-07-24
screenshot from 2017-11-11 11-03-41

**Comment by poeschlr** [comment]
Ok this should now be merge able.

More details about the stuff added yesterday:
screenshot from 2017-11-11 11-21-53

screenshot from 2017-11-11 11-29-15

screenshot from 2017-11-11 11-45-14


screenshot from 2017-11-11 11-40-03


screenshot from 2017-11-11 11-35-47

@easyw thanks for the new stepup importer. Having the fab and courtyard included makes checking footprints really a lot faster.

**Comment by SchrodingersGat** [comment]
Awesome work :) The scripts really are a great tool! Thanks!

**Comment by SchrodingersGat** [comment]
I have updated the [todo](https://github.com/KiCad/kicad-footprints/blob/master/TODO.md) also

**Comment by poeschlr** [comment]
Thanks for taking care of the todo.

**Pull request merged**
