### PR TITLE
Add FC source files

### PR DESCRIPTION
**Pull request by evanshultz**
I'm developing FreeCAD source files for a few footprints because that seemed like the best way to go. However, I'm not having complete success. I've included the WIP FC files.

Here is the footprint info:
- `Infineon_PG-LLGA-5-1`: https://www.infineon.com/cms/en/product/packages/PG-LLGA/PG-LLGA-5-1/
- `L_Wuerth_WE-TPC-3816`: http://katalog.we-online.de/pbs/datasheet/7440310047.pdf

Currently I'm running into a couple issues:
1. I cannot find how to add the labels for ref des and value. I looked in many WBs, Googled, and tried to copy them from the demos but I do not see how to add this.
2. The polygon pads aren't coming through. (Other layers seem to work OK.) I've added an anchor pad inside the boundary of the polygon outline and this works if I make a simple pad shape (like a rectangle) but for a complex pad shape it doesn't. I am successful generating footprints using the polygon pad demos included with KSU so I believe the issue is something I'm doing wrong.
3. I do not see how to set the pad number. This is not happening with any of the demos (all pads are numbered `#`) so perhaps this is a limitation of KSU?

Note that the paste layer sketch of `Infineon_PG-LLGA-5-1` still has 1 DOF which I haven't chased down yet. I'll build out the other paste pads once I take care of this. However, I don't think that's material to my questions above. All other sketches are fully constrained. That being said, I haven't used a MCAD tool since a decade ago in school so any tips and tricks or best practices are welcome!

From looking at the demos and the other source FC files in this repo, it appears some "post-processing" is required in KiCad or a text editor to add datasheet links in the description, pad numbers, etc. I'm only seeing that part of the footprint can be built in FC right now but perhaps I simply don't understand.

FC screenshots:
image
image

Pcbnew screenshot:
image

@easyw
Pinging you since surely you're able to help. :)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by easyw** [comment]
> I cannot find how to add the labels for ref des and value. I looked in many WBs, Googled, and tried to copy them from the demos but I do not see how to add this.

Just copy and paste between docs should work
> I do not see how to set the pad number. This is not happening with any of the demos (all pads are numbered #) so perhaps this is a limitation of KSU?

yes, it is not possible to set pin NBR in ksu atm

> The polygon pads aren't coming through.

I'll review those later on the evening... BTW for infineon fp, there is a demo of a similar fp in ksu (footprint-complex-arc-pads) which is similar to your. For the main pad, you need a custom geom.

**Comment by evanshultz** [comment]
@easyw 
Thank you! I appreciate if you can take a look.

The Infineon does have a custom pad design, which I can make directly in KiCad by hand so I know it's possible. It should be simpler than the demo with a split ring and I don't see what error I'm making. I can see that the paste layer won't export using KSU but I'm not sure if that's because there is 1 DOF or because of some other error.

For the Wuerth if I sketch a simple rectangle the pad shows up but not if I make a geometrically-correct pad with a half-moon bit out of the rectangle. The sketch has zero DOF and all elements form a closed polygon which I thought would be the only requirement for generating custom pads. Beats me. The poly pad layer does export here, so I thought I was good, but still no pads come through.

> Just copy and paste between docs should work

I tried that but couldn't paste using a right-click menu (copy is there to copy the label). I just figured out that Ctrl+V and the Edit menu work. Weird that the right-click menu doesn't have both copy and paste options.

But what if it's a new footprint design? How can I add the label if there was no source from which to copy?

At any rate, I am able to now generate all three pieces of text needed. Thanks!

**Comment by easyw** [comment]
please have a look at the fp source file attached
[L_Wuerth_WE-TPC-3816-reviewed.zip](https://github.com/KiCad/kicad-footprints/files/2427236/L_Wuerth_WE-TPC-3816-reviewed.zip)
[Infineon_PG-LLGA-5-1-reviewed.zip](https://github.com/KiCad/kicad-footprints/files/2427406/Infineon_PG-LLGA-5-1-reviewed.zip)

> But what if it's a new footprint design? How can I add the label if there was no source from which to copy?

FC has slightly changed the Annotation code, but anyway you can always copy the Ref & Label from the demo docs (always included with ksu wb)

**Comment by evanshultz** [comment]
@easyw 
Thanks again!

**L_Wuerth_WE-TPC-3816-reviewed**
Exporting your footprint works but mine doesn't. I hate to feel so lame. The only change I see you've made on this one are separating the pads into different sketches, removing constraint 14, and adding the labels; I attempted to make the same changes to my original sketch but I'm not getting pads. Since I can export your FC group and get pads I feel the issue is likely a fix that you made which I didn't notice.

**Comment by evanshultz** [comment]
FC is the latest 0.17 stable release. KSU is the latest according to the Addon Manager since it doesn't tell me I'm any commits behind.

**Comment by easyw** [comment]
Hi,
with this release (as seen in Report View Panel):

> kicad StepUp version 8.1.0.4
> ksuWB.Activated(v 7.8.1)

(installed from FC Tools Addons manager)
I can export your file to a kicad_mod fp without doing any modifications.

> OS: Windows 10
> Word size of OS: 64-bit
> Word size of FreeCAD: 64-bit
> Version: 0.17.13541 (Git)
> Build type: Release

> Here are the post-processing items I understand will need to be done in KiCad and can't be done in FC:
> 
>     Add pad numbers.
>     Move fab refdes (it is placed under the silk refdes).
>     Change value from silk to fab layer. 

I confirm those.
1. Pad nbrs it is not assignable ATM (and it would not in short time)
2. I could patch this to move silks refdes to fab
3. the same for value
2&3 was the old standard method I didn't noticed has changed.
[wurth-generated.zip](https://github.com/KiCad/kicad-footprints/files/2434926/wurth-generated.zip)

**Comment by evanshultz** [comment]
My Report View Panel also shows `kicad StepUp version 8.1.0.4`.

I found the issue. I need to select the Group, apparently. I was selecting all the sketches and annotations together and then clicking the button to export the footprint. I know I had tried selecting the group before but it didn't work and so I'd forgotten to try it again recently. Thank you for the help.

Fixing item 3 would be great, but for item 2 ref des should be on both silk and fab (typically at 0,0 for fab layer and above the footprint for silk).

**Comment by evanshultz** [comment]
Wuerth footprint updated and footprint posted at https://github.com/KiCad/kicad-footprints/pull/981#issuecomment-425997055.

**Comment by easyw** [comment]
Thx for testing my WB!
This is improving its reliability. 😄 
PS: I'm going to fix 2&3 issues asap

**Comment by evanshultz** [comment]
My pleasure! Thank you! My ineptitude can sometimes be useful.

I also note one slightly annoying thing: If I generate a footprint and then try to do another one, I go back to the demo folder and not the folder where the last footprint was generated. I see two variables in KSU named "last fp path" and "last brd path". The former is the path where I wrote out the footprint, so I thought that would be remembered from the last invocation; however, the default folder for subsequent footprints goes to the latter variable. Maybe it's just me.

**Comment by easyw** [comment]
This is a small other issue I have to fix 😝  😄 
Thx for reminding me this.

**Comment by evanshultz** [comment]
@easyw 
Sure thing. Thank you!

Going back to the Infineon footprint, I'm running into an issue. A few of them:
1. If I generate a footprint from [Infineon_PG-LLGA-5-1.zip](https://github.com/KiCad/kicad-footprints/files/2435681/Infineon_PG-LLGA-5-1.zip), I get a crash (full path removed):
```
Running the Python command 'ksuToolsFootprintGen' failed:
Traceback (most recent call last):
  File "\FreeCAD\Mod\kicadStepUpMod\kicadStepUpCMD.py", line 1258, in Activated
    kicadStepUptools.PushFootprint()
  File "\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 15199, in PushFootprint
    export_footprint(name)
  File "\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 16081, in export_footprint
    npad=npad+os.linesep+createFpPad(mpad,offset,u'Pads_Geom', pgeompad_pos)
  File "\FreeCAD\Mod\kicadStepUpMod\kicadStepUptools.py", line 17129, in createFpPad
    pts="      (gr_circle (center "+str("{0:.3f}".format(pad[0][2]-d[0]))+" "+str("{0:.3f}".format(-1*pad[0][3]-d[1]))+") (end "+str("{0:.3f}".format(pad[0][2]-d[0]+pad[0][1]))+" "+str("{0:.3f}".format(-1*pad[0][3]-d[1]))+") (width "+str(wd_)+"))"+os.linesep

local variable 'd' referenced before assignment
```
2. Removing the Pads_Geom_0.46 sketch, the footprint is generated but all paste pads are doubled.
3. In the above condition, I'm left with an extraneous set of paste sketches after generating the footprint (this may explain the above?):
image

Another tweak to your tool would be to number non-Cu pads (paste and mask) as an empty string (`""`) since that's what we're using in the official KiCad library. All custom pads, regardless of layer, are numbered `#` now.

image

**Comment by easyw** [comment]
please have a look at the Infineon_PG-LLGA-5-1-reviewed.zip I posted above.
1. Geom pads need to have a reference in sketcher Construction geometry (blue edges)

> Another tweak to your tool would be to number non-Cu pads (paste and mask) as an empty string ("") since that's what we're using in the official KiCad library.

2. this need to be improved.. ATM I don't have the feature to implement Mask or Paste pads... you need to move them manually from Cu layers to technical layers.

**Comment by evanshultz** [comment]
FC source file updated. Infineon footprint PR is at https://github.com/KiCad/kicad-footprints/pull/989.

@easyw 
Got it. I missed that it must be a construction line.

I added two more items to the list of post-processing tasks to do in KiCad. As opposed to the raw (and usable!) output directly from KSU WB, the footprint file is arranged differently with more xy points per line on custom pads and no empty lines between custom pads once saved in KiCad.

You may want to note at the footprint PR how the copper ring for pad 5 is offset to the left even though it's placed properly in the actual footprint when importing the footprint. I don't think I'm doing anything wrong when importing the footprint and hopefully it's an easy thing to figure out.

As powerful as FC + KSU WB is, there are quite a few gotchas and/or steps that I don't find documented at the moment. Nonetheless, without all of your efforts it would be very hard if not impossible to make some of the footprints we can now quickly and confidently create. I hope my silly mistakes and learning curve here will be useful to all KSU WB users. Thank you, Maurice!!

**Comment by antoniovazquezblanco** [comment]
Corresponding footprints have been merged. Given that the sources seem to have been updated, I am going to merge this PR unless any other librarian expresses their concern.

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
While the Infineon footprint has been merged, the Wuerth footprint is at https://github.com/KiCad/kicad-footprints/pull/981 and has not been merged.  So I think it's premature to merge this. Once I wrap up a couple things I will break apart #981 for easier merging.

**Comment by antoniovazquezblanco** [comment]
Perfect

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
Both footprint PRs that use these source files have now been merged  and you assigned this case to yourself. Are you ready to merge this PR now?

**Comment by evanshultz** [comment]
@antoniovazquezblanco 
Is there anything stopping this from being merged?

**Comment by antoniovazquezblanco** [comment]
Sorry, I've missed this! I have been a little bit busy lately. I will come back for more regular contributions soon.

Thank you!

**Pull request merged**
