### PR TITLE
Add WSON-8 Package with 1.45 x 2.4mm Pad

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of WSON-8-1EP_3x3mm_P0.5mm_EP1.45x2.4mm, required for INA333 - [Datasheet](https://www.ti.com/lit/ds/symlink/ina333.pdf)

This is a direct copy of WSON-8-1EP_3x3mm_P0.5mm_EP1.6x2.0mm with only the exposed pad & solder paste layers changed (plus description & 3D Model path)

[Associated Symbol PR](https://github.com/KiCad/kicad-symbols/pull/2351)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by jamesrlucas** [comment]
Closed and re-opened to give Travis a nudge...

**Comment by aewallin** [comment]
+1 for this!
also needed for OPA818, symbol PR at https://github.com/KiCad/kicad-symbols/pull/2852

**Review by chschlue — CHANGES_REQUESTED** [review]
Please generate this FP using https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by jamesrlucas** [comment]
Sure, I'll be able to have a look next week once I'm back at work :)

**Comment by jamesrlucas** [comment]
Apologies for the delay, I've scripted the footprint - I ended up changing the name to something more specific as well. 

Script PR linked above. 

Travis doesn't like the Paste/Mask layers on the thermal pad - is this normal for a generated footprint?

**Comment by chschlue** [comment]
@cpresser assigning you because you already reviewed the script PR.

**Pull request merged**
