### PR TITLE
Add following packages, used by Altera:

### PR DESCRIPTION
**Pull request by krtkr**
Hi all!

I add following BGA packages:
1. BGA-68_5.0x5.0mm_Layout9x9_P0.5mm_Ball0.3mm_Pad0.25mm_NSMD
1. BGA-100_6.0x6.0mm_Layout11x11_P0.5mm_Ball0.3mm_Pad0.25mm_NSMD
1. BGA-144_7.0x7.0mm_Layout13x13_P0.5mm_Ball0.3mm_Pad0.25mm_NSMD
1. BGA-256_11.0x11.0mm_Layout20x20_P0.5mm_Ball0.3mm_Pad0.25mm_NSMD
1. BGA-100_11.0x11.0mm_Layout10x10_P1.0mm_Ball0.5mm_Pad0.4mm_NSMD
1. BGA-324_19.0x19.0mm_Layout18x18_P1.0mm_Ball0.5mm_Pad0.4mm_NSMD

They are required to finish following pull request:
https://github.com/KiCad/kicad-library/pull/1418

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi please check [Travis](https://travis-ci.org/KiCad/kicad-footprints/builds/311201279?utm_source=github_status&utm_medium=notification) one of the footprints seems to be a bit wonky

**Comment by krtkr** [comment]
@SchrodingersGat it seems I have used old bga_wizard.py script to create all footprints. I had to add F.Fab outline by hand and missed it at one of the footprints.

If you want, I can recreate there footprints using script found here: https://github.com/blairbonnett-mirrors/kicad/blob/master/pcbnew/scripting/plugins/bga_wizard.py.

Might be the script requires some patching also? Could be nice to make it producing required footprints out of the box for future use.

**Comment by poeschlr** [comment]
I don't think the footprint generator wizards are updated. We normally use the scripts by @pointhi to generate our footprints.

They can be found under:
https://github.com/pointhi/kicad-footprint-generator

**Comment by SchrodingersGat** [comment]
The wizard scripts are horribly out of date. My very first contribution to KiCad was to improve them, but since then we have developed the KLC, and they do not match.

I would like to move the KiCad python scripts to GitHub, organized under:

* Footprint wizards
* BoM plugins
* DRC / ERC checks
* Action plugins

This way they can be community contributed a bit easier, as opposed to building into the KiCad release.

**Pull request merged**
