### PR TITLE
Added Omron B3FS tactile switch series.

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://omronfs.omron.com/en_US/ecb/products/pdf/en-b3fs.pdf

imagen

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cnieves1** [comment]
3D: https://github.com/KiCad/kicad-packages3D/pull/647

**Comment by chmorgan** [comment]
Hi @cnieves1 you've been doing a ton of library work. Would you be interested in joining the kicad librarians team to help review pull requests for symbols, footprints, 3d models etc? If you are interested I can mention it to the team leads.

**Comment by cnieves1** [comment]
Seems TravisCI is checking other footprints than those in this PR. The three contributed here seem ok:

> Checking: Button_Switch_SMD.pretty/SW_SPST_Omron_B3FS-100xP.kicad_mod
> Checking footprint 'SW_SPST_Omron_B3FS-100xP' - No errors
> Checking: Button_Switch_SMD.pretty/SW_SPST_Omron_B3FS-101xP.kicad_mod
> Checking footprint 'SW_SPST_Omron_B3FS-101xP' - No errors
> Checking: Button_Switch_SMD.pretty/SW_SPST_Omron_B3FS-105xP.kicad_mod
> Checking footprint 'SW_SPST_Omron_B3FS-105xP' - No errors
> Checking: Button_Switch_THT.pretty/SW_Tactile_SKHH_Angled.kicad_mod

**Comment by cnieves1** [comment]
> Hi @cnieves1 you've been doing a ton of library work. Would you be interested in joining the kicad librarians team to help review pull requests for symbols, footprints, 3d models etc? If you are interested I can mention it to the team leads.

Thanks! It is not so much time since I started to use Kicad. 
I will try to do my best, but at least for the beginning, I would prefer if someone could review what I do...
I really don't know anything about librarian's work... Is there any librarian beginner's guide?

**Comment by chmorgan** [comment]
Hi @cnieves1, you've created so many parts now that you've got the pre-requisites out of the way for sure. If you are interested you could review a couple of pull requests against the KLC and the other feedback I've given on your other PRs as practice.

**Comment by cnieves1** [comment]
Hi @chmorgan, should I do that commenting as a normal user or is anything more required?

**Comment by chmorgan** [comment]
@cnieves1 you could do that as a normal user. Do an @ mention of me and I can take a look too. Then we can discuss with the others on the team if you'd like to join as a reviewer.

**Pull request merged**
