### PR TITLE
QFN-64 footprint for LAN951x

### PR DESCRIPTION
**Pull request by jneiva08**
Created by the script the footprint QFN-64 1EP 9x9mm P0.5mm EP7.3x7.3mm

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/00002304A.pdf

qfn64

This PR for the symbol is [#651](https://github.com/KiCad/kicad-symbols/pull/651)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

You should add pads beneath pad 65, like this

bild

**Comment by jneiva08** [comment]
My PR was made a few time, is still make sense to merge?
I'm asking because of recent merge of qfn 64pin (scripted) made by @poeschlr.
if it already exist witch should choose? In the name none have 7.3x7.3 pad.

**Comment by poeschlr** [comment]
My script does not (yet) create a 7.3x7.3mm ep version. I could add it if you want. (Sometime this evening CET)

**Comment by jneiva08** [comment]
I will be grateful if you could add to the script.
It's what makes more sense.

**Comment by jneiva08** [comment]
thanks @poeschlr for the footprint, Can close this PR?

**Comment by poeschlr** [comment]
Yes. Just make sure your symbol pull request uses the footprint name equal to what my pull request includes.

**Pull request closed without merging**
