### PR TITLE
Molex 43045-xx2x

### PR DESCRIPTION
**Pull request by evanshultz**
Added a missing part of the family that uses metal clips to secure the header to the PCB.
https://www.molex.com/pdm_docs/sd/430450221_sd.pdf
image

This used the same script as an existing header so it got an updated and corrected description.
https://www.molex.com/pdm_docs/sd/430450201_sd.pdf

Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/437

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
It might be best to give the mounting pads the pin number "MP" and add the -1MP suffix to the pin layout descriptor.

It might be good to include the keepout area from note 8.

The  dimensions seem to be ok.
Screenshot from 2019-10-26 14-03-31

**Comment by evanshultz** [comment]
Good points. Thank you. Updated script and footprints.
image
image

**Comment by poeschlr** [comment]
We have a KLC rule detailing how a keepout area is to be drawn. http://www.kicad-pcb.org/libraries/klc/F4.5/ As this is so small i would accept it without hatching. (so only a rectangle) A filled polygon would violate this rule.

**Comment by evanshultz** [comment]
Done.
image

**Comment by poeschlr** [comment]
thanks

**Comment by evanshultz** [comment]
@poeschlr 
Thank you.

I believe the KiCad dev team is smart enough to implement keepouts with polygons once they are supported by PCBnew. As we're left with visual checking for keepouts at this time, a polygon (to me, at least) is easier to notice an overlap than an unfilled area. I'm also not sure if PCBnew supported polygons when the KLC clause was added. So using polygons now means that only the polygon layer has to change once keepouts are supported. Would you consider allowing polygons for keepouts? I can make a PR on the website repo with my first draft update for discussion if you would support this.

**Pull request merged**
