### PR TITLE
TerminalBlock: Add Wuerth 691311400102

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://katalog.we-online.de/en/em/TBL_7_62_3114_CLOSE_VERTICAL_PCB_HEADER_69131140010X/691311400102?m=n&sp=https%3A%2F%2Fwww.we-online.com%2Fweb%2Fen%2Fwuerth_elektronik%2Fsearchpage.php%3Fsearch%3D691311400102&_ga=2.253828047.693015018.1531393119-1957336121.1531393119

https://katalog.we-online.de/em/datasheet/6913114001xx.pdf

imagen

Hand made, I had no time to script this, sorry.
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
"Hand made, I had no time to script this, sorry."
There is always time ^^
Have you changed your mind about the scripting ?

**Comment by antoniovazquezblanco** [comment]
> There is always time ^^

Unfortunately when deadlines are tight I cannot spend time outside my work targets.

>  Have you changed your mind about the scripting ?

If you ask, I am pro scripting clearly, but this one I don't know when I will be able to do.

**Comment by Misca1234** [comment]
I see, 

About your symbol, make a "corner cut" in F.Fab layer at pin 1
(usually the pin 1 marker in F.Fab and F.silk is at upper left corner)

The "inner symbol" should be in F.silk and not in F.Fab

Are yo usure that the "upper" F.Fab should be at 4.7 ?
if the projection is correct in the data sheet, should it not be 3.8 ?

**Comment by antoniovazquezblanco** [comment]
> Are yo usure that the "upper" F.Fab should be at 4.7 ?
if the projection is correct in the data sheet, should it not be 3.8 ?

imagen

1 is shorter than 2 thus 1 is the 3.8 side and 2 is the 8.5-3.8=4.7

I am confused by this datasheet but the manufacturer 3D model seems to back my hypothesis.

imagen
imagen

What do you think?

**Comment by Misca1234** [comment]
jee, the datasheet is not "unfolded" the views as expected, perhaps it is a specific German mechanical tradition.
But if their own 3D model support your assumptions we should go with that

You should use the U-umlaut ('ü' https://en.wikipedia.org/wiki/%C3%9C) in the name.

Otherwise the fp look alright

bild

**Comment by antoniovazquezblanco** [comment]
> jee, the datasheet is not "unfolded" the views as expected, perhaps it is a specific German mechanical tradition.

They are using third angle projection which is traditionally used in the US AFAIK.

imagen

Changed the name.
Thanks @Misca1234

**Comment by antoniovazquezblanco** [comment]
Ping @Misca1234.

Can this be merged?

**Comment by antoniovazquezblanco** [comment]
I am taking the liberty of assigning you @Misca1234 to this PR as you have already done a review of the FP.

**Comment by Misca1234** [comment]
That is al right

**Comment by antoniovazquezblanco** [comment]
Thank you very much

**Comment by Schlumpf** [comment]
Hi,
there is still a mistake with the Umlaut 'ü'. The ASCII replacement for 'ü' is 'ue'. But there is no 'üe'. The correct spelling is 'Würth'.
This rule also affects the other umlauts: 'ä' -> 'ae' and 'ö' -> 'oe'.

PS: To make the list of german letters complete, the eszett (sharp s) has an ASCII replacement, too: 'ß' -> 'ss'

**Comment by antoniovazquezblanco** [comment]
Thanks @Schlumpf. Fix in the following PR: https://github.com/KiCad/kicad-footprints/pull/956

**Pull request merged**
