### PR TITLE
Adding QFN-68-1EP_8x8mm_P0.4mm_EP5.2x5.2mm

### PR DESCRIPTION
**Pull request by ki5libs**
Adding QFN-68-1EP_8x8mm_P0.4mm_EP5.2x5.2mm package
[Datasheet](https://www.mouser.com/ds/2/523/Microsemi_VSC8541-01_Datasheet_10496_V40-1148034.pdf)
qfn-68-1ep_8x8mm_p0 4mm_ep5 2x5 2mm
[3D package PR](https://github.com/KiCad/kicad-packages3D/pull/332)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Would you be mad if i replace some of your pull requests with scripted versions of the same footprints? (Will allow better maintainability later on.)

**Comment by ki5libs** [comment]
No problem, I think. What should I do?

**Comment by poeschlr** [comment]
If everything goes well you will not have anything extra to do. If you are interested i can show you how you can use the same script for future footprints.

**Comment by ki5libs** [comment]
Yeah, sure. It will be very helpful. Thanks.

**Comment by poeschlr** [comment]
Explanation for using my [ipc based footprint generator](https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_DFN_QFN). This generator uses size definition files (yaml format) as input and outputs footprints. 

The size definition for this footprint would look like this.
The only thing that is not directly given in the datasheet is the paste layout definition. I always aim for splitting the paste layer into pads of <1.5x1.5mm >1x1mm. In this case using 4x4 paste pads results in 1.05x1.05mm paste pads with the default 65% coverage.:

``` yaml
QFN-68-1EP_8x8mm_P0.4mm_EP5.2x5.2mm:
  device_type: 'QFN'
  size_source: 'https://cdn.microsemi.com/documents/1bf6886f-5919-4508-a50b-b1dbf3fdf0f4/download/ (page 98)'
  ipc_class: 'qfn' # 'qfn_pull_back'
  body_size_x:
    nominal: 8
    tolerance: 0
  body_size_y:
    nominal: 8
    tolerance: 0
  lead_width_min: 0.15
  lead_width_max: 0.25
  lead_len_min: 0.3
  lead_len_max: 0.5

  EP_size_x_min: 5.1
  EP_size_x: 5.2
  EP_size_x_max: 5.3
  EP_size_y_min: 5.1
  EP_size_y: 5.2
  EP_size_y_max: 5.3
  EP_num_paste_pads: [4, 4]

  pitch: 0.4
  num_pins_x: 17
  num_pins_y: 17
```

For creating a thermal vias version as well one could add something like this:
  ``` yaml
thermal_vias:
    count: [5, 5]
    drill: 0.2
    paste_via_clearance: 0.1
    EP_paste_coverage: 0.6
```

Lets say the size information is stored in `size_definition/qfn-other.yaml`, then the command to run it is `python3 ipc_dfn_qfn_generator.py size_definitions/qfn-other.yaml` 

One can also generate it with square pads instead of using rounded rectangle (useful if you want to check it with freecad stepup or if you want to use the footprint in 4.0.x as both do not support rounded rectangle.) The command line option to add for that is `--force_rectangle_pads` (for other command line options use `--help`)

**Comment by Misca1234** [comment]
@ki5libs 
Your foot print is in this push now
https://github.com/KiCad/kicad-footprints/pull/777

you should remove and delete this push

**Comment by poeschlr** [comment]
Should only be closed once the scripted one is accepted.

**Pull request closed without merging**
