### PR TITLE
Footprint for TDFN-6 2.5x2.5mm Pitch 0.65mm Pad 2.0x1.3mm

### PR DESCRIPTION
**Pull request by TiZed**
Hello,

Added TDFN-6 footprints for two NVE magnetic angle sensors.
Package specs: http://www.nve.com/Downloads/ab3.pdf
Symbols pull request: [KiCad/kicad-symbols#1922](https://github.com/KiCad/kicad-symbols/pull/1922)
3D Model pull request: [KiCad/kicad-packages3D#570](https://github.com/KiCad/kicad-packages3D/pull/570)

image

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Please use our footprint generator script found in https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON to generate footprints for such standardized packages.
The script is run with `python3 ipc_noLead_generator.py size_definitions/dfn.yaml`. Add your parts dimensions to the dfn.yaml. Take one of the other as example.

The definitions can be given as

---

```yaml
parameter_name:
  minimum: 1
  nominal: 2 # only include if listed in datasheet
  maximum: 3
```
Or as
```yaml
parameter_name:
  nominal: 2
  tolerance: 1 # optional as [negative tolerance, positive tolerance] like [-0.5, 0.2] for unsymetric ones
```

---

And there is a new style:

```yaml
parameter_name: 1 .. 2 .. 3 # min..nominal..max
parameter_name: 1 .. 3 # min..max
parameter_name: 2 +/-1 # nominal +/- tolerance
parameter_name: 2 +0.2 -0.1 # nominal with asymetric tolerance
```

**Comment by TiZed** [comment]
Ok, generated the footprints using the script and pushed to the branch.

**Comment by poeschlr** [comment]
Could you link to the script pull request as the review will then mostly happen over there.

**Comment by TiZed** [comment]
Ok, had to setup a fork of kicad-footprint-generator...
Pull request: [pointhi/kicad-footprint-generator#383](https://github.com/pointhi/kicad-footprint-generator/pull/383)

**Comment by poeschlr** [comment]
Looks good, thanks for your contribution.

**Pull request merged**
