### PR TITLE
Add R_Shunt_Otmite_LVK24 4 contacts smd resistor

### PR DESCRIPTION
**Pull request by penoud**
Add R_Shunt_Otmite_LVK24 4 contact resistor
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
https://www.ohmite.com/assets/docs/res_lvk.pdf
- [X] An example screenshot image is very helpful 
image
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
3d filename does not match footprint name

**Comment by penoud** [comment]
Correct the 3d filename

**Comment by penoud** [comment]
Correct the 3d name

**Comment by poeschlr** [comment]
Thanks. For reference the dimensioned drawing
screenshot from 2018-09-02 16-10-16

**Pull request merged**
