### PR TITLE
Added VQFN 48 7x7 mm package

### PR DESCRIPTION
**Pull request by ppielorz**
Added new footprint basen on QFN package.

Screenshot 
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Please include the datasheet here and link to the script update with the new part entry for convenience and faster review. http://www.ti.com/lit/ds/symlink/cc1312r.pdf.

**Comment by evanshultz** [comment]
A couple significant things before we can move on:
1. More than just the VQFN footprint is included here.
1. Include the thermal vias version of the footprint from the generator and well as the non-vias version.
1. Provide a link to the PR for the update to the script so we can check the input from which the footprint was created.
1. Give better commit messages, please.

**Comment by ppielorz** [comment]
Ok I created branch from another, not from master, this is why 1 happened. I will create a new pull request with correct base.
I don't understand your third remark. Which script update?

**Comment by evanshultz** [comment]
3. It appears we are requiring these footprints to use the nice footprint generator on GitHub. See https://github.com/KiCad/kicad-footprints/pull/1423#issuecomment-476326778. You will need a script update PR for that. More info follows in that thread.

**Comment by ppielorz** [comment]
Closing this PR because of wrong branch base.

Opened new: https://github.com/KiCad/kicad-footprints/pull/1542.

**Pull request closed without merging**
