### PR TITLE
Add Murata NCS1 DC/DC converter module

### PR DESCRIPTION
**Pull request by johnbeard**
This footprint fits:

* NCS1S1203SC - 4.5-18V in, 3.3V out
* NCS1S1205SC - 4.5-18V in, 5V out
* NCS1S1212SC - 4.5-18V in, 12V out
* NCS1S2403SC - 9-36V in, 3.3V out
* NCS1S2405SC - 9-36V in, 5V out
* NCS1S2412SC - 9-36V in, 12V out

Datasheet: https://power.murata.com/data/power/ncl/kdc_ncs1.pdf

Footprint screenshot

Notes: 

* The Fab layer is the maximum material condition of the body (i.e. the rectangle outside of which the body cannot be according the data sheet). 
* Silk is slightly outside that so it would be visible even at the limits of the body size and positions allowed. 
* Courtyard is +0.25mm on the MMC.

Symbol PR: https://github.com/KiCad/kicad-symbols/pull/656

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
There are some problems with this footprints dimensions. Example: pin pitch in the footprint is 2.45 instead of 2.54mm. More problems are pointed out in this annotated screenshot of the dimensioned drawing derived from your footprint. ([tutorial for creating such a drawing](https://forum.kicad.info/t/how-to-check-footprint-correctness/9279))

screenshot from 2018-06-16 01-47-12

**Comment by johnbeard** [comment]
The pin pitch is clearly wrong - I must have typo'd 2.45! Thanks for the catch.

For the other dimensions, is it standard to just average the upper and lower bounds in this case to get "nominal"? And then use this on the F_Fab?

If you take the nominal size of the case and use that on the F_Fab layer, then outset by a little to get the F_SilkS outline, the variation in the case position (up to 0.7mm long-wise and 0.65mm cross-wise) could result in invisible silk once assembled.

**Comment by Ratfink** [comment]
The name should say `Murata`, not `muRata`: see https://github.com/KiCad/kicad-footprints/issues/545.

**Comment by johnbeard** [comment]
@ratfink OK, I'll change that too. 

@poeschlr Can you advise on where the silkscreen box and courtyard should go? Outset from nominal, or where it currently is, outset from the maximum variation for the case position?

**Comment by johnbeard** [comment]
Also for IPC B pad sizes: should that now be 1.075 + 0.1 + 0.5mm = 1.675? Or use the minimum hole from the datasheet -> 1.6?

**Comment by poeschlr** [comment]
If you use IPC you need to start at the lead sizes not at the suggested hole.
So it would be maximum lead diameter + 0.2 = 0.65 + 0.2 = 0.85 (rounded to nearest 0.05)
screenshot from 2018-06-21 13-00-25

from that i would say the suggested hole diameter is quite large. The question would now be why. (Does muarta know something they do not tell us?)

**Comment by johnbeard** [comment]
I imagine it's to accommodate the pin position variance?

From the datasheet: "All pins on a 2.54 (0.100) pitch and within 0.25 (0.010) of true position."

**Comment by poeschlr** [comment]
Regarding your previous question: we draw the fab outline after the nominal measurements for all our parts. (And therefore also the silk and courtyard.)

In your case using everything as max tolerance might still result in parts being outside that area. (if the side to pin is at minimum for example.)

---

regarding drill: well with the tolerance for the pin position we would arrive at 1mm drill size. (or maybe a bit less if we use root mean square error addition.)

**Comment by Misca1234** [comment]
This push has been overtaken
https://github.com/KiCad/kicad-footprints/pull/1044

**Pull request closed without merging**
