### PR TITLE
Added Sipeed M1

### PR DESCRIPTION
**Pull request by iommu**
Added Sipeed M1 module ([As seen here](https://www.seeedstudio.com/Sipeed-MAIX-I-module-WiFi-version-1st-RISC-V-64-AI-Module-K210-inside-p-3206.html))

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [datasheet](http://dl.sipeed.com/MAIX/Specifications(PDF)/Sipeed%20M1%20Specifications_EN%20V1.1.pdf) 
- screenshot 
image

- [symbol pull request](https://github.com/KiCad/kicad-symbols/pull/1837)

### CODE REVIEW

**Comment by jneiva08** [comment]
Hi,
You will need to rotate ccw the footprint, because the pin 1 needs to be in upper left corner like [KLC 4.2](http://kicad-pcb.org/libraries/klc/F4.2/).

**Comment by iommu** [comment]
Hi jneiva08, done! 
image
new screenshot

**Comment by jneiva08** [comment]
Need to remove the F.Fab is top of F.CrtYd
F.CrtYd should be 0.25mm from edg of pins
Probably the pins can be Rounded Rectangle
The F.Fab should mark the actual size of the module (25.4x25.4mm)

Where can find the size of the pins?

**Comment by iommu** [comment]
Updated footprints with requested updates
image
And I was told to find the footprint sizes from measuring their their assembly drawing found here
http://dl.sipeed.com/MAIX/HDK/Maix-Dock/Maix-Dock_11.27/Maix-Dock_11.27%28TOP%20Assembly%20drawing%29.pdf
It's a but crude but I later checked what I measured against measuring the footprints on their specification sheet PDF and they showed comparable sizes

**Comment by poeschlr** [comment]
I get a file not found error message for your datasheet linked above

**Comment by iommu** [comment]
Yes they changed their url for the datasheet I've updated it in the schematic symbol 

http://dl.sipeed.com/MAIX/HDK/M1%26M1W/Specifications/Sipeed%20M1%20Specifications_EN%20V1.1.pdf

here the new url

**Comment by poeschlr** [comment]
The datasheet link seems to have changed again: http://dl.sipeed.com/MAIX/HDK/M1&M1W/Specifications/Sipeed%20M1W%20Datasheet%20V1.11.pdf

It seems that the pin table updated in this version. 

Also something went wrong with this pull request. There are no changed files.

**Comment by myfreescalewebpage** [comment]
@iommu ping, are you still alive on this subject ? Please check last comment of @poeschlr

**Comment by iommu** [comment]
Hi yeah sorry I decided to wait a bit with this because sipeed seems to be very temperamental with their hosting for this project and keeps changing the URL of where they host the .pdf. At current it resides under the URL https://dl.sipeed.com/MAIX/HDK/Sipeed-M1&M1W/Specifications but their file hosting solution doesn't allow me to dirrectly link to the pdf, is that ok?

[Also they uploaded official KiCad libraries](https://dl.sipeed.com/MAIX/HDK/Sipeed-M1&M1W/History/M1&M1W_11.13/Kicad_lib) which made this little less necessary.

**Comment by myfreescalewebpage** [comment]
https://dl.sipeed.com/MAIX/HDK/Sipeed-M1&M1W/Specifications is accepted in this case.
So do you want to continue working on this subject to have the device in the official library or are you using their KiCad definition ? (this is to update the status of this PR)

**Comment by iommu** [comment]
So i've updated the datasheet URL in the symbols repo and I fixed the mistake I made with the pull request. Hopefully everything should be good now :)

**Comment by myfreescalewebpage** [comment]
@poeschlr do you want to continue on this PR ? I can help if required

**Comment by poeschlr** [comment]
In general i allow you (and everyone else) to take over any of the pull requests i have assigned to me. I am going to help out with reviews if i find time but lately life seams to be determined to ensure i don't find any.

**Comment by myfreescalewebpage** [comment]
@iommu continue/restart review from this point:

- [ ] Datasheet link should be added to the description
- [ ] How have you chosen size of pin 1 to 72 ?
- [ ] How have you chosen the offset value between the border of thz package and the center of the pins ?
- [ ] F.Fab: pin 1 marker should be added, you can have the corner at 45° for example
- [ ] F.SilkS: we usually use clearance value of 0.11mm from F.Fab (and 0.2mm clearance from the pad). The silkscreen lines on your footprint have 4 decimal digits, which is too much. If you use 0.11mm offset from F.Fab this will round this
- [ ] Pin 73: I have computed position X = -6,135
- [ ] Pin 74: I have computed position X = 7.65
- [ ] Pin 73 and 74: this is a lot of Paste actually, I suggest to have 4 plots of Paste for this pins, as we do for expose pads on many footprints
- [ ] How do you know numbering and size of pin 75-77 ?
- [ ] Seems a pad is missing in the top left corner between pin 1 and pin 72

Joel

**Comment by iommu** [comment]
1. Datasheet link added
2. It was a year ago now but from memory I used the values from an image in the spec sheet as well as extrapolating from vector of a silk screen. These values were not far off but with an official kicad_mod now available they have now been updated to the official values 
See image
image
3. See 2
4. Added marker
5. Unsure what you mean
6. Fixed
7. Fixed
8. Do you mean something like this? I'm having trouble finding another footprint to reference what you mean e.g. the esp32 has a much larger paste area
image
9. See 2
10. This pad while physically on the board and hence in the spec isn't actually on any of the official footprints (including the official KiCad one) those pins 73-77 aren't documented of used for any general projects either

**Comment by myfreescalewebpage** [comment]
@iommu thanks for this detailed feedback. Few comments:

- [ ] F.Fab: the corner near pin 1 should just be a corner, like that:

Capture

- [ ] Paste: not in the corner, but you can look at any QFN/SOIC/QFP/etc with Expose Pad package, for example "QFN-12-1EP_3x3mm_P0.5mm_EP1.6x1.6mm".

Cu layer:
cu

Paste layer:
paste

All the other subject OK now.
Joel

**Comment by iommu** [comment]
Fixed F.Fab and added F.Paste pads
image

**Comment by myfreescalewebpage** [comment]
Very nice :) My last comment:

- [ ] F.CrtYd lines should leave an offset of 0.25mm from the package, actually it's too much closed to the pads.

Joel

**Comment by iommu** [comment]
Ah! Sorry must have missed that part of the comment. Fixed now :)
image
I'm assuming you wanted .25mm to the centre of the CrtYd line as well as that it what I found in other footprints

**Comment by myfreescalewebpage** [comment]
Yes exactly. No more comment, great job done here, merging your contribution!

**Pull request merged**
