### PR TITLE
Add Lattice 381-ball 0.8mm pitch caBGA footprint.

### PR DESCRIPTION
**Pull request by awygle**
This adds the caBGA-381 (BG381) footprint for Lattice ECP5 FPGAs. Documentation found at http://www.latticesemi.com/view_document?document_id=213

image
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by awygle** [comment]
Symbol PR is https://github.com/KiCad/kicad-symbols/pull/903

**Comment by Misca1234** [comment]
@awygle 
This one is begging for being made by scripts, will you give it a shoot ?

**Comment by poeschlr** [comment]
@awygle is this footprint the same that is generated in this script? https://github.com/pointhi/kicad-footprint-generator/pull/253

**Comment by awygle** [comment]
It's not, but I plan to update it to be that one. I wanted to make sure the generator script was OK before I updated this pull request, since I haven't done any generator PRs before.

**Comment by poeschlr** [comment]
A lot of the review will depend on seeing a footprint. We could of course checkout the script repo, generate the footprint for our self and make a review based on that but that will only increase our workload. So please add the footprint as it is generated by the script plus a screenshot here.

**Comment by awygle** [comment]
Done. Here are screenshots of the SMD and NSMD variant.

SMD:
image

NSMD:
image

**Pull request merged**
