### PR TITLE
ESP32-S2-WROVER: Added keepout on DWGS layer for espressif recommende…

### PR DESCRIPTION
**Pull request by chmorgan**
…d clearance of 15mm. Removed tick lines. Move courtyard around clearance area.

Figure 13 in https://www.espressif.com/sites/default/files/documentation/esp32_hardware_design_guidelines_en.pdf shows clearance drawing

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chmorgan** [comment]
@cpresser I left the pin 1 indication as moving the fab indication would shift the courtyard out and moving the pin 1 silk indicator in would result in the silk being partially under the footprint which would cause unevenness as this is an smt component. Otherwise I think everything else was addressed here.

**Comment by cpresser** [comment]
How about that?
- Keep-out also under the antenna
- Pin1 and Silkscreen as `ESP32-WROOM-32` 

image

**Comment by chmorgan** [comment]
@cpresser can you re-review?

**Comment by cpresser** [comment]
I checked again,
but I don't see consistency between `ESP32-S2-WROVER` and `ESP32-WROOM-32`.
The later has silkscreen not only on the edges, but all around the antenna part. And the chevron on F.Fab looks different.

**Comment by chmorgan** [comment]
Hi @cpresser. I can add that silk around the edges but imo the triangle is a bit easier to spot visually so I went that way vs. consistent but less clear with the other parts.

**Comment by chmorgan** [comment]
@cpresser I was initially going to push back a bit as I think we should get fixes into the library as long as they are moving in the right direction. In any case I decided to copy the pin 1 indicator from one of the other parts and correct the upper silk. I did leave the fab line for the antenna as that could be a helpful visual indication.

**Pull request merged**
