### PR TITLE
Murata LQH55DN inductor footprint

### PR DESCRIPTION
**Pull request by evanshultz**
https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-0045.pdf

image

I measured the bottom section's height right at 4mm, so I included that into the fab lines. However, I just took the overall 5.7x5mm rectangle for the silk lines.

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Should we possibly include the body size as a suffix as documented in the KLC? (I know we do not do it for other inductors right now but i fear this is simply an oversight from version 4 to 5 reorg.)

**Comment by evanshultz** [comment]
Sure! Can you point me to where this is mentioned in KLC? I don't see any section specific for inductor footprints and searching the term "inductor" only turns up one hit in the symbol section.

Are you suggesting `L_Murata_LQH55DN_5.7x5.0mm`?

**Comment by evanshultz** [comment]
@poeschlr 
Added body size as I wrote above. Please advise if this is not what you intended.

**Comment by poeschlr** [comment]
looks good, thanks

**Pull request merged**
