### PR TITLE
add Mini-Circuits DB1627

### PR DESCRIPTION
**Pull request by lorem-ipsum**
[Datasheet](https://ww2.minicircuits.com/case_style/DB1627.pdf).

Screenshot_20190802_155924

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
The generator you used is for no no-lead packages. Your package has leads. I think you will need to make this footprint manually as I don't believe we have a generator for this package type.

**Comment by lorem-ipsum** [comment]
meh, you're right. I viewed the bottom as a continuous plane, but then looking closely one can see the leads. Will build it manually off the Mini-Circuits land pattern.

**Comment by evanshultz** [comment]
I removed the script PR from the first post since it's not valid any longer.

1. Clean up the description and keywords so they're not the now-irrelevant script-generated ones.
1. You rounded the courtyard width up to get it on grid, so the height should change to +/-2.67mm. Or math has failed me.

Can you also post a new screenshot?

**Comment by lorem-ipsum** [comment]
Updated the description and fixed the courtyard. Checked the numbers again, you're right.
Screenshot_20190808_101558

**Comment by evanshultz** [comment]
Thank you once again!

**Pull request merged**
