### PR TITLE
WDFN-8-1EP_6x5mm_P1.27_EP4x3.4mm added.

### PR DESCRIPTION
**Pull request by serkanxselcuk**
WDFN-8-1EP_6x8mm_P1.27mm_EP6x4.8mm_ThermalPad added.

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/8L_WDFN_5x6mm_MF_C04210B.pdf
3D: ${KISYS3DMOD}/Package_DFN_QFN.3dshapes/DFN-8-1EP_6x5mm_Pitch1.27mm.wrl
image

image
image
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by serkanxselcuk** [comment]
I will serve SST26VFxxxB symbol soon.

**Comment by serkanxselcuk** [comment]
Datasheet:
image
image
image

Foorprint:
image

**Comment by poeschlr** [comment]
Footprints for standardized packages like these must be generated via our IPC footprint generators found here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by serkanxselcuk** [comment]
@poeschlr 
Hello Rene,
thanks for your tip. I generated this footprint using script you described above.

Kind Regards.

**Comment by poeschlr** [comment]
Please make a pull request on the script repo and link to it from here. The review happens on the script.

**Comment by myfreescalewebpage** [comment]
Symbol is Abandoned

**Comment by serkanxselcuk** [comment]
Hi @myfreescalewebpage ,
where is script repo? I couldn't find it on kicad's github repositories.

**Comment by myfreescalewebpage** [comment]
It's not on the kicad repos, it's at https://github.com/pointhi/kicad-footprint-generator/

**Comment by serkanxselcuk** [comment]
Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/647

**Comment by myfreescalewebpage** [comment]
Thanks, can you update the footprint file on this pull request with the one generated by the script ?

**Comment by serkanxselcuk** [comment]
Done

**Comment by myfreescalewebpage** [comment]
No comment, merging.

**Pull request merged**
