### PR TITLE
Wuerth WP-THRBU REDCUBE THR connectors

### PR DESCRIPTION
**Pull request by rleh**
Connector: Add Wuerth WP-THRBU REDCUBE THR connectors

Redcube THR overview: https://www.we-online.de/katalog/de/em/redcube_terminals/redcube_thr/

| Datasheet      | Screenshot  |
|--------------------|---|
|  [WP-THRBU 74650073](https://www.we-online.de/katalog/datasheet/74650073.pdf) | image  |
|  [WP-THRBU 74650074](https://www.we-online.de/katalog/datasheet/74650074.pdf) | image  |
|  [WP-THRBU 74650094](https://www.we-online.de/katalog/datasheet/74650094.pdf) | image  |
|  [WP-THRBU 74650173](https://www.we-online.de/katalog/datasheet/74650173.pdf) | image  |
|  [WP-THRBU 74650174](https://www.we-online.de/katalog/datasheet/74650174.pdf) | image  |
|  [WP-THRBU 74650194](https://www.we-online.de/katalog/datasheet/74650194.pdf) | image  |
|  [WP-THRBU 74650195](https://www.we-online.de/katalog/datasheet/74650195.pdf) | image  |
|  [WP-THRBU 74655095](https://www.we-online.de/katalog/datasheet/74655095.pdf) | image  |
|  [WP-THRSH 74651173](https://www.we-online.de/katalog/datasheet/74651173.pdf) | image  |
|  [WP-THRSH 74651174](https://www.we-online.de/katalog/datasheet/74651174.pdf) | image  |
|  [WP-THRSH 74651175](https://www.we-online.de/katalog/datasheet/74651175.pdf) | image  |
|  [WP-THRSH 74651194](https://www.we-online.de/katalog/datasheet/74651194.pdf) | image  |
|  [WP-THRSH 74651195](https://www.we-online.de/katalog/datasheet/74651195.pdf) | image  |

- [x] Datasheet: See table above
- [x] Screenshot: See table above
- [x] Currently no matching 3d model available
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] ~~Give a reason behind any intentional library convention rule violation.~~ No violations!

---

The footprint is of the THR (Through Hole Reflow) type and is therefore designated as a "surface mount" component because it has solder-paste pads and is usually assembled together with the other SMT components.

Unfortunately I have not found a single THR Footprint in KiCad so far, there seems to be no reference how THR components are handled.
Also in the KLC the topic is not mentioned.

---
The "non plated through-hole" has no diameter specified in the datasheet. I chose the "close fit" clearance hole minimum diameters for the connector thread size according to DIN/ISO norm (3.2mm for M3, 4.3mm for M4, 5.3mm for M5).

grafik

### CODE REVIEW

**Comment by chschlue** [comment]
> The footprint is of the THR (Through Hole Reflow) type and is therefore designated as a "surface mount" component because it has solder-paste pads and is usually assembled together with the other SMT components.
> 
> Unfortunately I have not found a single THR Footprint in KiCad so far, there seems to be no reference how THR components are handled.
> Also in the KLC the topic is not mentioned.

Looks like no one asked for THR before...
However, while this "hack" seems to do what it's supposed to, we may want an actual THR fab attribute for footprints in the future so those can have special paste reduction and such.
For now, an explicit paste layer following Würth's stencil recommendations might be a better solution [RFC].
@KiCad/librarians

**Comment by cpresser** [comment]
We actually have other THR parts already in the lib. A few can be found in `Connector_USB`. For example `USB_Micro-B_Amphenol_10103594-0001LF_Horizontal`

**Comment by chschlue** [comment]
Don't know what I was doing there... @rleh's FPs have explicit paste pads...

@cpresser Your example doesn't. There's no paste on the annular rings if used out-of-the-box.

**Comment by cpresser** [comment]
This looks like paste to me: 
image

**Comment by chschlue** [comment]
The gray parts do.
The yellow parts look like missing paste to me ;)

I can't image there will be enough paste to plug the hole that way.

**Comment by cpresser** [comment]
We are quite OT now.
In my experience that is enough paste.
I did not make this Footprint, but am using it at work. Assembly and soldering on a professional SMT-Line somewhere in poland. The soldering result is pretty good. So far no customer has managed to break the usb-plug.

**Comment by chschlue** [comment]
OK.
We may still want to give special consideration to THR components.

The commits adding that USB connector (https://github.com/KiCad/kicad-footprints/commits/master/Connector_USB.pretty/USB_Micro-B_Amphenol_10103594-0001LF_Horizontal.kicad_mod) look like it just happens to work by chance.

**Comment by rleh** [comment]
Thanks @cpresser for pointing out the Amphenol 10103594-0001LF THR footprint.
The only `grep -R`-able THR footprint is `TerminalBlock_Phoenix_PTSM-*-THR_`*, but that is just THT and has no paste layer at all.

On the REDCUBE footprints SMD type pads for paste are only on layer {*None*, F.Paste}.
Amphenol 10103594-0001LF has SMD type pads for paste on layers {F.Cu, F.Paste, F.Mask}.

I can't find anything in the KLC that says that.
Do you want me to change it?

**Comment by chschlue** [comment]
No. This PR looks fine, basically. Disregard at least half of my first comment.

I'm just arguing that we should probably codify what's supposed to be done with THR footprints.
The examples above seem to support that. Amphenol... apparently works, Phoenix_PTSM... obviously won't, both don't seem to be flagship examples of a nice, clean, well thought out footprint library.

@cpresser is correct that this isn't the right place for this discussion, of course.

**Comment by rleh** [comment]
Three more questions:
- It might be useful to add `REDCUBE THR` to the footprint name.
  - e.g. `Wuerth_REDCUBE-THR_WP-THRBU_74650073_THR`
  - or `Wuerth_REDCUBE-THR_WP-THRBU_74650073` (without `_THR` suffix)?
- Part 74650173 and 74650174 have an identical footprint: `Wuerth_WP-THRBU_7465017x_THR`. But the 3D model has slight differences (M3 vs. M4 thread). Should I duplicate the footprint?
- The footprints are identical for the [WP-THRSH](https://www.we-online.de/katalog/de/WP-THRSH/) components, but of course with different 3D models. I would also like to add the WP-THRSH parts (in this PR?). For this I have to duplicate the footprints, right?

**Comment by chschlue** [comment]
> * It might be useful to add `REDCUBE THR` to the footprint name.
>   
>   * e.g. `Wuerth_REDCUBE-THR_WP-THRBU_74650073_THR`
>   * or `Wuerth_REDCUBE-THR_WP-THRBU_74650073` (without `_THR` suffix)?

`_THR` suffix seems reasonable to me as that's not necessarily apparent from the MPN (see Wago THR terminal blocks for example.

> * Part 74650173 and 74650174 have an identical footprint: `Wuerth_WP-THRBU_7465017x_THR`. But the 3D model has slight differences (M3 vs. M4 thread). Should I duplicate the footprint?

Yes.

> * The footprints are identical for the [WP-THRSH](https://www.we-online.de/katalog/de/WP-THRSH/) components, but of course with different 3D models. I would also like to add the WP-THRSH parts (in this PR?). For this I have to duplicate the footprints, right?

Right.

**Comment by rleh** [comment]
@chschlue I duplicated the non-unique footprints and added all missing footprints from the whole Würth Electronik Redcube THR series.

**Comment by rleh** [comment]
@chschlue Thanks for reviewing!

I moved the footprints to (newly created) `TerminalBlock_Wuerth` lib.

**Pull request merged**
