### PR TITLE
add VSSOP-10 0.5mm pin pitch

### PR DESCRIPTION
**Pull request by penoud**
add VSSOP-10_3x3mm_P0.5mm pin pitch. Reference datasheet in following survey. 
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
http://www.ti.com/lit/ds/symlink/ads1115.pdf
- [X] An example screenshot image is very helpful 
image
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
https://github.com/KiCad/kicad-packages3D/pull/392
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by penoud** [comment]
Should I move the footprint or the 3d models. The footprints created with the script generator for Kicad place the 3d models in the folder named Package_SSOP.3dshapes. But the previous VSSOP-8 in the footprint were placed in the library Package_SO.pretty.

**Comment by Misca1234** [comment]
Do you have the link to the script that made the foot print ?

**Comment by penoud** [comment]
I didn't find the script. I've done a new one. Here the link to the PR
https://github.com/pointhi/kicad-footprint-generator/pull/209
Updated screenshoot:
image

**Comment by Misca1234** [comment]
> I reduced manually the font size from 0.75 to 0.65 for REF** after script generation.

Don't do that, we trust the script 100%, so just accept what ever the script output.

Of course there is an exception to this, and that if you find something that is wrong, 
then you should bring up the issue and the script can be corrected, try to avoid to "hand fix" them afterwards.

The reason is that if we find an error in the script later on re generate all the foot prints, and this foot print is not affected by the error, the script should produce a foot print equal to the one have been merged.

**Comment by penoud** [comment]
Ok make sense. 
I revert to original font size:
image

**Comment by poeschlr** [comment]
Why is the second reference on the bottom fab layer instead of the top one?

If you used the ipc scripts could you post the relevant section of the size definition yaml file here?

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
