### PR TITLE
Footprint for WDFN-12 3x3mm

### PR DESCRIPTION
**Pull request by jneiva08**
Added footprint for WDFN-12-1EP_3x3mm_P0.45mm_EP1.7x2.5mm 

Datasheet: https://www.diodes.com/assets/Datasheets/PAM2306.pdf

Footprint:
footprint

This PR for the symbol [#657](https://github.com/KiCad/kicad-symbols/pull/657)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
According to 
https://www.diodes.com/assets/Datasheets/PAM2306.pdf
Page 14, lower part "Suggested Pad Layout"

It says the pads 1-12 should be 1x0.25 large, but pad 13 is slightly larger, is it bigger due to discussions elsewhere where the pad size should be as large as the maximum tolerance of the pad on the component ?

Behind pad 13 you should add two "pads", like this 
bild

**Comment by jneiva08** [comment]
Added F.Fab line to indicated pin 1,
Added 2 pads for F.Paste.

f paste

Hope the size o pad is adequate.

3d

**Comment by poeschlr** [comment]
I might be able to script this if @jneiva08 is ok with it.

**Comment by jneiva08** [comment]
for me, you can put in script.

**Comment by Misca1234** [comment]
@jneiva08  
Your foot print is in this push now
https://github.com/KiCad/kicad-footprints/pull/778

you should remove and delete this push

**Comment by poeschlr** [comment]
Should only be closed once the scripted one is accepted.

**Pull request closed without merging**
