### PR TITLE
Add Lumex SML-LX0404SIUPGUSB

### PR DESCRIPTION
**Pull request by 0xdec**
Add Lumex SML-LX0404SIUPGUSB (big sibling to #1990)

[Datasheet](https://www.lumex.com/spec/SML-LX0404SIUPGUSB.pdf)

LED_Lumex_SML-LX0404SIUPGUSB

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Hi,
it looks like the silkscreen between the pads might violate KLC F5.1 (0.2mm clearance silk to pad)
Did you try to fit the F.Fab refdes into the body?

**Comment by poeschlr** [comment]
We allow smaller silk clearances for small parts like these. (The lowest allowable is clearance equal to line width.)

**Comment by 0xdec** [comment]
@cpresser it's a bit smaller bc otherwise basically no silkscreen would fit. And yeah the refdes really has no hope of fitting inside the outline.

**Comment by evanshultz** [comment]
1. Add the official datasheet at https://www.lumex.com/spec/SML-LX0404SIUPGUSB.pdf to the description.
1. The courtyard is too small. It should be a 0.9mm square.
1. No silk will fit between pads. Pads 1 and 2 are 0.4mm apart. 0.12mm clearance requires a line end 0.18mm away to account for the line endcap. That means a line length of 0.04mm. No way.
1. Similarly, the pin 1 silk lines need to be 0.83mm away from the origin and they are only 0.8mm now.

@poeschlr 
Why is text limited to 0.5mm and not smaller? If the assy layer is printed to PDF, and I'm not sure what else it's used for, vector text can be zoomed without a problem. If printed on paper, even 0.5mm could be a problem.

**Comment by 0xdec** [comment]
@evanshultz fixed all 4 points

**Comment by evanshultz** [comment]
The silk is at 0.825 instead of 0.83 as it should be.  Practically, that won't make any difference.

And as I found at https://github.com/KiCad/kicad-footprints/pull/1522#issuecomment-701053128, fab ref des are smaller on some parts. But this is OK with me.

**Pull request merged**
