### PR TITLE
Adding BGA-121 package pitch 0.8mm for PIC24

### PR DESCRIPTION
**Pull request by ajmv**
*Replace this line with your commit message! Please provide a description of your pull request*

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
@ajmv 
Thanks for contributing to KiCad!

Please read the 4 checkboxes above, none of which are done.
1. I suspect the relevant datasheet is at http://ww1.microchip.com/downloads/en/DeviceDoc/39969b.pdf, based on item 3 below.
1. Please add the screenshot.
1. Neither of those are done, but I suspect this footprint is to go with your symbol PR at https://github.com/KiCad/kicad-symbols/pull/383.
1. Our check scripts found a number of issues. It will be easier to review this if you can fix those issues first.

Please comment here if you have questions. I'll let you absorb the above instead of reviewing now.

**Comment by Shackmeister** [comment]
hi @ajmv 
Are you planning on coming back to this PR? :)
Please let us know if you need help with anything, we are more than happy to help out

**Comment by Misca1234** [comment]
@ajmv 
This foot print is easily done with scripts, do you want me to make it with scripts ?

**Comment by Shackmeister** [comment]
@Misca1234 that would be great :)

**Comment by Misca1234** [comment]
@ajmv 
I have made your foot print with help of scripts, it is named 
TFBGA-121_10x10mm_Layout11x11_P0.8mm

and can be found here
https://github.com/KiCad/kicad-footprints/pull/1013

**Pull request closed without merging**
