### PR TITLE
Add SON-8_2x1.5 footprint

### PR DESCRIPTION
**Pull request by sudhi345**
Add SON-8_2x1.5 footprint
This adds footprint for the TPS62840DLC by Texas Instruments.

---

- [ ] URL to the [datasheet](http://www.ti.com/lit/ds/symlink/tps62840.pdf) for the footprint.
Screenshot from 2019-10-06 10-17-14 
- [ ] An example screenshot image
- [ ] There are [matching symbols](https://github.com/KiCad/kicad-symbols/pull/2153).

### CODE REVIEW

**Comment by cpresser** [comment]
Hi and thanks for you contribution.
This looks like a part that can be generated by one of the IPC footprint generators.
You just have to specify the package in .yaml format and it will be build automatically.
See https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

That has two major advantages:
- The review is simple because we only need to look at the .yaml file
- If the IPC standard or other KLC rules changes we can just regenerate the footprint

**Comment by sudhi345** [comment]
OK. How am I supposed to add that script now? Or shall I close this request and make new one?

**Comment by cpresser** [comment]
Quick workflow:
- Clone the https://github.com/pointhi/kicad-footprint-generator repository
- Find the correct generator (Package_NoLead...)
- Find the .yaml file that contain the package description
- Add your part to that .yaml file
- Run the generator
- Add the output file into this branch and push it here
- Open a PR in the kicad-footprint-generator repository for you changes to the .yaml
- Add a link to that PR into this PR

**Comment by poeschlr** [comment]
A very detailed documentation of a **similar** generator is found here https://github.com/pointhi/kicad-footprint-generator/blob/fd49e97211c88b5d48f9339f3a73c646f24b1cd1/scripts/Packages/Package_Gullwing__QFP_SOIC_SO/Readme.md (Not yet merged into the main repo as it is missing the ok by the reviewer)

**Comment by sudhi345** [comment]
Thanks for your help. 
Here is the [link to the PR](https://github.com/pointhi/kicad-footprint-generator/pull/428) on kicad-footprint-generator

**Comment by sudhi345** [comment]
I made mistakes and reverted the changes. But The Travis CI is taking wrong SHA range. I mean other changes were not made by me. Why?
Thanks.

**Comment by poeschlr** [comment]
https://github.com/KiCad/kicad-library-utils/issues/302

**Comment by sudhi345** [comment]
Made changes according to the scripted FP.

**Comment by poeschlr** [comment]
why does this change so many footprints?

**Comment by sudhi345** [comment]
You mean closing this PR and opening a new one?

**Comment by chschlue** [comment]
Or try reverting https://github.com/KiCad/kicad-footprints/pull/1855/commits/2961f357daafda85a9246fdffa55bea5582e1d77

**Comment by poeschlr** [comment]
To be honest i would suggest closing this one and starting new. While it is possible to rescue a branch it is most likely more work and also error prone compared to making a new one. Especially as the main work contributed here is in the script anyways. (so simply regenerate the footprint and copy it into a new branch and then open a new pull request for that branch)

**Comment by sudhi345** [comment]
OK. Thank you.

**Comment by chschlue** [comment]
@sudhi345 
Your fork will stay at the commit you forked from unless you actively add commits or pull from upstream. This can lead to conflicts when PRs age, however, in case of FP additions it usually doesn't because every footprint is in its own file.

PR branches sometimes have to be updated manually to able to be merged with master, but please only do this when a PR is otherwise ready to be merged. Lots of merge commits in a PR just make it harder to review the actual changes (and can even result in a complete mess as in this case here).

Perhaps the last paragraph should be added to the guildelines for contributors.

**Comment by poeschlr** [comment]
A forked repo does not automatically sync up with it source. To do that you will need to add the original repo as a second upstream repo and pull from it.

**Pull request closed without merging**
