### PR TITLE
Mini-Circuits BK377 plain footprint

### PR DESCRIPTION
**Pull request by aewallin**
https://ww2.minicircuits.com/case_style/BK276.pdf

Discussion in #1308
- remove GND-vias, GND-zones, 
- remove clearance-values
- all pad-connections to "from parent footprint" (not "solid")
- new 0.25mm courtyard.
- parent footprint was reviewed in #1126

bk377

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I would suggest to move the min circuits packages into their own library. I think only a few have been part of the library before you added many of them recently. So they have never been part of a release and we should be free to move them.

My reasoning is that these are really not fitting to the SO lib that i would see as a library for gullwing lead style parts.

My suggestion would be to create a `Package_MiniCircuits` library specifically for these specialized footprints.

We can either decide to do this after this one has merged or you already place these into the new lib and we move the rest afterwards.
I would however suggest that you align all your still open symbol pull requests to fit that or at least make a note about the future move such that we do not create a problem for us later.

More details see https://github.com/KiCad/kicad-footprints/issues/1249

**Comment by aewallin** [comment]
OK, I guess creating a new library is just:
- move the files with "git mv" into a new directory
- update fp-lib-table to include the new library
- somehow (how?) figure out which symbols use the moved footprints - so the symbols can be flagged for updating the library

**Comment by poeschlr** [comment]
> somehow (how?) figure out which symbols use the moved footprints - so the symbols can be flagged for updating the library

a good text editor should do the trick. (one that can search a full directory. Example atom https://atom.io/)
Meaning it is quite easy to find out for stuff that is already in the library. But open pull requests are harder. Here i assume that you are the only one currently relying on the footprints you added very recently. I would further assume that you only have one footprint open right now that would be affected: https://github.com/KiCad/kicad-symbols/pull/1223

---

For the parts that where already in the lib by tag 5.0.2 (So the ones before you added many more)
- Mini-Circuits_CD541_H2.08mm (Not used)
- Mini-Circuits_CD542_H2.84mm -> used in the transformer lib
- Mini-Circuits_CD636_H4.11mm -> used in the transformer lib
- Mini-Circuits_CD637_H5.23mm -> used in the transformer lib

---

Another way of searching is by using `Package_SO:Mini-Circuits`. This results in the following:
- 1 symbol in the oszillator library
- 13 symbols in the transformer library.
- 14 symbols in the rf library

---

An alternative to having a manufacturer specific lib (which would not really fit the rest of the kicad library organization) would be to move the mini circuits stuff into the oszilator lib, the rf lib (new library but also already needed for another contribution) and transformer lib (also a new one).

**Comment by aewallin** [comment]
- I don't have any strong opinion on the organization - someone with a better overview can decide on the libraries/directories and I'll try to adapt.
- Yes the ones that are open now are this one (BK377) and symbol https://github.com/KiCad/kicad-symbols/pull/1223
- if there's a schedule for the next release then it's good to know about it asap.

**Comment by poeschlr** [comment]
The footprint looks good. Lets leave the reorganization for after you finished #1308

**Pull request merged**
