### PR TITLE
Add two more SMD solder wire pads

### PR DESCRIPTION
**Pull request by aurel32**
This adds two more SMD solder wire pads of size 3x6mm and 4x8mm, based on the existing 5x10mm one. The aspect ratio is the same.

screenshot_20180918_152923
screenshot_20180918_152848

They violate KLC rules F6.1 and F9.3, but that's also the case of the original 5x10mm pad and it seems normal not to provide a 3D model for a pad:

```
Checking footprint 'SolderWirePad_1x01_SMD_5x10mm':
  Violating F6.1
    For surface-mount devices, placement type must be set to "Surface Mount"
    Footprint placement type set to 'virtual' - ensure this is correct!
  Violating F9.3
    3D model settings
    No 3D model provided for virtual component
```

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
Hi I can see this has both a virtual and an SMD attribute. Did you modify this file manually? It should only have one

**Comment by aurel32** [comment]
@Shackmeister , I tried to minimize as much as possible the difference with `SolderWirePad_1x01_SMD_5x10mm.kicad_mod` that I used as a reference. It also has both virtual and SMD attributes. I guess the virtual one should be removed, correct?

**Comment by serkanxselcuk** [comment]
@aurel32,
>I guess the virtual one should be removed, correct?

I would make it virtual, when I think of pick&place automtion and BOM.

**Comment by aurel32** [comment]
I have just pushed a new version dropping the smd attribute from SolderWirePad_1x01_SMD_5x10mm and also from the 2 newly added ones.

**Comment by Shackmeister** [comment]
please rotate the fab refdes to fit inside the pad.
also the silk designer should be outside the pad

**Comment by evanshultz** [comment]
The silk refdes should also avoid the copper so move it up.

In the keywords and description there are extra spaces, missing spaces, extra commas, and a typo of "measurement".

**Comment by aurel32** [comment]
I do not need this anymore, therefore closing the bug.

**Pull request closed without merging**
