### PR TITLE
Add Diodes SOT-553

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.diodes.com/assets/Package-Files/SOT553.pdf

footprint

dsot553

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
You should make the pads as rounded rectangles

bild

**Comment by Misca1234** [comment]
Great thanks

**Comment by evanshultz** [comment]
Why was this a manufacturer-specific footprint? It's a standard footprint and should have the `Diodes_` prefix. This is a sticking point for merging https://github.com/KiCad/kicad-symbols/pull/1048.

**Comment by Misca1234** [comment]
There is already a SOT-553 in the library that is slightly different

**Comment by evanshultz** [comment]
The existing SOT-553 footprint has no documentation so we have no idea where it came from or why it's built that way. IPC gives us a way to develop standardized footprints from package drawings that removes any variation between vendors using a standard package.

I don't find the reference/standard/source SOT-553 drawing. Does anyone know what organization originated it? It may be JEDEC MO-293 variation UAAD-1; I could be mistaken but I think they match.

@poeschlr Shall we standardize now instead of having two SOT-553 footprints and proliferating what should be unnecessary manufacturer specificity?

**Pull request merged**
