### PR TITLE
Amphenol m8 s 03 pmmr sf8001

### PR DESCRIPTION
**Pull request by cronJ**
Add Amphenol LTW M8 shielded 3-pin connector

https://www.amphenolltw.com/2012download/2D%20PDF/03_M%20Series%20Sensor%20Connectors/M8S-XXPMMR-SF8001.pdf#page=2

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chmorgan** [comment]
@chschlue how do we approach adding new libraries like this? Amphenol does make a lot of connectors and we don't have a specific library for those yet.

**Comment by cronJ** [comment]
> * How did you get overall part dimensions? The drawing doesn't seem to have a way to show the face to the pins anywhere...

I measured the dimensions on the real part. This footprint is also on an already manufactured board and fits.

**Comment by chmorgan** [comment]
Hi @cronj. Looks like the left and right courtyard are offset from center of silk not fab

Silk lines look ok, a little inconsistent in the notches vs. the straight parts. Orientation looks good now.

**Comment by chmorgan** [comment]
@chschlue, @cpresser thoughts on adding this part to the this proposed Amphenol library?

**Comment by chschlue** [comment]
Looks good to me.

**Comment by cpresser** [comment]
> @chschlue, @cpresser thoughts on adding this part to the this proposed Amphenol library?

Good idea. Amphenol has lots of connectors.

**Comment by cpresser** [comment]
@chmorgan 
I think you need to check submissions more thoroughly. I checked this one since the screenshot looked wrong. Thus, wanted to see if it got merged like shown in the screenshot.

Then I checked some dimensions, and its not looking good :crying_cat_face: 
image
* this should be 7mm according to the datasheet.
* Another body-dimension is 13.2mm where the datasheet has 12.8
* The courtyard could be smaller (tight around the part), but that is not an real issue here: the biggest part of the device is not going to be on the PCB.
* If dimensions are missing in the datasheet another method of verification is needed. Either ask the manufacturer for more details, search for better docs, or measure in the 3D-Model. There is a step-file available here: https://www.amphenolltw.com/de/p2-products-detail.php?product_series_sn=15&product_classify_sn=33&sn=5151
* My estimation of the length is more like 18.5mm 
image With proper use of FreeCAD (or any other CAD-Tool) there will be a more accurate measurement. But I am quite confident that it won't be 19.8mm

**Comment by chmorgan** [comment]
@cpresser I can appreciate that. I'm trying to be as careful as possible but I'm also not a cad person.

In terms of adjusting I can adjust the width to be 7mm and shorten the body up slightly to match what you've measured if that makes sense. I can bring the courtyard in if you think it won't cause an issue with interference.

**Comment by cpresser** [comment]
**We usually ask the original contributor to do the fixes. Its their contribution after all.**
@cronJ Do you want to make another PR to fix the issues I found with this submission?

Regarding CAD, that is something one can learn :)
The above screenshot is actually garbage. I took the wrong part (Female vs. Male Plug).

I redid the whole thing in Fusion360 (because I know how to use that - contrary to FreeCad).
image
Workflow is:
* Import .step file
* Add offset-plane that does not cut the part (just eyeball the distance)
* Project part onto that new plane
* Use dimension-tool to add dimension (ignore the over constrained warning).

I am pretty sure a similar workflow also exists in FreeCAD, I just didn't bother to learn it yet.

**Comment by cronJ** [comment]
Yes, I'm already working on the fixes. I will create an PR when finished.

**Comment by chschlue** [comment]
I _think_ one of the easier ways to do this in FreeCAD is
* import STEP
* create 2D views in the TechDraw WB as needed (0.19pre; 0.18 has several ugly shortcomings in that regard)
* add dimensions

but I'm not an MCAD native either.
Quite possible this is actually a stupid workflow.

**Pull request merged**
