### PR TITLE
Add two more WSON-8-1EP_4x4mm_P0.8mm variants

### PR DESCRIPTION
**Pull request by cpresser**
Related: https://github.com/KiCad/kicad-symbols/pull/3097
GeneratorPR: https://github.com/pointhi/kicad-footprint-generator/pull/646

### CODE REVIEW

**Comment by cpresser** [comment]
@chschlue I was so bold and assigned you to this.

**Comment by chschlue** [comment]
Please update (doc link changed)

**Comment by cpresser** [comment]
Done (with a force-push)

**Review by chschlue — APPROVED** [review]
Thanks

**Pull request merged**
