### PR TITLE
Fixing RECOM footprints, round 2.

### PR DESCRIPTION
**Pull request by rschaeuble**
These files were regenerated with these changes to the generator:
https://github.com/pointhi/kicad-footprint-generator/pull/141.

R5xxxDA (https://www.recom-power.com/pdf/Innoline/R-5xxxPA_DA.pdf):
r5xxxda

R5xxxPA (https://www.recom-power.com/pdf/Innoline/R-5xxxPA_DA.pdf):
converter_dcdc_recom_r5xxxpa_tht

R-78B-2.0 (https://www.recom-power.com/pdf/Innoline/R-78Bxx-2.0.pdf):
converter_dcdc_recom_r-78b-2 0_tht

R-78E-0.5 (https://www.recom-power.com/pdf/Innoline/R-78Exx-0.5.pdf):
converter_dcdc_recom_r-78e-0 5_tht

R-78HB-0.5 (https://www.recom-power.com/pdf/Innoline/R-78HBxx-0.5_L.pdf):
converter_dcdc_recom_r-78hb-0 5_tht

R-78HB-0.5L (https://www.recom-power.com/pdf/Innoline/R-78HBxx-0.5_L.pdf):
r-78hb-0 5l

R-78S-0.1 (https://www.recom-power.com/pdf/Innoline/R-78Sxx-0.1.pdf):
converter_dcdc_recom_r-78s-0 1_tht

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
  - https://github.com/KiCad/kicad-packages3D/pull/339
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by rschaeuble** [comment]
If someone could do a quick sanity check and compare the measurements in the screenshots with the ones in the datasheets, that would be awesome.

If no error is pointed out in the next 2-3 days, I'll go and make the according changes to the 3D models as well (and link the PRs here).

**Comment by rschaeuble** [comment]
3D model changes are now available as well: https://github.com/KiCad/kicad-packages3D/pull/339

**Comment by Shackmeister** [comment]
Shouldn't R5xxx be R-5xxx?

Also for
Converter_DCDC_RECOM_R-78HB-0.5L_THT
and
Converter_DCDC_RECOM_R5xxxDA_THT
A silk line going next to the pin 1 pad would be sufficient :)

**Comment by rschaeuble** [comment]
@Shackmeister: yes, to be 100% correct and consistent, the dashes in the names would have to be added. Should I do this in this PR (and add one for the symbols repo, as the footprint names there would have to be adapted), or should I make a separate PR after this one?

The thing with the silk lines I didn't understand. Could you elaborate?

**Comment by Misca1234** [comment]
The only very small thing I found was in Converter_DCDC_RECOM_R-78E-0.5_THT
The F.Fab distance to pin one is -3,31, it should be -3.21

Shackmeister means something like this (I guess), the pin 1 marker should go "outside the pin and not around the corner

bild

**Comment by rschaeuble** [comment]
@Misca1234: I believe the -3.31 are correct.

The datasheet for the R-78E-0.5 specifies pin 3 to be 3.21 mm from the right side of the device. Pin 1 is 5.08 mm from pin 3, so it's 8.29 mm from the right side. With a width of 11.6 mm, pin 1 is 11.6 - 8.29 = 3.31 mm from the left side.

About the pin 1 marker: I think I understand what you mean, but I'll make a quick drawing to verify that with you tomorrow or Friday. I don't know, however, how easily that is changed in the generator script.

**Comment by Misca1234** [comment]
> About the pin 1 marker: I think I understand what you mean, but I'll make a quick drawing to 
> verify that with you tomorrow or Friday. I don't know, however, how easily that is changed in the generator script.

It was my guess that it is what Shackmeister wanted, he have to confirm

**Comment by Shackmeister** [comment]
Im referering to this (and it's brother), the Pin 1 line is marked.
pin1_marker1

I think this style would be much more suited. line is marked again
pin1_marker2

**Comment by rschaeuble** [comment]
@Shackmeister: alright, I get it now.

Would this also be OK?
capture

This way it looks similar to all the other RECOM packages (and, to be honest, it's less work ;) ).

Besides this, there is still the question of renaming R5xxx to R-5xxx? Should I do this in this PR, or open another one?

**Comment by rschaeuble** [comment]
I didn't get any feedback on the questions in my previous comment, so I went ahead and modified the footprints as I suggested.
Both the footprint generator and the footprints are updated; I also updated the screenshots of the R5xxxDA and the R-78HB-0.5L to show the changes.

If this is OK as it is, please merge. After the merge I will create a new PR to rename the R5xxx.

**Comment by poeschlr** [comment]
A bit late to the party but i must say i would like the pin 1 marker suggested by @Shackmeister a lot more than the L around the corner. That style would be closer to what industry standards suggest right now.

**Comment by rschaeuble** [comment]
@poeschlr alright, I made those changes, and updated the screenshots.

**Comment by rschaeuble** [comment]
@Shackmeister, @poeschlr: are there any issues left that are preventing this from getting merged?

**Comment by poeschlr** [comment]
I would guess just time for a proper review

**Comment by Misca1234** [comment]
I made a full review for some time ago, if it is only the pin 1 marker that have been changed we only need to look at that, or accept the current push as it is now right away

**Comment by rschaeuble** [comment]
@Misca1234 Yes, the pin 1 marker was the only thing I've changed.

I wouldn't mind if this got merged soon. As many of the old RECOM footprints are wrong anyway, the chance of making it worse isn't that biganyway ;-)

**Comment by Misca1234** [comment]
oh, it is eight of them, I will do it tomorrow

**Comment by Misca1234** [comment]
Everything looks good, however we need to update the 3D model for 
Converter_DCDC_RECOM_R5xxxDA_THT

(the problem is the pins, they are not 90 degree but 45 degree which made the 3D model slightly offset)

bild

**Comment by rschaeuble** [comment]
@Misca1234 please have a look at my pull request https://github.com/KiCad/kicad-packages3D/pull/339. That PR contains fixes to the 3D models.

**Comment by rschaeuble** [comment]
@Misca1234 Please also merge https://github.com/pointhi/kicad-footprint-generator/pull/141, which contains the changes to the generator that created these footprints.

**Comment by Misca1234** [comment]
I cant, I do not have any rights on that repository

**Pull request merged**
