### PR TITLE
Add TO-220F footprint & fix TO-220

### PR DESCRIPTION
**Pull request by jkriege2**
1. fixed TO-220 footprints: the y-offset of pins to metal-back was wrong, it has been modified to match https://www.vishay.com/docs/66542/to-220-1.pdf
2. added footpritns for TO-220F (isolated plastic package), see https://www.fairchildsemi.com/package-drawings/TO/TO220M03.pdf
3. 3D models (TO-220-2/3: full set and TO-220F-2/3: vertical): https://github.com/KiCad/kicad-packages3D/pull/288
4. 3D model sources: https://github.com/KiCad/kicad-packages3D-source/pull/115
5. generator script: https://github.com/pointhi/kicad-footprint-generator/pull/120
6. footprints: https://github.com/KiCad/kicad-footprints/pull/470
7. remaining KLC-violations are due to very small pin-pitch in 5-pin packages and have been present in the former version too. I don't see any way to satisfy the 0.15mm with these footprint, the distance between the hole outer diamaters is only 0.6mm. All other bugs are also not new, as I mainly renamed the footprints ==> Please ignore

2018-04-05 11_23_18-pcbnew d__kicad_devproject_devproject kicad_pcb
2018-04-05 11_40_24-3d viewer

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks Jan!

http://kicad-pcb.org/libraries/klc/F3.5/ shows using _TabUp and _TabDown. That gives the absolute orientation of the part instead of _Reversed which is ambiguous (it's reversed compared to what?). I fear now may be a bad time to make this change because of v5, but if our symbols specify the vertical versions by default then it shouldn't be so bad. What do you think?

**Comment by jkriege2** [comment]
OK, I renamed ... also in the other PRs connected to this one!

Also I made a PR to fix the footprint links to match this PR (and fix some errors): https://github.com/KiCad/kicad-symbols/pull/455

best,
JAN

**Comment by jkriege2** [comment]
Hi!

I will ignore all issues of TO-92 (no time at the moment) and will tend to some of the others:
1. For everything except TO-92 they should be there now.
2. Yes they are in the models ... this is important (IMHO) for optics components like photodiodes, transistors, ... where it may help to have these features in the 3D model (e.g. to correctly drill housings)
3. ignored
4. ignored
5. ignored
6. ignored
7. ignored
8. renamed to SOT-93
9. has been added
10. The old package will be deleted (without TabDown)
11. will change that (all unnumbered)
12. not sure ... I think I thought they were different when making the scripts ... for lack of a better argument I will leave it for now (assuming I had a point back then ;-))
13. Yes, because pad=pin4 ... for all the others the pad is not connected!
14. should be fixed
15. old version will be deleted
16. can't find one ... should we remove it?

Thanks for the review ... anything else?
JAN

**Comment by jkriege2** [comment]
Now also the specific TO-220F-5 that you requested exists (there are 2 variants for pin-bening now with differen y-pitch):
2018-04-06 10_27_50-pcbnew d__kicad_devproject_devproject kicad_pcb

**Comment by jkriege2** [comment]
Since my last review, I used this PR to correct bugs in two packages (TO-251 and TO-262), also I added weblinks for package references! Hope that's fine with you!

Best,
JAN

**Comment by jkriege2** [comment]
PS: I will add a nother PR with more 3D models and link it here at some point today or in the coming days ... but that can be reviewed separately from this one!

**Comment by jkriege2** [comment]
@evanshultz OK; I finished this for now ... Here are two more PRs with additional 3D models (I think I have nearly all vertical devices and some horizontals:

- sources: https://github.com/KiCad/kicad-packages3D-source/pull/118
- exports: https://github.com/KiCad/kicad-packages3D/pull/289

2018-04-08 17_01_52-3d viewer
2018-04-08 17_01_34-3d viewer

**Comment by evanshultz** [comment]
I was just about to look at this. Should I do that now or are you going to push more commits?

Sorry, but I'm not comfortable to merge 3D models. You requested my review but I'd prefer is somebody else can take that one.

**Comment by jkriege2** [comment]
Yes please have a look, I just fixed one more today, which I had forgotten (TO-218) ... but which is more or less obsolete nowadays, I think ;-)

@Ratfink @poeschlr @Misca1234 Would onw of you guys have time to look at the 3D models? I think they would be a nice addition to the v5-libs. I didn't model all variants, but mainly the vertical ones + a few of the horizontal ones. I think the missing 3D models will dribble in over time (I hope). If you do have time, you'll need to look at two sets of PRs:
- https://github.com/KiCad/kicad-packages3D-source/pull/118 / https://github.com/KiCad/kicad-packages3D/pull/289
- https://github.com/KiCad/kicad-packages3D/pull/288 / https://github.com/KiCad/kicad-packages3D-source/pull/115

Best,
JAN

**Comment by Ratfink** [comment]
I'm afraid I'm not familiar enough with FreeCAD to trust myself to review the 3D models well, either.

**Comment by jkriege2** [comment]
Thanks for the review:
1. About the staggered-devices: I renamed them by adding TabDown (where necessary) and the y-pin-pitch with `_PyX.XXmm` ... So no devices should have been lost, just new names (+ bugfixes/added webpages)
2. L298: done
3. I hope it's a bit better now ... for some I don't have a weblink, then I leave one that AT LEAST shows a comparable package with different staggering ...
4. TO-251: done
5. Since we removed all doubble-names, also from other libs (e.g. TO_SOT_SMD), I also removed it here and added the name to the description/tags ... I would leave it like this for now 
6. I added F.Paste to all top-pads

Best,
JAN

**Comment by evanshultz** [comment]
- Some of the staggered TO220-5 use http://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/ltc-legacy-to-220/to-220_5_05-08-1421_straight_lead.pdf, which is a straight lead drawing.
- In https://github.com/KiCad/kicad-footprints/pull/470/commits/581e3d2cfa150e6c2cd6f0ea8573207ad738933b many datasheet links were lost.

Everything else is OK with me. Thanks Jan!

**Comment by jkriege2** [comment]
Hi!

I fixed the TO-220-5 datasheet links. All the others were lost, because they didn't match the footpritns specifically.

OK to merge?

cu
JAN

**Pull request merged**
