### PR TITLE
Add Mini-Circuits land pattern PL-247

### PR DESCRIPTION
**Pull request by aewallin**
land-pattern: https://ww2.minicircuits.com/pcb/98-pl247.pdf
component: https://ww2.minicircuits.com/pdfs/LPF-B0R3+.pdf
package: https://ww2.minicircuits.com/case_style/HZ1198.pdf

KLC check gives error about the footprint anchor, but I dont know how to move the footprint by 0.000635mm.

pl-247

used by e.g. https://github.com/KiCad/kicad-symbols/pull/1212

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
after revisions:
pl247

**Comment by serkanxselcuk** [comment]
Hello @aewallin ,
you can move items exactly, if you select item(s) "right click>Move exactly" or shortcut key "Ctrl+M".
image
 In this menu, you can give exactly distance in X or Y direction you want to move.

**Comment by poeschlr** [comment]
The large pad looks quite different to how it is shown in the datasheet. (It should be larger)
The clearance to the normal pads is also not quite right.

screenshot from 2019-01-02 00-40-31

**Comment by aewallin** [comment]
Here I would prefer leaving the GND SMD-pads out completely. Just define a 0.032" clearance for the signal pads, maybe a keepout-zone as per the 0.138" dimension in the spec - and rely on the user providing a GND-zone everywhere else.
What do you think?
(different SMD pad clearance-values in X/Y directions would be nice in this case..)

**Comment by aewallin** [comment]
from the land-pattern drawing I estimated that the GND-zone overlaps the f.fab outline of the package by 40mils. The GND-zone pads are now revised:
pl247_dims

**Comment by myfreescalewebpage** [comment]
@aewallin same problem here already discussed on other Mini-Circuits footprint.

Joel

**Comment by aewallin** [comment]
@myfreescalewebpage I don't see any issues with the coordinates of any pads or the dimensions. They are even numbers in units of mils.
The dimensions pointed out by @poeschlr above should be corrected in 7526fa3

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
