### PR TITLE
add LFCSP-8-1EP 3x3mm variant (Analog cp-8-13)

### PR DESCRIPTION
**Pull request by lorem-ipsum**
created by copying the existing LFCSP-8-1EP 3x2mm, adjusted the pad size
and widened the package. The pin positions are identical.

[Outline PDF](https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/cp-8/CP_8_13.pdf) This will be used for the [ADG901](https://www.analog.com/media/en/technical-documentation/data-sheets/ADG901_902.pdf) switch.

screenshot_20181101_122221

### CODE REVIEW

**Comment by poeschlr** [comment]
This one could be scripted. @lorem-ipsum would you be willing to look into that?
The script that can handle these sort of parts lives here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_DFN_QFN

**Comment by lorem-ipsum** [comment]
I will take a look at it around christmas time when I have a bit more time.

**Comment by poeschlr** [comment]
If you need any help understanding the scripts feel free to ask over here or via the forum (private message if you feel more at ease that way)

**Comment by lorem-ipsum** [comment]
I created a version based on the script and pushed the new version. The name has changed as the script flipped the x-y-naming of the pad. The script is currently only existing in [my fork](https://github.com/lorem-ipsum/kicad-footprint-generator/tree/cp-8-13) of the footprint generator (yaml file [here](https://github.com/lorem-ipsum/kicad-footprint-generator/tree/cp-8-13/scripts/Packages/Package/Package_DFN_QFN/size_definitions/lfcsp.yaml). Will generate a PR once its fine. 
screenshot_20181227_133543

**Comment by poeschlr** [comment]
Please open a pull request for the script addition now. The review of your contribution will happen in that pull request.

**Comment by lorem-ipsum** [comment]
Created the [PR](https://github.com/pointhi/kicad-footprint-generator/pull/255)

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
