### PR TITLE
4UCON 10156 right-angle through-hole card-edge socket

### PR DESCRIPTION
**Pull request by ppelleti**
[Datasheet](http://www.4uconnector.com/online/object/4udrawing/10156.pdf).

This is the connector used for the [BBC micro:bit](https://tech.microbit.org/hardware/edgeconnector/), although it is used for other things, too.

This footprint is based on [a footprint](https://github.com/SukkoPera/OpenAmiga600RamExpansion/blob/master/OpenAmiga600RamExpansion.pretty/4UCON_10156_90deg.kicad_mod) by @SukkoPera, which is based on [a footprint for the "straight" (vertical) version of the connector](https://github.com/anthonykirby/kicad_microbit_connector/blob/master/Connectors_4UCON.pretty/4UCON_17909_02x401.27mm_Vertical.kicad_mod) by @anthonykirby.

Both of them have given their [permission](https://github.com/anthonykirby/kicad_microbit_connector/issues/6#issuecomment-419675526) for this footprint to be contributed to the KiCad library.  (Thanks!)

microbit_edge_connector_2

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
They both made their models in kicad, you should asked them to send them in to kicad ^^ ;)?

How do you know how to enumerate the pins?

How did you calculate the width (C-distance) of the unit?
Should it not be 49,53 ?

The description should be change 
from
**descr "Card edge socket with 80 contacts (40 each side), through-hole, http://www.4uconnector.com/online/object/4udrawing/10156.pdf")**
**tags "bbc microbit edge connector right-angle")**
to
**descr "4UCON  10156 Card edge socket with 80 contacts (40 each side) ....**
**tags "4UCON  10156 Card edge socket with 80 contacts"**

**Comment by ppelleti** [comment]
> How do you know how to enumerate the pins?

Pin 1 is marked on the datasheet.  The odd-numbered pins are for the front of the card, and the even-numbered pins are for the back of the card.

> How did you calculate the width (C-distance) of the unit?
> Should it not be 49,53 ?

Yes, I intended the C-distance to be 49.53.  What are you finding it to be instead?

**Comment by Misca1234** [comment]
It is ok, i mixed up A and C in the drawing

**Comment by ppelleti** [comment]
I've updated the description and tags as you requested.

**Comment by Misca1234** [comment]
Great thx

**Pull request merged**
