### PR TITLE
Added TDK SLF from script

### PR DESCRIPTION
**Pull request by matyro**
Added 11 footprints for all TDK SLF inductors.

https://www.mouser.com/ds/2/400/tdk_e531_slf-1207238.pdf

See issue #345

### CODE REVIEW

**Comment by poeschlr** [comment]
A screenshot of the footprint would help quite a lot

**Comment by matyro** [comment]
grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

grafik

**Comment by Shackmeister** [comment]
The silkscreen is usually going all the way around except for the pads.

can you please link to the script? and is this something you can fix in the script yourself?

**Comment by matyro** [comment]
Sorry for the noise above,
I did not commit the scripts to footprint_genator and forgot about this branch here. I can create a pullrequest for the scripts and change the silkscreen to finish this.

**Comment by Shackmeister** [comment]
Please change the silkscreen :)

**Comment by Misca1234** [comment]
@matyro 
Please check Schakmesiter comment above

**Comment by Misca1234** [comment]
@matyro
Please check Schakmesiter comment above

**Comment by SchrodingersGat** [comment]
@matyro bump - please address the silkscreen issues above and we can get this merged :)

**Comment by Misca1234** [comment]
Replacement push is here
https://github.com/KiCad/kicad-footprints/pull/1021

Closing this one

**Pull request closed without merging**
