### PR TITLE
Added USB_Mini-B_AdamTech_MUSB-B5-S-VT-TSMT-1_SMD_Vertical

### PR DESCRIPTION
**Pull request by 5N44P**
image

DS: http://www.adam-tech.com/upload/MUSB-B5-S-VT-TSMT-1.pdf
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by 5N44P** [comment]
See https://github.com/KiCad/kicad-footprints/pull/804#issuecomment-410227192 for the remaining Travis errors

**Comment by 5N44P** [comment]
To me this is ready for merging. All travis errors and warnings have been cleared and the footprint is already tested on a pcb. 
Waiting for the mantainers response

**Comment by 5N44P** [comment]
Tonight i'll fix the fab and silk lines. 
The pin order is standard for all usb connectors, but i'll double check also that. 
The measures on the ds aren't missing, they are only a bit too implicit. 


Btw i've tested the footprint in production, minus the data pins. The power pins are correct, so i'd assume that also the others are. Mechanically fits perfectly.

**Comment by 5N44P** [comment]
@poeschlr I've fixed the silkscreen and the fab layer. 

see http://pinoutguide.com/PortableDevices/mini-usb-cable_pinout.shtml for pinouts.

Outlines can be obtained adding the metal thickness (0.4mm, showed in the upper right corner for the tab) to the inner measurement (showed in the lower left corner). Measure with the caliper on the connector confirms the dimensions.

**Comment by poeschlr** [comment]
One courtyard direction is not quite right (see drawing)
Add pin 1 markers on silk and fab layers (remove the silk line next to pin 1 for marking that pin. Add a chamfer on the fab outline edge near pin 1)
Rotate the footprint counter clockwise by 90 degree such that pin 1 is nearest to the top left corner.

screenshot from 2018-08-09 11-55-25

**Comment by poeschlr** [comment]
You are right, as the pins protrude the body, the silk line along pin 1 is the marker.

**Comment by 5N44P** [comment]
I'm looking into KLC. Pin 1 marking on Fab layer for connectors requires an arrow (F.5.2.2.c) 
Is it better to make the arrow or the chamfer?

**Comment by poeschlr** [comment]
The pictures in the KLC are just examples of different posibilities. IPC suggests what i described above. Where sensible we should go with the standard. (So chamfer on fab plus line alongside pin 1 on silk. If you do not include the area covered by the pins in the fab outline then we might use something similar to what is used for molex picoblade connectors on the fab layer.)

**Comment by 5N44P** [comment]
Yeah that's also what's happening with the only other mini usb. I'd propose do that to keep consistency across the usb lib and adhere to the KLC

image

**Comment by 5N44P** [comment]
Current proposed footprint:

image

**Comment by poeschlr** [comment]
Looks good. Thanks

**Pull request merged**
