### PR TITLE
Hirose conn BM24 series. 40 pin. Receptacle and header

### PR DESCRIPTION
**Pull request by carlosromorgar**
https://www.hirose.com/product/en/download_file/key_name/BM24/category/Catalog/doc_file_id/47680/?file_category_id=4&item_id=50&is_series=1

image

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Would "NO FRONT COPPER" or even just "NO COPPER" work?

**Comment by poeschlr** [comment]
Copper is allowed. It just must be covered with something insolating. (So no blank copper)

**Comment by evanshultz** [comment]
Got it. In that case, using the word "exposed" will be a good choice.

**Comment by carlosromorgar** [comment]
Hi,
Thanks for your comments. I have added the keep-out areas and I had to reduce the text size because it did not fit into the area. Is it right? Or the text size must be 1.00mm and 0.15mm thickness?

This is the new screenshot.

image


The screenshot of the other footprint is 

image


Thanks

BR

**Comment by poeschlr** [comment]
Good work, thanks

**Pull request merged**
