### PR TITLE
Add footprint for Quectel L80 GPS module

### PR DESCRIPTION
**Pull request by thatoddmailbox**
Datasheet: https://www.quectel.com/UploadImage/Downlad/Quectel_L80-R_Hardware_Design_V1.2.pdf

I wasn't completely sure how to indicate pin 1. I added an extra line on the silkscreen, but I wasn't sure if there should be something more noticeable (like an arrow or circle or something...)

Screenshot: 
image
Dimensioned drawing (this is my first time creating one of these--if I'm missing anything important, please let me know!): 
l80_dimensions

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by thatoddmailbox** [comment]
The associated symbol for this is KiCad/kicad-symbols#2657.

**Comment by myfreescalewebpage** [comment]
Hi @thatoddmailbox , thanks for contributing,

A few comments I have during my review:

- [ ] The footprint is not vertically centered. Everything should be moved by 0.5mm
- [ ] F.CrtYd layer is too much closed to the pad, please respect 0.25mm clearance
- [ ] Datasheet to be added in the description as done for all footprints
- [ ] The keepout area is not placed correctly according to the dimensions on Figure 20 Page 31 of the datasheet

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
@thatoddmailbox ping

**Comment by thatoddmailbox** [comment]
@myfreescalewebpage Sorry about that, I was really busy last week! I've made fixes for the first three issues you mentioned. However, for the keepout area, I remeasured and I still got the same measurements as in that figure. (7.4 mm and 7.37 mm). I'm measuring from the center of the circle to the lines on F.Fab, since those are 16 mm x 16 mm, like it says in that figure. 

Do you mean that the keepout circle should be 7.4 mm and 7.37 mm from the bottom right corner? That's also what I originally thought, but on the actual module, the circle on the top is closer to the top left (pin 1). See: 

kicad_l80

**Comment by myfreescalewebpage** [comment]
@thatoddmailbox thanks for the details and for the fixes. Just checked again the keepout is correct I think now. Maybe I have made a wrong comment because of the first issue (vertical centering of fp).

No more comment, merging.

**Pull request merged**
