### PR TITLE
Added DIP-5-6 footprint

### PR DESCRIPTION
**Pull request by Misca1234**
This push consist of the new footprint DIP-5-6 used by TLP3542

The new foot prints is copied from DIP-6

DIP-5-6_W10.16mm.kicad_mod

DIP-5-6_W10.16mm_LongPads.kicad_mod
DIP-5-6_W7.62mm.kicad_mod
DIP-5-6_W7.62mm_LongPads.kicad_mod
DIP-5-6_W7.62mm_SMDSocket_SmallPads.kicad_mod
DIP-5-6_W7.62mm_Socket.kicad_mod
DIP-5-6_W7.62mm_Socket_LongPads.kicad_mod
DIP-5-6_W8.89mm_SMDSocket_LongPads.kicad_mod

3D models are here
https://github.com/KiCad/kicad-packages3D/pull/257

bild

bild

bild

bild

bild

### CODE REVIEW

**Comment by jkriege2** [comment]
Please post a screenshot of the new footprints ...

**Comment by Misca1234** [comment]
3D models are here
https://github.com/KiCad/kicad-packages3D/pull/257

bild

bild


bild

bild

bild

**Comment by jkriege2** [comment]
Looks good, thanks!

PS: How did you create these? By hand (based on the existing ones) or did you modify the scripts? In the latter case: please open a PR for the scripts and post the link here!

Thanks,
JAN

**Comment by jkriege2** [comment]
This will be used for https://github.com/KiCad/kicad-symbols/pull/282

**Comment by Misca1234** [comment]
They are made by a script from 
https://github.com/easyw/kicad-3d-models-in-freecad

(In directory cadquery/FCAD_script_generator/DIP_packages)

Which I have modified heavily so it can make both THT and SMD capsules (and now you can exclude specific pins)
I believe all the THT DIL and SMD DIL 3D models in Package_DIP.3dshapes comes from this script.
(except the socket ones)

The pull specific for these 3d models is 
https://github.com/easyw/kicad-3d-models-in-freecad/pull/152

**Pull request merged**
