### PR TITLE
Add HVSON-8-1EP_3x3mm_P0.65mm_EP1.6x2.4mm

### PR DESCRIPTION
**Pull request by LHSmicius**
Datasheet: https://www.nxp.com/docs/en/data-sheet/TJA1051.pdf  (page 16)
HVSON-8_3x3mm
Travis gives violation F6.3  - Pad '9' missing layer 'Paste'. This is because of exposed center pad.
Footprint is generated with kicad-footprint-generator.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chschlue** [comment]
Please link to the corresponding generator PR.

**Comment by LHSmicius** [comment]
Generator: 
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/ipc_noLead_generator.py
PR means Pull-Request? Sorry if my link is not what you want. It links to "master" branch but it should be the same as I used, because I downloaded it month ago.

**Comment by chschlue** [comment]
Is there a pull request adding the size definition you used to create this footprint?
If not, you need to open one before the corresponding can be merged.

**Comment by LHSmicius** [comment]
Here is the link to PR https://github.com/pointhi/kicad-footprint-generator/pull/580 .

**Comment by LHSmicius** [comment]
Wait, I didn't regenerate footprint with last size definition file fixes.

**Comment by chschlue** [comment]
The changes shouldn't have affected the actual output.
Did they?

**Comment by LHSmicius** [comment]
Only datasheet's URL would be affected, but it's not necessary to make URL linking directly to the page where footprint dimensions are, just nice to have :)

**Comment by chschlue** [comment]
Oops.
Would you like to submit a fix?

**Comment by LHSmicius** [comment]
Sure. I have to make new PR?

**Comment by chschlue** [comment]
Yes. Merged PRs are dead and buried on GH.

**Pull request merged**
