### PR TITLE
add Bosch LGA-8 2x2.5mm Pitch 0.65mm footprint

### PR DESCRIPTION
**Pull request by ChristianHirsch**
Hi @SchrodingersGat 
image
[BMP280](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BMP280-DS001-18.pdf) Datasheet
I'm violating rule F9.3, but I have no idea how to fix this. Can anyone help me?

### CODE REVIEW

**Comment by poeschlr** [comment]
From travis report:
> 3D model directory is different from footprint directory (found 'Housings_LGA.3dshapes', should be 'Package_LGA.3dshapes')

This means your 3d settings are incorrect. You can reach the 3d settings via this button:
screenshot from 2017-12-11 10-26-15

Also your footprint is already in the lib ;)
https://github.com/KiCad/kicad-footprints/blob/master/Package_LGA.pretty/Bosch_LGA-8_2.5x2.5mm_P0.65mm_ClockwisePinNumbering.kicad_mod

**Comment by ChristianHirsch** [comment]
Hi @poeschlr, no, it's not. Mine is 2(.0)x2.5mm. The one you mentioned is 2.5x2.5mm.
I found the problem and fixed the 3d settings.

**Comment by poeschlr** [comment]
Could you also orient your footprint the same as the one i linked? (i.e. pin 1 at the top left corner. -> rotate by 90 degrees counter clockwise.)

**Comment by ChristianHirsch** [comment]
Fixed :+1:
image

**Comment by ChristianHirsch** [comment]
@poeschlr wait a moment. I need to fix the name. It is still called Pitch0.65, but you renamed all footprints to P*.

**Comment by poeschlr** [comment]
Your latest commit also reverted the changes to the 3d model path it seems.

**Comment by ChristianHirsch** [comment]
Ok, so now everything looks fine :)

**Comment by poeschlr** [comment]
Sorry that i missed it, but could you rotate the reference on fab layer? That way it could be a bit bigger. (just take the values from the other bosch footprint.)

**Comment by ChristianHirsch** [comment]
Fixed :+1: @poeschlr

**Comment by poeschlr** [comment]
Thanks for this contribution.

**Pull request merged**
