### PR TITLE
Add 49-ball 0.4mm pitch BGA footprint.

### PR DESCRIPTION
**Pull request by awygle**
This adds a 49-ball 0.4mm pitch BGA footprint based on the Lattice CM49 footprint found at http://www.latticesemi.com/view_document?document_id=213 .

image
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
you might wanna go over the 3D model name again :)

**Comment by awygle** [comment]
Argh. Fixed :)

**Comment by Misca1234** [comment]
@awygle 
I know it takes a lot of work to make these by hand, but have you looked into how to create foot prints with help of scripts, it is very easy, you just specify the dimensions in a readable text file and then let the already scripts do the work.

If you want I give you a description of how to do it
(The review goes much much faster, we only have to check the text file, with hand made models we need for example check each one of the pads manually)

**Comment by awygle** [comment]
@Misca1234 I'd be happy to do so, if you can point me to some documentation.

**Comment by Misca1234** [comment]
What you do is to checkout this git repository
https://github.com/pointhi/kicad-footprint-generator

Depending on what type of foot print you want to make you modify the .yaml file in different directories
For example for BGA you modify the file 
tree/master/scripts/Package_BGA/bga.yml
file with the parameters that match the data sheet

then you generate the foot print by executing the python script
scripts/Package_BGA/bga.py with the bga.yml as an argument.

Then you push the generated foot print in same as you done now 
but also push the changes to .yaml file to
https://github.com/pointhi/kicad-footprint-generator
as well






PS
for most other capsules you do the same but use the scritps in 
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages
DS

**Comment by Misca1234** [comment]
@awygle 
scripts perhaps ;) ?

**Comment by Misca1234** [comment]
This one already exist among the foot prints
UCBGA-49_3x3mm_Layout7x7_P0.4mm

I am closing this one

**Pull request closed without merging**
