### PR TITLE
Connector usb1

### PR DESCRIPTION
**Pull request by krtkr**
Hi all!

I add a few USB packages, used at my project:
1. USB_B_TE_5787834_Vertical
1. USB_Micro-B_Tensility_54-00023_Vertical
1. USB_Micro-B_Tensility_54-00023_Vertical_CircularHoles

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@krtkr nice these are great :) One minor complaint (very minor!) The F.Fab lines are a little wonky

selection_023

**Comment by pointhi** [comment]
I would include the manufactur number in the first footprint as well.

**Comment by poeschlr** [comment]
It seems to be TE-Connectivity 5787834
So the name should be `USB_B_TE_5787834_Vertical`

**Comment by krtkr** [comment]
@poeschlr I have a little confusion regard naming here.

At new KLC for connectors you specify MPN. It seems that it consist of Manufacturer and Part number. What should be separator between Manufacturer and Part number? '_' or '-'?

For Connector_USB.pretty library both used. At my patch I use '-': Tensility-54-00023, you suggest '_': TE_5787834.

Maybe we should come up with something common for all footprints here?

**Comment by poeschlr** [comment]
The separator between MAN and MPN is defined as "_"
See section `Connectors for Specific Functions` of http://kicad-pcb.org/libraries/klc/F3.6/

**Comment by krtkr** [comment]
@poeschlr I guess _USB_Micro-B_Wuerth-614105150721_Vertical_CircularHoles_ should be named _USB_Micro-B_Wuerth_614105150721_Vertical_CircularHoles_ in this case?

**Comment by poeschlr** [comment]
Yup exactly.

**Comment by krtkr** [comment]
@poeschlr in this case someone should fix the KLC, because first example at F3.6 'Connectors for Specific Functions' is _USB_Micro-B_Wuerth-614105150721_Vertical_CircularHoles_.

**Comment by poeschlr** [comment]
See PR for the webside: https://github.com/KiCad/kicad-website/pull/247

**Comment by SchrodingersGat** [comment]
Thanks for the contributions :)

**Pull request merged**
