### PR TITLE
Add WQFN-20 package for ON Semi FXMA108BQX.

### PR DESCRIPTION
**Pull request by awygle**
Add WQFN-20 package for ON Semi FXMA108BQX IC.

Datasheet: https://www.mouser.com/ds/2/149/FXMA108-1010351.pdf
Package Document: http://www.onsemi.com/pub/Collateral/510CD.PDF
Symbol PR: https://github.com/KiCad/kicad-symbols/pull/461

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Ratfink** [comment]
[KLC]: http://kicad-pcb.org/libraries/klc/ "KiCad Library Convention"
[G1.1]: http://kicad-pcb.org/libraries/klc/G1.1/ "Only standard characters are used for naming libraries and components"
[G1.2]: http://kicad-pcb.org/libraries/klc/G1.2/ "Each library is limited to 250 items"
[G1.3]: http://kicad-pcb.org/libraries/klc/G1.3/ "Libraries are organized by functionality"
[G1.4]: http://kicad-pcb.org/libraries/klc/G1.4/ "English language should be used throughout libraries"
[G1.5]: http://kicad-pcb.org/libraries/klc/G1.5/ "Plural naming is to be avoided"
[G1.6]: http://kicad-pcb.org/libraries/klc/G1.6/ "Capitalization conventions"
[G1.7]: http://kicad-pcb.org/libraries/klc/G1.7/ "Library files use Unix style line endings"
[G1.8]: http://kicad-pcb.org/libraries/klc/G1.8/ "Components can only contain features supported in latest stable release"
[G1.9]: http://kicad-pcb.org/libraries/klc/G1.9/ "Dimensional units"
[G2.1]: http://kicad-pcb.org/libraries/klc/G2.1/ "Defining generic and atomic parts"
[S1.1]: http://kicad-pcb.org/libraries/klc/S1.1/ "Symbol libraries should be categorized by function"
[S2.1]: http://kicad-pcb.org/libraries/klc/S2.1/ "General symbol naming guidelines"
[S2.2]: http://kicad-pcb.org/libraries/klc/S2.2/ "Non-functional variations in part number should be replaced with wildcard"
[S2.3]: http://kicad-pcb.org/libraries/klc/S2.3/ "Where atomic parts are available in multiple footprint options, a separate symbol must be drawn for each footprint"
[S3.1]: http://kicad-pcb.org/libraries/klc/S3.1/ "Origin is centered on the middle of the symbol"
[S3.2]: http://kicad-pcb.org/libraries/klc/S3.2/ "Text fields should use a common text size of 50mils"
[S3.3]: http://kicad-pcb.org/libraries/klc/S3.3/ "Symbol outline and fill requirements"
[S3.4]: http://kicad-pcb.org/libraries/klc/S3.4/ "Symbols with complex functionality may incorporate simple functional diagrams"
[S3.5]: http://kicad-pcb.org/libraries/klc/S3.5/ "Pin connection points must be placed outside of the symbol"
[S3.6]: http://kicad-pcb.org/libraries/klc/S3.6/ "Pin name position offset"
[S3.7]: http://kicad-pcb.org/libraries/klc/S3.7/ "Pin numbering for exposed pads"
[S3.8]: http://kicad-pcb.org/libraries/klc/S3.8/ "Multi unit symbols"
[S4.1]: http://kicad-pcb.org/libraries/klc/S4.1/ "General pin requirements"
[S4.2]: http://kicad-pcb.org/libraries/klc/S4.2/ "Pins should be grouped by function"
[S4.3]: http://kicad-pcb.org/libraries/klc/S4.3/ "Rules for pin stacking"
[S4.4]: http://kicad-pcb.org/libraries/klc/S4.4/ "Pin electrical type"
[S4.5]: http://kicad-pcb.org/libraries/klc/S4.5/ "Pins not connected on the footprint may be omitted from the symbol"
[S4.6]: http://kicad-pcb.org/libraries/klc/S4.6/ "Hidden pins"
[S4.7]: http://kicad-pcb.org/libraries/klc/S4.7/ "Active low pins should be designated using a bar above the symbol name"
[S5.1]: http://kicad-pcb.org/libraries/klc/S5.1/ "Symbols with a default footprint link to a valid footprint file"
[S5.2]: http://kicad-pcb.org/libraries/klc/S5.2/ "Footprint filters should match all appropriate footprints"
[S6.1]: http://kicad-pcb.org/libraries/klc/S6.1/ "Component Reference Designator (RefDes)"
[S6.2]: http://kicad-pcb.org/libraries/klc/S6.2/ "Component fields must be filled appropriately"
[S6.3]: http://kicad-pcb.org/libraries/klc/S6.3/ "Component metadata is added to symbol (and all aliases)"
[S7.1]: http://kicad-pcb.org/libraries/klc/S7.1/ "Power flag symbols"
[S7.2]: http://kicad-pcb.org/libraries/klc/S7.2/ "Graphical symbols"
[F1.1]: http://kicad-pcb.org/libraries/klc/F1.1/ "Footprint libraries are categorized by function"
[F1.2]: http://kicad-pcb.org/libraries/klc/F1.2/ "Connector footprint libraries"
[F2.1]: http://kicad-pcb.org/libraries/klc/F2.1/ "General footprint naming conventions"
[F2.2]: http://kicad-pcb.org/libraries/klc/F2.2/ "Footprint naming field prefixes"
[F2.3]: http://kicad-pcb.org/libraries/klc/F2.3/ "Manufacturer specific version of generic footprints"
[F2.4]: http://kicad-pcb.org/libraries/klc/F2.4/ "Footprint naming for non-standard pin numbering"
[F2.5]: http://kicad-pcb.org/libraries/klc/F2.5/ "Footprint naming conventions for specific components"
[F3.1]: http://kicad-pcb.org/libraries/klc/F3.1/ "SMD chip package naming conventions"
[F3.2]: http://kicad-pcb.org/libraries/klc/F3.2/ "Resistor naming conventions"
[F3.3]: http://kicad-pcb.org/libraries/klc/F3.3/ "Capacitor naming conventions"
[F3.4]: http://kicad-pcb.org/libraries/klc/F3.4/ "SMD IC package naming conventions"
[F3.5]: http://kicad-pcb.org/libraries/klc/F3.5/ "THT IC package naming conventions"
[F3.6]: http://kicad-pcb.org/libraries/klc/F3.6/ "Connector naming conventions"
[F3.7]: http://kicad-pcb.org/libraries/klc/F3.7/ "Fuse naming conventions"
[F4.1]: http://kicad-pcb.org/libraries/klc/F4.1/ "Datasheet recommendations take priority"
[F4.2]: http://kicad-pcb.org/libraries/klc/F4.2/ "Pin 1 should be located at the top left"
[F4.3]: http://kicad-pcb.org/libraries/klc/F4.3/ "Connected copper elements have the same pad number"
[F4.4]: http://kicad-pcb.org/libraries/klc/F4.4/ "Thermal pads"
[F4.5]: http://kicad-pcb.org/libraries/klc/F4.5/ "Specifying footprint keepout areas"
[F4.6]: http://kicad-pcb.org/libraries/klc/F4.6/ "Local clearance and settings should be set to zero"
[F5.1]: http://kicad-pcb.org/libraries/klc/F5.1/ "Silkscreen layer requirements"
[F5.2]: http://kicad-pcb.org/libraries/klc/F5.2/ "Fabrication layer requirements"
[F5.3]: http://kicad-pcb.org/libraries/klc/F5.3/ "Courtyard layer requirements"
[F6.1]: http://kicad-pcb.org/libraries/klc/F6.1/ "Footprint placement type must be set to surface mount"
[F6.2]: http://kicad-pcb.org/libraries/klc/F6.2/ "Footprint anchor should be placed in the middle of the component body"
[F6.3]: http://kicad-pcb.org/libraries/klc/F6.3/ "Pad requirements for SMD footprints"
[F7.1]: http://kicad-pcb.org/libraries/klc/F7.1/ "Footprint placement type must be set to Through Hole"
[F7.2]: http://kicad-pcb.org/libraries/klc/F7.2/ "Footprint anchor should placed at the location of Pin-1"
[F7.3]: http://kicad-pcb.org/libraries/klc/F7.3/ "Pin 1 should be rectangular, and other pads circular or oval"
[F7.4]: http://kicad-pcb.org/libraries/klc/F7.4/ "Pad requirements for THT footprints"
[F7.5]: http://kicad-pcb.org/libraries/klc/F7.5/ "Minimum annular ring width"
[F7.6]: http://kicad-pcb.org/libraries/klc/F7.6/ "Minimum hole diameter"
[F8.1]: http://kicad-pcb.org/libraries/klc/F8.1/ "Virtual components"
[F9.1]: http://kicad-pcb.org/libraries/klc/F9.1/ "Footprint meta-data is filled in as appropriate"
[F9.2]: http://kicad-pcb.org/libraries/klc/F9.2/ "Footprint properties are as default values unless otherwise required in datasheet"
[F9.3]: http://kicad-pcb.org/libraries/klc/F9.3/ "Footprint 3D model requirements"
[M1.1]: http://kicad-pcb.org/libraries/klc/M1.1/ "Models should be created by contributor"
[M1.2]: http://kicad-pcb.org/libraries/klc/M1.2/ "Manufacturer models should not be duplicated"
[M1.3]: http://kicad-pcb.org/libraries/klc/M1.3/ "Source files for 3D models should be supplied"
[M2.1]: http://kicad-pcb.org/libraries/klc/M2.1/ "Permitted 3D model file types"
[M2.2]: http://kicad-pcb.org/libraries/klc/M2.2/ "Model alignment and scaling"

Thank you for making this first contribution to the kicad-footprints library!

There are some changes I'd like to have made before this can be merged:

* The footprint name should be `WQFN-20-1EP_2.5x4.5mm_P0.5mm_EP1x2.9mm`.  The number of EPs should be listed after the pin number and the EP dimensions in the name should be for the pad on the footprint, not on the chip itself.  The dimensions should be listed with X first.
* The EP is currently very slightly off-center.  Please center it on the origin.
* The EP should have paste coverage of 50-80%.  See the part of [F6.3] about custom stencil openings for information on how to achieve this.
* The courtyard clearance is 0.05 mm too big on the left and right ([F5.3]).  The courtyard rectangle should be 4x6mm overall for this part (unusually round dimensions!).
* The F.Fab reference designator should be oriented 0°, and scaled down to fit inside the body outline ([F5.2]).
* The value text should be set back to the default size and orientation, and moved to the bottom of the footprint.
* The silkscreen reference designator should be moved to the top of the footprint.
* The silkscreen outline needs some improvement.  Rules for it are at [F5.1].
  * It should outline the body rectangle, not the courtyard rectangle.  The final silkscreen outline for this part should consist of marks at the corners, like the other QFN parts in the library.  The lines should ideally have an offset of 0.11 or 0.12 mm from the body outline (but don't follow the chamfer at the pin 1 corner).  The line next to pin 1 should be removed, to act as a pin 1 indicator, leaving 7 silkscreen lines in total.

Finally, once everything looks good with this footprint, if you'd like, it would be great if you could make a second version of this footprint with thermal vias.  Totally up to you if you want to or not.

**Comment by awygle** [comment]
I have some responses to some of these comments. Note that these are _not_ me refusing to make these changes, or complaining about the feedback, but rather suggestions for how the KLC could be improved (is there a place to make PRs against the conventions?)

> - The footprint name should be WQFN-20-1EP_2.5x4.5mm_P0.5mm_EP1x2.9mm. The number of EPs should be listed after the pin number and the EP dimensions in the name should be for the pad on the footprint, not on the chip itself. The dimensions should be listed with X first.

The KLC says in F.2.2: "_If there is more than one exposed pad_, **prepend** with the pad count" (emphasis mine). The example immediately below that rule  contradicts the "prepend" directive by **ap**pending the count. The KLC doesn't say anywhere that the footprint dimensions should be used rather than those of the part.

> - The F.Fab reference designator should be oriented 0°, and scaled down to fit inside the body outline (F5.2).

The KLC says in F5.2: "Orientation of RefDes should match major component axis", but the term "major component axis" is never defined.

> - The silkscreen reference designator should be moved to the top of the footprint.

Section F5.1 of the KLC says "Reference Designator must be drawn on F.SilkS layer" but does not specify location (nor, indeed, orientation).

> - The silkscreen outline needs some improvement. Rules for it are at F5.1. 

Section F5.1 of the KLC does not even specify a requirement for a silkscreen outline, much less what form it should take. In my opinion it should at a minimum specify the requirements for a Pin 1 indicator.

For this piece of feedback in particular, if you could point me at a component to use as a reference, that would be helpful - I actually copied this "two lines, one line longer than the other" format from another component.

**Comment by awygle** [comment]
All of the above changes have  been made.

**Comment by Ratfink** [comment]
Looks great, thanks for making the changes!  The one thing I'd like to suggest is that you change the silkscreen line width to 0.12 mm (0.15 mm is for low density designs, and I don't think I could call a 0.5-mm-pitch QFN a low density part).  The lines extend a bit closer towards the pads than KLC currently says they should, but we're planning on reducing the required clearance in KLC to [the silkscreen line width used in the footprint], so it's not a problem.

Once that's done, would you like to make a _ThermalVias version or should I merge this PR with just the one footprint?

**Comment by awygle** [comment]
I shrank the lines. Because there's no manufacturer recommendation for thermal vias in the datasheet, I'd rather not create a thermal via version of the footprint - please go ahead and merge with just the one.

**Comment by Ratfink** [comment]
Thanks for the good work!

**Pull request merged**
