### PR TITLE
Fix Neutrik NMJ6HCD2 audio jack footprint

### PR DESCRIPTION
**Pull request by pushytoxin**
-Rename 3.5mm -> 6.3mm
-Make pads compatible with the audio jack symbols
-Place pin 1 at the top-left
-Fix silkscreen clearance

### CODE REVIEW

**Comment by pushytoxin** [comment]
Original PR was #272, a trivial change was done on the github text editor.

I've cleaned up a few more things about this footprint, but I couldn't change the other PR.

**Comment by pushytoxin** [comment]
Looks like I saved the part to the library incorrectly because I edited the footprint directly from the PCB layout.

The 3D model was also missing.

**Comment by pushytoxin** [comment]
I added a 3d model to the library, Travis seems to need it.

https://github.com/KiCad/kicad-packages3D/pull/225

**Comment by pushytoxin** [comment]
screenshot_20180120_220332

**Comment by pushytoxin** [comment]
screenshot_20180120_220914

**Comment by poeschlr** [comment]
The 3d settings should be:
- scale: 1,1,1
- rotation: 0,0,0
- offset: 0,0,0

Only one single measurement of this footprint conforms with the datasheet. The courtyard clearance should be 0.5mm all around.
screenshot from 2018-01-30 00-40-29

**Comment by Shackmeister** [comment]
Hi @pushytoxin are you still working on this one?

**Comment by pushytoxin** [comment]
I already completed my board with the my current version, but I want to clean things up so it can be merged. I've just been too busy in the past few weeks to get around to doing it.
Give me a few days, I'll get around doing it eventually!

**Comment by evanshultz** [comment]
I'm trying to get answers to questions about audio jacks at https://github.com/KiCad/kicad-symbols/pull/310, and then I'll be adding footprints for every audio jack Neutrik makes. Including this one. So if it doesn't matter to have this done right away, you can close it and I'll take care of it shortly

Thanks, but we happened to be working on the same thing in this case. We'd be happy to see future PRs from you!

**Comment by diegoherranz** [comment]
Please note filename (and a few other references) incorrectly say Neutric instead of Neutrik.
Thanks.

**Comment by evanshultz** [comment]
Thanks! I noted this at https://github.com/KiCad/kicad-footprints/issues/191#issuecomment-359552482 and will fix it when I push my footprints if it's not done by then.

**Comment by diegoherranz** [comment]
Thanks, @evanshultz

**Comment by pushytoxin** [comment]
This PR is in limbo right now. It started out with me fixing its name, but it turns out there are issues with the dimensions as well.

I don't see this being merged in the future, as this conflicts with @evanshultz's more complete work of rebuilding the audio connector library from scratch.

**Pull request closed without merging**
