### PR TITLE
update Molex 47346 USB connector

### PR DESCRIPTION
**Pull request by florolf**
Molex has published a [PCN](https://media.digikey.com/pdf/PCNs/Molex/pcn506286.pdf) recommending a new footprint for the 47346 USB receptacle. Update the library footprint to match.

FWIW, this change has been rolled up into the current version of the [product drawing](http://www.molex.com/pdm_docs/sd/473460001_sd.pdf), as referenced in the footprint.

Screenshot of the updated footprint:

2019-09-02-223454_680x588_scrot

### CODE REVIEW

**Comment by nfbraun** [comment]
Pads look ok to me.

The datasheet for the connector (https://www.molex.com/pdm_docs/sd/473460001_sd.pdf) specifies a "pick and place area", the center of which is different from the footprint anchor. (This is independent of this pull request, which does not change the footprint anchor position.)

**Comment by poeschlr** [comment]
The courtyard clearance is not correct. (must be 0.5mm all around, rounded to 0.01mm grid but that does not apply here)

grafik

**Comment by florolf** [comment]
Fixed in a separate commit for easier review. Ping me and I'll squash it before merging.

I'm curious: How did you create that dimensioned drawing? Was this done manually or is there a script for that?

**Comment by poeschlr** [comment]
No need for you to squash it, github offers us a one click solution that does that.

**Comment by poeschlr** [comment]
Courtyard still not correct in y direction

**Comment by florolf** [comment]
What am I missing?
2019-09-21-153316_1494x720_scrot
2019-09-21-153337_1004x566_scrot

**Comment by poeschlr** [comment]
are you sure you pushed your last stuff?
grafik

**Comment by poeschlr** [comment]
Wait a moment. I think i had the wrong footprint open!

**Comment by poeschlr** [comment]
Yes it was on my end. Sorry about that (had the path variable set to the wrong version of the library)

**Comment by florolf** [comment]
No worries, I keep running into the same problem. :)

Thank you for the review!

**Pull request merged**
