### PR TITLE
Stocko fix

### PR DESCRIPTION
**Pull request by balcer**
During 3D model generation I noted that I broke footprints. 

stocko

https://www.stocko-contact.com/downloads/steckverbindersystem-raster-2,5-mm.pdf#page=15

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@balcer many files changed here, is it really wanted ? Please have a look at the git diff, thanks!

**Comment by evanshultz** [comment]
The CONNFLY USB connector is probably an accident. All other changes files are Stocko MKS parts. Note that I didn't check each one, just quickly looked at changed files.

https://github.com/pointhi/kicad-footprint-generator/pull/298 is the PR for the script fix that drove this, so these are generated by script, which is why some footprints only had the time stamp changed.

**Comment by myfreescalewebpage** [comment]
> The CONNFLY USB connector is probably an accident

Yes I think too

**Comment by balcer** [comment]
Now should be ok. sorry for problems

**Comment by evanshultz** [comment]
I just quickly checked the script fix and it did add the -X offset at 3.6mm from pin 1, which is the correct dimension in the datasheet. I added more notes at the script PR that don't affect the footprint.

Looking at the code paths, and even though they were submitted and checked at https://github.com/KiCad/kicad-footprints/pull/1403, I dimensioned both 2-pin, the 3-pin, and the highest pin count footprints:
image

**Comment by balcer** [comment]
thx

**Pull request merged**
