### PR TITLE
Fix F.Paste of Quectel BC66

### PR DESCRIPTION
**Pull request by jneiva08**
Fixed F.Paste in accord of Quectel SMT Application Note
Link: https://www.quectel.com/UploadImage/Downlad/Quectel_Module_Secondary_SMT_Application_Note_V2.7.pdf#page=14

Screenshot:
bc66

Have fixed the footprints in PR  https://github.com/KiCad/kicad-footprints/pull/1943 and https://github.com/KiCad/kicad-footprints/pull/2239

Please let me know if missed something.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by poeschlr** [comment]
You have shifted both the inside and outside edge of past by 0.2mm instead of the outside by 0.4mm.
The pad width should be reduced to 85%.

**Comment by jneiva08** [comment]
For the inner circle try to go by 65% of 1mm2, then got radius of 0.45mm
My error was to suppose "Size X" is radius and not diameter. I will change to 0.9mm

**Comment by jneiva08** [comment]
For the F.Paste should change length to 2.7 to have outside 0.4
The width should be 0.595
@poeschlr I'm wrong?

**Comment by poeschlr** [comment]
My suggestion is to make the change for one pad and then measure if the result is correct. You can also create a sketch in a parametric CAD system like FreeCAD and get the measurements from there.

**Comment by jneiva08** [comment]
@poeschlr have made the changes requested

**Comment by poeschlr** [comment]
thanks

**Comment by jneiva08** [comment]
Thanks for your time.
In weekend hope to finish the changes for BC95.

**Pull request merged**
