### PR TITLE
Add D_SOD-123W

### PR DESCRIPTION
**Pull request by chschlue**
https://assets.nexperia.com/documents/outline-drawing/SOD123W.pdf
https://assets.nexperia.com/documents/data-sheet/PMEG40T10ER.pdf

D_SOD-123W
sod-123w

https://github.com/KiCad/kicad-symbols/pull/2213

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. See my comments about fab lines for the SOT1289 footprint.
1. Is this manufacturer-specific even if there are similar packages elsewhere? http://rohmfs.rohm.com/en/products/databook/datasheet-nrnd/discrete/diode/schottky_barrier/rb160m-40.pdf and https://www.taiwansemi.com/products/datasheet/SS14LW%20SERIES_B1906.pdf are both 'SOD123W' at DigiKey, and Taiwan Semi even uses the same package name, but they're subtly different. And the recommended footprints don't match.

Dimensions match the datasheet.

**Comment by chschlue** [comment]
The Rohm SOD-123 appears to be a SOD-123F (thin and flat leads), SOD-123 is thick with gullwings, this SOD-123W is thick with flat leads and TaiwanSemi's SOD-123W is larger than this one.

Not sure what to make of that.

**Comment by chschlue** [comment]
The Taiwan Semi package seems to be the freak among the SOD-123s, maybe that one should be manufacturer specific?

**Comment by poeschlr** [comment]
The rohm one claims to follow JEDEC. maybe a good idea would be to check the standard document, it could be that it gives guidance for how to classify these.

**Comment by chschlue** [comment]
I think JEDEC only specifies gullwing SOD (DO-215). Not sure what Rohm was up to.

The flat lead variants seem to be either JEITA or industry standards.

**Comment by chschlue** [comment]
Renamed to `Nexperia_CFP3_SOD-123W`. Also fixed silk clearance.

**Comment by myfreescalewebpage** [comment]
@chschlue I had a look to this footprint:
- F.Fab ok, pads ok, F.CrtYd ok
- F.SilkS: on the left the silkscreen is a little too much on the left, particularly when I compare to the nomal D_SOD 123 footprint
Joel

**Comment by chschlue** [comment]
Not sure what you mean.
This one has 0.2mm clearance, as recommended (F5.1)
D_SOD-123 only has 0.09mm, which is less than required.

**Comment by myfreescalewebpage** [comment]
See above screenshot, I just measure 0.25mm from the left pad, instead of 0.2mm:

Capture

**Comment by chschlue** [comment]
Now I get it. It's fine nonetheless.

Silk clearance is to be measured from the edge of the line, not from the center (because silk is physical paint on the board, as opposed to fab and crtyd lines, which are virtual and have zero physical width.)

**Comment by myfreescalewebpage** [comment]
ooooh this trouble me and I was wrong since a long time in this case ?
When using generators I don't think this is from the border, it's to the center of the silkscreen line in my memory.
I have just check with some phoenix connectors.

**Comment by myfreescalewebpage** [comment]
New look at the footprint, ok to merge

**Pull request merged**
