### PR TITLE
Adding Texas_VSON-HR-8_1.5x2mm_P0.5mm

### PR DESCRIPTION
**Pull request by ki5libs**
Adding Texas_VSON-HR-8_1.5x2mm_P0.5mm footprint
[Datasheet](http://www.ti.com/lit/ds/symlink/tps62823.pdf)

Texas_VSON-HR_1 5x2mm_P0 5mm

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
This is a generic no lead package so it must use our IPC generator script found at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by ki5libs** [comment]
Hi @poeschlr 

Got it. I made the [PR](https://github.com/pointhi/kicad-footprint-generator/pull/429), but I have couple questions:
- generated footprint has pads length much more longer than datasheet recommends (0.8 mm vs 0.55 mm), is it OK?
- generated footprint has a different name (Texas_VSON-8_1.5x2mm_P0.5mm vs Texas_VSON-HR_1.5x2mm_P0.5mm), I'm not sure which one should be used finally

Texas_VSON-8_1 5x2mm_P0 5mm

Just let me know your opinion. I will update this footprint after that. Thanks.

**Comment by poeschlr** [comment]
The generator is not intended to replicate the suggested footprint but uses the part dimensions and the industry standard IPC-7351B to generate the land pattern. Your original name did violate the KLC. You can use VSON-HR to include the HR part in the name.

**Comment by ki5libs** [comment]
Updated

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
