### PR TITLE
LFCSP 3x3mm P0.5mm EP1.5x1.85mm

### PR DESCRIPTION
**Pull request by calebns**
Footprint required by
http://www.analog.com/media/en/technical-documentation/data-sheets/ADL5542.pdf
image

image
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
What was the reason to not make the footprint like the recommendation with the EP and 4 pins joined together? Were you tying to make this a more general-purpose footprint? If so, and what's great, I think we should also have one specific for ADI that is to their recommendation and assigned to the ADL5542 symbol.

**Comment by calebns** [comment]
OK, that one will be tricky. I left the generic symbol and added ADI specific.
What should I do with pad numbering? I don't want to modify assignment on schematic symbol, but that means I need to connect 2,3,6,7 with pad 9. Let me know if footprint below is fine.

image

**Comment by evanshultz** [comment]
This footprint will be ADI-specific, and the symbol of course is too, so we can do whatever we want. You can have just one pin 9 on both (5 pins total on the symbol). There isn't anything generic about a symbol for a specific device, and in this case we need a custom footprint too. Am I misunderstanding your concern?

Alternatively, you can draw a line on a different layer and then change it to F.Cu either in the GUI or a text editor. You lose DRC functions doing this, though, so it's not a good idea. To be honest, I'm not sure I'd merge a footprint like this. Here's an image after doing it on the lower one and getting the warning for the upper one:
image

Shrink down the ref des on F.Fab to fit within the part outline.

Lastly, your silkscreen is unlike other similar footprints. And it goes under the package body which is verboten. Here's a better idea:
image

Once you take a look at that and play around a bit, let me know where you're at and I'll give a proper review. I feel like now we're just figuring out how to make this footprint.

One more thing: our prefix for ADI parts is `Analog_` as you can see at https://github.com/KiCad/kicad-footprints/tree/master/Package_TO_SOT_SMD.pretty. Just like we use `Texas_` for TI parts. One of those things you just have to know since I don't think it's written down anywhere...

**Comment by evanshultz** [comment]
And also, the footprint name should show the EP size as 1.53x1.85mm. The first number in your footprint is only 1.5.

Here is my footprint code:
```
(module ADI_LFCSP-8-1EP_3x3mm_P0.5mm_EP1.5x1.85mm (layer F.Cu) (tedit 5A9E3C27)
  (descr "LFCSP 8pin Pitch 0.5mm, ADI, http://www.analog.com/media/en/technical-documentation/data-sheets/ADL5542.pdf")
  (tags "ADI LFCSP 8pin thermal pad 3x3mm Pitch 0.5mm")
  (attr smd)
  (fp_text reference REF** (at 0 -2.5) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value ADI_LFCSP-8-1EP_3x3mm_P0.5mm_EP1.5x1.85mm (at 0 2.5) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start -1.37 -0.25) (end 1.37 -0.25) (layer F.Cu) (width 0.28))
  (fp_text user %R (at 0 0) (layer F.Fab)
    (effects (font (size 0.7 0.7) (thickness 0.1)))
  )
  (fp_line (start -1 -1.5) (end -1.5 -1) (layer F.Fab) (width 0.1))
  (fp_line (start -1.62 1.62) (end -1.62 -1.62) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.62 1.62) (end -1.62 1.62) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.62 -1.62) (end 1.62 1.62) (layer F.CrtYd) (width 0.05))
  (fp_line (start -1.62 -1.62) (end 1.62 -1.62) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.5 1.5) (end 1.5 -1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.5 1.5) (end -1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start -1.5 -1) (end -1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start -1 -1.5) (end 1.5 -1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.6 -1.6) (end 1.6 -1.1) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.6 1.6) (end 1.6 1.1) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.6 1.6) (end -1.6 1.1) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.6 1.6) (end 1.6 1.6) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.37 0.25) (end 1.37 0.25) (layer F.Cu) (width 0.28))
  (fp_line (start -1.6 -1.6) (end 1.6 -1.6) (layer F.SilkS) (width 0.12))
  (pad 1 smd rect (at -1.37 -0.75) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 2 smd rect (at -1.37 -0.25) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 3 smd rect (at -1.37 0.25) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 4 smd rect (at -1.37 0.75) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 5 smd rect (at 1.37 0.75) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 6 smd rect (at 1.37 0.25) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 7 smd rect (at 1.37 -0.25) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 8 smd rect (at 1.37 -0.75) (size 0.71 0.28) (layers F.Cu F.Paste F.Mask))
  (pad 9 smd rect (at 0 0) (size 1.5 1.85) (layers F.Cu F.Mask))
  (pad "" smd rect (at 0 0) (size 1.2 1.55) (layers F.Paste))
  (model ${KISYS3DMOD}/Package_CSP.3dshapes/LFCSP-8-1EP_3x3mm_P0.5mm.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)

```

**Comment by calebns** [comment]
I've used a pin number 9 to mark all GND pins in Analog footprint.
Also, modified drawings to avoid silkskreen to be under the package in both symbols (ADI and generic)

image

**Comment by evanshultz** [comment]
@calebns 
Thanks! We still have more work to do.
1. Should the big pin be 9? Perhaps 2 would be better since at https://github.com/KiCad/kicad-symbols/pull/349 pin 2 is visible in the symbol.
1. That center pad was only 1.5mm wide and it should be 1.53mm.
1. Remove the silk circle for pin 1. Leaving off the vertical silk line on the top left, as I did above, is the pin 1 mark on silk.
1. Your silk outline is composed of a whole bunch of lines, not just 5.
1. The F.Fab text looks like it can be a little bit bigger.
1. You could simplify the footprint by using just seven pin 9s: one rectangle in the middle and two long but narrow ones spanning all the way from pin 2-7 and 3-6, and then those 4 outer pins to give mask clearance (or you could add separate mask clearance pads).
1. You will want copper over the whole area connecting the thermal pad and pins 2, 3, 6, and 7, but that entire area should probably not have exposed mask or be fully covered with paste. I would avoid bridging the outer pins and thermal pad with copper, so avoid totally removing mask. Then you can treat the paste on outer pads and exposed pad separately.
1. How did you choose the paste pad size of 1.2x1.55mm in the middle of the footprint?
1. The courtyard is outside the extents of the body or pads by 0.25mm.
1. The 3D model needs to have the EP size in the name. For the ADI-specific one it can keep the generic LFCSP 3D model.
1. Silk-to-pad clearance should be at least the silk width of 0.12mm.
1. The BXL file for this footprint is terribly mis-matched with the datasheet recommendation and I object to using any part of it except for the pad width, which is 0.305mm. The not-ADI version can keep 0.28mm tall pads if you like.

Since I made it to check, here is a fixed footprint (but without mask openings on pins 2-3 and 6-7):
image

```
(module Analog_LFCSP-8-1EP_3x3mm_P0.5mm_EP1.53x1.85mm (layer F.Cu) (tedit 5AA6C336)
  (descr "LFCSP, exposed pad, Analog Devices (http://www.analog.com/media/en/technical-documentation/data-sheets/ADL5542.pdf)")
  (tags "LFCSP 8 0.5")
  (attr smd)
  (fp_text reference REF** (at 0 -2.5) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value Analog_LFCSP-8-1EP_3x3mm_P0.5mm_EP1.53x1.85mm (at 0 2.5) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text user %R (at 0 0 180) (layer F.Fab)
    (effects (font (size 0.7 0.7) (thickness 0.15)))
  )
  (fp_line (start -1 -1.5) (end -1.5 -1) (layer F.Fab) (width 0.1))
  (fp_line (start -1.98 1.75) (end -1.98 -1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.98 1.75) (end -1.98 1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.98 -1.75) (end 1.98 1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start -1.98 -1.75) (end 1.98 -1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.5 1.5) (end 1.5 -1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.5 1.5) (end -1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start -1.5 -1) (end -1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start -1 -1.5) (end 1.5 -1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.62 -1.62) (end -1.62 -1.62) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.62 -1.62) (end 1.62 -1.15) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.62 1.15) (end 1.62 1.62) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.62 1.62) (end -1.62 1.62) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.62 1.62) (end -1.62 1.15) (layer F.SilkS) (width 0.12))
  (pad 1 smd rect (at -1.37 -0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad "" smd rect (at -1.37 -0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad "" smd rect (at 1.37 -0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad "" smd rect (at -1.37 0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad "" smd rect (at 1.37 0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad 2 smd rect (at 0 -0.25) (size 3.45 0.305) (layers F.Cu))
  (pad 4 smd rect (at -1.37 0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad 5 smd rect (at 1.37 0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad 8 smd rect (at 1.37 -0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad 2 smd rect (at 0 0) (size 1.53 1.85) (layers F.Cu F.Mask))
  (pad "" smd rect (at 0 0) (size 1.2 1.55) (layers F.Paste))
  (pad 2 smd rect (at 0 0.25) (size 3.45 0.305) (layers F.Cu))
  (model ${KISYS3DMOD}/Package_CSP.3dshapes/LFCSP-8-1EP_3x3mm_P0.5mm.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)
```

You could also use a polygon pad shape if you're using a recent pre-release version of KiCad, but the mask and paste layers are more complicated. Here is an example (because polygon pads are very new please check it thoroughly yourself):
```
(module Analog_LFCSP-8-1EP_3x3mm_P0.5mm_EP1.53x1.85mm (layer F.Cu) (tedit 5AA6CA4E)
  (descr "LFCSP, exposed pad, Analog Devices (http://www.analog.com/media/en/technical-documentation/data-sheets/ADL5542.pdf)")
  (tags "LFCSP 8 0.5")
  (attr smd)
  (fp_text reference REF** (at 0 -2.5) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value Analog_LFCSP-8-1EP_3x3mm_P0.5mm_EP1.53x1.85mm (at 0 2.5) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text user %R (at 0 0 180) (layer F.Fab)
    (effects (font (size 0.7 0.7) (thickness 0.15)))
  )
  (fp_line (start -1 -1.5) (end -1.5 -1) (layer F.Fab) (width 0.1))
  (fp_line (start -1.98 1.75) (end -1.98 -1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.98 1.75) (end -1.98 1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.98 -1.75) (end 1.98 1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start -1.98 -1.75) (end 1.98 -1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 1.5 1.5) (end 1.5 -1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.5 1.5) (end -1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start -1.5 -1) (end -1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start -1 -1.5) (end 1.5 -1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.62 -1.62) (end -1.62 -1.62) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.62 -1.62) (end 1.62 -1.15) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.62 1.15) (end 1.62 1.62) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.62 1.62) (end -1.62 1.62) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.62 1.62) (end -1.62 1.15) (layer F.SilkS) (width 0.12))
  (pad 1 smd rect (at -1.37 -0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad 4 smd rect (at -1.37 0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad 5 smd rect (at 1.37 0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad 8 smd rect (at 1.37 -0.75) (size 0.71 0.305) (layers F.Cu F.Paste F.Mask))
  (pad 2 smd custom (at 0 0) (size 1.53 1.85) (layers F.Cu)
    (zone_connect 0)
    (options (clearance outline) (anchor rect))
    (primitives
      (gr_poly (pts
         (xy -1.725 -0.4025) (xy -0.765 -0.4025) (xy -0.765 -0.925) (xy 0.765 -0.925) (xy 0.765 -0.4025)
         (xy 1.725 -0.4025) (xy 1.725 -0.0975) (xy 0.765 -0.0975) (xy 0.765 0.0975) (xy 1.725 0.0975)
         (xy 1.725 0.4025) (xy 0.765 0.4025) (xy 0.765 0.925) (xy -0.765 0.925) (xy -0.765 0.4025)
         (xy -1.725 0.4025) (xy -1.725 0.0975) (xy -0.765 0.0975) (xy -0.765 -0.0975) (xy -1.725 -0.0975)
) (width 0))
    ))
  (pad "" smd rect (at 0 0) (size 1.2 1.55) (layers F.Paste))
  (pad "" smd rect (at -1.37 -0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad "" smd rect (at 1.37 -0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad "" smd rect (at -1.37 0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad "" smd rect (at 1.37 0.25) (size 0.71 0.305) (layers F.Paste F.Mask))
  (pad "" smd rect (at 0 0) (size 1.53 1.85) (layers F.Mask))
  (model ${KISYS3DMOD}/Package_CSP.3dshapes/LFCSP-8-1EP_3x3mm_P0.5mm.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)
```

**Comment by calebns** [comment]
@evanshultz  I've used your part. Also, I've removed the generic one and left only ADI specific, as the generic does not comply to BXL files. There are at least 8 different LFCSP-8 on Analog webpage, so we might add them just when they are necessary.

As for the solder paste pad size, I couldn't find any recomendations, so used a rule-of-thumb 67% of coverage.

**Comment by evanshultz** [comment]
66% paste coverage is fine for me.

- Please see item 10 above. That needs a quick update.
- I also realized that the pad height was specified. We know the pads are 0.5mm apart and the total height is 1.78mm which means pad height is 0.28mm. Sorry that I was wrong. Would you mind the change that so we're adhering to the datasheet, now that I find the datasheet does include that dimension?

Here is the dimensional check showing all is well otherwise:
image

**Comment by evanshultz** [comment]
Thanks! This was a tricky footprint! And sorry that I didn't catch the dimension was present earlier.

**Pull request merged**
