### PR TITLE
Add footprints for XT60 male and female connectors.

### PR DESCRIPTION
**Pull request by reportingsjr**
Add footprints for male and female XT60 connectors. Yes, these are technically wire to wire connectors, but lots of people have been using them as PCB mount connectors.

I created the footprints by measuring a handful of physical connectors (purchased through hobbyking so they are legitimate parts) and finding the average pin diameter (~4.3mm) and adding the IPC standard 0.2mm clearance.

Here is the only datasheet really available for it: https://www.tme.eu/en/Document/2d152ced3b7a446066e6c419d84bb460/XT60%20SPEC.pdf

This PR should also close #1462 if it is accepted.

3D model PR: https://github.com/KiCad/kicad-packages3D/pull/603

Male connector footprint:
XT60 male

Female connector footprint:
XT60 female

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by reportingsjr** [comment]
Hmmm, it is failing and saying some silkscreen in intersecting with pad 1. By chance is the script checking the pad as if it is a square pad rather than a rounded rectangle pad?

**Comment by poeschlr** [comment]
The fab layer is correctly representing the nominal body size (measured using the kicad internal measure tool -> not persistent so no nice screenshot.) But the silk screen should be fully outside the nominal body (as it will otherwise be covered by the body)

Move the fab reference inside the body outline (center).

**Comment by reportingsjr** [comment]
Ok, I went ahead and bumped the silkscreen out a bit so it won't be under the body of the connector. I didn't go too far as I'm not a huge fan of silkscreen that is way bigger than connectors, but I can go further if that is your preference.

I shrunk down the fab layer reference to the minimum mentioned in the KLC (0.5mm in KLC 5.2) and centered it on the connector body.

**Comment by poeschlr** [comment]
There is no need to shrink the reference for this huge component. Please keep it at 1mm size.

**Comment by reportingsjr** [comment]
Ohhh, I misread KLC F5.2 4C. I didn't see the part where it says to scale the reference only if it is overlapping parts of the same layer. Fixed!

**Comment by poeschlr** [comment]
Thanks

**Comment by reportingsjr** [comment]
@poeschlr would you mind looking at  KiCad/kicad-packages3D#603 so this can have the 3d model as well?

**Pull request merged**
