### PR TITLE
Add molex EDGELOCK

### PR DESCRIPTION
**Pull request by asukiaaa**
I add 6pins version EDGELOCK.
If 6pins version pass review, I will add 2, 4, 8 version with using footprint generator script.
Thank you.

Datasheet: https://www.molex.com/pdm_docs/sd/2008900106_sd.pdf

screenshot from 2018-10-29 22-52-30

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
So was this done with a script? If so, please submit the script as a PR and link it here so we can inspect the script. That's the most important thing.

And really, it's so easy to add more footprints via script that there's no harm in going ahead and adding all of them at once. Updating due to any feedback is just one click.

**Comment by asukiaaa** [comment]
This is the script.
https://github.com/pointhi/kicad-footprint-generator/pull/215
I willtI share a script and a footprint together next time.

**Comment by asukiaaa** [comment]
I add 2, 4 and 8.

screenshot from 2018-11-02 07-46-50
screenshot from 2018-11-02 07-47-39
screenshot from 2018-11-02 07-48-16

**Comment by poeschlr** [comment]
Sorry for the long delay. It seems you pull request got a bit forgotten.

Add a note on the comments layer and indicator on the dwgs layer for the chamfered leading edge.
Maybe also a note about the maximum internal radii.

I am not sure what note 6 means but it seems important.

Dimensions look good. For reference:
Screenshot from 2019-06-01 09-51-32

**Comment by asukiaaa** [comment]
Thank you for the feedback but I'm not clear what you require.
Please let me to ask questions.

> Add a note on the comments layer and indicator on the dwgs layer for the chamfered leading edge.
> Maybe also a note about the maximum internal radii.

What note should I add to dwgs layer?
Do you require me to add guide of length like a picgure you showed?
Could you show some example?

> I am not sure what note 6 means but it seems important.

The `6` means 6 on tile of this issue?
The reason of 6 is the first footprint that I show was EDGELOCK 6-CKT.
You reviewed EDGELOCK 8-CKT so I remove 6 from title.

> Dimensions look good.

Thank you for checking.

**Comment by poeschlr** [comment]
With note 6 i mean note 6 in the datasheet.

---

Regarding markings: A bit of text and a few lines should be enough. A quick draft as inspiration (made on your screenshot using inkscape)

47884377-d622a480-de73-11e8-9495-1b717f796096

But you can of course make a wonderful drawing for these if you are overly motivated. (These should just be notes for the designer such that they remember to ask the manufacturer for special treatment.)

**Comment by asukiaaa** [comment]
Thank you for the feedback.

I updated the footprints.
- Use rounded lines for Edge.Cuts.
- Add comment and lines about chamfer for Cmts.User.

Screenshot from 2019-06-02 15-02-02

Do I need to put lies for chamfer on Margin layer because you use pink lines for example?

**Comment by poeschlr** [comment]
I used pink because that is what inkscape was setup from the last time i used it. You have placed both the text and line on the cmts layer. We typically put drawings onto the dwgs.user layer.

**Comment by asukiaaa** [comment]
Thank you for the feedback.
I change layer to put lines about chamfer as Dwgs.User.
Screenshot from 2019-06-02 15-54-12

**Comment by poeschlr** [comment]
thanks

**Comment by asukiaaa** [comment]
Thank you for checking and merging.

**Pull request merged**
