### PR TITLE
Add Coilcraft XAL60xx

### PR DESCRIPTION
**Pull request by jneiva08**
Added Coilcraft XAL60xx

Datasheet: https://www.coilcraft.com/pdfs/xal60xx.pdf

footprint:
xal

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by johnbeard** [comment]
Dimensions look sane to me.

Should the coil orientation be marked in any way? Depending on application, there could be a reason to mount one way and not the other?

2019-03-02_143635_692x652_screenshot
2019-03-02_143657_366x435_screenshot

**Comment by poeschlr** [comment]
Marking the orientation might indeed be valid even for inductors. (If they are marked on the package)

I think this would be the first one to get a marking. I would suggest an IPC standard polarity marking (chamfer top left edge and extend silk around left side. Look at tantal caps for inspiration)

**Comment by jneiva08** [comment]
@poeschlr have added cut in F.Fab and line in F.Silk like the tantalum capacitor.

xal6060

This  series only have 2 heights XA6030 (3.1mm) and XAL6060 (6.1mm), make sense to separate?

In  Inductor_SMD have another 2 footprint of XAL5030 and XAL4040, is recommended to add orientation line?

**Comment by poeschlr** [comment]
We have decided that we follow the KLC more closely even for inductors. This means you should include the body size in the footprint name.
Meaning the name should be: `L_Coilcraft_XAL60xx_6.36x6.56mm`

The chamfer on the fab layer is a bit large. Should be at most 1mm in x and y direction.

**Comment by jneiva08** [comment]
shoud include hight? `L_Coilcraft_XAL6030_6.36x6.56x3.1mm` and `L_Coilcraft_XAL6060_6.36x6.56x6.1mm`

**Comment by poeschlr** [comment]
we do not typically include the height at this point in time.

**Comment by jneiva08** [comment]
@poeschlr , have made the changes requested

**Comment by poeschlr** [comment]
thanks

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
