### PR TITLE
Scripted UQFN footprints

### PR DESCRIPTION
**Pull request by poeschlr**
https://github.com/pointhi/kicad-footprint-generator/pull/292

These do not require any changes on the symbol side. (same names and some are not even used right now.)

---

http://ww1.microchip.com/downloads/en/DeviceDoc/40001839B.pdf#page=464

screenshot from 2019-02-07 22-57-42

```yaml
UQFN-20-1EP_4x4mm_P0.5mm_EP2.8x2.8mm:
  device_type: 'UQFN'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://ww1.microchip.com/downloads/en/DeviceDoc/40001839B.pdf#page=464'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  # custom_name_format:
  body_size_x:
    nominal: 4
  body_size_y:
    nominal: 4
  overall_height:
    minimum: 0.45
    nominal: 0.5
    maximum: 0.55

  lead_width:
    minimum: 0.2
    nominal: 0.25
    maximum: 0.3
  lead_len:
    minimum: 0.3
    nominal: 0.4
    maximum: 0.5

  EP_size_x:
    minimum: 2.6
    nominal: 2.7
    maximum: 2.8
  EP_size_x_overwrite: 2.8
  EP_size_y:
    minimum: 2.6
    nominal: 2.7
    maximum: 2.8
  EP_size_y_overwrite: 2.8
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [2, 2]

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    EP_num_paste_pads: [2, 2]
    #paste_between_vias: 1
    #paste_rings_outside: 1
    EP_paste_coverage: 0.7
    #grid: [1, 1]
    # bottom_pad_size:
    paste_avoid_via: False

  pitch: 0.5
  num_pins_x: 5
  num_pins_y: 5
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'
```

http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#page=338

screenshot from 2019-02-07 22-57-00

```yaml
UQFN-28-1EP_4x4mm_P0.4mm_EP2.35x2.35mm:
  device_type: 'UQFN'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#page=338'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  # custom_name_format:
  body_size_x:
    nominal: 4
  body_size_y:
    nominal: 4
  overall_height:
    minimum: 0.45
    nominal: 0.5
    maximum: 0.55

  lead_width:
    minimum: 0.15
    nominal: 0.2
    maximum: 0.25
  lead_len:
    minimum: 0.3
    nominal: 0.4
    maximum: 0.5

  EP_size_x:
    minimum: 2.55
    nominal: 2.65
    maximum: 2.75
  EP_size_x_overwrite: 2.35
  EP_size_y:
    minimum: 2.55
    nominal: 2.65
    maximum: 2.75
  EP_size_y_overwrite: 2.35
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [2, 2]

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    EP_num_paste_pads: [2, 2]
    #paste_between_vias: 1
    #paste_rings_outside: 1
    EP_paste_coverage: 0.7
    #grid: [1, 1]
    # bottom_pad_size:
    paste_avoid_via: False

  pitch: 0.4
  num_pins_x: 7
  num_pins_y: 7
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'
```

http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#page=345

screenshot from 2019-02-07 22-56-06

```yaml
UQFN-40-1EP_5x5mm_P0.4mm_EP3.8x3.8mm:
  device_type: 'UQFN'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#page=345'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  # custom_name_format:
  body_size_x:
    nominal: 5
  body_size_y:
    nominal: 5
  overall_height:
    minimum: 0.45
    nominal: 0.5
    maximum: 0.55

  lead_width:
    minimum: 0.15
    nominal: 0.2
    maximum: 0.25
  lead_len:
    minimum: 0.3
    nominal: 0.4
    maximum: 0.5

  EP_size_x:
    minimum: 3.6
    nominal: 3.7
    maximum: 3.8
  EP_size_x_overwrite: 3.8
  EP_size_y:
    minimum: 3.6
    nominal: 3.7
    maximum: 3.8
  EP_size_y_overwrite: 3.8
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [3, 3]

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    #EP_num_paste_pads: [2, 2]
    paste_between_vias: 1
    paste_rings_outside: 1
    #EP_paste_coverage: 0.7
    grid: [1.3, 1.3]
    # bottom_pad_size:
    #paste_avoid_via: False

  pitch: 0.4
  num_pins_x: 10
  num_pins_y: 10
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'
```

http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#page=347

screenshot from 2019-02-07 22-55-20

```yaml
UQFN-48-1EP_6x6mm_P0.4mm_EP4.45x4.45mm:
  device_type: 'UQFN'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf#page=347'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  # custom_name_format:
  body_size_x:
    nominal: 6
  body_size_y:
    nominal: 6
  overall_height:
    minimum: 0.45
    nominal: 0.5
    maximum: 0.55

  lead_width:
    minimum: 0.15
    nominal: 0.2
    maximum: 0.25
  lead_len:
    minimum: 0.3
    nominal: 0.4
    maximum: 0.5

  EP_size_x:
    minimum: 4.45
    nominal: 4.6
    maximum: 4.75
  EP_size_x_overwrite: 4.45
  EP_size_y:
    minimum: 4.45
    nominal: 4.6
    maximum: 4.75
  EP_size_y_overwrite: 4.45
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [3, 3]

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    #EP_num_paste_pads: [2, 2]
    paste_between_vias: 1
    paste_rings_outside: 1
    #EP_paste_coverage: 0.7
    grid: [1.4, 1.4]
    # bottom_pad_size:
    #paste_avoid_via: False

  pitch: 0.4
  num_pins_x: 12
  num_pins_y: 12
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'
```

### CODE REVIEW

**Comment by evanshultz** [comment]
UQFN-28-1EP_4x4mm_P0.4mm_EP2.35x2.35mm and (to a lesser extent) UQFN-48-1EP_6x6mm_P0.4mm_EP4.45x4.45mm: I don't like a smaller pad than the slug, even though that's what Microchip shows. Can match the package?

**Comment by poeschlr** [comment]
Typically we use nomial slug size for the EP. But if the datasheet suggests an EP then we use that suggestion. (I have been the one who originally wanted to use nominal slug size for all footprints but you where quite persuasive that we should use the datasheet suggested size.)

We could however look into this a bit again. Especially if the suggestion is for an extreme and not for the nominal size. (So if the datasheet suggestion is a minimum then i am prepared to change it. This is something i thought of yesterday when i merged a different microchip package that listed maximum in the suggestion but not nominal.)

---

But also take into consideration that i did not change the ep size compared to the original footprints. (None of the footprints of this PR have been renamed. Should we change the names then i would guess that further changes on the symbol side will be required.)

**Comment by evanshultz** [comment]
True, but I don't like going smaller than the minimum of the package pad. That's my main concern because other traces can make contact with the thermal pad of the IC if the mask is scratched. (Trust me, this can happen. Rare, yes, but possible.)

If the datasheet specifies some unique design, perhaps for thermal reasons, I'd want to do that. But I think we've always gone with manufacturer-specific footprints in that case we we're OK.

Maybe I'm prone to fits of fancy and change my mind. Who knows??

Anyway, we still end up with a generic footprint. It's just that if I saw this package I wouldn't choose this footprint. Make sense? The footprints are fine but I question the manufacturer specifying this footprint for the package.

I'll merge then since we're following what Microchip says.

**Comment by poeschlr** [comment]
I will look into this as documented in the issue linked above.

**Pull request merged**
