### PR TITLE
Added USB_A_Molex_67643_Horizontal

### PR DESCRIPTION
**Pull request by blackvladimir**
Molex USB A connector. Similar to USB_A_Stewart_SS-52100-001_Horizontal but little bit longer.

molex

datasheet https://www.molex.com/pdm_docs/sd/676433910_sd.pdf

two dimensions are not clear from datasheet so I took them from step file ( https://www.molex.com/molex/part/partModels.jsp?&prodLevel=part&partNo=676430910&channel=products )

width
sheet

And dimensions of footprint:

dim

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by poeschlr** [comment]
Please move the silk outline outside the nominal dimension of the component such that it is visible after assembly. Also add a pin 1 marker on silk and fab.

**Comment by blackvladimir** [comment]
Here it is

USB_A_Molex_67643_Horizontal

**Comment by cpresser** [comment]
Checked
- [x] Pads position, size, properties and numbering
- [ ] Where did you get the 13.1mm Body dimension? 
image
- [x] All other F.Fab dimensions check out
- [ ] Silkscreen distance to F.Fab is perfect
- [ ] Silkscreen distance to copper is slightly less than 0.2mm: 
image
- [x] Courtyard distance to F.Fab is good
- [ ] Description needs improvement (check other USB Connectors for hints)

**Comment by blackvladimir** [comment]
- I moved the silk.

- I looked for description of other USB connectors but most of them have just datasheet link. So I added just "USB A" and "horizontal"

- this is how it looks with 3d model from molex (I don't think their license allows to upload it to kicad model repo)

molextop
molexback
molexbot

**Pull request merged**
