### PR TITLE
Esp32 wroom

### PR DESCRIPTION
**Pull request by Misca1234**
These are the foot prints used by Espressif's RF modules

ESP-WROOM-02 (existed before but modified)
https://www.espressif.com/sites/default/files/documentation/0c-esp-wroom-02_datasheet_en.pdf

ESP-WROOM-32
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf

ESP-WROOM-32U
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf

ESP-WROOM-32D
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf

The keep out area is described in
https://www.espressif.com/sites/default/files/documentation/esp-wroom-02_pcb_design_and_module_placement_guide_0.pdf

(I can not figure out why travis complain about 
  Footprint anchor is not located at center of footprint
     - Footprint center calculated as (0.0,0.775)mm
for ESP-WROOM-32 and ESP-WROOM-32U, but I guess it is OK)

ESP-WROOM-02
bild

bild

bild

ESP-WROOM-32
bild

bild

bild

ESP-WROOM-32U
bild

bild

bild

ESP-WROOM-32D
bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by herostrat** [comment]
Hey,

good that I searched in the PR first, I also wanted to add the ESP footprints to KiCad.
Thanks a lot for the awesome work so far!

What I found this far:
 - ESP-WROOM-02: 
   - The CrtYd on the left side is inconsistent and too near to the pads
   - General questions: Where did you get the exact dimensions for the padsizes?
 - ESP-WROOM-32:
   - Footprint seems to be correct
 - ESP-WROOM-32U:
   - The screenshot inserted is wrong (its the D)
 - ESP-WROOM-32D:
   - Footprint seems to be correct

Do you plan to add the symbols too or can I help you with that?

**Comment by Misca1234** [comment]
Hi

> General questions: Where did you get the exact dimensions for the padsizes?

It is described in this document
https://www.espressif.com/sites/default/files/documentation/esp-wroom-02_pcb_design_and_module_placement_guide_0.pdf


> Do you plan to add the symbols too or can I help you with that?
Others are already in progress of doing so

> The naming for the ESP32 is not correct imho. The datasheet reference to the modules as:
> ESP32-WROOM-32, ESP32-WROOM-32D, ESP32-WROOM-32U

Good catch

**Comment by Misca1234** [comment]
Now they look like this

bild

bild

bild

**Comment by herostrat** [comment]
You are right.
Just for the sake of completion for the maintainer:

PR for kicad-symbols:
 - ESP-WROOM-02: https://github.com/KiCad/kicad-symbols/pull/728
 - ESP32-WROMM-32/U/D: https://github.com/KiCad/kicad-symbols/pull/724

**Comment by Misca1234** [comment]
And the 3D models are here
https://github.com/KiCad/kicad-packages3D/pull/337

**Comment by diegoherranz** [comment]
It seems the names are still incorrect? I can still see ESP-WROOM-32 instead of ESP32-WROOM-32, for instance. Did you forget to push after your comment on July 11th?

Thanks for working on this.

**Comment by Misca1234** [comment]
I added a space to ESP32 but rmember there is on whos name is 
ESP-WROOM-32
http://espressif.com/sites/default/files/documentation/0c-esp-wroom-02_datasheet_en.pdf

**Comment by Misca1234** [comment]
I recreate the push

**Comment by Misca1234** [comment]
New push done, see
https://github.com/KiCad/kicad-footprints/pull/767

**Pull request closed without merging**
