### PR TITLE
added Texas_S-PVQFN-N16_EP2.1x2.1mm footprint

### PR DESCRIPTION
**Pull request by nivekg**
Hey Guys, 

I finally created the Texas_S-PVQFN-N16_EP2.1x2.1mm and Texas_S-PVQFN-N16_EP2.1x2.1mm_ThermalVias footprints for the INA3221 symbol (https://github.com/KiCad/kicad-symbols/pull/1343). Not sure if it conforms to the rules, I kept getting python errors when running check_kicad_mod.py

Datasheet: http://www.ti.com/lit/ds/symlink/ina3221.pdf#page=44
Screenshots:
Screenshot from 2019-06-12 11-28-07
Screenshot from 2019-06-12 11-28-35

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
We have recently discovered that the most unique identifier of the footprint is the trhee letter code. The footprint should be named `Texas_RGV`.

Thanks

**Comment by nivekg** [comment]
Cool, will do. Just to understand this, the files should be renamed to Texas_RGV.kicad_mod and Texas_RGV_ThermalVias.kicad_mod

**Comment by antoniovazquezblanco** [comment]
Exctly! Thanks!

**Comment by nivekg** [comment]
Done : )

**Comment by poeschlr** [comment]
footprints for standardized packages like these really should be generated via the script found here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by nivekg** [comment]
Oops, I forgot to say the footprint was generated with that script. I'll change the name back.

**Comment by evanshultz** [comment]
The footprint does need the three-letter (or sometimes less) designation in it. So `Texas_RGV_S-PVQFN-N16_EP2.1x2.1mm` may be best. I believe that's what we settled on for other footprints.

**Comment by evanshultz** [comment]
And the Python errors are sadly normal. The footprint is built well but the check script isn't smart enough for the way the footprints are built by the script.

**Comment by poeschlr** [comment]
please link to the script pull request as the review will happen on it.

**Comment by nivekg** [comment]
Hey Guys,

I renamed the footprint to Texas_RGV_S-PVQFN-N16_EP2.1x2.1mm footprint and made a PR for the footprint generator which is https://github.com/pointhi/kicad-footprint-generator/pull/382

**Comment by evanshultz** [comment]
Comments left in script PR.

**Comment by evanshultz** [comment]
Please generate a new footprint to take into account the script changes. Thank you.

**Comment by nivekg** [comment]
added the updated footprint

**Comment by evanshultz** [comment]
Great. Thank you!

**Pull request merged**
