### PR TITLE
Copied relay fooprints

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Relay_SMD
- Relay_THT
- No attempt to fix KLC

Straight copy of Relays_THT and Relays_SMD repositories as they both have no outstanding PRs

@poeschlr

### CODE REVIEW

**Comment by evanshultz** [comment]
Should the 3D model path be changed to singular for v5, as noted by the check script?

**Comment by SchrodingersGat** [comment]
@evanshultz yes, it definitely should. Thanks to you and Travis :) I'll amend the PR

**Comment by SchrodingersGat** [comment]
OH what joy it brings to only have to manage one repo now!!! I'm so happy :) I just deleted 50 repos from my own GitHub account :)

**Comment by Shackmeister** [comment]
Indeed it does! Ill see if I can find some time to bring some scripts up to date :) primarily for the 3D models, but perhaps also some footprints. Can't wait to get this going! :D

**Comment by SchrodingersGat** [comment]
@Shackmeister that would be great :) Hopefully we can move everything across by end of Nov and then Dec can be the symbols

**Comment by Shackmeister** [comment]
@SchrodingersGat well moving is probably the easy oart

**Comment by Shackmeister** [comment]
@SchrodingersGat finger slip on my Phone, sorry xD

Mocong is probably the easy part, getting everything up to the KLC 3.0 is probably gonna be a bit tougher :p

**Comment by SchrodingersGat** [comment]
Oh yeah we won't be able to fix everything and our focus should be on transfer. Where changes are easy to make (especially in bulk with scripts) then we can make those fixes. But fixing everything is too much. We'll never get it done :)

**Comment by poeschlr** [comment]
Things that already fulfill KLC 2 should also comply with KLC 3 once they are renamed. (The main change between 2 and 3 is the naming convention.)

**Comment by poeschlr** [comment]
Forgot to click the merge button. Thanks Oliver

**Pull request merged**
