### PR TITLE
New scripted version of TI footprints

### PR DESCRIPTION
**Pull request by poeschlr**
This adds scripted alternatives for some TI footprints.
There are no changes to the symbol side needed. The footprints that have been renamed are currently not used by any symbol.

Script pull request: https://github.com/pointhi/kicad-footprint-generator/pull/285

# Texas_RUM0016A
http://www.ti.com/lit/ds/symlink/lmh0074.pdf#page=13

screenshot from 2019-02-02 22-54-36

```yaml
Texas_RUM0016A:
  device_type: 'QFN'
  size_source: 'http://www.ti.com/lit/ds/symlink/lmh0074.pdf#page=13'
  ipc_class: 'qfn' # 'qfn_pull_back'
  custom_name_format: 'Texas_RUM00{pincount}A_EP{ep_size_x:g}x{ep_size_y:g}mm{vias:s}'
  body_size_x:
    nominal: 4
    tolerance: 0.1
  body_size_y:
    nominal: 4
    tolerance: 0.1
  body_height:
    maximum: 0.8

  lead_width:
    nominal: 0.3
    tolerance: 0.05
  lead_len:
    nominal: 0.4
    tolerance: 0.1

  EP_size_x:
    nominal: 2.6
    tolerance: 0.1
  EP_size_y:
    nominal: 2.6
    tolerance: 0.1
  EP_num_paste_pads: [2, 2]

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    paste_via_clearance: 0.1
    EP_paste_coverage: 0.7
    paste_avoid_via: False

  pitch: 0.65
  num_pins_x: 4
  num_pins_y: 4
```

# Texas_S-PVQFN-N20_EP2.7x2.7mm
http://www.ti.com/lit/ds/symlink/drv8662.pdf#page=23

screenshot from 2019-02-02 22-55-50

```yaml
Texas_S-PVQFN-N20_EP2.7x2.7:
  device_type: 'QFN'
  size_source: 'http://www.ti.com/lit/ds/symlink/drv8662.pdf#page=23'
  ipc_class: 'qfn' # 'qfn_pull_back'
  custom_name_format: 'Texas_S-PVQFN-N{pincount}_EP{ep_size_x:g}x{ep_size_y:g}mm{vias:s}'
  body_size_x:
    minimum: 3.85
    maximum: 4.15
  body_size_y:
    minimum: 3.85
    maximum: 4.15
  body_height:
    minimum: 0.8
    maximum: 1.0

  lead_width:
    minimum: 0.18
    maximum: 0.30
  lead_len:
    minimum: 0.3
    maximum: 0.5

  EP_size_x:
    nominal: 2.7
    tolerance: 0.1
  EP_size_y:
    nominal: 2.7
    tolerance: 0.1
  EP_num_paste_pads: [2, 2]

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    paste_via_clearance: 0.1
    EP_paste_coverage: 0.7
    paste_avoid_via: False

  pitch: 0.5
  num_pins_x: 5
  num_pins_y: 5
```

# Texas_S-PVQFN-N36
http://www.ti.com/lit/ds/slvsba5d/slvsba5d.pdf#page=32

screenshot from 2019-02-02 22-57-39

```yaml
Texas_S-PVQFN-N36_EP:
  device_type: 'QFN'
  size_source: 'http://www.ti.com/lit/ds/slvsba5d/slvsba5d.pdf#page=32'
  ipc_class: 'qfn' # 'qfn_pull_back'
  custom_name_format: 'Texas_S-PVQFN-N{pincount}_EP{ep_size_x:g}x{ep_size_y:g}mm{vias:s}'
  body_size_x:
    minimum: 5.9
    maximum: 6.1
  body_size_y:
    minimum: 5.9
    maximum: 6.1
  body_height:
    minimum: 0.8
    maximum: 1.0

  lead_width:
    minimum: 0.18
    maximum: 0.3
  lead_len:
    minimum: 0.45
    maximum: 0.65

  EP_size_x:
    nominal: 4.4
    tolerance: 0.1
  EP_size_y:
    nominal: 4.4
    tolerance: 0.1
  EP_num_paste_pads: [3, 3]

  thermal_vias:
    count: [4, 4]
    drill: 0.2
    paste_via_clearance: 0.1
    paste_between_vias: 1
    paste_rings_outside: 1
    EP_paste_coverage: 0.65
    grid: [1.05, 1.05]

  pitch: 0.5
  num_pins_x: 9
  num_pins_y: 9
```

# Texas_S-PVQFN-N40_EP2.9x2.9mm
http://www.ti.com/lit/ds/symlink/msp430fr5731.pdf#page=114

screenshot from 2019-02-02 22-59-16

```yaml
Texas_S-PVQFN-N40_EP2.9x2.9mm:
  device_type: 'QFN'
  size_source: 'http://www.ti.com/lit/ds/symlink/msp430fr5731.pdf#page=114'
  ipc_class: 'qfn' # 'qfn_pull_back'
  custom_name_format: 'Texas_S-PVQFN-N{pincount}_EP{ep_size_x:g}x{ep_size_y:g}mm{vias:s}'
  body_size_x:
    minimum: 5.85
    maximum: 6.15
  body_size_y:
    minimum: 5.85
    maximum: 6.15
  body_height:
    minimum: 0.8
    maximum: 1.0

  lead_width:
    nominal: 0.23
    tolerance: [-0.05, 0.07]
  lead_len:
    minimum: 0.3
    maximum: 0.5

  EP_size_x:
    nominal: 2.9
    tolerance: 0.1
  EP_size_y:
    nominal: 2.9
    tolerance: 0.1
  EP_num_paste_pads: [2, 2]

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    paste_via_clearance: 0.1
    EP_paste_coverage: 0.7
    paste_avoid_via: False

  pitch: 0.5
  num_pins_x: 10
  num_pins_y: 10
```

# Texas_S-PVQFN-N40_EP3.52x2.62mm
http://www.ti.com/lit/ds/symlink/drv8308.pdf#page=56

screenshot from 2019-02-02 23-01-06

```yaml
Texas_S-PVQFN-N40_EP3.52x2.62mm:
  device_type: 'QFN'
  size_source: 'http://www.ti.com/lit/ds/symlink/drv8308.pdf#page=56'
  ipc_class: 'qfn' # 'qfn_pull_back'
  custom_name_format: 'Texas_S-PVQFN-N{pincount}_EP{ep_size_x:g}x{ep_size_y:g}mm{vias:s}'
  body_size_x:
    minimum: 5.85
    maximum: 6.15
  body_size_y:
    minimum: 5.85
    maximum: 6.15
  body_height:
    minimum: 0.8
    maximum: 1.0

  lead_width:
    nominal: 0.23
    tolerance: [-0.05, 0.07]
  lead_len:
    minimum: 0.3
    maximum: 0.5

  EP_size_x:
    nominal: 3.52
    tolerance: 0.1
  EP_size_y:
    nominal: 2.62
    tolerance: 0.1
  EP_num_paste_pads: [3, 2]

  thermal_vias:
    count: [4, 3]
    drill: 0.2
    paste_via_clearance: 0.1
    EP_paste_coverage: 0.7
    paste_avoid_via: False

  pitch: 0.5
  num_pins_x: 10
  num_pins_y: 10
```

# Texas_S-PVQFN-N40_EP4.6x4.6mm
http://www.ti.com/lit/ds/symlink/msp430g2755.pdf#page=68

screenshot from 2019-02-02 23-02-50

```yaml
Texas_S-PVQFN-N40_EP4.6x4.6mm:
  device_type: 'QFN'
  size_source: 'http://www.ti.com/lit/ds/symlink/msp430g2755.pdf#page=68'
  ipc_class: 'qfn' # 'qfn_pull_back'
  custom_name_format: 'Texas_S-PVQFN-N{pincount}_EP{ep_size_x:g}x{ep_size_y:g}mm{vias:s}'
  body_size_x:
    minimum: 5.85
    maximum: 6.15
  body_size_y:
    minimum: 5.85
    maximum: 6.15
  body_height:
    minimum: 0.8
    maximum: 1.0

  lead_width:
    nominal: 0.23
    tolerance: [-0.05, 0.07]
  lead_len:
    minimum: 0.3
    maximum: 0.5

  EP_size_x:
    nominal: 4.6
    tolerance: 0.1
  EP_size_y:
    nominal: 4.6
    tolerance: 0.1
  EP_num_paste_pads: [3, 3]

  thermal_vias:
    count: [4, 4]
    drill: 0.2
    paste_via_clearance: 0.1
    paste_between_vias: 1
    paste_rings_outside: 1
    grid: [1.15, 1.15]

  pitch: 0.5
  num_pins_x: 10
  num_pins_y: 10
```

### CODE REVIEW

**Comment by poeschlr** [comment]
This is now ready for review.

**Comment by evanshultz** [comment]
1. Datasheet should link to page 31.
1. Texas_S-PVQFN-N40_EP4.6x4.6mm has the wrong datasheet.

Sorry for some duplicate comments but I'm just listing everything I see as I make my way through your PRs.

**Comment by poeschlr** [comment]
The issues have been addressed.

**Comment by evanshultz** [comment]
Yup. Looks good. Thanks!

**Pull request merged**
