### PR TITLE
Add ST PowerSO-20/36 footprints

### PR DESCRIPTION
**Pull request by Salamandar**
Add ST PowerSO-20/36 footprints.

* The SlugDown footprints are based on the datasheet of the component (thus the dimensions of the slug).
* The SlugDown_ThermalVias footprints are based on the suggested PCB footprints.
* The SlugUp are the same footprints without slug (obviously).

Datasheet for the footprints: http://www.st.com/content/ccc/resource/technical/document/technical_note/group0/89/b8/8f/9b/ed/7b/41/56/DM00454055/files/DM00454055.pdf/jcr:content/translations/en.DM00454055.pdf

capture du 2018-06-10 23-03-13
capture du 2018-08-20 13-42-44
capture du 2018-06-10 23-05-20
capture du 2018-08-20 13-41-38

---
Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

It helps the review process if you provide screen shoot of the footprints and their data,
see https://github.com/KiCad/kicad-footprints/pull/647

as an example

**Comment by Salamandar** [comment]
I realized there were "suggested" footprints for thermal dissipation. I'll WIP this PR until I design those footprints.

**Comment by jschall** [comment]
I think you may've forgotten to push the thermal via version.

**Comment by Salamandar** [comment]
Didn't want to close this, I did just move it to a new branch.
@poeschlr OK, I got the problem… I didn't fully understand the multiple layers. I'm modifying it.

**Pull request closed without merging**
