### PR TITLE
Adding newly scripted molex connector footprints (The rest of them)

### PR DESCRIPTION
**Pull request by poeschlr**
This time around i choose a slightly different work order. For the jst connectors i had one and a half day of only checking footprints. This time i will add the footprints series by series to this PR and check them immediately. (Split up the boring work.)
This also allows you guys to give feedback early on.

This will ultimately add:
- KK
- mega fit
- micro fit
- mini fit
- nano fit
- micro clasp
- micro latch
- picoblade (tht)
- pico flex
- slimstack

Similar to the jst PR i will also unify the pad dimensions (as far as possible)
- standardized minimum annular ring: 0.15mm (as per KLC)
- standardized minimum pad to pad clearance: 0.8mm
- standardized maximum "solder space": 0.5mm (elongation of pads where possible.)

I will notify you once everything is added and ready to merge.

### CODE REVIEW

**Comment by poeschlr** [comment]
# Molex KK 254
About the footprint name:
It seems molex did change the mpn for these since the footprints have been originally created. (The old name is still listed as Engineering/Old PN on the [part webside](http://www.molex.com/molex/products/datasheet.jsp?part=active/0022272021_PCB_HEADERS.xml))

The name "KK 254" comes form [this webside](http://www.molex.com/molex/products/family?key=kk_254_rpc_connector_system&channel=products&chanName=family&pageTitle=Introduction&parentKey=kk_interconnect_solutions)

Currently i only list the "old" series number (6410) only in the description not in the footprint name. (previously 6410 was part of the mpn.)

http://www.molex.com/pdm_docs/sd/022272021_sd.pdf

Differences to old footprints:
- new name
- more pad to pad clearance
- added pin 1 marker (was already in the script, just not in the repo)

screenshot from 2017-11-18 21-06-48
screenshot from 2017-11-18 21-11-08

**Comment by poeschlr** [comment]
# Molex Mega-Fit (Horizontal)

http://www.molex.com/pdm_docs/sd/1720640002_sd.pdf

No real functional differences. (Only changed some minor things on silk and fab layer)

screenshot from 2017-11-19 00-26-57
screenshot from 2017-11-19 00-38-36

**Comment by poeschlr** [comment]
# Molex Mega-Fit Vertical

http://www.molex.com/pdm_docs/sd/768290102_sd.pdf
http://www.molex.com/pdm_docs/sd/768290004_sd.pdf

Added type without the external mounting "pins".
A lot of the dimensions for these footprints where off. (Even pad placements)

screenshot from 2017-11-19 14-18-43
screenshot from 2017-11-19 14-18-06

**Comment by poeschlr** [comment]
# Molex PicoClasp Vertical

http://www.molex.com/pdm_docs/sd/559320210_sd.pdf
http://www.molex.com/pdm_docs/sd/559320530_sd.pdf

New footprints. (generators where over at the script repo but no footprints are in the current master branch of the Connectors_Molex repo)

screenshot from 2017-11-19 17-44-02
screenshot from 2017-11-19 17-57-59

**Comment by poeschlr** [comment]
# Molex Micro-Fit 3.0 dual row side entry

http://www.molex.com/pdm_docs/sd/430450210_sd.pdf

These footprints where duplicated. Difference between *10 and *11 is the contact material. (If we want one footprint per material type why has *09 been ignored? A similar question would arise with the other mega fit footprints. There each footprint represents all 3 types of material)

Pin numbering is wrong for the existing footprints.

Courtyard offset has been inconsistent around footprint.

Currently the footprint is centered between numbered pads. Should i change it such that it also takes the mounting pads into account? (There is no reference point given in the datsheet)

Pin numbering according to datasheet:
screenshot from 2017-11-19 21-27-26

screenshot from 2017-11-19 21-19-53
screenshot from 2017-11-19 21-22-17

**Comment by poeschlr** [comment]
# Molex Micro-Fit 3,0 Dual Row Top Entry

http://www.molex.com/pdm_docs/sd/430450217_sd.pdf
http://www.molex.com/pdm_docs/sd/430450218_sd.pdf

Like with the other micro fit version i reduced the number of footprints because there where duplicates for different pin materials. (again only two of the 3 available versions)

This version again had wrong pin numbering
This version was rotated wrong
Because the script is written quite hard to understand i completely re implemented these connector footprints.

screenshot from 2017-11-20 01-06-14
screenshot from 2017-11-20 01-05-58

**Comment by poeschlr** [comment]
# Molex Micro-Latch

http://www.molex.com/pdm_docs/sd/532540270_sd.pdf
http://www.molex.com/pdm_docs/sd/532530770_sd.pdf

Changes compared to old footprints:
Larger pad to pad clearance (allows for traces between pads) Elongated for better solder ability.

screenshot from 2017-11-20 14-14-30
screenshot from 2017-11-20 14-07-04

**Comment by poeschlr** [comment]
I fucking hate the molex part number system. No logic at all. 100 (felt) part numbers for the same fucking connector, datasheets list different numbers to the webside, ....

I will choose one mpn style (per series) at random for the footprint naming.

**Comment by evanshultz** [comment]
Yes, their PNs are annoying!

Since https://github.com/KiCad/Connectors_Molex.pretty/pull/56 was locked, I can't comment there. Just an FYI if you want to add this series. Obviously some KiCad user wanted to use it so if you're able to add it then all KiCad users could benefit.

**Comment by poeschlr** [comment]
@evanshultz about FCC series i would wait if @johl adds them.

I decided to use the old/eng names for the footprint naming. (I just don't care anymore. Their new system is too confusing for me to wrap my head around. And i also start to feel a bit burned out. I definitely need to reduce my standards. Otherwise i will never finish this PR.)

# Molex Mini-Fit Jr

Horizontal:
- http://www.molex.com/pdm_docs/sd/039291047_sd.pdf
- http://www.molex.com/pdm_docs/sd/039300020_sd.pdf
Vertical:
- http://www.molex.com/pdm_docs/sd/039289068_sd.pdf
- http://www.molex.com/pdm_docs/sd/039281043_sd.pdf

Changes:
- Outlines where wrong
- more pad to pad clearance
- better crtyd
- better outline graphics on silk and fab

screenshot from 2017-11-22 20-27-14
screenshot from 2017-11-22 20-27-05
screenshot from 2017-11-22 20-35-24

**Comment by poeschlr** [comment]
# Molex Mini-Fit Sr dual row vertical

http://www.molex.com/pdm_docs/sd/439151206_sd.pdf

Changes:
- better fab outlines
- slightly different pad sizes
- more regular "thermal" vias (and larger pad size)

screenshot from 2017-11-23 14-18-26

screenshot from 2017-11-23 14-09-09

screenshot from 2017-11-23 14-18-46

screenshot from 2017-11-23 14-21-21

**Comment by poeschlr** [comment]
# Molex Nano Fit

Single row:
- http://www.molex.com/pdm_docs/sd/1053131208_sd.pdf
- http://www.molex.com/pdm_docs/sd/1053091203_sd.pdf

Dual row:
- http://www.molex.com/pdm_docs/sd/1053141208_sd.pdf
- http://www.molex.com/pdm_docs/sd/1053101208_sd.pdf

Changes:
- rotated such that pin 1 is on top left for dual row versions
- larger pad to pad clearance
- simplified fab and silk artwork

screenshot from 2017-11-23 22-10-05
screenshot from 2017-11-23 22-09-48
screenshot from 2017-11-23 22-29-22

**Comment by poeschlr** [comment]
# PicoBlade THT

http://www.molex.com/pdm_docs/sd/530480610_sd.pdf
http://www.molex.com/pdm_docs/sd/530470610_sd.pdf

changes:
- more pad to pad clearance
- better pin 1 marker

screenshot from 2017-11-23 23-51-49
screenshot from 2017-11-23 23-48-47

**Comment by poeschlr** [comment]
# Molex Picoflex

http://www.molex.com/pdm_docs/sd/903250004_sd.pdf
http://www.molex.com/pdm_docs/sd/908140004_sd.pdf

Changes:
- I hope not really much (Quite complex code and not really enough data in the datasheet to really check it.)
- the only thing i really changed is to simplify the courtyard to a rectangle to ensure a closed polygon. (It had arcs in it that approximately met but i doubt DRC scripts can deal with that if they ever get implemented.)

screenshot from 2017-11-24 01-41-45

**Comment by poeschlr** [comment]
This is now ready to merge.

Slimstack will get it's own PR (Some of them might need mirrored pin out.)

Travis errors stem from Micro-Fit 3.0 not being centered in Y direction. (Currently the center is between the numbered pads. Should we center it with regards to the bounding box including the mounting pads?)

There are also travis warnings because Mini-Fit Sr has all it's pads as rectangle.

**Comment by SchrodingersGat** [comment]
Rene thanks for this fantastic effort :)

**Pull request merged**
