### PR TITLE
Package_DFN_QFN: Add TQFN-16-1EP_5x5mm_P0.8mm_EP3.1x3.1mm

### PR DESCRIPTION
**Pull request by zonque**
This footprint is used by MAXIM parts, as described here:

  https://pdfserv.maximintegrated.com/package_dwgs/21-0140.PDF

Generated with kicad-footprint-generator.

The PR for the generator is here: https://github.com/pointhi/kicad-footprint-generator/pull/329

image

### CODE REVIEW

**Comment by poeschlr** [comment]
Wrong IPC class used. See comment on script PR.

**Comment by zonque** [comment]
Thanks! Updated now.

**Comment by poeschlr** [comment]
Please avoid force pushes for contributions to the kicad library when you already have a review. (Makes it harder for us to see what changed. Not as critical for scripted contributions.)

We then use squashed merge to keep the master history clean.

**Comment by poeschlr** [comment]
Why does this pull request change stuff for a crystal and a terminal block?

**Comment by zonque** [comment]
> Why does this pull request change stuff for a crystal and a terminal block?

Ugh, sorry for that. I must have staged something that I didn't intend to. Added a commit that reverts these stray changes. Please squash, and thanks for noting!

**Comment by poeschlr** [comment]
As a tip: Have a separate local clone for managing your personal libs to use for your own projects compared to the one that is used to commit changes to github. (Maybe setup that clone for read only github sync.)

**Comment by poeschlr** [comment]
The footprint looks nice now. Thanks.

**Pull request merged**
