### PR TITLE
WDFN-8-1EP_6x8mm_P1.27mm_EP6x4.8mm_ThermalPad added.

### PR DESCRIPTION
**Pull request by serkanxselcuk**
WDFN-8-1EP_6x8mm_P1.27mm_EP6x4.8mm_ThermalPad added.

`Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/8L_WDFN_5x6mm_MF_C04210B.pdf`

**EDIT**
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/8L_WDFN_6x8mm_MN_C04172A.pdf

image

image
image
image
image
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by serkanxselcuk** [comment]
Travis errors are because of termal pad and vias.
3D file is not present.
I will serve SST26VFxxxB symbol soon.

**Comment by serkanxselcuk** [comment]
image
image

**Comment by myfreescalewebpage** [comment]
Symbol is Abandoned

**Comment by serkanxselcuk** [comment]
Transfered to #2506

**Pull request closed without merging**
