### PR TITLE
LFCSP-72-1EP_10x10mm_P0.5mm

### PR DESCRIPTION
**Pull request by calebns**
LFCSP-72-1EP_10x10mm_P0.5mm   , as for AD9142

https://www.intersil.com/content/dam/Intersil/documents/l72_/l72.10x10c.pdf

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Your version of the exposed pad does not conform to the KLC. More details see rule http://kicad-pcb.org/libraries/klc/F6.3/

**Comment by calebns** [comment]
Fixed.

image

image

**Comment by calebns** [comment]
Updated pads and EP to match the latest BXL  (C72-7 footprint)
http://www.analog.com/media/en/symbols-footprints/symbols/AD9142BCPZ.bxl

Pad size: 0.3mmx0.8mm
EP: 6.15x6.15mm
EP solder paste coverage: 67%

Is there a chance it could be merged anytime soon?

image

**Comment by poeschlr** [comment]
The Pad suffix is wrong for indicating the size of the EP. Use the suffix EP6.15x6.15mm
See: http://kicad-pcb.org/libraries/klc/F2.2/

An example for a correctly named footprint is the `LQFP-144-1EP_20x20mm_P0.5mm_EP4x4mm` footprint

**Comment by calebns** [comment]
My bad, should be fixed by now.

**Comment by poeschlr** [comment]
Looks good thanks

**Pull request merged**
