### PR TITLE
Harwin connectors

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added existing Harwin connectors
* Rebuilt from scripts
* No KLC

### CODE REVIEW

**Comment by dragonlost** [comment]
Good morning all. Why this pull request was not accepted. For now the numbering for harwin connectors is wrong in kicad which is a shame.

**Comment by chschlue** [comment]
Do you mean #323?
Apparently because its author never finished it.

**Comment by dragonlost** [comment]
ha darn

**Comment by chschlue** [comment]
@dragonlost feel free to re-push and fix it.

**Pull request merged**
