### PR TITLE
Fix F.Paste of SIMCom SIM800C

### PR DESCRIPTION
**Pull request by jneiva08**
Fixed F.Paste in accord of datasheet
Moved F.CrtYd to have 0.25mm from F.Paste pad

Datasheet: https://simcom.ee/documents/SIM800C/SIM800C_Hardware_Design_V1.05.pdf#page=16

Screenshot:
sim800c

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by evanshultz** [comment]
Is it weird to anyone else that the paste pads are taller than the copper pads? That seems like a relatively odd thing and I question it. During reflow the paste may wick down onto the pads and it would probably work out OK, but it's abnormal in my (questionable and limited) experience.

**Comment by chschlue** [comment]
Exactly what I thought. So I decided to leave it to someone more experienced with castellated pads :)

Apart from that strange paste-on-mask thing, I'd generally leave paste clearance to the user (board setup or local FP options).

**Comment by jneiva08** [comment]
I'm curious too, but i think they make this way, is because when goes to the oven, the solder melt an try to climb the pad and leaves more solder near of the module.

I will making this change for the other modules (Quectel) on repository. Because the module i need will have more complex patterns, and the F.Paste is different depending of the version.
In one project I'm envolved, the company responsible to order the pcb's with ublox SAM-M8, forgot to send the F.Paste. When be PCB's arrived they found some pads of gps was shorted.

**Comment by poeschlr** [comment]
It is definitely a strange thing but the resulting footprint agrees with the datasheet so i am ok with merging it.

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
