### PR TITLE
5-pin SAW filter 1.4x1.1mm

### PR DESCRIPTION
**Pull request by calebns**
I couldn't find a place where to put the footprint, so I propose to create a new "Filter" library. Please let me know if that's OK or if I should move it somewhere else.

1.4x1.1mm:
https://www.mouser.com/ds/2/40/AVX_140127%20Connectivity-1158389.pdf
image

1.1x0.9mm:
https://www.mouser.com/ds/2/842/B8813-1092540.pdf

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for the contribution. I found a few issues with these footprints:
1. Could you please add a pin1-marker to F.Fab (see screenshot below
1. Maybe use a pin1-marker on F.SilkS which is a bit closer to other components (we often use double-stroke corners) in the lib, e.g.:
2018-02-17 16_14_42-footprint editor no active library
1. About the naming I'm not sure ... these are not standardized, but they seem to be used by more than one manuacturer ... @evanshultz @poeschlr Do you have proposals for the naming? Maybe `Filter_1411-5_1.4x1.1mm` and `Filter_1109-5_1.1x0.9mm`??? That does cover the pad-count, but not the layout ... Using a manufacturer MPN does not work either, because the packages are used by multiple manufacturers and for different types of filters ...

**Comment by calebns** [comment]
Is it OK now?

image

**Comment by jkriege2** [comment]
looks goot, but please replace the minus `-` before the package size `1.4x1.1mm`/`1.1x0.9mm` by an underscore `_`

Thanks,
JAN

**Comment by calebns** [comment]
Updated.

**Comment by jkriege2** [comment]
Thanks!

JAN

**Pull request merged**
