### PR TITLE
Package_SO: Add TSOP-6_1.5x2.9mm_P0.95mm

### PR DESCRIPTION
**Pull request by zonque**
This package is used by NXP as described here:

  https://www.nxp.com/packages/SOT457

image

### CODE REVIEW

**Comment by zonque** [comment]
PR for generator script: https://github.com/pointhi/kicad-footprint-generator/pull/328

**Comment by poeschlr** [comment]
I kind of missed that this got updated. Looks good now, thanks

**Comment by chschlue** [comment]
@poeschlr 
Now there's a generator for SC-74-6 but a TSOP-6 FP

**Comment by poeschlr** [comment]
damn i missed that

**Pull request merged**
