### PR TITLE
Add Molex 47590-0001

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.molex.com/pdm_docs/sd/475900001_sd.pdf

Screenshot:

micro-usb-ab

3d_1

3d_2

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jneiva08** [comment]
F6.2: The footprint is a little forward because of the edge.
F7.5: Need advise to fix this, the pads is composed various shapes, I don't know if it was the best way to do.

**Comment by poeschlr** [comment]
The side pads are not quite right. Might is suggested using a normal oblong (oval) pad plus a rectangle smd pad? (easier to get right and easier to check as stepup can import such a padshape) Also i think the square extension is not necessary on any other layer than the top side.

Screenshot from 2019-10-13 18-58-47

Move the pcb edge stuff to the edge cuts layer. (And close the fab outline properly to represent the part body.)
Screenshot from 2019-10-13 19-17-14

**Comment by jneiva08** [comment]
@poeschlr , did you mean to change like this:
molex usb

**Comment by poeschlr** [comment]
Yes

**Comment by jneiva08** [comment]
@poeschlr , hope didn't wrongly interpreted the change have requestes.

micro_ab

**Comment by poeschlr** [comment]
The two small smd pads with number 6 should not have paste as that would result in paste covering the large slot (could lead to production problems) At most a even smaller paste pad could be added that avoids the slot. (with a bit of clearance)

---

Footprint dimensions look good

Screenshot from 2019-10-21 19-58-56

**Comment by jneiva08** [comment]
Have removed F.Paste from side pad's, have added small on with only F.Paste

Screenshot:
pad

**Comment by poeschlr** [comment]
The paste pads should not have copper.

**Comment by poeschlr** [comment]
thanks

**Comment by jneiva08** [comment]
thanks

**Pull request merged**
