### PR TITLE
DRC0010J via to solid

### PR DESCRIPTION
**Pull request by jneiva08**
Changed vias to be solid, forgot to change in the initial commit.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Why? We typically do not do this. The only pads that we set to solid are polygon pads as they do not offer thermals as an option.

**Comment by jneiva08** [comment]
Used this footprint for a dc-dc, if i put solid when have ground plane in the bottom, it have the best dissipation even the other components have thermal reliefs for soldering

**Comment by poeschlr** [comment]
Yes but that should be made in the zone settings not at the footprint level. At least not for generic footprints in the library.

What is however missing is a rectangular pad on the bottom layer covering all vias. (See any qfn thermal vias variant.)
That pad should have the same pad number as the vias and only copper activated (no mask and no paste active) See: http://kicad-pcb.org/libraries/klc/F4.4/

**Comment by jneiva08** [comment]
I will have attention for next time.
@poeschlr  can I close this PR?

**Comment by poeschlr** [comment]
I created an issue such that we remember that this one is missing the bottom pad: https://github.com/KiCad/kicad-footprints/issues/1400

**Pull request closed without merging**
