### PR TITLE
BatteryHolder: Add CH273-2450 (1 x CR2450)

### PR DESCRIPTION
**Pull request by piotr-wiszowaty**
Description: http://www.comf.com.tw/ProductDetail.asp?no=148

ch273-2450

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Do you know of a more detailed drawing for this part? The one on the website is under constrained. (There is no dimension given that relates the pads to the body. The lead diameter is not given.)

Is there a particular reason for having the silkscreen so far out?
I would suggest to put it nearer to the fab outline. (There is no strict requirement. But it should be near enough to be of use for manual part placement.)

---

The courtyard clearance should be 0.25mm it is 0.5mm now
The circular features are not quite precise. (I know kicad is not really good at handling arcs but i feel you can do a better job than that. You might also be able to use freecad and stepup to make your live easier.)

screenshot from 2019-01-19 01-05-11

**Comment by piotr-wiszowaty** [comment]
This is what the component looks like:
ch273-2450

**Comment by poeschlr** [comment]
So does this mean the part does not at all agree with what is given in the datasheet?
I am not really happy about having such parts in the official library to be honest.

**Comment by piotr-wiszowaty** [comment]
That's right - the spec drawing is significantly different from the real 
thing.

I've just sent the manufacturer an e-mail asking to provide a correct 
drawing.
Let's see what their reply will be.

**Comment by poeschlr** [comment]
That would be perfect. If they can produce a drawing that aligns with what you see then we can include this part.

Maybe the better drawing has even the one missing dimension.

**Comment by piotr-wiszowaty** [comment]
The manufacturer sent back this datasheet:
[CH 273-2450LF.pdf](https://github.com/KiCad/kicad-footprints/files/2873363/CH.273-2450LF.pdf)

They also said that they will correct the drawing on the webpage.

**Comment by poeschlr** [comment]
Thanks for taking care of this. I will check your footprint against that new drawing shortly.

The question now is how to link to this datasheet such that users of the footprints can verify that it fits their part?

**Comment by piotr-wiszowaty** [comment]
They've actually updated the drawing on their webpage, but rounded the dimensions.
I propose putting the datasheet on github in some (maybe newly created) repository.

**Comment by poeschlr** [comment]
I would go with their rounded version of the datasheet to be honest. They are after all free to define the part as they wish (rounding probably gives them more wiggle room than the precise drawing you got.)

**Comment by poeschlr** [comment]
Please remove the version you based on the unofficial datasheet. (I know it seems crazy but we really can not base stuff in the official lib on unofficial information that nobody can later verify. Especially as that unofficial information is not binding anyways.)

The dimensions of the version complying with the drawing on their website fits with these dimensions.

General remark: It is kind of annoying that they are still missing the dimension that fixes where the pins are in relation to the body. (the 1.22mm) It is also kind of annoying that they do not simply use the detailed drawings from the pdf or at least link the pdf on their site (I suspect they want to be able to easily switch supplier if they find something cheaper)

**Comment by poeschlr** [comment]
Thanks.

**Pull request merged**
