### PR TITLE
Connector_Card: Add microSD Molex 104031-0811

### PR DESCRIPTION
**Pull request by gmsotavio**
Add the Molex 104031-0811 to Connector_Card footprint library.

**Footprint**

screenshot_2018-12-14_16-02-03

 **Datasheet**: [https://www.molex.com/pdm_docs/sd/1040310811_sd.pdf](https://www.molex.com/pdm_docs/sd/1040310811_sd.pdf)

screenshot_2018-12-14_15-58-26

**Testing**

Regards!
Otavio Augusto

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi. It' is my first contribution to kicad-footprints library. I need some help with Travis CI error.

### Violating F6.2
    For surface-mount devices, footprint anchor is placed in the middle of the footprint (IPC-7351).
    Footprint anchor is not located at center of footprint
     - Footprint center calculated as (-0.0,0.025)mm

How kicad defines precisely the center of the footprint ? Where is the reference, highlighting the non-symmetrical footprints ? In the symbol of the PR I choose the center based on F.Fab, like depicted bellow.

dimension

**Comment by poeschlr** [comment]
Sorry for the long wait. There is a small mistake with the outline otherwise this is ok.
Screenshot from 2019-06-05 23-59-58

**Comment by gmsotavio** [comment]
Hi @poeschlr, Thank you for your review. I pushed the recommended changes. Please, may you generate a new drawing with the measurements? By the way, how do you generate it? Can you share your method?

Otavio

**Comment by gmsotavio** [comment]
I have a remaining question. I made this footprint with the pins at top to be compatible with KLC , but the reel considers that pin should be located at bottom
Screenshot_2019-07-02_12-01-52
Is this a problem to pick and place?

**Comment by evanshultz** [comment]
Drawing instructions: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279. Unfortunately, the Drawing Dimensions workbench doesn't work in FreeCAD 0.18, but you can still use 0.17.

**Comment by gmsotavio** [comment]
> Drawing instructions: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279. Unfortunately, the Drawing Dimensions workbench doesn't work in FreeCAD 0.18, but you can still use 0.17.

Thanks @evanshultz !

**Comment by gmsotavio** [comment]
I realized that the dimensions are still wrong. Please, do not review for a while. I going to provide the due fixes.

**Comment by gmsotavio** [comment]
Fixed
measurements

**Comment by poeschlr** [comment]
Looks good thanks

**Pull request merged**
