### PR TITLE
Adding IDT oscillator JU6 package footprint

### PR DESCRIPTION
**Pull request by ki5libs**
Adding IDT oscillator JU6 package footprint
[Datasheet](https://www.idt.com/document/dst/xu-family-datasheet#page=17)

JU6_new

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
We never include the word pin in the footprint name.
The pitch should be included in the footprint name.

Rotate the footprint 90 degree such that pad 1 is on the top left corner (IPC zero orientation A)

Use IPC style pad 1 marking. (chamfer on fab, missing/short line on silk. look at DFN-8-1EP_2x2mm_P0.5mm_EP0.9x1.5mm for inspiration)

Possibly move silk closer to the fab outline (to aid part alignment for manual assembly)

Courtyard clearances are 0.3mm instead of 0.25mm (all other dimensions are ok. No nice drawing as i checked it with kicad internal tools)

**Comment by ki5libs** [comment]
Hi @poeschlr, footprint updated. I renamed it as you can see on the refreshed screenshot, but I couldn't find any oscillators in the actual library with such name template. The old one was more common for oscillators.

**Comment by poeschlr** [comment]
I think there was a bit of a misunderstanding. I did not intent for the pin count specifier to be removed. Just the word Pin. So the name would be `Oscillator_SMD_IDT_JU6-6_7.0x5.0mm_P2.54mm`

And yes we are aware that some libraries do not follow the klc with regards to naming but we try to steer new contributions to the correct naming.

**Comment by ki5libs** [comment]
Got it, done.

**Comment by poeschlr** [comment]
looks good now, thanks

**Comment by ki5libs** [comment]
Hi @poeschlr,

did you just forget to merge this one or I should do something else?

**Comment by poeschlr** [comment]
Yes seems i forgot to click the button. Sorry bout that.

**Pull request merged**
