### PR TITLE
added 3 variations of MMCX 73415-0961

### PR DESCRIPTION
**Pull request by Shackmeister**
Datasheet:
https://www.molex.com/pdm_docs/sd/734150961_sd.pdf

The variations are made from the recommended dimensions in the datasheet.
I would like some feedback on the name and if the edge lines are handled correctly
3D model has been made and will be added soon
molex_mmcx

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
3d model PR: https://github.com/KiCad/kicad-packages3D/pull/394

skaermbillede fra 2018-09-09 23-36-09
mmcx_molex

**Comment by Misca1234** [comment]
I get this error from kicad when I try to view the 3D model,
I guess it is because you have an open rectangle

bild

**Comment by Shackmeister** [comment]
It has an open rectangle on edge cut. Perhaps Evan and René can help out

**Comment by Misca1234** [comment]
All looks good

**Pull request merged**
