### PR TITLE
Footprint for microSIM card from JAE

### PR DESCRIPTION
**Pull request by jneiva08**
Added footprint for microSIM GSM Card

Datasheet: https://www.jae.com/z-en/pdf_download_exec.cfm?param=SJ115712.pdf

Footprint:
footprint

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
Remake the connector to be centered.

usim

Travis gives now error KLC@F6.2 because of 0.7mm of Note 1.

**Comment by Misca1234** [comment]
Is not the F.CrtYrd line a little bit to far away on left, right and top sides ?

> Travis gives now error KLC@F6.2 because of 0.7mm of Note 1.

If you mark everything and right click on it you have "Move exactly", you can experiment with this to centre the foot print if you want.

**Comment by jneiva08** [comment]
Sorry for nor reply earlier. it can be shorter.
Still i will change, to be centered like the datasheet says.

**Comment by jneiva08** [comment]
Still have KLC F6.2 error, because the center is the recommended on datasheet.

Footprint:
footprint

Measurements:
size

**Comment by jneiva08** [comment]
Forgot to add measurements of keepout
card

**Comment by jneiva08** [comment]
@Misca1234 now it should be right

**Comment by Misca1234** [comment]
jee, give me some time and I re check it

**Comment by Misca1234** [comment]
All looks good, lets keep the origo as in the data sheet

**Comment by jneiva08** [comment]
thank you for your patience for having changed several times

**Pull request merged**
