### PR TITLE
Capacitor_THT: Regenerate from scripts

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
I needed to generate radial caps with different heights. I have found that the changes to do so were in place but footprints were not updated given that https://github.com/KiCad/kicad-footprints/pull/550 was not merged.

I've changed the scripts to improve capacitor splitting a little bit and regenerated the capacitors.
Script changes in https://github.com/pointhi/kicad-footprint-generator/pull/396

Before regenerating the rest of the repos, I would like to get to an agreement about naming and if the splitting.

TODO:
- [ ] Check if I need to update symbol footprints
- [ ] Check if I need to update symbol footprint filters
- [ ] Update 3D models

I think this one will need input from @poeschlr 

Thanks!

### CODE REVIEW

**Comment by evanshultz** [comment]
As I mentioned in the PR earlier, I would like a well-defined (a matrix?) of cap libraries to make sure all footprints we need or anticipate are located nicely. Managing contributions and potential user confusion will be difficult if the library names aren't salient and well-defined.

**Comment by poeschlr** [comment]
Sorry this has to wait till v6. Really guys we can not simply split libs during a minor release.

**Comment by antoniovazquezblanco** [comment]
Please, allow me to reopen this issue in order to regenerate the caps without splitting the libs in order to keep the scripts and the library in sync.

Thanks!

**Comment by poeschlr** [comment]
I suggest a new pull request on a fresh branch after such a huge change (You will need to start from scratch anyways)

**Comment by antoniovazquezblanco** [comment]
I will do, just allow me to keep this as a reminder.

**Comment by antoniovazquezblanco** [comment]
Given this have been script generated and that the requested changes I can force push to this branch to start again and I would get the same result as now. Do you still want me to start a new PR? would you have a look at the script changes?

Thanks!

**Pull request closed without merging**
