### PR TITLE
Shielding

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Coped from old **Shielding_Cabinets** repo

### CODE REVIEW

**Comment by pointhi** [comment]
Please replace ```Wurth``` with ```Wuerth``` as discussed some time ago

**Comment by SchrodingersGat** [comment]
Thanks @pointhi , done.

**Comment by poeschlr** [comment]
Thanks. The footprints look good (You did not seem to break them)

**Comment by pointhi** [comment]
what about naming the folder ```RF_Shielding```, to cluster things together?

**Comment by SchrodingersGat** [comment]
@pointhi I like that, `Shielding` doesn't really make sense outside of RF context really, I'll fix the name.

**Comment by poeschlr** [comment]
So i have been to fast with merging. Sorry.

**Pull request merged**
