### PR TITLE
add Ninigi RJ45GE connector

### PR DESCRIPTION
**Pull request by balcer**
https://www.tme.eu/en/details/rj45ge/rj-connectors/ninigi/
https://en.ninigi.com/product/ninigi/socket/rj45ge

rj45

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
I can not find a dimensioned drawing of this. Could you link to the drawing you used to create the footprint found in this pull request?

**Comment by balcer** [comment]
tme

**Comment by poeschlr** [comment]
For future reference here the source: https://www.tme.eu/html/gfx/image_17594.gif

**Comment by poeschlr** [comment]
I think the dimensions are ok. (The drawing you found might be wrong as it seems to give the dimension i marked orange as 8.89.)

I would however suggest to either generally reduce the rest ring or at least reduce it in x direction. (right now the rest ring is 0.445 could easily be reduced down to 0.3 which would increase the clearance to ~1mm. See green dimensions.)

Screenshot from 2019-06-03 19-49-36

**Comment by balcer** [comment]
@poeschlr You are wright about wrong dimension given in drawing. This is a standard ethernet connector. Pad size reduced. Thanks for rereview.

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
