### PR TITLE
added xt60 connector

### PR DESCRIPTION
**Pull request by rs-development**
I could not find the so famous XT60 connector, so here is one:

Measurements taken from a real piece since i could not find a datasheet online. I used the footprint before and it fits fine, but maybe someone can validate.

### CODE REVIEW

**Comment by jneiva08** [comment]
Hi,

Can you put the screenshot?
What is the connector XT60 you made? I can share a link for the connector, but isn't from the maker.

Make sense to be in Connector_AMASS.pretty?

**Comment by rs-development** [comment]
image

> Make sense to be in Connector_AMASS.pretty?

Didn't know the name of the company making these connectors, would be good to put it in there.

**Comment by jneiva08** [comment]
Small review:

- The pin 1 should be in (0, 0)
- The only datasheet i know is the following: https://www.tme.eu/pt/Document/2d152ced3b7a446066e6c419d84bb460/XT60%20SPEC.pdf
- Missing %R
- Missing body should be in F.Fab
- 0.12mm offset of body in F.SilkS
- Missing F.CrtYd
- Missing default 3D wrl

Probably the naming should be:
- AMASS_XT60-F_1x02_P7.20mm_Vertical.kicad_mod
- AMASS_XT60-M_1x02_P7.20mm_Vertical.kicad_mod

**Comment by rs-development** [comment]
I will notify you after i fixed all errors.

**Comment by rs-development** [comment]
I kinda messed up my repo, i will try to fix this.

I have started the footprint from scratch, so please have a look.

I am having problems with the description of the library itself. Where it is defined?

**Comment by rs-development** [comment]
If you are happy with the male version, i will add the female version

**Comment by poeschlr** [comment]
I suggest you start over from a fresh branch. (copy the files you want to add to some unrelated folder, checkout the current state of master, create a new branch and then copy the stuff back in and commit it.) You deleted two unrelated footprints which is an absolute no go.

**Comment by poeschlr** [comment]
Now for the review:
Pin numbers fit the same order as https://github.com/KiCad/kicad-footprints/pull/1566 (not sure if this is on accident or i did miss a pin 1 indicator)

Make pad 1 square (or roundrect with 25% round radius)
How did you determine the pad dimensions? Especially the hole size. Nothing of relevance is dimensioned in the datasheet (probably because this connector is not really meant to be soldered directly to a pcb)

Screenshot from 2019-06-02 22-52-17

**Pull request closed without merging**
