### PR TITLE
Add QFN-64-1EP_9x9mm_P0.5mm_EP3.8x3.8mm

### PR DESCRIPTION
**Pull request by joshtyler**
Footprint generated with script, PR is at: https://github.com/pointhi/kicad-footprint-generator/pull/426

Datasheet is https://datasheet.lcsc.com/szlcsc/Realtek-Semicon-RTL8211EG-VB-CG_C69264.pdf (p.69)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by joshtyler** [comment]
I believe that the failing CI test is because the test script is getting confused and thinks the generated symbol is a through hole part?

**Comment by joshtyler** [comment]
Symbol PR is [here](https://github.com/KiCad/kicad-symbols/pull/2166)

**Comment by chschlue** [comment]
Yes, that's a known problem with thermal vias.

**Comment by poeschlr** [comment]
see comments on script pull request

**Comment by joshtyler** [comment]
Updated with changes from script PR.

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
