### PR TITLE
Mini-Circuits land-pattern PL-094

### PR DESCRIPTION
**Pull request by aewallin**
land-pattern: https://ww2.minicircuits.com/pcb/98-pl094.pdf
typical component: https://ww2.minicircuits.com/pdfs/ADC-10-1R.pdf
package: https://ww2.minicircuits.com/case_style/CD542.pdf

pl-094

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
I added two data-sheet links above.

**Comment by poeschlr** [comment]
I am not so sure about the naming convention here. Maybe something like "Case name" followed by "land pattern name"

Meaning something like `Mini-Circuits_CD542_LandPatternPL-094`

This all should then be reflected in the description of the footprint. 
Add both the case and land pattern drawing links plus a description. Example: 
`Footprint for mini circuit case CD542, Land pattern PL-094, pads 5 and 2 connected via insulated copper area below body, vias included (case drawing: https://ww2.minicircuits.com/case_style/CD542.pdf, land pattern drawing: https://ww2.minicircuits.com/pcb/98-pl094.pdf)`

**Comment by poeschlr** [comment]
Could you also take a look at the CD542 footpirnt that is already in the lib and copy its pin 1 marking style for the fab layer?

**Comment by poeschlr** [comment]
I think the description field has gotten renamed in the gui (in nightly it is called description again)
In v5 it is called documentation link.

**Comment by poeschlr** [comment]
Thanks. Looks good now.

**Pull request merged**
