### PR TITLE
Add Potentiometer Bourns 3314G and 3314J

### PR DESCRIPTION
**Pull request by strombom**
Bourns 3314G and 3314J
http://www.bourns.com/docs/Product-Datasheets/3314.pdf

image

image

Footprint copied from Potentiometer_Bourns_3214G_Horizontal.kicad_mod

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by strombom** [comment]
I have not made any 3D model yet.

**Comment by evanshultz** [comment]
@strombom 
Did you make these by hand? All other pots in this repo were made by script, and I think that's the best way to go. (Note that I've updated the script dramatically and haven't yet finishing some housekeeping, so the latest version of the script is on my local PC.)

**Comment by strombom** [comment]
Oh, I didn't find any script. Then we could wait for the script and close this pull request?

**Comment by strombom** [comment]
Where can I find footprint scripts?

I need to make some power resistors and started manually but maybe there are scripts?

**Comment by poeschlr** [comment]
https://github.com/pointhi/kicad-footprint-generator

**Comment by strombom** [comment]
Added 3D model: https://github.com/KiCad/kicad-packages3D/pull/263
Not sure if that will also be scripted...

**Comment by evanshultz** [comment]
The script generators are at https://github.com/pointhi/kicad-footprint-generator.

The pot script is at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/tools. The script that feeds inputs for each pot footprint is at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Potentiometers.

I've added code to generate these pots to the script and the PR is at https://github.com/KiCad/kicad-footprints/pull/349.

I'll also finish the script polish and push the updated scripts shortly.

**Comment by evanshultz** [comment]
@strombom With the script-generated footprints submitted, please close this if you have nothing further. Thanks again for all of your hard work to improve KiCad's libraries!

**Pull request closed without merging**
