### PR TITLE
CP Radial D10.0mm L20.0mm P5.00mm Horizontal

### PR DESCRIPTION
**Pull request by persus**
CP Radial D10.0mm L20.0mm P5.00mm Horizontal

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Please, post a screenshot of the footprint. Thanks!

**Comment by evanshultz** [comment]
I assume you made this manually?

This PR and https://github.com/KiCad/kicad-footprints/pull/1580 both are footprints which could be scripted. Are you up to modify the script at https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Capacitors_THT/make_Capacitors_THT.py to generate these footprints?

**Comment by poeschlr** [comment]
Not just could be scripted. Must be scripted as i am not prepared to accept anything into the lib anymore that i then later need to convert to being scripted.

**Comment by persus** [comment]
image

**Comment by persus** [comment]
> I assume you made this manually?
> 
> This PR and #1580 both are footprints which could be scripted. Are you up to modify the script at https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Capacitors_THT/make_Capacitors_THT.py to generate these footprints?

I am new with KiCad. Before I used Eagle. I didn't knew that there is the possibility of scripting such things. Yes, I am up to it, since I am a software developer. Please give me a little time to see how it works and I will script this. Thanks for your suggestion. :)

**Comment by persus** [comment]
Closing the pull request. The footprint will be scripted.

**Pull request closed without merging**
