### PR TITLE
Added OnSemi_SIP-38-6EP-9x7mm_P0.65mm_EP0.95x0.95mm 

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.onsemi.com/pub/Collateral/AX-SIP-SFEU-D.PDF#page=19

Captura de pantalla de 2020-03-31 12-00-03
Captura de pantalla de 2020-03-31 12-05-32
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chschlue same question do you think it's possible to script this footprint ? looks like a QFN package with 6 EP. Thanks

**Comment by chschlue** [comment]
No

**Comment by myfreescalewebpage** [comment]
@cnieves1 starting the review here.

- [ ] EP size should be 1.2mm in the name of the footprint (the name refer to the dimension of the footprint, not the dimension of the pad on the device itself)

Else, no comment to do.

Joel

**Comment by myfreescalewebpage** [comment]
Thanks, merging

**Pull request merged**
