### PR TITLE
Adding corrected versions of the JST GH connector series

### PR DESCRIPTION
**Pull request by poeschlr**
The JST GH connector footprints where slightly wrong in the old repo. (wrong size for the mounting pads)
I re-implemented the scripts. (Is now also configurable via a yaml file.)
I also changed the pin 1 marker from a small triangle outside the component to line next to pin 1 and triangle inside the body.

Datasheet: http://www.jst-mfg.com/product/pdf/eng/eGH.pdf

---

screenshot from 2017-11-08 21-51-28
screenshot from 2017-11-08 21-52-58

---

screenshot from 2017-11-08 20-52-36
screenshot from 2017-11-08 21-52-42

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please add "mm" after the pitch dimension :)

**Comment by poeschlr** [comment]
Good catch. Fixed.

**Comment by poeschlr** [comment]
About the center location:
I kept it at the same place at it was in the old repo. (origin is between the centers of the pads not the outside of the pads.)
Should i change this? (The script is not written in a way to allow this easily.)

**Comment by SchrodingersGat** [comment]
Does the datasheet give any indication regarding where the pick-and-place center point is?

**Comment by poeschlr** [comment]
No

**Comment by SchrodingersGat** [comment]
If it is overly difficult to change I am happy to merge as-is. I have had these connectors machine loaded onto boards without incident.

**Comment by poeschlr** [comment]
I already started with changing it. Give me a moment.

**Comment by SchrodingersGat** [comment]
Ok cool :)

**Comment by poeschlr** [comment]
Fixed

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
