### PR TITLE
Add footprint for Maxim Integrated TSOC-6

### PR DESCRIPTION
**Pull request by jneiva08**
Add footprint for TSOC-6

Datasheet: https://datasheets.maximintegrated.com/en/ds/DS2401.pdf
Package: https://pdfserv.maximintegrated.com/package_dwgs/21-0382.PDF
https://pdfserv.maximintegrated.com/land_patterns/90-0321.PDF

This footprint is for the following issue: https://github.com/KiCad/kicad-symbols/issues/962

Screenshot:
tsoc

tsoc_dim

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Note to eventual reviewer: This one is not supported by my scripts right now. The script supporting j-lead packages only supports them on all four sides. (PLCC)

**Comment by poeschlr** [comment]
The footprint name should include much more info. It should feature the body size and pin pitch.

The silk pin 1 mark is not really easy to see the way you made it. Might i suggest something like this?

screenshot from 2019-01-20 19-56-33

Your dimensioned drawing does agree with the maxim suggestion.

**Comment by jneiva08** [comment]
@poeschlr, as you have recommended, I have moved footprint to Package_SO_J-Lead

Have changed top F.SilkS to the center to easely identify pin 1.

tsoc

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
