### PR TITLE
Quectel BC95

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.quectel.com/UploadImage/Downlad/Quectel_BC95_Hardware_Design_V1.3.pdf

Screenshot: 
bc95

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi @jneiva08,

Thanks for your contribution. By the way, amazing footprint. Some remarks:

- Which symbol do you intend to use with this?

- No deviation from manufacturer recommendation has found.
- No KLC violation has found.

image

**Comment by jneiva08** [comment]
Hi,

I have already made the symbol, but didn't have time to finish the NC pins.
They are too many pins and don't know how will fit inside the square.

bc95

**Comment by gmsotavio** [comment]
> Hi,
> 
> I have already made the symbol, but didn't have time to finish the NC pins.
> They are too many pins and don't know how will fit inside the square.
> 
> bc95

I have no idea how to handle this. I need some help.

**Comment by gmsotavio** [comment]
> Hi,
> 
> I have already made the symbol, but didn't have time to finish the NC pins.
> They are too many pins and don't know how will fit inside the square.
> 
> bc95

@poeschlr I have no idea how to handle this. I need some help.

**Comment by gmsotavio** [comment]
@poeschlr 
> Hi,
> 
> I have already made the symbol, but didn't have time to finish the NC pins.
> They are too many pins and don't know how will fit inside the square.
> 
> bc95

@poeschlr I have no idea how to handle this. I need some help.

**Comment by poeschlr** [comment]
The NC pin rule specifically allows not including them if there are this many. (This assumes the pins are indeed NC pins. I have not checked the datasheet if this is the case)

**Comment by jneiva08** [comment]
@gmsotavio @poeschlr , have added symbol but didn't the NC pins only added 1 to 49

**Comment by jneiva08** [comment]
@gmsotavio, have fixed the F.Paste for proper stencil, didn't change any dimensions.

I found recently the following pdf when was making another module footprint. The pdf can find it in:
https://www.quectel.com/UploadImage/Downlad/Quectel_Module_Secondary_SMT_Application_Note_V2.7.pdf#page=14

**Comment by myfreescalewebpage** [comment]
@jneiva08 No comment to add on the footprint, thanks for the modification of the Paste according to the doc linked. I will now have a look to the symbol. Merging the fp.

**Comment by jneiva08** [comment]
@myfreescalewebpage, the changes in the F.Paste it's not wright have was my first attempt to fix it. it's better to make new PR to fix-it?

**Comment by myfreescalewebpage** [comment]
@jneiva08 the Paste was correct for me, I don't understand what you mean which need to be changed ?

**Comment by jneiva08** [comment]
@myfreescalewebpage, the F.Paste on center pins needs to be little bigger and the outside need be between 0.4 and 0.6mm
you can see in the following [link](https://www.quectel.com/UploadImage/Downlad/Quectel_Module_Secondary_SMT_Application_Note_V2.7.pdf#page=14), i can make the changes

**Comment by myfreescalewebpage** [comment]
Ok you can open a new PR no problem

**Pull request merged**
