### PR TITLE
Add dfn 6 2 ep 2x2mm p0.65mm ep1x0.7mm

### PR DESCRIPTION
**Pull request by pboe**
As discussed with @evanshultz  in Issue  #1452 
First commit on github ever, so please cut me some slack.
Datasheets:
- https://www.infineon.com/dgdl/irlhs6376pbf.pdf?fileId=5546d462533600a401535663bef425af
- https://www.onsemi.com/pub/Collateral/FDMA2002NZ-D.pdf
- https://assets.nexperia.com/documents/data-sheet/PMDPB56XNEA.pdf
- http://www.mccsemi.com/up_pdf/MCMNP517(DFN2020-6U)-A.pdf
- http://aosmd.com/res/data_sheets/AON2810.pdf
- https://www.diodes.com/assets/Datasheets/DMP2065UFDB.pdf

dfn

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by pboe** [comment]
Pushed again with the correct user and email. Sorry for the inconvenience.

**Comment by poeschlr** [comment]
The first two commits are still with the old mail address. I suggest you squash all 3 commits into one and push that.
Another option is to take the asset you want to add and copy it to a new branch (copy it to a save location, switch branch, copy it back in, commit it) and open a new pull request. (Hacky but requires less knowledge about git)

**Comment by pboe** [comment]
OK, took the option for a new branch and opened a new pull request. Thanks for the supervision.

**Comment by evanshultz** [comment]
Let's close this now and we can move over to https://github.com/KiCad/kicad-footprints/pull/1528.

**Pull request closed without merging**
