### PR TITLE
Varistor: Add a 4.9 width version

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Copy-paste of the 4.8mm version but slightly wider.

To be used with VDRS05C275BSE
https://www.mouser.es/datasheet/2/427/vdrs-101657.pdf
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Dimension e (pitch in y direction) is not quite right.
screenshot from 2019-01-19 00-42-19

I now wonder if we need to include this dimension in the naming scheme. Maybe something we should keep in mind for version 6.

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by poeschlr** [comment]
Looks good, thanks
screenshot from 2019-01-22 21-18-19

**Comment by antoniovazquezblanco** [comment]
Thanks!

**Pull request merged**
