### PR TITLE
Button_Switch_SMD: Add new Wuerth button

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://katalog.we-online.com/em/datasheet/434133025816.pdf

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
We normally only include the array nomenclature (xN) for N > 1.

Courtyard clearance in x direction is wrong.
Screenshot from 2019-10-28 21-39-41

**Comment by antoniovazquezblanco** [comment]
Done

**Comment by poeschlr** [comment]
thanks

**Comment by antoniovazquezblanco** [comment]
Thank you very much!

**Pull request merged**
