### PR TITLE
Fix EP round-radius for scripted footprints (#1798)

### PR DESCRIPTION
**Pull request by poeschlr**
script changes: https://github.com/pointhi/kicad-footprint-generator/pull/422
Discussion: #1798

This changes all exposed pads from 25% (maximum 0.25mm) round radius to be the same as for the normal pads of the same footprint. (Most datasheets show rounded corners without dimensioning them, they look similar in radius to the normal pads of the same footprint.) 

Tip for review: look at the script ;) Checking the footprints would be infeasible.

### CODE REVIEW

**Comment by poeschlr** [comment]
Guys this should have quite a high priority as it has the potential of generating massive merge issues if left for too long. Also every generator footprint that is created between this change and the time this (and the script side) is merged will need to be recreated to fit this change (again something that will get worse with every day)

**Comment by evanshultz** [comment]
It appears this will address https://github.com/KiCad/kicad-footprints/issues/1655, right?

**Comment by poeschlr** [comment]
Yes

**Comment by poeschlr** [comment]
@evanshultz did you forget about this or just no time? (Your last comment indicated that you already looked at it and as there is not "this needs to be fixed" part i also kind of assumed it should be ready after answering your question.)

**Comment by evanshultz** [comment]
In the script PR I have three outstanding comments which were minor and don't affect the footprints, but would you mind addressing them first? I wanted to wait to get more input on the script but I think enough time has passed.

**Comment by evanshultz** [comment]
I spot-checked a half-dozen or so of the footprints and the changes to the EP seem correct (the radius matches the outer pads).

Just by randomly clicking, though, I happened to pick `SOIC-4_4.55x3.7mm_P2.54mm` and noticed a pad number change. Is that intentional? Did you check for noteworthy/breaking changes outside of the EP radius or other benign changes that are incremental script improvements?

**Comment by poeschlr** [comment]
I think the SOIC-4 was one that got modified in the footprint editor when it was contributed originally. We should have never allowed it to be placed in the same size definition documents to be honest.

**Comment by evanshultz** [comment]
So does this pin number change need to be reverted? Do these footprints, to your knowledge, then need to be reviewed for other unintended issues?

**Comment by poeschlr** [comment]
The SOIC-4_4.55x3.7mm_P2.54mm has the exclude pin list set wrong (it excludes 2, 4 but should exclude 2, 5) The exclude pin stuff has been added to the script since it was originally generated (but then again it should not have been placed into the same size definition file as the non hand manipulated definitions)
I will fix that as soon as i find time.

**Comment by poeschlr** [comment]
Fixed the soic-4.

I think this one is named wrong to be honest. it is a soic-6 with missing pins not a pure soic-4. but that would be something for a later date. Issue created https://github.com/KiCad/kicad-footprints/issues/1904

**Pull request closed without merging**
