### PR TITLE
added NodeMCU modules ESP-12E and ESP-32S

### PR DESCRIPTION
**Pull request by farkasgzoltan**
*Replace this line with your commit message! Please provide a description of your pull request*

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Please sign the license agreement, Add a screenshot of your contribution and a link to the datasheet that inspired its creation.

**Comment by farkasgzoltan** [comment]
I still learn how to use Kicad.
I will fix it!

**Comment by poeschlr** [comment]
Nothing of what i requested requires kicad (ok the screenshot does but opening a footprint should already be known to you as you designed one)
All of it needs to be done here on github

**Comment by Misca1234** [comment]
@farkasgzoltan 
Hi

1. Please sign the license/cla, you see it on this page, see image below
2. Please provide screen shoots of your components and a links to the data sheets
3. I can see on the names, for example, ESP-12E_ESP8266, check the RF_Module library, we have over the past months been merging RF modules with ESP chips, it might be so that those you want are already merged by others.

Look at this merge and you get a feeling what would be good if you provide in a push
https://github.com/KiCad/kicad-symbols/pull/998


bild

**Pull request closed without merging**
