### PR TITLE
Package_DFN_QFN: Add Texas_S-PWQFN-N32_EP2.8x2.8mm

### PR DESCRIPTION
**Pull request by zonque**
Used by this part:

  https://www.ti.com/lit/ds/symlink/bq25703a.pdf (page 91)

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 

image

### CODE REVIEW

**Comment by zonque** [comment]
Generator PR: https://github.com/pointhi/kicad-footprint-generator/pull/330

**Comment by zonque** [comment]
Oh, the script generates footprints that fail the Travis checks? Hmm.

**Comment by poeschlr** [comment]
The travis check simply does not deal well with thermal vias. It throws false positives for it. (This is because it does not realize that these are vias but assumes them to be normal tht pads which of course have different layer requirements compared to what we use them for when creating thermal vias.)

**Comment by poeschlr** [comment]
Looks good now. Thanks

**Pull request merged**
