### PR TITLE
Add Sunlord MWSA0518 Inductors 

### PR DESCRIPTION
**Pull request by joshtyler**
[Datasheet](http://www.sunlordinc.com/Download.aspx?file=L1VwbG9hZEZpbGVzL1BERl9DYXQvMjAxODA1MTAxNDU4NTM5MDIucGRm&lan=en)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by joshtyler** [comment]
Updated screenshot now KLC errors are fixed:
image

**Comment by poeschlr** [comment]
I suggest to increase the clearance between silk and exposed copper to about 0.2mm (There will be enough silk left and this allows the footprint to be used by much cheaper fabs)

Add the body dimension to the footprint name.

The footprint clearance in x direction is too large
Screenshot from 2019-10-27 19-16-02

**Comment by joshtyler** [comment]
Thank you for the review! The commits I have made should address your comments.
Updated screenshot:
image

Out of interest, how did you produce the dimensioned diagram in your comment? It looks like a good way to ensure that footprints are correct.

**Comment by poeschlr** [comment]
> Out of interest, how did you produce the dimensioned diagram in your comment? It looks like a good way to ensure that footprints are correct.

Read what github posted into your bug description. The tutorial is linked in there ;)

**Comment by poeschlr** [comment]
The footprint looks good now, thanks

**Pull request merged**
