### PR TITLE
Add a new footprint for ethernet conectors

### PR DESCRIPTION
**Pull request by fr4nc15co**
Datasheet:
https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwiCsIurxpHZAhXHtRQKHWC5B6gQFggoMAA&url=https%3A%2F%2Fwww.wiznet.hk%2Fen%2Findex.php%3Fcontroller%3Dattachment%26id_attachment%3D2&usg=AOvVaw0koItAcjo_XMUMN_kFX47m

conector

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
A screenshot of the footprint would make our live a lot easier

**Comment by fr4nc15co** [comment]
@poeschlr The screenshot and the datasheet link were already uploaded.

**Comment by poeschlr** [comment]
I see only a screenshot of the datasheet not for the footprint it self.

**Comment by fr4nc15co** [comment]
@poeschlr I misunderstood you, sorry

rj45

**Comment by Shackmeister** [comment]
@fr4nc15co Are you planning on getting back to this PR? :)

**Comment by Shackmeister** [comment]
Hi @fr4nc15co 
Can you please let us know if we can be helpful with moving this PR along somehow?
In case you don't plan on getting back to this, it would be great to know, so we can either close it or have somebody else take over :)

**Comment by poeschlr** [comment]
The land pattern does not look bad. I will finish this up in a separate pull request.
For reference the dimensioned drawing made from this contribution:
screenshot from 2018-08-29 15-12-27

**Comment by poeschlr** [comment]
Finished in https://github.com/KiCad/kicad-footprints/pull/894

**Comment by Shackmeister** [comment]
fixed in https://github.com/KiCad/kicad-footprints/pull/894

**Pull request closed without merging**
