### PR TITLE
add RAK Wireless RAK4200 LoRa module footprint

### PR DESCRIPTION
**Pull request by alnunez**
RAK Wireless RAK4200 LoRa modules.

Datasheet: [https://downloads.rakwireless.com/LoRa/RAK4200/Hardware-Specification/RAK4200_Module_Specifications_V1.4.pdf](https://downloads.rakwireless.com/LoRa/RAK4200/Hardware-Specification/RAK4200_Module_Specifications_V1.4.pdf)

Schematic PR# [2859](https://github.com/KiCad/kicad-symbols/pull/2859) 

RAK4200-FP

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@alnunez thanks for this footprint. Two comment to start the review:

- [ ] The footprint is not vertically centered
- [ ] You should round the position of the lines on CrtYd layer, see following screenshot.

Capture

Joel

**Comment by alnunez** [comment]
> @alnunez thanks for this footprint. Two comment to start the review:
> 
> * [ ]  The footprint is not vertically centered
> * [ ]  You should round the position of the lines on CrtYd layer, see following screenshot.
> 
> Capture
> 
> Joel

Done!

**Comment by alnunez** [comment]
> Thanks, I continue the review, global dimensions, pins size and position checked OK.
> 
> Change required:
> 
> * [ ]  F.Silk: You can put the lines closest to F.Fab lines. We use generally an offset of 0.12mm with F.Fab layer (it's enough).
> * [ ]  F.CrtYd: You can put the top and bottom lines closest to F.Fab lines (left and right are ok for me). We use generally an offset of 0.5mm with F.Fab layer (it's enough).
> 
> Joel

Done, F.Silk closer to F.Fab 0.12mm. Upper and lower F.CrtYd now at 0.5mm to F.Fab

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment, merging.

**Pull request merged**
