### PR TITLE
Add QFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm footprint.

### PR DESCRIPTION
**Pull request by whitequark**
This is a straightforward QFN footprint variant, unmodified from the KiCAD generator.

Datasheet: https://www.diodes.com/assets/Datasheets/PI6C5946002.pdf#page=12
Screenshot:
Screenshot_20200112_193419
Symbol PR: https://github.com/KiCad/kicad-symbols/pull/2441

Rule violations:
  * F9.3: the model should have a 1.8x1.8mm EP, not a 1.6x1.6mm one; the datasheet explicitly uses different EP sizes for package and footprint.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Footprints for generic packages like these must be generated using our IPC compatible footprint generator found here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by whitequark** [comment]
@poeschlr Regenerated.

**Comment by whitequark** [comment]
Updated the script in https://github.com/pointhi/kicad-footprint-generator/pull/485.

**Comment by whitequark** [comment]
Regenerated again.
Screenshot_20200209_175231

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
