### PR TITLE
Kobitone buzzer 254-EMB84Q-RO

### PR DESCRIPTION
**Pull request by carlosromorgar**
https://www.mouser.es/datasheet/2/209/KT-400385-1171904.pdf

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by carlosromorgar** [comment]
Hi
This is the new aspect
image


BR

**Comment by Misca1234** [comment]
You don't need to mark out + and -, I suggest you remove those markers

Because the foot print is already polarized I guess you do not need a pin 1 marker at all, but if you do, 
I suggest you do two circles, on in F.FAb as now, and one in F.Silk outside the F.Fab

**Comment by carlosromorgar** [comment]
Hi,

sorry for my late response. I have done the changes. This is the result.

Best regards

image

**Comment by Misca1234** [comment]
Great, thx

**Pull request merged**
