### PR TITLE
Xm1100 xm1110

### PR DESCRIPTION
**Pull request by Misca1234**
This push is for Sierra's GNSS chip and modules

XM1100 
https://source.sierrawireless.com/~/media/support_downloads/airprime/hardware_specs_user_guides/airprime_xm1100_product_technical_specification_rev4_0.ashx
Sort of QFN-20

XM1110 
https://source.sierrawireless.com/~/media/support_downloads/airprime/hardware_specs_user_guides/airprime_xm1110_product_technical_specification_rev3_1.ashx
Sort of QFN-20

XA1100
https://source.sierrawireless.com/~/media/support_downloads/airprime/hardware_specs_user_guides/airprime_xa1100_product_technical_specification_rev4_1.ashx
Sort of QFN-24

These will be used for 
XM1100 and XM1110
and
XA1100, XA1110, XA1120 and XA1130

bild

bild

bild

bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
This push includes some foot prints that should not be included, give me some minutes to re push

**Comment by Misca1234** [comment]
Now so

**Comment by poeschlr** [comment]
When trying to open the datasheets i get "permission denied"

**Comment by Misca1234** [comment]
No idea, I guess it is another annoying policy in line with "We want to know who our customer is" shit, 
shall I send them via email ?

**Comment by poeschlr** [comment]
I would suggest you simply put a screenshot of the relevant part of the datasheet here.

**Comment by Misca1234** [comment]
Here they are

bild

bild

bild

bild

**Comment by poeschlr** [comment]
The courtyard should be outside the pads.

The land pattern looks to be ok.
screenshot from 2018-12-29 10-30-47

**Comment by Misca1234** [comment]
Hmm, these could be made with the QFN script, i have a look

**Comment by poeschlr** [comment]
The script does not really support missing pads. Especially not when the count is uninterrupted.

**Comment by Misca1234** [comment]
For a quick solution I continue with the manual, but I wil lsee if I can squeeze in a fix for the script

**Comment by Misca1234** [comment]
They look like this now

bild

bild

**Comment by Misca1234** [comment]
Not sure what happen, after this "fixing the history issue" it did not push to this thread but instead here

https://github.com/KiCad/kicad-footprints/pull/1229

I guess this thread can then be closed

**Comment by poeschlr** [comment]
The reason might be that this pull request is connected to a branch on the official repo instead of to one on your fork. I assume you now have setup your local repo such that you can not really push directly to the official one so this was kind of to be expected.

**Comment by Misca1234** [comment]
Hmm, the AK300 worked, I guess because this push is so old it might be some additional "problems"

**Comment by poeschlr** [comment]
After looking at your other push i am kind of convinced that you simply pushed to the wrong "branch" (Misca1234:XM1100_XM1110 instead of KiCad:XM1100_XM1110)
This is totally ok. (This PR was connected to a kind of illegal branch anyways.)

**Comment by poeschlr** [comment]
Replacement merged. Closing this.

**Pull request closed without merging**
