### PR TITLE
Package_SO: fix ssop-8.3.95x5.21x3.27mm_P1.27mm

### PR DESCRIPTION
**Pull request by sebastianbasierski**
There are 2 pads with number '1'.
One of that pair should be named as '8'.

Signed-off-by: Sebastian Basierski <sebastian@basierski.pl>

*Replace this line with your commit message! Please provide a description of your pull request*

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
@strombom you added this in https://github.com/KiCad/kicad-footprints/pull/333. I think the dual pin 1 is indeed a mistake and this would fix it.

@sebastianbasierski please sign the contributor license agreement.

**Comment by strombom** [comment]
Thanks, yes looks like a bad mistake!

**Comment by sebastianbasierski** [comment]
Should be signed now.

**Comment by poeschlr** [comment]
The commit does not seem to be linked to your account. (I would guess your local git client is setup with a different mail address then the one you have set in your github account.)

I can merge it this way but am not sure if this will result in us losing the green status for the CLA manager. (I assume this will not be a problem as you have agreed to it with your latest comment.)

**Comment by jkriege2** [comment]
Uuupps ... didn't see that one, when merging the footprint ... please merge ASAP, this is definitely a bug and unintended!

**Comment by poeschlr** [comment]
I will merge it tomorrow even if the CLA stuff is not resolved until then.

**Comment by sebastianbasierski** [comment]
@poeschlr That could be it. Emails are different. I've added now an address. Maybe this will help. Thank You for explanation.

**Comment by Shackmeister** [comment]
CLA stuff has been fixed, so Ill merge this

**Pull request merged**
