### PR TITLE
Add previously existing converters

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Work in progress

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Names could be a little bit more unified here. Current names list:
```ACDC-Conv_Hahn-HS-400XX.kicad_mod
ACDC-Conv_MeanWell-IRM-20-XX.kicad_mod
ACDC-Conv_SMMeanWell-IRM-02-XX.kicad_mod
ACDC-Conv_SMMeanWell-IRM-03-XX.kicad_mod
ACDC-Conv_THTMeanWell-IRM-02-XX.kicad_mod
ACDC-Conv_THTMeanWell-IRM-03-XX.kicad_mod
ACDC-Conv_Traco-TMLM-04.kicad_mod
ACDC-Conv_Traco-TMLM-05.kicad_mod
ACDC-Conv_Traco-TMLM-10-20.kicad_mod
ACDC-Conv_Vigortronix_VTX-214-010-XXX.kicad_mod
ACDC-Conv_Vigortronix_VTX-214-010-XXX_Miniature.kicad_mod
ACDC-Conv_Vigortronix-VTX-214-015-1XX.kicad_mod
DCDC-Conv_BOTHHAND_CFUDxxxx-Serie.kicad_mod
DCDC-Conv_BOTHHAND_CFUSxxxxEH-Serie.kicad_mod
DCDC-Conv_BOTHHAND_CFUSxxxx-Serie.kicad_mod
DCDC-Conv_CINCON_EC5BEXX_Dual.kicad_mod
DCDC-Conv_CINCON_EC5BEXX_Single.kicad_mod
DCDC-Conv_CINCON_EC6CXX_Dual_Tripple.kicad_mod
DCDC-Conv_CINCON_EC6CXX_Single.kicad_mod
DCDC-Conv_MeanWell_NID30.kicad_mod
DCDC-Conv_MeanWell_NID60.kicad_mod
DCDC-Conv_muRata_CRE1xxxxxx3C.kicad_mod
DCDC-Conv_muRata_CRE1xxxxxxDC.kicad_mod
DCDC-Conv_muRata_CRE1xxxxxxSC.kicad_mod
DCDC-Conv_muRata_NMAxxxxDC.kicad_mod
DCDC-Conv_muRata_NMAxxxxSC.kicad_mod
DCDC-Conv_muRata_NXE2SxxxxMC.kicad_mod
DCDC-Conv_RECOM_R5xxxDA.kicad_mod
DCDC-Conv_RECOM_R5xxxPA.kicad_mod
DCDC-Conv_RECOM_R-78B-2.0.kicad_mod
DCDC-Conv_RECOM_R-78E-0.5.kicad_mod
DCDC-Conv_RECOM_R-78HB-0.5.kicad_mod
DCDC-Conv_RECOM_R-78HB-0.5L.kicad_mod
DCDC-Conv_Recom_R-78HBxx-0.5.kicad_mod
DCDC-Conv_RECOM_R-78S-0.1.kicad_mod
DCDC-Conv_TRACO_TEN10-xxxx.kicad_mod
DCDC-Conv_TRACO_TEN10-XXXX_Dual.kicad_mod
DCDC-Conv_TRACO_TEN10-XXXX_Single.kicad_mod
DCDC-Conv_TRACO_TEN20-xxxx.kicad_mod
DCDC-Conv_TRACO_TEN20-XXXX_Dual.kicad_mod
DCDC-Conv_TRACO_TEN20-XXXX_Single.kicad_mod
DCDC-Conv_TRACO_TMR_1-xxxx_Dual.kicad_mod
DCDC-Conv_TRACO_TMR_1-xxxx_Single.kicad_mod
DCDC-Conv_TRACO_TMR_xxxx.kicad_mod
DCDC-Conv_TRACO_TMR-1SM.kicad_mod
DCDC-Conv_TRACO_TSR-1.kicad_mod
```
I would name using the following criteria `Converter_{ACDC|DCDC}_Manufacturer_Model.kicad_mod`

Should I proceed?

**Comment by antoniovazquezblanco** [comment]
More doubts:
Capital vs small letters in series numbering: `DCDC-Conv_TRACO_TEN10-xxxx.kicad_mod` vs `DCDC-Conv_TRACO_TEN10-XXXX.kicad_mod`

There is a DCDC converter that has three versions. Single, double and triple output. Double and triple output models share the same footprint. Currently has two modifiers at the end `_Double_Triple`. Should it be `_DoubleAndTriple`? `_Double-Triple`? Any other suggestion?

**Comment by poeschlr** [comment]
I generally like your suggestion of  `Converter_[ACDC|DCDC]_Manufacturer_Model_[SMD|THT].kicad_mod`
I would include SMD/THT in all footprints. (Otherwise we maintainer need to check for every future contribution if this specifier is required or not. And it makes searching for smd or tht easier.)

Or we could split the lib between SMD and THT versions. Like we already do for other libs. (Examples: LED, Resistor, ...) If we do this the specifier would not be required within the footprint name.

@antoniovazquezblanco wrote:
> There is a DCDC converter that has three versions. Single, double and triple output. Double and triple output models share the same footprint. Currently has two modifiers at the end _Double_Triple. Should it be _DoubleAndTriple? _Double-Triple? Any other suggestion?

Is this not already fully specified via the part number? I think converters only exist as atomic parts anyways. 
Or are there generic symbols that would need these suffixes to define their footprint filters? If so then we need two footprints even if they would be compatible. Meaning one for double and one for triple.

**Comment by antoniovazquezblanco** [comment]
I will add the THT/SMD sufix to every footprint then.

@poeschlr wrote:
> Is this not already fully specified via the part number? I think converters only exist as atomic parts anyways.
Or are there generic symbols that would need these suffixes to define their footprint filters? If so then we need two footprints even if they would be compatible. Meaning one for double and one for triple.

In this case both the Double and Triple versions have the same footprint and the Single has a different version. That is, three different symbols with two different footprints. The symbols will need the suffixes for their footprint filters, yes.

How should I proceed with the Double/Triple suffix?
What about the `x` vs `X` in series numbering?

**Comment by antoniovazquezblanco** [comment]
Maybe @SchrodingersGat has some pointers.

**Comment by evanshultz** [comment]
I'm a bit confused about the problem. If there are three symbols, one for single, dual, and triple output, then create those symbols. Use the ALIAS feature to add each unique MPN to each symbol.

Then the footprint for the single symbol will point to the single footprint, and both the dual and triple symbols will use the same footprint.

@antoniovazquezblanco Can you point out an example that is giving you trouble? [Cincon EC6C](http://www.cincon.com/upload/media/data%20sheets/EC6C-V11.pdf) is listed in your table but it seems straightforward as I described above.

Also, there is a good bit of naming and spelling corrections to be done in the list of footprints above.

**Comment by antoniovazquezblanco** [comment]
Ok. Sorry if I am not able to explain myself. It is sometimes difficult for me as it is not my first language.

I have doubts about the naming schema. This is not related to symbols, just how to name the footprints. The example you pointed out it is the one I was looking at so lets focus on it. I am asking about what do you prefer:
`Converter_DCDC_Cincon_EC6CXX_DualTriple_THT`
`Converter_DCDC_Cincon_EC6CXX_Dual_Triple_THT`
`Converter_DCDC_Cincon_EC6CXX_DualAndTriple_THT`
Or if there is another option that you would like more than any of my proposals.

Also, the second doubt is regarding whether to capitalize or not the `X` in series numbering. So for example:
`Converter_DCDC_muRata_CRE1xxxxxx3C_THT`
`Converter_DCDC_muRata_CRE1XXXXXX3C_THT`

**Comment by jkriege2** [comment]
Hi!

when you rename the footprints, could you also post a PR to the symbols, where you duplicate those renames there?

Thanks,
JAN

**Comment by antoniovazquezblanco** [comment]
Will do @jkriege2 ;)

**Comment by SchrodingersGat** [comment]
I think there are enough footprints here to justify splitting into SMD and THT libs. Otherwise I like your naming conventions :)

**Comment by antoniovazquezblanco** [comment]
Currently there are only two SMD footprints. I can move them to a different repo but seems a bit to excessive for just them.

Current name list:
```
Converter_ACDC_Hahn_HS-400XX_THT.kicad_mod
Converter_ACDC_MeanWell_IRM-02-XX_SMD.kicad_mod
Converter_ACDC_MeanWell_IRM-02-XX_THT.kicad_mod
Converter_ACDC_MeanWell_IRM-03-XX_SMD.kicad_mod
Converter_ACDC_MeanWell_IRM-03-XX_THT.kicad_mod
Converter_ACDC_MeanWell_IRM-20-XX_THT.kicad_mod
Converter_ACDC_TRACO_TMLM-04_THT.kicad_mod
Converter_ACDC_TRACO_TMLM-05_THT.kicad_mod
Converter_ACDC_TRACO_TMLM-10-20_THT.kicad_mod
Converter_ACDC_Vigortronix_VTX-214-010-XXX_Miniature_THT.kicad_mod
Converter_ACDC_Vigortronix_VTX-214-010-XXX_THT.kicad_mod
Converter_ACDC_Vigortronix_VTX-214-015-1XX_THT.kicad_mod
Converter_DCDC_Bothhand_CFUDXXXX_THT.kicad_mod
Converter_DCDC_Bothhand_CFUSXXXX_THT.kicad_mod
Converter_DCDC_Bothhand_CFUSXXXXEH_THT.kicad_mod
Converter_DCDC_Cincon_EC5BEXX_Dual_THT.kicad_mod
Converter_DCDC_Cincon_EC5BEXX_Single_THT.kicad_mod
Converter_DCDC_Cincon_EC6CXX_DualTriple_THT.kicad_mod
Converter_DCDC_Cincon_EC6CXX_Single_THT.kicad_mod
Converter_DCDC_MeanWell_NID30_THT.kicad_mod
Converter_DCDC_MeanWell_NID60_THT.kicad_mod
Converter_DCDC_muRata_CRE1XXXXXX3C_THT.kicad_mod
Converter_DCDC_muRata_CRE1XXXXXXDC_THT.kicad_mod
Converter_DCDC_muRata_CRE1XXXXXXSC_THT.kicad_mod
Converter_DCDC_muRata_NMAXXXXDC_THT.kicad_mod
Converter_DCDC_muRata_NMAXXXXSC_THT.kicad_mod
Converter_DCDC_muRata_NXE2SXXXXMC_THT.kicad_mod
Converter_DCDC_RECOM_R5XXXDA_THT.kicad_mod
Converter_DCDC_RECOM_R5XXXPA_THT.kicad_mod
Converter_DCDC_RECOM_R-78B-2.0_THT.kicad_mod
Converter_DCDC_RECOM_R-78E-0.5_THT.kicad_mod
Converter_DCDC_RECOM_R-78HB-0.5_THT.kicad_mod
Converter_DCDC_RECOM_R-78HB-0.5L_THT.kicad_mod
Converter_DCDC_RECOM_R-78HBXX-0.5_THT.kicad_mod
Converter_DCDC_RECOM_R-78S-0.1_THT.kicad_mod
Converter_DCDC_TRACO_TEN10-XXXX_Dual_THT.kicad_mod
Converter_DCDC_TRACO_TEN10-XXXX_Single_THT.kicad_mod
Converter_DCDC_TRACO_TEN10-XXXX_THT.kicad_mod
Converter_DCDC_TRACO_TEN20-XXXX_Dual_THT.kicad_mod
Converter_DCDC_TRACO_TEN20-XXXX_Single_THT.kicad_mod
Converter_DCDC_TRACO_TEN20-XXXX_THT.kicad_mod
Converter_DCDC_TRACO_TMR-1SM_THT.kicad_mod
Converter_DCDC_TRACO_TMR-1-XXXX_Dual_THT.kicad_mod
Converter_DCDC_TRACO_TMR-1-XXXX_Single_THT.kicad_mod
Converter_DCDC_TRACO_TMR-XXXX_THT.kicad_mod
Converter_DCDC_TRACO_TSR-1_THT.kicad_mod
```

Any other suggestion? Should we merge?

**Comment by SchrodingersGat** [comment]
I'm happy with that naming :) @jkriege2 @poeschlr ?

**Comment by evanshultz** [comment]
@antoniovazquezblanco This is great work!

A few comments:
- We use a small `x` as a wildcard according to http://kicad-pcb.org/libraries/klc/S2.2/.
- Add a hyphen between `Dual` and `Triple` instead of running the words together, like in `Converter_DCDC_Cincon_EC6CXX_DualTriple_THT.kicad_mod`? Hyphens are used within the same section, according to KLC, while underscores are section separators.
- I don't see `Converter_ACDC_Vigortronix_VTX-214-010-XXX_Miniature_THT` being used by any of the symbols in the legacy ac-dc.lib or dc-dc.lib. Also, the datasheet at http://www.vigortronix.com/10WattACDCPCBPowerModule.aspx only lists one size (36x56mm) which matches the non-miniature version. To what does the miniature footprint belong?
- If I'm selecting a power supply module during schematic design I will be thinking about AC- or DC-input, so it makes sense to me that the symbols libraries are divided along those lines. In isolation, footprints make most sense (to me) to divide between THT and SMD. But should we separate both symbols and footprints by input voltage shape for consistency?
- Always specify `Single`, `Dual`, `Triple`, or come combination thereof? I'm not strong on this point.

**Comment by antoniovazquezblanco** [comment]
Addressed @evanshultz suggestions ;)

**Comment by antoniovazquezblanco** [comment]
Awaiting feedback @poeschlr @jkriege2 @SchrodingersGat @evanshultz

Thanks!

**Comment by SchrodingersGat** [comment]
The naming looks very clean now, thanks for transferring these across :)

**Pull request merged**
