### PR TITLE
Added footprint for CUI CMT-8504-100-SMT

### PR DESCRIPTION
**Pull request by cnieves1**
Datasheet: https://www.cuidevices.com/product/resource/pdf/cmt-8504-100-smt-tr.pdf
3D: https://github.com/KiCad/kicad-packages3D/pull/664

imagen

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cnieves1** [comment]
I don't understand why TravisCI is checking the footprint of this PR _and_ other footprints.
It seems there are no issues with this footprint:
```
Checking: Buzzer_Beeper.pretty/MagneticBuzzer_CUI_CMT-8504-100-SMT.kicad_mod
Checking footprint 'MagneticBuzzer_CUI_CMT-8504-100-SMT' - No errors
```

**Comment by chmorgan** [comment]
@cnieves1 can you fetch and rebase against kicad-footprints master? While GitHub is reporting the correct thing, and git log master..cui_cmt8504 reports just your changes the state of your branch prior to your changes does not match master.

**Comment by cnieves1** [comment]
I think it is done now... Please test...

**Comment by cnieves1** [comment]
Changes done.
Captura de pantalla de 2020-03-16 21-42-12

I use Device:Buzzer symbol. I noticed that there are several buzzer footprints, but no specific symbol or alias for them. Should I add an alias for this buzzer to Device:Buzzer symbol? I think it would be better...

**Comment by chmorgan** [comment]
@cnieves1 it looks like a bunch of other changes got pulled into this pull request. Would you know how to fix that with git or do you need help there? I think just the last change is what you want to include in this branch.

**Comment by cnieves1** [comment]
Seems it was not a clean rebase... I think it is fixed now...

**Comment by chmorgan** [comment]
@cnieves1 what do you think about removing the silk plus that is inside of the part outline now that there is one outside? The fab plus I think is good as it matches with the datasheet but the inside silk plus looks a little odd given that we have one outside of the part already...

**Comment by cnieves1** [comment]
Done

**Pull request merged**
