### PR TITLE
Footprint for Taoglas GPS antenna

### PR DESCRIPTION
**Pull request by jneiva08**
added footprint for 2 GPS antennas from Taoglas

Taoglas CGGBP.18.4.A.02
datasheet: http://www.taoglas.com/images/product_images/original_images/CGGBP.18.4.A.02.pdf
symbol:
gps_18_2

gps_18

Taoglas CGGBP.25.4.A.02
datasheet: http://www.taoglas.com/images/product_images/original_images/CGGBP.25.4.A.02.pdf
symbol:
gps_25_2

gps_25

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Is there a reason for choosing 0.5mm courtyard clearance?

**Comment by jneiva08** [comment]
No reason at all, should be 0,25?

**Comment by poeschlr** [comment]
yes unless there is a special reason, kicad footprints should use 0.25mm courtyard clearance

**Comment by poeschlr** [comment]
The y position of the pad relative to the outline is not quite right for the smaller of the two parts:

screenshot from 2018-08-27 09-12-50

**Comment by jneiva08** [comment]
I did check the math it appears to be fine.
Next week i will try to verify on frrecad mod (drawing dimensioning) in my work pc, in my old laptop it don't works well.

**Comment by poeschlr** [comment]
Did you intent to push a change that goes with your comment?

**Comment by Misca1234** [comment]
Should there not be a ground plane as well, like this ?

bild

**Comment by jneiva08** [comment]
I have small experience is patch/ceramic antennas.
The few testes i did with iridium antenna, i did have better better if the ground plane/area was bigger. Normally the antenna recommend the best area.
In the following image image can see the top layer. Only call attention for arround the solder pin.
top
If you want can post two pcb's using this two gps antennas.

**Comment by Shackmeister** [comment]
I believe the ground plane shouldn't be part of the footprint.

**Comment by Misca1234** [comment]
@Shackmeister 
According to page 13 they recommend a ground plane, on both sides of the PCB, I guess the images on bottom of page shows top and bottom side

**Comment by Misca1234** [comment]
@jneiva08 
Shackmeister is correct, neither the ground plane or the suggested pin 2 should be included in the foot print, it is up to the user to define the ground plane later.
So remove the copper around the pin

**Comment by jneiva08** [comment]
@Misca1234 
The ground place and pin 2 was never added on the footprint.
I'm thinking changing pin 1 to be only B.Cu with B.Paste and B.Mask. i don't know how should mark the limit of clearance, probably with two circles in F.SilkS and B.SilkS.
What is your opinion?

**Comment by Misca1234** [comment]
To follow Shackmeisters recommendation it would mean not to even include the copper plane, just the "pin"

**Comment by chschlue** [comment]
@jneiva08 reopen if you're still on this.

**Pull request closed without merging**
