### PR TITLE
Fixup 3 dmodel path

### PR DESCRIPTION
**Pull request by Misca1234**
Fixup of the 3D model paths and missing 3D model tag

Relay_DPDT_AXICOM_IMSeries_JLeg
Added ${KISYS3DMOD}/

Texas_SWRA117D_2.4GHz_Left
Texas_SWRA117D_2.4GHz_Right
Added 3D model tag

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Not sure if we should fix the rest as well

**Comment by evanshultz** [comment]
https://github.com/KiCad/kicad-footprints/pull/1008/commits/8fafdc1d11c4086b1cbed08b5c94d44afd6fa97f looks fine, but there are a lot of other changes here. Perhaps you can merge your branch with upstream and then only submit that one commit?

**Comment by Misca1234** [comment]
Hmm, I thought I did that just before I createdthis branch due to the Lair Technology incident

**Comment by Misca1234** [comment]
$ git merge master
Already up to date.

**Comment by Misca1234** [comment]
My knowledge about git is not that deep

**Comment by Shackmeister** [comment]
@Misca1234 I believe it's ok not to have any 3D reference on virtual footprints which doesn't doesnt make any sense to have a model on

**Comment by evanshultz** [comment]
Should these antenna to be virtual? Perhaps having a 3D model is nice so the user can see the antenna in the 3D viewer? Just thinking out loud...

**Comment by evanshultz** [comment]
Aaaahhhh. I was under the impression that virtual components didn't get a 3D model. It just means there's not a physical component that goes on top of the footprint. So the copper of the antenna still shows up and that's all I was thinking about. Thanks.

Yes, indeed I think they should be custom pads. Not necessarily in this PR but put it on the list...

**Pull request merged**
