### PR TITLE
LTC MSOP-16 with 1-ExposedPad (non-thermal-vias and thermal-vias versions)

### PR DESCRIPTION
**Pull request by daab4848**
**Pull Request for branch_daab_footprints** 
-----------------------------------------------------------------
**Branch Name**: branch_daab_footprints                                            
**Branch Author**: David Abillar                                           
**Last Modified by**: David Abillar                                   
**Date**: 03-06-2018   
**Current Branch Revision**: 0.01

**Push Details** 
-----------------------------------------------------------------
**Footprint Name**: LTC_MSOP-16-1EP_3x4mm_P0.5mm
**Current Footprint Library**: Package_SO
**Associated Symbols**: (none currently, but can be for LT8610, LT8610AC, LT8610AC-1 symbols)
**Part Manufacturer**: Analog Devices/ Linear Technology
**Datasheet(s) URL(s)**: 
http://cds.linear.com/docs/en/datasheet/8610fa.pdf 
http://cds.linear.com/docs/en/datasheet/8610acfa.pdf

**Footprint Screenshot**:
image

**Footprint Screenshot (closeup to component):
image

image

######################################################################  
     
**Footprint Name**: LTC_MSOP-16-1EP_3x4mm_P0.5mm_ThermalVias
**Current Footprint Library**: Package_SO
**Associated Symbols**:  LT8610, LT8610AC, LT8610AC-1
**Part Manufacturer**: Analog Devices/ Linear Technology
**Datasheet(s) URL(s)**: 
http://cds.linear.com/docs/en/datasheet/8610fa.pdf 
http://cds.linear.com/docs/en/datasheet/8610acfa.pdf

**Footprint Screenshot**:
image

**Footprint Screenshot (closeup to component):
image

image

**Footprint Screenshot (closeup of exposed pad):
image

image

**Additional Comments** 
-----------------------------------------------------------------
- Associated symbols can be found in **Regulator_Switching** symbol library 
- Please double check the _ThermalVias version of the footprint. There are six thermal vias and have made necessary adjustments to paste layer to avoid intersection with drill hole of vias.
- Thank you for the thorough review(s)!

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up the integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x ] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
With a quick check i found some problems:
The large pad 17 on the top copper layer has paste enabled. (This negates your smaller paste pads)
The THT pads have mask enabled.
Why do you have two pin 1 markers on silk?
The silk outline would hint at a much larger package then the outline on the fab layer. (Which of them is correct?)
If the fab outline is correct, then the courtyard area is way too large. (clearance is calculated relative to the part body and pads. As the fab outline represents the part body this means the clearance is calculated relative to the fab outline and pads.)
The fab outline should use a line width of 0.1mm
Add a EP size specifier to the footprint name as is done with other such footprints.

The footprint seems extremly similar to the already present `MSOP-16-1EP_3x4mm_P0.5mm_EP1.65x2.85mm` footprints. Could you highlight the differences between your footprint and the old one.

**Comment by daab4848** [comment]
**These edits have only been done on the _ThermalVias version of the footprint. Will include these edits to the non_ThermalVias version after this footprint has been fully fixed.**
> The large pad 17 on the top copper layer has paste enabled. (This negates your smaller paste pads)

-Fixed with latest commit to branch


> The THT pads have mask enabled.

-Originally the thermal vias didn't have mask, but the Travis check scripts gave me an error for missing *.Mask layer on them.
 I'll remove the masks and if Travis check scripts gives me an error about it I will screenshot for further debugging.

 
> Why do you have two pin 1 markers on silk?

-Removed pin 1 dot-designator due to redudancy


> The silk outline would hint at a much larger package then the outline on the fab layer. (Which of them is correct?)
> If the fab outline is correct, then the courtyard area is way too large. (clearance is calculated relative to the part body and pads. 
> As the fab outline represents the part body this means the clearance is calculated relative to the fab outline and pads.)
> The fab outline should use a line width of 0.1mm

-Fixed silk outline to enclose the package more snuggly. This fix accommodate the max length and width of package to ensure the silk outline is still visible after part assembly. 
-Fixed fab outline to be nominal dimensions of package and set line width to 0.1mm.


> Add a EP size specifier to the footprint name as is done with other such footprints.

-Included EP size specifier in footprint name (both on footprint and actual footprint-file-name).
-**Will change the footprint names for symbols using this package after this footprint as been fully fixed.**


> The footprint seems extremly similar to the already present MSOP-16-1EP_3x4mm_P0.5mm_EP1.65x2.85mm footprints. Could you highlight the differences between your footprint and the old one.

Below refers to features of the LTC_MSOP-16-1EP_3x4mm_P0.5mm_EP2.15x3.26mm_ThermalVias footprint that differ from the MSOP-16-1EP_3x4mm_P0.5mm_EP1.65x2.85mm footprints.
-Pads (including thermal) have been sized to the recommended solder pad layout for the MSE (MSOP-16 with Exposed Die Pad) package as seen in the datasheet. 

-In particular, the pin pads have been shortened from 1.4mm to 1.0mm and distance from left-side-pads to right-side-pads (measured from sides closest to middle of package) has been slgihtly extended from 3.0mm to 3.2mm. (these have been fixed with the latest commit to branch)

-Six thermal vias instead of three, drill size increased from 0.25mm to 0.3mm, and thermal pad dimensions increased from 1.65x2.85mm to 2.15x3.26mm to fulfill F4.4 #3 (which is >=0.5mm clearance from via edge to thermal pad edge).

Since the set of parts (at least from LTC) that use this package can output currents in the range of mA to A, the slight increase in drill size, increased number of vias, and increased dimensions of thermal pad were necessary to accommodate these higher-power parts.


**Footprint (thermalvias) with most recent edits**
image

image

**Comment by poeschlr** [comment]
You forgot to include the ep size specifier in the non thermal via version.
Otherwise this contribution would be ready to be merged.

**Comment by daab4848** [comment]
@poeschlr 
Due to some unfortunate circumstances, I had to reinstall KiCad on my computer and I loss the footprint files I was working on (so I can no longer make the necessary changes to merge this pull request.) However, I made another pull request #499 for the MSOP 16 footprints under a slightly different name. Apologies for any confusion and/or inconveniences.

**Comment by Ratfink** [comment]
@daab4848 The files for this PR are all on GitHub.  You can get them back as described by cloning this repository, then running (assuming the KiCad/kicad-footprints remote is called `origin`):

```
git fetch origin pull/415/head:pr-415
git checkout pr-415
```

**Comment by daab4848** [comment]
@Ratfink Under the assumption that KiCad/kicad-footprints remote is called origin, I get the following error:
image

I did, however, delete the forked and cloned footprint repository associated with this PR some few weeks ago without me realizing the consequences of doing so (yikes!) - perhaps that is why I am seeing this at the top of my PR and why I am getting the error above too. Any thoughts?

image

**Comment by daab4848** [comment]
@Ratfink Hence why I started PR #499

**Comment by Ratfink** [comment]
That must be the wrong remote then, because on my end, it works fine:

```
$ git remote
origin
upstream
$ git remote get-url upstream
https://github.com/KiCad/kicad-footprints.git
$ git fetch upstream pull/415/head:pr-415
From https://github.com/KiCad/kicad-footprints
 * [new ref]           refs/pull/415/head -> pr-415
$ git checkout pr-415
Switched to branch 'pr-415'
$ 
```

But if you'd rather continue this work in #499, we can close this PR.

**Comment by daab4848** [comment]
@Ratfink I think it'd be best to continue this work in #499.

**Comment by Ratfink** [comment]
Alrighty then!

**Pull request closed without merging**
