### PR TITLE
Add QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm

### PR DESCRIPTION
**Pull request by fauxpark**
Required for https://github.com/KiCad/kicad-symbols/pull/1898.
Generator PR: https://github.com/pointhi/kicad-footprint-generator/pull/365

Datasheet: http://www.issi.com/WW/pdf/31FL3731.pdf#page=21

fp

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
see comments on the script pull request

**Comment by fauxpark** [comment]
Updated the script, no changes to the generated footprint other than the timestamp.

**Comment by poeschlr** [comment]
Seems unlikely as the body size tolerance should influence the pad sizes.

**Comment by fauxpark** [comment]
Double checked, definitely no changes.

```diff
diff --git a/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm.kicad_mod b/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm.kicad_mod
index 5325d9a4..23133bba 100644
--- a/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm.kicad_mod
+++ b/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm.kicad_mod
@@ -1,4 +1,4 @@
-(module QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm (layer F.Cu) (tedit 5CF28F5D)
+(module QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm (layer F.Cu) (tedit 5CF3F0C3)
   (descr "QFN, 28 Pin (http://www.issi.com/WW/pdf/31FL3731.pdf#page=21), generated with kicad-footprint-generator ipc_noLead_generator.py")
   (tags "QFN NoLead")
   (attr smd)
diff --git a/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm_ThermalVias.kicad_mod b/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm_ThermalVias.kicad_mod
index ef7325ea..a5bcb487 100644
--- a/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm_ThermalVias.kicad_mod
+++ b/Package_DFN_QFN.pretty/QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm_ThermalVias.kicad_mod
@@ -1,4 +1,4 @@
-(module QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm_ThermalVias (layer F.Cu) (tedit 5CF28F5D)
+(module QFN-28-1EP_4x4mm_P0.4mm_EP2.3x2.3mm_ThermalVias (layer F.Cu) (tedit 5CF3F0C3)
   (descr "QFN, 28 Pin (http://www.issi.com/WW/pdf/31FL3731.pdf#page=21), generated with kicad-footprint-generator ipc_noLead_generator.py")
   (tags "QFN NoLead")
   (attr smd)
```

**Comment by poeschlr** [comment]
Ok well then it seems to vanish in the IPC required rounding.

**Pull request merged**
