### PR TITLE
Adding JK0654219NL

### PR DESCRIPTION
**Pull request by ki5libs**
Adding JK0654219NL
[Datasheet](https://media.digikey.com/pdf/Data%20Sheets/Pulse%20PDFs/JK%20Series.pdf#page=2)

JK0654219NL_footprint

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi. Thanks for your contribution.

- [ ] Please, provide a description in the "Description" field. Currently, there is a datasheet link only. If available, replace the datasheet link from DigiKey by the link provided by the manufacturer.

image

- [ ] The Silk lines are too near to the exposed copper of the pads. Clearance between silkscreen and exposed copper elements is recommended to be 0.2mm (at least), as per KLC F5.1 (http://kicad-pcb.org/libraries/klc/F5.1/). 
image

- [ ] I suggest keeping the Fab outline continuous
image

- [ ] Pin-1 indicator is missing on the Fab layer.
image
I recommend something like this


- [ ] There are a few wrong dimensions. Take a look at the dimensioned drawing bellow. (Blue dimension lines are in inches and pink in mm. Red text means a bad dimension).
image

**Comment by ki5libs** [comment]
Hi @gmsotavio 
This footprint going to be used with this [symbol](https://github.com/KiCad/kicad-symbols/pull/2228)
- description added, couldn't find this part on the manufacturer website, so old link left;
- silk and fab lines are corrected;
- pin-1 indicator added on Fab layer;
- dimensions are fixed

**Comment by gmsotavio** [comment]
Hi @ki5libs,

Thanks for addressing all my suggestions.

- [ ] One incorrect dimension remains. Take a look at the dimensioned drawing bellow.

image

**Comment by ki5libs** [comment]
Hi @gmsotavio 

looks like it happened because I use metric dimensions. It should be OK now. Thanks for review.

**Comment by gmsotavio** [comment]
100%

image

**Pull request merged**
