### PR TITLE
Wuerth 7499151120 dual RJ45 jack

### PR DESCRIPTION
**Pull request by evanshultz**
As mentioned at https://github.com/KiCad/kicad-symbols/issues/301.

In addition to adding this footprint, the other two RJ45 jacks have no manufacturer information I can see. Should I remove them? Can anyone identify the vendor and MPN?

Notes:
- I chose pin names that follow the datasheet, using 1-14 and appending D or U for DOWN or UP.
- The housing pins are named SH, in accordance with out latest plan (I believe).
- Pad sizes chosen according to IPC Level B
- The F.Fab footprint name extends past the footprint outline, but will shrink once it's packaged to match the shorter symbol name (which doesn't have "_Horizontal" in it).

Datasheet: http://katalog.we-online.de/pbs/datasheet/7499151120.pdf

Image:
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
I also added the datasheet link to the Amphenol RJ45 jack. That footprint has wrong 3D model params, and I don't find a repo for RJ connectors, so shall I correct the 3D model params now?

Also note the question above about deleting unknown RJ45 footprints.

**Comment by Shackmeister** [comment]
I don't recognize the unknown connectors, and agree they should be removed. I don't believe in generic USB, HDMI, RJ45 etc connectors. There is currently no 3D model, so yes the 3D parameters should be corrected.

Regarding the footprint itself, Ill try to have a look tomorrow

**Comment by evanshultz** [comment]
I corrected the 3D params for the RJHSE538X footprint.

Here is the dimensioned drawing in FreeCAD for my Wuerth jack:
image

It matches the datasheet:
image

@poeschlr 
Your instructions are awesome! Surely there are many people to thank, but I appreciate you pulling it all together. I haven't figured out how to offset (slide) the dimension for readability, but I'll play with it more later and figure it out. Thank you!

Also, I assume you agree to remove the unknown RJ45 footprints? I can do that quickly before this is merged if all three of us agree.

**Comment by evanshultz** [comment]
@Shackmeister @poeschlr 
Are either of you able to take a look at this footprint? And please confirm, Rene, if you agree with us that generic RJ45 jacks should go away.

**Comment by poeschlr** [comment]
Jup generic footprints for such specific parts make no sense. They give beginners a false sense of security, whereas a more professional user will never touch such footprints. (As they most likely have been already burned by something similar.)

**Comment by evanshultz** [comment]
Alright, I deleted the generic RJ footprints. That just leaves approving the new Wuerth footprint.

**Comment by evanshultz** [comment]
@Shackmeister 
Are you able to take a look at this footprint?

**Comment by Shackmeister** [comment]
Sure thing, Ill take a look tomorrow :) (which is later today since we just passed midnight here in Denmark) sleep tight

**Comment by evanshultz** [comment]
@Shackmeister Fixed branch conflict that appeared. Can you check this out?

**Comment by evanshultz** [comment]
@Shackmeister 
Are you able to get to this?

**Comment by Shackmeister** [comment]
Hi @evanshultz sorry for the delay, Im  buried neck deep in work.

if the courtyard could be made a bit closer I believe it's good to go :) (see https://github.com/KiCad/kicad-footprints/pull/389)

**Comment by evanshultz** [comment]
You're asking for the courtyard to be contoured around the part body? Is that required? I don't see that in KLC anywhere, though I do see it in IPC docs and some of our footprints. If this is a requirement for merging footprints I would like to see it in KLC.

Based on the simpler method Rene suggested, here is what I've implemented:
image

**Comment by Shackmeister** [comment]
Thanks :)

I dont think the courtyard is required, but I prefer it for my footprints

**Comment by thomasonw** [comment]
@evanshultz   Hello.  The old RJ45 default connector was a match for FCI 54602-908LF,  can we get it added back in?

**Comment by evanshultz** [comment]
Of course. As you can see above generic footprints were removed. But if it can be a specific one then certainly it can live again! I'll check this out later today.

**Pull request merged**
