### PR TITLE
fixed some rules violations

### PR DESCRIPTION
**Pull request by gggfred**
Fixed rule violations on the next components:

-  L_Neosid_Ms42 (F5.4)
-  L_Pulse_PA4320 (F5.3)
-  L_Wuerth_WE-PD-Typ-LS (F5.4)
-  L_Wuerth_WE-PD-Typ-M-Typ-S (F5.4)
-  L_Wuerth_WE-PD-Typ-M-Typ-S_Handsoldering (F5.4)

Translated descriptions, added datasheets

-  Inductor_SMD.pretty/L_Neosid_MicroCoil_Ms36-L.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms42.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms50.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms50T.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms85.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms85T.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms95.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms95T.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_Ms95a.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-NE127.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-NE127_HandSoldering.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-NE150.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-NE95H.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-PIC0512H.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-PIC0602H.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-PIC0612H.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SM-PIC1004H.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SMS-ME3010.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SMS-ME3015.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SMs42.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SMs50.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SMs85.kicad_mod
-  Inductor_SMD.pretty/L_Neosid_SMs95_SMs95p.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-DD-Typ-L-Typ-XL-Typ-XXL.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-DD-Typ-M-Typ-S.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD-Typ-7345.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD-Typ-LS.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD-Typ-LS_Handsoldering.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD-Typ-M-Typ-S.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD-Typ-M-Typ-S_Handsoldering.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD2-Typ-L.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD2-Typ-MS.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD2-Typ-XL.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PD4-Typ-X.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PDF.kicad_mod
-  Inductor_SMD.pretty/L_Wuerth_WE-PDF_Handsoldering.kicad_mod

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Please list what you fixed. That will help us know what you planned to do.

Also, if a datasheet is needed for reference please include it as well.

**Comment by gggfred** [comment]
> 
> 
> Please list what you fixed. That will help us know what you planned to do.
> 
> Also, if a datasheet is needed for reference please include it as well.

Dear @evanshultz, I have updated the comment with the changes

**Comment by evanshultz** [comment]
Thanks! :)

While I'm happy to merge these fixes are they are, some of these footprints could also use a little more work. The Neosid and Wuerth footprints should have all words in the description changed to English and add datasheet URL. Let me know if you'd like me to merge right away or not.

**Comment by gggfred** [comment]
> 
> 
> Thanks! :)
> 
> While I'm happy to merge these fixes are they are, some of these footprints could also use a little more work. The Neosid and Wuerth footprints should have all words in the description changed to English and add datasheet URL. Let me know if you'd like me to merge right away or not.

Sure!! I'll tell you, as soon as I complete the changes

**Comment by gggfred** [comment]
@evanshultz I changed the parts listed, translating some words of description, changing some descriptions, and fixing some parts that not accomplish with the component sizes.

**Comment by evanshultz** [comment]
Wow! Thank you!

Let me remind you that this is all optional. We rely on the community to grow and update our library, so you don't have to do any of this. But it's a great and welcome improvement!

So if you want to continue, there are just a couple remaining things:
- L_Neosid_MicroCoil_Ms36-L, L_Neosid_Ms50T, L_Neosid_Ms85T, L_Neosid_Ms95T, and L_Neosid_Ms95a are missing a datasheet. If there is no PDF datasheet, you can link to the product page URL like https://neosid.de/en/products/inductors/rod-core-chokes/smd-rod-core-chokes/52026/ms-36/7-h.
- L_Wuerth_WE-DD-Typ-M-Typ-S fixes look good, but can you add https://katalog.we-online.de/pbs/datasheet/744877001.pdf to the description since this footprint covers both type M and S?
- L_Wuerth_WE-PD2-Typ-MS fixes look good.
- L_Wuerth_WE-PD2-Typ-XL needs the fab lines changed back to 0.1mm but the outline looks more correct. You can also cut off the angle decimals after the period. That's optional.
- L_Wuerth_WE-PD4-Typ-X datasheet appears to be https://katalog.we-online.de/pbs/datasheet/74458001.pdf.
- L_Wuerth_WE-PDF appears to be at https://katalog.we-online.de/en/pbs/WE-PDF.

If you're done with this, let me know and I'll merge now.

I should have looked at this earlier, but https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Inductors has scripts for several inductor footprints. It's great to get these fixes in the library, but always best to fix the script where possible. In this case, it doesn't look like any of these footprints were scripted so all is good!

**Comment by gggfred** [comment]
> 
> 
> Wow! Thank you!
> 
> Let me remind you that this is all optional. We rely on the community to grow and update our library, so you don't have to do any of this. But it's a great and welcome improvement!
> 
> So if you want to continue, there are just a couple remaining things:
> 
>     * L_Neosid_MicroCoil_Ms36-L, L_Neosid_Ms50T, L_Neosid_Ms85T, L_Neosid_Ms95T, and L_Neosid_Ms95a are missing a datasheet. If there is no PDF datasheet, you can link to the product page URL like https://neosid.de/en/products/inductors/rod-core-chokes/smd-rod-core-chokes/52026/ms-36/7-h.
> 
>     * L_Wuerth_WE-DD-Typ-M-Typ-S fixes look good, but can you add https://katalog.we-online.de/pbs/datasheet/744877001.pdf to the description since this footprint covers both type M and S?
> 
>     * L_Wuerth_WE-PD2-Typ-MS fixes look good.
> 
>     * L_Wuerth_WE-PD2-Typ-XL needs the fab lines changed back to 0.1mm but the outline looks more correct. You can also cut off the angle decimals after the period. That's optional.
> 
>     * L_Wuerth_WE-PD4-Typ-X datasheet appears to be https://katalog.we-online.de/pbs/datasheet/74458001.pdf.
> 
>     * L_Wuerth_WE-PDF appears to be at https://katalog.we-online.de/en/pbs/WE-PDF.
> 
> 
> If you're done with this, let me know and I'll merge now.
> 
> I should have looked at this earlier, but https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Inductors has scripts for several inductor footprints. It's great to get these fixes in the library, but always best to fix the script where possible. In this case, it doesn't look like any of these footprints were scripted so all is good!

Don't worry! I want to contribute and I'm glad of can do it.

**Comment by gggfred** [comment]
@evanshultz please check again and let me know if all right

**Comment by evanshultz** [comment]
Looks great! Thank you!

**Pull request merged**
