### PR TITLE
Add reflexcouplers

### PR DESCRIPTION
**Pull request by jkriege2**
- several footprints for https://github.com/KiCad/kicad-symbols/pull/127
- 3D models: https://github.com/KiCad/kicad-packages3D-source/pull/74 and https://github.com/KiCad/kicad-packages3D/pull/208

2018-01-03 12_50_58-3d viewer
2018-01-03 12_51_14-3d viewer
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by pointhi** [comment]
simple question: is the cutout big enough to be practical producable (because in production there would be no straight 90° edge, but instead some rounded edge due to the milling cutter)

**Comment by jkriege2** [comment]
Hmmm ... do you knwo what cutter-diameters are typically used?

**Comment by jkriege2** [comment]
also: Would you know whether they will cut ALONG the line (center of cutter on drawn line), or until the line (cutter outer edge touches drawn line-center)?

**Comment by pointhi** [comment]
to my knowledge, they cut until the line (otherwise you would always need to know the tool diameter).

At the moment, I have no real numbers about the production tolerances to expect.

**Comment by jkriege2** [comment]
Hi I found one manufacturer that uses 0.8mm tools for cutting ... I increased the cutout-size slightly, so the cutout will be big enough for 0.8mm and also above:

2018-01-03 13_57_33-footprint editor no active library

**Comment by jkriege2** [comment]
@pointhi Better this way? Would you have time to merge this if there are no other problems?

Thanks,
JAN

**Comment by pointhi** [comment]
at the moment, better a bit to big than to small.

@SchrodingersGat we should specify some rules in the future what pcb-manufacture-capabilites the library assumes.

**Comment by SchrodingersGat** [comment]
AFAIK most fab houses operate on the assumption that the line you draw is the boundary of the cut line, not the center. i.e. you specify the *final product* and it is up to the fab house to decide how to adjust for tool diameter, etc.

(This is how I have operated with multiple fabs for many many projects. In my experience it is rare that you have to specify specific tool info).

**Comment by jkriege2** [comment]
OK, then the symbols should be fine. Even if made with a 1mm cutting tool, the reflex coupler will fit in the cutout .... so can this be merged? Models and Symbols have already been merged!

**Pull request merged**
