### PR TITLE
added Alps EC11 and EC12 rotary encoder footprints

### PR DESCRIPTION
**Pull request by jkriege2**
- made to match generic symbols from device.lib (see also https://github.com/KiCad/kicad-symbols/pull/206)
2018-01-21 17_59_24-symbol library editor - device d__kicad_kicad-symbols_device lib
- variants with and without switch
- for now 20mm shaft lengtrh variants (given height for future 3D models, variants with other shaft lengths can come in future)
- variants with circular holes for mounting-pins
- mounting pins are assigned pin0 to allow connecting them to a shield explicitly with symbols from https://github.com/KiCad/kicad-symbols/pull/206
- datasheets:
  - http://www.alps.com/prod/info/E/HTML/Encoder/Incremental/EC11/EC11E15204A3.html
  - http://www.alps.com/prod/info/E/HTML/Encoder/Incremental/EC12E/EC12E1240405.html 
  - http://cdn-reichelt.de/documents/datenblatt/F100/402097STEC12E08.PDF
- cross marks axis center on F.Fab and F.Silks

2018-01-21 21_39_36-pcbnew d__kicad_devproject_devproject kicad_pcb
2018-01-21 21_39_24-pcbnew d__kicad_devproject_devproject kicad_pcb
2018-01-21 21_39_48-3d viewer

## check against 3D models from ALPS: EC11
These images show that the ALPS models fit the footprints:
2018-01-22 19_41_26-3d viewer
2018-01-22 19_41_12-3d viewer
2018-01-22 19_40_20-3d viewer
2018-01-22 19_39_53-3d viewer

## check against 3D models from ALPS: EC12
These images show that the ALPS models fit the footprints:
2018-01-22 19_46_43-3d viewer
2018-01-22 19_45_52-3d viewer
2018-01-22 19_45_43-3d viewer

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Take a closer look at the silk outlines. Some of them are "behind" the fab outline instead of being outside of it.
From the 3d models it looks like the pads that currently have number 0 are there to increase the mechanical strength. So i think these should get pin number "MP" as decided in issue https://github.com/KiCad/kicad-footprints/issues/117

The landing patterns look ok.

**Comment by jkriege2** [comment]
I fixed the silkscreen-problems (only found two in the EC11E's).

ABout the pin-naming, @evanshultz raised comparable question at the PR for the symbols: https://github.com/KiCad/kicad-symbols/pull/220 ... I think we should discuss that there and I will change both PRs, depending on the outcome of that discussion.

**Comment by jkriege2** [comment]
rename pin 0 to pin MP as explained over in https://github.com/KiCad/kicad-symbols/pull/220

**Comment by jkriege2** [comment]
@poeschlr @evanshultz Since the symbols have been merged with https://github.com/KiCad/kicad-symbols/pull/220 ... Could I get a review for these?

Thanks,
JAN

**Comment by poeschlr** [comment]
Sorry this has been forgotten for so long. Looks good now. Thanks

**Pull request merged**
