### PR TITLE
Add ADI LFCSP-72 footprints

### PR DESCRIPTION
**Pull request by evanshultz**
http://www.analog.com/media/en/technical-documentation/data-sheets/ADAU1452_1451_1450.pdf

image
image

@poeschlr 
Could you please add the entry at https://github.com/KiCad/kicad-symbols/pull/825#issuecomment-414146988 to your outstanding PR at https://github.com/pointhi/kicad-footprint-generator/pull/149? (I didn't put it here again to keep one source of truth.)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
@poeschlr 
ADI calls this a LFCSP, so I renamed the 3D model repo as such. I don't see an easy or reasonable way to incorporate this into the script (could be kludgy based on text in `device_type`), so I'm assuming it's fine the way it is and to keep the nomenclature ADI uses.

**Comment by poeschlr** [comment]
For special namings you have two options in my script. One is the device type (I should have called it symbol_prefix or something similar) Have a look at the WSON yaml file to see what i mean.

The other is a custom format string (As used by the texas instrument footprints)

**Comment by evanshultz** [comment]
Thanks Rene!

I don't see a way to set just the 3D model folder inside the script, though. There appears to be no override for the `category` variable in the script. Right? Adding `category: 'CSP'` to the YAML file has no effect on the 3D model path (still `DFN_QFN`).

Is there anything to do before merging this footprint, then?

**Comment by poeschlr** [comment]
As i said look at the WSON size definition. You can add a library parameter.

**Comment by evanshultz** [comment]
I think this is good to go.

If you would add it to your PR, the entry is this:
```
LFCSP-72-1EP_10x10mm_Pitch0.5mm_EP5.3x5.3mm_ThermalVias:
  device_type: 'LFCSP'
  library: Package_CSP
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://www.analog.com/media/en/technical-documentation/data-sheets/ADAU1452_1451_1450.pdf'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  # custom_name_format:
  body_size_x_min: 9.9
  body_size_x: 10.0
  body_size_x_max: 10.1
  body_size_y_min: 9.9
  body_size_y: 10.0
  body_size_y_max: 10.1
  lead_width_min: 0.18
  lead_width_max: 0.3
  lead_len_min: 0.3
  lead_len_max: 0.5

  EP_size_x_min: 5.15
  EP_size_x: 5.3
  EP_size_x_max: 5.45
  EP_size_y_min: 5.15
  EP_size_y: 5.3
  EP_size_y_max: 5.45
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [3, 3]
  #heel_reduction: 0.1 #for relatively large EP pads (increase clearance)

  thermal_vias:
    count: [4, 4]
    drill: 0.3
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    # EP_num_paste_pads: [2, 2]
    #paste_between_vias: 1
    #paste_rings_outside: 1
    EP_paste_coverage: 0.65
    #grid: [1, 1]
    # bottom_pad_size:
    # paste_avoid_via: False

  pitch: 0.5
  num_pins_x: 18
  num_pins_y: 18
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'
```

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
