### PR TITLE
Added ISL3298ExRTZ-T and ISL32956ExHZ

### PR DESCRIPTION
**Pull request by UsairemAlamgeer**
Footprints along with 3D models have been added for **ISL3298E** and **ISL3295E RTC485** ICs.

The footprints in the current Libraries Lacked F.Fab layer, 3D Model and detailed name with dimensions.

**Description:** RS-422/RS-485 Interface IC 6LD SNG RS-485 DRVR FAST SPD IND

**Mounting Style:** SMD/SMT

**Package Casing:** SOT-23-6

 The packages included are **SOT-23-3_B2.8x2.9x1.45mm_P0.95mm** and **TDFN-8_B2.0x3.0x0.75mm_P0.5** respectively.

**Datasheet:** https://eu.mouser.com/datasheet/2/698/isl3295e-98e-1697114.pdf

Link to Repo Issue: jbots/kicad-jb-public#1

image
image

### CODE REVIEW

**Review by chschlue — CHANGES_REQUESTED** [review]
Welcome and thanks for your first contribution. There are, however, some issues with it:
- [ ] device-specific subdirs for standard packages are not acceptable
- [ ] TSOT-23-6 is already available
- [ ] DFN must be scripted using the generator at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON
- [ ] footprints must adhere to our naming convention

**Comment by UsairemAlamgeer** [comment]
> Welcome and thanks for your first contribution. There are, however, some issues with it:
> 
> * [x]  device-specific subdirs for standard packages are not acceptable
> * [x]  TSOT-23-6 is already available
> * [x]  DFN must be scripted using the generator at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON
> * [x]  footprints must adhere to our naming convention

**Comment by UsairemAlamgeer** [comment]
Changes have been made.

**Review by chschlue — CHANGES_REQUESTED** [review]
Please actually fix this submission instead of just checking the boxes.

- [ ] we already have TSOT-23-6. A manufacturer-specific version can be added if there is a compelling reason, like impedance control for example, which I fail to see at this point. Please explain why you think this addition is necessary.
- [ ] TDFN must be scripted, as I already said, as long as there is no compelling reason to follow the manufacturer footprint over IPC recommendations (see above)
- [ ] both footprints must adhere to our naming convention

I'll be blunt: Both submissions could hardly be any more broken (orientation is wrong, body outline is wrong, courtyard is inside the body, silkscreen is beneath the body, and those are just the most obvious errors).
Please read the [library conventions](https://kicad-pcb.org/libraries/klc/) and perhaps take a look at some examples of correct footprints before requesting a review.
In fact, please don't request a review at all. Each submission will be reviewed when its time has come.

**Comment by UsairemAlamgeer** [comment]
Thanks for the important feedback Sir.

I have taken back the footprints, and would keep in mind your points next time. 

Thanks a lot.

**Pull request closed without merging**
