### PR TITLE
Mountyrox: Bugfix in TO-92S_Wide footprint 

### PR DESCRIPTION
**Pull request by MountyRox**
Bugfix: old footprint had incorrect courtyart (not a closed shape) in file "Package_TO_SOT_THT.pretty/TO-92S_Wide.kicad_mod"

Changes to be committed:
	modified:   Package_TO_SOT_THT.pretty/TO-92S_Wide.kicad_mod

TO-92S_Wide

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x ] Provide a URL to a datasheet for the footprint(s) you are contributing  **(already included)**
- [x ] An example screenshot image is very helpful 
- [x ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate  **(already included)**
- [ x] Check the output of the Travis automated check scripts - fix any errors as required  **(I checked the foorprint with Pcbnew)**
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by MountyRox** [comment]
Hi

I'm sorry for the incomplete fix. I just corrected the CrtYd to get no more errors in Pcbnew editor. Of course I can fix the other parts. 

Since I am new to GitHub I am not sure how I can perform the the Travis CI check to avoid such errors in the future. Could you give me some hints how to do it.

What are the steps after fixing the footprint? Must I create a complete new pull request or can I update the footprint using the pull request #2392? If yes, how can it be done? 

Many thanks. 
Joerg

**Comment by chschlue** [comment]
> Since I am new to GitHub I am not sure how I can perform the the Travis CI check to avoid such errors in the future. Could you give me some hints how to do it.

CI checks run automatically as soon as a commit is pushed. You can see the results by clicking the `Details` link next to `Travis CI build` at the bottom of this page. Alternatively, you can download the scripts from https://github.com/KiCad/kicad-library-utils and run the checks locally.

> What are the steps after fixing the footprint? Must I create a complete new pull request or can I update the footprint using the pull request #2392? If yes, how can it be done?

You can just push the commit(s) fixing the remaining issues to update this PR.

Final hint: Better not create PRs from your master branch, you will shoot yourself in the foot at some point.
If you just keep your master branch in sync with kicad-footprints and branch off of it for fixes and additions, you'll be able to keep several PRs open in parallel (the review process for each one can take some time).

**Comment by MountyRox** [comment]
Ok, I will download the kicad-library-utils and try to run the script locally. Hope I am able to get it working.

And thanks for the hint. I wondered why it is necessary to work on a new branch. Now its clear.

**Comment by MountyRox** [comment]
When checking the above mentioned footprint, I found a lot more footprints in the Package_TO_SOT_THT folder to be invalid. Should I try to fix them or are there other things to do with higher priority?

**Comment by chschlue** [comment]
Oh, there's always plenty to do, but you have to start somewhere, right?

You're welcome to fix other TO_SOT_THT footprints, of course.
If there's more to fix than open courtyard polygons and such, consider splitting them into several PRs so they can get reviewed (and merged) one by one as reviewers can manage.

**Comment by chschlue** [comment]
Note #2396

**Comment by evanshultz** [comment]
@MountyRox 
I didn't search for this PR before I submitted a PR that fixed this along with several other things about TO-92 footprints. Since the issue you've mentioned is corrected I'm going to close this PR. You did find and fix a problem which is great and we really appreciate it. In your first comment you expressed willingness to help in a variety of ways and so I hope you will continue to do so. Thanks again!

**Pull request closed without merging**
