### PR TITLE
QFN-32-1EP for NXP LCP111x (correct ep size)

### PR DESCRIPTION
**Pull request by poeschlr**
original ep size was 5.46mm. Correct size is 4.7mm nominal (or at most
4.85mm)

datasheet https://www.nxp.com/docs/en/data-sheet/LPC111X.pdf (page 108)

Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/149
Symbol PR: https://github.com/KiCad/kicad-symbols/pull/768

Parameters:
``` yaml
QFN-32-1EP_7x7mm_P0.65mm_EP4.7x4.7mm:
  device_type: 'QFN'
  size_source: 'https://www.nxp.com/docs/en/data-sheet/LPC111X.pdf (Page 108)'
  ipc_class: 'qfn' # 'qfn_pull_back'
  body_size_x:
    nominal: 7
    tolerance: 0.1
  body_size_y:
    nominal: 7
    tolerance: 0.1
  lead_width:
    minimum: 0.23
    maximum: 0.35
  lead_len:
    minimum: 0.45
    maximum: 0.75

  EP_size_x:
    nominal: 4.7
    minimum: 4.55
    maximum: 4.85
  EP_size_y:
    nominal: 4.7
    minimum: 4.55
    maximum: 4.85
  EP_num_paste_pads: [4, 4]

  thermal_vias:
    count: [4, 4]
    drill: 0.2
    paste_via_clearance: 0.1
    paste_between_vias: 1
    paste_rings_outside: 1
    grid: [1.05, 1.05]

  pitch: 0.65
  num_pins_x: 8
  num_pins_y: 8
```

Screenshot of the thermal via version:
screenshot from 2018-07-18 01-27-18

### CODE REVIEW

**Comment by evanshultz** [comment]
This footprint looks good to me, but is there a reason not to leave the old footprint? Is it being used by any symbols now? I suppose re-creating it with your script later is the best option if it's not being used now, though.

Also, see my note about adding pad size to the footprint name in another QFN PR.

**Comment by poeschlr** [comment]
Yes it is used by the NXP part i mention above. (The reason why this PR has a sister symbol PR)

**Comment by Misca1234** [comment]
If this foot print is the "Footprint information for reflow soldering of HVQFN33 package " on page 116
The the pitch should be 0.5 mm

**Comment by poeschlr** [comment]
The one on page 116 is for the 5x5mm body size. Not for the 7x7mm.

**Comment by Misca1234** [comment]
Beside the arrangement of the vias all looks good

**Pull request merged**
