### PR TITLE
Add Infineon footprints from my personal lib used for the smart fets.

### PR DESCRIPTION
**Pull request by poeschlr**
This PR will add all the additional footprints needed for the smart fets i add from my personal lib in PR https://github.com/KiCad/kicad-symbols/pull/117. (Screenshots and datasheets will follow when i have added everything.)

### CODE REVIEW

**Comment by poeschlr** [comment]
Package documentations:
https://www.infineon.com/cms/en/product/packages/PG-DSO/PG-DSO-12-9/
https://www.infineon.com/cms/en/product/packages/PG-DSO/PG-DSO-12-11/
https://www.infineon.com/cms/en/product/packages/PG-DSO/PG-DSO-20-32/
https://www.infineon.com/cms/en/product/packages/PG-DSO/PG-DSO-20-71/ (This one is for -30 and -71)

Screenshots:
screenshot from 2017-12-30 23-05-19
screenshot from 2017-12-30 23-05-10

**Comment by poeschlr** [comment]
Remaining travis errors are from the thermal vias that off course have mask disabled.

**Comment by jkriege2** [comment]
Hi!

looks good, only the bottom pads are missing for the footprints with thermal vias (they don't make much sense without copper on the bottom!)

Best,
JAN

**Comment by poeschlr** [comment]
We don't have bottom pads in any of the other thermal vias versions. I think we decided on this some time back because it gives the user more freedom to connect the thermal mass to any zone they want. (Can then even be connected to a large GND plane on an inside layer)

**Comment by jkriege2** [comment]
Hhmmm ... I though we decided the other way round. And that version also ended up in KLC, see http://kicad-pcb.org/libraries/klc/F4.4/ item 2.
The bottom pad should just cover/connect all vias, so we at least have that area covered, have minimal cooling and you don't route traces between them (user can enlarge es required, or remove it in a specialized footprint). Several footprints have it already, e.g.:
- HSOP-36-1EP_11.0x15.9mm_P0.65mm_SlugDown_ThermalVias
- ST_PowerSSO-24_SlugDown_ThermalVias
- TI_SO-PowerPAD-8_ThermalVias
- Infineon_PG-HSOF-8-1_ThermalVias
- SOT-669_LFPAK_ThermalVias-1
- QFN-48-1EP_6x6mm_P0.4mm_ThermalVias
... but then equally many don't ... i.e. we should fix that at some point ;-)

I think the old discussion is here: https://github.com/KiCad/Housings_SOIC.pretty/pull/31#issuecomment-327200740 @evanshultz  proposed the wording for KLC 

So could you add it?

Thanks,
JAN

**Comment by poeschlr** [comment]
Hm i did miss that discussion. I was going on an earlier discussion about the same thing in a different PR (just can't be bothered to really look for it.)

**Comment by jkriege2** [comment]
So will you add the bottom pads?

**Comment by jkriege2** [comment]
I adressed all other ThermalVia-footprints here: https://github.com/KiCad/kicad-footprints/pull/207

**Comment by poeschlr** [comment]
Copied the top pad to the bottom layer. (Without mask and paste similar to what you did in PR #207)

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
