### PR TITLE
Esp32 wroom 2

### PR DESCRIPTION
**Pull request by Misca1234**
(replace push for https://github.com/KiCad/kicad-footprints/pull/647)

These are the foot prints used by Espressif's RF modules

ESP-WROOM-02 (existed before but modified)
https://www.espressif.com/sites/default/files/documentation/0c-esp-wroom-02_datasheet_en.pdf

ESP-WROOM-32
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf

ESP-WROOM-32U
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf

ESP-WROOM-32D
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf

The keep out area is described in
https://www.espressif.com/sites/default/files/documentation/esp-wroom-02_pcb_design_and_module_placement_guide_0.pdf

bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
The travis error is about 

    Footprint anchor is not located at center of footprint
     - Footprint center calculated as (0.0,0.775)mm

**Comment by poeschlr** [comment]
Courtyard clearance is not quite right (currently is about 0.3mm)

The -02 has no recommended land pattern in the datasheet. How are the pad sizes determined?

screenshot from 2018-07-23 14-41-47

screenshot from 2018-07-23 14-37-11

**Comment by Misca1234** [comment]
Courtyard clearance is not quite right (currently is about 0.3mm)

> The -02 has no recommended land pattern in the datasheet. How are the pad sizes determined?
Not sure, I was not the original designer, I just cleaned it up a little

I only found this resource
https://www.espressif.com/sites/default/files/documentation/esp-wroom-02_pcb_design_and_module_placement_guide_0.pdf

Do you want me to change it beside the 0.3 clearance ?

**Comment by diegoherranz** [comment]
I've started reviewing this.
It seems that ESP32-WROOM-32 and ESP32-WROOM-32D footprints are identical.
Wouldn't it make sense to have a single footprint (ESP32-WROOM-32) and reference it from both ESP32-WROOM-32 and ESP32-WROOM-32D symbols? In fact, the symbols are the same too, so the WROOM-32D could be an alias of the WROOM-32.

Thanks

**Comment by poeschlr** [comment]
@Misca1234 if you fix the courtyard clearance i would be prepared to merge.

I calculated the pads acourding to IPC for the one missing the suggested land pattern. See https://docs.google.com/spreadsheets/d/1mz7J-FMTo-L3qUG917im-0DBbNAzGDmI479VqDLaEyw/edit?usp=sharing for more details.

Result:

outside (Z) |  19.3
-- |  --
inside (S) |  15.65
width (X) |  0.85
  |      
pad center |  8.7375 |  
pad lenght |  0.9125 |  
pad width |  0.85 |

**Comment by Misca1234** [comment]
@diegoherranz 
They are not exactly the same
ESP32-WROOM-32
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf
Page 16

ESP32-WROOM-32D
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf
Page 17

You can see that the "bottom pad" is not the same size or position, it is very little difference, but it is there

**Comment by poeschlr** [comment]
Looks good, thanks

**Comment by diegoherranz** [comment]
It's true, the bottom pad is slightly different, however, the recommended footprint is the same for both. See:
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf (Figure 8)
and
https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32d_esp32-wroom-32u_datasheet_en.pdf (Figure 8)

And in fact, the footprints merged to the repo are the same as well (mind a zero length line, see below).

So, why do we need 2 footprints? (honest question)
Is it because of the 3D model? It makes it harder to maintain.

Anyway, thanks for the work on these footprints which look very good :)

Thanks!

extra zero-length line on ESP32-WROOM-32D
  (fp_line (start -9 -15.745) (end 9 -15.745) (layer Dwgs.User) (width 0.1))

**Comment by Misca1234** [comment]
@diegoherranz 
The ESP32-WROOM-32U need a seperate fp due to the 3D model but you are somewhat right about the foot print for the two others, it is on the master now so you are free to make pushes ^^ ;)
(I wont make another push for these atm)
Regards

**Pull request merged**
