### PR TITLE
Adding TE Connectivity FFC/FPC connectors and moving other such connectors.

### PR DESCRIPTION
**Pull request by poeschlr**
Adding the script generated FFC/FPC TE connectivity connectors.

For now i created a separate lib for this type of connector as i suggested in issue https://github.com/KiCad/kicad-footprints/issues/134

If we decide to do it this way i also need to add the FFC connectors from Molex and Hirose.
If we decide against it, then i need to move these connectors into Connector_TE-Connectivity.

About the footprints: I did not change anything on purpose. (Maybe text positions and line widths changed.)

script PR: https://github.com/pointhi/kicad-footprint-generator/pull/88

### CODE REVIEW

**Comment by poeschlr** [comment]
@SchrodingersGat we can archive the old TE-Connectivity repo now.

**Comment by poeschlr** [comment]
This should now be ready to merge. 

I needed to regenerate the molex 502250 footprints because their pin layout was mirrored. (Because of that i converted the generator script to use kicadModTree)

screenshot from 2017-11-30 16-54-03

**Comment by poeschlr** [comment]
Regarding part naming. Currently the cable pitch is used in the footprint name, not the pin pitch. Should i change this?

**Comment by SchrodingersGat** [comment]
Hmm probably pin pitch is better

**Comment by poeschlr** [comment]
I changed it to be the pin pitch

**Comment by SchrodingersGat** [comment]
Thanks @poeschlr  :)

**Pull request merged**
