### PR TITLE
Add VCXO Abracon ABLNO

### PR DESCRIPTION
**Pull request by aewallin**
Datasheet: https://abracon.com/Precisiontiming/ABLNO.pdf

Screenshot:
ablno

Symbol PR: https://github.com/KiCad/kicad-symbols/pull/1173

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
ablno

**Comment by poeschlr** [comment]
The outline has slightly wrong dimensions.
oscilator svg

**Comment by aewallin** [comment]
let me know if further changes are required - thanks.

**Comment by aewallin** [comment]
VCXO can be removed - especially if there's a new footprint-browser that shows the description-text also when you select footprints. In fact they make this in an non-adjustable XO version and the one I'm using which is a VCXO.

In general I think there's not that much similarity between oscillator-footprints, so Abracon *might* have some other series with this footprint (I don't know and haven't searched), but other manufacturers most likely don't use this footprint.

**Comment by poeschlr** [comment]
@evanshultz this is good to go from my side. Do you have any futher comments?

**Comment by poeschlr** [comment]
@aewallin thanks for your contribution

**Pull request merged**
