### PR TITLE
Add SOIC-16W-12 for HCP-314J

### PR DESCRIPTION
**Pull request by El3ctr0nic**
Add SOIC-16W-12 for HCP-314J

Standard SOIC-16W with removed pins
I can't generate 3D model - my python is very basic so i can't handle generation script.
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks! Only two things:
1. Update the description to mention the missing pins and add the HCPL datasheet
1. Indicate the missing pins in the keywords

**Comment by El3ctr0nic** [comment]
obraz

I'm not sure about keywords.

**Comment by evanshultz** [comment]
I think `SOIC-16 with 12 pin placed` or similar works well for the description. Keywords could be `SOIC 1.27 16 12 wide`. Those terms seem like reasonable search criteria.

Once again, always include a link to the datasheet and an image of the thing(s) you're submitting in your initial PR. Thank you.

**Comment by El3ctr0nic** [comment]
https://docs.broadcom.com/docs/AV02-0169EN

obraz

obraz

I think that now is ok.
Sorry for my english it's not my primary language I can sometime write something wrong or missunderstand.

Regards,
Marcin

**Comment by evanshultz** [comment]
This is great. And your English is good. Thank you very much!

**Pull request merged**
