### PR TITLE
WLCSP-4-X1-WLB0909-4_0.890x0.890_P0.500mm

### PR DESCRIPTION
**Pull request by chmorgan**
Footprint for a number of OnSemi power switches.

Generator PR: https://github.com/pointhi/kicad-footprint-generator/pull/575

image

https://www.diodes.com/assets/Datasheets/AP22913.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cpresser** [comment]
Is there a matching footprint-generator script and PR?

**Comment by chmorgan** [comment]
@cpresser added footprint generator PR above in the first comment, sorry about missing that.

It's at https://github.com/pointhi/kicad-footprint-generator/pull/575 if you don't want to scroll up.

**Comment by chmorgan** [comment]
@cpresser and here is the updated footprint after I removed a couple of extra fields in the footprint generator side that I learned about during previous footprint generator reviews.

**Comment by myfreescalewebpage** [comment]
@cpresser I assigned you to this PR because you self assigned to the PR of the generator associated to this footprint

**Comment by cpresser** [comment]
@chmorgan Can you please push the generator result here? I expect the name to change slightly.

**Comment by myfreescalewebpage** [comment]
@chmorgan ping

**Comment by chmorgan** [comment]
@myfreescalewebpage updated from generator, renamed from old name. Sorry for the delay and I really appreciate the review.

**Comment by myfreescalewebpage** [comment]
Helping here, footprint is ok for me, merging.

**Pull request merged**
