### PR TITLE
OCXO OH300

### PR DESCRIPTION
**Pull request by aewallin**
ConnorWinfield SMD OCXO model OH300

Datasheet: http://www.conwin.com/datasheets/cx/cx282.pdf

Screenshot:
oh300

Symbol PR: https://github.com/KiCad/kicad-symbols/pull/1174

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Thanks for this contribution.

Sadly i can see some issues with it that need to be fixed.
The datasheet calls out a keepout area for traces on the "top layer" (copper layer nearest to the part)
It also calls for a copper zone in the layer below it.

Kicad does not directly support adding keepout areas to the footprint. So we can only add notes to it to indicate this. Read http://kicad-pcb.org/libraries/klc/F4.5/ for more details.

The pin 1 indicator on the fab layer is missing. I suggest a chamfer on the nearest edge.

Rotate the footprint by 90 degree clockwise to get pin 1 to the top right corner.

The courtyard clearance should be 0.5mm for crystals (+/-0.005 mm to get it on 0.01mm grid)

There are also some dimensions wrong. See dimensioned drawing for more details.

oscilator svg

**Comment by aewallin** [comment]
- missing the keepout (I don't know how to draw this)
- KLC errors on silkscreen intersecting bottom GND-pad
oh300

**Comment by poeschlr** [comment]
We can not add a bottom pad to get the result explained in the application note. We do not know if this footprint is used in a two layer or 32 layer pcb. This is why a note on the user layers is the best option.

What part of the linked KLC (tutorial) is unclear to you regarding the keepout? Maybe we can help you out there.

**Comment by aewallin** [comment]
regarding the tools: it seems the way to draw on Dwgs.User or make comments on Cmts.User is to first add the graphic/text on some other layer and then edit the properties with "E" and change the layer to Dwgs.User or Cmts.User?
tools

**Comment by aewallin** [comment]
The footprint now has a zone drawing on Dwgs.User and a note about keepout on top and GND on 2nd layer.
oh300

**Comment by poeschlr** [comment]
We typically do not use circles as pin 1 markers. Make a chamfer on the corner nearest pin 1.

Rotate the part by 90 degree clockwise to get pin one to the top left corner.

The courtyard clearance is not yet quite right in y direction.

screenshot from 2018-12-05 19-02-09

**Comment by aewallin** [comment]
rotated, chamfered f.fab, fixed courtyard clearance:
oh300

**Comment by poeschlr** [comment]
Looks good, thanks.

**Pull request merged**
