### PR TITLE
add scripted LFCSP-64-1EP_9x9mm_P0.5mm_EP5.21x5.21mm

### PR DESCRIPTION
**Pull request by aewallin**
Analog Devices CP-64-7 used by e.g. AD9912
https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/lfcspcp/cp_64_7.pdf
https://www.analog.com/media/en/technical-documentation/data-sheets/ad9912.pdf

made with: https://github.com/pointhi/kicad-footprint-generator/pull/318
AD9912 symbol PR: https://github.com/KiCad/kicad-symbols/pull/1655 

LFCSP-64-1EP_9x9mm_P0 5mm_EP5 21x5

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Can you please also include the thermal vias version? With such a large EP I think we will want more vias than you put in the script. Perhaps 3x3 would work?

**Comment by aewallin** [comment]
3x3 ThermalVias version added.

FWIW looking at the dev-kit gerbers it seems AD uses a large pad for the EPAD and 5x5 thermalvias.
https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/eval-ad9912.html#eb-overview
(I can't seem to open the drill-file correctly in GerbView...)

but I trust the kicad footprint-generator does a good job based on IPC rules/guidelines and this generated footprint will work.

LFCSP-64-1EP_thermals

**Comment by evanshultz** [comment]
Yes indeed. The use a 7x7mm pad with 5x5 via array. Perhaps bump this up to 4x4 vias then? Plus, it looks sparse above. Otherwise, we use IPC rules, as you noted, and we'll consider this good.

**Comment by aewallin** [comment]
now with 4x4 thermalvias:
LFCSP-64-1EP_4x4

**Comment by evanshultz** [comment]
Thank you!

**Comment by nickoe** [comment]
Hmm, I would love to see a 48 lead variant of this for the ADF7021.

**Pull request merged**
