### PR TITLE
Fix DirectFET ME fab, silk, pad height

### PR DESCRIPTION
**Pull request by chschlue**
https://github.com/KiCad/kicad-footprints/pull/1804

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Pad size fix looks good.

**Comment by chschlue** [comment]
@poeschlr 
This is the way @evanschultz and me have been doing the 40 or so DirectFET PRs all week long.
What exactly is suddenly wrong with it?

**Comment by poeschlr** [comment]
The same as at the beginning of the week. I can not really say if evan is as effected by something like this as i have been when somebody did this to me. But i can for sure tell you that it is annoying that the full dashboard is full of repeated "ping" comments (which means it is much more likely that i miss stuff that would be important to see)

**Comment by evanshultz** [comment]
@chschlue 
I wanted to get these footprints done and I had them all opened in tabs so I kept charging ahead. But I agree with Rene, that no ping is necessary because I will see all PRs. I just wanted to get these done first.

Thanks for updating all of them!

**Comment by chschlue** [comment]
@evanshultz 
Ok, so the pings didn't hurt much either? If they did, I apologize.

**Comment by evanshultz** [comment]
No worries. They're just unnecessary as Rene said above.

**Pull request merged**
