### PR TITLE
Update Pqfn 8x8

### PR DESCRIPTION
**Pull request by evanshultz**
Breaking apart https://github.com/KiCad/kicad-footprints/pull/981.

https://www.fairchildsemi.com/datasheets/FD/FDMT80080DC.pdf

Changed overlapping pads to single custom pads. This needed some dimensional fixes also.
image
image

I fixed the courtyard after dimensioning.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
The datasheet link does not work for me. (I am simply shown the on semi main page)

**Comment by evanshultz** [comment]
@poeschlr 
Yep. Legacy Fairchild datasheet link.
- Updated to https://www.onsemi.com/pub/Collateral/FDMT80080DC-D.pdf which is for the same PN and all dimensions above still seem correct.
- I did catch that the courtyard was wrong above and I fixed that too in the latest commit.
- And while I was there I improved the courtyard and pin 1 silk mark.
image

Should this be changed to a manufacturer-specific name? Maybe there are other 8x8mm packages that fit this footprint, but the original datasheet (and this one, still) are for a part using the Dual Cool 88 package which appears to be unique to ON Semi (previously Fairchild).

**Comment by evanshultz** [comment]
@poeschlr 
Is this ready? I hope I fixed what you brought up.

**Comment by poeschlr** [comment]
looks good, thanks

**Pull request merged**
