### PR TITLE
Pulse pa4320 2

### PR DESCRIPTION
**Pull request by Misca1234**
This is a re push of, probably abandon, foot print
Pulse_PA4320
http://productfinder.pulseeng.com/products/datasheets/P787.pdf

original fp push
https://github.com/KiCad/kicad-footprints/pull/398

bild

bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Why does an inductor include a polarization mark?

**Comment by Misca1234** [comment]
Is not pin 1 supposed to be marked out according to the KLC in F.Silk layer ?

**Comment by poeschlr** [comment]
Only for polarized parts. (Should be added to the KLC. It was in KLC 2.x but is not really clear in KLC 3.x)

**Comment by Misca1234** [comment]
The corners looks the same now

**Comment by poeschlr** [comment]
I would make the corner markers on silk a bit longer to make aligning the part easier. (The component has rounded corners. Your silk mark should be long enough to reach the straight parts of it.)

To be honest i do not quite get why you only have marks on the corner instead of a full outline as used for all other parts in the library.

**Comment by Misca1234** [comment]
We discussed it the other day, the tendency was to use as little F.Silk as possible, but I can changed them to go all the way around

**Comment by Misca1234** [comment]
Now so

bild

**Comment by poeschlr** [comment]
Thanks, looks good.

---

The reason behind reducing silk is to reduce cost in series production. There you have camera systems that check component placements. These systems only need a very small mark on the corners as reference. In small scale (or even prototype) production settings you do not have the luxury to use such a modern system. In such a setting having a full outline helps a lot. (Especially for hand populating the pcb)

For this reason i would not go with the (future) ipc suggestions as long as there is not clear downside of using our current system.

**Pull request merged**
