### PR TITLE
TI TLC5971 

### PR DESCRIPTION
**Pull request by s-light**
adding Texas Instruments footprints following datasheet of TLC5971:
- HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.75x3.43mm_ThermalVias
- HTSSOP-20-1EP_4.4x6.5mm_P0.65mm_EP3.4x6.5mm_Mask2.75x3.43mm_ThermalVias_HandSolder

TODO:
- [x] add [QFN variant](http://www.ti.com/lit/ds/symlink/tlc5971.pdf#page=42&zoom=200,-13,779)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
http://www.ti.com/lit/ds/symlink/tlc5971.pdf
- [x] An example screenshot image is very helpful 
image
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
https://github.com/KiCad/kicad-symbols/pull/795
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by s-light** [comment]
i need some input on the QFN variants:
if i follow the [datasheet (page 42)](http://www.ti.com/lit/ds/symlink/tlc5971.pdf#page=42&zoom=200,-13,779) i can generate a perfectly fitting footprint with the help of the QFN Wizard and some manual tweaking.

but how should i name it?
the TI naming is really confusing - in this datasheet it is called `RGE 24` or `RGE0024H` and also referenced as `VQFN`.
so i looked at the [already available footprints in the library](https://github.com/KiCad/kicad-footprints/tree/master/Package_DFN_QFN.pretty) and found *similar*
- Texas_VQFN-RGW-20.kicad_mod
- VQFN-24-1EP_4x4mm_P0.5mm_EP2.45x2.45mm_ThermalVias.kicad_mod
- WQFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias.kicad_mod *1
- QFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias.kicad_mod *1

for the first- the Manufacture specific the name would be `Texas_VQFN-RGE-24_ThermalVias.kicad_mod`
and for the general version i could add  
`VQFN-24-1EP_4x4mm_P0.5mm_EP2.7x2.7mm_ThermalVias.kicad_mod`

the ones i marked with *1 are very close to the datasheet - but differ slightly in the size and spacing of the pads -
and with the normal soldermask clearance of my manufacture (0.075mm) this leads to no solder-mask between pads and EP... and if i did calculate correctly with the datasheet recommendations there is a soldermask bridge of ~0.1mm left :-)

please advice - what is the recommend naming in this case?

**Comment by poeschlr** [comment]
For qfn it is suggested to use our scripts: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_DFN_QFN (look in size definition there are already other similar ti footprints defined) The scipt is then run with `python3 ipc_qfn_generator size_definition/def.yaml`

The kicad internal qfn footprint wizard does not give you enough degrees of freedom as it places the center of the pads always exactly on the body outline. This means you have no way of defining the toe and heel sizes (either heel is too small or toe is too large)

**Comment by s-light** [comment]
https://github.com/KiCad/kicad-footprints/pull/813/commits/ba696b3a503d08f62b6327275c577a43cf7ba350
is created with 
https://github.com/pointhi/kicad-footprint-generator/pull/158

**Comment by poeschlr** [comment]
> should i go the same way for the HTSSOP things?

Right now we do not have a script that can generate such footprints. If you are interested you could modify the qfp generator to generate them. (I had planned to make this generator but until now i just did not find the time for it.)

**Comment by poeschlr** [comment]
You asked if these could be script generated. Well i invested some time and now i have a generator for this.
It is found in my pull request https://github.com/pointhi/kicad-footprint-generator/pull/149
it is found in `scripts/Packages/Package_Gullwing__QFP_SOIC_SO/`

**Comment by s-light** [comment]
@poeschlr that was fast ;-) i had thought about trying to understand the qfn-generator more so i could look in modifying ;-)...
thank! i will try it out!
when do you plan to to merge this?
or should i fork the branch and add the dimensions there?

**Comment by poeschlr** [comment]
I have no control over when it gets merged. It depends on when the qfn footprints generated by that change are merged. (Two rather large pull requests are open and no maintainer has looked at them at this point in time.)
It also depends on whether @pointhi (the maintainer of this script repo) finds time to review my changes. (I touched core functionality in that pull request so he wants to review it more closely)

**Comment by s-light** [comment]
now i have added the script generate HTSSOP-20...
size-definitions can be found at https://github.com/pointhi/kicad-footprint-generator/pull/189

**Comment by Misca1234** [comment]
Hi

Nice, you using the scripts, the yaml data files is in accordance to the data sheet

**Pull request merged**
