### PR TITLE
Footprint for Ublox zed

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.u-blox.com/sites/default/files/ZED-F9P_DataSheet_(UBX-17051259).pdf
Symbol: https://github.com/KiCad/kicad-symbols/pull/1858

Footprint: 
zed

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
How did you determine the pad sizes? (I can not see suggestions in the datasheet. You did not mention it in your description.)

**Comment by jneiva08** [comment]
The pad size is on page 19 of https://www.u-blox.com/sites/default/files/ZED-F9P_DataSheet_(UBX-17051259).pdf
The outside pads are H (0.8mm) and K (1.5mm) and the inner pad is R (1.10mm)

**Comment by poeschlr** [comment]
This drawing does not show a suggested footprint but describes the dimensions of the package itself. We might need to use IPC equations to derive the required pad sizes.

**Comment by jneiva08** [comment]
@poeschlr have contacted ublox, and having the following answer:

> Hello
> 
> Unfortunately, it is not documented yet at the moment.
> And we are still unsure when this would be available.
> Sorry for the inconvenience.
> 
> Thank you.
> 
> Best Regards, 

Probably its better to wait for them release an datasheet update.

**Comment by myfreescalewebpage** [comment]
@jneiva08 any news on this subject ?

**Comment by jneiva08** [comment]
@myfreescalewebpage I have reviewed the documentation from website again and have found the following pdf, but from other variation.

ZED-F9T: https://www.u-blox.com/sites/default/files/ZED-F9T_IntegrationManual_%28UBX-19005590%29.pdf pag.69

by this pdf the pad size is the same, but what is different is Paste Mask

What you think?

**Comment by myfreescalewebpage** [comment]
@poeschlr ping

**Comment by poeschlr** [comment]
Sorry i am currently quite busy and being sick the last last week did not help either. My focus will be on getting ready for gitlab so i guess pull request reviews will be on hold for quite some time.

**Comment by poeschlr** [comment]
Ok i will accept the pads having the same size as the "leads". In which case everything looks good.
Screenshot from 2020-02-06 20-09-26

**Comment by jneiva08** [comment]
Thanks

**Pull request merged**
