### PR TITLE
Added footprint for the SO-8 used by the PCF8523

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Datasheet - https://www.nxp.com/docs/en/data-sheet/PCF8523.pdf

Signed-off-by: John Whitmore <johnfwhitmore@gmail.com>

Footprint for the PCF8523, this time using python.

Datasheet - https://www.nxp.com/docs/en/data-sheet/PCF8523.pdf

Python:

from KicadModTree import *

footprint_name = "SO-8_4.0x5.0mm_P1.27mm"

# init kicad footprint
kicad_mod = Footprint(footprint_name)
kicad_mod.setDescription("8-Lead Plastic Small Outline, 4.0x5.0mm Body")
kicad_mod.setTags("SO-8")

# set general values
kicad_mod.append(Text(type='reference', text='REF**', at=[0, -4], layer='F.SilkS'))
kicad_mod.append(Text(type='value', text=footprint_name, at=[1.5, 4], layer='F.Fab'))

# create silscreen
kicad_mod.append(RectLine(start=[((-6.6/2) -0.25), ((-5.5/2) -0.25)], end=[((+6.6/2) +0.25), ((+5.5/2) +0.25)], layer='F.SilkS'))

# create courtyard
kicad_mod.append(RectLine(start=[((-6.6/2) -0.5), ((-5.5/2) -0.5)], end=[((+6.6/2) +0.5), ((+5.5/2) +0.5)], layer='F.CrtYd'))

# create pads
kicad_mod.append(Pad(number=1, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[-5.3/2, -(1.27+(1.27/2))], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=2, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[-5.3/2, -(1.27/2)], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=3, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[-5.3/2, (1.27/2)], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=4, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[-5.3/2, (1.27+(1.27/2))], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=5, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3/2, (1.27+(1.27/2))], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=6, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3/2, (1.27/2)], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=7, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3/2, -(1.27/2)], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=8, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3/2, -(1.27+(1.27/2))], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

# output kicad model
file_handler = KicadFileHandler(kicad_mod)
file_handler.writeFile('%s.%s' % (footprint_name, 'kicad_mod',))

screenshot from 2019-01-23 18-19-46

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
Just checking Travis

**Comment by johnfwhitmore** [comment]
from KicadModTree import *

footprint_name = "SO-8_4.0x5.0mm_P1.27mm"

# init kicad footprint
kicad_mod = Footprint(footprint_name)
kicad_mod.setDescription("8-Lead Plastic Small Outline, 4.0x5.0mm Body")
kicad_mod.setTags("SO-8")

# set general values
kicad_mod.append(Text(type='reference', text='REF**', at=[6.6/2 - (1.3/2), (-(5.5 - ((3 * 1.27) + 0.6))/2) -0.5 - 1], layer='F.SilkS'))
kicad_mod.append(Text(type='value', text=footprint_name, at=[6.6/2 - (1.3/2), (5.5 - (5.5 - ((3 * 1.27) + 0.6)) + 0.5 + 1)], layer='F.Fab'))

# create silscreen
kicad_mod.append(RectLine(start=[(0 - (1.3/2) -0.25), (-(5.5 - ((3 * 1.27) + 0.6))/2) -0.25], end=[(6.6 - (1.3/2) +0.25), (5.5 - (5.5 - ((3 * 1.27) + 0.6)) + 0.25)], layer='F.SilkS'))

# create courtyard
kicad_mod.append(RectLine(start=[(0 - (1.3/2) -0.5), (-(5.5 - ((3 * 1.27) + 0.6))/2) -0.5], end=[(6.6 - (1.3/2) +0.5), (5.5 - (5.5 - ((3 * 1.27) + 0.6)) + 0.5)], layer='F.CrtYd'))

# create pads
kicad_mod.append(Pad(number=1, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 0], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=2, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 1.27], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=3, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 1.27 * 2], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=4, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 1.27 * 3], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=5, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 0], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=6, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 1.27], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=7, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 1.27 * 2], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=8, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 1.27 * 3], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

# output kicad model
file_handler = KicadFileHandler(kicad_mod)
file_handler.writeFile('%s.%s' % (footprint_name, 'kicad_mod',))


screenshot from 2019-01-23 18-47-05

**Comment by johnfwhitmore** [comment]
from KicadModTree import *
import math

footprint_name = "SO-8_4.0x5.0mm_P1.27mm"

# init kicad footprint
kicad_mod = Footprint(footprint_name)
kicad_mod.setDescription("8-Lead Plastic Small Outline, 4.0x5.0mm Body")
kicad_mod.setTags("SO-8")

# set general values
kicad_mod.append(Text(type='reference', text='REF**', at=[math.ceil((6.6/2 - (1.3/2)) * 100) / 100, math.ceil(((-(5.5 - ((3 * 1.27) + 0.6))/2) -0.5 - 1) * 100) / 100], layer='F.SilkS'))
kicad_mod.append(Text(type='value', text=footprint_name, at=[math.ceil((6.6/2 - (1.3/2)) * 100) / 100, math.ceil(((5.5 - (5.5 - ((3 * 1.27) + 0.6)) + 0.5 + 1)) * 100) / 100], layer='F.Fab'))

# create silscreen
kicad_mod.append(RectLine(start=[math.ceil((0 - (1.3/2) -0.25) * 100) / 100, math.ceil(((-(5.5 - ((3 * 1.27) + 0.6))/2) -0.25) * 100) / 100], end=[math.ceil((6.6 - (1.3/2) +0.25) * 100) / 100, math.ceil((5.5 - (5.5 - ((3 * 1.27) + 0.6)) + 0.25) * 100) / 100], layer='F.SilkS'))

# create courtyard
kicad_mod.append(RectLine(start=[math.ceil((0 - (1.3/2) -0.5) * 100) / 100, math.ceil(((-(5.5 - ((3 * 1.27) + 0.6))/2) -0.5) * 100) / 100 ], end=[math.ceil((6.6 - (1.3/2) +0.5) * 100) / 100, math.ceil((5.5 - (5.5 - ((3 * 1.27) + 0.6)) + 0.5) * 100) / 100], layer='F.CrtYd'))

# create pads
kicad_mod.append(Pad(number=1, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 0], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=2, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 1.27], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=3, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 1.27 * 2], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=4, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[0, 1.27 * 3], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=5, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 0], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=6, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 1.27], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=7, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 1.27 * 2], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

kicad_mod.append(Pad(number=8, type=Pad.TYPE_SMT, shape=Pad.SHAPE_RECT,
                     at=[5.3, 1.27 * 3], size=[1.3, 0.6], layers=Pad.LAYERS_SMT))

# output kicad model
file_handler = KicadFileHandler(kicad_mod)
file_handler.writeFile('%s.%s' % (footprint_name, 'kicad_mod',))

**Comment by poeschlr** [comment]
I left a comment on your old pull request.

The footprint you present here does not come close to following KLC. I think you will be a lot faster adding your stuff to the ipc script as i describe it in the other pull request of yours. If you have any questions feel free to ask.

**Comment by johnfwhitmore** [comment]
This footprint is generated by a script fed to the generator as suggested in the other pull request. That pull request was deleted in favour of this better and easier solution to the addition of footprints. 

Just clearing the Travis issues. I have to translate error messages into python code.

**Comment by poeschlr** [comment]
You do not need to write a single line of pyhton code. Really read my comment closely. The only thing you need to fill out is the yaml file. The script then generates a kicad footprint ready to go.

**Comment by poeschlr** [comment]
It is possible that you did not get a notification for my comment as it is on a closed pull request. I gave you a detailed tutorial on how to use the IPC generator script already in the footprint generator repo in this comment: https://github.com/KiCad/kicad-footprints/pull/1309#issuecomment-456929066

**Comment by johnfwhitmore** [comment]
Oops I used the readme file in the generator repo as that gave an example of creating a footprint. Yes the previous pull request was deleted as it's no longer the way things are done. It now appears that I should not be issuing a pull request to the kicad-footprints library but rather creating a yaml file and submitting that to the generator repo. 

Deleting this pull request as well.

**Pull request closed without merging**
