### PR TITLE
Add Texas_DSBGA-5_0.822x1.116mm_Layout2x1x2_P0.4mm

### PR DESCRIPTION
**Pull request by evanshultz**
Adding the missing footprint from https://github.com/KiCad/kicad-footprints/issues/253.

KLC violations are due to the pad definitions and are not real issues.

Image:
image

Datasheet at http://www.ti.com/lit/ds/symlink/opa330.pdf (page 33).
Pad definitions from http://www.ti.com/lit/an/snva009ag/snva009ag.pdf.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
@poeschlr @jkriege2 
Can you take a look at this one?

**Comment by evanshultz** [comment]
@poeschlr @jkriege2 Review please? This footprint is being used by a symbol (OPA330YFF and linked above) but is not yet present in our library.

**Comment by evanshultz** [comment]
@poeschlr @jkriege2 Review please? This footprint is being used by a symbol (OPA330YFF and linked above) but is not yet present in our library.

**Comment by poeschlr** [comment]
Calm down i checked at least 30 pull requests today. Yours will not be checked earlier just because you remind us every few hours.

**Comment by poeschlr** [comment]
I think the "x" separator for the layout description might be a bit misleading here. Maybe something like 2-1-2 could be better?

According to KLC the courtyard clearance should be 1mm. (Quite huge for this device. Which leaves me to believe that that rule is not quite right. Sadly i don't have access to IPC standards to check where the 1mm suggestion comes from.)

For reference, the dimensioned sketch of this footprint
screenshot from 2018-02-04 01-48-43

**Comment by evanshultz** [comment]
The other DSBGA parts use the layout term with an "x" separator. I agree this one looks a bit more awkward with three digits, but it follows TI's convention on page 4 of http://www.ti.com/lit/an/snva009ag/snva009ag.pdf.

WIth such a small device a 1mm courtyard is relatively huge. I believe this is for inspection of the balls, which does not change regardless of package size. I'll wait for you to come back with more information, and see if I can find anything about BGA courtyard clearance in IPC docs as well.

**Comment by evanshultz** [comment]
@poeschlr 
Did you find anything about IPC courtyard clearance for BGAs? I didn't find too much:
- https://www.pcblibraries.com/forum/1mm-pitch-bga-courtyard-nominal_topic1752.html
- https://blogs.mentor.com/tom-hausherr/blog/2011/01/08/pcb-design-perfection-starts-in-the-cad-library-part-9-bga-components/

What about the "x" separator?

Anything else that needs to be done before merging?

**Comment by poeschlr** [comment]
I asked over at the forum for help.
https://forum.kicad.info/t/bga-courtyard-clearance-is-the-klc-correct-in-requireing-1mm-clearance/9544

Everything i found said the clearance is used to allow reworking of pga packages.
I found a blog that defined a relation between ball size and required clearance: https://blogs.mentor.com/tom-hausherr/blog/2011/01/08/pcb-design-perfection-starts-in-the-cad-library-part-9-bga-components/

---

From all my research i gather that for such a small package one could use clearance as low as 0.5mm.
But i am not sure how to make an easy to understand rule for the KLC.

**Comment by evanshultz** [comment]
Possibly. But for now, can we merge with 1mm?

**Comment by poeschlr** [comment]
If you want it to be merged with 1mm you would need to change it to 1mm ;)

Can i assume you mean "can we merge with 0.5mm"?

---

I still find the x separator a bit wrong here but as TI really uses this nomenclature, i would accept it.

**Comment by evanshultz** [comment]
Heh! Yes, my mistake. I meant to go with 1mm and follow KLC, until and unless we have better information. I suppose being conservative is best. Footprint updated.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
