### PR TITLE
Add Bourns 3386F

### PR DESCRIPTION
**Pull request by evanshultz**
From request at https://github.com/KiCad/kicad-footprints/pull/339.

Datasheet: https://www.bourns.com/pdfs/3386.pdf

Image:
image

This required adding the following lines to the (unreleased, which I need to clean up and do!) make_potentiometer_THT.py file in the existing section for 3386 family:
```
class_name="Bourns 3386F"
rmx=5.08; voffsetx=-9.53+5.08+2.34; vwbody=9.53 style="trimmer", shaft_hole=False, class_name=class_name, wbody=vwbody, hbody=hbody, d_body=dbody, dshaft=dshaft, dscrew=dscrew, c_ddrill=c_ddrill,c_offsetx=c_offsetx, c_offsety=c_offsety, pinxoffset=voffsetx,pinyoffset=pinyoffset, pins=pins, rmx=rmx, rmy=rmy, ddrill=ddrill, specialtags=[], add_description=add_description, name_additions=[], script3d=script3d_ph_bel,height3d=height3d)
```

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
From a request at https://github.com/KiCad/kicad-footprints/pull/357, and since this PR doesn't appear to have been reviewed yet, I've added all but the "Z" version of Bourns 3314 SMD pots.

Datasheet: http://www.bourns.com/docs/Product-Datasheets/3314.pdf

Image:
image

**Comment by poeschlr** [comment]
Is it on purpose that none of these have pin 1 on the top left?

The 3386F has a few problems. The courtyard clearance is wrong and two dimensions are not quite right.
pot

The dimensions for the 3314 footprints look good.

**Comment by evanshultz** [comment]
I used an improved version of the existing script, which placed the pins as such. I didn't change that and all our trimmer footprints should be the same.

And I believe we're covered that the pinout of our pot symbols and footprints is meaningless right now. It does need to be fixed, but I think later (?).

The courtyard clearance is handled in the script "automatically", so I'll have to take a look at that and see what happened. Hang on...

**Comment by evanshultz** [comment]
@poeschlr 
I fixed the courtyard. Thanks for catching that!

**Comment by poeschlr** [comment]
Did you also check the other two dimensions i marked?

**Comment by evanshultz** [comment]
Sorry. My eye only caught the red text. I changed the courtyard manually with the thought I'd fix the script a bit later, but let me look into the script a bit now...

**Comment by poeschlr** [comment]
No problem. I should have added more annotations to the sketch like i did in the past.

**Comment by poeschlr** [comment]
Nope looks good. (I trust you that the sketch represents the footprint that is currently in the lib.)

**Pull request merged**
