### PR TITLE
Added VQFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm

### PR DESCRIPTION
**Pull request by ppielorz**
Added two footprints for 48-pin VQFN 7x7 mm packages generated with KiCAD footprint generators.

Datasheet: http://www.ti.com/lit/ds/symlink/cc1312r.pdf

image

image

Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/338

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
see comments over at the script pull request

**Comment by poeschlr** [comment]
It seems that you used a mail address for your commits that is not known to github. This means the license assistant can not identify you correctly.

**Comment by ppielorz** [comment]
Ok, you were right. I added this email and successfully signed CLA.

**Comment by poeschlr** [comment]
You still need to update this pull request with the changes you made on the script side

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
