### PR TITLE
Added footprint for panasonic caps

### PR DESCRIPTION
**Pull request by matyro**
https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL92.pdf

Created multiple panasonic smd caps with "c_elec_round.py" script.
B
grafik

grafik

C
grafik

grafik

D
grafik

grafik

E
grafik

grafik

F
grafik

grafik

G
grafik

grafik

H
grafik

grafik

J
grafik

grafik

K
grafik

grafik

### CODE REVIEW

**Comment by matyro** [comment]
yaml description:

######################Panasonic
C_Panasonic_Standard_B:
    description: "SMT capacitor, standard, aluminium electrolytic, 4.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 4.3
    width: 4.3
    height: 5.8
    diameter: 4.0
    pad_width: 1.6
    pad_length: 2.5
    pad_spacing: 1.0

C_Panasonic_Standard_B_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 4.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 4.3
    width: 4.3
    height: 5.8
    diameter: 4.0
    pad_width: 1.6
    pad_length: 3.5
    pad_spacing: 1.0

C_Panasonic_Standard_C:
    description: "SMT capacitor, standard, aluminium electrolytic, 5.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 5.3
    width: 5.3
    height: 5.8
    diameter: 5.0
    pad_width: 1.6
    pad_length: 2.8
    pad_spacing: 1.5

C_Panasonic_Standard_C_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 5.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 5.3
    width: 5.3
    height: 5.8
    diameter: 5.0
    pad_width: 1.6
    pad_length: 3.8
    pad_spacing: 1.5

C_Panasonic_Standard_D:
    description: "SMT capacitor, standard, aluminium electrolytic, 6.3mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 6.6
    width: 6.6
    height: 5.8
    diameter: 6.3
    pad_width: 1.6
    pad_length: 3.2
    pad_spacing: 1.8

C_Panasonic_Standard_D_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 6.3mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 6.6
    width: 6.6
    height: 5.8
    diameter: 6.3
    pad_width: 1.6
    pad_length: 4.2
    pad_spacing: 1.8

C_Panasonic_Standard_E:
    description: "SMT capacitor, standard, aluminium electrolytic, 8.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 8.3
    width: 8.3
    height: 6.2
    diameter: 8.0
    pad_width: 1.6
    pad_length: 4.0
    pad_spacing: 2.2

C_Panasonic_Standard_E_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 8.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 8.3
    width: 8.3
    height: 6.2
    diameter: 8.0
    pad_width: 1.6
    pad_length: 5.0
    pad_spacing: 2.2

C_Panasonic_Standard_F:
    description: "SMT capacitor, standard, aluminium electrolytic, 8.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 8.3
    width: 8.3
    height: 10.2
    diameter: 8.0
    pad_width: 2.0
    pad_length: 4.0
    pad_spacing: 3.1

C_Panasonic_Standard_F_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 8.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 8.3
    width: 8.3
    height: 10.2
    diameter: 8.0
    pad_width: 2.0
    pad_length: 5.0
    pad_spacing: 3.1

C_Panasonic_Standard_G:
    description: "SMT capacitor, standard, aluminium electrolytic, 10.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 10.3
    width: 10.3
    height: 10.2
    diameter: 10.0
    pad_width: 2.0
    pad_length: 4.1
    pad_spacing: 4.6

C_Panasonic_Standard_G_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 10.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 10.3
    width: 10.3
    height: 10.2
    diameter: 10.0
    pad_width: 2.0
    pad_length: 5.1
    pad_spacing: 4.6

C_Panasonic_Standard_H:
    description: "SMT capacitor, standard, aluminium electrolytic, 12.5mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 13.5
    width: 13.5
    height: 13.5
    diameter: 12.5
    pad_width: 2.0
    pad_length: 5.7
    pad_spacing: 4.0

C_Panasonic_Standard_H_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 12.5mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 13.5
    width: 13.5
    height: 13.5
    diameter: 12.5
    pad_width: 2.0
    pad_length: 6.7
    pad_spacing: 4.0

C_Panasonic_Standard_J:
    description: "SMT capacitor, standard, aluminium electrolytic, 16.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 17.0
    width: 17.0
    height: 16.5
    diameter: 16.0
    pad_width: 2.5
    pad_length: 6.5
    pad_spacing: 6.0

C_Panasonic_Standard_J_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 16.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 17.0
    width: 17.0
    height: 16.5
    diameter: 16.0
    pad_width: 2.5
    pad_length: 7.5
    pad_spacing: 6.0

C_Panasonic_Standard_K:
    description: "SMT capacitor, standard, aluminium electrolytic, 18.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 19.0
    width: 19.0
    height: 16.5
    diameter: 18.0
    pad_width: 2.5
    pad_length: 7.5
    pad_spacing: 6.0

C_Panasonic_Standard_K_HandSoldering:
    description: "SMT capacitor, standard, aluminium electrolytic, 18.0mm, Panasonic"
    datasheet: "https://industrial.panasonic.com/cdbs/www-data/pdf/RDE0000/DME0000COL48.pdf"
    courtjard: 0.25
    length: 19.0
    width: 19.0
    height: 16.5
    diameter: 18.0
    pad_width: 2.5
    pad_length: 8.5
    pad_spacing: 6.0

**Comment by Shackmeister** [comment]
Hi matyro
Im currently doing a major overhaul of the capacitor script, you can continue with this PR but they will probably be replaced once I finish the script :)

**Comment by matyro** [comment]
Hi, fine for me. 
I would be happy when you include the above .yaml data. Depending on the timeframe I can close this pr.

Otherwise I would fix the missing things in the script and get the footprints corrected.

**Comment by Shackmeister** [comment]
I have included these caps in this PR
https://github.com/KiCad/kicad-footprints/pull/372

**Comment by matyro** [comment]
Thx

**Pull request closed without merging**
