### PR TITLE
Added BGA-200 pitch 0.80x0.65 mm for LPDDR4/4X SDRAM.

### PR DESCRIPTION
**Pull request by mhrdmhrd**
Datasheet: http://www.issi.com/WW/pdf/43-46LQ32256A-AL.pdf

Screenshot:
image

Package dimensions from the data sheet on page 7:
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
  Symbol PR: https://github.com/KiCad/kicad-symbols/pull/2951
  3D model PR: https://github.com/KiCad/kicad-packages3D/pull/723
  Footprint generator PR: https://github.com/pointhi/kicad-footprint-generator/pull/599
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.
  No rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by mhrdmhrd** [comment]
Thank you for reviewing my PR. I have made the two changes below:
- Changed the file name to correct the package size embedded in it. (10.0x15.0 -> 10.0x14.5)
- Replaced by the footprint generated by kicad-footprint-generator. I have only adjusted the chamfer because it partially over wrapped a BGA pad.

**Comment by cpresser** [comment]
@evanshultz I assigned you since you already took the footprint-generator PR. Un-assign yourself if you are not happy with that.

**Comment by evanshultz** [comment]
@mhrdmhrd 
Can you please confirm that the script-generated footprint didn't require any dimension adjustments? Your first bullet doesn't apply now?

Did you make any other edits? For example, the description doesn't look like it came directly from the script.

Lastly, see my comments in the script PR.

**Comment by mhrdmhrd** [comment]
@evanshultz 
Yes, I have removed all the dimension adjustments that included in the first bullet.
The description had changed in the previous commit, but I have replaced it with script-generated one. So the footprint is exactly same as the one generated by the script now.

Thanks!

**Comment by evanshultz** [comment]
Thank you!

**Comment by mhrdmhrd** [comment]
Thank you for your support and merging!

**Pull request merged**
