### PR TITLE
Finish #589: Mini-Circuits Filter Mounts FV1206 and variants

### PR DESCRIPTION
**Pull request by poeschlr**
This finishes the problems with #589 

Details will follow in comments as i work my way through the parts.

### CODE REVIEW

**Comment by poeschlr** [comment]
Details about FV1206: https://ww2.minicircuits.com/case_style/FV1206.pdf

screenshot from 2018-08-28 00-30-18

Details about FV1206-1: https://ww2.minicircuits.com/case_style/FV1206-1.pdf

screenshot from 2018-08-28 00-29-04

Dimensioned drawing of FV1206 (left) and FV1206-1

screenshot from 2018-08-28 00-22-26

**Comment by poeschlr** [comment]
Details about 1206-4 and 1206-5 (They are identical from the footprints point of view. Not wildcardable so kept as separate footprints):
- https://ww2.minicircuits.com/case_style/FV1206-4.pdf
- https://ww2.minicircuits.com/case_style/FV1206-5.pdf

screenshot from 2018-08-28 00-58-18

screenshot from 2018-08-28 00-58-43

**Comment by poeschlr** [comment]
Details about FV1206-6: https://ww2.minicircuits.com/case_style/FV1206-6.pdf

screenshot from 2018-08-28 01-23-00

Details about FV1206-7: https://ww2.minicircuits.com/case_style/FV1206-7.pdf
screenshot from 2018-08-28 01-31-12

Dimensioned drawing of 1206-6 (left) and 1206-7
screenshot from 2018-08-28 01-34-06

**Comment by poeschlr** [comment]
This should now be ready for review (I hope i fixed everything found in the original pull request. Took me way longer than expected to be honest.)

**Comment by evanshultz** [comment]
- For all but `FV1206-1`: What about a small triangle on the left fab line since pin 1 isn't on a corner?
- I see excess silk precision on several footprints.
- `FV1206`: Maybe on this one silk should be added to mark pin 1? It's ambiguous to me.
- `FV1206-1`: Could you swap the X and Y dimensions of the pads to eliminate the 270deg rotation?
- `FV1206-1`: Could the silk dogleg closer to pin 1?
- `FV1206-4` (and `-5`): Pads 2 and 4 Y dimension can be 1.015 instead of 1.014999.
- `FV1206-6`: Why is clearance not 0?
- `FV1206-6`: Why not make pads 2-4 cover exactly 0.46 to 1.51mm vertically? Does the pad need to overlap the center of the via?

**Comment by poeschlr** [comment]
Fixed everything as noted in my previous comment.

**Comment by evanshultz** [comment]
- FV1206: Yes, I saw that. But because the silk lines are so short it's not obvious to me. What about a silk line all around pin 1 like on some of our small SMT diodes (1206 shown here):
image
- FV1206-7: Pin 1 fab mark can be a small triangle. I know there's only one pin on that side but it seems to be more clear to me and you did FV1206 this way.

**Comment by evanshultz** [comment]
@poeschlr 
Can you take a look at the last couple suggestions I made above?

**Comment by poeschlr** [comment]
I am settling into a new job right now. I hope i will find some time next weekend.

**Comment by evanshultz** [comment]
Do you have time to work on this PR now?

**Comment by evanshultz** [comment]
Can you please make time to wrap this up soon?

**Comment by poeschlr** [comment]
I completely forgot about this. I think i can squeze fixing my currently open pull requests into next week.

**Comment by evanshultz** [comment]
@poeschlr 
Do have an expected time when you may be able to squeeze this in?

**Comment by poeschlr** [comment]
I did not only fix what you requested but also made the courtyard outline hug the part more closely. (The new "snap to endpoint" feature is quite nice for this.)

# 1206:
screenshot from 2018-12-12 21-57-15
screenshot from 2018-12-12 22-09-54

# 1206-4:
screenshot from 2018-12-12 22-19-10
screenshot from 2018-12-12 22-23-55

# 1206-5:
screenshot from 2018-12-12 22-44-25
screenshot from 2018-12-12 22-47-29

# 1206-6:
screenshot from 2018-12-12 22-53-12
screenshot from 2018-12-12 22-57-09

# 1206-7
screenshot from 2018-12-12 22-32-59
screenshot from 2018-12-12 22-37-23

**Comment by evanshultz** [comment]
@poeschlr 
Thanks! Very nice. I don't see anything that regressed but I didn't do a full dimensioning again with the belief that you didn't break anything and that they look nice above.

Just one question: Should the fab ref des shrink just a bit to avoid the fab pin 1 mark? If you would like to leave the text size alone I'll merge.

**Comment by poeschlr** [comment]
A real refdes will never be 5 characters long. I personally aim to get at least 3 chars into the part. (if possible 4 which should be no problem here.)

**Comment by evanshultz** [comment]
Never say never. :) I'll merge then. Thanks!

This is probably something that should go into KLC as well...

**Pull request merged**
