### PR TITLE
Added LEM-LTSR-NP footprint

### PR DESCRIPTION
**Pull request by jeremysiebers**
Footprint to be used with LEM-LTSR6-NP, LEM-LTSR15-NP and LEM-LTSR25-NP.
See [https://github.com/KiCad/kicad-symbols/pull/615](url)

[https://www.lem.com/sites/default/files/products_datasheets/ltsr_6-np.pdf](url)
[https://www.lem.com/sites/default/files/products_datasheets/ltsr_15-np.pdf](url)
[https://www.lem.com/sites/default/files/products_datasheets/ltsr_25-np.pdf](url)

ltsr_footprint

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jeremysiebers** [comment]
Updated footprint regarding comments in: [https://github.com/KiCad/kicad-symbols/pull/615](url)

**Comment by jeremysiebers** [comment]
Renamed footprint to LEM_LTSR-NP see [https://github.com/KiCad/kicad-symbols/pull/615](url)
Updated footprint due to fit-test on PCB test board.
Enlarged holes and set them all to circular shape.
Re-test footprint after new test board is lasered.

image

**Comment by jeremysiebers** [comment]
Updated Footprint contact holes after fit test on test PCB:



Contact numbers 7 to 10 do fit but they are a little to tight, also a bit more copper pad is better for soldering. 
Contact numbers 1 to 6 do not fit so they are also increased

image

image

**Comment by jeremysiebers** [comment]
Holes are now:

image

image

Look in 3D like:

image

**Comment by jeremysiebers** [comment]
@Shackmeister

No, I've downloaded the 3D model from www.lem.com

**Comment by Misca1234** [comment]
Hi

F.Silk line is not allowed to cross the pads, do something like this instead, otherwise it looks good

bild

**Comment by evanshultz** [comment]
- As mentioned above, cut silk around pads. Fill in between pairs of pads which isn't shown above.
- Description can be just `LEM current transducer LTSRx-NP 5V supply voltage series` or similar (and keep URL
- Pin 1 should be in the top left corner.
- While not required, I prefer if you adjust pad dimensions and don't rotate any pads.
- Pins 7-10 are 0.61mm across by sqrt(0.5^2+0.35*2). Drill holes should be 0.2mm bigger according to IPC (which we adopted for KLC), so 0.81mm but yours are 0.7mm. Similarly, pins 1-6 are 0.8mm so the drill should be 1mm. Is there a reason to make those 6 pins bigger?
- Annular rings should be 0.55mm bigger then the drill (see https://github.com/KiCad/kicad-footprints/issues/595), so 1.36mm for pins 7-10. Your 1.4mm is OK.
- For pins 1-6, the pads are a bit oversized but that's OK. You could shrink the small dimension to 1.85mm just to give a bit more space, but 2.8mm for the big dimension seems OK to me.
- How did you come up with the radius of the body near pins 3 and 10?
- Your courtyard is bigger than 0.25, but all other dimensions look good to me:
image

**Comment by poeschlr** [comment]
Finished in https://github.com/KiCad/kicad-footprints/pull/881

**Pull request merged**
