### PR TITLE
Adding PCB Edge PCI Express connectors

### PR DESCRIPTION
**Pull request by ki5libs**
Adding PCB Edge PCI Express connectors:
x1
PCIe_x1
x4
PCIe_x4
x8
PCIe_x8
x16
PCIe_x16

[Datasheet - PCIe Standard](http://www.ritrontek.com/uploadfile/2016/1026/20161026105231124.pdf#page=70)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi @ki5libs. I'm not reviewing this. I believe would be acceptable to move the edge outline from Dwgs.User to Edge.Cuts layer. Currently, KiCad does not provide this feature in the user interface, so we need a workaround here. Use an text editor and replace Dwgs.User by Edge.Cuts to do the trick.

image

For reference, there is a previous discussion about that.

- https://github.com/KiCad/kicad-footprints/issues/1009
- https://forum.kicad.info/t/mid-mount-connector-footprint-using-edge-cut-solved/5791/15
- https://bugs.launchpad.net/kicad/+bug/1251393

**Comment by ki5libs** [comment]
Hi @gmsotavio. Got it. In this case sign "PCB Edge" on the `Dwgs.User` makes no sense and should be removed, shouldn't it? But what do you think about another one with PCB Thickness? Is it OK?

**Comment by poeschlr** [comment]
Currently, there is a PCIexpress footprint in the lib. My assumption is that it is the same as the x1 of your contribution. If that is the case then remove the old footprint.

---

The current footprints dimensions look good.
Drawing of x1, all others checked directly in kicad (no nice drawing created)

Screenshot from 2019-10-28 20-40-09

**Comment by gmsotavio** [comment]
> Hi @gmsotavio. Got it. In this case sign "PCB Edge" on the `Dwgs.User` makes no sense and should be removed, shouldn't it?

Yes

> But what do you think about another one with PCB Thickness? Is it OK?

I would keep the PCB Thickness comment. But my suggestion is to move this comment from Dwgs.User to Cmts.User.

**Comment by ki5libs** [comment]
@gmsotavio, @poeschlr, all changes asked by you are made.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
