### PR TITLE
Add Ublox SARA G3/U2 footprint

### PR DESCRIPTION
**Pull request by jneiva08**
Add footprint for Ublox GSM/HSPDA modem

Datasheet: https://www.u-blox.com/sites/default/files/SARA-G3-U2_SysIntegrManual_%28UBX-13000995%29.pdf

Footprint:
ublox_sara

Measurements:
ublox_sara_1

Symbol PR [#1158](https://github.com/KiCad/kicad-symbols/pull/1158)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jneiva08** [comment]
Have rotated the footprint. Now it looks like:

sara_clockwise

**Comment by jneiva08** [comment]
@poeschlr is needed to make more changes?

**Comment by poeschlr** [comment]
No looks good.

**Comment by jneiva08** [comment]
thanks for your time.
tomorrow morning will fix S6.3 on the symbol

**Pull request merged**
