### PR TITLE
Add Package_DFN_QFN:QFN-20_1EP_3x3mm_P0.5mm_EP1.8x1.8mm

### PR DESCRIPTION
**Pull request by 0xdec**
[Datasheet](https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf) (page 41)
Symbol: kicad/kicad-symbols#2364

QFN-20_1EP_3x3mm_P0 5mm_EP1 8x1

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by poeschlr** [comment]
Footprints for standardized packages (including QFN) must be generated with our IPC scripts found here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON (readme for similar generator will be of help: https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO/Readme.md)

**Comment by 0xdec** [comment]
@poeschlr I don't think this is a real IPC-compliant QFN footprint, as you can see from the four small corner pads, so the QFN generator would not work. Should I rename it to be something like `Silicon-Labs_QFN-20_1EP_3x3mm_P0.5mm_EP1.8x1.8mm`?

**Comment by poeschlr** [comment]
I have a dislike of simply adding a manufacturer prefix and calling it quits. It does not really tell a user what to expect. Especially as i imagine that silicon labs will use a normal QFN 20 package for other parts.

A better solution would be to add a suffix to the name indicating that there are corner pads. Something like `_CornerPads` would work. In the long run adapting the script to create such a footprint might be an option but for now we really are stuck with making these by hand.

---

Additionally: the counter of normal pads vs center pad(s) is separated by a dash (or minus) not an underline.

Meaning the name would be: `QFN-20-1EP_3x3mm_P0.5mm_EP1.8x1.8mm_CornerPads`

To be honest one could even argue that this is not a QFN20 but a QFN16 with four additional corner pads so the name could also be `QFN-16-1EP-4CP_3x3mm_P0.5mm_EP1.8x1.8mm` (-nCP would be a new pad count modifier indicating additional corner pads). I however fear this would be confusing to users who read the datasheet and get informed that this is a qfn20.

**Comment by chschlue** [comment]
> To be honest one could even argue that this is not a QFN20 but a QFN16 with four additional corner pads so the name could also be `QFN-16-4CP-1EP_3x3mm_P0.5mm_EP1.8x1.8mm` (-nCP would be a new pad count modifier indicating additional corner pads). I however fear this would be confusing to users who read the datasheet and get informed that this is a qfn20.

I actually think this is the most reasonable solution, followed by a manufacturer prefix.

This is far from a "real" (i.e. industry standard) QFN-20, so IMO either `QFN-16-4CP...` (standard QFN-16 plus additional features) or `Silicon-Labs_QFN-20...` (something a single manufacturer happens to call QFN-20) fits best.
The DS claims [on page 42](https://www.silabs.com/documents/public/data-sheets/cp2102n-datasheet.pdf#page=42) this is MO-220 compiant by the way (which it obviously isn't).

**Comment by poeschlr** [comment]
Ok we can go with the manufacture prefix for now. If we discover more such packages then we will have a larger sample size to use for determining if the corner pads should be counted as part of the normal pads or if we should add them separately.

**Comment by 0xdec** [comment]
@poeschlr I just realized that this footprint already exists in the library as `SiliconLabs_QFN-20-1EP_3x3mm_P0.5mm`, so it seems I've reinvented the wheel. Closing this PR, thanks!

**Pull request closed without merging**
