### PR TITLE
Add TI PWP footprints for TPS703xx

### PR DESCRIPTION
**Pull request by evanshultz**
http://www.ti.com/lit/ds/symlink/tps703.pdf, page 43

Used by symbols at https://github.com/KiCad/kicad-symbols/pull/990.

image

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
The mask is actually 3.4mm wide. I'm not sure why it's coming out as 3.2mm above as it looks like I've clicked on the right points. Anyway, it's good.

**Comment by evanshultz** [comment]
I fixed the Travis error. It was a script problem that I will look into later. It's also weird why the silk lines are each two lines joined at the X axis instead of a single line.

**Comment by Misca1234** [comment]
Is this script made or by hand ?

**Comment by evanshultz** [comment]
Script. You can see the case linked above in GH.

**Comment by Misca1234** [comment]
Thx

**Comment by evanshultz** [comment]
Dang. I flipped the name of with with regards to the EP and mask size. My bad.

Fixed PR at https://github.com/KiCad/kicad-footprints/pull/1017 and script fixed.

**Pull request merged**
