### PR TITLE
Sensor_Pressure: Add MPS20N0040D-D Pressure Sensor

### PR DESCRIPTION
**Pull request by gmsotavio**
"Datasheet": http://www.qiannipicture.com/pic/UploadFile/P0/SKU236753/D25316C7669BCD169A15D29C9993CED2C763DF1663D233632363D2A193CF239B9E9B9A5697739E9D93A063.png
D25316C7669BCD169A15D29C9993CED2C763DF1663D233632363D2A193CF239B9E9B9A5697739E9D93A063
MPS20N0040D-D_2
MPS20N0040D-D_3
MPS20N0040D-D_4
MPS20N0040D-D_1
MPS20N0040D-D_5
MPS20N0040D-D_6
MPS20N0040D-D_7

Pad dimensions was based on a standard DIP-6 from KiCad library.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
The other single pressure sensor in current KiCad library has 0.5 mm of clearance for Couryard outline. I did the same for this sensor, but I think the correct clearance is 0.25mm, because the sensor is not a connector.

**Comment by evanshultz** [comment]
Yes, please use 0.25mm courtyard clearance. The other one is probably just a mistake. Good catch.

Are both versions needed, or will only one pad size be suitable?

1. Can you please add dimensions or other package-specific into in the description?
1. How did you come up with the 10.16mm row-row dimension? It seems reasonable, but with the paltry info in the drawing I'm not sure what works well.
1. All fab lines, including arcs and circles, should be 0.1mm in width.

**Comment by gmsotavio** [comment]
Thanks for your notes.

> Yes, please use 0.25mm courtyard clearance.The other one is probably just a mistake. Good catch.

Done. I will open a PR to fix the other.

> Are both versions needed, or will only one pad size be suitable?

Circular pads is suitable. I removed the LongPads version.

> 1. Can you please add dimensions or other package-specific into in the description?

Sorry. I didn't understand what you meant. Which description?

> 2. How did you come up with the 10.16mm row-row dimension? It seems reasonable, but with the paltry info in the drawing I'm not sure what works well.

This is a generic part from some unknown manufacturer, being very poorly documented. Lucky, its package fits perfectly in a breadboard with row spacing of 10.16 mm (0.4 in), which is a standard value for row-spacing in some versions of DIP packages. I end-up with this value, because it is the only standard value between 10 and 11. I don't know if it is the best value, but as you have said " It seems reasonable".
MPS20N0040D-D

> 3. All fab lines, including arcs and circles, should be 0.1mm in width.
I forgot the internal circles. Fixed!

**Comment by evanshultz** [comment]
Before the "datasheet" link in the description can you add something like the dimensions and brief description (like `Pressure Sensor, WxHxDmm`).

Do you have any official documentation for this part? Or a product page on a website?

**Comment by evanshultz** [comment]
I would just like to see better documentation. Is there an official datasheet? Or some better-known brand with a compatible part that could be used instead?

**Comment by gmsotavio** [comment]
Hi Evan

I going to search for a better documentation. But as it is a generic part from some unbranded Chinese manufacturer, I know it will be hard to find anything. I provided such part because I have done it to my personal library because I have used in a past project and as it is very popular in sites like ebay and AliExpress, many KiCad users may benefit from this ready to use footprint. If you prefer, we can keep it away from official KiCad library in order to provide a high level consistence and quality.

**Comment by gmsotavio** [comment]
Hi Evan

It seems that MPS20N0040D-D is compatible with XGZP series from CFSensor (Chinese Company). Actually the MPS20N0040D-D is a generic version from XGZP.
Screenshot_2019-07-30_11-48-48

As MPS20N0040D-D is a generic part, I know it will be hard to find a datasheet for it. I provided such part because I have done it to my personal library once I have used in a past project and as it is very popular in sites like ebay and AliExpress, many KiCad users may benefit from this ready to use footprint.

I can include the CFSensor datasheet into description. Maybe we can rename the footprint for the CFSensor naming convention, but i believe the name MPS... is well know. Maybe we can include both. I do not know. You are the experienced contributor here. I will follow your directions.

You can be asking yourself, how I know the electrically specs from this sensor. Well, some time ago SparkFun hosted this "datasheet like" for the SMD version: https://cdn.sparkfun.com/assets/home_page_posts/1/9/0/2/Pressure_Sensor.pdf. The electrical specs seem ok.

**Comment by gmsotavio** [comment]
Hi Evan

It seems that MPS20N0040D-D is compatible with XGZP series from CFSensor (Chinese Company) http://www.cfsensor.com/editor/attached/file/20170511/20170511092125_8750.pdf. Actually the MPS20N0040D-D is a generic version from XGZP.
Screenshot_2019-07-30_11-48-48

As MPS20N0040D-D is a generic part, I know it will be hard to find a datasheet for it. I provided such part because I have done it to my personal library once I have used in a past project and as it is very popular in sites like ebay and AliExpress, many KiCad users may benefit from this ready to use footprint.

I can include the CFSensor datasheet into description. Maybe we can rename the footprint for the CFSensor naming convention, but I believe the name MPS... is well know. Maybe we can include both. I do not know. You are the experienced contributor here. I will follow your directions.

You can be asking yourself, how I know the electrically specs from this sensor? Well, some time ago SparkFun hosted this "datasheet like" for the SMD version: https://cdn.sparkfun.com/assets/home_page_posts/1/9/0/2/Pressure_Sensor.pdf. The electrical specs seem ok.

**Comment by gmsotavio** [comment]
This PR is a bad idea. I'm closing it. I will avoid open new PRs for poorly documented parts in the future.

**Pull request closed without merging**
