### PR TITLE
Button_Switch_SMD: Add a 6x6mm SMD push button

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
I was not sure if the component was generic enough to be named as I have currently submitted or if should be specific for the series of the following datasheet. Let me know if you prefer a more "atomic" naming. Thanks!

https://www.ckswitches.com/media/1471/pts645.pdf

screenshot from 2018-12-11 17-59-22

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
are there cases where polarity matters? if so, pin1 should be indicated?
if they are atomic parts and you follow the datasheet it numbers pins as 1,2,3,4 (but ofcourse the generic symbol has pins 1,2...)

**Comment by poeschlr** [comment]
The only reason i could see for a pin 1 mark on non polarized parts is that it could in some cases help with debugging. (This is true for every part.)

This is clearly a generic footprint intended to work with the generic symbol. (you can tell from the footprint name.) Footprints specialized for a single component include the full part number plus manufacturer name. (It does not really make sense for the official lib to go that far for parts like standard buttons. The most we can do is have generic footprints with fully specialized symbols or more likely aliases of a fully specified symbol. For buttons even that is too far in my opinion.)

**Comment by antoniovazquezblanco** [comment]
Thanks @poeschlr,

Should we include the height of the device in the naming? (`SW_Push_1P1T_NO_6x6mm_H9.5mm`)

**Comment by poeschlr** [comment]
I am torn to be honest. On the one had having the height would allow us to offer different generic footprints fitting different parts with a correct 3d model already build in. But on the other this would mean that we will need quite a few such generic footprints.

**Comment by antoniovazquezblanco** [comment]
I will go whatever direction you prefer. Just let me know.

Thanks!

**Comment by poeschlr** [comment]
Lets include the height in the name but don't go overboard with the number of generic footprints.

**Comment by antoniovazquezblanco** [comment]
It should be ready for review.

Thanks!

**Comment by poeschlr** [comment]
Pad positions in x direction are not quite right. Courtyard clearance is wrong (Will not be fixed by moving the pads to the correct position).

Screenshot from 2019-03-14 07-02-39

**Comment by antoniovazquezblanco** [comment]
Messed up the PR. 

Re push at: https://github.com/KiCad/kicad-footprints/pull/1480

Sorry

**Pull request closed without merging**
