### PR TITLE
Useful EuroRack Footprints

### PR DESCRIPTION
**Pull request by marangisto**
This pull request is for three commonly used components that are either new or where alternative footprints have poor choice of mechanical alignment.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ Only fully traceable for PJ398SM:  

http://www.qingpu-electronics.com/en/products/WQP-PJ398SM-362.html

The other components were source from Ali-Express and I can't find direct manufacturer references:
https://www.aliexpress.com/item/BELLA-Shelf-units-produced-aristocratic-precision-adjustable-potentiometer-R09-Vertical-clubfoot-single-joint-B10K-15/1576639333.html

https://www.aliexpress.com/item/5pcs-Lot-SPDT-3Pins-2Position-ON-ON-Miniature-Rocker-Toggle-Switch-PCB-Lug-2A-250VAC-5A/32836620523.html

] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ see marangisto branch pull request on 3d model repo ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by marangisto** [comment]
The "Pad '1' not located at origin" rule seems to be in conflict with the ability to make footprints with critical mechanical alignment. Otherwise, what is the recommended approach for components that require matching panel alignment for holes, e.g. potentiometers, jacks and switches?

**Comment by poeschlr** [comment]
Wrl is used for the library. This is because the file ending is automatically replaced with step for every tool that uses step.

**Comment by poeschlr** [comment]
The qing pu audio connector is already in the library. `Jack_3.5mm_QingPu_WQP-PJ398SM_Vertical_CircularHoles`

**Comment by chschlue** [comment]
@marangisto reopen and sign CLA if you're still on this.

**Pull request closed without merging**
