### PR TITLE
Added modified HTSSOP footprint for EP size for MAX482x ICs

### PR DESCRIPTION
**Pull request by amil109**
Added modified HTSSOP footprint for EP size for MAX482x ICs.

https://pdfserv.maximintegrated.com/package_dwgs/21-0108.PDF
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ x ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 

HTSSOP-20-1EP_4 4x6 5mm_P0 65mm_EP3 1x4 2mm

- [ x ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate

https://github.com/KiCad/kicad-symbols/pull/2648

- [ TBC ] Check the output of the Travis automated check scripts - fix any errors as required
- [ NA ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cp-aquila** [comment]
Hi and thanks for the contribution!

There are also some other footprints in here (relays). Please remove them from this PR.
This should be generated with kicad-footprint-generator ipc_gullwing_generator.py. If you already did that, also add a PR for the changed .yaml file (and link it to this one).

**Comment by amil109** [comment]
Hi There,

Thanks for the hint - I didn't know about the footprint generator, I've made it in there. The name has changed as a result. Pull request for the YAML file here: 

https://github.com/pointhi/kicad-footprint-generator/pull/534

Relays removed from the pull request - sorry about that (my git is a bit rusty...).

**Comment by chschlue** [comment]
Thanks.

**Comment by chschlue** [comment]
Please remove these relay FPs.

**Comment by amil109** [comment]
Relays removed again... sorry.

**Pull request merged**
