### PR TITLE
SOIC 7.5x5.85mm (Texas DWV) footprint

### PR DESCRIPTION
**Pull request by evanshultz**
http://www.ti.com/lit/ml/mpds382b/mpds382b.pdf

image

Seemed generic enough that it doesn't need to be TI-specific.

Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/353

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by herostrat** [comment]
I checked this footprint and it is correct.

**Comment by evanshultz** [comment]
To change labels I believe one must be a part of the KiCad team. Leaving a comment is, AFAIK, the only way for someone not on the team to contribute to a PR.

You didn't express interest in joining the team above but if you are I imagine it would be welcome.

**Comment by herostrat** [comment]
I was asked (IIRC also from you) about a year ago the same question.
Then I was new to KiCad and wanted to get to know the program and workflow.
Now I guess I know the basics and am really fond of KiCad in general, so I would be happy to be a part of the team and help out :)

**Comment by evanshultz** [comment]
@poeschlr 
Boss?

**Comment by herostrat** [comment]
Should we try another information channel? :)

**Comment by antoniovazquezblanco** [comment]
> Should we try another information channel? :)

I've sent a message to the librarians group in github :)

**Comment by poeschlr** [comment]
@evanshultz thanks for the contribution. Looks good.

@herostrat i just sent you an invite.

Regarding the false positive of the script: I pinged the author in the pull request that added this feature. Lets see if we get a fix for it or if i need to open an issue over on the library utils repo.

**Pull request merged**
