### PR TITLE
Add Bourns SRR1260

### PR DESCRIPTION
**Pull request by strombom**
Bourns SRR1260 series

Datasheet: http://www.bourns.com/docs/Product-Datasheets/SRR1260.pdf

image

image

Footprint pull request: https://github.com/KiCad/kicad-packages3D/pull/246

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Please add the datasheet link to the description. Rest is fine and I will merge when that's done!

Thanks for ll your work!
JAN

**Comment by jkriege2** [comment]
Is there a reason for the rounded pads?

**Comment by strombom** [comment]
Mostly that I think it looks nicer, and a similar inductor I made has rounded land pattern:
http://www.bourns.com/docs/product-datasheets/srp2313aa.pdf

Also a large PCBA company I worked with always insisted on rounded pads but I'm not sure of the reason.

Should I go back to square pads since the datasheet has square pads?

**Comment by strombom** [comment]
Maybe not related to such large components as this, here is a recommendation on page 9:

http://www.ocipcdc.org/archive/What_is_New_in_IPC-7351C_03_11_2015.pdf

They also state that maximum radius is 0.25mm so my rounded corners are wrong either way.

**Comment by poeschlr** [comment]
I would like to keep rounded rectangles to a minimum until we have made our kicad version 4 backport of the new lib. (Will happen soonish. Depends a bit on the decision we will reach in https://github.com/KiCad/kicad-footprints/issues/117 as i would like to include that change if we decide for it.)
As IPC does suggest the use of rounded rectangles we might even consider to switch over to them in the future. (I seem to remember that the main argument for rounded rectangles is that the paste layer stencils need a radius. And there is an argument that solder flow is better with rounded rectangle pads.)

High voltage devices are a different story. There rounded rectangles are required to ensure their voltage rating. So if your component is a high voltage device than go ahead.

**Comment by strombom** [comment]
No, not using it for high voltage, thank you.

**Comment by evanshultz** [comment]
Corners also radiate more than curves. This can be important with high edge rates (voltage or current) when meeting EMC.

**Comment by jkriege2** [comment]
For now I would stick to the datasheet recommendation (I think that's best we can do until we have a proper rule). So I would remove the rounded corners from the pads here.

**Comment by strombom** [comment]
The rounded corners were removed in the latest commit.

**Comment by jkriege2** [comment]
Thanks,
JAN

**Pull request merged**
