### PR TITLE
Sop 8 3.9x5.05mm p1.27mm sop 8 5.30x5.24mm p1.27mm

### PR DESCRIPTION
**Pull request by Misca1234**
Partly replacement of push 
https://github.com/KiCad/kicad-footprints/pull/634

The foot prints are made with scripts, script push is here
https://github.com/pointhi/kicad-footprint-generator/pull/167

SOP-8_3.9x5.0mm_P1.27mm
http://www.fujitsu.com/downloads/MICRO/fsa/pdf/products/memory/fram/MB85RS16-DS501-00014-6v0-E.pdf

SOP-8_5.3x5.2mm_P1.27mm
http://www.fujitsu.com/ca/en/Images/MB85RS2MT-DS501-00023-1v0-E.pdf

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Is there a reason why you used the legacy footprint generator instead of the new one?

**Comment by Misca1234** [comment]
Legacy ?
It is the one in 
scripts/Packages/Package_SOIC/package_soic_sop.py

Which indirectly pointed to in your push
https://github.com/pointhi/kicad-footprint-generator/pull/149

when you for example updates the files
scripts/Packages/Package_XXXXX/YYYYYYY.py

**Comment by poeschlr** [comment]
How is that generator script indirectly pointed out in my push?

In that push i made the Package_QFP generator more generic to also be able to create SOIC and similar footprints. This is why i renamed that particular generator to Package_Gullwing_QFP_SOIC_SO/ipc_gullwing_generator.py (I mentioned that in my response to your original question. In the first sentence to be precise.)

**Comment by Misca1234** [comment]
Then let us go with 
 scripts/Packages/Package_Gullwing__QFP_SOIC_SO/ipc_gullwing_generator.py

First I need to figure out why directory Package_Gullwing__QFP_SOIC_SO does not show up in on my master branch
bild

**Comment by poeschlr** [comment]
It is not in your master branch because my pull request has not been merged yet.
Either clone my fork and checkout the branch on which i work
or use the following commands. (they assume that pointhis repo is added as a second remote called upstream. If you named it differently then use that name.)

```
git fetch upstream pull/149/head
git checkout FETCH_HEAD
```

you can then base a new personal branch on that by using git checkout -b branch_name (simply sent me your branch name and i can cherry-pick your additions into my branch/pull request)

As a lot of stuff has been merged today it could be that my PR is merged soon. So maybe wait one or two days if you think the above is too dangerous.

**Comment by Misca1234** [comment]
I will wait for the merge

**Comment by poeschlr** [comment]
@Misca1234 my generators have been merged into master. So you should be able to use them now.

**Comment by Misca1234** [comment]
Awsome

**Comment by Misca1234** [comment]
This push is obsolete, the foot prints have been made with the new scripts, see push
https://github.com/KiCad/kicad-footprints/pull/927

**Pull request closed without merging**
