### PR TITLE
fixed polarity sign and some silkscreen, crt yard etc.

### PR DESCRIPTION
**Pull request by Shackmeister**
fixing issue #72 
and did a few changes to silkscreen, and added a round courtyard

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
radial_cp

**Comment by jkriege2** [comment]
Hi!

could you also make a PR for the modified generator scripts?

Thanks,
JAN

**Comment by Shackmeister** [comment]
Sure, just wanted to see if there were some tweeks needed :)

**Comment by jkriege2** [comment]
The screenshot looks good to me ... could you list, what you exactly changed?

**Comment by jkriege2** [comment]
I had a look, also the small ones look good. Which courtyard offset did you use? Looks like 0.4mm, which is maybe a bit large? Default should be 0.25mm ...

Best,
JAN

**Comment by Shackmeister** [comment]
Hi @jkriege2 
my math skills are still on christmas vacation, but the courtyard should be fixed now.

here is a list of everything I changed:

- changed the polarity sign to be visible after assembly (KLC)
- made selfadjusting %R designator size
- changed the way the silkscreen is drawn (primarily to avoid problems with the polarity sign)
- made the courtyard round for the round capacitors

**Comment by Shackmeister** [comment]
Now I also made the slk polarity indicator visible for CP_Axial caps
cp_axial

**Comment by jkriege2** [comment]
Great work!

Thanks,
JAN

**Pull request merged**
