### PR TITLE
Connector JAE: Add Nano SIM Card SF72S006

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Add Nano SIM Card SF72S006

Datasheet: https://www.jae.com/direct/topics/topics_file_download/topics_id=68892&ext_no=06&index=0&_lang=en&v=202003111511468456809

Capture

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation.

The center seems shift, I suppose this is because I have centered the device following the border and the travis check is looking at the pins ?

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chschlue thanks for the review.
I think the dimensions are now OK.
For the second comment I do not understand what you mean. What is the "PnP area" ?
Joel

PS : an also one question because I still don't know how you make it, which tool are you using to draw the schematic you just attached to your comment, with all the dimensions ? Is it something integrated in Kicad ?

**Comment by chschlue** [comment]
> For the second comment I do not understand what you mean. What is the "PnP area" ?

The pick-and-place area as given in the datasheet. See [S6.2 exception](https://kicad-pcb.org/libraries/klc/F6.2/).
These parts have holes in them where the vacuum nozzles of a PnP machine couldn't pick them up and also probably and odd center of mass, so manufacturer recommendations should be followed.
This also true for your TE SIM connectors but I think I forgot to mention it in my reviews.

> PS : an also one question because I still don't know how you make it, which tool are you using to draw the schematic you just attached to your comment, with all the dimensions ? Is it something integrated in Kicad ?

@poeschlr made a very detailed tutorial [over at the forum](https://forum.kicad.info/t/tutorial-how-to-check-footprint-correctness/9279).
Personally, I avoid the TechDraw -> DXF -> LibreCad step but use TechDraw from FreeCAD 0.19pre (which fixes many shortcomings of 0.18) instead.

**Comment by myfreescalewebpage** [comment]
Understood. I have identified the pick and place on the drawing, will fix right now. We should verify for the TE parts too.

**Comment by myfreescalewebpage** [comment]
Checked the tutorial and added to my bookmarks :)

**Comment by myfreescalewebpage** [comment]
Moved anchor using 0.98mm shift from the physical center on X axis and 5.06mm distance with the bottom on Y axis.

You 2 comments above should be fixed now :)

**Comment by chschlue** [comment]
Will re-check.
Keeping up with footprint PRs isn't easy after you've been reviewing symbols like crazy lately :)

**Comment by myfreescalewebpage** [comment]
Yes sure :( will try do center correctly at the first commit for my next footprint contribution (I need to improve on footprints !)

Thanks @chschlue

**Comment by myfreescalewebpage** [comment]
So bad commits before. Thanks for pointing every thing and for your patience.
Have checked every positions, should now be good. The misunderstanding was I was almost sure before the pins C2/C6 was not centered, but they are. Not very easy to read the drawing of this part...

**Comment by myfreescalewebpage** [comment]
Fix CrtYd and Silkscren following travis result.

**Comment by myfreescalewebpage** [comment]
Very nice :) Thanks !!!

**Pull request merged**
