### PR TITLE
Fuseholder Keystone 3555-2

### PR DESCRIPTION
**Pull request by rleh**
Add Fuseholder_Keystone_3555-2

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Datasheet: https://www.keyelco.com/userAssets/file/M65p40.pdf
- [x] An example screenshot image is very helpful 
- [x] No 3D model yet
- [x] Travis automated check scripts: no errors
- [x] Give a reason behind any intentional library convention rule violation: None

grafik
grafik

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

---

<details>

<summary>

## :warning: Deprecation warning
:unamused: 

</summary>

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-footprints/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

</details>

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @rleh , thank you for your conribution.

- [ ] silk needs 0.2mm clearance from copper

- [ ] fab layer needs 0.25mm clearance from fab

**Comment by rleh** [comment]
> silk needs 0.2mm clearance from copper

Silkscreen clearance is ≥0.2mm from Copper.

image

> fab layer needs 0.25mm clearance from fab

[What do you mean?](https://kicad-pcb.org/libraries/klc/F5.2/)

**Comment by aris-kimi** [comment]
Sorry, comment updated.

**Comment by rleh** [comment]
> courtyard layer needs 0.25mm clearance from fab

This is already the case.

image

**Comment by aris-kimi** [comment]
This counts from the center of fab layer, and the center of courtyard.

Only silk counts from line's edge.

**Comment by rleh** [comment]
But also 0.25mm clearance from copper (pads) to (center of) the courtyard line, not?

image

**Comment by rleh** [comment]
Courtyard at side is now also fixed:
image

**Comment by aris-kimi** [comment]
You are correct. Thanks.

Merging now.

**Comment by rleh** [comment]
Thanks for reviewing!

**Pull request merged**
