### PR TITLE
Add footprint for Harwin M20-781xx45

### PR DESCRIPTION
**Pull request by jneiva08**
Footprint for Harwin M20-781xx45

Datasheet: https://cdn.harwin.com/pdfs/M20-781.pdf
                  https://cdn.harwin.com/pdfs/Harwin_Product_Catalog_page_225.pdf

Script [#224](https://github.com/pointhi/kicad-footprint-generator/pull/224)

harwin

Dimensions:
harwin_size

Please indicate if need do changes in footprints or script.

The datasheet do not indicates pin N.1
The 40 pin was intended for raspberry pi, but the pin order is different.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @jneiva08 can you please remove the duplicate ```M20_M20``` in the name for these? To match the naming convention for footprints already in the library. Looks good, though.

**Comment by jneiva08** [comment]
It have twice because the series name is M20, and the second is the part number,
or it shoud be like this M20-781_M20-781xx45?

**Comment by jneiva08** [comment]
@SchrodingersGat, removed the M20 series from the name

**Comment by SchrodingersGat** [comment]
THanks @jneiva08 I have tested alignment against a sample 3D model, these look good. Thanks for the contribution.

**Pull request merged**
