### PR TITLE
RF Module: Add CMWX1ZZABZ

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Add CMWX1ZZABZ module from muRata (LoRa / SIGFOX).

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
The datasheet do not indicate the recommended footprint anymore. This old one has footprint in chapter 4.

[Murata LoRa Module Preliminary Datasheet SP-ABZ-G.PDF](https://github.com/KiCad/kicad-footprints/files/2752235/Murata.LoRa.Module.Preliminary.Datasheet.SP-ABZ-G.PDF)

- [x] An example screenshot image is very helpful 

Indeed, here it is :)

capture

- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate

https://github.com/KiCad/kicad-symbols/pull/1424

- [x] Check the output of the Travis automated check scripts - fix any errors as required

No error at this time.

### CODE REVIEW

**Comment by poeschlr** [comment]
The inner pads do not agree with the suggested footprint on page 11

Courtyard clearance should be 0.25

screenshot from 2019-01-19 12-06-08

**Comment by poeschlr** [comment]
tutorial: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279

**Comment by poeschlr** [comment]
Looks good now. Thanks

**Comment by myfreescalewebpage** [comment]
Thanks for your review!

**Pull request merged**
