### PR TITLE
Renamed XFL4020 to XxL since XAL, XEL etc all shares the same footprint and added variants for different heights

### PR DESCRIPTION
**Pull request by Shackmeister**
and added variations for different heights
https://www.coilcraft.com/pdfs/xfl4020.pdf
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

thanks for your contribution. I did a quick check and some things I found:
1. Please provide the correct datasheet for XxL4030: https://www.coilcraft.com/pdfs/xfl4030.pdf ... or use the overview of the series https://www.coilcraft.com/pdfs/Doc373%20-%20XAL_XFL_XEL_Selector.pdf (maybe even add that as a second link to all)
2. I didn't find any reference to a XxL4040 (see https://www.coilcraft.com/xal.cfm) ... but I found XFL4012 and XFL4015. Could you provide a datasheet for the first one or remove it if it doesn't exist. Also to make the series complete would yo be willing to add the 4012 and 4015?
3. I'm thinking: These seem a good candidate for scripting the footprints and the models. This way we could easily add the complete series https://www.coilcraft.com/pdfs/Doc373%20-%20XAL_XFL_XEL_Selector.pdf  ... did you use scripts, or did you hand-draw them?

best,
JAN

**Comment by jkriege2** [comment]
PS: Footprint itself looks fine to me and I would merge in this form.

**Comment by Shackmeister** [comment]
Hi Jan, Thanks for the review. the footprint is handdrawn and was added a week ago or so.
I might just close this PR and get back to it later when I have some time to make a proper script for the whole series :) I simply added it since I needed it in a work project

**Comment by jkriege2** [comment]
Then maybe for now, could you fix the issues above and we merge this as is ... We can replace this by the whole series later ... OK?

**Comment by Shackmeister** [comment]
XxL4040 is mentioned here: https://www.coilcraft.com/pdfs/xal4000.pdf almost in the bottom of the document

**Comment by jkriege2** [comment]
Thanks, JAN

**Pull request merged**
