### PR TITLE
Updated the 3D model path to a number of existing 3D models

### PR DESCRIPTION
**Pull request by Misca1234**
Changed the 3D path of the following foot prints to auto generated already existing 3D models

The CHS-01A1 series looks like this
http://www.nidec-copal-electronics.com/e/catalog/switch/chs.pdf

The CHS-01B1 series looks like this
http://www.nidec-copal-electronics.com/e/catalog/switch/chs.pdf

FP: SW_DIP_SPSTx01_Slide_Copal_CHS-01A_W5.08mm_P1.27mm_JPin.kicad_mod
3D: SW_DIP_x1_W5.08mm_Slide_Copal_CHS-A

FP: SW_DIP_SPSTx01_Slide_Copal_CHS-01B_W7.62mm_P1.27mm.kicad_mod
3D: SW_DIP_x1_W7.62mm_Slide_Copal_CHS-B

FP: SW_DIP_SPSTx02_Slide_Copal_CHS-02A_W5.08mm_P1.27mm_JPin.kicad_mod
3D: SW_DIP_x2_W5.08mm_Slide_Copal_CHS-A

FP: SW_DIP_SPSTx02_Slide_Copal_CHS-02B_W7.62mm_P1.27mm.kicad_mod
3D: SW_DIP_x2_W7.62mm_Slide_Copal_CHS-B

FP: SW_DIP_SPSTx04_Slide_Copal_CHS-04A_W5.08mm_P1.27mm_JPin.kicad_mod
3D: SW_DIP_x4_W5.08mm_Slide_Copal_CHS-A

FP: SW_DIP_SPSTx04_Slide_Copal_CHS-04B_W7.62mm_P1.27mm.kicad_mod
3D: SW_DIP_x4_W7.62mm_Slide_Copal_CHS-B

FP: SW_DIP_SPSTx06_Slide_Copal_CHS-06A_W5.08mm_P1.27mm_JPin
3D: SW_DIP_x6_W5.08mm_Slide_Copal_CHS-A

FP: SW_DIP_SPSTx06_Slide_Copal_CHS-06B_W7.62mm_P1.27mm.kicad_mod
3D: SW_DIP_x6_W7.62mm_Slide_Copal_CHS-B

FP: SW_DIP_SPSTx08_Slide_Copal_CHS-08A_W5.08mm_P1.27mm_JPin.kicad_mod
3D: SW_DIP_x8_W5.08mm_Slide_Copal_CHS-A

FP: SW_DIP_SPSTx08_Slide_Copal_CHS-08B_W7.62mm_P1.27mm.kicad_mod
3D: SW_DIP_x8_W7.62mm_Slide_Copal_CHS-B

FP: SW_DIP_SPSTx10_Slide_Copal_CHS-10A_W5.08mm_P1.27mm_JPin.kicad_mod
3D: SW_DIP_x10_W5.08mm_Slide_Copal_CHS-A

FP: SW_DIP_SPSTx10_Slide_Copal_CHS-10B_W7.62mm_P1.27mm.kicad_mod
3D: SW_DIP_x10_W7.62mm_Slide_Copal_CHS-B

bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Why not rename the 3D models so that everything is in sync?

Did you check if the footprint and/or the 3D model following the KLC convention for their part type? It could be that the file names are wrong on either the footprint or the 3D model, or even both.

**Comment by Misca1234** [comment]
I faintly remember a discussion about fixing 3D models for the dip switches where I made some and other did some and someone volunteered to make them oncen for all.

They are made with these scripts.
https://github.com/easyw/kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\DIP_parts

The script seems to been well done and there are 3D models for the others as well, like omron etc.
The look of the 3D model seems to be similar to those in the data sheet.

**Comment by evanshultz** [comment]
Yes, they are nice-looking models.

But I'm asking why not align the models with the footprint name? If the script already generates nice 3D models for various manufacturers, why not then make the models that match the footprints even if it means a small change to the script to edit the output file names? Is there a reason to not have the footprint and 3D model share a file name for a manufacturer-specific part?

**Comment by Misca1234** [comment]
ok, let me change the script so they match the existing foot prints but it will be after i finnished the valve things, i close this push

**Pull request closed without merging**
