### PR TITLE
added Taiyo-Yuden_EYSGJNZWY

### PR DESCRIPTION
**Pull request by Shackmeister**
Datasheet: https://www.yuden.co.jp/wireless_module/document/datareport2/en/TY_BLE_EYSGJNZ_DataReport_V1_9_20180530E.pdf

taiyo-yuden_eysgjnzwy

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
according to Datasheet the center should be in the middle of the module

**Comment by Misca1234** [comment]
Everything looks good, fp comply to foot print

Regarding the anchor in middle, your F.Fab "line" is centred but the pads are not, 
if you want to remove the travis error just move the whole foot print.

**Comment by Shackmeister** [comment]
@Misca1234  Sorry for the delay, the center is set according to the pick and place info from the datasheet. So I dont believe it should be moved

**Comment by Misca1234** [comment]
Ok

**Pull request merged**
