### PR TITLE
added Coilcraft LPS4018 Inductor footprint

### PR DESCRIPTION
**Pull request by Shackmeister**
Datasheet:
https://www.coilcraft.com/misc/lps4018d.html

screenshot:
lps4018

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
You could use polygon pads here. (Would result in a better handling of the mask and paste layers.)
They are allowed for the v5 repo.

**Comment by Shackmeister** [comment]
I know but these footprints are only made/fixed since I'm using them in a design at work :) so no nightly build yet :) if we can accept it as is now, Ill be happy to change it once I got V5 (or the nightly build gets changed so I can run stable and nightly simultaniously on ubuntu)

**Comment by poeschlr** [comment]
I can merge it as is. There are other footprints that will benefit from polygon pads.

I will create an issue about that.

---

The only way i know of to run both is by having one of them in a virtual machine.

**Comment by Shackmeister** [comment]
sounds good :)

would be great if it could work like Freecad and Freecad-daily :)
I talked to JS Reynaud about this, he said it's on his todolist

**Pull request merged**
