### PR TITLE
Samtec LSHM and HLCD

### PR DESCRIPTION
**Pull request by poeschlr**
Newly scripted. script PR: https://github.com/pointhi/kicad-footprint-generator/pull/90

<s>HLCD will follow shortly</s> HLCD is a cable connector not pcb. This connector mates with it self.
We need to decide on a pin "number" for the shielding connector pads.

datasheets:
- landing pattern: http://suddendocs.samtec.com/prints/lshm-1xx-xx.x-x-dv-a-x-x-tr-footprint.pdf
- detailed body drawings: http://suddendocs.samtec.com/prints/lshm-1xx-xx.x-xx-dv-a-x-x-tr-mkt.pdf
- ordering information: http://suddendocs.samtec.com/catalog_english/lshm_dv.pdf

screenshot from 2017-11-30 19-54-27
screenshot from 2017-11-30 19-54-14

### CODE REVIEW

**Comment by poeschlr** [comment]
This one is ready to merge as soon as we decide on a pin number for shield pads.

**Comment by SchrodingersGat** [comment]
I'm happy with `SH` - we should document this in the KLC somehow. Are there any other specialized pad names that we should mandate?

**Comment by poeschlr** [comment]
Just a reminder, i have not yet re exported these. They still use pin number 0 for the shield pins. So do not merge yet. (will do this as soon as i am finished with my rework of the jst 3d models.)

**Comment by poeschlr** [comment]
@SchrodingersGat this should now be ready to merge again.
 - Changed to shield pin number to be SH (I did not care to update the screenshot)
 - fixed merge conflict of the fp-lib-table

**Comment by SchrodingersGat** [comment]
Great, thanks again for your fine work

**Pull request merged**
