### PR TITLE
Added generic buzzer 14D, 7mm height, P10mm

### PR DESCRIPTION
**Pull request by gggfred**
[Datasheet](https://media.digikey.com/pdf/Data%20Sheets/Panasonic%20Semiconductors%20ICs%20PDFs/EFB-R,A,B.pdf)

Footprint

Reference
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
Hi and thanks for you contribution.

This looks like it is exactly in line with the other buzzers already in the library. Which is good.
But the name does not conform to KLC. Whats the meaning of `RM`?

A compliant KLC name would be: `Buzzer_D14mm_H7mn_P10mm`

**Comment by gggfred** [comment]
> 
> 
> Hi and thanks for you contribution.
> 
> This looks like it is exactly in line with the other buzzers already in the library. Which is good.
> But the name does not conform to KLC. Whats the meaning of `RM`?
> 
> A compliant KLC name would be: `Buzzer_D14mm_H7mn_P10mm`

Hi @cpresser thanks for your comments, actually I don't know what does RM means, I just copy Buzzer_12x9.5RM7.6.kicad_mod and Buzzer_15x7.5RM7.6.kicad_mod name. But Buzzer_D14mm_H7mm_P10mm is better. I'll rename.

**Comment by gggfred** [comment]
@cpresser I renamed the part, please check again

**Comment by cpresser** [comment]
The 3D-Model is missing `mm`. 
And travis is having some issues again, it did include parts/commits that you did not commit in this PR. You can ignore the errors not related to your addition.

**Comment by gggfred** [comment]
The 3D model name now includes the missing `mm`. I read about the travis error, but I didn't understood yet, so I'll research more.

**Comment by chschlue** [comment]
I assume RM means `Rastermaß`.
Somebody apparently forgot to translate to `pitch`.

**Comment by gggfred** [comment]
Thanks @chschlue

**Comment by evanshultz** [comment]
@chschlue 
Correct. Many scripts written by @jkriege2 use or used this term.

**Comment by chschlue** [comment]
@evanshultz 
Wasn't aware of scripted buzzers. So this one should be added to https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Buzzers_Beepers?

**Comment by evanshultz** [comment]
@chschlue 
We prefer scripted solutions where possible, but we wouldn't discount a good handmade contribution without reason. Lately, Rene has been requiring scripted submissions for the IPC generators, but this footprint isn't one of them.

So if the contributor would swap out this footprint with a scripted one and submit the script update that's ideal.

I know that Jan often used `RM` in his footprints, the scripted ones being what I'm familiar with, but if one of his footprints was used as a reference (like it was here) we can proliferate that convention. Sometimes the convention might be desirable and other times not.

**Comment by chschlue** [comment]
`Rastermaß` is kind of obsolescent in German (this thread has shown its abbreviation can baffle electronics-savvy native speakers) and probably unknown elsewhere.

So I'm all for proliferating / reviving it!

**Comment by gggfred** [comment]
Ok, now everything is clear. Where can I find information about scripting?

**Comment by cpresser** [comment]
perhaps those? But I am not sure if thats the script which was used to generate the other buzzers.
https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Buzzers_Beepers

TBH, I don't see why we would want to keep `RM`. I would rather merge this PR as it is. With the current KLC compliant naming.

We can open an issue to rework the buzzers. Their geometry is so simple that we can redo the whole script so it also uses the .yaml input like the newer generators.

**Comment by gggfred** [comment]
I can rename the buzzers, I have no problem, is it possible?

**Comment by cpresser** [comment]
> 
> 
> I can rename the buzzers, I have no problem, is it possible?

Nope. That would break existing designs. So we don't want that yet. With the next major (v6) release, renaming is possible.

**Comment by evanshultz** [comment]
@cpresser 
For footprints, we can rename since they are embedded into the board file. It's symbols that are not, and the rescue feature is apparently fragile.

**Comment by cpresser** [comment]
> @cpresser
> For footprints, we can rename since they are embedded into the board file.

Then I am in favor of renaming all of them so they conform to KLC.
Perhaps even regenerating them with a updated script.

There is only one symbol for a buzzer with no FP set and the filter is `*Buzzer*`, which will still work after renaming all FPs.

**Comment by cpresser** [comment]
This has been sitting idle for quite some time.
I would like to merge this PR as it is right now. Then do a separate PR to rename all Buzzers to align the naming with current KLC.
Any objections?

@gggfred Would you like to do the renaming PR? If not, I will take care of it.

**Comment by gggfred** [comment]
Ok @cpresser I will rename the buzzers in other PR

**Pull request merged**
