### PR TITLE
Adds Connector RJ11 Connfly DS1133-S4

### PR DESCRIPTION
**Pull request by vondraussen**
Adds Connector RJ11 Connfly DS1133-S4

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
[http://www.connfly.com/userfiles/image/UpLoadFile/File/2012/10/26/DS1133.pdf](http://www.connfly.com/userfiles/image/UpLoadFile/File/2012/10/26/DS1133.pdf)
- [x] An example screenshot image is very helpful 
rj11-connfly-ds1133-s4
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
symbol: 6P4C
- [x] Check the output of the Travis automated check scripts - fix any errors as required
`Checking footprint 'RJ11_Connfly_DS1133-S4' - No errors`
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by poeschlr** [comment]
please add a screenshot of your contribution

**Comment by vondraussen** [comment]
> * How do you know the pinout? The datasheet doesn't indicate that...

According to: [https://en.wikipedia.org/wiki/Registered_jack](https://en.wikipedia.org/wiki/Registered_jack)
Pin 1 at the jack is on the left, so it should be the opposite for the connector, if the latch is on the top.
Screenshot from 2020-03-16 22-09-28

**Comment by vondraussen** [comment]
> HI @vondraussen, thank you for your submission.
> 
>     * Can you rotate the part so pin 1 is in the upper left corner per F4.2?

I've rotated it.
@chmorgan thanks for the review

**Comment by chmorgan** [comment]
Hi @vondraussen. I discussed with the other library people and there is a desire to have the silk screen outline under the part for visibility. This isn't the case for many other RJ45 adapters and this isn't particularly clear in the KLC yet. Would you be above to shift the outline silk screen out slightly so it isn't overlapping the fab, and thus isn't covered by the part when the part is installed? Apologizes for this additional feedback so late.

**Comment by vondraussen** [comment]
Hi @chmorgan would it work like in the picture?
Screenshot from 2020-03-17 20-26-16

**Comment by chmorgan** [comment]
@vondraussen alright, I pushed some updates, can you review and let me know if everything looks ok?

**Comment by vondraussen** [comment]
Looks good. Just changed the courtyard next to the mounting holes to be round.

**Comment by cp-aquila** [comment]
A pin1 marker is missing in F.Fab

**Comment by vondraussen** [comment]
> A pin1 marker is missing in F.Fab

@cp-aquila Fixed

**Comment by cpresser** [comment]
I am not sure RJ11 is correct.
* `6P4C` has RJ13 and RJ14 as aliases in the symbol lib.
* Wikipedia (https://en.wikipedia.org/wiki/Registered_jack) also suggests that RJ11 might not be correct


Updated screenshot:
image
- [ ] The slikscreen is to close to the mounting-hole
- [ ] The silkscreen can be closer to F.Fab. There should be zero or close to zero space between the two lines.
- [ ] Courtyard around the mounting holes is slightly to small: 
image
- [ ] The Pin1 marker on Silk can be closer to the part, like so: 
image



Unfortunately the _RJ lib is not that consistent, see https://github.com/KiCad/kicad-footprints/issues/1955
We should try to not introduce yet another new style here.

Is this a shielded connector?
Is it vertical or horizontal? That should be part of the description.

**Comment by vondraussen** [comment]
> I am not sure RJ11 is correct.
> 
>     * `6P4C` has RJ13 and RJ14 as aliases in the symbol lib.
> 
>     * Wikipedia (https://en.wikipedia.org/wiki/Registered_jack) also suggests that RJ11 might not be correct

changed it to RJ14

> 
> 
> Updated screenshot:
> image
> 
>     * [x]  The slikscreen is to close to the mounting-hole
> 
>     * [x]  The silkscreen can be closer to F.Fab. There should be zero or close to zero space between the two lines.
> 
>     * [x]  Courtyard around the mounting holes is slightly to small:
>       image
> 
>     * [x]  The Pin1 marker on Silk can be closer to the part, like so:
>       image
> 
> 
> Unfortunately the _RJ lib is not that consistent, see #1955
> We should try to not introduce yet another new style here.
> 
> Is this a shielded connector?
> Is it vertical or horizontal? That should be part of the description.

It is not shielded but I've added the orientation.
Screenshot from 2020-03-19 20-28-19

**Comment by chmorgan** [comment]
Hi @vondraussen, it looks like something odd happened with git. Can you fetch and rebase against kicad-footprints master? There are a ton of commits showing up that aren't the ones you were proposing. If you have trouble let me know and I can do it here.

**Comment by vondraussen** [comment]
> Hi @vondraussen, it looks like something odd happened with git. Can you fetch and rebase against kicad-footprints master? There are a ton of commits showing up that aren't the ones you were proposing. If you have trouble let me know and I can do it here.

@chmorgan please help

**Comment by chmorgan** [comment]
@vondraussen can you see how this looks? If you are in your 'feature/connectorxxxx' branch you'll want to do:

git fetch
git reset --hard origin/connectorxxxx (with your branch name here)

Basically you want to avoid doing a merge that will occur when you do 'git pull' (which does a git fetch and a git merge internally)

**Comment by vondraussen** [comment]
> @vondraussen can you see how this looks? If you are in your 'feature/connectorxxxx' branch you'll want to do:
> 
> git fetch
> git reset --hard origin/connectorxxxx (with your branch name here)
> 
> Basically you want to avoid doing a merge that will occur when you do 'git pull' (which does a git fetch and a git merge internally)

@chmorgan Thanks! I moved between two different PC's. Not sure what happened.

**Pull request merged**
