### PR TITLE
Added DC4759J5020AHF.

### PR DESCRIPTION
**Pull request by matthuszagh**
https://cdn.anaren.com/product-documents/Xinger/DirectionalCouplers/DC4759J5020AHF/DC4759J5020AHF_DataSheet(Rev_E).pdf

image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by matthuszagh** [comment]
I've renamed this footprint to a more general name since it's used in a number of different Anaren devices.

**Comment by matthuszagh** [comment]
@poeschlr, fixed.

**Comment by matthuszagh** [comment]
Ok, sorry about that @poeschlr.

**Comment by poeschlr** [comment]
I missed a small thing with my last review:
The silk pin 1 marker is not really clear this way. Maybe we let us be inspired by how we do it with DFN and LGA footprints.
(The bottom line is as long as the body is wide. The top line goes from the center of the body to the right end of the body)

screenshot from 2019-01-20 19-26-42

---

Your fixes to the land pattern look good otherwise:
screenshot from 2019-01-20 19-32-18

**Comment by matthuszagh** [comment]
Should be fixed now.

image

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
