### PR TITLE
HTSSOP-44_6.1x14mm_P0.635mm_TopEP4.14x7.01mm

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.ti.com/lit/ds/symlink/tpa3251.pdf
image

Naming for footprints with a top EP is finally settled in the last comment at https://github.com/KiCad/kicad-footprints/issues/955, so I can submit this.

Generated with the following, but since top EP isn't really supported yet I didn't make a PR. I can properly support that later with a script update so that a custom name isn't required:
```
HTSSOP-44_6.1x14.0mm_P0.5mm_TopEP4.14x7.01mm:
  size_source: 'http://www.ti.com/lit/ds/symlink/tpa3251.pdf#page=38'
  custom_name_format: 'HTSSOP-{pincount}_{size_x:g}x{size_y:g}mm_P{pitch}mm_TopEP4.14x7.01mm'
  body_size_x:
    minimum: 6.0
    maximum: 6.2
  body_size_y:
    minimum: 13.9
    maximum: 14.1
  overall_size_y:
    minimum: 7.9
    maximum: 8.3
  lead_width:
    minimum: 0.17
    maximum: 0.27
  lead_len:
    minimum: 0.5
    maximum: 0.75
  pitch: 0.635
  num_pins_y: 22
  num_pins_x: 0
  top_heatsink:
    x: 4.14
    y: 7.01
```

Symbol PR: https://github.com/KiCad/kicad-symbols/pull/2003

---

## :warning: Deprecation warning

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-footprints/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@evanshultz no comment on this footprint.
I suggest anyway to push the definition to the generator repo, just to not lose it + create an issue to indicate the generator should be updated to support this configuration. What do you think ?
Joel

**Comment by myfreescalewebpage** [comment]
@evanshultz ping

**Comment by evanshultz** [comment]
Sure thing! https://github.com/pointhi/kicad-footprint-generator/pull/636

**Comment by myfreescalewebpage** [comment]
Thanks, merging.

**Pull request merged**
