### PR TITLE
Add footprint for 8045 Crystal

### PR DESCRIPTION
**Pull request by gcormier**
New crystal footprint, 8045.

This will accomodate : http://www.txccrystal.com/images/pdf/ax-automotive.pdf

Uses manufacturers recommended pads.

image

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

F.Fab should be the physical size, your drainw sets the height to 5 mm when it is 4.5
F.CrtYrd should include the pads aswell
Change the name into 
Crystal_SMD_TXC_8045-2Pin_8.0x4.5mm
Add the 3D path as well
Pads X position should be 3.25


Try something like this
(module Crystal_SMD_8045-2Pin_8.0x4.5mm (layer F.Cu) (tedit 5BBD0101)
  (descr "SMD crystal 8-40MHz http://www.txccrystal.com/images/pdf/ax-automotive.pdf")
  (tags "SMD SMT crystal")
  (attr smd)
  (fp_text reference REF** (at 0 -3.7) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value Crystal_SMD_8045-2Pin_8.0x4.5mm (at 0 3.7) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text user %R (at 0 0) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start -3.8 -2.25) (end 3.8 -2.25) (layer F.Fab) (width 0.1))
  (fp_line (start 4 -2.05) (end 3.8 -2.25) (layer F.Fab) (width 0.1))
  (fp_line (start 4 -2.05) (end 4 2.05) (layer F.Fab) (width 0.1))
  (fp_line (start 3.8 2.25) (end -3.8 2.25) (layer F.Fab) (width 0.1))
  (fp_line (start -3.8 2.25) (end -4 2.05) (layer F.Fab) (width 0.1))
  (fp_line (start -4 2.05) (end -4 -2.05) (layer F.Fab) (width 0.1))
  (fp_line (start -4 -2.05) (end -3.8 -2.25) (layer F.Fab) (width 0.1))
  (fp_line (start 0 -2.38) (end -4 -2.38) (layer F.SilkS) (width 0.12))
  (fp_line (start -4.75 -2.5) (end -4.75 2.5) (layer F.CrtYd) (width 0.05))
  (fp_line (start -4.75 2.5) (end 4.75 2.5) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4.75 2.5) (end 4.75 -2.5) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4.75 -2.5) (end -4.75 -2.5) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4 2.05) (end 3.8 2.25) (layer F.Fab) (width 0.1))
  (fp_line (start -1 2.38) (end 1 2.38) (layer F.SilkS) (width 0.12))
  (pad 1 smd rect (at -3.25 0) (size 2.5 3) (layers F.Cu F.Paste F.Mask))
  (pad 2 smd rect (at 3.25 0) (size 2.5 3) (layers F.Cu F.Paste F.Mask))
  (model ${KISYS3DMOD}/Crystal.3dshapes/Crystal_SMD_TXC_8045-2Pin_8.0x4.5mm.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)

**Comment by gcormier** [comment]
If there is no 3D model what should I do?

**Comment by Misca1234** [comment]
> If there is no 3D model what should I do?
The 3D model's url should always be included, in case someone makes the 3D model later, then the FP does not have to be re pushed.

However, someone just did one ;)

bild

**Comment by Misca1234** [comment]
Your FP look like this now

bild

The F.Silk line is "cutting" through pads, this is not allowed
Your F.CrtYrd does not "circumvent everything"
The 3D path is missing
You can remove the the central dot (why is it included?)
The pads should have rounded rectangles

Compare it to the one I gave you

bild

**Comment by gcormier** [comment]
Okay I'll make the changes this evening :) Thanks for the 3D file ;)

**Comment by gcormier** [comment]
CrtYrd 0.5mm clearance as per KLC.

image

**Comment by Misca1234** [comment]
Just a thought, the other TXC crystals are named like this
Crystal_SMD_TXC_XXX where XXX is the serie, your crystal is the XA serie, 

what do you say about renaming the foot print into Crystal_SMD_TXC_AX-2Pin_8.0x4.5mm ?

**Comment by Misca1234** [comment]
@evanshultz 
You thinking of the dot in the center ?

**Comment by evanshultz** [comment]
None of the F.SilkS layers I see above match the docs I linked.

**Comment by gcormier** [comment]
image

**Comment by Misca1234** [comment]
@gcormier 
You forgott to change the 3D model path to 
Crystal_SMD_TXC_AX_8045-2Pin_8.0x4.5mm.wrl
it is still
Crystal_SMD_TXC_8045-2Pin_8.0x4.5mm

**Comment by Misca1234** [comment]
Great thx

**Comment by Misca1234** [comment]
3D model push here 
https://github.com/KiCad/kicad-packages3D/pull/417

**Pull request merged**
