### PR TITLE
Added TDK VLF10040 Series

### PR DESCRIPTION
**Pull request by johnfwhitmore**
http://www.efreewind.cn/data2/pdf_data/VLF10040.pdf

screenshot from 2017-11-07 16-28-19

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
I wonder have a left something out of this pull request which means that the ball, so to speak, is in my court here?

**Comment by SchrodingersGat** [comment]
@johnfwhitmore nope, there are just only very few librarians :) I shall have a look over this soon :)

**Comment by johnfwhitmore** [comment]
@SchrodingersGat cheers for that, I just wondered had I ticked all the boxes. Hope it's acceptable but will try sort out any problems.

**Comment by SchrodingersGat** [comment]
Nice work :)

**Comment by johnfwhitmore** [comment]
Thanks a million for that ;-)

**Comment by SchrodingersGat** [comment]
Thank you! Please keep the contributions coming :)

**Comment by johnfwhitmore** [comment]
I will certainly try, it's easier then I thought, especially as the CI tests tell me what I've done wrong

**Comment by johnfwhitmore** [comment]
I wonder can I still communicate on this channel, inspite of the PR being closed and branch deleted?

**Comment by evanshultz** [comment]
You can, but all libraries get an email for every comment. So no need to thank us or prolonging a conversation. Your continued contributions say it all!

**Comment by johnfwhitmore** [comment]
Got an answer to the question I was going to ask. Sorry about the noise

**Pull request merged**
