### PR TITLE
add SMD Fuse Schurter UMZ250

### PR DESCRIPTION
**Pull request by lorem-ipsum**
This adds a footprint for the [Schurter UMZ250](https://us.schurter.com/bundles/snceschurter/epim/_ProdPool_/newDS/en/typ_UMZ_250.pdf) series of SMT fuses.

Screenshot_20191005_170001

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
- [ ] Body Size is 11.1, should be 11.3
- [ ] Pad-Distance is not correct, should be 5.5mm
- [ ] I suggest to add the 'ears' created by the holder to the body-outline in F-Fab

**Comment by lorem-ipsum** [comment]
I've fixed the pads and reworked the fab layer. I copied the fab from the UMT250 (which is clipped into the "ears") and added the ears as extra rectangles.
Screenshot_20191225_155937

**Comment by cpresser** [comment]
image
- [x] Pad size and distance
- [x] courtyard
- [ ] Description has `3.8 x 11.1 mm`. Where did you get these values? I see `4.2x11.3mm`.
- [ ] The F.Fab lines look to crowded in my opinion. This is highly subjective. I tried several different styles and don't have a clear favorite. This one is the least shitty one I could come up with: 
image

**Comment by lorem-ipsum** [comment]
Not sure where I got the size from the datasheet also says 4.2mm. Fixed it. Also used your suggestion on the Fab lines, I agree this looks cleaner.

**Pull request merged**
