### PR TITLE
Add Quectel M95 GSM modem

### PR DESCRIPTION
**Pull request by Schlumpf**
grafik
https://www.quectel.com/UploadImage/Downlad/M95_Hardware_Design_V1.3.pdf (see section 6.2 for footprint)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] ~~If there are matching symbol or 3D model pull requests, provide link(s) as appropriate~~
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] ~~Give a reason behind any intentional library convention rule violation.~~

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by jneiva08** [comment]
For the F.Paste you can follow the document provided by Quectel.
https://www.quectel.com/UploadImage/Downlad/Quectel_Module_Secondary_SMT_Application_Note_V2.7.pdf#page=13

Have made the changes for BC66 and BC95 is still in PR

**Comment by Schlumpf** [comment]
Done

**Comment by myfreescalewebpage** [comment]
Hello @Schlumpf I start review of this footprint:

- [ ] F.SilkS offset from F.Fab should be 0.11mm
- [ ] F.SilkS clearance with all pads should be at least 0.2mm, you have no need to draw the silkscreen so closed to the pads
- [ ] F.CrtYd offset should be 3mm from F.Fab for this part, you have an error of 0.05mm on the left and the right sides

Joel

**Comment by myfreescalewebpage** [comment]
@Schlumpf ping

**Comment by Schlumpf** [comment]
I fixed the issues 2 and 3.
Why should be an offset between Silk and Fab? I did not find it in KLC...

**Comment by Schlumpf** [comment]
See https://github.com/KiCad/kicad-footprints/pull/2109 for question about offset between Silk and Fab.

**Comment by myfreescalewebpage** [comment]
Answer at #2109, please ping me when this footprint is ready for the next steps of the review.

**Comment by Schlumpf** [comment]
@myfreescalewebpage ping

**Comment by myfreescalewebpage** [comment]
Thanks @Schlumpf 
The second point is not addressed. KLC F5.1 (https://kicad-pcb.org/libraries/klc/F5.1/) recommend distance between pad and silkscreen to be at least 0.2mm.

Capture

Joel

**Comment by Schlumpf** [comment]
Damn, I measured against the paste layer. I will correct it tomorrow.

**Comment by Schlumpf** [comment]
@myfreescalewebpage fixed :)

**Comment by myfreescalewebpage** [comment]
Looks great, thanks. Merging.

**Pull request merged**
