### PR TITLE
modified QFN-16-1EP_4x4mm_P0.65mm according to new footprint style

### PR DESCRIPTION
**Pull request by Shackmeister**
datasheet: http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf

Screenshot:
qfn16_4x4

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Hm this might not be enough paste coverage. (It's ~30% of the copper area)
Accourding to: https://www.allaboutcircuits.com/technical-articles/stencil-design-for-exposed-pad-packages/ 
the coverage should be somewhere between 50% and 80%.

See discussion in https://github.com/KiCad/kicad-footprints/issues/211

**Comment by Shackmeister** [comment]
I have now changed the paste layer to have a clearance of 70,87% on the epad
and changed the Courtyard to a prettier one:
qfn16_1ep

**Comment by poeschlr** [comment]
How do you get 70.87%?
I get 77.44% (Ap/Acu=4x1.1^2/2.5^2). Which would be a bit on the high side.
Have you used 1-(Acu-Ap)/Ap = 2-Acu/Ap

**Comment by Shackmeister** [comment]
by being a bit clumsy on the keyboard :)
using 1,05 paste pads now which should give 70,56% (fingers crossed)

**Comment by poeschlr** [comment]
Yup better now. Thanks.

**Comment by poeschlr** [comment]
Your commit messages could use a bit better explanation. Your last one could be something on the line of: "Changed paste pads to achieve paste coverage of 70%"

**Pull request merged**
