### PR TITLE
Button_Switch_SMD: Add KSC7 button from CK switches

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
https://www.ckswitches.com/media/1973/ksc7.pdf

imagen

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
BONUS: Added KSC6

https://www.ckswitches.com/media/1972/ksc6.pdf

imagen

**Comment by evanshultz** [comment]
- I think we can ditch the `LFx` or use `xxx` since RoHS compliance is non functional.
- Silk can be offset by just 0.11mm but this is OK.
- If we use the dimensions they give as nominal (not min or max), pads should be 2.8mm wide on +/-2.9mm X location.
- KSC6 button circle should be 1.85mm radius.
- Courtyard offset should just be 0.25mm unless I misunderstand this requirement for switches. So yours are too big.

**Comment by poeschlr** [comment]
I think these would get the name prefix:

`SW_push_1P1T_NO`

See: https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-450632899

**Comment by antoniovazquezblanco** [comment]
Performed requested changes!

**Comment by evanshultz** [comment]
1. Should we have all lowercase in the footprint name? Not `Push`?
1. Is the trailing `xxx` required? Would that be important in the 3D model?
1. Pads should have X location of +/-2.9mm, right? Then courtyard X location can be +/-4.55m.
1. KSC6: Should the circle be 1.45mm in diameter, half of 2.9mm?

**Comment by antoniovazquezblanco** [comment]
Done!

**Comment by evanshultz** [comment]
Looks good. Thanks!

**Comment by antoniovazquezblanco** [comment]
Thank you!

**Pull request merged**
