### PR TITLE
LED SMD: Create Wurth 150141M173100

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Create Wurth 150141M173100

This LED can be used with standard "LED_ABRG" symbol we have in the library.

Datasheet: https://www.we-online.de/katalog/datasheet/150141M173100.pdf

The design is based on "LED_Cree-PLCC4_3.2x2.8mm_CCW" already in the lib (dimension of the package are the same but pads are larger and not at the same position)

Screenshot:

Capture

Image:

---

## :warning: Deprecation warning

On Oct 1, 2020 this repository, including issues and pull requests, will be archived and transferred to [gitlab.com](https://gitlab.com/kicad/libraries/kicad-footprints/). In order for your pull requests and issues to be imported into GitLab you must set your email address on GitHub to public and use the same address for your GitLab account. Or login to GitLab at least once using the GitHub icon. Otherwise the importer can't correlate the account information and the issues/comments on GitLab will be owned by `kicad-bot` ([importer documentation](https://docs.gitlab.com/ee/user/project/import/github.html#how-it-works)).

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by aris-kimi** [comment]
Hi @myfreescalewebpage , after a quick look pin numbering/location is different from ds.
I will check again later when i'll have access to kicad.

**Comment by myfreescalewebpage** [comment]
Ohhhh you're right !!! Thanks to point it, I was just finishing a personal project with this, I will fix right now.

**Comment by myfreescalewebpage** [comment]
Fixed, and screenshot on top of the PR updated, thank you so much @aris-kimi

**Comment by myfreescalewebpage** [comment]
Silkscreen indicator of pin 1 moved following previous change, and screenshot updated again

**Comment by aris-kimi** [comment]
Thanks, i will full review later today.
Now from the image, may i suggest to change also fab layer in order to shown with 5 corners outside ( i mean with bevel) and not 4 (the rectangular one)? What do you think?

**Comment by myfreescalewebpage** [comment]
> to shown with 5 corners outside

Not understood

**Comment by aris-kimi** [comment]
I meant rectangle trapezoid :)

**Comment by myfreescalewebpage** [comment]
Added an image of the part in the first message, not sure where it is possible because the part is very rectangular, but you can make a simple drawing if you want

**Comment by aris-kimi** [comment]
Hi @myfreescalewebpage ,

I think this also needs a 90Deg counterclockwise rotation.

45Deg bevel also needs to point pin1 (also the kind of fab design i was trying to describe)
εικόνα

I think silkscreen needs to change like @cnieves1 's approach on the other PR, like this in order to point cathode, and also pin1 with a single line. ( I do not like those internal graphics tbh, but it is not a problem and a lot of footprints have them so it is acceptable)
εικόνα

Dimensions are good.

**Comment by myfreescalewebpage** [comment]
> I think this also needs a 90Deg counterclockwise rotation.

Why ?

> 45Deg bevel also needs to point pin1 (also the kind of fab design i was trying to describe)

On this device the 45deg corner physically present on the device indicate pin 3... So moving the corner to pin 1 will be a big trouble !

> I think silkscreen needs to change like @cnieves1 's approach on the other PR, like this in order to point cathode, and also pin1 with a single line. ( I do not like those internal graphics tbh, but it is not a problem and a lot of footprints have them so it is acceptable)

I don't really like the two SilkS lines not aligned. Is it something we have a lot in the library or do you speak of just one footprint ?
Probably something like "LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm" is better in my opinion, corner on the physical device indicated by pin 3 and marker on pin 1 indicated by the number "1" added on SilkS.

Joel

**Comment by aris-kimi** [comment]
As per KLC:
F4.2 - Pin 1 should be located at the top left
or left if there are 2pins.

I am wondering if something like this is a good compromise in order to show mf's cut, and still according to KLC F5.2.2
εικόνα

Do you think this is a better approach for cnieves1's deign?
εικόνα

**Comment by myfreescalewebpage** [comment]
> F4.2 - Pin 1 should be located at the top left

Ooooh you're right. A rule I have miss. Changing right now.

> I am wondering

I'm not sure we have to create new design, existing LEDs have been integrated and worked previously and we just have to follow the example. Creating new design like @cnieves1 is just a way to disturb futur contributions.

**Comment by myfreescalewebpage** [comment]
Proposition updated on the basis of "LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm" footprint. Screenshot updated.

**Comment by aris-kimi** [comment]
Agreed here, but then this will have to be against klc.. I am not sure if passing by some rules has a good effect either..
I am willing to try and (manualy) reorganize those library's designs after migration.

I think it is good to ask for some input here from a more experienced reviewer, what do you think?

However i liked those last changes and i can say i will approve this new design. I will also advice cnieves1 to copy numbering for pin1 silkscreen too.

But i will also ask you to close silk line all over that empty space at the bottom part of the footprint, as most of footprints currently are afaik..

**Comment by chschlue** [comment]
Please wait a moment.

**Comment by myfreescalewebpage** [comment]
I was about to ping you @chschlue about this specific footprint with a strange "pin 1 indicator" :)

**Comment by chschlue** [comment]
For some reason the GitHub app notified me even before you pinged ;)

This is a corner case and not covered by KLC, but bear with me...
The only people who ultimately care about orientation are assembly houses and nobody but the designer really cares about pin numbers. Now, what data do we have here:
1) The part has a physical mark at pin 3.
2) The datasheet specifies the orientation on the reel in terms of said mark.
3) Position files contain orientation but no information about pin numbers.

To me, the sensible conclusion is: Mark pin 3 on fab and silk, rotate such that (IPC / IEC Level B) zero orientation is pin 3 (and all indicators) top left.
Am I missing something?

**Comment by myfreescalewebpage** [comment]
> zero orientation is pin 3

This means pin 3 at top left position ?

I trust in you, I agree with your arguments

**Comment by chschlue** [comment]
Yes.

**Comment by myfreescalewebpage** [comment]
Back to pin 3 on top left corner, screenshot updated in first message

**Comment by chschlue** [comment]
@myfreescalewebpage One more thing: Please change name to Wuerth. See https://github.com/KiCad/kicad-footprints/pull/2255.

**Comment by myfreescalewebpage** [comment]
oupss yes absolutely !

**Comment by aris-kimi** [comment]
Thanks both. Merging now.

PS: I must note that this was a very interesting PR..

**Comment by myfreescalewebpage** [comment]
Yes for me too :) 
Thanks for your time

**Pull request merged**
