### PR TITLE
Adding files from unfinished PR in old RF_modules repo.

### PR DESCRIPTION
**Pull request by poeschlr**
This is again a fix for https://github.com/KiCad/kicad-symbols/issues/520
It adds footprints that where stuck in an unfinished PR over at the RF_Modules repo. (https://github.com/KiCad/RF_Modules.pretty/pull/23)

Datasheet: https://github.com/Telecom-Design/Documentation_TD_RF_Module/raw/master/TD1205%20Datasheet.pdf

https://s3-eu-west-1.amazonaws.com/assetstdnext/download/TD120xR+Datasheet+rev1.2.pdf

### CODE REVIEW

**Comment by poeschlr** [comment]
Details about TD1205

screenshot from 2018-04-25 15-10-21

screenshot from 2018-04-25 15-02-02

**Comment by poeschlr** [comment]
Details for 1208

screenshot from 2018-04-25 15-46-42
screenshot from 2018-04-25 15-41-00

**Comment by poeschlr** [comment]
Now with fixed courtyard:
screenshot from 2018-04-25 15-54-31

**Comment by Ratfink** [comment]
TD1205 looks okay to me.  TD1208 has some issues though:

* Keep-out zone's right edge should be aligned with the left edges of pads 23-25.
* Pad 23 should be 6.38 mm away from pad 22, not 6.35 mm.
* No silkscreen under part (remove the arc around the keep-out zone).
* The top and bottom courtyard clearance should be 0.255 mm, to maintain the minimum of 0.25 mm (am I right about this interpretation?).

**Comment by poeschlr** [comment]
Fixed

screenshot from 2018-04-26 14-56-21

screenshot from 2018-04-26 14-55-52

**Comment by Ratfink** [comment]
Thanks for fixing these old footprints!

**Pull request merged**
