### PR TITLE
Add DirectFET SB

### PR DESCRIPTION
**Pull request by chschlue**
Add DirectFET SB

https://www.infineon.com/dgdl/Infineon-AN-1035-ApplicationNotes-v29_01-EN.pdf?fileId=5546d462533600a40153559159020f76#page=23

DirectFET_SB

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Just the issue already mentioned about body and courtyard height.
image

**Comment by chschlue** [comment]
@evanshultz ping

BTW, I just incremented the timestamps during these fixes, assuming they're really just fancy monotonic revision counters. Anything wrong with that?

**Comment by evanshultz** [comment]
No problem whatsoever with me. I'm not aware that we care when the latest change was done, or if the change was done in a text editor and the timestamp doesn't move.

Thanks again!

**Comment by poeschlr** [comment]
If the timestamp is not updated then the update footprint feature within pcb_new might not work

**Comment by chschlue** [comment]
I thought it would be something like that. Still, incrementing by one should be good enough then?

**Comment by poeschlr** [comment]
Didn't you write you made them by hand with kicad? Because kicad already takes care of handling the timestamp

**Comment by chschlue** [comment]
True, but vi doesn't take care of handling the timestamp while fixing the outline dimensions :-)

**Pull request merged**
