### PR TITLE
Texas VQFN RHL

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: http://www.ti.com/lit/ds/symlink/bq51050b.pdf (pag.40)

Screenshot:
texas

Later will add symbol

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Is this the same footprint as https://github.com/KiCad/kicad-footprints/pull/454?

**Comment by jneiva08** [comment]
it seems to be the same

**Comment by jneiva08** [comment]
forgot to add 3d
3d

**Comment by poeschlr** [comment]
As this one includes the Thermal vias it should have a suffix _ThermalVias

**Comment by jneiva08** [comment]
Renamed footprint to have "_ThermalVias" on the name

**Comment by poeschlr** [comment]
Paste pads (the ones without a pin number) should not have copper enabled.

I would suggest to change the pad types to rounded rectangle with 25% round radius (maximum radius 0.25mm.)

It might also be a good idea to change pad 21 into a polygon pad (not necessary for merging this.)
And there is a small mistake with the layout of pad 1 (the blue dimension should be 0.4 instead of 0.405)

screenshot from 2018-07-28 01-51-50

**Comment by jneiva08** [comment]
* Changed the pads to be rounded to be near 0.05,
* Fix small mistake to be 0.4mm instead 0.405,
* Removed F.CU from F.Paste pads.

vqfn

@poeschlr 
Where can find maual for make polygon pad's?

**Comment by poeschlr** [comment]
Looks good, thanks (sorry for the delay in merging, i kind of forgot about that one)

**Pull request merged**
