### PR TITLE
Add VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias

### PR DESCRIPTION
**Pull request by cronJ**
Add VQFN-16-1EP_3x3mm_P0.5mm_EP1.6x1.6mm_ThermalVias

symbol: https://github.com/KiCad/kicad-symbols/pull/1867

Created from [http://www.ti.com/lit/ds/symlink/cdclvp1102.pdf](http://www.ti.com/lit/ds/symlink/cdclvp1102.pdf)

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Footprints for standardized packages like this should be scripted using our IPC generator script. https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON

**Comment by cronJ** [comment]
First time using the script. Hope the two files are okay.

**Comment by poeschlr** [comment]
Could you link to the pull request on the script repo? The review will then mostly happen over there.

**Comment by cronJ** [comment]
https://github.com/pointhi/kicad-footprint-generator/pull/367

**Comment by poeschlr** [comment]
You would need to update this pull request with the footprint generated by the script.

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
