### PR TITLE
added Texas Instruments S-PWSON-N8, with&without thermal vias

### PR DESCRIPTION
**Pull request by jkriege2**
- datasheet: http://www.ti.com/lit/ds/symlink/lp2951.pdf
- used for LP2951: https://github.com/KiCad/kicad-symbols/pull/564
- remaining Travis errors are due to the thermal vias ... hope I got them right!

2018-04-30 18_48_24-footprint editor no active library
2018-04-30 18_48_14-footprint editor no active library

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
The pad stackup for the exposed pads looks a bit strange could you align it to our normal workflow? (See any other fp with exposed pad/thermal via or the KLC section about pad requirements)

**Comment by evanshultz** [comment]
- As Rene mentioned, the pin 9 stackup is atypical.
- The silk could be a bit different, getting closer on the sides and enclosing the top and bottom.
- The paste on pads 1-8 isn't working out correctly because it cuts in on both sides:
image
- Did you consider using custom pads? That would make the above easier to manage.
- Courtyard is off:
image

Here is my footprint if you want to review and take any part of it:
```
(module Texas_S-PWSON-N8 (layer F.Cu) (tedit 5AF0AD79)
  (descr "8-Lead Plastic WSON, 3x3mm Body, 0.5mm Pitch, S-PWSON-N8, with thermal vias, http://www.ti.com/lit/ds/symlink/lp2951.pdf")
  (tags "DFN 0.5 S-PWSON-N8 thermal vias")
  (solder_mask_margin 0.07)
  (attr smd)
  (fp_text reference REF** (at 0 -2.5) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value Texas_S-PWSON-N8_ThermalVias (at 0 2.5) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start -1.61 1.61) (end -1.61 1.07) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.61 1.07) (end 1.61 1.61) (layer F.SilkS) (width 0.12))
  (fp_line (start 1.61 -1.07) (end 1.61 -1.61) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.61 1.61) (end 1.61 1.61) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.8 -1.61) (end 1.61 -1.61) (layer F.SilkS) (width 0.12))
  (fp_line (start -2.15 1.75) (end 2.15 1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start -2.15 -1.75) (end 2.15 -1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start 2.15 -1.75) (end 2.15 1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start -2.15 -1.75) (end -2.15 1.75) (layer F.CrtYd) (width 0.05))
  (fp_line (start -0.5 -1.5) (end 1.5 -1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.5 -1.5) (end 1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start 1.5 1.5) (end -1.5 1.5) (layer F.Fab) (width 0.1))
  (fp_line (start -1.5 1.5) (end -1.5 -0.5) (layer F.Fab) (width 0.1))
  (fp_line (start -0.5 -1.5) (end -1.5 -0.5) (layer F.Fab) (width 0.1))
  (fp_text user %R (at 0 0) (layer F.Fab)
    (effects (font (size 0.7 0.7) (thickness 0.1)))
  )
  (pad 9 thru_hole circle (at -0.35 0.75) (size 0.45 0.45) (drill 0.3) (layers *.Cu))
  (pad 9 thru_hole circle (at 0.35 0.75) (size 0.45 0.45) (drill 0.3) (layers *.Cu))
  (pad 9 thru_hole circle (at 0.35 -0.75) (size 0.45 0.45) (drill 0.3) (layers *.Cu))
  (pad 9 thru_hole circle (at -0.35 -0.75) (size 0.45 0.45) (drill 0.3) (layers *.Cu))
  (pad 9 thru_hole circle (at 0 0) (size 0.45 0.45) (drill 0.3) (layers *.Cu))
  (pad 9 smd rect (at 0 0) (size 1.2 2) (layers F.Cu F.Mask))
  (pad 9 smd rect (at 0 0) (size 1.2 2) (layers B.Cu))
  (pad "" smd rect (at 0 0.525) (size 1 0.85) (layers F.Paste))
  (pad "" smd rect (at 0 -0.525) (size 1 0.85) (layers F.Paste))
  (pad 1 smd custom (at -1.09 -0.75) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy -0.81 0.14) (xy -0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (pad 2 smd custom (at -1.09 -0.25) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy -0.81 0.14) (xy -0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (pad 3 smd custom (at -1.09 0.25) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy -0.81 0.14) (xy -0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (pad 4 smd custom (at -1.09 0.75) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy -0.81 0.14) (xy -0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (pad 5 smd custom (at 1.09 0.75) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy 0.81 0.14) (xy 0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (pad 6 smd custom (at 1.09 0.25) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy 0.81 0.14) (xy 0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (pad 7 smd custom (at 1.09 -0.25) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy 0.81 0.14) (xy 0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (pad 8 smd custom (at 1.09 -0.75) (size 0.28 0.28) (layers F.Cu F.Paste F.Mask)
    (solder_paste_margin -0.05) (zone_connect 0)
    (options (clearance outline) (anchor circle))
    (primitives
      (gr_poly (pts
         (xy 0 0.14) (xy 0.81 0.14) (xy 0.81 -0.14) (xy 0 -0.14)) (width 0))
    ))
  (model ${KISYS3DMOD}/Package_SON.3dshapes/Texas_S-PWSON-N8.wrl
    (at (xyz 0 0 0))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)
```

**Comment by evanshultz** [comment]
One more thing: One keyword is "DFN" but this is a SON package.

**Comment by poeschlr** [comment]
Footprints like these can now be generated with my footprint generators. 

I would also advice against this form of pads. (IPC discourages them) Use rounded rectangle pads instead.

**Comment by poeschlr** [comment]
@jkriege2 and @evanshultz i assigned my self to this as i plan to go through currently open pull requests that can be scripted sometime soon. Would any of you object for me adding this to the script?

**Comment by evanshultz** [comment]
Absolutely not. :)

**Pull request closed without merging**
