### PR TITLE
Add vertical RJ-45 connector On-Shore PJ012-8P8CX

### PR DESCRIPTION
**Pull request by cpresser**
Add vertical RJ-45 connector On-Shore PJ012-8P8CX

------------

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
http://www.on-shore.com/wp-content/uploads/2015/09/PJ012-8P8CX.pdf
- [x] An example screenshot image is very helpful 
https://imgur.com/a/yGlUDlq
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
Nope, not there yet.
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Pleas sign the license agreement, add a screenshot of the footprint to the conversation, provide a datasheet link

**Comment by cpresser** [comment]
Somehow I seem unable to sign the CLA. Most likely since the email-address first used for the commit was not the same as the one used for my github account.
I did change the email-address in the commit, but that does not seem to work.
Most likely I will close this PR and make a new one with the same content, but correct email-address.

Datasheet-Link and screenshot are in the first post.

**Comment by poeschlr** [comment]
you can setup your mail adress now and use commit --amend followed by push --force to get it updated here.
Or you make a new pull request
Or you could add the used mail adress to your github account (not sure if that works)

**Comment by cpresser** [comment]
I did the "commit --amend --reset-author" with force-push. Thats where we are now.
So I will just do a new PR.

**Pull request closed without merging**
