### PR TITLE
Tdk inductor

### PR DESCRIPTION
**Pull request by Misca1234**
Example datasheet https://product.tdk.com/info/en/catalog/datasheets/inductor_automotive_power_slf10145-h_en.pdf

This push is replacing the push in 
https://github.com/KiCad/kicad-footprints/pull/352

It is script based, where data is in a .yml file

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1021

Foot print script push 
https://github.com/pointhi/kicad-footprint-generator/pull/201

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Just a question here without a real review: Should these have a notch in fab and silk? 
image

**Comment by Misca1234** [comment]
Jee, I need to modify that

**Comment by Misca1234** [comment]
Fixed the corners

**Comment by poeschlr** [comment]
The notch and rounded corners are not dimensioned in the linked datasheet. Where did you get their dimensions from?

**Comment by Misca1234** [comment]
The notch I used 0.9 mm and the rounded corner was artistic freedom

**Comment by poeschlr** [comment]
In that case a simple rectangle might be a better choice. If we include notches and rounded corners in the outline then users will expect them to have the correct size. Especially as your courtyard follows the outline this closely.

**Comment by Misca1234** [comment]
Ok, I change them to be rectangle then

**Comment by Misca1234** [comment]
The corners are now 90 degree

bild

bild

updated script push is here

**Comment by poeschlr** [comment]
Thanks and sorry about forgetting this for so long.

**Pull request merged**
