### PR TITLE
New LED footprint 5381 series VCC

### PR DESCRIPTION
**Pull request by ferdymercury**
https://vcclite.com/wp-content/uploads/wpallimport/files/files/5381Series.pdf
http://static.vcclite.com/pdf/Mounting%20Hole%20Pattern%202.pdf

------------

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

You need to change the following

Filename should be named 
LED_VCCLite_5381_6.1x6.1mm.kicad_mod

3D model name
${KISYS3DMOD}/LED_THT.3dshapes/LED_VCCLite_5381_6.1x6.1mm.wrl

In general cases you could use 
(see http://kicad-pcb.org/libraries/klc/ for exception)
F,Fab should be 0.1 thick
F.silk 0.12 thick, distance from F.Fab 0.13
F.Ycrtd 0.05 thick distance from F.Fab 0.25

F.Fab should be the physical outline of the component
F.Silk should follow F.Fab
F.CrtYrd should "include" everything of the components, also those spaces that the manufacture recommend, such as antennas.

Pin 1 should be placed in the "upper left corner"
For THT pin 1 should be in origo

The pin whole can be smaller, like 0.7

In your case your FP should look like something like this

bild

You can use this as a starter

(module LED_CML_5381_6.1x6.1mm (layer F.Cu) (tedit 5BCEABD8)
  (descr "LED CML https://vcclite.com/wp-content/uploads/wpallimport/files/files/5381Series.pdf http://static.vcclite.com/pdf/Mounting%20Hole%20Pattern%202.pdf")
  (tags "5381 Series LED ")
  (fp_text reference D1 (at -1 -3) (layer F.SilkS)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value LED_VCCLite_5381_6.1x6.1mm (at 1.27 6) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start -2.03 -2.03) (end 4.57 -2.03) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4.57 4.57) (end -2.03 4.57) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4.57 -2.03) (end 4.57 4.57) (layer F.CrtYd) (width 0.05))
  (fp_line (start 4.32 4.32) (end 4.32 -1.78) (layer F.Fab) (width 0.1))
  (fp_line (start 4.32 -1.78) (end -1.78 -1.78) (layer F.Fab) (width 0.1))
  (fp_line (start 4.32 4.32) (end -1.78 4.32) (layer F.Fab) (width 0.1))
  (fp_line (start -1.78 -1.78) (end -1.78 -1.4) (layer F.Fab) (width 0.1))
  (fp_line (start -1.78 4.32) (end -1.78 3.94) (layer F.Fab) (width 0.1))
  (fp_line (start -1.4 -1.13) (end -1.4 -0.51) (layer F.Fab) (width 0.1))
  (fp_line (start -1.4 3.67) (end -1.4 3.05) (layer F.Fab) (width 0.1))
  (fp_line (start -1.78 -1.4) (end -1.4 -1.13) (layer F.Fab) (width 0.1))
  (fp_line (start -1.4 3.67) (end -1.78 3.94) (layer F.Fab) (width 0.1))
  (fp_arc (start 1.27 1.27) (end -1.4 -0.51) (angle -67.4) (layer F.Fab) (width 0.1))
  (fp_line (start -1.91 -1.91) (end 4.45 -1.91) (layer F.SilkS) (width 0.12))
  (fp_line (start 4.45 -1.91) (end 4.45 4.45) (layer F.SilkS) (width 0.12))
  (fp_line (start 4.45 4.45) (end -1.91 4.45) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.91 4.45) (end -1.91 3.87) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.91 3.87) (end -1.53 3.61) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.53 3.61) (end -1.53 3.07) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.91 -1.91) (end -1.91 -1.33) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.91 -1.33) (end -1.54 -1.07) (layer F.SilkS) (width 0.12))
  (fp_line (start -1.53 -1.07) (end -1.53 -0.53) (layer F.SilkS) (width 0.12))
  (fp_arc (start 1.27 1.27) (end -1.53 -0.53) (angle -64.6) (layer F.SilkS) (width 0.12))
  (fp_arc (start 1.27 1.27) (end -2.03 0.14) (angle -37.44523623) (layer F.CrtYd) (width 0.05))
  (fp_line (start -2.03 -2.03) (end -2.03 0.14) (layer F.CrtYd) (width 0.05))
  (fp_line (start -2.03 4.57) (end -2.03 2.4) (layer F.CrtYd) (width 0.05))
  (pad 1 thru_hole rect (at 0 0 270) (size 1.5 1.5) (drill 0.7) (layers *.Cu *.Mask))
  (pad 2 thru_hole circle (at 2.54 2.54 270) (size 1.5 1.5) (drill 0.7) (layers *.Cu *.Mask))
  (model ${KISYS3DMOD}/LED_THT.3dshapes/LED_VCCLite_5381_6.1x6.1mm.wrl
    (offset (xyz -0.909 -3.522 -2.4))
    (scale (xyz 1 1 1))
    (rotate (xyz 0 0 0))
  )
)

**Comment by ferdymercury** [comment]
Thanks for the example. I amended the file according to your suggestions. It passes now the Travis check.

**Comment by ferdymercury** [comment]
image

**Comment by Misca1234** [comment]
Looks good, just a question, why did you named it 
LED_VCCLite_5381_6.35x6.35mm.kicad_mod ?
The dimension of it is (rounded) 6.1x6.1 ?

**Comment by ferdymercury** [comment]
I think that the datasheet contains a mistake, because the manufacturer 3D model reflects an exact size of 6.35mmx6.35mm, see step file above.

I do not know how to design .wrl files. (I only work with Autodesk Inventor.)

**Comment by ferdymercury** [comment]
I will contact VCCLite.

I thought it is better to have just one footprint named 5381 for all four LED variants?
image

Is there a way to add several 3D models for the same footprint?

**Comment by Misca1234** [comment]
> Is there a way to add several 3D models for the same footprint?
No, that is the issue, it is one to one relationship

here is the example of the red variant

bild

**Comment by ferdymercury** [comment]
3D model looks nice, thanks. I have created four footprints of them because sometimes I use several led colors in the same board, and it might be useful to see in the 3D view which color led is placed where. I think it is enough with 4 footprints that contain the 4 different colors. The rest are just variants in the intensity, etc.

**Comment by ferdymercury** [comment]
I did not get an answer from vcclite yet, but I just measured the LED in my PCB with high precision calliper.

It is clearly 0.25'' as in the 3D STEP file. So the 0.24'' stated in the datasheet are wrong.

image

**Comment by Misca1234** [comment]
Lets go with that, let me create 3D models first

**Comment by Misca1234** [comment]
3D model push 
https://github.com/KiCad/kicad-packages3D/pull/425

**Comment by Misca1234** [comment]
Thx

**Pull request merged**
