### PR TITLE
Add DirectFET MC

### PR DESCRIPTION
**Pull request by chschlue**
Add DirectFET MC

https://www.infineon.com/dgdl/Infineon-AN-1035-ApplicationNotes-v29_01-EN.pdf?fileId=5546d462533600a40153559159020f76#page=37

DirectFET_MC

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
The "wings" on the side are 0.5mm wide but should be 0.4mm wide. Maybe the doc was updated or it's an error? I'll stop here on the medium can ones as I assume you'll update all of them and then I can continue on. If you would like to proceed another way please let me know.
image

**Comment by chschlue** [comment]
I'm on it

**Comment by chschlue** [comment]
@evanshultz ping

**Comment by evanshultz** [comment]
@chschlue 
The overall width was correct before, only the wing width was wrong. The outer vertical fab lines should go back to +/-3.15mm and the wings should then lay at +/-2.75mm. Or am I mistaken?

**Comment by chschlue** [comment]
@evanshultz 
No, you're not...

**Comment by chschlue** [comment]
@evanshultz ping

**Comment by evanshultz** [comment]
Yay!

**Pull request merged**
