### PR TITLE
Adding SOT-457T / SC-95 footprint

### PR DESCRIPTION
**Pull request by persus**
*Replace this line with your commit message! Please provide a description of your pull request*

---

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by persus** [comment]
My source of specs for this footprint:
https://www.mouser.de/datasheet/2/348/qs6k21-e-1139119.pdf

**Comment by chschlue** [comment]
Please don't push unrelated FPs.

**Comment by poeschlr** [comment]
@persus make one branch per pull request. That branch only contains the finished product (before review of course). Only requests made during the review should then be pushed to that branch.

**Comment by persus** [comment]
I will do as requested. Sorry for any inconvenience.

**Pull request closed without merging**
