### PR TITLE
Correct JST MPNs

### LINKED ISSUE #911: JST connectors have wrong PN
The EH series MPNs are shown in [the datasheet](http://www.jst-mfg.com/product/pdf/eng/eEH.pdf) here:
image

Here is our current library:
image

Issue 1: Our PNs have a leading zero when the pin count is <10 (`B03B-EH-A` instead of `B3B-EH-A`).

Issue 2: Keywords for the [vertical 3 pin header](https://github.com/KiCad/kicad-footprints/blob/master/Connector_JST.pretty/JST_EH_B03B-EH-A_1x03_P2.50mm_Vertical.kicad_mod) are `connector JST EH side entry`. The term "side entry" is no longer used in our library and also it's wrong (the vertical and horizontal footprint descriptions should be swapped).

These might apply to other series of JST connectors as well.

### PR DESCRIPTION
**Pull request by evanshultz**
Fixes #911

This all started from https://github.com/KiCad/kicad-footprints/issues/1141 and I documented the first couple issues at https://github.com/KiCad/kicad-footprints/issues/911. I've now looked at all JST connector footprints and fixed only the errors in MPN and make other non-breaking updates (fixed keywords, etc.).

General single-row connectors:
- Changed "side entry" to "horizontal" and "top entry" to "vertical" in keywords

ACH (http://www.jst-mfg.com/product/pdf/eng/eACH.pdf):
- MPN started with "BBM" and should be "BM"

EH (http://www.jst-mfg.com/product/pdf/eng/eEH.pdf):
- When the pin count is <10 there is no leading zero in the MPN
- There is no 16 pin version

J2100 (http://www.jst-mfg.com/product/pdf/eng/eJFA-J2000.pdf, page 7):
- Keying was not in the footprint name; this is unclear (and affects 3D models) so could somebody check me on this?
- Changed pin numbers a1 through b5 to 1 though 10 (the "Line No" in the datasheet is not related to the pin number)

PH (http://www.jst-mfg.com/product/pdf/eng/ePH.pdf):
- Abstracts away the exact PN for normal vs low insertion force THT headers, but I left it alone

SFH (http://www.jst-mfg.com/product/pdf/eng/eSFH.pdf):
- Corrected MPN

XH (http://www.jst-mfg.com/product/pdf/eng/eXH.pdf):
- When the pin count is <10 there is no leading zero in the MPN
- Removed JST_XH_B11B-XH-AM_1x11_P2.50mm_Vertical (doesn't exist)

ZE (http://www.jst-mfg.com/product/pdf/eng/eZE.pdf):
- For SMT, the top entry was massing the final "T" and the side entry had a final "T" but shouldn't have

The following appear to be OK to be in footprint naming, so just keyword updates: AUH, GH, JWPF, LEA, NV, PH, SHL, SH, SUR, VH, XAG

I used Python 3.7.0.

The number of additions and deletions seems odd to me, but I'm quite sure I was careful with only updating the changed files so I think this is correct.

@poeschlr
Would you be willing to correct the EH and XH 3D models? Those are the only ones at https://github.com/KiCad/kicad-packages3D/tree/master/Connector_JST.3dshapes that are affected and it looks like you submitted the existing files. Since you're not busy with anything else I hope that's OK. :)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Script update is at https://github.com/pointhi/kicad-footprint-generator/pull/256.

Travis shows a red 'x' above but the Details page is all green that I can see. Am I doing something wrong? Maybe the quantity of file changes is too great for Travis to handle and it bails?

**Comment by poeschlr** [comment]
The travis error comes from the library table check. Looks like i missed the problem in the pull request i merged.

**Comment by poeschlr** [comment]
At least JST EH,PH and XH also have 3d models in our lib. Meaning you would need to also update these scripts and the 3d models in our lib.

**Comment by evanshultz** [comment]
@poeschlr 
Is there a fix that's needed for the table check?

Would you be willing to do the 3D models? Or @Shackmeister or @Misca1234 ?

**Comment by poeschlr** [comment]
The table stuff is already fixed in a pull request of mine.

**Comment by evanshultz** [comment]
Thanks, I looked but didn't catch it right away. All is green now with Travis.

**Comment by poeschlr** [comment]
Thanks, with the 3d models now ready this can be merged.

**Pull request merged**
