### PR TITLE
Create Texas_RUK_S-PWQFN-N20_EP_3x3_Pitch0.4mm.kicad_mod

### PR DESCRIPTION
**Pull request by cronJ**
Add Texas Instruments RUK_S package.

http://www.ti.com/lit/ds/symlink/ts3ds10224.pdf#page=31

image

PR for symbol: https://github.com/KiCad/kicad-symbols/pull/2513

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
@chschlue I think this kind of footprint should be scripted, isn't it ? Thanks for your answer, Joel

**Comment by chschlue** [comment]
Yes. It also doesn't look like it needs a manufacturer-specific name. `WQFN-20-1EP...` should be perfectly fine.

**Comment by myfreescalewebpage** [comment]
@cronJ you have to script this footprint according to the previous confirmation of @chschlue using the generator at https://github.com/pointhi/kicad-footprint-generator/. Thanks. Joel

**Comment by cronJ** [comment]
Okay, I understand. So is this PR then getting closed?

**Comment by myfreescalewebpage** [comment]
Thanks. No, you can continue on this PR, it's better to follow the subject. Just generate the footprint with the generator, create PR for the generator, and push the footprint generated on this PR.

**Comment by myfreescalewebpage** [comment]
Can you push here the two footprints (normal and with thermal via) that the script generate for you please ?

**Comment by myfreescalewebpage** [comment]
Thanks, looks great, just need to remove the file "Package_DFN_QFN.pretty/Texas_RUK_S-PWQFN-N20_EP_3x3_Pitch0.4mm.kicad_mod " in this PR.

**Comment by myfreescalewebpage** [comment]
Thanks, no more comment. Merging.

**Pull request merged**
