### PR TITLE
Add QFN-16-1EP_4x4x0.75mm_P0.65mm_EP2.7x2.7mm

### PR DESCRIPTION
**Pull request by jcyrax**
Footprint for https://github.com/KiCad/kicad-symbols/pull/249

https://www.allegromicro.com/~/media/Files/Datasheets/A4403-Datasheet.ashx

Some questions:
1. Do I need to add height 0.75mm to footprint name?
2. I made it following A4403 datasheet, should this footprint be prefixed with Allegro?
3. Is my document link text OK? Or do I add link to datasheet (whole part)?
image
image
image
image
image
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
Hi @jcyrax 
Some comments for your footprint:
 - Height is not in any of the other QFN packages so I would suggest we stick to that
 - Fab lines should be 0.1mm
 - Silk lines should be 0.12mm
 - The Fab REF** should be slightly smaller to fit inside the fab body
 - The default clearance is 0.2mm, the silkscreen is coliding with the mask area.
 - Optional: courtyard can be a made in to a "plus" shape to be smaller and better fit the component

**Comment by jcyrax** [comment]
@Shackmeister I think I fixed all the issues.

image

**Comment by Shackmeister** [comment]
Courtyard is slightly to far from the pads and body :) the clearance should be 0.25mm

**Comment by jcyrax** [comment]
Fixed

**Comment by Shackmeister** [comment]
thanks for the contribution! :D

**Pull request merged**
