### PR TITLE
Fixes for consistency with other footprints

### PR DESCRIPTION
**Pull request by robkam**
was PR #828
mono with circular holes QingPu_WQP-PJ398SM
http://www.qingpu-electronics.com/en/products/WQP-PJ398SM-362.html

mono circular holes qingpu_wqp-pj398sm

### CODE REVIEW

**Comment by robkam** [comment]
one

**Comment by poeschlr** [comment]
Is this still relevant or has some other pull request made this obsolete?

**Comment by robkam** [comment]
> Is this still relevant or has some other pull request made this obsolete?
It's still relevant. Except there was another PR to resolve TN, S, T vs. 2, 1, 3. I didn't follow what was decided.

**Comment by poeschlr** [comment]
As this is an audio connector i would assume the letters are what should be used.

**Comment by robkam** [comment]
With the letters there's no mismatch to the symbols, but the data sheet uses numbers.

**Comment by poeschlr** [comment]
The decision was made to use numbers for this part. This is because we are not prepared to have atomic parts for audio connectors.

**Comment by poeschlr** [comment]
Oh dammit. Sorry i got confused in my last response. We should use letters.

**Comment by poeschlr** [comment]
Thanks

**Comment by robkam** [comment]
Thanks! :-)

**Pull request merged**
