### PR TITLE
Adds a lot of SIP footprints for Traco DC/DC parts

### PR DESCRIPTION
**Pull request by Werni2A**
All footprints are [script](https://github.com/pointhi/kicad-footprint-generator/pull/579) generated.

The corresponding symbols will follow (hopefully) in the near future. I will also use this PR to track the status of symbol PRs:
- [x] [TBA 1](https://github.com/KiCad/kicad-symbols/pull/2879)
- [ ]  TBA 1E
- [ ]  TBA 1HI
- [ ]  TBA 2
- [ ]  TMA
- [ ]  TMAP
- [ ]  TME
- [ ]  TMR 1
- [ ]  TMR 2
- [ ]  TMR 2E
- [ ]  TMR 2WI
- [ ]  TMR 3
- [ ]  TMR 3E
- [ ]  TMR 3HI
- [ ]  TMR 3WI
- [ ]  TMR 6
- [ ]  TMR 6WI
- [ ]  TMR 9WI
- [ ]  TMV
- [ ]  TMV-EN
- [ ]  TMV-HI
- [ ]  TMV 2HI
- [ ]  TMW 2WIN
- [ ]  TRV 1M
- [ ]  TEC 2
- [ ]  TEC 2WI
- [ ]  TEC 3
- [ ]  TEC 3WI
- [ ]  TMH
- [ ]  TRA 3
- [ ]  TEA 1
- [ ]  TEA 1E
- [ ]  TEA 1HI

Todo:
- [x] Datasheets should point to the page with the footprint specification
- [x] Add revision of the datasheet to the description
- [x] Improve description
- [x] Check pin size tolerances
- [ ] Regenerate footprints

Sample image:
image

### CODE REVIEW

**Comment by Werni2A** [comment]
@Franck78 I saw that you were checking on AC/DC converter 3D models. Maybe you are also interested in this PR.

**Comment by Franck78** [comment]
you do the footprints, I do the 3dmodels for them.

**Comment by Werni2A** [comment]
Sounds good but no pressure on you :smile:

**Comment by Franck78** [comment]
@Dominik, I did my part as I said. Some ~140 3dmodels waiting Someone Somewhere In Summertime

**Comment by Werni2A** [comment]
@Franck78 I think you linked the wrong Dominik :sweat_smile: 

140 models are a lot of effort, thank you fort that. Can you link you PR to this one, then everything is together. I think it's also inevitable that I rename some of the footprints and therefore also some 3D models. But at the moment I update my footprint generator script to ease the review, I recon that it will take some more time until the generator is merged and finally the footprints can be reviewed.

**Comment by Franck78** [comment]
wrong Dominik ? No It's your first name.

I'm pretty sure you can use the 3d data input file to generate your footprints. Why bother enter them again.

the PR is waiting here : https://github.com/easyw/kicad-3d-models-in-freecad/pull/390
Probably also some names to fix

**Comment by Werni2A** [comment]
Try to hover over "Dominik" in you link and you will see that this is someone else. But sure I know that you meant me. When you want to link someone you need to use the GitHub username, mine is @Werni2A . You can also name me with my first name without the "@" sign then it's fine but I won't get notified.

I already entered all the footprint parameters but as we wrote down the parameters independently it's an easy way to check if there are still some issues. This is on my todo list when the generator is merged.

**Comment by Franck78** [comment]
Hello @Werni2A ,

Easyw merged my patch for generating the 3dmodels converters. You can generate all of them for testing with your footprints.
You probably will find some incorrect names, with the 'xxxx' wildcards. 

Also have a thought for this poor little guy when your will push something
https://github.com/KiCad/kicad-packages3D/issues/600

Franck

**Pull request closed without merging**
