### PR TITLE
Add scripted WDFN-12-1ep, 3x3mm footprint (replace #643)

### PR DESCRIPTION
**Pull request by poeschlr**
Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/149
replaces #643

config:
``` yaml
WDFN-12-1EP_3x3mm_P0.45mm_EP1.7x2.5mm:
  device_type: 'WDFN'
  size_source: 'https://www.diodes.com/assets/Datasheets/PAM2306.pdf'
  ipc_class: 'qfn' # 'qfn_pull_back'
  body_size_x:
    minimum: 2.95
    maximum: 3.05
  body_size_y:
    minimum: 2.95
    maximum: 3.05
  lead_width_min: 0.15
  lead_width_max: 0.25
  lead_len_min: 0.35
  lead_len_max: 0.45


  EP_size_x: 1.7
  EP_size_y: 2.5
  EP_num_paste_pads: [2, 2]

  pitch: 0.45
  num_pins_x: 0
  num_pins_y: 6
```

Screenshot (pad clearance shown as 0.2mm, only for screenshot.):
screenshot from 2018-07-24 00-55-03

### CODE REVIEW

**Comment by Misca1234** [comment]
Is this correct ?
According to 
https://www.diodes.com/assets/Datasheets/PAM2306.pdf

The suggest pad layout says 1mm width
(bottom page 14)

**Comment by poeschlr** [comment]
I used IPC formulas and suggested fillet sizes. This is not intented as a specialized footprint that works for one part but a general WDFN footprint.
My guess is that their suggestion comes from an older standard (older standards had larger fillet sizes. The datasheet is from 2012. Back then IPC-7351 just came out so they might have even used the suggestions that came before that.)

**Comment by jneiva08** [comment]
@poeschlr 
the script do account for different lengths for horizontal/vertical pins sizes?

**Comment by poeschlr** [comment]
I assume you ask because of the other PR of yours. (https://github.com/KiCad/kicad-footprints/pull/717) Sadly i do not yet support that in my script. So at this point in time this one will need to stay hand crafted.

**Pull request merged**
