### PR TITLE
Add STM32 Blue Pill footprint

### PR DESCRIPTION
**Pull request by jeanthom**
Hi!

This is my STM32 Blue Pill footprint submission. This footprint is related to this symbol PR : https://github.com/KiCad/kicad-symbols/pull/1121

STM32 bluepill
Footprint printed on paper

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
I looked at the screenshot (So if you do not show all layers then my assessment might be wrong)

- [ ] it seems you are missing the fab layer outline (should represent the nominal body outline. Silk must be outside of that)
- [ ] You might also be missing the courtyard outline (clearance to nominal body size must be 0.25mm but rounded to nearest 0.01mm grid point)
- [ ] Pad 1 should be a different shape to the other ones to make it easy to find it. I suggest the use of a rounded rectangle with 25% radius ratio (maximum 0.25mm radius).
- [ ] Move the reference and value fields outside the footprint. Add a second reference on the fab layer. (That one should be centered on the footprint)
- [ ] The footprint might need rotating. This is assuming pin 1 is currently at the footprint origin. (Pin 1 should be nearest the top left corner. -> so rotating 90 degree in clockwise direction might be in order.)
- [ ] Check the 3d model settings. The path must start with the environment variable KISYS3DMOD, the 3d model library name must agree with the footprint library name and the 3d model name must agree with the footprint name.

I have not yet checked any dimensions. Could you add a datasheet link to the pull request description such that this task is made easier?

**Comment by jeanthom** [comment]
The official documentation for this dev board is available here : http://www.vcc-gnd.com/cp/stm32hxb/stm32f1xxhexinban/ (chinese)

Inside STM32F103C8T6核心板硬件资料.rar you can find this mechanical drawing :
default

I updated the footprint to metter match the manufacturer spec.

bluepill

I haven't sorted the 3D model issues yet.

**Comment by jeanthom** [comment]
3D model path issues sorted :)

**Comment by poeschlr** [comment]
Outline on silk layer is missing
pin 1 markers on both silk and fab layer are missing
Dimensions look ok.

**Comment by lorem-ipsum** [comment]
As I am planing to use this for a project I used this PR as a basis and added the missing silk screen markers. Also increased the size of the pads a bit as the remaining copper appeared a bit thin. It is currently in [a branch in my repo](https://github.com/lorem-ipsum/kicad-footprints/tree/bluepill). 

@jeanthom I would post it as a new PR so it and the symbol can be merged into the repos. Are you fine with that or do you want to finish it yourself?

**Comment by jeanthom** [comment]
Sure, I'll close this PR right now. Please keep me in touch when you submit your PR!

**Pull request closed without merging**
