### PR TITLE
fixed THT -> SMD and  NXE2 -> NXEx

### PR DESCRIPTION
**Pull request by od83**
Hi,

What I did:
1. remove Converter_DCDC.pretty/Converter_DCDC_muRata_NXE2SxxxxMC_THT.kicad_mod
2. add Converter_DCDC.pretty/Converter_DCDC_muRata_NXExSxxxxMC_SMD.kicad_mod

I did not change the footprint itself, only (file)name and description.

Why I did it:
a. The footprint is (and was) a SMD type, not THT type.
b. The footprint can also be used for the NXE1S Series of Murata's 1W DC/DC converters

Reference:
[NXE1 Series](http://power.murata.com/data/power/ncl/kdc_nxe1.pdf)
[NXE2 Series](http://power.murata.com/data/power/ncl/kdc_nxe2.pdf)

Symbol pull request for added NXE1S0x0xMC and changed NXE2SxxxxMC are [here](https://github.com/KiCad/kicad-symbols/pull/2452).

PAD_NXExSxxxxMC_SMD

Best regards,
Oliver
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cpresser** [comment]
This will also need a fix in the `NXE2S0505MC` Symbol

**Comment by rleh** [comment]
I created a pull request for the Symbol: KiCad/kicad-symbols#2567

**Comment by od83** [comment]
Hi @rleh , @cpresser ,
I already committed changes to the NXE2SxxxxMC Symbol in this pull request:
[KiCad/kicad-symbols#2452](https://github.com/KiCad/kicad-symbols/pull/2452)

The changes I made were
1. adding the NXE1S symbols
and
2. changing the footprint references in existing NXE2S symbols

best regards
Oliver

**Comment by rleh** [comment]
Oh sorry, I didn't find your pull request. I'm going to close mine.

**Comment by od83** [comment]
Yes, I have to admit, the link is a bit hidden in my description and the 
symbols PR title doesn't mention the Series 2 changes I made.

For future PR: would it be better/more convenient for the community if I split 
such commits in multiple PR? I.e. one for NXE1 addition + one for NXE2 
changes.
Also, if I'm creating various new components for a new project , can they all 
be in one PR or should it be one symbol/footprint per PR?

Best regards
Oliver

**Comment by cpresser** [comment]
> Also, if I'm creating various new components for a new project , can they all be in one PR or should it be one symbol/footprint per PR? Best regards Oliver

This is pretty clear from a maintainers perspective: One PR for each component or logical group (for example variants of the same part). For example don't add two different switches into one PR, but you can add a series of MCUs (different footprints) in one PR.

**Comment by cpresser** [comment]
It seems the wrong name came from this issue:
https://github.com/KiCad/kicad-footprints/pull/127#issuecomment-347614800
https://github.com/KiCad/kicad-footprints/pull/127#issuecomment-348448613

---

I found some small things that I would like to see fixed since we are working on this Part anyway:
- [ ] one Silk-Line is slightly crooked 
image
- [ ] The Keepout-Area does not conform to KLC. Perhaps also add a text saying why this is a keepout-area (isolation barrier). See https://kicad-pcb.org/libraries/klc/F4.5/
- [ ] The Origin should be set the pick'n'place origin as shown in the datasheet
- [ ] The Pads are not oriented with rotation 0°. This is not a real KLC rule (https://github.com/KiCad/kicad-website/pull/479), so it is not mandatory to fix it. The solution would be to exchange x/y size and set orientation to 0°.
- [ ] The silkscreen is slightly to close to the pads (by 0.5x silk-line-width): 
image

**Comment by od83** [comment]
I fixed what @cpresser suggested. Please have another look

**Comment by cpresser** [comment]
I gave it another look. The keepout-area looks even better than I imagined.

But unfortunately two of the above points are not perfect yet:
* The p'n'p origin is at 7.52, should be at 7.62. 
* Some of the silk distances are not exactly 0.2mm 
image
 KLC does not mandate those to be exact 0.2mm. But I caught my eye that the spacing on top and bottom of the pad are not identical. Thus, I would like to see it fixed. But its not mandatory. Its above the clearance value and not really important.

**Comment by od83** [comment]
- the pad to silk clearance is the same on all pads now 

image

- the origin is corrected by 0.1mm. Sorry, that slipped.
image

**Comment by cpresser** [comment]
Silk looks good.
Btw, a simple variant to check this is to increase pad-size by 0.4mm.

- [ ] Centering in x-direction is off: 
image 
The same issue can be seen with the pads. I would expect pads 7 & 8 to be symmetrical to the center.

**Comment by od83** [comment]
just pushed the change
image

**Pull request merged**
