### PR TITLE
Inductor_SMD: Add Bourns SRP7028A Shielded Power Inductors Series

### PR DESCRIPTION
**Pull request by gmsotavio**
Datasheet: https://www.bourns.com/docs/product-datasheets/srp7028a.pdf

L_Bourns_SRP7028A_4
L_Bourns_SRP7028A_1
L_Bourns_SRP7028A_2
L_Bourns_SRP7028A_3
L_Bourns_SRP7028A_5
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Should I add the body dimensions as part of naming as done in https://github.com/KiCad/kicad-footprints/pull/1749 ?

**Comment by poeschlr** [comment]
Yes i think adding body size to the name would make sense.

**Comment by gmsotavio** [comment]
I changed the courtyard style from rectangular to contoured and appended the body dimensions to footprint name.

image

**Comment by gmsotavio** [comment]
I forget to change the 3d shape name.

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
