### PR TITLE
Added Kionix_LGA-12_2x2mm_P0.5mm_LayoutBorder2x4y.

### PR DESCRIPTION
**Pull request by cederom**
Footprint for KXTJ3-1057 3-Axis Accelerometer.
Symbol added here: https://github.com/KiCad/kicad-symbols/pull/621.
Specifications:
http://kionixfs.kionix.com/en/datasheet/KXTJ3-1057-Specifications-Rev-5.0.pdf
http://kionixfs.kionix.com/en/document/TN008-PCB-Design-Guidelines-for-2x2-LGA-Sensors.pdf

Generated with https://github.com/pointhi/kicad-footprint-generator.
Source:
```
Kionix_LGA-12_2x2x0.9mm_P0.35x0.375mm:⏎
  device_type: 'LGA'⏎
  size_source: 'http://kionixfs.kionix.com/en/document/TN008-PCB-Design-Guidelines-for-2x2-LGA-Sensors.pdf#page=4'⏎   library: 'Package_LGA'⏎
  manufacturer: 'Kionix'⏎
  use_name_format: 'LGA'⏎
  #ipc_density: 'least'⏎
  ipc_class: 'qfn_pull_back'⏎
  body_size_x:⏎
    nominal: 2.0⏎
    tolerance: 0.05⏎
  body_size_y:⏎
    nominal: 2.0⏎
    tolerance: 0.05⏎
  overall_height: 0.9⏎
  lead_width:⏎
    nominal: 0.25⏎
    tolerance: 0.05⏎
  lead_len:⏎
    nominal: 0.275⏎
    tolerance: 0.05⏎
  lead_to_edge:⏎
    nominal: 0.1⏎
  pitch: 0.5⏎
  num_pins_x: 2⏎
  num_pins_y: 4⏎
```

image

Signed-off-by: Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [X] Give a reason behind any intentional library convention rule violation (NONE).

### CODE REVIEW

**Comment by evanshultz** [comment]
Thanks for submitting this footprint!

I have left some comments in the script PR. Which is https://github.com/pointhi/kicad-footprint-generator/pull/634.

**Comment by cederom** [comment]
Okay, replied. Please note that resulting footprint is almost exactly the same as existing `LGA-12_2x2mm_P0.5mm` except shape of the pads is rounded. This work already cost me some days.

**Comment by evanshultz** [comment]
Something will need to be done with this footprint. Please select an option I outlined at https://github.com/pointhi/kicad-footprint-generator/pull/634 and proceed whichever way you like.

I believe the symbol is otherwise ready, and we have less than a day before closing this repo and moving to GitLab. Hopefully you are available to wrap this up.

**Comment by cederom** [comment]
Mkay, will take the first way - update the footprint generator yaml then update geberated footpint. Change footprint dimensions to exactly match the comopnent sizes as requested.

**Comment by cederom** [comment]
Pads are now resized to exactly match the size of a component as you requested @evanshultz .

Again. The Kionix's PCB Design Guidelines [1] does not define a footprint for this component. However page 4/9 says:
> Using  a  0.0635  mm  solder  mask  around  each  pad  (pad  dimension  +  0.1270  mm),  the minimum solder mask web is 0.1227mm between I/O pads.

Which I took into account with my previous commit, and it turned out to be existing LGA-12 component in a release footprint library.

[1] http://kionixfs.kionix.com/en/document/TN008-PCB-Design-Guidelines-for-2x2-LGA-Sensors.pdf

**Comment by cederom** [comment]
image

**Comment by evanshultz** [comment]
The pad size does not match the existing LGA-12 footprint. But it might still work. LGAs usually self-center rather well in my experience. And neither does the silk, but both ways are probably fine.

The description doesn't quite make sense since this footprint was hand-modified, but better to get it done since the footprint itself looks OK.

BTW, I dug around a bit and found that the existing LGA-12 footprint was added at https://github.com/KiCad/Housings_LGA.pretty/pull/2 for https://www.st.com/content/ccc/resource/technical/document/datasheet/c9/16/f2/79/ca/31/47/89/DM00096789.pdf/files/DM00096789.pdf/jcr:content/translations/en.DM00096789.pdf. Indeed, the package does look the same. However, https://www.st.com/content/ccc/resource/technical/document/technical_note/73/17/9c/16/dd/96/4a/01/CD00134799.pdf/files/CD00134799.pdf/jcr:content/translations/en.CD00134799.pdf has specific requirements for the footprint design and probably that one should have a manufacturer-specific name.

**Pull request merged**
