### PR TITLE
Update murata naming to Murata

### LINKED ISSUE #545: Murata footprints incorrectly named "muRata"
We have a variety of footprints for parts made by [Murata](https://www.murata.com/).  Some include the company's name in the footprint name.  Of these, we have some that capitalize it as `muRata`, and others that capitalize it as `Murata`.  We should reconcile these before the 5.0 freeze begins.

In the company's logo, it's capitalized `muRata`.  However, in ordinary text, they seem to be quite consistent with `Murata`, so I suggest we use the latter.

### PR DESCRIPTION
**Pull request by JacobEFO**
Fix murata naming to Murata as per #545

Namings have been updated for the following folders:
- [X] Converter_DCDC
- [X] Crystial
- [X] Inductor_THT

This appears to be everything for now.

**Other PRs:**
kicad-packages3D: https://github.com/KiCad/kicad-packages3D/pull/595
kicad-3d-models-in-freecad: https://github.com/easyw/kicad-3d-models-in-freecad/pull/309
kicad-footprint-generator: https://github.com/pointhi/kicad-footprint-generator/pull/394

**Known issues (other PR):**
The packages3D PR has some issues with Git/GitHub seeing the names are in fact changed. They show up with the correct naming "Murata" instead of "muRata" and "muRATA" on my own branch and fork.

Apparently this PR has some issues with actually seeing the filenames are changed as well, causing Travis errors.

### CODE REVIEW

**Comment by poeschlr** [comment]
The filenames would need updating to the new footprint names. If you indeed see them changed locally then maybe your git client does not properly handle this (windows does not care about filename capitalization)

**Review by antoniovazquezblanco — APPROVED** [review]
This looks good to me :)

Can you confirm @poeschlr ?

**Comment by poeschlr** [comment]
The footprints look good but there are symbols pointing to them so they need updating of their footprint fields. There is however no symbol pull request linked here so i assume this is not done.

**Comment by JacobEFO** [comment]
Hi @poeschlr 

There's a symbol PR [here](https://github.com/KiCad/kicad-symbols/pull/2508).

**Comment by myfreescalewebpage** [comment]
@JacobEFO I have checked all the Murata footprints. I have found some issues (not introduced by yourself) than can be easily corrected:

Converter_DCDC_Murata_NMAxxxxSC_THT:
- [ ] In the description and in the tags: "muRata" => "Murata"

Resonator_SMD_Murata_CDSCB-2Pin_4.5x2.0mm_HandSoldering:
- [ ] The 3D models should be `${KISYS3DMOD}/Crystal.3dshapes/Resonator_SMD_Murata_CDSCB-2Pin_4.5x2.0mm.wrl`

Resonator_SMD_Murata_SFECV-3Pin_6.9x2.9mm_HandSoldering
- [ ] The 3D model should be `${KISYS3DMOD}/Crystal.3dshapes/Resonator_SMD_Murata_SFECV-3Pin_6.9x2.9mm.wrl`

Resonator_SMD_Murata_SFSKA-3Pin_7.9x3.8mm_HandSoldering
- [ ] The 3D model should be `${KISYS3DMOD}/Crystal.3dshapes/Resonator_SMD_Murata_SFSKA-3Pin_7.9x3.8mm.wrl`

Resonator_SMD_Murata_TPSKA-3Pin_7.9x3.8mm_HandSoldering
- [ ] The 3D model should be `${KISYS3DMOD}/Crystal.3dshapes/Resonator_SMD_Murata_TPSKA-3Pin_7.9x3.8mm.wrl`

Joel

**Comment by JacobEFO** [comment]
@myfreescalewebpage Have a look here, I had to do a merge where one file had to be removed (was renamed on this upstream).
I reckon the changes you asked for are also included.

**Comment by myfreescalewebpage** [comment]
@JacobEFO thanks, seems the 3 last points about the 3D models are not included, if you can do it

**Comment by JacobEFO** [comment]
Hey @myfreescalewebpage I am little unsure why the last 3 points didn't make it. I did it manually through the footprint editor, but somehow it didn't actually save the settings.

**Comment by myfreescalewebpage** [comment]
@JacobEFO this is because the HandSoldering have to be removed, I think this is normal to do it manually.
Thanks for the energy you spent on the murata subject ! Merging now this PR.

**Pull request merged**
