### PR TITLE
added Wuerth_61400826021USB connector and fixed minor issues

### PR DESCRIPTION
**Pull request by Shackmeister**
changed all "manf-mpn" to "manf_mpn"
removed all generic footprints

Datasheet: http://katalog.we-online.de/em/datasheet/61400826021.pdf
screenshot:
wuerth_usb

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
made a new courtyard
wuerth_usb

**Comment by poeschlr** [comment]
Is the courtyard a closed shape? I fear that because of the arcs there are some holes in the courtyard "polygon".
Open courtyard drawings might create problems once DRC checks courtyard violations.
So it might be better to approximate the arc by part of a rectangle or octagon.

My suggestions: 
36383215-c74c7136-158b-11e8-9bfa-7afa9386be99

I would be ok with the red solution. I don't think any more is necessary as i doubt one could place any other part in the space "freed up" by drawing a closer fitting courtyard shape. (If you really want a closer fitting shape you could go to something like my green shape.)

**Comment by Shackmeister** [comment]
wuerth_usb

**Comment by Shackmeister** [comment]
@poeschlr can you check it again? :)

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
