### PR TITLE
Add Molex SL 171971

### PR DESCRIPTION
**Pull request by waschhauser**
Molex SL Connector overview:
https://www.molex.com/pdm_docs/ps/1719710000-PS-000.pdf

Datasheet Molex SL 171971:
https://www.molex.com/pdm_docs/sd/1719710103_sd.pdf
https://www.molex.com/webdocs/datasheets/pdf/en-us/1719710103_PCB_HEADERS.pdf

FPG PR:
https://github.com/pointhi/kicad-footprint-generator/pull/442

image

From Molex 3D model

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
It is really a bit strange which footprints you decide to script. This for example is a prime example for something that really benefits from a script as there is a full series of parts and very similar scripts already exist (low effort for a lot of result.) Just to be clear a script is not a requirement here just something i noticed.

**Comment by poeschlr** [comment]
please make a pull request on the script side and link to it. (I kind of missed that you have a script for this in my last response.)

**Comment by waschhauser** [comment]
@poeschlr I overworked the footprint and created a pull request for the footprint generator script.

**Comment by poeschlr** [comment]
A few dimensions are not correct (I checked the 7 circuit version)

Screenshot from 2019-10-13 19-30-09

**Comment by waschhauser** [comment]
@poeschlr thank you for the review. Which tool do you use for the review of the footprints (dimensions check)? Maybe I can use it too the check my modifications.

**Comment by poeschlr** [comment]
https://forum.kicad.info/t/how-to-check-footprint-correctness/9279

**Comment by waschhauser** [comment]
@poeschlr thank you very much. I will try to fix the bugs until end of the week.

**Comment by waschhauser** [comment]
Hi @poeschlr,

I fixed the length (A) of the connector.

From your review screenshot, I think only the the red highlighted dimmesions are wrong.
The orange one, I think it's just inaccuracy from FreeCAD.

As mentioned the length A of the connector is fixed.

But the other one, I think it's not on error.
The following picture shows the 7 circuit version from the molex 3D model:

image

The length of the thing that is responsible of fix the wires is allways 7.62mm (except for the 2 circuit version). B seams to be the distance between the first and the last pin. For the 7 circuit version, B = 15.24 = (7 - 1) * 2.54

image

image

That's why I thinkt that B is not relevant for the footprint.

**Comment by poeschlr** [comment]
Looks good now, thanks

**Pull request merged**
