### PR TITLE
Add the Laird BMI-S-230-F RF shield

### PR DESCRIPTION
**Pull request by dlharmon**
Add the Laird BMI-S-230-F RF Shield

https://media.digikey.com/pdf/Data%20Sheets/Laird%20Technologies/BMI-S-230-F_Dwg.pdf

Screenshot from 2019-03-10 12-25-05

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by dlharmon** [comment]
This is missing the inner courtyard lines the other BMI-S-xxx-F parts have causing DRC to fail for any components inside. There may have been some manual edits on this family after the generator. I'll try to fix the generator and update this.

**Comment by dlharmon** [comment]
This should be good to go now.

It's script generated, https://github.com/pointhi/kicad-footprint-generator/pull/310

If desired, I can create another commit updating the other parts in this family using the generator which should now be KLC compliant. I believe these were modified after generation.

**Comment by poeschlr** [comment]
The footprint is too large in x direction.
Screenshot from 2019-06-05 21-49-09

**Comment by dlharmon** [comment]
Screenshot from 2019-06-17 14-45-31

It looks like Travis CI is now failing due to the inside and outside courtyard rectangles.

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
