### PR TITLE
Add DirectFET SA

### PR DESCRIPTION
**Pull request by chschlue**
Add DirectFET SA

https://www.infineon.com/dgdl/Infineon-AN-1035-ApplicationNotes-v29_01-EN.pdf?fileId=5546d462533600a40153559159020f76#page=22

DirectFET_SA

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Drain pads should be +/-2.455mm (to close by 0.005mm).
1. Same deal as before with "S" package height.

image

**Comment by chschlue** [comment]
1. Look again. SA drain to drain is either 1.83+1.25+1.83=4.91 or 1.65+1.60+1.65=4.9. Impossible to get this one right... 
I prefer 4.9mm, matching all other S-Packages.

**Comment by evanshultz** [comment]
1. LOL. I will ping Infineon about this error too. I see 4.9mm, 4.91mm, and 4.901mm shown in the app note...

**Comment by evanshultz** [comment]
2. Looks good. Let's get this merged and deal with anything else later.

**Pull request merged**
