### PR TITLE
Bourns SDR1806

### PR DESCRIPTION
**Pull request by bdm310**
Added the Bourns SDR1806 series footprint to Inductor_SMD.
https://www.bourns.com/docs/Product-Datasheets/SDR1806.pdf

image

https://github.com/KiCad/kicad-packages3D/pull/305

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
hi @bdm310 

Can you please export your model using Kicad Stepup?
if you could be willing to, it would be great with some copper on where the coil should be :)

**Comment by poeschlr** [comment]
The courtyard clearance should be 0.25mm
The body length is also not quite right. See annotated dimensioned drawing

screenshot from 2018-05-06 03-38-21

**Comment by bdm310** [comment]
Not sure where my 17.78mm came from and I think I did this before finding the 0.25mm spec in the KLC. I did 14.3+0.05 this time around; I'd say it's better to do the courtyard at max tolerance condition.

**Comment by bdm310** [comment]
I must've done it to the silk and not the body. Updated.

**Comment by Shackmeister** [comment]
getting closer :)
please change silkscreen width to 0.12mm instead of 0.15mm
also please move the REF and Value closer to the courtyard :)

**Comment by bdm310** [comment]
I wasn't consistent (one of the arcs was 0.12) so this would've needed an update anyway but it may be helpful to clarify in the KLC that 0.12 should only be deviated from if necessary. The current wording makes it seem relatively loose and I'd call this a "low density" part. It'd also definitely be helpful to include a guideline for where reference designators and values should go.

**Comment by Shackmeister** [comment]
@bdm310 
Thanks for the contribution :)
hope to see more :)

**Pull request merged**
