### PR TITLE
Added DIP-8-16 Footprint

### PR DESCRIPTION
**Pull request by LJJS**
Added a DIP-8-16_W7.62mm_LongPads Footprint:

dip-8-16

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
http://www.experimentalistsanonymous.com/diy/Datasheets/MN3005.pdf
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

Do you have a data sheet to a component that use this foot print?
Did you take a DIP 16 and just removed the pads ?

**Comment by Misca1234** [comment]
ah, sorry, I missed the data sheet link

You now it is an old component when they give an implementation example of a hand drawn pcb :)

@KiCad/librarians 
What do you say about this?
Shall we make it with the scripts that made all other DIP FP (then we will get all variants automatically) ?
Shall it perhaps be renamed to `Panasonic_MN3005_DIP-8-16_W7.62mm_......` ?

**Comment by poeschlr** [comment]
If this can be scripted then i would prefer it to be scripted.

**Comment by Misca1234** [comment]
@LJJS 
Would yo uprefer to get this scripted, if you do not want to do it, I could do an attempt?

**Comment by Misca1234** [comment]
Repalcement push is here
https://github.com/KiCad/kicad-footprints/pull/1352

@LJJS 
I close this push, you can follow the merge push here
https://github.com/KiCad/kicad-footprints/pull/1352

**Pull request closed without merging**
