### PR TITLE
RF_Module: Added a footprint for RF modules IQRF TR-x2DA

### PR DESCRIPTION
**Pull request by Roman3349**
Symbol pull request: https://github.com/KiCad/kicad-symbols/pull/421

Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>

RF_Module: Added a footprint for RF modules IQRF TR-x2DA in the connector IQRF KON-SIM-01

Datasheet: https://iqrf.org/weben/downloads.php?id=337

Bottom view photo:
p_20180326_140811_1
Screenshot: 
snimek obrazovky porizeny 2018-03-26 14-14-46

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Misca1234** [comment]
You need to sign the CLA

**Comment by poeschlr** [comment]
Can you link a datasheet for the "connector"? I would need something with a dimensioned drawing such that we can check the landing pattern dimensions

**Comment by Roman3349** [comment]
@poeschlr Datasheet for the KON-SIM01 connector is [here](http://iqrf.org/weben/downloads.php?id=104).

**Comment by poeschlr** [comment]
I would suggest to use the pin "numbers" as they are shown in the datasheet. (C1...C8 instead of 1...8)

Add pin 1 markers on Silk and on the fab layer.

I assume there might be some sort of area where there should not be any copper feature. 
Normally in the area below the antenna. Sadly this seems to be missing from the datasheet you linked. Is there maybe some sort of application note that specifies some sort of PCB design layout guide?

Are you planning to supply a symbol for this footprint? (If there already is a pull request please link it here)

The pin pitch between C5/C6 and C1/C2 is wrong (is 2.55 should be 2.54)

Some other measurements are also wrong: (Highlighted in the screenshot)
screenshot from 2018-04-23 22-56-40

**Comment by Roman3349** [comment]
@poeschlr Pins were renamed. Measurements should be fixed. Keep out zone for antenna was added. Symbol pull request: KiCad/kicad-symbols#421

**Comment by Ratfink** [comment]
[KLC]: http://kicad-pcb.org/libraries/klc/ "KiCad Library Convention"
[G1.1]: http://kicad-pcb.org/libraries/klc/G1.1/ "Only standard characters are used for naming libraries and components"
[G1.2]: http://kicad-pcb.org/libraries/klc/G1.2/ "Each library is limited to 250 items"
[G1.3]: http://kicad-pcb.org/libraries/klc/G1.3/ "Libraries are organized by functionality"
[G1.4]: http://kicad-pcb.org/libraries/klc/G1.4/ "English language should be used throughout libraries"
[G1.5]: http://kicad-pcb.org/libraries/klc/G1.5/ "Plural naming is to be avoided"
[G1.6]: http://kicad-pcb.org/libraries/klc/G1.6/ "Capitalization conventions"
[G1.7]: http://kicad-pcb.org/libraries/klc/G1.7/ "Library files use Unix style line endings"
[G1.8]: http://kicad-pcb.org/libraries/klc/G1.8/ "Components can only contain features supported in latest stable release"
[G1.9]: http://kicad-pcb.org/libraries/klc/G1.9/ "Dimensional units"
[G2.1]: http://kicad-pcb.org/libraries/klc/G2.1/ "Defining generic and atomic parts"
[S1.1]: http://kicad-pcb.org/libraries/klc/S1.1/ "Symbol libraries should be categorized by function"
[S2.1]: http://kicad-pcb.org/libraries/klc/S2.1/ "General symbol naming guidelines"
[S2.2]: http://kicad-pcb.org/libraries/klc/S2.2/ "Non-functional variations in part number should be replaced with wildcard"
[S2.3]: http://kicad-pcb.org/libraries/klc/S2.3/ "Where atomic parts are available in multiple footprint options, a separate symbol must be drawn for each footprint"
[S3.1]: http://kicad-pcb.org/libraries/klc/S3.1/ "Origin is centered on the middle of the symbol"
[S3.2]: http://kicad-pcb.org/libraries/klc/S3.2/ "Text fields should use a common text size of 50mils"
[S3.3]: http://kicad-pcb.org/libraries/klc/S3.3/ "Symbol outline and fill requirements"
[S3.4]: http://kicad-pcb.org/libraries/klc/S3.4/ "Symbols with complex functionality may incorporate simple functional diagrams"
[S3.5]: http://kicad-pcb.org/libraries/klc/S3.5/ "Pin connection points must be placed outside of the symbol"
[S3.6]: http://kicad-pcb.org/libraries/klc/S3.6/ "Pin name position offset"
[S3.7]: http://kicad-pcb.org/libraries/klc/S3.7/ "Pin numbering for exposed pads"
[S3.8]: http://kicad-pcb.org/libraries/klc/S3.8/ "Multi unit symbols"
[S4.1]: http://kicad-pcb.org/libraries/klc/S4.1/ "General pin requirements"
[S4.2]: http://kicad-pcb.org/libraries/klc/S4.2/ "Pins should be grouped by function"
[S4.3]: http://kicad-pcb.org/libraries/klc/S4.3/ "Rules for pin stacking"
[S4.4]: http://kicad-pcb.org/libraries/klc/S4.4/ "Pin electrical type"
[S4.5]: http://kicad-pcb.org/libraries/klc/S4.5/ "Pins not connected on the footprint may be omitted from the symbol"
[S4.6]: http://kicad-pcb.org/libraries/klc/S4.6/ "Hidden pins"
[S4.7]: http://kicad-pcb.org/libraries/klc/S4.7/ "Active low pins should be designated using a bar above the symbol name"
[S5.1]: http://kicad-pcb.org/libraries/klc/S5.1/ "Symbols with a default footprint link to a valid footprint file"
[S5.2]: http://kicad-pcb.org/libraries/klc/S5.2/ "Footprint filters should match all appropriate footprints"
[S6.1]: http://kicad-pcb.org/libraries/klc/S6.1/ "Component Reference Designator (RefDes)"
[S6.2]: http://kicad-pcb.org/libraries/klc/S6.2/ "Component fields must be filled appropriately"
[S6.3]: http://kicad-pcb.org/libraries/klc/S6.3/ "Component metadata is added to symbol (and all aliases)"
[S7.1]: http://kicad-pcb.org/libraries/klc/S7.1/ "Power flag symbols"
[S7.2]: http://kicad-pcb.org/libraries/klc/S7.2/ "Graphical symbols"
[F1.1]: http://kicad-pcb.org/libraries/klc/F1.1/ "Footprint libraries are categorized by function"
[F1.2]: http://kicad-pcb.org/libraries/klc/F1.2/ "Connector footprint libraries"
[F2.1]: http://kicad-pcb.org/libraries/klc/F2.1/ "General footprint naming conventions"
[F2.2]: http://kicad-pcb.org/libraries/klc/F2.2/ "Footprint naming field prefixes"
[F2.3]: http://kicad-pcb.org/libraries/klc/F2.3/ "Manufacturer specific version of generic footprints"
[F2.4]: http://kicad-pcb.org/libraries/klc/F2.4/ "Footprint naming for non-standard pin numbering"
[F2.5]: http://kicad-pcb.org/libraries/klc/F2.5/ "Footprint naming conventions for specific components"
[F3.1]: http://kicad-pcb.org/libraries/klc/F3.1/ "SMD chip package naming conventions"
[F3.2]: http://kicad-pcb.org/libraries/klc/F3.2/ "Resistor naming conventions"
[F3.3]: http://kicad-pcb.org/libraries/klc/F3.3/ "Capacitor naming conventions"
[F3.4]: http://kicad-pcb.org/libraries/klc/F3.4/ "SMD IC package naming conventions"
[F3.5]: http://kicad-pcb.org/libraries/klc/F3.5/ "THT IC package naming conventions"
[F3.6]: http://kicad-pcb.org/libraries/klc/F3.6/ "Connector naming conventions"
[F3.7]: http://kicad-pcb.org/libraries/klc/F3.7/ "Fuse naming conventions"
[F4.1]: http://kicad-pcb.org/libraries/klc/F4.1/ "Datasheet recommendations take priority"
[F4.2]: http://kicad-pcb.org/libraries/klc/F4.2/ "Pin 1 should be located at the top left"
[F4.3]: http://kicad-pcb.org/libraries/klc/F4.3/ "Connected copper elements have the same pad number"
[F4.4]: http://kicad-pcb.org/libraries/klc/F4.4/ "Thermal pads"
[F4.5]: http://kicad-pcb.org/libraries/klc/F4.5/ "Specifying footprint keepout areas"
[F4.6]: http://kicad-pcb.org/libraries/klc/F4.6/ "Local clearance and settings should be set to zero"
[F5.1]: http://kicad-pcb.org/libraries/klc/F5.1/ "Silkscreen layer requirements"
[F5.2]: http://kicad-pcb.org/libraries/klc/F5.2/ "Fabrication layer requirements"
[F5.3]: http://kicad-pcb.org/libraries/klc/F5.3/ "Courtyard layer requirements"
[F6.1]: http://kicad-pcb.org/libraries/klc/F6.1/ "Footprint placement type must be set to surface mount"
[F6.2]: http://kicad-pcb.org/libraries/klc/F6.2/ "Footprint anchor should be placed in the middle of the component body"
[F6.3]: http://kicad-pcb.org/libraries/klc/F6.3/ "Pad requirements for SMD footprints"
[F7.1]: http://kicad-pcb.org/libraries/klc/F7.1/ "Footprint placement type must be set to Through Hole"
[F7.2]: http://kicad-pcb.org/libraries/klc/F7.2/ "Footprint anchor should placed at the location of Pin-1"
[F7.3]: http://kicad-pcb.org/libraries/klc/F7.3/ "Pin 1 should be rectangular, and other pads circular or oval"
[F7.4]: http://kicad-pcb.org/libraries/klc/F7.4/ "Pad requirements for THT footprints"
[F7.5]: http://kicad-pcb.org/libraries/klc/F7.5/ "Minimum annular ring width"
[F7.6]: http://kicad-pcb.org/libraries/klc/F7.6/ "Minimum hole diameter"
[F8.1]: http://kicad-pcb.org/libraries/klc/F8.1/ "Virtual components"
[F9.1]: http://kicad-pcb.org/libraries/klc/F9.1/ "Footprint meta-data is filled in as appropriate"
[F9.2]: http://kicad-pcb.org/libraries/klc/F9.2/ "Footprint properties are as default values unless otherwise required in datasheet"
[F9.3]: http://kicad-pcb.org/libraries/klc/F9.3/ "Footprint 3D model requirements"
[M1.1]: http://kicad-pcb.org/libraries/klc/M1.1/ "Models should be created by contributor"
[M1.2]: http://kicad-pcb.org/libraries/klc/M1.2/ "Manufacturer models should not be duplicated"
[M1.3]: http://kicad-pcb.org/libraries/klc/M1.3/ "Source files for 3D models should be supplied"
[M2.1]: http://kicad-pcb.org/libraries/klc/M2.1/ "Permitted 3D model file types"
[M2.2]: http://kicad-pcb.org/libraries/klc/M2.2/ "Model alignment and scaling"

Sorry it took so long for anyone to review this again.

* The NC pins should have no pin number, rather than "NC".
* The bottom row of pads is positioned 0.01 mm too high.
* Both rows of pads are too far to the right: the datasheet says they should be 4.33 mm from the leftmost F.Fab line, but you have this as 4.415 mm.
* Courtyard clearance is much too big: should be 0.5 mm for connectors ([F5.3]), you have 0.78 mm.
* I'd like to see the silkscreen much closer to the body outline, but still outside of it.  Keep a minimum clearance of 0.12 mm from exposed copper pads.
* Silkscreen pin 1 mark should be outside of the connector body so it can be seen when the part is installed on the board.  There should be a pin 1 mark on the F.Fab layer as well.  See the footprint `ZETA-433-SO_THT` for the kind of marks I'd like to see here.
* Please move the F.Fab reference designator to the origin.
* I don't believe the footprint is large enough in the Y direction.  By the drawing for the connector, the module's top will have a 0.4 mm offset from the uppermost F.Fab lines.  The module extends down 31.75 mm from there, which is beyond the bottom of your keepout and very close to the courtyard line.

If you could fix all this within the week, that would be ideal, as then it could be included in the library for KiCad 5.0.0.

**Comment by Roman3349** [comment]
@Ratfink In the datasheet there must be some mistake because 16.45 != 2*4.33+7.62...

**Comment by Ratfink** [comment]
@Roman3349 Any updates on this?  I'd like to fix this issue before the 5.0.0 release if possible, but if you don't have time I understand.

**Comment by Ratfink** [comment]
The delay is no problem; I understand that life comes first.  If this doesn't make it in time for 5.0.0, so be it.

* The positions of the unnamed pads were correct before c35b9ade5e7b74d32c60efb9bacf7010e2b3b4a7, but now they're too far from the bottom of the connector.
* The silkscreen outline is still rather far from the F.Fab outline, but this isn't necessarily a problem.  However, I do ask that you make the silkscreen offset from the F.Fab outline consistent, at the very least.  As it is, I see offsets ranging between 0.235–0.27 mm.
* There's still no pin 1 mark on the F.Fab layer outline.  It should be a triangular wedge cut into the outline at pad C1, similar to the one in the `ZETA-433-SO_THT` footprint.
* You still haven't addressed my earlier comment about the pads being positioned too far to the right.  You seemed to think this was a mistake in the dimension, but I don't see anything suggesting that the groups of pads are centered horizontally on the body (e.g. there's no center line in the drawing), only the distance between the left edge and the leftmost pad.  So unless you can prove that they should be centered, please move them to match the drawing from the manufacturer.

**Comment by Ratfink** [comment]
Looks good, thanks for the contribution!

**Pull request merged**
