### PR TITLE
Son 8 1 ep 3.0x2.0mm p0.5mm ep1.4x1.6mm

### PR DESCRIPTION
**Pull request by Misca1234**
Partly replacement of push 
https://github.com/KiCad/kicad-footprints/pull/634

The foot prints are made with scripts, script push is here
https://github.com/pointhi/kicad-footprint-generator/pull/187

Fujitsu_SON-8-1EP_3x2mm_P0.5mm_EP1.4x1.6mm
http://www.fujitsu.com/downloads/MICRO/fsa/pdf/products/memory/fram/MB85RS16-DS501-00014-6v0-E.pdf

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
There's a banana-jack-connector included in this PR - I assume this is a mistake?

**Comment by Misca1234** [comment]
Yes, it was one of my reviews i did that sneaked in

**Comment by SchrodingersGat** [comment]
Looks good, a couple points:

1. This looks generic enough that we can drop the `Fujitsu`.. We do not have a SON with this layout in the libs currently...

1. (More of a general question for the lib maintainers) - how should we address similarities between the DFN and SON parts? There's a lot of overlap between the two sets of footprints and manufacturers often refer to the same style of package using interchangeable terms. Is there a canonical differentiation between `SON` and `DFN`?

**Comment by Misca1234** [comment]
Removed the suffix Fujitsu from the file name

bild

**Comment by SchrodingersGat** [comment]
Thanks @Misca1234 I'll merge this - the larger discussion regarding naming for SON / DFN / etc can remain 'unsolved' for now 👍

**Comment by Misca1234** [comment]
Thx, jeee, I saw it, but I guess it is an evan and rene question, I can not contribute much to that discussion

**Pull request merged**
