### PR TITLE
Add RJ45-Molex vertical connector footprint

### PR DESCRIPTION
**Pull request by floesche**
The Molex 85513 series is a surface-mount only (no mechanical via/holes)
RJ45 unshielded vertical plug. Product webpage at
https://www.molex.com/molex/products/part-detail/modular_jacks_plug/0855135013.

The datasheet is at https://www.molex.com/pdm_docs/sd/855135013_sd.pdf

image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by floesche** [comment]
Thanks @chmorgan for pointing out the problems. I had accidentally used the silk layer for reference on the courtyard calculation. The other problem should be fixed, too, and snapped to the grid.

**Comment by cp-aquila** [comment]
The courtyard should wrap around the edges, see here: https://ocipcdc.org/archive/What_is_New_in_IPC-7351C_03_11_2015.pdf#page=8

**Comment by floesche** [comment]
Thanks @cp-aquila, I overlooked that example in F5.3. The new courtyard looks as follows:

Screenshot_2020-03-20T14-48-18

**Comment by Ripae** [comment]
Isn't the pin numbering reverse?

**Comment by cp-aquila** [comment]
> 
> 
> Isn't the pin numbering reverse?

grafik

Yep, seems like this needs a fix. Mirroring anlong the X-Axis should do it.
@Ripae Do you want to open a PR with that fix?

**Comment by Ripae** [comment]
@cp-aquila Not much, no. Not today.

**Comment by floesche** [comment]
My attempt to fix the problem looks as follows. Is that OK?

Screenshot_2020-06-20T22-21-58

Thanks for finding the problem and apologies for introducing it in the first place.

**Comment by poeschlr** [comment]
Rotate by 90 degree such that pin 1 is closest to the top left corner.

**Comment by floesche** [comment]
Thanks. It looks like this now in 1ff6137:

Screenshot_2020-06-21T12-52-24

Is there a recommendation/convention for the distance between text and component, eg for the silkscreen or fab layer? At the moment I use 0.5mm (1/2 the text size).

**Comment by cpresser** [comment]
> Is there a recommendation/convention for the distance between text and component, eg for the silkscreen or fab layer? At the moment I use 0.5mm (1/2 the text size).

No, there is none. For most boards the designer will move the F.SilkS designators around anyway. Close to Pin1 does seems like a good idea.
Your choice seems plausible.

**Pull request merged**
