### PR TITLE
Jst b2p3-vh

### PR DESCRIPTION
**Pull request by evanshultz**
B2P3-VH is popular as an AC connector where earth ground is not required so I wanted to generate it
http://www.jst-mfg.com/product/pdf/eng/eVH.pdf
image

See page 4 for post-omitted variants of this header. This version, 3 pin with pin 2 omitted, falls into 3) which is named "when the pitch is set again" so I changed the pitch. I also used pin numbers 1 and 2 so that it will work with the standard 2-pin symbols in KiCad. Let me know if either choice is undesirable.

Since there was a minor correction in an external file which the script uses and affects all footprints, I pushed all that come from this script.

Script PR: https://github.com/pointhi/kicad-footprint-generator/pull/389

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
pad 1 should have a different shape than circle (roundrect or rect)

**Comment by evanshultz** [comment]
@poeschlr 
You are right. Updated footprint and screenshot above.

**Comment by poeschlr** [comment]
thanks

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
