### PR TITLE
Scripted sop-4 and sop-18 footpritns

### PR DESCRIPTION
**Pull request by poeschlr**
No changes to symbols needed. (The footprint that got renamed is not currently used by any symbol)

script: https://github.com/pointhi/kicad-footprint-generator/pull/289

http://www.ixysic.com/home/pdfs.nsf/www/CPC1017N.pdf/$file/CPC1017N.pdf

screenshot from 2019-02-06 23-23-36

```yaml
SOP-4_3.8x4.1mm_P2.54mm:
  size_source: 'http://www.ixysic.com/home/pdfs.nsf/www/CPC1017N.pdf/$file/CPC1017N.pdf'
  body_size_x:
    nominal: 3.8 #rounded to avoid changing the symbol
    tolerance: 0.025
  body_size_y:
    nominal: 4.1 #rounded to avoid changing the symbol
    tolerance: 0.025
  body_height:
    # calculated from (2.03 +/-0.025) + (0.64 +/-0.04)
    nominal: 2.094
    tolerance: 0.047

  overall_size_x:
    nominal: 6.096
    tolerance: 0.102
  lead_width:
    nominal: 0.381
    tolerance: 0 # not given
  lead_len:
    nominal: 0.559
    tolerance: 0.127

  pitch: 2.54
  num_pins_x: 0
  num_pins_y: 2
```

---

https://toshiba.semicon-storage.com/info/docget.jsp?did=30523

screenshot from 2019-02-06 23-23-22

```yaml
SOP-18_7.0x12.5mm_P1.27mm:
  size_source: 'https://toshiba.semicon-storage.com/info/docget.jsp?did=30523'
  body_size_x:
    nominal: 7
    tolerance: 0.2
  body_size_y:
    nominal: 12.5
    tolerance: 0.2
  body_height:
    maximum: 2.45

  overall_size_x:
    nominal: 10.3
    tolerance: 0.3
  lead_width:
    nominal: 0.4
    tolerance: 0.1
  lead_len:
    nominal: 0.7
    tolerance: 0.2

  pitch: 1.27
  num_pins_x: 0
  num_pins_y: 9
```

### CODE REVIEW

**Comment by evanshultz** [comment]
Can you put the datasheet nominal body size dimensions in the comment for clarity? And is there a reason not to update the symbol and make it "right"?

SOP-18_7.0x12.5mm_P1.27mm: Since the Toshiba datasheet has such similarly-named packages and is laid out, in my opinion, poorly, could you capture the Toshiba package name for which this footprint is designed (`SOP18-P-375-1.27`)?

**Comment by poeschlr** [comment]
The body size does not at all influence copper parts of these footprints. (The body is larger by 0.01mm so it would influence the courtyard by a bit)

A real fix would be a better more powerful footprint name manager that could allow us to define the number of digits after the decimal. I have this planned for the distant future.

**Comment by evanshultz** [comment]
Understood. I was thinking to capture a bit more info in the script so it's there and ready if needed. Is that too much? And yes, I get it that the footprints won't be changed but I did the review here since you nicely provided all the info.

**Comment by poeschlr** [comment]
Ah you mean add this info to the comment of in the script. (I really have been to tired yesterday it seems.) Done: https://github.com/pointhi/kicad-footprint-generator/pull/289/commits/727a321e107379a68fe1e2eac1669ab2b2619759

**Comment by evanshultz** [comment]
Oh yes. There are two kinds of comments here. I didn't think about that earlier.

**Pull request merged**
