### PR TITLE
Use unique and IPC package sizes for R, L, and C

### PR DESCRIPTION
**Pull request by evanshultz**
Chip capacitors were using resistor package information when IPC-SM-782 shows distinct resistor and capacitor packages; to fix this some chip package info was modified based on datasheet anlysis was tweaking. Also, the same IPC doc includes unique chip inductor package sizes and they were again using resistor package information. See https://github.com/pointhi/kicad-footprint-generator/issues/420.

The script update is at https://github.com/pointhi/kicad-footprint-generator/pull/438 and you should find the most useful information there and the file diff to assess this.

Related:
https://github.com/KiCad/kicad-footprints/pull/3
https://github.com/KiCad/kicad-footprints/pull/469
https://github.com/KiCad/kicad-footprints/issues/711
https://github.com/KiCad/kicad-footprints/pull/712
https://github.com/pointhi/kicad-footprint-generator/issues/420

The only significant changes are on some R, L, and C footprints, but most of the changes are quite close to the existing footprints which had made-up info to suit packages found in datasheets (especially see the 0805 capacitor footprint); this validates that the IPC-SM-782 doc is reasonable and that chip component manufacturers were roughly adhering to it all along. All chip footprints are re-generated here since there are a handful of typos.

Marking as a bug since the library claimed to be IPC-compliant and called out IPC-SM-782 but the footprints didn't actually adhere to those documents.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by diegoherranz** [comment]
A bit late to the party but have been dealing with a very similar thing at work recently.

I don't have access to the IPC standards but if I understand correctly, the latest relevant standard for this is IPC-7351B (which replaced IPC-7351A, IPC-7351 and IPC-SM-782 in that order).

Has anyone access to the IPC standards? Was there any change between IPC-SM-782 and IPC-7351B which affects this PR (and the related ones like https://github.com/pointhi/kicad-footprint-generator/issues/420)?
If so, I think we should follow IPC-7351B.

Thanks!

**Comment by evanshultz** [comment]
Yes, B is the latest release. We have switched to rounded rectangle pads in all generators as that is shown as the best pad shape for all circumstances in the draft C releases, but otherwise all generators adhere to B.

Rene and I have the standards.

782 had body sizes for chip parts. 7351 started an algorithmic way of determining footprints. So we use the body sizes from 782 as they're still valid and match real parts in the market, but derive pad sizes from 7351B. Originally, the resistor body sizes from 782 were errantly being used for capacitor and inductors, and this PR fixes that. Does that make sense?

**Comment by diegoherranz** [comment]
Thanks for your reply.

Sorry if I make a few more questions on this, but not having access to the standards (or not to the latest versions, at least) makes this a bit more complicated.

> We have switched to rounded rectangle pads in all generators as that is shown as the best pad shape for all circumstances in the draft C releases, but otherwise all generators adhere to B.

I have seen in [IPC-7351 Feb. 2005](http://pcbget.ru/Files/Standarts/IPC_7351.pdf): "The land form may be rectangular with straight or rounded corners. In the latter case the area of the smallest circumscribed rectangle shall be equal to that of one with straight corners."

If I understand that correctly, that makes the pads with rounded corners bigger than the ones with straight corners. Is that still the case in IPC-7351B and IPC-7351C (draft)? Is that what we're doing in KiCad?

> 782 had body sizes for chip parts. 7351 started an algorithmic way of determining footprints. So we use the body sizes from 782 as they're still valid and match real parts in the market, but derive pad sizes from 7351B

And no version of IPC-7351 includes body sizes and that is why we refer to IPC-SM-782A, right?
Where do we take the values for 0201 and smaller? Can't find that on IPC-SM-782A.

> Originally, the resistor body sizes from 782 were errantly being used for capacitor and inductors, and this PR fixes that. Does that make sense?

Yes, that makes it more clear. I think I'm starting to understand the puzzle.

Somehow related to this, I'm a bit confused with some of the rounding terminology used on [IPC-7351 Feb. 2005](http://pcbget.ru/Files/Standarts/IPC_7351.pdf)

On Page 23:

_Round off to the nearest two place even decimal, i.e., 1.00, 1.20, 1.40_
Is that a typo? Should it be 1.02, 1.04, 1.06?

_Round off to the nearest two place decimal, i.e., 1.00, 1.05, 1.10, 1.15_  
Should it be 1.01, 1.02, 1.03? Otherwise the round off factor would be 0.05 for sizes smaller than 0603 and 0.02 for 0603 and larger which doesn't make much sense to me. Something looks wrong.

That made me wonder whether the rounding on [ipc_smd_two_terminal_chip.yaml](https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/SMD_chip_package_rlc-etc/ipc_smd_two_terminal_chip.yaml) is correct, although I guess we don't use that file anymore but only [ipc7351B_smd_two_terminal_chip.yaml](https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/SMD_chip_package_rlc-etc/ipc7351B_smd_two_terminal_chip.yaml)?

Many thanks!

**Comment by evanshultz** [comment]
I'm not the authority on IPC 7351, but I'll share my understanding...

Rev B was released in 2010, after the doc you mention, and things have changed. It switched to oblong/oval pads. Draft rev C info from Tom Hausherr was online in a presentation titled "what is new in ipc-7351c", but the link we had is broken so here's a screenshot:
image

It's correct that 782 gave body sizes and 7351 gives an algorithm to determine pad sizes. We put them together to end up with the KiCad library's footprints. You can see at https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/SMD_chip_package_rlc-etc/size_definitions/size_default_chip_devices_smaller_0402.yaml that 0201 and 01005 body sizes were taken from a Vishay resistor datasheet.

Regarding rounding, I checked the 7351B YAML file against the doc for >=0603 and <0603 chip parts and it's correct. The IPC doc has changed since 7351 (no suffix) that you linked and I think our YAML file is good. The other YAML file is available to use, but since rev B is using later and more updated info we aren't using it in the current library footprints.

I hope that answers everything as best as I can.

**Comment by evanshultz** [comment]
Footprints updated.

There were a number of non-scripted capacitor footprints which I removed since I didn't find that body size available at DigiKey.

Also, handsolder footprints adjust the footprint name based on the pad size. That seems rather unhelpful. What if the pad size in the footprint name was discarded and just keep the `_HandSolder` suffix? Is there need to support multiple handsolder chip footprints?

**Comment by evanshultz** [comment]
@cpresser 
Does this look fine to you so far? Only the tantalums are potentially outstanding?

**Comment by cpresser** [comment]
Sorry for the delay, I was building our hacker-space yesterday. I will look at the tantalum caps now.

> Footprints updated.
> 
> There were a number of non-scripted capacitor footprints which I removed since I didn't find that body size available at DigiKey.

Did you make a list that I can verify? Or should I just look at the git log?
 
> Also, handsolder footprints adjust the footprint name based on the pad size. That seems rather unhelpful. What if the pad size in the footprint name was discarded and just keep the `_HandSolder` suffix? Is there need to support multiple handsolder chip footprints?

TBH, I don't like it.
* The users are expecting handsolder named footprints. If we change this, I would suggest to wait for v6. But not include such a big change in 5.1.x
* The size increase is arbitrary, and so is the resulting overall size.
* They are intended for not so advanced users. My gut feeling is that no experienced engineer uses them.  But those are the only people interested in the exact size.
* As a user of those footprints I am not interested in their size. The user-story is **I want a 0805 for handsoldering**.
* I might be a bit biased here since I don't like the whole idea of handsoldering footprints. I would rather teach people how to solder the regular sized footprints^^

**Comment by chschlue** [comment]
I'd rather pick up the discussion about including MMC and LMC footprints alongside default level B ones again for v6 (leaving it to the forum regulars to tell people to use the MMC ones if they don't have a steady hand ;) .)

I'm not very fond of the arbitrary `_HandSolder` FPs sprinkled over the library here and there either.

**Comment by evanshultz** [comment]
I'm not fond of the `_HandSolder` footprints myself, either, but what I'm asking about is the need to specify the pad size in their footprint name. I'd rather just have `_HandSolder` and leave the pad size out of the footprint name, rather than `Pad1.05x0.85_HandSolder` (I just made that up). Sorry if I wasn't clear before. Is that something we could/should look at now?

**Comment by cpresser** [comment]
I vote for just having `_HandSolder`. Reasoning for that is included in the above post.

**Comment by cpresser** [comment]
Parts I can also not find
* C_0815
* C_2010
* C_1806
* C_2512
* C_2816
* D_1806
* Fuse_1806 (TBH, I don't understand fuses.. 
* L_1806
* LED_1806
* R_1806


Parts that are removed, but I could find them
* C_0504 https://www.mouser.de/datasheet/2/218/Comm-Chip-X7R-16V-10kVdc-1359205.pdf
* LED_1206_3216Metric_ReverseMount https://www.we-online.de/katalog/de/WL-SMRW/
* R_2810 http://www.vishay.com/doc?30100

Parts that are still included, but I could not find:
* Fuse_0201

**Comment by cpresser** [comment]
The tantalum caps are unchanged but the timestamp. That means they are good enough for now. I would keep them like this and revisit them in a dedicated PR.

**Comment by chschlue** [comment]
@evanshultz @cpresser 
There's no chance this will require symbol changes in any way, right?
I'm asking because the merge of https://github.com/KiCad/kicad-symbols/pull/2344 closed the last remaining 5.1.7 issue and I would like to go on with releasing 5.1.7 symbols if there's nothing left to do there.

**Comment by cpresser** [comment]
> @evanshultz @cpresser
> There's no chance this will require symbol changes in any way, right?

No, I don't assume so. Here is a list of all footprints touched by this PR. All of them are covered by `Device.lib` symbols.
```
Capacitor_SMD.pretty/C_01005_0402Metric.kicad_mod
Capacitor_SMD.pretty/C_0201_0603Metric.kicad_mod
Capacitor_SMD.pretty/C_0402_1005Metric.kicad_mod
Capacitor_SMD.pretty/C_0504_1310Metric.kicad_mod
Capacitor_SMD.pretty/C_0603_1608Metric.kicad_mod
Capacitor_SMD.pretty/C_0603_1608Metric_Pad1.08x0.95mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_0805_2012Metric.kicad_mod
Capacitor_SMD.pretty/C_0805_2012Metric_Pad1.18x1.45mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_1206_3216Metric.kicad_mod
Capacitor_SMD.pretty/C_1206_3216Metric_Pad1.33x1.80mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_1210_3225Metric.kicad_mod
Capacitor_SMD.pretty/C_1210_3225Metric_Pad1.33x2.70mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_1812_4532Metric.kicad_mod
Capacitor_SMD.pretty/C_1812_4532Metric_Pad1.57x3.40mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_1825_4564Metric.kicad_mod
Capacitor_SMD.pretty/C_1825_4564Metric_Pad1.57x6.80mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_2220_5650Metric.kicad_mod
Capacitor_SMD.pretty/C_2220_5650Metric_Pad1.97x5.40mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_2225_5664Metric.kicad_mod
Capacitor_SMD.pretty/C_2225_5664Metric_Pad1.80x6.60mm_HandSolder.kicad_mod
Capacitor_SMD.pretty/C_3640_9110Metric.kicad_mod
Capacitor_SMD.pretty/C_3640_9110Metric_Pad2.10x10.45mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-1608-08_AVX-J.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-1608-08_AVX-J_Pad1.25x1.05mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-1608-10_AVX-L.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-1608-10_AVX-L_Pad1.25x1.05mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-2012-12_Kemet-R.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-2012-12_Kemet-R_Pad1.30x1.05mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-2012-15_AVX-P.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-2012-15_AVX-P_Pad1.30x1.05mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3216-10_Kemet-I.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3216-10_Kemet-I_Pad1.58x1.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3216-12_Kemet-S.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3216-12_Kemet-S_Pad1.58x1.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3216-18_Kemet-A.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3216-18_Kemet-A_Pad1.58x1.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3528-12_Kemet-T.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3528-12_Kemet-T_Pad1.50x2.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3528-15_AVX-H.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3528-15_AVX-H_Pad1.50x2.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3528-21_Kemet-B.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-3528-21_Kemet-B_Pad1.50x2.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-6032-15_Kemet-U.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-6032-15_Kemet-U_Pad2.25x2.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-6032-20_AVX-F.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-6032-20_AVX-F_Pad2.25x2.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-6032-28_Kemet-C.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-6032-28_Kemet-C_Pad2.25x2.35mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-20_AVX-U.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-20_AVX-U_Pad2.72x3.50mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-28_AVX-C.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7132-28_AVX-C_Pad2.72x3.50mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-15_AVX-R.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-15_AVX-R_Pad2.68x6.30mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-20_AVX-M.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-20_AVX-M_Pad2.68x6.30mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-28_AVX-M.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-28_AVX-M_Pad2.68x6.30mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-38_AVX-R.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7260-38_AVX-R_Pad2.68x6.30mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-15_Kemet-W.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-15_Kemet-W_Pad2.25x2.55mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-20_Kemet-V.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-20_Kemet-V_Pad2.25x2.55mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-30_AVX-N.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-30_AVX-N_Pad2.25x2.55mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-31_Kemet-D.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-31_Kemet-D_Pad2.25x2.55mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-40_Kemet-Y.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-40_Kemet-Y_Pad2.25x2.55mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-43_Kemet-X.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7343-43_Kemet-X_Pad2.25x2.55mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7360-38_Kemet-E.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7360-38_Kemet-E_Pad2.25x4.25mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7361-38_AVX-V.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7361-38_AVX-V_Pad2.18x3.30mm_HandSolder.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7361-438_AVX-U.kicad_mod
Capacitor_Tantalum_SMD.pretty/CP_EIA-7361-438_AVX-U_Pad2.18x3.30mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_01005_0402Metric.kicad_mod
Diode_SMD.pretty/D_0201_0603Metric.kicad_mod
Diode_SMD.pretty/D_0402_1005Metric.kicad_mod
Diode_SMD.pretty/D_0603_1608Metric.kicad_mod
Diode_SMD.pretty/D_0603_1608Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_0603_1608Metric_Pad1.05x0.95mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_0805_2012Metric.kicad_mod
Diode_SMD.pretty/D_0805_2012Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_0805_2012Metric_Pad1.15x1.40mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_1206_3216Metric.kicad_mod
Diode_SMD.pretty/D_1206_3216Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_1206_3216Metric_Pad1.42x1.75mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_1210_3225Metric.kicad_mod
Diode_SMD.pretty/D_1210_3225Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_1210_3225Metric_Pad1.42x2.65mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_1812_4532Metric.kicad_mod
Diode_SMD.pretty/D_1812_4532Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_1812_4532Metric_Pad1.30x3.40mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_2010_5025Metric.kicad_mod
Diode_SMD.pretty/D_2010_5025Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_2010_5025Metric_Pad1.52x2.65mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_2114_3652Metric.kicad_mod
Diode_SMD.pretty/D_2114_3652Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_2114_3652Metric_Pad1.85x3.75mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_2512_6332Metric.kicad_mod
Diode_SMD.pretty/D_2512_6332Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_2512_6332Metric_Pad1.52x3.35mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_2816_7142Metric.kicad_mod
Diode_SMD.pretty/D_2816_7142Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
Diode_SMD.pretty/D_3220_8050Metric.kicad_mod
Diode_SMD.pretty/D_3220_8050Metric_Castellated.kicad_mod
Diode_SMD.pretty/D_3220_8050Metric_Pad2.65x5.15mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_01005_0402Metric.kicad_mod
Fuse.pretty/Fuse_0201_0603Metric.kicad_mod
Fuse.pretty/Fuse_0402_1005Metric.kicad_mod
Fuse.pretty/Fuse_0603_1608Metric.kicad_mod
Fuse.pretty/Fuse_0603_1608Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_0603_1608Metric_Pad1.05x0.95mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_0805_2012Metric.kicad_mod
Fuse.pretty/Fuse_0805_2012Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_0805_2012Metric_Pad1.15x1.40mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_1206_3216Metric.kicad_mod
Fuse.pretty/Fuse_1206_3216Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_1206_3216Metric_Pad1.42x1.75mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_1210_3225Metric.kicad_mod
Fuse.pretty/Fuse_1210_3225Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_1210_3225Metric_Pad1.42x2.65mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_1812_4532Metric.kicad_mod
Fuse.pretty/Fuse_1812_4532Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_1812_4532Metric_Pad1.30x3.40mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_2010_5025Metric.kicad_mod
Fuse.pretty/Fuse_2010_5025Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_2010_5025Metric_Pad1.52x2.65mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_2512_6332Metric.kicad_mod
Fuse.pretty/Fuse_2512_6332Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_2512_6332Metric_Pad1.52x3.35mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_2816_7142Metric.kicad_mod
Fuse.pretty/Fuse_2816_7142Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
Fuse.pretty/Fuse_2920_7451Metric.kicad_mod
Fuse.pretty/Fuse_2920_7451Metric_Castellated.kicad_mod
Fuse.pretty/Fuse_2920_7451Metric_Pad2.10x5.45mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_01005_0402Metric.kicad_mod
Inductor_SMD.pretty/L_0201_0603Metric.kicad_mod
Inductor_SMD.pretty/L_0402_1005Metric.kicad_mod
Inductor_SMD.pretty/L_0603_1608Metric.kicad_mod
Inductor_SMD.pretty/L_0603_1608Metric_Pad1.05x0.95mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_0805_2012Metric.kicad_mod
Inductor_SMD.pretty/L_0805_2012Metric_Pad1.05x1.20mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_0805_2012Metric_Pad1.15x1.40mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_1008_2520Metric.kicad_mod
Inductor_SMD.pretty/L_1008_2520Metric_Pad1.43x2.20mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_1206_3216Metric.kicad_mod
Inductor_SMD.pretty/L_1206_3216Metric_Pad1.22x1.90mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_1206_3216Metric_Pad1.42x1.75mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_1210_3225Metric.kicad_mod
Inductor_SMD.pretty/L_1210_3225Metric_Pad1.42x2.65mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_1806_4516Metric.kicad_mod
Inductor_SMD.pretty/L_1806_4516Metric_Pad1.45x1.20mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_1812_4532Metric.kicad_mod
Inductor_SMD.pretty/L_1812_4532Metric_Pad1.30x3.40mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_2010_5025Metric.kicad_mod
Inductor_SMD.pretty/L_2010_5025Metric_Pad1.52x2.65mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_2512_6332Metric.kicad_mod
Inductor_SMD.pretty/L_2512_6332Metric_Pad1.52x3.35mm_HandSolder.kicad_mod
Inductor_SMD.pretty/L_2816_7142Metric.kicad_mod
Inductor_SMD.pretty/L_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_01005_0402Metric.kicad_mod
LED_SMD.pretty/LED_0201_0603Metric.kicad_mod
LED_SMD.pretty/LED_0402_1005Metric.kicad_mod
LED_SMD.pretty/LED_0603_1608Metric.kicad_mod
LED_SMD.pretty/LED_0603_1608Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_0603_1608Metric_Pad1.05x0.95mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_0805_2012Metric.kicad_mod
LED_SMD.pretty/LED_0805_2012Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_0805_2012Metric_Pad1.15x1.40mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_1206_3216Metric.kicad_mod
LED_SMD.pretty/LED_1206_3216Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_1206_3216Metric_Pad1.42x1.75mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_1210_3225Metric.kicad_mod
LED_SMD.pretty/LED_1210_3225Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_1210_3225Metric_Pad1.42x2.65mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_1812_4532Metric.kicad_mod
LED_SMD.pretty/LED_1812_4532Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_1812_4532Metric_Pad1.30x3.40mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_2010_5025Metric.kicad_mod
LED_SMD.pretty/LED_2010_5025Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_2010_5025Metric_Pad1.52x2.65mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_2512_6332Metric.kicad_mod
LED_SMD.pretty/LED_2512_6332Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_2512_6332Metric_Pad1.52x3.35mm_HandSolder.kicad_mod
LED_SMD.pretty/LED_2816_7142Metric.kicad_mod
LED_SMD.pretty/LED_2816_7142Metric_Castellated.kicad_mod
LED_SMD.pretty/LED_2816_7142Metric_Pad3.20x4.45mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_01005_0402Metric.kicad_mod
Resistor_SMD.pretty/R_0201_0603Metric.kicad_mod
Resistor_SMD.pretty/R_0402_1005Metric.kicad_mod
Resistor_SMD.pretty/R_0603_1608Metric.kicad_mod
Resistor_SMD.pretty/R_0603_1608Metric_Pad0.98x0.95mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_0612_1632Metric.kicad_mod
Resistor_SMD.pretty/R_0612_1632Metric_Pad1.18x3.40mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_0805_2012Metric.kicad_mod
Resistor_SMD.pretty/R_0805_2012Metric_Pad1.20x1.40mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_0815_2038Metric.kicad_mod
Resistor_SMD.pretty/R_0815_2038Metric_Pad1.20x4.05mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_1020_2550Metric.kicad_mod
Resistor_SMD.pretty/R_1020_2550Metric_Pad1.33x5.20mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_1206_3216Metric.kicad_mod
Resistor_SMD.pretty/R_1206_3216Metric_Pad1.30x1.75mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_1210_3225Metric.kicad_mod
Resistor_SMD.pretty/R_1210_3225Metric_Pad1.30x2.65mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_1218_3246Metric.kicad_mod
Resistor_SMD.pretty/R_1218_3246Metric_Pad1.22x4.75mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_1812_4532Metric.kicad_mod
Resistor_SMD.pretty/R_1812_4532Metric_Pad1.30x3.40mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_2010_5025Metric.kicad_mod
Resistor_SMD.pretty/R_2010_5025Metric_Pad1.40x2.65mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_2512_6332Metric.kicad_mod
Resistor_SMD.pretty/R_2512_6332Metric_Pad1.40x3.35mm_HandSolder.kicad_mod
Resistor_SMD.pretty/R_4020_10251Metric.kicad_mod
Resistor_SMD.pretty/R_4020_10251Metric_Pad1.65x5.30mm_HandSolder.kicad_mod
```

> I'm asking because the merge of [KiCad/kicad-symbols#2344](https://github.com/KiCad/kicad-symbols/pull/2344) closed the last remaining 5.1.7 issue and I would like to go on with releasing 5.1.7 symbols if there's nothing left to do there.

Off-Topic: I got one more low hanging fruit (not yet tagged with 5.1.7)
https://github.com/KiCad/kicad-symbols/pull/3089

**Comment by cpresser** [comment]
@evanshultz Can you please re-add those parts?
* C_0504 https://www.mouser.de/datasheet/2/218/Comm-Chip-X7R-16V-10kVdc-1359205.pdf
* LED_1206_3216Metric_ReverseMount https://www.we-online.de/katalog/de/WL-SMRW/
* R_2810 http://www.vishay.com/doc?30100

I how about removing the tiny fuse and  LEDs? I could not verify their existence.
* Fuse.pretty/Fuse_01005_0402Metric.kicad_mod
* Fuse.pretty/Fuse_0201_0603Metric.kicad_mod
* LED_SMD.pretty/LED_01005_0402Metric.kicad_mod

**Comment by evanshultz** [comment]
C_0504 (and smaller) was there, but not the handsolder version. Same with small resistors. And all small castellated footprints. The reverse LED was an accidental delete when I was cleaning out old footprints. (I assumed anything with an old file date should be removed since there were lots of handsolder footprints with now-bogus pad sizes, but I missed that one.) The resistor was a mistake in the generator that is fixed.

I removed the tiny fuses and LED footprints.

All of the above should be corrected. Let me know if I missed anything that I didn't catch.

**Comment by cpresser** [comment]
Your latest 3 commits look good.

----

I checked the whole PR with
`git diff-tree --diff-filter=A --no-commit-id --name-only -r  5.1.6 HEAD` and
`git diff-tree --diff-filter=D --no-commit-id --name-only -r  5.1.6 HEAD` for added and deleted parts.
The exact pad-sizes of the `_HandSolder` I did not check, they are arbitrary anyway.
Filenames look good, nothing use full was removed.

---


I picked a few random parts to sanity check them.. and damm... I found something. :sob: 
There seems to be an issue with `L_1806`. Its not wide enough. The IPC doc seems wrong.
image

Metric code is 4516, but according to the table the max body-width is 1.2mm.
image

Murata disagrees:
image

**Comment by cpresser** [comment]
I merged this, and opened a PR to fix that inductor here: https://github.com/KiCad/kicad-footprints/pull/2487
Please review and merge, then we are ready for 5.1.7

**Pull request merged**
