### PR TITLE
Add MQ-6 Gas Sensor

### PR DESCRIPTION
**Pull request by gggfred**
[Datasheet](https://www.winsen-sensor.com/d/files/semiconductor/mq-6.pdf)

imagen

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by cpresser** [comment]
- [x] Pin positions are perfect.
- [x] New library for just one part seems odd; but I think its okay since it matches the symbol library.
- [ ] Courtyard clearance should be 0.25mm

**Comment by poeschlr** [comment]
please put this into the generic sensor lib. i do not expect us to ever have enough gas sensors to require a separate lib

**Comment by gggfred** [comment]
> 
> 
>     * [x]  Pin positions are perfect.
> 
>     * [x]  New library for just one part seems odd; but I think its okay since it matches the symbol library.
> 
>     * [ ]  Courtyard clearance should be 0.25mm

please, check again, from the outside fab line, to the courtyard center, actually is 0.25 mm

**Comment by cpresser** [comment]
> 
> please, check again, from the outside fab line, to the courtyard center, actually is 0.25 mm

I did, and measured the `F.Fab` circle to have a radius of 9.5mm and `F.SilkS` circle 9.8mm. Thats 0.3mm difference to me.

**Comment by gggfred** [comment]
Mmmm, I thought than the clearance should be taken from the external side fab line (I mean, 9.5 + 0.05 half fab line width). I fix it now

**Comment by cpresser** [comment]
The F.CrtYd lines can be considered as 'zero' width. Their purpose is to check if parts overlap. Two courtyard-lines can be exactly on top of each other without generating a DRC error.
It is similar for F.Fab lines. They are the theoretical exact boundary of the part. The width itself has little meaning. I am not sure why 0.1mm was chosen in KLC, perhaps its based on IPC, or just because it looks nice.

**Comment by gggfred** [comment]
Thanks!

**Pull request merged**
