### PR TITLE
Infineon TISON footprints

### PR DESCRIPTION
**Pull request by evanshultz**
This PR includes all four current Infineon PG-TISON packages that have footprints.

The pin numbering is a bit tricky. I chose to start with the designated pin 1 and then go counter-clockwise, as usual, and finish with pads under the part. I'm open to suggestions about a better scheme.

Also, I squared off the paste pads on PG-TISON-8-2 and -3.

PG-TISON-8-2 / PG-TISON-8-3
https://www.infineon.com/cms/en/product/packages/PG-TISON/PG-TISON-8-2/
https://www.infineon.com/cms/en/product/packages/PG-TISON/PG-TISON-8-3/
image
image

PG-TISON-8-4
https://www.infineon.com/cms/en/product/packages/PG-TISON/PG-TISON-8-4/
image
image

On this one I caught an incorrect courtyard during dimensioning and fixed it before committing.

PG-TISON-8-5
https://www.infineon.com/cms/en/product/packages/PG-TISON/PG-TISON-8-5/
image
image

This one doesn't import the custom shape with two primitives. And it's missing the inner radius so I know somebody will say I should have used FreeCAD. And you'd be right.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
TISON-8-3 appears to be identical to TISON-8-2. I have asked Infineon if there is a difference.

**Comment by poeschlr** [comment]
Did infineon ever get back to you on that?
Otherwise, i would say this is ready to merge.

**Comment by evanshultz** [comment]
@poeschlr 
Yes, sorry about that. The internal clip is different to hold a bigger die size. But from the outside, where we care about the footprint, they're identical.

**Comment by poeschlr** [comment]
thanks for the update and of course the work you did here

**Pull request merged**
