### PR TITLE
Create DFN-6-1EP_3x2mm_P0.5mm_EP1.65x1.35mm.kicad_mod

### PR DESCRIPTION
**Pull request by ferdymercury**
https://github.com/KiCad/kicad-symbols/pull/1087/
https://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/ltc-legacy-dfn/(DCB6)%20DFN%2005-08-1715%20Rev%20A.pdf
image

------------

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
This one could be scripted. @ferdymercury  would you be willing to look into that?
The script that can handle these sort of parts lives here: https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_DFN_QFN

**Comment by ferdymercury** [comment]
Thanks. I wont be able to look into it for the moment, but maybe beginning of next year.

**Comment by poeschlr** [comment]
Please open a pull request on the script repo and point to it from here. I normally mainly check the script stuff. (One of the benefits of having scripts is that it reduces our review effort. )

**Comment by ferdymercury** [comment]
Alright, I close then this PR, please follow here https://github.com/pointhi/kicad-footprint-generator/pull/234

**Comment by poeschlr** [comment]
A pull request here on this repo will still be required. Adding something to the generator repo does not automatically add the result here.

**Comment by ferdymercury** [comment]
Pull request updated with scripted FP output

**Comment by poeschlr** [comment]
Thanks for your contribution. Especially as you where prepared to look into the script.

**Pull request merged**
