### PR TITLE
TLP3123

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Footprint SO-4, 4.4x3.9mm, Pitch 2.54mm, for TLP3123 device from Toshiba

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing

https://toshiba.semicon-storage.com/info/docget.jsp?did=10047&prodName=TLP3123

- [x] An example screenshot image is very helpful 

capture

- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
Please script this one with https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_Gullwing__QFP_SOIC_SO

---

Short instruction: Enter the package size definitions into a new size file called so.yaml (copy some other file as a template.)
Fill out the header section of that file and enter your size definition with the same tolerancing scheme used by the datasheet.
Run the script with python3 (Important: really use a version 3 python. The scripts are not tested in version 2) `python3 ipc_gullwing_generator.py size_definitions/so.yaml` (right now you could give it a spin with any other size definition file already present to get a feel of what it does.)

**Comment by myfreescalewebpage** [comment]
Thanks @poeschlr I was almost sure there was the possibility, I'm looking to that, thanks for the quick instructions, helpful, this is my first scripted footprint to do !!!

**Comment by myfreescalewebpage** [comment]
Updated with scripted version, sources at https://github.com/pointhi/kicad-footprint-generator/pull/296.

**Comment by poeschlr** [comment]
comment added to the script PR

**Comment by myfreescalewebpage** [comment]
@poeschlr fixed

**Comment by evanshultz** [comment]
@poeschlr 
Is this ready to merge?

**Comment by evanshultz** [comment]
@myfreescalewebpage 
Did the script changes affect the footprint in any way, or were they only formatting of the YAML file? If the footprint here is good, I'll merge.

**Comment by myfreescalewebpage** [comment]
No change of the footprint except the tedit field, updated just to be sure :)

**Comment by evanshultz** [comment]
It seems Travis has lost his mind, but this particular footprint is OK. And it's the only file changed in this PR. Thanks!

**Pull request merged**
