### PR TITLE
Sensor pressure

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Added `Sensor_Pressure` footprint library for bespoke pressure sensor footprints.

Started the ball rolling with two footprints from Freescale / NXP

https://www.nxp.com/docs/en/data-sheet/MPXA6115A.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
The only errors are the fp-lib-table checks. They need to be improved, I'm working on that. But these footprints have no KLC issues :)

**Comment by SchrodingersGat** [comment]
New, from my archives.

**Comment by SchrodingersGat** [comment]
image

image

**Comment by evanshultz** [comment]
Honeywell datasheet is at https://sensing.honeywell.com/index.php?ci_id=138832. It's an odd package.

I'll merge this, but need to ask if you also have schematic symbols.

**Comment by SchrodingersGat** [comment]
There are already schematic symbols for the 40PC and MPX pressure sensors in the "sensors.lib" library :)

**Pull request merged**
