### PR TITLE
Add Resistor Stackpole CSS/CSSH current sense resistors

### PR DESCRIPTION
**Pull request by strombom**
CSSH2728
https://www.seielect.com/catalog/SEI-CSS_cssh.PDF

image

Is there a resistor footprint script somewhere that I can add those resistors to?

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by strombom** [comment]
https://www.seielect.com/catalog/sei-css_cssh.pdf

Added script for the CSS/CSSH series: https://github.com/pointhi/kicad-footprint-generator/pull/112

image

**Comment by strombom** [comment]
Added fabrication refdes, centered component

image

image

image

**Comment by strombom** [comment]
Added 3D models: https://github.com/KiCad/kicad-packages3D/pull/266

**Comment by Shackmeister** [comment]
I think the look fine and the naming makes sense but I would like to get a second opinion (@poeschlr @evanshultz @jkriege2 )

in my own libraries I use this kind of shunt footprint with the "silk trace hack" to connect pad 1-3 and 2-4. how does other people do it? isolate a trace or live with the DRC error?
shunt

**Comment by Shackmeister** [comment]
Hi @strombom 
Great looking stuff :)
couple of notes:

- I agree with @evanshultz  regarding the name, the Resistance range does not make sense to have in the name.

- You seem to have included a few LED's in the PR, those should probably be in a seperate :)

**Comment by Misca1234** [comment]
This push have been taken over
https://github.com/KiCad/kicad-footprints/pull/1034

**Pull request closed without merging**
