### PR TITLE
Adding newly script generated footprints for Molex SPOX and Sabre connectors

### PR DESCRIPTION
**Pull request by poeschlr**
There are still two series of connectors missing.
For these two there where no scripts in the script repo. So i adapted similar generator scripts to generate SPOX and Sabre connectors.

I will add screenshots as i go along.

### CODE REVIEW

**Comment by poeschlr** [comment]
# SPOX vertical THT shrouded

The old SPOX footprints have a pitch of 2.54mm. I can't find any version of the SPOX connector on the molex webside that uses imperial grid sizes. @sonelu you added them originally (10 month ago). Where did you get the idea for them being 2.54mm grid?

Other changes:
- corrected drill size
- added pin 1 marker
- corrected CrtYd offset (No clue why it has been accepted this way. Old PR for reference: https://github.com/KiCad/Connectors_Molex.pretty/pull/32)

datasheet: http://www.molex.com/pdm_docs/sd/022035035_sd.pdf

screenshot from 2017-11-24 21-48-33
screenshot from 2017-11-24 21-48-03

**Comment by poeschlr** [comment]
# Sabre THT side entry

Similar to Mini-Fit Sr, with and without thermal vias.
New pads overlap in y direction (similar to Mini-Fit Sr)

screenshot from 2017-11-24 23-30-08
screenshot from 2017-11-24 23-27-32
screenshot from 2017-11-24 23-30-13

**Comment by poeschlr** [comment]
# Molex Sabre THT top entry

http://www.molex.com/pdm_docs/sd/431602102_sd.pdf

screenshot from 2017-11-25 00-37-38
screenshot from 2017-11-25 00-40-47

**Comment by poeschlr** [comment]
This is now also ready to merge.

**Comment by sonelu** [comment]
@poeschlr Sorry about the pitch. I have looked at the data sheet and indeed they are 2.5mm not 2.54. I have been using them for so long on normal 0.1'' pitch boards that I assumed they are 0.1''. Sorry about this.

**Comment by poeschlr** [comment]
No problem i was just worried that you have more information than i could find.

**Comment by SchrodingersGat** [comment]
Thanks Rene :)

**Pull request merged**
