### PR TITLE
add ONFI BGA-63_9x11mm_Layout10x12_P0.5mm

### PR DESCRIPTION
**Pull request by nerdyscout**
hi,

this adds a new footprint.

datasheet: https://www.digikey.de/products/de?keywords=TC58NYG1S3HBAI4
generic footprint info: http://www.onfi.org/-/media/client/onfi/specs/onfi_4_0-gold.pdf?la=en page 17

grafik

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by nerdyscout** [comment]
I made the initial commit from another computer, as I do not have access to this machine anymore I removed the sshkey. guess this is why CLA complains now... just not sure how to fix this.

**Comment by chschlue** [comment]
The SSH key shouldn't have anything to do with it, the email address associated with the commits is what's important.

**Comment by evanshultz** [comment]
For new BGA footprint contributions please use the generator at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_BGA. And if they're not manufacturer-specific (like there) please use the new support for IPC pad size derived from ball type and diameter.

**Comment by nerdyscout** [comment]
https://github.com/pointhi/kicad-footprint-generator/pull/623

**Pull request closed without merging**
