### PR TITLE
Create footprint for C&K switch PTS125SM43SMTR2-LFS

### PR DESCRIPTION
**Pull request by jayeshvora72**
This is a footprint for PTS125 series SMT switches from C&K. For example, this footprint is good for PTS125SM43SMTR2-LFS particular switch.

The URL to a datasheet for this footprint is:
https://www.mouser.in/datasheet/2/60/-523824.pdf

PTS125_PCB_layout

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jayeshvora72** [comment]
This PR is ready for review. The footprint looks like:

PTS125_Footprint

**Comment by poeschlr** [comment]
please align this to our new naming convention for buttons and switches. https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-450632899

SW_Push_1P1T_NO_[Manufacturer]_[Part number]

**Comment by jayeshvora72** [comment]
Hi @poeschlr , I have renamed the footprint as per your suggestion. Please review. Thanks.

**Comment by diegoherranz** [comment]
Thanks, @jayeshvora72. I was planning to review this one. I'll have a look after work.
Thanks, @poeschlr, for the naming comment.

**Comment by diegoherranz** [comment]
Many thanks for submitting this footprint. I hope it is the first of many.

Things reviewed which look OK:
- Overall size of the switch. I'm not sure from the datasheet about the dimensions of the chamfers. On the drawings it looks like it may be 9mm between chamfers but measuring a real switch, it seems to be a bit more than that. Either way, it's probably good enough.
- Location and size of the NPTH for the pegs
- Y location of pads
- Actuator circle radius
- Line thicknesses. Silkscreen is 0.15mm instead of the recommended 0.12, but it is OK for this part. 

Things which need fixing:
- [ ] There are multiple variants of this switch including THT/SMT and with/without pegs. The name needs to specify the variant used here which is SMT with pegs. Following the image below, I think we could call it `PTS125_PSMTR` (plus the naming convention referenced by @poeschlr).
- [ ] Pad sizes are bigger than the recommended size on the datasheet (1.5mm x 2mm)
- [ ] X location of pads doesn't match datasheet either
- [ ] Pin numbering should be 1, 1, 2 and 2 instead of 1, 2, 3 and 4, to match the SW_SPST symbol 
- [ ] Courtyard clearance is now 0.3mm. The standard is 0.25mm [KLC F5.3](http://kicad-pcb.org/libraries/klc/F5.3/). It will need to be updated anyway because of the pads adjustments. This is minor anyway.
- [ ] Silkscreen to copper clearance should be 0.2mm [KLC F5.1](http://kicad-pcb.org/libraries/klc/F5.1/). It is too tight at the moment.
- [ ] Description. Replace SMD by SMT. I wonder whether C&K Switches would be better than C&K Components. I think that the latter is the legal name but they are widely known as the former, what do you think about this one? Please add "with pegs". Also, could you add a link to the official datasheet at the end, separated by a comma? In summary "C&K Switches 1P1T SMT PTS125 Series 12mm Tact Switch with pegs, https://www.ckswitches.com/media/1462/pts125.pdf"

PTS125

Thanks!

**Comment by jayeshvora72** [comment]
Thanks for the review comments. I will hopefully work on them over next couple of days.

**Comment by jayeshvora72** [comment]
Thanks for the detailed review.

> Many thanks for submitting this footprint. I hope it is the first of many.
> 
> Things reviewed which look OK:
> 
> * Overall size of the switch. I'm not sure from the datasheet about the dimensions of the chamfers. On the drawings it looks like it may be 9mm between chamfers but measuring a real switch, it seems to be a bit more than that. Either way, it's probably good enough.
> * Location and size of the NPTH for the pegs
> * Y location of pads
> * Actuator circle radius
> * Line thicknesses. Silkscreen is 0.15mm instead of the recommended 0.12, but it is OK for this part.
> 
> Things which need fixing:
> 
> * [x]  There are multiple variants of this switch including THT/SMT and with/without pegs. The name needs to specify the variant used here which is SMT with pegs. Following the image below, I think we could call it `PTS125_PSMTR` (plus the naming convention referenced by @poeschlr).
> * [x]  Pad sizes are bigger than the recommended size on the datasheet (1.5mm x 2mm)
> * [x]  X location of pads doesn't match datasheet either
> * [x]  Pin numbering should be 1, 1, 2 and 2 instead of 1, 2, 3 and 4, to match the SW_SPST symbol
I have take care of this comment, however I just have a feeling that all pin numbers should be distinct. I was also thinking to add new symbol for this switch, something like:

image

My apprehension about distinct number for each pin is because, it should not so happen that in pcbNew with ratsnest, it would show a net connecting both the pins numbered 1 and similarly both the pins numbered 2 on the other hand. I haven't tried this, but I just have a feeling.

> * [x]  Courtyard clearance is now 0.3mm. The standard is 0.25mm [KLC F5.3](http://kicad-pcb.org/libraries/klc/F5.3/). It will need to be updated anyway because of the pads adjustments. This is minor anyway.
> * [x]  Silkscreen to copper clearance should be 0.2mm [KLC F5.1](http://kicad-pcb.org/libraries/klc/F5.1/). It is too tight at the moment.
> * [x]  Description. Replace SMD by SMT. I wonder whether C&K Switches would be better than C&K Components. I think that the latter is the legal name but they are widely known as the former, what do you think about this one? Please add "with pegs". Also, could you add a link to the official datasheet at the end, separated by a comma? In summary "C&K Switches 1P1T SMT PTS125 Series 12mm Tact Switch with pegs, https://www.ckswitches.com/media/1462/pts125.pdf"
> 
> PTS125
> 
> Thanks!

Additionally I also changed the silks width to 0.12.

Please review.

Thanks.

**Comment by jayeshvora72** [comment]
Please review. Thanks.

**Comment by poeschlr** [comment]
We will come to your contribution when we come to it.

**Comment by jayeshvora72** [comment]
Take your time. No hurry. :) Thanks.

**Comment by evanshultz** [comment]
1. `PTS125_PSMTR` includes the packaging (tape & reel). Also, we can only have one 3D model for the footprint and actuator shape, switch height, and pegs affect that. So we either need to wildcard things a lot and forget about a unique 3D model for now with `PTS125_SxxxxxPSM`, or go specific and pick one variant.
1. I believe we decided to not use an ampersand and go with "CK" for this vendor. https://github.com/KiCad/kicad-footprints/issues/759
1. Silkscreen to copper can be down to 0.12mm, per IPC 7351. KLC needs an update. 0.2mm is OK too.

Lastly, why not center the fab layer ref des and please use the "official" datasheet at https://www.ckswitches.com/media/1462/pts125.pdf?

**Comment by jayeshvora72** [comment]
Thanks @evanshultz for the review comments.

> 1. `PTS125_PSMTR` includes the packaging (tape & reel). Also, we can only have one 3D model for the footprint and actuator shape, switch height, and pegs affect that. So we either need to wildcard things a lot and forget about a unique 3D model for now with `PTS125_SxxxxxPSM`, or go specific and pick one variant.

I would go with a name "PTS125SX43PSMTR". This will help in our quest to have a unique 3D model as 43 stands for 4.3 mm actuator height. As per specs, SMTR stands for SMT Tape and Reel. If needed we can shorten it to SMT although my suggestion is to go with SMTR.
@diegoherranz , let me know if any change required here.

> 2. I believe we decided to not use an ampersand and go with "CK" for this vendor. #759

In the current footprint name "SW_Push_1P1T_NO_CK_PTS125_PSMTR", we do not have ampersand. I have used ampersand only in description. I hope that is okay.

> 3. Silkscreen to copper can be down to 0.12mm, per IPC 7351. KLC needs an update. 0.2mm is OK too.
> 
> Lastly, why not center the fab layer ref des and please use the "official" datasheet at https://www.ckswitches.com/media/1462/pts125.pdf?

I just centered the ref des of Fab Layer. I will commit it now. For the datasheet, we already have the same link as shown by you in the description of footprint.

**Comment by diegoherranz** [comment]
I've reviewed again and I think it looks good after your changes. I'm just waiting for the discussion on https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-492372648 which could affect the name and description. As soon as that's agreed, we can finish this one.

Thanks for the patience.

**Comment by jayeshvora72** [comment]
Thanks Diego for the update. We can wait for the said discussion to conclude.

**Comment by diegoherranz** [comment]
By the way, regarding which name to use for different 3D models, etc. I agree with @jayeshvora72 and I think that PTS125Sx43PSMTR should be optimum:

- I don't think we can split the `SMTR` in smaller chunks since the whole thing means SMT and Tape and reel.
- We need the `43` for the height
- We need the `P` for the pegs
- Force can be a wildcard `x` (please note that I prefer lowercase here since it's clearer to see it is a wildcard).

So as soon as https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-492372648 gets agreed (nearly there), we can use PTS125Sx43PSMTR

Thanks!

**Comment by jayeshvora72** [comment]
Very good! I will wait for [KiCad/kicad-symbols#580 (comment)](https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-492372648) to conclude and then will change the file name along with the footprint name. Thanks.

**Comment by diegoherranz** [comment]
I think we've reached an agreement on https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-495741787, even if it's because of lack of disagreement :)

That is using 1P1T on the name and including SPST in the keywords.

- [ ] Could you change the MPN portion of the name (and 3D model) to PTS125Sx43PSMTR as discussed?
- [ ] And add 1P1T to the keywords so that it lists both SPST and 1P1T?

Thanks!

**Comment by jayeshvora72** [comment]
> I think we've reached an agreement on [KiCad/kicad-symbols#580 (comment)](https://github.com/KiCad/kicad-symbols/issues/580#issuecomment-495741787), even if it's because of lack of disagreement :)
> 
> That is using 1P1T on the name and including SPST in the keywords.
> 
> * [x]  Could you change the MPN portion of the name (and 3D model) to PTS125Sx43PSMTR as discussed?
> * [x]  And add 1P1T to the keywords so that it lists both SPST and 1P1T?

Hi Diego,
I have taken care of both of above mentioned changes. Please review. Thanks.

**Comment by diegoherranz** [comment]
Looks good. Thanks for all the changes. Merging.

**Pull request merged**
