### PR TITLE
add  ESP-07S

### PR DESCRIPTION
**Pull request by dongly**
Add a WIFI module  : AI-Thinker ESP-07S
[https://wiki.ai-thinker.com/_media/esp8266/a018ps00.pdf](https://wiki.ai-thinker.com/_media/esp8266/a018ps00.pdf)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hello @dongly,

It looks like it's your first contribution to kicad-footprints repository. Welcome!

---

I verified your footprint and I would like to recommend some changes in order to be included in KiCad library.
- [ ]  Some dimensions looks incorrect. I've highlighted with the red color. The courtyard lines must be 0.25mm apart from Fab/Pad, instead 0.2mm. The height must be 17mm instead 17.2mm.
image

image

- [ ] RefDes (of the F.Fab layer) must be centered on component body (inside component outline) as per KLC F5.2 (http://kicad-pcb.org/libraries/klc/F5.2/). Additionally, I would like recommend to move RefDes of the Silk layer to top and the footprint name to bottom, like depicted in the following picture.

image

- [ ] Most of RF modules use the following style of mark on silk layer. I suggest to switch to this style, but it is just my personal recommendation. The style you've used is not wrong.

image

- [ ] My last recommendation is to remove the silkscreen between the pads. The length is too short, so it's best to remove them.

**Comment by dongly** [comment]
I have modified the footprint as required. Please check again.

**Comment by gmsotavio** [comment]
@dongly Are you still alive on this subject?

**Comment by gmsotavio** [comment]
@dongly please, reopen if you are still on this.

**Pull request closed without merging**
