### PR TITLE
Add Footprint support of USR USR-C322.

### PR DESCRIPTION
**Pull request by cybertale**
Signed-off-by: Song Qiang <songqiang1304521@gmail.com>

Add Footprint Support of USR USR-C322, which is a 3Mbps low power UART-WIFI Module.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing

https://www.usriot.com/download/WIFI/USR-C322-Hardware-Manual_V1.2.01.pdf

- [x] An example screenshot image is very helpful 

usr-mod

- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate

https://github.com/KiCad/kicad-symbols/pull/1236

- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @cybertale , thanks for contributing,

A few comments I have during my review:

- [ ] Can you move the device to "RF_WiFi" library (that's a new one in which we have all WiFi modules). If you haven it, it's because you need to solve branch conflict before by merging the master in your branch.
- [ ] I do not agree with fab layer dimensions, module is 18.22x26.65mm, not 18.62x26.54mm (distance between pins 28 and 29 is not correct).

Please can you fix above before I can continue the review ? Thanks.

Cheers,
Joel

**Comment by myfreescalewebpage** [comment]
Hi @cybertale are you still alive on this subject ? Thanks

**Comment by cybertale** [comment]
Very sorry for the late, this was a task of my classmate, my teacher assigned me other tasks that delayed the development of this PR, I'll get it down as soon as possible. Sorry for any troubles brought by my delay.

**Comment by myfreescalewebpage** [comment]
No worries @cybertale just wanted to know if you still want to work on it, take your time to complete it if required! Cheers, Joel

**Comment by cybertale** [comment]
@myfreescalewebpage Hi Joel, I moved pin 17-28 left for 0.05 and fixed the fab layer dimension conflict. But I didn't find the RF_Wifi directory in module(Maybe my fault, there was one but not now), so I left it in RF_Module.

**Comment by myfreescalewebpage** [comment]
Hi @cybertale thanks for the fixes here too!
- [ ] For the RF_WiFi, seems it does not exist at all at the moment, you can create it, just think to also modify "fp-lib-table" file
- [ ] Fab layer is OK for me know. But Silkscreen and CrtYd layer are not. Distance between Fab and Silkscreen lines should be 0.12mm and clearance around the device to the CrtYd layer should be 0.25mm. It is not exactly the right dimensions actually.
Joel

**Comment by cybertale** [comment]
@myfreescalewebpage Hi joel, I was planning to push them as two commits but empty folder is not allowed in git. This is also the reason why I cannot fix this ci error.

**Comment by myfreescalewebpage** [comment]
Thanks for the creation of RF_Wifi. It is still not yet correct for position of silkscreen and CrtYd lines. Here is an schema with expected dimensions:

Capture

**Comment by cybertale** [comment]
@myfreescalewebpage Hi Joel, how about this time?

**Comment by myfreescalewebpage** [comment]
I do not agree with the top CrtYd line, as shown on the following screenshot, the distance should be 0.25mm here too.

Capture

Else this is great for me on the other lines.
Joel

**Comment by cybertale** [comment]
@myfreescalewebpage Hi Joel, is this all right?

**Comment by myfreescalewebpage** [comment]
Thanks @cybertale looks great for me now :) Merging your contribution
Thanks for this job!

**Pull request merged**
