### PR TITLE
Seiko ms621 f

### PR DESCRIPTION
**Pull request by Misca1234**
When created the 3D model for battery holder Seiko MS621F 
https://www.sii.co.jp/en/me/files/2014/02/file_EXTENDED_PRDCT_SPEC_75_FILE_11.jpg

It seems that the battery circles was off 0.4, earlier origo was at -4.6 but should be 5.0

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1218

3D model push
https://github.com/KiCad/kicad-packages3D/pull/486

3D model script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/245

bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
The courtyard clearance is not quite right.

The land pattern it self is ok.

screenshot from 2019-01-16 22-07-18
screenshot from 2019-01-16 22-02-09

**Comment by Misca1234** [comment]
Move the courtyard a little bit out

bild

bild

**Comment by poeschlr** [comment]
The bottom side connection between the arc and the horizontal line is open (by more than 0.01mm which is the maximum tolerance for the DRC algorithm to work.)

**Comment by Misca1234** [comment]
Circle end have been moved

**Comment by poeschlr** [comment]
looks good now. Thanks

**Pull request merged**
