### PR TITLE
added 256-ball caBGA footprint for iCE40-HX8K-CT256

### PR DESCRIPTION
**Pull request by cyber-murmel**
according to Lattice PCB Layout Recommendations for BGA Packages (March
2017; Technical Note TN1074) page 4 and Package Diagrams (November 2017)
page 82

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
* [Lattice PCB Layout Recommendations for BGA Packages](http://www.latticesemi.com/~/media/LatticeSemi/Documents/ApplicationNotes/PT/PCBLayoutRecommendationsforBGAPackages.pdf?document_id=671)
* [Package Diagrams](http://www.latticesemi.com/-/media/LatticeSemi/Documents/PinPackage/PackageDiagrams.ashx?document_id=213)
- [X] An example screenshot image is very helpful
screenshot of PcbNew
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
https://github.com/KiCad/kicad-packages3D/pull/262
screenshot of the 3D model
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by cyber-murmel** [comment]
Travis says
```
  Violating F9.3
    3D model reference
    No 3D model provided
```
Do I needa 3D model?

**Comment by poeschlr** [comment]
About mask: If all pads should have this setting then set it in the footprint not the pads. (Travis will still complain but you can ignore that)

About 3d model:
You don't need to provide the model. You need to fill out the 3d settings such that a model can be added without touching the footprint. (It talks about 3d model reference)

**Comment by cyber-murmel** [comment]
Ok, now I have moved the solder mask property from the pads to the footprint settings and designed a 3D model 😃

**Comment by Shackmeister** [comment]
Hi @cyber-murmel 
Pin 1 chamfer on Fab should be which ever is smallest of 1mm or 1/4 of the shortest package side.
so In this case it should be 1mm instead of the 0.5mm you

**Comment by Shackmeister** [comment]
Hi @cyber-murmel 
Would it be possible for you to fix the pin 1 chamfer and the rotation in the 3D setting?
After this it should be ready to merge :)

**Comment by cyber-murmel** [comment]
Hey,
sorry it took me so long... I got distracted.
I applied all the fixes and even rebased onto the KiCad footprint upstream master :slightly_smiling_face:

**Comment by Shackmeister** [comment]
@cyber-murmel 

Thanks for the contribution! :D

**Pull request merged**
