### PR TITLE
added Footprint U-DFN2018-6

### PR DESCRIPTION
**Pull request by hamtam1**
https://www.diodes.com/assets/Package-Files/U-DFN2018-6.pdf

Signed-off-by: Martin Thomas <mtgithub@hamtam.de>

### CODE REVIEW

**Comment by Misca1234** [comment]
It helps the review process if you provide screen shoot of the footprints and their data,
see https://github.com/KiCad/kicad-footprints/pull/647

as an example

**Comment by poeschlr** [comment]
I might look into creating this via my scripts if @hamtam1 is ok with that.

**Comment by hamtam1** [comment]
@poeschlr Of course it is all right for me to create it via your script.

**Comment by Misca1234** [comment]
The script based version of this foot print 
https://github.com/KiCad/kicad-footprints/pull/788
have been merged, this push can be closed and deleted

**Pull request closed without merging**
