### PR TITLE
Add Samtec HLE connectors

### PR DESCRIPTION
**Pull request by twam**
Datasheets:
http://suddendocs.samtec.com/prints/hle-1xx-02-xx-dv-xe-xx-mkt.pdf, http://suddendocs.samtec.com/prints/hle-1xx-02-xxx-dv-xx-xx-xx-mkt.pdf
Screenshot:
screen shot 2017-12-21 at 19 07 23

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
Are these scripted?

**Comment by twam** [comment]
Yes.
I haven't pull-requested the generator script yet, as this depends on https://github.com/pointhi/kicad-footprint-generator/pull/102

**Comment by poeschlr** [comment]
Looks good. Thanks for this contribution.

For reference the dimensioned drawings i made for checking these:
screenshot from 2018-01-18 11-50-21

**Comment by twam** [comment]
I really like your sketches!

**Comment by poeschlr** [comment]
Thanks. If you want to create similar sketches i wrote a short tutorial over at the kicad forum that explains my workflow: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279

**Pull request merged**
