### PR TITLE
Wuerth MH: Anchor pad margin to avoid DRC errors

### PR DESCRIPTION
**Pull request by poeschlr**
Fixes problem with DRC found by @Shackmeister 

script https://github.com/pointhi/kicad-footprint-generator/pull/488

### CODE REVIEW

**Comment by poeschlr** [comment]
problem reported in discussion of https://github.com/KiCad/kicad-footprints/pull/1612 (after merge)

**Comment by Shackmeister** [comment]
I still get a DRC error between the custom pad and the NTPH

**Comment by poeschlr** [comment]
Ok strange my first tests showed no error but now i get one too. Well at least it is now only one error per footprint.

**Comment by Shackmeister** [comment]
merging as it's an improvement, hopefully we can get it fully resolved during V6

**Pull request merged**
