### PR TITLE
Amass xt30

### PR DESCRIPTION
**Pull request by jneiva08**
Connectors used on small copters

MR30PW-FB and MR30PW-M - https://www.tme.eu/en/Document/5e47640ba39fa492dbd4c0f4c8ae7b93/MR30PW%20SPEC.pdf

MR30PW

XT30PW-F and XT30PW-M - https://www.tme.eu/en/Document/ce4077e36b79046da520ca73227e15de/XT30PW%20SPEC.pdf

XT30PW

XT30U-F and XT30U-M - https://www.tme.eu/en/Document/3cbfa5cfa544d79584972dd5234a409e/XT30U%20SPEC.pdf

XT30U

XT30UPB-F and XT30UPB-M - https://www.tme.eu/en/Document/4acc913878197f8c2e30d4b8cdc47230/XT30UPB%20SPEC.pdf

XT30UPB

Another datasheets with all connectors from AMASS
https://datasheet.lcsc.com/szlcsc/Changzhou-Amass-Elec-MT30-M_C99903.pdf

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by jneiva08** [comment]
Updated MR30PW connectors, didn't noticed the numering behind of connector

MR30PW-FB
mr90-f

MR30PW-M
mr90-m

**Comment by SchrodingersGat** [comment]
For the MR30 connector the  pitch should be P3.50mm according to the spec sheet:

image

**Comment by jneiva08** [comment]
Probably forgot to change because reused XT30PW footprint.
Thanks for let me know

**Comment by SchrodingersGat** [comment]
Ok I think these look pretty good! I'm glad to see the Amass connectors getting some love.

Are you going to be able to add the 60 / 90 series too? :)

**Comment by SchrodingersGat** [comment]
I am not sure what is going on with Travis but there are no KLC issues against these footprints.

**Comment by jneiva08** [comment]
Thanks

**Comment by evanshultz** [comment]
FYI, this caught a lot of minor errors which will never get fixed unless somebody does it. So expect a deluge of PRs coming soon to make the fixes Travis picked up here.

**Comment by SchrodingersGat** [comment]
Has something changed in the Travis script to cause this? I thought it was only meant to check changes made in the PR.

**Pull request merged**
