### PR TITLE
Add LPF-C012303S Lightpipe

### PR DESCRIPTION
**Pull request by cp-aquila**
Add LPF-C012303S Lightpipe

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

grafik
* Datasheet: https://www.lumex.com/spec/LPF-C012303S.pdf
* I was not sure in which library I should put this; none seemed to fit, so I created a new one. I am open for suggestions and happy to move it to another lib.
* The additional circles on the F.Fab layer indicate the optimal LED-position
* Some of the coordinates of the lines are ugly; I drew this mixed imperial/metric. It this is an issue, I can rework it.

### CODE REVIEW

**Comment by cp-aquila** [comment]
Travis fails since the new library does not exist in fp-lib-table

**Comment by poeschlr** [comment]
@cp-aquila said:
> Travis fails since the new library does not exist in fp-lib-table.

Add the lib to the lib table then ;)

**Comment by poeschlr** [comment]
Sorry for the delay.

Is  it possible that the datasheet suggests either four rectangular cutouts or for SMD pads.

---

Also i just checked out the dimensions of your part and you do seem to have used imperial instead of metric like is both suggested by the datasheet and by kicad in general.

**Comment by cp-aquila** [comment]
Hi,

Thanks for the review. 
But I fail to understand what the suggested changes are (Pending changes label). Its not clear to me from the last comments.

**Comment by poeschlr** [comment]
If a datasheet contains both metric and imperial we will use the metric dimensions to check your part. I did that and it failed every measurement. So instead of making a drawing of only red dimensions i simply told you to use the metric dimensions.

**Comment by poeschlr** [comment]
Sorry it took so long, I kind of missed that this got updated.
Screenshot from 2019-09-22 16-54-59

**Comment by cp-aquila** [comment]
> 
> Sorry it took so long, I kind of missed that this got updated.

Nevermind, I was pretty slow in the beginning myself.
Thanks for the patience and review!

**Pull request merged**
