### PR TITLE
ECS-2520MV oscillator footprint

### PR DESCRIPTION
**Pull request by Shackmeister**
other pin 1 style ideas are very welcome, I think these parts quite hard.
Datasheet:
https://www.ecsxtal.com/store/pdf/ECS-2520MV.pdf

ecs_crystal

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by cpresser** [comment]
There is already a similar crystal in the libs: "Crystal_SMD_2520-4Pin_2.5x2.0mm"
It is basically the same device, but with slightly different pad geometry. 
You could copy its pin1 style, or just use that footprint :)

**Comment by poeschlr** [comment]
The courtyard clearance on the top side is smaller than all others. Could you fix that?
screenshot from 2019-01-01 14-30-14

**Comment by Shackmeister** [comment]
@poeschlr fixed

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
