### PR TITLE
Add BM78SPPS5XC2 bluetooth module footprint

### PR DESCRIPTION
**Pull request by Kev-J**
Added the BM78SPPS5XC2 bluetooth module from Microchip.

Associated symbol PR: https://github.com/KiCad/kicad-symbols/pull/2887
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/60001380C.pdf
Sans titre

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by myfreescalewebpage** [comment]
Hi @Kev-J , thanks for contributing,

Not the final review but some few comments right now:

- [ ] Name should be "BM78SPPS5xC2"
- [ ] 3D model should be "BM78SPPS5xC2.wrl"
- [ ] Datasheet link to be provided in the description
- [ ] Position of the pins not correct, for example pin 14, Y = 9.23mm instead of 9.2mm, etc. Please make a global checking and fix
- [ ] F.Silk: lines in the corner should be longer, they are very small.
- [ ] F.Silk: offset with F.Fab is generally 0.12mm
- [ ] F.Ctyd: right line is not vertical
- [ ] F.CrtYd: offset with F.Fab is generally 0.5mm for such kind of device

Cheers,
Joel

**Comment by Kev-J** [comment]
Hi Joel,

Thanks for the review. Sorry for the pins, I don't know what happened but everything was wrong =D

I did all the changes except for the F.CrtYd. If I apply 0.5mm clearance with F.Fab, F.CrtYd are overlaping with pads. I did 0.25 clearance with pads instead (as mentionned in KLC).

Cheers,
Kevin

**Comment by myfreescalewebpage** [comment]
> I did all the changes except for the F.CrtYd. If I apply 0.5mm clearance with F.Fab, F.CrtYd are overlaping with pads. I did 0.25 clearance with pads instead (as mentionned in KLC).

It's ok of course!

Last comment:
- [ ] At the top, the clearance for the F.CrtYd is 0.25mm between the F.Fab and F.CrtYd lines, not the F.SilkS and F.CrtYd lines

Joel

**Comment by Kev-J** [comment]
Sorry about that! It should be fixed now.

Kevin

**Comment by myfreescalewebpage** [comment]
Thanks, great job done here, no more comment.

**Pull request merged**
