### PR TITLE
Update CMakeLists.txt to install only .pretty

### PR DESCRIPTION
**Pull request by jsreynaud**
Modify installation to install only *.pretty directories.
All other directories (for example CMakeModules) should not be installed.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I assume you tested this?
@tijuca you seem to know something about make files, is this ok?

**Comment by jsreynaud** [comment]
I had tested it under Linux. Not yet under Windows/Macosx

**Comment by tijuca** [comment]
This is probably the better and correct approach as this installs only the specific folders. Currently I can't test this but I guess Jean-Samuel has done this. I can test this later once I'm home again.

My bad I haven't seen this issue from Jean-Samuel.

**Comment by poeschlr** [comment]
Thanks for looking into this.

**Pull request merged**
