### PR TITLE
Add Epson FA128 crystal footprint

### PR DESCRIPTION
**Pull request by aurabindo**
Signed-off-by: Aurabindo J <mail@aurabindo.in>

Add FA128 series of Crystals from Epson

Datasheet: https://support.epson.biz/td/api/doc_check.php?dl=brief_fa-238v_en.pdf

fa128

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aurabindo** [comment]
@poeschlr @jkriege2 bump!

**Comment by Shackmeister** [comment]
Hi @aurabindo are you still planning on coming back to this PR? :)

**Comment by Misca1234** [comment]
This push can be closed, both FA-238V and TSX3225 exist in Crystal.pretty

**Comment by Shackmeister** [comment]
Closing due to duplicate footprints

**Pull request closed without merging**
