### PR TITLE
Abracon ASPI-0630LR inductor

### PR DESCRIPTION
**Pull request by SchrodingersGat**
https://abracon.com/Magnetics/power/ASPI-0630LR.pdf

image

image

### CODE REVIEW

**Comment by poeschlr** [comment]
I hope you did not yet use this in production. The pads are much too close together. (Might be hard to solder)
And the courtyard clearance and y size of the body are also not quite right.

Screenshot from 2019-05-31 18-31-17

**Comment by SchrodingersGat** [comment]
Ah, great catch @poeschlr - I have adjusted the pad location and the courtyard.

**Comment by poeschlr** [comment]
The land pattern looks good now but there are newly introduced errors to the courtyard clearances.

Screenshot from 2019-06-01 18-41-39

**Comment by SchrodingersGat** [comment]
I have fixed some of those courtyard distances. The ones circled below I have left as 2.275mm as moving them to 2.25 places the lines off the required 0.01mm grid.

image

**Comment by poeschlr** [comment]
0.255 or 0.245 would be the grid points nearest to the required 0.25. I would suggest to choose 0.255

**Comment by SchrodingersGat** [comment]
I think this is OK now

**Comment by poeschlr** [comment]
Thanks

**Pull request merged**
