### PR TITLE
Add Panasonic Battery Vertical

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://industrial.panasonic.com/cdbs/www-data/pdf2/AAA4000/AAA4000D140.pdf

Footprint:
battery all

Measurements:
CR-1025
cr-1025-vsk

CR1220
cr-1220-vcn

CR-1632
cr-1632-v1an

CR-2025
cr-2025-v1ak

CR-2032
cr-2032-vs1n

CR-2354
cr-2354-vcn

CR-2450
cr-2450-van

CR-2477
cr-2477-vcn

CR-3032
cr-3032-vcn

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by aewallin** [comment]
I don't understand the "+" sign. Should it always be there (looks like some have it, some not), and should its size scale with the pin1-pad-size (or overall footprint size)?

**Comment by poeschlr** [comment]
The annular rings look a bit small for these. (you went down to the absolute minimum defined in KLC)
I would suggest to increase them as there is no real reason to be that small in this case.

**Comment by jneiva08** [comment]
@poeschlr, sorry to taking long time to fix it
Have already made the changes requested

**Comment by jneiva08** [comment]
@poeschlr one fast question to renaming the footprints
It should be like this:

Battery_CR2032-VS1N_Vertical_CircularHoles

Because the same battery can be vertical, horizontal both tht and horizontal smd
[Digikey link](https://www.digikey.com/products/en/battery-products/batteries-non-rechargeable-primary/90?k=CR-2032&k=&pkeyword=CR-2032&sv=0&v=11&sf=0&quantity=&ColumnSort=0&page=1&pageSize=500)

what is your opinion?

**Comment by poeschlr** [comment]
Yes that name would be good. But we might even want to add a suffix for the manufacturer name to be honest unless these are produced in the same manner by many different manufacturers

**Comment by poeschlr** [comment]
The hole size changes look good, now the only thing required is renaming the parts. Use your naming convention but include the manufacturer name as well.

`Battery_[Manufacturer]_CR2032-VS1N_Vertical_CircularHoles`

**Comment by poeschlr** [comment]
Thanks

**Comment by jneiva08** [comment]
Thanks, when have opportunity will try to add the exra pad on positive

**Pull request merged**
