### PR TITLE
Add Finder 36.11 10A SPDT relay footprint

### PR DESCRIPTION
**Pull request by chschlue**
Add Finder 36.11 10A SPDT relay footprint

Datasheet: https://gfinder.findernet.com/public/attachments/36/EN/S36EN.pdf
Symbol: https://github.com/KiCad/kicad-symbols/pull/1998

Violating F7.[23]: Component has no pin 1

3611foot

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Depends on https://github.com/KiCad/kicad-website/issues/418

**Comment by evanshultz** [comment]
1. Please add a documentation link to the description.
1. I think you can remove the "1" text.
1. Could you please rotate the pads to 0 degrees?
1. Please bump in the courtyard so it's 0.25mm offset from pads/body. Now it's 0.3mm:
image

**Comment by chschlue** [comment]
Done

**Comment by evanshultz** [comment]
Thanks! Looks great!

**Comment by antoniovazquezblanco** [comment]
AFAIK this does not conform to the newest naming convention https://github.com/KiCad/kicad-website/issues/418

This will probably require an update

**Comment by chschlue** [comment]
Sure, as soon as the powers that be can make up their minds regarding https://github.com/KiCad/kicad-website/issues/418

**Comment by poeschlr** [comment]
No matter what we decide it will only really come into effect with version 6. The reason we will hold new contributions to the new standard before that is to reduce the required work for getting everything done for v6.

**Pull request merged**
