### PR TITLE
Solder wire pad 1x01 SMD 1x2mm

### PR DESCRIPTION
**Pull request by persus**
Solder wire pad 1x01 SMD 1x2mm

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Please, add a screenshot of your creation! Thanks!

**Comment by persus** [comment]
image

My 'creation' I often see on professional SMD-PCBs which have solder wire-pads for user extensions. The already in the footprint library existing 5x10mm big solder wire-pad is way too big to be practical on small SMD-PCBs. :)

**Comment by poeschlr** [comment]
Select the virtual attribute as this does not need to appear in the pos file.
Do not include a 3d model in this case (does not make sense)

**Comment by persus** [comment]
Hi. Sorry I abandoned this pull request. If there is a way to reactivate this pull request, I would like it. I fixed the footprint as suggested.

- [X] Select the virtual attribute as this does not need to appear in the pos file.
- [X] Do not include a 3d model in this case (does not make sense).

**Comment by poeschlr** [comment]
thanks

**Pull request merged**
