### PR TITLE
Addition of XP Power RPA60-FW Series of DC-DC Converters

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of XP Power 60W Isolated DC-DC modules.

Datasheet: [RPA60-FW](https://recom-power.com/pdf/Powerline_DC-DC/RPA60-FW.pdf)

Symbol will be coming later - I'll update this when I'm done

image

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by jamesrlucas** [comment]
And I worked out how to do a drawing for you!

[Drawing.pdf](https://github.com/KiCad/kicad-footprints/files/4177895/Drawing.pdf)

**Comment by jamesrlucas** [comment]
And before someone asks me to do it - I've rotated the footprint & moved the fab text to the bottom.

**Comment by jamesrlucas** [comment]
All done for you!

**Comment by chschlue** [comment]
Thanks.

**Pull request merged**
