### PR TITLE
Add DirectFET S3C

### PR DESCRIPTION
**Pull request by chschlue**
Add DirectFET S3C

https://www.infineon.com/dgdl/Infineon-AN-1035-ApplicationNotes-v29_01-EN.pdf?fileId=5546d462533600a40153559159020f76#page=25

DirectFET_S3C

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@chschlue 
FYI it would be easier for me to review these all at once because I could check out one branch from you and then dimension all footprints. Maybe even better would be one PR with the missing footprints, to get them done first, and then another PR with the new but not needed footprints (the ones not listed at https://github.com/KiCad/kicad-footprints/issues/608).

The Y dimension of the total body height is +/-1.925mm and it should be +/-1.9mm. The courtyard height should then be +/-2.15mm. Are all of the "S" DirectFETs wrong at +/-2.18mm?

Otherwise looks good:
image

**Comment by poeschlr** [comment]
As a tip for your guys sanity: I would still limit a pull request of manual changes to about 10 footprints as it gets quite easy to burn out on much larger pull request reviews.

**Comment by chschlue** [comment]
@evanshultz @poeschlr 
Just a habit of keeping commits short and more or less atomic.
But no problem, I'll close the bad ones, merge them, fix them and open a new PR.

**Comment by evanshultz** [comment]
No no. Please. I have already reviewed some and do having the delta change is better. So please keep these PRs as they are.

Just in the future packing together more than one item is OK. Another option might be one PR is all "S" DirectFETs, one with all "M" DirectFETs, etc. Since we had already talked about me reviewing these I don't mind a bigger chunk.

**Comment by chschlue** [comment]
Fine by me.

**Comment by chschlue** [comment]
@evanshultz ping

**Comment by evanshultz** [comment]
Looks good. This is the first missing one to be added. Yay!

**Pull request merged**
