### PR TITLE
Revert "Close courtyard of Omron B3F-10xx tactile switch. (#1856)"

### PR DESCRIPTION
**Pull request by chschlue**
This reverts commit 83075a764e6093701af251cc23c2507fdc1f7be4.

See discussion in #1856 

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
This is undoing everything, not just the pin number change. I think because of the squash commit?

**Comment by chschlue** [comment]
Right. Every other way I could think of is ugly one way or another.
Will re-push the correct part after this has been merged.

**Comment by poeschlr** [comment]
Why not simply reassign the original pad numbers and call it a fix commit instead of a revert commit?

**Comment by chschlue** [comment]
Fine by me.

**Pull request closed without merging**
