### PR TITLE
Added script made foot print QFN-32-1EP_5x5mm_P0.5mm_EP3.7x3.7mm

### PR DESCRIPTION
**Pull request by Misca1234**
Added foot print QFN-32-1EP_5x5mm_P0.5mm_EP3.7x3.7mm

Needed for ESP8285
https://www.espressif.com/sites/default/files/documentation/0a-esp8285_datasheet_en.pdf

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1344

Foot print script push
https://github.com/pointhi/kicad-footprint-generator/pull/279

bild

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by poeschlr** [comment]
comments added to the script pull request

**Comment by Misca1234** [comment]
Changed to min/nom/max dimensioning

**Comment by Misca1234** [comment]
Changes made, see push
https://github.com/pointhi/kicad-footprint-generator/pull/279

**Comment by poeschlr** [comment]
looks good.

**Pull request merged**
