### PR TITLE
Ak300

### PR DESCRIPTION
**Pull request by Misca1234**
This the push of Altech AK300 serie
http://www.altechcorp.com/PDFS/PCBMETRC.PDF

All foot prints and 3D models are script made

Foot print push
https://github.com/KiCad/kicad-footprints/pull/1155

Foot print script push 
https://github.com/pointhi/kicad-footprint-generator/pull/236

3D model push
https://github.com/KiCad/kicad-packages3D/pull/478

3D model script push
https://github.com/easyw/kicad-3d-models-in-freecad/pull/242

Parameter file foot prints
```
AK300:
  description: "Altech AK300 serie connector"
  datasheet: "http://www.altechcorp.com/PDFS/PCBMETRC.PDF"
  tags: "Altech AK300 serie connector"
  manufacture: 'Altech' # Model name
  serie: 'AK300'        # Model name
  W: 12.5               # Package width
  H: 12.5               # Package height
  WD: 6.5               # > Y distance form pin center to package edge
  A1: 0.1               # package board seperation
  pin_number: [ 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24]  # Which pin configuration
  PE: 2.5               # Distance from edge to pin
  PS: 5.0               # Distance between pins
  PD: [1.0, 0.8]        # Pin size, [1.0] diameter 1 mm, [1.0, 0.8] rectangle 1.0x0.8
  PL: 4.5               # Pin length
  PF: 'rect'            # Pin form 'round' or 'rect'
  SW: 2.7               # Blender width
  DD: 1.5               # Drill diameter
  PD: 3.0               # Pad diameter
  rotation: 0           # Rotation if required
  dest_dir_3D_prefix: 'Connector_Altech.3dshapes'  # Destination directory

```

Parameter file 3D model

```
    'AK300': Params(   # ModelName
        #
        #
        #
        manufacture = 'Altech', # Model name
        serie = 'AK300',        # Model name
        W  = 12.5,              # Package width
        H  = 12.5,              # Package height
        WD  = 6.5,              # > Y distance form pin center to package edge
        A1 = 0.1,               # package board seperation
        pin_number = [ 2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],  # Which pin configuration
        PE = 2.5,               # Distance from edge to pin
        PS = 5.0,               # Distance between pins
        PD = [1.0, 0.8],        # Pin size, [1.0] diameter 1 mm, [1.0, 0.8] rectangle 1.0x0.8
        PL = 4.5,               # Pin length
        PF = 'rect',            # Pin form 'round' or 'rect'
        SW = 2.7,               # Blender width
        rotation = 0,           # Rotation if required
        body_color_key  = 'black body',         # Body color
        pin_color_key   = 'metal grey pins',    # Pin color
        dest_dir_prefix    = 'Connector_Altech.3dshapes'  # Destination directory
        ),

```

bild

bild

bild

bild

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I think the library for these should be renamed to TerminalBlock_Altech

Furthermore these are not really vertical entry. Looks more like 45 degree. See http://kicad-pcb.org/libraries/klc/F3.6/ I think from that it would mean the names would be `Altech_AK300_1x02_P5.0mm_45-Degree-Inverse`

I don't think we already have a footprint that uses this name so we could still think about better naming options (I am no longer so sure about the inverse part)

screenshot from 2018-12-13 21-00-09

**Comment by Misca1234** [comment]
Should I go with "Altech_AK300_1x02_P5.0mm_45-Degree" then ?

**Comment by poeschlr** [comment]
I am a bit unsure right now. We have a differentiation regarding positive and negative direction for the 45 degree version but not for horizontal versions. I think this differentiation is a bit too much so 45-Degree might indeed be enough. (Meaning the picture in the KLC would need to be exchanged.)

**Comment by Misca1234** [comment]
Then I wait for your final decision of the file name

**Comment by poeschlr** [comment]
I just removed the option for reversed 45 degree naming. So the name would be `Altech_AK300_1x02_P5.0mm_45-Degree` as suggested by you

**Comment by Misca1234** [comment]
Ok, great, then I wont change the name but move them to TerminalBlock_Altech

**Comment by Misca1234** [comment]
File name ending change to _45-Degree 
Directory change to TerminalBlock_Altech

Done

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
