### PR TITLE
Add finder relay socket 96.12 for type 56.32

### PR DESCRIPTION
**Pull request by Ekran**
purrint566
purrint567

according datasheet http://gfinder.findernet.com/public/attachments/56/DE/S56DE.pdf

*Replace this line with your commit message! Please provide a description of your pull request*

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
You advertise this PR as: includes 56.32 and 96.12 but it does only contain one footprint.

The silk outline should be outside of the body. (Because the Fab line should be the exact body outline, this would mean that you need to move the silk outside of the fab outline.)

Make pad A1square, add a 1mm chamfer to the top left corner and an L that hugs the top left corner on silk. ("Pad 1" marker)

Your screenshot is missing the courtyard rectangle. Please add a rectangle on the F.CrtYd layer with offset 0.25 relative to the fab outline.

**Comment by Ekran** [comment]
The 96.12 is the socket for PCB. The 56.32 is mounted in this socket. I will do the required changes.

**Comment by Ekran** [comment]
- silk outline is now outside the body

**Comment by poeschlr** [comment]
The courtyard rectangle should be larger then thy component by 0.25 mm in all directions. (offset 0.25mm all around)

**Comment by jkriege2** [comment]
Does the drawing on F-SilkS make sense? It will be covered/invisible after assembly, so probably we don't need it?

**Comment by jkriege2** [comment]
... we have the solenoid on all existing relays though (switches are sometimes there, sometines not, especially since varying switch-connections might use the same package/footprint)

**Comment by Ekran** [comment]
> Does the drawing on F-SilkS make sense? It will be covered/invisible after assembly, so probably we don't need it?
I use them in the printed documentations for PCBs. Ok, they can be moved from silk to fab.

**Comment by poeschlr** [comment]
Thanks for your effort. The remaining fixes have been done by @Misca1234 in the now merged pull request #773

**Pull request closed without merging**
