### PR TITLE
Add Vishay PowerPak 1212-8

### PR DESCRIPTION
**Pull request by jneiva08**
Datasheet: https://www.vishay.com/docs/72597/72597.pdf

Screenshot:

pp1212-8
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Nice dimensioned drawing. Thanks!

Would you mind using a single custom pad shape for pin 5 rather than overlapping pads? You can see examples where I've done this for other footprints at https://github.com/KiCad/kicad-footprints/pull/981.

**Comment by jneiva08** [comment]
Have changed to custom shape.

**Comment by evanshultz** [comment]
- Since there are single and dual versions add `_Single` to the end.
- Can you put some general search terms in the description like the other PowerPAK footprints?
- Also include https://www.vishay.com/docs/71656/ppak12128.pdf in the description.
- Please add keywords like other PowerPAK footprints.
- The fab lines should be 3.05x3.05mm since that's the body size ignoring the leads (like SOIC footprints). You should clear the silk under the side leds by at least the silk line width (0.12mm).
- Two dimensional issues: Right side pad total distance is only 2.385mm and width of the big section of pin 5 is not 1.725mm:
image

**Comment by jneiva08** [comment]
Hope i didn't miss anything. This time tried to make pad 5 with less points.

size

**Comment by evanshultz** [comment]
This looks great. Thank you!

**Pull request merged**
