### PR TITLE
UDFN-4_1x1mm_P0.65mm update

### PR DESCRIPTION
**Pull request by evanshultz**
Breaking apart https://github.com/KiCad/kicad-footprints/pull/981.

http://ww1.microchip.com/downloads/en/DeviceDoc/MIC550x-300mA-Single-Output-LDO-in-Small-Packages-DS20006006A.pdf

Added datasheet and updated footprint to match, using custom pad shapes.

image

Note that the courtyard was fixed after this was done.
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
Regarding the courtyard above: Rene said at https://github.com/KiCad/kicad-footprints/pull/981#issuecomment-455718226 to use 0.25mm. The footprint was already updated but I didn't see this comment before posting above.

**Comment by poeschlr** [comment]
Should we raname this footprint to make it clear that it includes an exposed pad? So `UDFN-4-1EP_1x1mm_P0.65mm_EP0.48x0.48mm`

**Comment by evanshultz** [comment]
That probably would have been a good idea. But it's an existing footprint, so is that reason enough to rename right now? Let me know if you want it that way.

**Comment by poeschlr** [comment]
It does not look like there is any symbol in the lib that has this footprint assigned as its default footprint. And because footprints are included in the pcb file we have a lot more wiggle room here.

**Comment by evanshultz** [comment]
Okey dokey. Done.

BTW, "Remove" in the commit message above should have been "Rename".

**Comment by evanshultz** [comment]
@poeschlr 
Sorry that I missed pinging you above. Is this ready?

**Comment by poeschlr** [comment]
thnaks

**Pull request merged**
