### PR TITLE
Creating a few parts popularly used with Eurorack synth modules

### PR DESCRIPTION
**Pull request by robkam**
Jack_3.5mm_QingPu_WQP-PJ398SM_Vertical.kicad_mod
was #820
Create footprint for mono vertical 3.5mm jack with oval pads and holes QingPu_WQP-PJ398SM
http://www.qingpu-electronics.com/en/products/WQP-PJ398SM-362.html (can't find a pdf)
mono oval holes qingpu_wqp-pj398sm

Jack_3.5mm_QingPu_WQP-PJ366ST_Vertical.kicad_mod
was #822
Create footprint for stereo vertical 3.5mm jack with oval pads and holes QingPu_WQP-PJ366ST 
http://www.qingpu-electronics.com/en/products/WQP-PJ366ST-364.html (no pdf)
stereo oval holes qingpu_wqp-pj366st

Jack_3.5mm_QingPu_WQP-PJ366ST_Vertical_CircularHoles.kicad_mod
was #823
Create footprint for stereo  vertical 3.5mm jack  with circular pads and holes QingPu_WQP-PJ366ST 
http://www.qingpu-electronics.com/en/products/WQP-PJ366ST-364.html (no pdf)
stereo circular holes qingpu wqp-pj366st

### CODE REVIEW

**Comment by robkam** [comment]
Create Potentiometer_Alpha_RD901F-40_Single_Vertical
was #910
Pin 1 is round because it's not a polarised component.
Plated through mounting pin holes because more robust
http://www.taiwanalpha.com.tw/english2016/p_e_062.htm although a more legible version is at https://www.taydaelectronics.com/datasheets/A-1848.pdf
potentiometer_alpha_rd901f-40_single_vertical

Create Potentiometer_Alpha_RD902F-40_Dual_Vertical
was #913
Pin 1 is round because it's not a polarised component.
Plated through mounting pin holes because more robust
http://www.taiwanalpha.com.tw/english2016/p_e_062.htm
potentiometer_alpha_rd902f-40_dual_vertical

**Comment by xxv** [comment]
I'd like to point out a PR I put up https://github.com/KiCad/kicad-footprints/pull/930 which corrects the pad names to match the standard KiCAD symbols.

**Comment by robkam** [comment]
Need to fix so that the jack pins are named to match symbol pins, see #1014

**Comment by robkam** [comment]
Fixed the pins to match symbols T,TN,S and T,R,S instead of 1,2,3

three

**Comment by robkam** [comment]
Somebody please review this ...

**Comment by poeschlr** [comment]
@evanshultz you assigned your self to this. Could you take a look?

**Comment by robkam** [comment]
I would have included C&K's subminiature switches here but there is a PR for them already at #1083

**Comment by evanshultz** [comment]
Please stop adding commits. It's a mess above. This PR had a vague title already, but let's leave it at connectors. Switches can go in another PR.

**Comment by robkam** [comment]
Then I'll have to delete the switches again.

**Comment by diegoherranz** [comment]
Do you think, @robkam, that you could split the pots to a different PR called "Add: Alpha 9mm pots" or similar? If you do so, I think I could review that one.

Then this PR could be renamed as: "Add: QingPu 3.5mm audio jacks"?

I think that would make it all clearer and more likely to get processed/reviewed earlier.

Thanks for your contributions. As a hint for future ones, please only send multiple components on the same PR if they are very related to each other, e.g. same manufacturer, same type/family, etc. It makes it all easier. Thanks!

**Pull request closed without merging**
