### PR TITLE
Add Fuseholder for littelfuse nano2

### PR DESCRIPTION
**Pull request by jneiva08**
Fuse holder and fuse SMD from littelfuse

Datasheet: https://www.littelfuse.com/~/media/electronics/datasheets/fuses/littelfuse_fuse_154_154t_154l_154tl_datasheet.pdf.pdf

Screenshot:
fuseholder

PR littelfuse nano2: https://github.com/KiCad/kicad-footprints/pull/1897

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi @jneiva08,

Thanks for your contribution!

Some remarks:

- [ ] The right name pattern according to KLC is `Fuseholder_[MAN]_[Series]_[MPN]`, so change the name of the footprint to `Fuseholder_Littelfuse_Nano2_154x`. Do not forget to change the 3D shape name too.

-  [ ] There is a minor error in the size of the left pad. Check the dimensioned drawing.

---
image
---
image
---

**Comment by jneiva08** [comment]
@gmsotavio have made all the fix requested

**Comment by gmsotavio** [comment]
Hi @jneiva08,

You have changed the position of the left pad when you should change the size of the pad in the X-direction. Reread my previous comment.

image

**Comment by jneiva08** [comment]
@gmsotavio 

The way it is both pads have same size and it is centered.
In your last comment says the show total length is 10.61 and should be 10.62, on the datasheet only says total length and (10.62mm) and the size of pad 2 (4.24mm), so pad 1 should be bigger 0.1mm

In the high for F.CrtYd have already incised to 2.77mm (the math gives 2.765mm) need to increase to 2.78mm?

**Comment by jneiva08** [comment]
Hi @gmsotavio any news in this PR?

**Comment by myfreescalewebpage** [comment]
Hello @jneiva08  I just looked at this PR, no more comment for me, merging.

**Comment by jneiva08** [comment]
Thanks for your time.

**Pull request merged**
