### PR TITLE
Adding Vishay_PowerPAK_SO-8

### PR DESCRIPTION
**Pull request by ki5libs**
[Datasheet](www.vishay.com/docs/73152/si7336adp.pdf)
powerpak
[3D package PR](https://github.com/KiCad/kicad-packages3D/pull/395)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Pads that are connected together must have the same pad number:

http://kicad-pcb.org/libraries/klc/F4.3/

**Comment by ki5libs** [comment]
@SchrodingersGat I've fixed that
powerpak
Should I remove pads 6,7 and 8 from [this symbol](https://github.com/KiCad/kicad-symbols/pull/924) respectively?

**Comment by SchrodingersGat** [comment]
Yes the pinout for the symbol must match the footprint :)

**Comment by Misca1234** [comment]
Any comment about the foot print name, otherwise I will merge the push

**Pull request merged**
