### PR TITLE
Add footprint for TI TCAN4550

### PR DESCRIPTION
**Pull request by HubertD**
Proposing this lack of better knowledge or ideas, especially regarding the footprint name.

This is my attempt of a footprint for the TCAN4550 SPI CAN Controller.
http://www.ti.com/lit/ds/symlink/tcan4550-q1.pdf
Symbol PR: https://github.com/KiCad/kicad-symbols/pull/1566

The package is what TI calls a QFN-20(RGY) or R-PVQFN-N20 with custom Thermal Pad.
Base package is described here: http://www.ti.com/lit/ml/mpqf116g/mpqf116g.pdf

What I did to create this footprint:
1. Create a VQFN package with ipc_noLead_generator.py from current kicad-footprint-generator repo (will post settings in a seperate comment)
2. Move/Resize pads 12, 13, 22, 23 so that they overlap with the EP  
3. Renumber pads to match datasheet, set pin number 21 for all structures belonging to the future EP
4. Add another "Pad 21" to fill the gap between the outer exposed pads

tcan4550 footprint

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by HubertD** [comment]
ipc_noLead_generator.py configuration used to create base footprint

```
VQFN-20-1EP_4.5x3.5mm_P0.5mm_TCAN4550:
  device_type: 'VQFN'
  #manufacturer: 'man'
  #part_number: 'mpn'
  size_source: 'http://www.ti.com/lit/ml/mpqf116g/mpqf116g.pdf'
  ipc_class: 'qfn' # 'qfn_pull_back'
  #ipc_density: 'least' #overwrite global value for this device.
  body_size_x:
    minimum: 3.35
    nominal: 3.5
    maximum: 3.65
  body_size_y:
    minimum: 4.35
    nominal: 4.5
    maximum: 4.65
  body_height:
    maximum: 1
  lead_width:
    minimum: 0.18
    maximum: 0.30
  lead_len:
    minimum: 0.3
    maximum: 0.5

  EP_size_x:
    minimum: 2.2
    nominal: 2.2
    maximum: 2.2
  EP_size_y:
    minimum: 3.2
    nominal: 3.2
    maximum: 3.2
  # EP_paste_coverage: 0.65
  EP_num_paste_pads: [3, 3]
  heel_reduction: 0.1 #for relatively large EP pads (increase clearance)
  #EP_size_limit_x: 2.7  #for relatively large EP pads (increase clearance)
  #EP_size_limit_y: 2.7  #for relatively large EP pads (increase clearance)

  thermal_vias:
    count: [3, 3]
    drill: 0.2
    # min_annular_ring: 0.15
    paste_via_clearance: 0.1
    # EP_num_paste_pads: [2, 2]
    EP_paste_coverage: 0.55
    # grid:
    # bottom_pad_size:
    # paste_avoid_via: True
  pitch: 0.5
  num_pins_x: 4
  num_pins_y: 8
  #chamfer_edge_pins: 0.25
  #pin_count_grid:
  #pad_length_addition: 0.5
  #suffix: '_Pad{pad_x:.2f}x{pad_y:.2f}mm_HandSolder'
  #include_suffix_in_3dpath: 'False'

```

**Comment by HubertD** [comment]
Just found the headline "RGY0020C" above the land pattern example in the TCAN4550 datasheet (p.139). 
Maybe that would be the most exact name for this footprint?

**Comment by HubertD** [comment]
Changed footprint name to what might be appropriate, given that there is a similar named "Texas_RGE0024H_EP2.7x2.7mm" already in the library.

Not sure about the EP-suffix though, since it reflects the size of the large pad in the center, not taking account of the additional pads connected to this EP.

tcan4550 footprint

Will provide a thermal vias variant if necessary and when this drawing is considered okay.

**Comment by SchrodingersGat** [comment]
I think that the original footprint name makes more sense as it conveys some information about the footprint.

```R-PVQFN-N20``` at least tells me that this is a QFN with 20 leads

In addition to including the EP size I think the footprint name should include other key factors such as body size and pitch (as per the KLC).

So I would suggest

```Texas_R-PVQFN-N20_3.5x4.5mm_P0.5mm_EP2.2x3.2mm```

**Comment by evanshultz** [comment]
Closing as this RGY footprint was merged at https://github.com/KiCad/kicad-footprints/pull/1460.

**Pull request closed without merging**
