### PR TITLE
create stereo oval holes QingPu_WQP-PJ366ST

### PR DESCRIPTION
**Pull request by robkam**
QingPU stereo 3.5 mm vertical jack WQP-PJ366ST suits symbol AudioJack3_Ground

http://www.qingpu-electronics.com/en/products/WQP-PJ366ST-364.html (no pdf)

jack_3 5mm_qingpu_wqp-pj366st_vertical

### CODE REVIEW

**Comment by poeschlr** [comment]
Another new pull request for the same part?

**Comment by robkam** [comment]
stereo version, the body is .5 mm wider

**Comment by robkam** [comment]
There should be four PRs but I can only see 3. I've lost one somewhere.

**Comment by poeschlr** [comment]
Ah ok. In future if you submit similar things you can put them into the same pull request. Or if you make different pull requests at least make it clear what the small difference is as it is hard to see otherwise.

**Comment by robkam** [comment]
I've no special requirement for the oval hole version.

**Comment by robkam** [comment]
stereo oval holes

**Pull request closed without merging**
