### PR TITLE
MountingEquipment: moving DIN Rail adapter

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Only moving the DIN Rail footprint and 3D following discussion at KiCad/kicad-footprints#1245. No other modification of the part.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
I seem to remember that this one is connected to a symbol. Does this need fixing as well?

**Comment by ferdymercury** [comment]
Yep, here it was done with MountingHole: https://github.com/KiCad/kicad-symbols/pull/1095

**Comment by myfreescalewebpage** [comment]
@poeschlr you are righ, but the symbol has no default footprint :)

**Comment by poeschlr** [comment]
In this case it is ok. I however feel the symbol has a way too specific footprint filter. I would not really suggest to list the screw size. Might be something that should be fixed.

**Comment by myfreescalewebpage** [comment]
@poeschlr probably yes, will see in the future depending of the footprints proposed by the community. Actually the available footprint is M3 only.

**Pull request merged**
