### PR TITLE
Added TDFN 10 Package with Exposed pad

### PR DESCRIPTION
**Pull request by jamesrlucas**
Addition of TDFN-10 2x3mm Packages with exposed pad (redone using footprint generator)

Drawing for [Package](https://pdfserv.maximintegrated.com/package_dwgs/21-0429.PDF)

Footprint Generator [PR 548](https://github.com/pointhi/kicad-footprint-generator/pull/548)
Submitted for symbol [PR 2360](https://github.com/KiCad/kicad-symbols/pull/2360)

image

image
---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chschlue** [comment]
Please use the generator at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON for standardized packages like this.

**Comment by jamesrlucas** [comment]
I have no clue where to start with that - I'll have a look, but it's a bit beyond what I've done before (I have zero python experience for starters)

**Comment by chschlue** [comment]
It's mostly adding dimensions from the datasheet to https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml and running `ipc_noLead_generator.py size_definitions/dfn.yaml`.
Preliminary documentation is at https://github.com/pointhi/kicad-footprint-generator/blob/c585351479201b0d1a67415c078dc6e728c645d6/scripts/Packages/Package_Gullwing__QFP_SOIC_SO/Readme.md and don't be afraid to ask if anything remains unclear.

**Comment by jamesrlucas** [comment]
Right, I think I've done it - I'll submit a PR on the footprint generator side of things. Do I also need to submit the generated footprints here?

**Comment by chschlue** [comment]
Yes.
Please also cross reference generator and FP PRs.

**Comment by jamesrlucas** [comment]
Right, all done! I deleted the old footprint I drew manually, and replaced with those from the footprint generator. (I also did a thermal vias footprint)

Thanks for your help!

**Pull request merged**
