### PR TITLE
Add Texas_S-PVQFN-N20_EP2.7x2.7mm

### PR DESCRIPTION
**Pull request by stephf0716**
matching footprint(s) for DRV8662 package
http://www.ti.com/lit/ds/symlink/drv8662.pdf
image
image

Link to symbol PR: https://github.com/KiCad/kicad-symbols/pull/162

### CODE REVIEW

**Comment by Shackmeister** [comment]
@poeschlr would you mind if we supply the TI specific packages both with and without ThermalVias?

**Comment by poeschlr** [comment]
@Shackmeister look again at the contribution. @stephf0716 does supply both a version with and one without thermal vias.

**Comment by Shackmeister** [comment]
Hmm wasn't fast enough to remove my comment :) noticed it a minute ago

**Comment by poeschlr** [comment]
Thanks for this contribution. Everything looks good now.

**Pull request merged**
