### PR TITLE
Minor footprint fixes (3D models and footprint name)

### PR DESCRIPTION
**Pull request by evanshultz**
When the footprints were moved to this repo I made a queue of issues to be fixed later. Now is later.
- Correct "Pitch" to "P".
- Add missing 3D models.
- Rename a couple footprints which seemed to be manufacturer-specific and had unhelpful suffixes. I also made a few corrections to those footprints to match the TI datasheet at http://www.ti.com/lit/ds/symlink/tps5430.pdf. (Note that TPS5430DDA exists in Regulator_Switching.lib, but it's using a different footprint. And that footprint's prefix is `Texas`, not `TI`. Sigh.)

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
Unless there are objections, I'd prefer to merge this as-is.

**Comment by poeschlr** [comment]
The texas_hsop-8 footprints have strange EP pad stackup. Please use the same as we use for all other such packages.

Especially problematic is the SMD pad with "All copper layers".

**Comment by evanshultz** [comment]
@poeschlr 
Do you have time to finish reviewing this? Anybody else is welcome as well. https://github.com/KiCad/kicad-symbols/pull/512 could use a footprint that is getting changed in this PR.

**Comment by poeschlr** [comment]
It is strange that the texas footprints have only one paste pad but as this is the suggestion from texas i will merge it as is. Thanks for your work.

**Pull request merged**
