### PR TITLE
add Oscillator_SMD_Abracon_ASCO-4Pin_1.6x1.2mm

### PR DESCRIPTION
**Pull request by penoud**
add Oscillator_SMD_Abracon_ASCO-4Pin_1.6x1.2mm footprint. Based on https://abracon.com/Oscillators/ASCO.pdf
------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
https://abracon.com/Oscillators/ASCO.pdf
- [X] An example screenshot image is very helpful 
image
image

- [X] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
I will create the PR soon and update this with the link.
- [X] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
From the screenshot i can already tell that this should be rotated by 90 degree in clockwise direction

**Comment by penoud** [comment]
Rotate component
image
image

**Comment by Misca1234** [comment]
Just some minor details,
can you rotate the pads 90 degree so they are "naturally rotated 90" (ans switch place of the X and Y sizes), I guess you last push included a rotation of the whole symbol.

otherwise it looks good

**Comment by poeschlr** [comment]
Sorry for the long delay. It seems this was kind of forgotten.

Please add a pin 1 marker on the fab layer. (chamfer the corner nearest to it. chamfer size = 25% of shortest outline length)

Otherwise everything looks to be good.
screenshot from 2018-12-31 21-20-13

**Comment by poeschlr** [comment]
The diagonal line you added is completely off grid and does not agree with the line closest to its end.

Version 5 has a bug where it does this when dragging an endpoint with the angle lock (crtl key). This is fixed in nightly. I would suggest you go into the lines properties menu and fix it there.

**Comment by poeschlr** [comment]
Looks good now. Thanks

**Pull request merged**
