### PR TITLE
Add Taiyo-Yuden NR 10050 inductor footprint with handsoldering variant.

### PR DESCRIPTION
**Pull request by reportingsjr**
This adds a standard footprint and a handsoldering variant for Taiyo-Yuden NR 10050 SMD inductors.

For the handsoldering variant I extended the pads a similar amount as the Taiyo-Yuden_NR-80xx_HandSoldering footprint vs the normal (1.4mm extra for each pad).

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing: https://ds.yuden.co.jp/TYCOMPAS/or/specSheet?pn=NR10050T1R3N
- [x] An example screenshot image is very helpful 
taiyo yuden nr 10050 handsoldering footprint
taiyo yuden nr 10050 footprint
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
No 3d model created for this
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by gmsotavio** [comment]
Hi @reportingsjr,

I'm not reviewing this right now, but consider to include the body size in the name.

**Comment by reportingsjr** [comment]
@gmsotavio Good catch on the courtyard! I pushed it out to be 0.25mm beyond the pads as it should have been.

I also added the inductor body size in the name of the footprint.

**Comment by reportingsjr** [comment]
New screenshots:
NR10050
NR10050 handsoldering

**Comment by gmsotavio** [comment]
Hi @reportingsjr ,

Some thoughts about your contribution:

- [ ] There are some bad dimensions on the Fab. layer. Check the dimensioned drawing bellow.

image

image

- [ ] Something is inverted here
image
- [ ] Change the X coordinate of the RefDes (Silk) to 0.
- [ ] Datasheet link is missing in the description
- [ ] Usually, the dimensions in the name follow this rule: _WxLmm. Please add `_9.8x10.0mm` to the footprint name, rather than `_10.0x9.8mm`.
- [ ] Remove footprints you do not want from the PR. You are submitting 2 footprints, but there are 4 files in the PR.

**Comment by reportingsjr** [comment]
> Hi @reportingsjr ,
> 
> Some notes about your contribution:
> 
> * [ ]  There are some bad dimensions on the Fab. layer. Check the dimensioned drawing bellow.
I looked at your dimensioned drawing and I'm not sure what is wrong? I put a very rough outline in, with the max dimensions at 10.3x10.3mm. What do you think needs to change?

> * [ ]  Something is inverted here
Yep, I thought the drawing on the right was a bottom view. It looks like it isn't.
> * [ ]  Change the X coordinate of the RefDes (Silk) to 0.
Fixed
> * [ ]  Datasheet link is missing in the description
Fixed
> * [ ]  Usually, the dimensions in the name follow this rule: _WxLmm. Please add `_9.8x10.0mm` to the footprint name, rather than `_10.0x9.8mm`.
Fixed
> * [ ]  Remove footprints you do not want from the PR. You are submitting 2 footprints, but there are 4 files in the PR.
Looks like I forgot to git rm them. Fixed!
> **Edit**
> 
> * [ ]  Change 3D shape names to take into account the body dimensions.
Fixed.

Thanks for being so thorough! I wish I did this more frequently so I could become more familiar with all of the rules.

**Comment by gmsotavio** [comment]
Hello @reportingsjr ,

Thanks for addressing the recommended changes! Asking your question:

> I looked at your dimensioned drawing and I'm not sure what is wrong? I put a very rough outline in, with the max dimensions at 10.3x10.3mm. What do you think needs to change?

Usually, the fab outline should represent the nominal dimensions of the components. Some manufacturers don't provide the nominal values, only the maximum. Less often, they provide a mix of maximum and nominal values, such as seen in this PR https://github.com/KiCad/kicad-footprints/pull/1721. In your case, the nominal values are provided in the datasheet, so i think that nominal values are the right way to go. I have checked the KLC and I found no information about Fab outline, but your question has already occurred before (https://github.com/KiCad/kicad-footprints/issues/1095). The best answer I've found from that thread:

"_The requirement for nominal dimensions comes from industry standards. The reason for this is that maximum tolerances are normally never really reached (very low probability)
It is also hard to determine what maximum means. Especially for long chains of dependent dimensions._"

_Originally posted by @poeschlr in https://github.com/KiCad/kicad-footprints/issues/1095#issuecomment-444194815_

If you do not agree, drop me a line.

**Comment by reportingsjr** [comment]
Ok, that makes sense. I've pushed the fix for that.

**Comment by gmsotavio** [comment]
- [ ] Courtyard isn't quite right
image

- [ ] Please, change the coordinates of RefDes (Fab) to (0,0).

**Comment by gmsotavio** [comment]
- [ ] Courtyard isn't quite right
image

- [ ] Please, change the coordinates of RefDes (Fab) to (0,0).

**Comment by reportingsjr** [comment]
Ok, I changed all of the text to be centered on the X axis and put the Fab ref des at (0,0). I also corrected the courtyard size.

For what it is worth I didn't move the silk which is now just outside of the courtyard, as <0.25mm from the component seems too close. I didn't see anything in the KLC about this and I see other components with silk outside of the courtyard, so hopefully that is ok!

**Comment by gmsotavio** [comment]
> For what it is worth I didn't move the silk which is now just outside of the courtyard, as <0.25mm from the component seems too close. I didn't see anything in the KLC about this and I see other components with silk outside of the courtyard, so hopefully that is ok!

You are right. KLC tells us nothing about silk offset from fab outline or anything about silk lines being inside or outside the courtyard layer. It is allowed to do what you did. Don't worry. I had that same doubt some time ago. I found a discussion (https://github.com/KiCad/kicad-footprints/issues/1095) where @evanshultz says "_...at the standard offset of silk lines from fab lines used in most of the librarian-developed (or -inspired) scripts use 0.11mm. This means the edges of the fab and silk lines touch._" I would like to hear @poeschlr and @evanshultz, what they think about add that rule as a silk requirement to a future revision of KLC. If we apply this rule into your footprint it becomes:

image

But as I said, at this time, this is not mandatory. I checked your footprint, and everything seems good for me now.

**Pull request merged**
