### PR TITLE
Add Infineon PG-LLGA-5-1

### PR DESCRIPTION
**Pull request by evanshultz**
https://www.infineon.com/cms/en/product/packages/PG-LLGA/PG-LLGA-5-1/

The drawing appears to show mask removed under the entire part body, so I made a polygon on F.Mask. Am I misinterpreting the footprint drawing?

FreeCad source file at https://github.com/KiCad/kicad-footprints/pull/972.

Cu + Mask:
image

Paste:
image

I don't know why the Cu donut is offset when importing the footprint but at least the dimensions are correct.
image

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by evanshultz** [comment]
I'm not sure why Travis thinks the footprint is not centered, but all pads are within the fab outline and the fab outline is centered so this is bogus.

**Comment by easyw** [comment]
@evanshultz 

> I don't know why the Cu donut is offset when importing the footprint but at least the dimensions are correct.

this is a bug in ksu reloading the fp inside FC .. I need to fix it 😉

**Comment by evanshultz** [comment]
@easyw 
Thanks for the confirmation. Would you like me to make any issues at https://github.com/easyw/kicadStepUpMod or are you tracking everything?

**Comment by poeschlr** [comment]
The center calculation only takes pads into account not fab outlines. It might be beneficial to change that.

**Comment by easyw** [comment]
> Thanks for the confirmation. Would you like me to make any issues

it should be fixed now [PR](https://github.com/easyw/kicadStepUpMod/commit/a99ba74cb973243c8072a9799413dea5b4025687)

**Comment by poeschlr** [comment]
It seems this package is specialized for microphones. Meaning the Sensor_Audio lib might be a better fit.

Why is there a polygon on the mask layer?
https://www.infineon.com/dgdl/Infineon-Board+Assembly+Recommendations-Open+Sensors+Leadless-P-v04_00-EN.pdf?fileId=5546d462602a9dc8016045cdeb5f1a47#page=8 shows soldermask like normal.

Even if soldermask needs to be removed it should be done using a mask only pad instead of a polygon.

**Comment by evanshultz** [comment]
Thanks for reviewing! The mask polygon is there because I mis-interpreted the footprint drawing. Fixed now by adding F.Mask t o all 5 pads and removing the polygon, and I also footprint moved to the library you mentioned above. Anything else?

**Comment by poeschlr** [comment]
Looks good, thanks

**Pull request merged**
