### PR TITLE
TRANSFORMER: Fix Wurth spelling

### PR DESCRIPTION
**Pull request by myfreescalewebpage**
Everything is in the title.
No modifications of the footprint itself, just fix the name of the manufacturer.

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by chschlue** [comment]
This was actually correct before (see https://en.wikipedia.org/wiki/Diaeresis_(diacritic)#Printing_conventions_in_German), but I agree that it's far from obvious.
We should probably also "fix" Mounting_Wuerth and all the other Wuerth stuff in the long run.

**Comment by evanshultz** [comment]
Search around and you'll see discussions about this. I recall we mostly relied on what the vendor called themselves if diacritics weren't used and also the input of German-speaking librarians. Closing.

**Comment by poeschlr** [comment]
Even the webaddress of würth uses wuerth: See https://www.we-online.com/web/en/wuerth_elektronik/start.php

We can however add the alternative spelling to the keyword list such that it appears with a search

**Comment by myfreescalewebpage** [comment]
I wasn't aware of this kind of details. I was the author of this symbol and the associated footprint and I realized I have used this spelling but the logo of Wurth is the following:

WE-Logo_2007_A4_RGB

Are you sure we want to keep the existing symbol and footprint ?

**Comment by myfreescalewebpage** [comment]
Also just notice this new PR: https://github.com/KiCad/kicad-footprints/pull/2256/files. The name of the file is "Wurth"...

**Comment by poeschlr** [comment]
Yes i am positive. And their logo is not wurth its würth. The ü is a special sound. And with the knowledge of ue being ü have a guess what the oe in my name stands for ;).

**Comment by chschlue** [comment]
My guess: Ρενε Ποισχλ, transcribed from Greek to Pöschl?

pic_gall_a_0004434_int

Perhaps we should consistently switch to ligatures. Phœnix. Wᵫrth.

Sorry for derailing this thread :)

**Comment by myfreescalewebpage** [comment]
Interesting details :) thanks @poeschlr and @chschlue 

@chschlue this include special characters which is not so good in computing science...

**Comment by evanshultz** [comment]
@myfreescalewebpage 
I think that is a joke above. Using `ue` instead of `ü` was done to avoid 'special' characters.

**Comment by chschlue** [comment]
Jokes aside, adding `wurth` keywords / tags sounds like a good idea to me to improve searchability.

Compare https://trends.google.com/trends/explore?q=jagermeister and https://trends.google.com/trends/explore?q=lowenbrau for Jagërmeister and Lowënbraü, respectively, for example.

Note: I'm not suggesting this for Phoenix. As @poeschlr already pointed out, they never use Phönix anywhere anymore.

**Pull request closed without merging**
