### PR TITLE
Moved the courtyard to outside the pads

### PR DESCRIPTION
**Pull request by Misca1234**
After removing some trailing histy things on my local branch a push of an old branch 
https://github.com/KiCad/kicad-footprints/pull/638

It ended up here

They look like this now

bild

bild

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [ ] Provide a URL to a datasheet for the footprint(s) you are contributing
- [ ] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
You setup the pull request wrong. It wants to merge in your old branch that you created on the official repo instead of into master. I changed that for you.

**Comment by poeschlr** [comment]
You setup the pull request wrong. It wants to merge in your old branch that you created on the official repo instead of into master. I changed that for you.

**Comment by poeschlr** [comment]
Looks good, thanks

**Comment by evanshultz** [comment]
Not a big issue, but the silk at each corner could go closer to the pads.

**Comment by evanshultz** [comment]
@Misca1234 
This PR added a README.md to RF_GPS.pretty. I checked a few other repos and don't see a readme file. Was this an accident?

**Comment by Misca1234** [comment]
> This PR added a README.md to RF_GPS.pretty. I checked a few other repos and don't see a readme file. Was this an accident?

I have an extremely faint memory of "do everything right" in this push by also adding a readme file, which I see now that I do not have anywhere else, especially in all the 3D model push.

Shall I remove it ?

**Pull request merged**
