### PR TITLE
Add Molex Micro-Fit 3.0 THT Vertical Headers

### PR DESCRIPTION
**Pull request by twam**
Datasheets:
http://www.molex.com/pdm_docs/sd/430450212_sd.pdf
http://www.molex.com/pdm_docs/sd/436500215_sd.pdf

Screenshots:
screen shot 2017-12-14 at 20 18 19
screen shot 2017-12-14 at 20 18 27

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [ ] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by poeschlr** [comment]
The single pin, single row version you add is not produced by Molex.
And you seem to multiply the number of pins in the MPN with 2 for the single row variant.

There are also some minor problems with the footprints:
screenshot from 2017-12-15 00-42-04

You could also elongate the pads for the single row connectors. (might make it easier to solder these.)

**Comment by twam** [comment]
Thanks for the thorough review!

How did you do the nice drawing? Is there an (semi-)automatic way?

Update footprint screenshots:
screen shot 2017-12-16 at 16 06 31
screen shot 2017-12-16 at 16 06 20

**Comment by poeschlr** [comment]
The drawings are made using kicad stepup to get the footprint into freecad and then i use the drawing dimensions workbench to measure stuff. (There is also the technical drawing workbench you could try.)

**Comment by poeschlr** [comment]
Looks good thanks

**Pull request merged**
