### PR TITLE
Coilcraft xfl4020

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Added the footprint for the Coilcraft XFL4020 Series of Inductors

Datasheet : https://www.coilcraft.com/pdfs/xfl4020.pdf

screenshot from 2017-12-27 15-01-29

Going to check Travis output here

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
I've never created a 3D file as yet. I'll look into it...

**Comment by poeschlr** [comment]
It is not required to supply the 3d model it self. But the footprint needs to be setup to be able to add one without the need to touch it again.
This means: Fill out the model path `${KISYS3DMOD}/[lib name].3dshapes/[footprint name].wrl`, set the scale to 1, offset and rotation to 0

**Comment by johnfwhitmore** [comment]
Added a reference to the 3D Model for the component.

Thanks for your help with that, know for the next time.

**Comment by poeschlr** [comment]
Thanks for your contribution

**Pull request merged**
