### PR TITLE
Add SIL0008D MicroSiP Package

### PR DESCRIPTION
**Pull request by awygle**
Adds the SIL0008D MicroSiP package used in TI's TPS82130 and similar parts.

Datasheet is http://www.ti.com/lit/ds/symlink/tps82130.pdf

image

Wasn't sure about the Pin 1 indicator, or even whether this goes in Packages_LGA at all... please feel free to advise.

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by awygle** [comment]
Symbol PR is https://github.com/KiCad/kicad-symbols/pull/921

**Comment by Misca1234** [comment]
Is the provided foot print in this push from the script generation in push 
https://github.com/pointhi/kicad-footprint-generator/pull/184 ?

If so, all looks good

**Comment by Misca1234** [comment]
@awygle 
What do you say about making your foot print script based as well?

**Comment by awygle** [comment]
I have mixed feelings, frankly, but I'm open to giving it a shot. I'd like to see the script changed to more closely match both the KLC and the manufacturer recommendation (which I'm willing to do/help with). I'm a bit bogged down at the moment but I'll go to script based for this PR and the CM49 one sometime this week.

**Comment by Misca1234** [comment]
> I have mixed feelings, frankly, but I'm open to giving it a shot. 
> I'd like to see the script changed to more closely match both the KLC and the manufacturer 
> recommendation (which I'm willing to do/help with). I'm a bit bogged down at the moment but I'll go 

The nice thing with the scripts is that we only examine the parameters you have added to the .yaml file, it is understood and assumed that the scripts always do right
(if they do wrong, we just correct the script and remake all the depending foot prints)

It works like this
1. You checkout the repository  https://github.com/pointhi/kicad-footprint-generator
2. You find the correct library and edit the right .yaml file
3. Generate the .kicad_mod file
4. Make a push to the https://github.com/KiCad/kicad-footprints with the .kicad_mod
5. Make a push to https://github.com/pointhi/kicad-footprint-generator with the generated .yaml file

We will never review the .kicad_mod file itself, only the .yaml file (add cross links between the both pushes so they are easy to find)

In your case you should update the file with the dimensions of your desired foot print
https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_LGA/lga_definitions.yaml

You generate the foot print in directory
```
kicad-footprint-generator/blob/master/scripts/Packages/Package_LGA/
python ipc_lga_layoutBorder_generator.py lga_definitions.yaml
```

**Comment by Misca1234** [comment]
@awygle 
Have you giving it a shoot ?

**Comment by poeschlr** [comment]
I assigned myself as i will look into the script. Right now the LGA generator is kind of a weak spot. (It has not been updated to my latest discoveries regarding correct handling of tolerances.) So this one can be used as an excuse to fix that.

**Comment by poeschlr** [comment]
Scripted alternative available in https://github.com/KiCad/kicad-footprints/pull/1263

**Pull request closed without merging**
