### PR TITLE
new diode footprints (cathode marked with a K, which is better visible than the old marks)

### PR DESCRIPTION
**Pull request by jkriege2**
- K is now marked by a letter + removed the old diode drawing as it was invisible after assembly anyways
- script-based: https://github.com/pointhi/kicad-footprint-generator/pull/83
- based on this discussion: https://github.com/KiCad/kicad-footprints/issues/78
- also fixed 3D models: https://github.com/KiCad/kicad-packages3D-source/pull/64 and https://github.com/KiCad/kicad-packages3D/pull/161

2017-11-24 21_42_56-pcbnew d__temp_test kicad_pcb
2017-11-24 21_42_46-pcbnew d__temp_test kicad_pcb
2017-11-24 21_42_30-pcbnew d__temp_test kicad_pcb

### CODE REVIEW

**Comment by poeschlr** [comment]
Could you also take a closer look at the positioning of the second reference designator? Currently it does interfere with other features of the fab layer. (I am assuming here that you adapted the scripts if you made this changes by hand we can merge as is.)

**Comment by evanshultz** [comment]
It might be nicer to put a "K" or an "A" closest to the pin _without_ the diode body there. That may avoid putting the marker under a nearby  part. So for example, in the first screenshot above an "A" would go by pin 2 instead of a "K" by pin 1.

Another option could be to fill the circle if it's over the cathode pin and not fill the circle if it's over the anode pin. This isn't as clear, and maybe a bad idea, but it just popped into my head.

**Comment by jkriege2** [comment]
Hi!

just making the circle filled is also not really visible after assembly, assuming the diode covers the circle, but marking A instead of K seems a great idea, so I stuck with that ...

Aso I did some other adjustments!

## horizontal diodes: %R-placement on F.Fab
2017-11-25 12_28_41-footprint editor no active library
2017-11-25 12_28_23-footprint editor no active library


## vertical diodes: %R-FFab-label inside or over SilkS-REF-label + A/K placement where space permits
2017-11-25 12_49_49-footprint editor no active library
2017-11-25 12_47_28-footprint editor no active library
2017-11-25 12_47_18-footprint editor no active library
2017-11-25 12_47_08-footprint editor no active library
2017-11-25 12_46_52-footprint editor no active library
2017-11-25 12_54_35-footprint editor no active library
2017-11-25 12_56_21-3d viewer
2017-11-25 12_56_06-3d viewer
2017-11-25 12_55_44-3d viewer
2017-11-25 12_54_55-footprint editor no active library
2017-11-25 12_54_35-footprint editor no active library

**Comment by poeschlr** [comment]
Much better. Thanks for the quick fix jan.

**Pull request merged**
