### PR TITLE
updated DFN-8-1EP_2x2mm_P0.5mm footprint according to newer KLC

### PR DESCRIPTION
**Pull request by Shackmeister**
datasheet:
http://www.onsemi.com/pub/Collateral/506CN.PDF

screenshot:
dfn8_2x2mm

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Shackmeister** [comment]
@poeschlr @SchrodingersGat 

would you mind if I rename this to include the Epad Info?
and in that case how should it be named?
DFN-8-1EP1.05x1.75_2x2mm_P0.5mm
DFN-8-1EP1.05x1.75mm_2x2mm_P0.5mm
DFN-8-1EP1.05x1.75_B2x2mm_P0.5mm
DFN-8-1EP1.05x1.75mm_B2x2mm_P0.5mm
DFN-8-1EP_2x2mm_EP1.05x1.75_P0.5mm
DFN-8-1EP_2x2mm_EP1.05x1.75mm_P0.5mm

**Comment by poeschlr** [comment]
None of the above ;)
`DFN-8-1EP_2x2mm_P0.5mm_EP1.05x1.75mm` (EP size, mask size, pad size, ... are part of the field called "Modifiers" in http://kicad-pcb.org/libraries/klc/F3.4/. I had it originally more detailed but it was decided to simplify the naming convention.)

**Comment by Shackmeister** [comment]
should we start adding the Epad to all?
I mainly wanted to add this because I wanted to add this:
https://github.com/KiCad/kicad-footprints/pull/260
as the same name with different Epad size, but decided to make it manufacturer specific

**Comment by poeschlr** [comment]
My original draft required adding them for all. My reasoning has been that there does not seem to be one standard across all manufacturers. This has been removed. (or has been forgotten to add to the final version.)
@SchrodingersGat can you enlighten us about this? (God dammit i can't find a phrasing that does not sound salty. Well my english is not the best today it seems.)

**Comment by SchrodingersGat** [comment]
It probably makes sense to be consistent and add them for all - you would need to ensure that all the footprint fields in `kicad-symbols` get updated accordingly.

**Comment by poeschlr** [comment]
If i have time this weekend i will look into this.

**Comment by Shackmeister** [comment]
can we possibly merge the footprint with the current name and then do the renaming at a later point?

**Comment by poeschlr** [comment]
Yes i will do the renaming stuff later.

**Pull request merged**
