### PR TITLE
add missing TDFN8 footprint for mcp2558 symbol

### PR DESCRIPTION
**Pull request by menschel**
grafik

referencing to #https://github.com/KiCad/kicad-symbols/pull/201

This is the first result from my footprint generator script.

https://github.com/menschel/kicad-footprint-generator

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing >> see footprint description
- [X] An example screenshot image is very helpful
- [ ] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate >> not available
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by Ratfink** [comment]
[KLC]: http://kicad-pcb.org/libraries/klc/ "KiCad Library Convention"
[G1.1]: http://kicad-pcb.org/libraries/klc/G1.1/ "Only standard characters are used for naming libraries and components"
[G1.2]: http://kicad-pcb.org/libraries/klc/G1.2/ "Each library is limited to 250 items"
[G1.3]: http://kicad-pcb.org/libraries/klc/G1.3/ "Libraries are organized by functionality"
[G1.4]: http://kicad-pcb.org/libraries/klc/G1.4/ "English language should be used throughout libraries"
[G1.5]: http://kicad-pcb.org/libraries/klc/G1.5/ "Plural naming is to be avoided"
[G1.6]: http://kicad-pcb.org/libraries/klc/G1.6/ "Capitalization conventions"
[G1.7]: http://kicad-pcb.org/libraries/klc/G1.7/ "Library files use Unix style line endings"
[G1.8]: http://kicad-pcb.org/libraries/klc/G1.8/ "Components can only contain features supported in latest stable release"
[G1.9]: http://kicad-pcb.org/libraries/klc/G1.9/ "Dimensional units"
[G2.1]: http://kicad-pcb.org/libraries/klc/G2.1/ "Defining generic and atomic parts"
[S1.1]: http://kicad-pcb.org/libraries/klc/S1.1/ "Symbol libraries should be categorized by function"
[S2.1]: http://kicad-pcb.org/libraries/klc/S2.1/ "General symbol naming guidelines"
[S2.2]: http://kicad-pcb.org/libraries/klc/S2.2/ "Non-functional variations in part number should be replaced with wildcard"
[S2.3]: http://kicad-pcb.org/libraries/klc/S2.3/ "Where atomic parts are available in multiple footprint options, a separate symbol must be drawn for each footprint"
[S3.1]: http://kicad-pcb.org/libraries/klc/S3.1/ "Origin is centered on the middle of the symbol"
[S3.2]: http://kicad-pcb.org/libraries/klc/S3.2/ "Text fields should use a common text size of 50mils"
[S3.3]: http://kicad-pcb.org/libraries/klc/S3.3/ "Symbol outline and fill requirements"
[S3.4]: http://kicad-pcb.org/libraries/klc/S3.4/ "Symbols with complex functionality may incorporate simple functional diagrams"
[S3.5]: http://kicad-pcb.org/libraries/klc/S3.5/ "Pin connection points must be placed outside of the symbol"
[S3.6]: http://kicad-pcb.org/libraries/klc/S3.6/ "Pin name position offset"
[S3.7]: http://kicad-pcb.org/libraries/klc/S3.7/ "Pin numbering for exposed pads"
[S3.8]: http://kicad-pcb.org/libraries/klc/S3.8/ "Multi unit symbols"
[S4.1]: http://kicad-pcb.org/libraries/klc/S4.1/ "General pin requirements"
[S4.2]: http://kicad-pcb.org/libraries/klc/S4.2/ "Pins should be grouped by function"
[S4.3]: http://kicad-pcb.org/libraries/klc/S4.3/ "Rules for pin stacking"
[S4.4]: http://kicad-pcb.org/libraries/klc/S4.4/ "Pin electrical type"
[S4.5]: http://kicad-pcb.org/libraries/klc/S4.5/ "Pins not connected on the footprint may be omitted from the symbol"
[S4.6]: http://kicad-pcb.org/libraries/klc/S4.6/ "Hidden pins"
[S4.7]: http://kicad-pcb.org/libraries/klc/S4.7/ "Active low pins should be designated using a bar above the symbol name"
[S5.1]: http://kicad-pcb.org/libraries/klc/S5.1/ "Symbols with a default footprint link to a valid footprint file"
[S5.2]: http://kicad-pcb.org/libraries/klc/S5.2/ "Footprint filters should match all appropriate footprints"
[S6.1]: http://kicad-pcb.org/libraries/klc/S6.1/ "Component Reference Designator (RefDes)"
[S6.2]: http://kicad-pcb.org/libraries/klc/S6.2/ "Component fields must be filled appropriately"
[S6.3]: http://kicad-pcb.org/libraries/klc/S6.3/ "Component metadata is added to symbol (and all aliases)"
[S7.1]: http://kicad-pcb.org/libraries/klc/S7.1/ "Power flag symbols"
[S7.2]: http://kicad-pcb.org/libraries/klc/S7.2/ "Graphical symbols"
[F1.1]: http://kicad-pcb.org/libraries/klc/F1.1/ "Footprint libraries are categorized by function"
[F1.2]: http://kicad-pcb.org/libraries/klc/F1.2/ "Connector footprint libraries"
[F2.1]: http://kicad-pcb.org/libraries/klc/F2.1/ "General footprint naming conventions"
[F2.2]: http://kicad-pcb.org/libraries/klc/F2.2/ "Footprint naming field prefixes"
[F2.3]: http://kicad-pcb.org/libraries/klc/F2.3/ "Manufacturer specific version of generic footprints"
[F2.4]: http://kicad-pcb.org/libraries/klc/F2.4/ "Footprint naming for non-standard pin numbering"
[F2.5]: http://kicad-pcb.org/libraries/klc/F2.5/ "Footprint naming conventions for specific components"
[F3.1]: http://kicad-pcb.org/libraries/klc/F3.1/ "SMD chip package naming conventions"
[F3.2]: http://kicad-pcb.org/libraries/klc/F3.2/ "Resistor naming conventions"
[F3.3]: http://kicad-pcb.org/libraries/klc/F3.3/ "Capacitor naming conventions"
[F3.4]: http://kicad-pcb.org/libraries/klc/F3.4/ "SMD IC package naming conventions"
[F3.5]: http://kicad-pcb.org/libraries/klc/F3.5/ "THT IC package naming conventions"
[F3.6]: http://kicad-pcb.org/libraries/klc/F3.6/ "Connector naming conventions"
[F3.7]: http://kicad-pcb.org/libraries/klc/F3.7/ "Fuse naming conventions"
[F4.1]: http://kicad-pcb.org/libraries/klc/F4.1/ "Datasheet recommendations take priority"
[F4.2]: http://kicad-pcb.org/libraries/klc/F4.2/ "Pin 1 should be located at the top left"
[F4.3]: http://kicad-pcb.org/libraries/klc/F4.3/ "Connected copper elements have the same pad number"
[F4.4]: http://kicad-pcb.org/libraries/klc/F4.4/ "Thermal pads"
[F4.5]: http://kicad-pcb.org/libraries/klc/F4.5/ "Specifying footprint keepout areas"
[F4.6]: http://kicad-pcb.org/libraries/klc/F4.6/ "Local clearance and settings should be set to zero"
[F5.1]: http://kicad-pcb.org/libraries/klc/F5.1/ "Silkscreen layer requirements"
[F5.2]: http://kicad-pcb.org/libraries/klc/F5.2/ "Fabrication layer requirements"
[F5.3]: http://kicad-pcb.org/libraries/klc/F5.3/ "Courtyard layer requirements"
[F6.1]: http://kicad-pcb.org/libraries/klc/F6.1/ "Footprint placement type must be set to surface mount"
[F6.2]: http://kicad-pcb.org/libraries/klc/F6.2/ "Footprint anchor should be placed in the middle of the component body"
[F6.3]: http://kicad-pcb.org/libraries/klc/F6.3/ "Pad requirements for SMD footprints"
[F7.1]: http://kicad-pcb.org/libraries/klc/F7.1/ "Footprint placement type must be set to Through Hole"
[F7.2]: http://kicad-pcb.org/libraries/klc/F7.2/ "Footprint anchor should placed at the location of Pin-1"
[F7.3]: http://kicad-pcb.org/libraries/klc/F7.3/ "Pin 1 should be rectangular, and other pads circular or oval"
[F7.4]: http://kicad-pcb.org/libraries/klc/F7.4/ "Pad requirements for THT footprints"
[F7.5]: http://kicad-pcb.org/libraries/klc/F7.5/ "Minimum annular ring width"
[F7.6]: http://kicad-pcb.org/libraries/klc/F7.6/ "Minimum hole diameter"
[F8.1]: http://kicad-pcb.org/libraries/klc/F8.1/ "Virtual components"
[F9.1]: http://kicad-pcb.org/libraries/klc/F9.1/ "Footprint meta-data is filled in as appropriate"
[F9.2]: http://kicad-pcb.org/libraries/klc/F9.2/ "Footprint properties are as default values unless otherwise required in datasheet"
[F9.3]: http://kicad-pcb.org/libraries/klc/F9.3/ "Footprint 3D model requirements"
[M1.1]: http://kicad-pcb.org/libraries/klc/M1.1/ "Models should be created by contributor"
[M1.2]: http://kicad-pcb.org/libraries/klc/M1.2/ "Manufacturer models should not be duplicated"
[M1.3]: http://kicad-pcb.org/libraries/klc/M1.3/ "Source files for 3D models should be supplied"
[M2.1]: http://kicad-pcb.org/libraries/klc/M2.1/ "Permitted 3D model file types"
[M2.2]: http://kicad-pcb.org/libraries/klc/M2.2/ "Model alignment and scaling"

Thanks for the contribution!  As it is, there are some issues with this footprint that should be addressed before it can be merged.

* The footprint should be named `TDFN-8-1EP_3x2mm_P0.5mm_EP1.80x1.65mm_ThermalVias` (scratch the `itch` in `Pitch`)
* Thermal pad issues ([F4.4])
  * The bottom copper for the thermal vias should be just one big pad that covers all the vias.  This can usually just be a copy of the EP on the B.Cu layer, with no soldermask.
  * Please add a non-`_ThermalVias` version of this footprint.
* Silkscreen issues ([F5.1])
  * The silkscreen lines need to be farther from the body and exposed copper.  KLC currently says to keep a 0.2 mm clearance from exposed copper, but we're in the process of relaxing that requirement to the silkscreen line width.  So, make sure there's no silkscreen within 0.12 mm of the exposed copper pads.
  * Please make the pin-1 mark extend just as far the copper pads.
* Fabrication layer issues ([F5.2])
  * The body outline should be 2×3 mm according to the datasheet, but it's only 1.5×2.9 mm right now.
  * The pin-1 chamfer is too small (should be 25% of the smaller body dimension, or 1 mm, whichever is smaller)
  * The text thickness of the F.Fab reference designator should be 15% of the width/height.
* The courtyard clearance is too small according to [F5.3].  It should be 0.25 mm from exposed copper and the chip body all around, rounded up to a 0.01 mm grid if necessary.  Right now, it looks like you didn't use the correct body size, and rounded down when you should have rounded up.
* According to [F6.3], paste coverage for the EP is too low (should be 50–80%, but right now you have ≈36.5%)

**Comment by menschel** [comment]
grafik


> The footprint should be named TDFN-8-1EP_3x2mm_P0.5mm_EP1.80x1.65mm_ThermalVias (scratch the itch in Pitch)

renamed

> Thermal pad issues (F4.4)
>    The bottom copper for the thermal vias should be just one big pad that covers all the vias. This can usually just be a copy of the EP on the B.Cu layer, with no soldermask.
>     Please add a non-_ThermalVias version of this footprint. That's the default footprint from the symbol PR you linked above, so it's really needed.

B.Cu pad redone, concerning the non-_ThermalVias version,
does it make sense to use the same paste pads as the _ThermalVias version or is it necessary make a separate collection of paste pads?

From manufacturer's point of view, reusing the paste pads saves one variant of the paste mask plate.

> Silkscreen issues (F5.1)
> 
>     The silkscreen lines need to be farther from the body and exposed copper. KLC currently says to keep a 0.2 mm clearance from exposed copper, but we're in the process of relaxing that requirement to the silkscreen line width. So, make sure there's no silkscreen within 0.12 mm of the exposed copper pads.
>     Please make the pin-1 mark extend just as far the copper pads.

added 0.1mm to the clearance and subtracted linewidth/2 from the pin-1 mark X pos

> Fabrication layer issues (F5.2)
> 
>     The body outline should be 2×3 mm according to the datasheet, but it's only 1.5×2.9 mm right now.
>     The pin-1 chamfer is too small (should be 25% of the smaller body dimension, or 1 mm, whichever is smaller)
>     The text thickness of the F.Fab reference designator should be 15% of the width/height.
changed to body dimensions instead of pad position calculation

> The courtyard clearance is too small according to F5.3. It should be 0.25 mm from exposed copper and the chip body all around, rounded up to a 0.01 mm grid if necessary. Right now, it looks like you didn't use the correct body size, and rounded down when you should have rounded up.

changed to body dimensions instead of pad position calculation

**Comment by Ratfink** [comment]
Thanks for making these changes!  Your generator is getting a lot better.  I still have some notes:

* The F.Fab RefDes thickness is set to `0.09999999999999999`.  I suggest you round that to two or three decimal places when formatting the text.  Also, if you're calculating 15% of 0.6 mm, shouldn't it be 0.09 mm?
* The courtyard clearance is still too small.  It needs to be calculated as a distance from both the pads and the body, and rounded up to a 0.01 mm grid.  Right now you have 0.245 mm clearance at the left and right (should be rounded up to the grid instead of down, making a 0.255 mm clearance), and 0.12 mm clearance at the top and bottom (should be 0.25 mm).
* The soldermask layers should be disabled for the thermal vias.
* Using the same stencil openings for the non-ThermalVias footprint makes sense, yes.  Just remove the thermal vias and the bottom pad, and of course change the name.
* Both footprint variants should use a 3D model filename without `_ThermalVias`.
* Ideally the silkscreen lines would have an offset of 0.11 or 0.12 mm (your choice!) from the F.Fab lines.  They're okay where they are though, if you prefer.

**Comment by Ratfink** [comment]
Overall, you're on the right track, though it looks like you made some simple goofs in this particular commit.

screenshot from 2018-04-09 13-46-10

* The courtyard clearance should be calculated from both the body *and* the pads.  As such, you have negative clearance on the left and right here (and of course, the courtyard shouldn't be bowtie-shaped 🙂).
* It looks like you only set the correct Y-position on the left side of the bottom silkscreen line.

We're aware of the Travis error for the missing soldermask on the thermal vias, it can be safely ignored.  That's a good plan w.r.t. adding the non-ThermalVias footprint.

**Comment by menschel** [comment]
Obviously too late at night.
Shame on me for not posting the screenshot and realizing this, but good thing is, I found that the right side pin order was wrong from the beginning.

Considering the generator concept, it was wrong to start with a line oriented concept as I had trouble getting the previous generated points from other layers. I'll go for a layer object oriented version next.

grafik

**Comment by Ratfink** [comment]
Looks great, thank you!  I don't see any further issues with these footprints, and I see you added the non-ThermalVias one as well, so I'll merge this now.

Also, shame on me too for not noticing the pin numbering problem!  Thanks for catching that.

**Pull request merged**
