### PR TITLE
Add 196-pin TFBGA, 0.75mm pitch, 0.32mm ball, 0.35 mm land for Microchip ATSAMA5D21

### PR DESCRIPTION
**Pull request by yankee14**
This footprint is a 196-pin, Thin Fine Pitch Ball Grid Array for a Microchip ATSAMA5D21 MPU--one of the cheapest Linux-capable microprocessor units on the market!

[Datashort](http://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-45165-Atmel-SMART-SAMA5D2_Flyer.pdf)
[Datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/SAMA5D2-Series-Data-Sheet-DS60001476C.pdf)

TFBGA-196_11 0x11 0mm_Layout14x14_P0 75mm_Ball0 32mm_Pad0

[Associated symbol PR](https://github.com/KiCad/kicad-symbols/pull/1866)
[Associated kicad-footprint-generator PR](https://github.com/pointhi/kicad-footprint-generator/pull/364)

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [ ] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
@yankee14 
First, please sign the CLA above. We can't accept any PR without this being signed.

Next, please generate the footprint using the scripts at https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Package_BGA. Even better, base it off of my branch at https://github.com/evanshultz/kicad-footprint-generator/tree/bga-update (PR at https://github.com/pointhi/kicad-footprint-generator/pull/356). We have written these scripts for consistency and to make reviewing easier, and for new contributions we want to use them.

Thank you!

**Comment by yankee14** [comment]
@evanshultz I think I have signed the CLA? It says "You have signed the CLA already but the status is still pending? Let us recheck it." I click on re-check it, but nothing happens.

Also, I will use your scripts and resubmit.

**Comment by evanshultz** [comment]
Thanks! Sometimes the CLA gets stuck, but it looks OK to me now, too.

**Comment by yankee14** [comment]
Okay, great!

I apologize, but I am not understanding how to use the [footprint generator scripts](https://github.com/evanshultz/kicad-footprint-generator/tree/bga-update). Is it supposed to act as a plugin to KiCad? I had to compile KiCad with KICAD_SCRIPTING_WXPYTHON=OFF, so I'm not sure I can use it. [The documentation](https://kicad-footprint-generator.readthedocs.io/en/latest/) seems to imply it is a plugin?

**Comment by evanshultz** [comment]
They are standalone Python scripts. Add in your parameters to the YAML file and then run the script from the console proving the YAML file as an argument. The documentation is limited to what's in the repo, barebones right now. I thought I had written something about this for a previous contributor but I can't find the post right now. Comment here if you get stuck.

**Comment by yankee14** [comment]
@evanshultz I understand the principle of what the generator is doing, but it's not clear to me how to use it. Can you possibly provide me a full example? I see many python scripts. Do I navigate down to the scripts/Packages/Package_BGA directory, and configure and execute from there? Or do I configure it there, and run one of the top level python scripts, like setup.py?

I'm sorry; I'm really bad at this sort of thing, not sure where I should start.

**Comment by poeschlr** [comment]
You run the python script that is found inside the bga directory. Add the part info to the bga.yaml file and use it as a parameter for the script (command: python3 bga.py bga.yaml) 

By the way while the core libs are tested with python 2 most of the scripts are not. So use python version 3. (python 2 is dead: https://pythonclock.org/

**Comment by yankee14** [comment]
Thanks, I got it to work. Final question: I roughly understand what is meant by the parameters `mask_margin` and `paste_margin`, but I am not sure how it is calculated. I see `mask_margin` on pretty much every other BGA footprint that already exists in the library. `paste_margin` is only on some of them. On the other footprints, `mask_margin` is usually very small, in the tens of micrometers. `paste_margin`, where it exists, is usually 0.000001.

**Comment by poeschlr** [comment]
the mask and paste stuff normally comes from some suggestion by the manufacturer. Typically this is either given directly in the datasheet as a suggested footprint or there is some application note handling either a series of components or a series of packages.

**Comment by yankee14** [comment]
Thank you @poeschlr. I understand that those values are normally given by the manufacturer like that, or that you can even go with IPC recommended values. I am just not sure how these values translate to the value the footprint generator scripts expect.

From what I can tell, `mask_margin` refers to how much the mask should be expanded past or retracted from the pad diameter.

For example, the datasheet for the footprint I'm trying to add gives:

**Table 67-12: 196-ball TFBGA Package information**

| Parameter | Value |
| ---- | ---- |
| Ball Land | 0.350 mm +/-0.05 |
| Nominal Ball Diameter| 0.3 mm |
| Solder Mask Opening | 0.275 mm +/-0.30 |
| Solder Mask Definition | SMD |
| Solder | OSP |

Since the suggested "Solder Mask Opening" is smaller than the "Ball Land", then shouldn't `mask_margin=-0.075`? As I said, I cannot tell from the other existing footprints that this is how this is calculated.

Thanks for your help; I'm sorry for asking for so much help on this.

**Comment by yankee14** [comment]
Screenshot of generated footprint, soldermask shown.
Screenshot of soldermask details. Notice how it is pulled back, as the manufacturer seems to have recommended.

new scap

mask

**Comment by evanshultz** [comment]
@yankee14 
Thanks! Please link the PR to update to the YAML file here so we can trace all the related changes.

**Comment by evanshultz** [comment]
Let's take a quick step back.

You've posted two datasheets: http://ww1.microchip.com/downloads/en/devicedoc/ds60001476b.pdf?expand=1#page=2536 and http://ww1.microchip.com/downloads/en/DeviceDoc/SAMA5D2-Series-Data-Sheet-DS60001476C.pdf#page=2596.

The latter is both newer and the one linked from the SAMA5D22 and D23 product pages. So let's go with that.

It calls out the 'BAB' package, which has a drawing at http://ww1.microchip.com/downloads/en/DeviceDoc/196B_TFBGA_11x11_[BAB]_C04-21141a.pdf (from https://www.microchip.com/quality/packaging-specifications?packageFamily=TFBGA). There is nothing about SMD pads or the mask diameter in the newer docs, and my belief may be that it is because NSMD pads are preferred now.

So in that case we have two choices:
1. We need to know if the package is using collapsible (most common) or non-collapsible solder balls. With 0.32mm balls, we can use the IPC recommendation for 0.3mm balls and select 0.25mm or 0.33mm pads, respectively.
1. Since the above is not the Microchip recommendation of 0.35mm pads, please prefix the footprint with `Microchip_` so this is clearly not a generic footprint using IPC rules.

Let me know if the above makes sense or if I've gotten something twisted.

**Comment by evanshultz** [comment]
OK, so you selected to go with the second option above. That's fine.

You have made manual changes to the footprint and not used the script to generate it, I believe. For example, I put the wrong page number in my post above (it should be 2956 and not 2596). But the script is correct! It appears both https://github.com/KiCad/kicad-footprints/pull/1604/commits/14e1f61ecb9a883d30dcf7124ce55b35adfb5fd1 and https://github.com/KiCad/kicad-footprints/pull/1604/commits/ffd5cc09e13bfb0f24a41f92f00a8a4f35d0f4a8 were not script-generated footprints. Please re-generate the footprint from the script and then let me look at this again. I believe the script cannot support custom footprint names, which is a limitation I hadn't considered before, but let's see if anything else is amiss. Because that limitation isn't your fault I'm willing to bend the rules a bit to help you get this in the library without requiring a script update. But let's sync things up first.

Also, the script PR is https://github.com/pointhi/kicad-footprint-generator/pull/381. (The old one was closed.)

**Comment by yankee14** [comment]
@evanshultz Thanks for the script PR link, I'll give it a shot

**Comment by yankee14** [comment]
Oops I copied it to the wrong path (wrong filename)

**Comment by yankee14** [comment]
The CI script is throwing a warning:

Violating F9.2

    Footprint properties should be left to default values.

    Attribute solder_mask_margin == -0.0375 != 0!

    Attribute solder_paste_margin == 1e-06 != 0!

Should I fix that?

**Comment by evanshultz** [comment]
Thanks for updating!

The F9.3 violation is just a warning and can be ignored since we know this is intentional here. The script doesn't have any way to know that and it's, in most cases, undesirable.

`Pad0.35mm_` should be removed from the footprint name because, since this is a Microchip-specific footprint, we don't need to capture that's not adhering to the IPC pad sizes.

**Comment by yankee14** [comment]
@evanshultz when you get a moment, could you let me know how I'm doing so far on this PR? Thanks!

**Comment by evanshultz** [comment]
@yankee14 
Sorry for the long delay. Everything looks OK to me now. Did you have any other concerns or are you ready for me to merge?

**Comment by yankee14** [comment]
@evanshultz no worries. I think it's okay. I'll create an issue if I run into problems when using it.

**Comment by evanshultz** [comment]
OK. Thanks!

**Pull request merged**
