### PR TITLE
Added QFN-56 5.9x5.9EP

### PR DESCRIPTION
**Pull request by awjlogan**
Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/00001734B.pdf, page 50
Screenshot: 
image

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [X] Provide a URL to a datasheet for the footprint(s) you are contributing
- [X] An example screenshot image is very helpful 
- [X] ~If there are matching symbol or 3D model pull requests, provide link(s) as appropriate~
- [X] Check the output of the Travis automated check scripts - fix any errors as required
- [X] ~Give a reason behind any intentional library convention rule violation.~

---

Be patient, we maintainers are volunteers with limited time and need to check your contribution against the datasheet. You can speed up the process by providing all the necessary information (see above). And you can speed up the process even more by providing a dimensioned drawing of your contribution. A tutorial on how to do that is found here: https://forum.kicad.info/t/how-to-check-footprint-correctness/9279 (This is optional!)

### CODE REVIEW

**Comment by cp-aquila** [comment]
This looks like it was created with a generator.
Can you please add a link to the generator PR?

**Comment by awjlogan** [comment]
> 
> 
> This looks like it was created with a generator.
> Can you please add a link to the generator PR?

Hi - I don't have a PR open for this, but did use a generator. Do you want me to put this into the YAML file in **kicad_footprint_generator**?

**Comment by cp-aquila** [comment]
yes please.

**Comment by awjlogan** [comment]
> 
> 
> yes please.

Link to kicad-footprint-generator PR: https://github.com/pointhi/kicad-footprint-generator/pull/530

**Comment by chschlue** [comment]
@awjlogan please re-push the updated footprint.

**Comment by awjlogan** [comment]
> @awjlogan please re-push the updated footprint.

Done, thank you @chschlue

**Pull request merged**
