### PR TITLE
Add DirectFET L6

### PR DESCRIPTION
**Pull request by chschlue**
Add DirectFET L6

https://www.infineon.com/dgdl/Infineon-AN-1035-ApplicationNotes-v29_01-EN.pdf?fileId=5546d462533600a40153559159020f76#page=42

DirectFET_L6

---

All contributions to the kicad library must follow the [KiCad library convention](http://kicad-pcb.org/libraries/klc/)

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model pull requests, provide link(s) as appropriate
- [x] Check the output of the Travis automated check scripts - fix any errors as required
- [x] Give a reason behind any intentional library convention rule violation.

### CODE REVIEW

**Comment by evanshultz** [comment]
1. Courtyard width is too big.

image

**Comment by evanshultz** [comment]
2. Didn't notice the excessive courtyard precision before.

Note that this type of thing is why scripting is nice and was my intent for the DirectFET footprints. One simple tweak to a script and a whole slew of new footprints can be made that don't need individual verification.

**Comment by chschlue** [comment]
It's not that I hate scripting, but:
a) There are 29 DirectFETs now and maybe 35 or so in the not-so-foreseeable future
b) You said yourself that full dimensions are next to impossible to come by (Infineon can't even seem to agree on dimensions for each series of package sizes)
c) Source and gate pads are irregular and would need to be hardcoded
d) I need some practice drawing footprints anyway (although these _do_ become repetitive and boring quickly)

**Comment by evanshultz** [comment]
Just one comment on your first item, and it's a tangent: Where are the 35 new DirectFET footprints coming from? I understood the DirectFET/CanPak was not going to be used in future products after the Infineon acquisition. AN-1035 only defines 26 so I thought that was all there would ever be. Are there ~35 more coming from another vendor? Or something else?

**Comment by chschlue** [comment]
I mostly made that one up. I didn't comb through every press release since the acquisition or anything. My point was just that the number of footprints probably won't be growing exponentially.

AN-1035 defines 29.
I had trouble counting, too. The TOC lists appendices 26, 27, 28 and then 26 again...

**Comment by chschlue** [comment]
@evanshultz ping

**Pull request merged**
