### PR TITLE
Added footprint for Bourns SRR1210A

### PR DESCRIPTION
**Pull request by johnfwhitmore**
Added footprint for the Bourns SRR1210A Inductor

https://www.bourns.com/docs/Product-Datasheets/SRR1210A.pdf

screenshot from 2018-06-22 22-45-33
screenshot from 2018-06-22 22-45-43

### CODE REVIEW

**Comment by johnfwhitmore** [comment]
I've pretty much copied another Bourns Inductor already in the library. This one is a tad smaller, which is why I passed Travis checks first time. First time for everything, but let me know what I should change to get this merged.

**Comment by johnfwhitmore** [comment]
Ping...
Sorry I've not had any response to this Pull Request. Wondering have I made a mess and failed to actually create the PR Correctly

**Comment by poeschlr** [comment]
Sorry for the late review. It seems this simply got forgotten while we prepared the lib for the v5 release.

The courtyard area should have a clearance of 0.25mm compared to the union of the area taken up by pads and body. So in this case you would need to increase the area in x direction.

The footprint looks fine otherwise. For reference the dimensioned drawing created from it:

screenshot from 2018-08-27 15-46-23

**Comment by johnfwhitmore** [comment]
Ping, sorry wonder what the status is with this contribution.

**Comment by Misca1234** [comment]
Thx

**Comment by johnfwhitmore** [comment]
Thank you kindly

**Pull request merged**
