### PR TITLE
Add WSON-8-1EP_3x3mm_P0.5mm_EP1.6x2.0mm

### PR DESCRIPTION
**Pull request by strombom**
WSON-8-1EP_3x3mm_P0.5mm_EP1.6x2.0mm

Datasheet: http://www.ti.com/lit/ml/mpds403/mpds403.pdf

image

image

image

3D Model: https://github.com/KiCad/kicad-packages3D/pull/242

------------

Thanks for creating a pull request to contribute to the KiCad libraries! To speed up integration of your PR, please check the following items:

- [x] Provide a URL to a datasheet for the footprint(s) you are contributing
- [x] An example screenshot image is very helpful 
- [x] If there are matching symbol or 3D model PRs, provide link(s) as appropriate
- [ ] Check the output of the Travis automated check scripts - fix any errors as required

### CODE REVIEW

**Comment by strombom** [comment]
Found an error, fixing.

**Comment by poeschlr** [comment]
The landing pattern looks good.
I would move the paste pads slightly inward such that there is a bit copper only on the outside to allow for paste alignment tolerances. (0.05mm should be enough)
70% paste coverage is also a bit high. I personally would aim for closer to 65% (Some manufacturers suggest 50 to 80 while other suggest 50 to 70.)

**Comment by strombom** [comment]
Is 60% ok? That could be obtained with 0,6 x 0,8mm paste pads.

image

**Comment by strombom** [comment]
Oh I only moved them 0,005 mm. Updating.

**Comment by poeschlr** [comment]
60 is ok as well.
Thanks for your contribution.

**Pull request merged**
