### PR TITLE
Added SOT-1123

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Teeny tiny transistor package:

Example datasheet: http://www.onsemi.com/pub/Collateral/NST3906F3-D.PDF

image

### CODE REVIEW

**Comment by Misca1234** [comment]
Hi

You have set the pad X-size to 0.35, it should be 0.34 ?
If you want you make the f.silk width to 0.1 (KLC F5.1:5)
Is not F.Silk a little close to the pads, < 0.2 mm (KLC F5.1:2) ?

**Comment by Misca1234** [comment]
@poeschlr 
So all is good with you then (if so i merge) ?

**Comment by poeschlr** [comment]
well other than he fab reference being a bit tiny (as mentioned above)

i also did not check any measurements.

**Comment by Misca1234** [comment]
@SchrodingersGat 
If you make the REF** slightly biggar as Rene suggest I can merge it

**Comment by SchrodingersGat** [comment]
hey thanks for the feedback guys, sorry it has taken ages to respond.

image

Sufficient?

**Comment by poeschlr** [comment]
I checked the footprint more closely. The copper pads are a bit too large and therefore the outside to outside dimension does not agree with the datasheet.
The courtyard is too far away on the right side.

The silk to copper clearance is a bit small (0.05mm) should be 0.1 (assuming silk line width is 0.1mm)

sot

**Comment by poeschlr** [comment]
@Misca1234 i will make a pull request fixing your merge that was a bit too early.

**Comment by Misca1234** [comment]
Ok, thx

**Pull request merged**
